### ISSUE TITLE
sealos add 新节点后，无法连接节点(ping connection refused)

### ISSUE THREAD

**Issue by maslow** [labring/sealos#1024]
**哪个命令或者组件**
sealos add --nodes 172.xx.xx.xx

**描述这个缺陷**
有两台阿里云 ECS 分别为 lafyun0, lafyun1，  在同一安全组：

第一次复现：lafyun1 as Master,  add lafyun0 as node ->  ping lafyun0 failed in lafyun1(refused)
第二次复现：lafyun0 as Master, add lafyun1 as node -> ping lafyun1 failed in lafyun0  ( refused)

1. 被 add 的机器，皆经过重做系统(Centos 7.9, kernetl 5.4)
2. sealos add 执行无报错，成功；执行前 master 可 ssh 连接 node；
3. 两台阿里云 ecs nameserver  改为了 8.8.8.8

**重现步骤（如果有需要可以附加图片）**

```bash
# 在主节点(Master)生成 ssh 密钥对
ssh-keygen -t rsa -b 4096

# 还需要本机给本机授权 SSH 访问：将 id_rsa.pub 拷到 authorized_keys 中

# 在各工作节点(Worker) 分别设置主节点的 public key，确保主节点可连接各工作节点

# 下载并安装sealos, sealos是个golang的二进制工具，直接下载拷贝到bin目录即可, release页面也可下载
wget -c https://sealyun-home.oss-cn-beijing.aliyuncs.com/sealos-4.0/latest/sealos-amd64 -O sealos && \
    chmod +x sealos && mv sealos /usr/bin

# 下载buildah
wget https://sealyun-home.oss-accelerate.aliyuncs.com/images/buildah.linux.amd64 --no-check-certificate -O buildah && chmod a+x buildah && mv buildah /usr/bin

# create k8s cluster
sealos run registry.cn-hongkong.aliyuncs.com/sealyun/oci-kubernetes:1.23.6 registry.cn-hongkong.aliyuncs.com/sealyun/oci-calico:v3.22.1  --masters 172.17.118.75

# install helm 
sealos run docker.io/fanux/helm:v3.8.1

# 要先去掉 taint ，不然 ingress-nginx 无法运行
kubectl taint node iz8vbgalm1f4e9ffn55w75z node-role.kubernetes.io/master-

# install ingress-nginx
sealos run docker.io/fanux/ingress-nginx:4.1.0
```

**运行环境**

- Docker版本:   containerd
- Kubernetes版本 : registry.cn-hongkong.aliyuncs.com/sealyun/oci-kubernetes:1.23.6 registry.cn-hongkong.aliyuncs.com/sealyun/oci-calico:v3.22.1
- sealos版本: {"gitVersion":"4.0.0-alpha.11","gitCommit":"322749c","buildDate":"2022-05-07T12:05:34Z","goVersion":"go1.16.15","compiler":"gc","platform":"linux/amd64"}
- 操作系统:  Linux iZ8vbgalm1f4e9ffn55w73Z 5.4.194-1.el7.elrepo.x86_64 #1 SMP Sat May 14 06:58:30 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
- 运行模式:  ecs 32g 8cpu
- 集群规模:   1master 
- 附加说明: istio,dashboard ...

**Comment by fanux** [comment]
由于使用external ip导致机器所有流量发送给了ingress
