### ISSUE TITLE
calico/node 起不来，进入容器内部无法访问

### ISSUE THREAD

**Issue by zLiangliangliang** [labring/sealos#1038]
**哪个命令或者组件**
eg. calico

**描述这个缺陷**

![1653013336(1)](https://user-images.githubusercontent.com/87415232/169436156-b3995621-7187-4fc5-92c6-0129caf2ea52.jpg)
![1653013562(1)](https://user-images.githubusercontent.com/87415232/169436346-c2046b41-05be-43cb-958d-0468914a5064.jpg)

**重现步骤（如果有需要可以附加图片）**
1. 
...

**测试结果**
1. 
2. 
3.

**期望结果**
1. 期望出现 xxx
   前置条件: xxx
   操作步骤:
   1. xxx
   2. xxx
   预期结果:
   1. xxx
   2. xxx

**运行环境**

- Kubernetes版本 :kube1.23.5.tar.gz

- 操作系统:  ubuntu 桌面版
- 运行模式:  
- 集群规模:    1master 4node
- 附加说明: istio,dashboard ...

**Comment by fanux** [comment]
如果 是公有云服务器 请把主机dns 改成nameserver 8.8.8.8再重启coredns

**Comment by zLiangliangliang** [comment]
> 如果 是公有云服务器 请把主机dns 改成nameserver 8.8.8.8再重启coredns
![image](https://user-images.githubusercontent.com/87415232/169465323-f111a55e-25f2-45a3-bc78-81fe3aecea02.png)
您看看下面的日志
[kube-system_calico-node-g9vdp_calico-node.log](https://github.com/labring/sealos/files/8736882/kube-system_calico-node-g9vdp_calico-node.log)
下面是网卡信息
![image](https://user-images.githubusercontent.com/87415232/169465662-2db83afb-ec59-4de9-9694-1b4e562f03bf.png)
![image](https://user-images.githubusercontent.com/87415232/169465697-f8315d20-11f1-487b-9b75-fcd570bd6bb6.png)

**Comment by huanghantao** [comment]
> 如果 是公有云服务器 请把主机dns 改成nameserver 8.8.8.8再重启coredns

想问下，为什么不能用公有云服务器的dns呢？我也遇到一样的问题，在宿主机可以，在pod里面不行，换成8.8.8.8后在pod里面是可以的。

**Comment by fanux** [comment]
因为我们选的pod地址段与公有云内网DNS冲突。 但是pod如果选择172 192这些又非常容易与私网冲突，这个问题不好处理，只能手动改改了
