### ISSUE TITLE
需求: 不支持非标准 ssh 端口

### ISSUE THREAD

**Issue by LiaoSirui** [labring/sealos#1039]
**哪个命令或者组件**
sealos init

**详细描述你的需求/任务**
详细描述你的需求和任务要求
1. 不支持非标准 ssh 端口吗（非 22 端口）

**Comment by cuisongliu** [comment]
> **哪个命令或者组件**
> 
> sealos init
> 
> 
> 
> **详细描述你的需求/任务**
> 
> 详细描述你的需求和任务要求
> 
> 1. 不支持非标准 ssh 端口吗（非 22 端口）
> 
> 
> 
> 

支持，看一下3.0的文档
