### ISSUE TITLE
Set default registry domain and namespace.

### ISSUE THREAD

**Issue by fanux** [labring/sealos#1052]
```
sealos run kubernetes:1.24.0 calico:v3.22.1 --masters 192.168.64.2,192.168.64.22,192.168.64.20 -p 123456
```

**Comment by SignorMercurio** [comment]
Proposal: Add a new command line flag `--default-registry` to `sealos run`, which has a default value. If the image name does not contain any `/`, prepend the default registry to it.

Would this be ok? If so, what should the default value for `--default-registry` be?

**Comment by cuisongliu** [comment]
/etc/containers/registries.conf 

```
unqualified-search-registries = ["localhost"]

[[registry]]
prefix = "localhost"
location = "registry.cn-hongkong.aliyuncs.com/labring"
```

**Comment by cuisongliu** [comment]
@fanux   set mirror is better?

**Comment by cuisongliu** [comment]
> Proposal: Add a new command line flag `--default-registry` to `sealos run`, which has a default value. If the image name does not contain any `/`, prepend the default registry to it.
> 
> Would this be ok? If so, what should the default value for `--default-registry` be?

need support `sealos run` and `sealos pull`

**Comment by SignorMercurio** [comment]
> /etc/containers/registries.conf
> 
> ```
> unqualified-search-registries = ["localhost"]
> 
> [[registry]]
> prefix = "localhost"
> location = "registry.cn-hongkong.aliyuncs.com/labring"
> ```

1. So I think we need to read the registry info from a config file `/etc/containers/registries.conf`?
2. What does `prefix` and `unqualified-search-registries` mean?
3. May we use YAML format instead?

**Comment by cuisongliu** [comment]
> > /etc/containers/registries.conf
> > ```
> > unqualified-search-registries = ["localhost"]
> > 
> > [[registry]]
> > prefix = "localhost"
> > location = "registry.cn-hongkong.aliyuncs.com/labring"
> > ```
> 
> 1. So I think we need to read the registry info from a config file `/etc/containers/registries.conf`?
> 2. What does `prefix` and `unqualified-search-registries` mean?
> 3. May we use YAML format instead?

this config is buildah config, link is https://github.com/containers/image/blob/main/docs/containers-registries.conf.5.md

**Comment by cuisongliu** [comment]
```
unqualified-search-registries = ["localhost"]

[[registry]]
prefix = "localhost"
location = "registry.cn-qingdao.aliyuncs.com/labring"
```

detail logs:
```
root@docker-ce:~# sealos pull calico:v3.22.1
Resolving "calico" using unqualified-search registries (/etc/containers/registries.conf)
Trying to pull localhost/calico:v3.22.1...
Getting image source signatures
Copying blob 931910ce95c4 done
Copying config 3acf7e89ba done
Writing manifest to image destination
Storing signatures
3acf7e89ba2d885a437f7d7e96915700e92419d2ac67dc6ed2b3208cd3753aea
root@docker-ce:~# sealos images
REPOSITORY                                                 TAG          IMAGE ID       CREATED         SIZE
localhost/calico                                           v3.22.1      3acf7e89ba2d   3 minutes ago   234 MB
localhost/coredns                                          v0.0.1       3546c465cd97   5 minutes ago   4.81 KB
```

**Comment by SignorMercurio** [comment]
I see that `sealos pull` can already read default registries from config(with `buildah.Pull()`), so now we need to make `sealos run` also support that. To do so, we also need to use buildah's ability to parse `/etc/containers/registries.conf` and retrieve the complete image name, is that correct?

**Comment by cuisongliu** [comment]
code need auto write file  `/etc/containers/registries.conf`

```
unqualified-search-registries = ["localhost"]


[[registry.mirror]]
location = "ghcr.io/labring"

[[registry.mirror]]
location = "registry.cn-qingdao.aliyuncs.com/labring"
```



https://github.com/labring/sealos/blob/485db0cc5873e1f64cbb63f78ac3c11e85a2891d/pkg/image/buildah.go#L25

append auto write registries.conf logic

**Comment by fanux** [comment]
> I see that `sealos pull` can already read default registries from config(with `buildah.Pull()`), so now we need to make `sealos run` also support that. To do so, we also need to use buildah's ability to parse `/etc/containers/registries.conf` and retrieve the complete image name, is that correct?

sealos integrates the code of buildah, so it can directly recognize this configuration file. 

So I think we just write the default config file.
