### ISSUE TITLE
sealos-add 命令执行结果与预期不符

### ISSUE THREAD

**Issue by wohuyuelong** [labring/sealos#1067]
**哪个命令或者组件**
sealos add -m 192.168.1.3 -n 192.168.1.9

**描述这个缺陷**
我之前用 sealos run 命令创建了一个集群，现在我想在这个集群中添加node，就是使用了sealos add 命令。
结果，我集群中，有部分node没有启动，命令直接执行失败；启动了所有node之后，再执行，执行成功，但是，这个命令中，没有-p参数 传递密码，怎么会ssh去新的node呢，果然，192.168.1.9的机器并没有安装成功。

**重现步骤（如果有需要可以附加图片）**
1. 用sealos run 。。。。。。 命令配置一个集群
2. 部分node关机
3. 在master上，用sealos add -m 192.168.1.3 -n 192.168.1.9 去添加node

**测试结果**
1. 命令执行失败，提示关机的node连接不上
2. 开启关闭的node，再次执行add命令，提示执行成功，但是实机上没有安装成功

**期望结果**
1. 期望出现 add 命令可以添加node
   前置条件: master上安装了4以上版本
   操作步骤:

   预期结果:
   1. add 命令中，还应该有 -p参数 指定ssh密码
   2. add 命令应该要可以成功在node机器上执行配置和安装，加入到集群中

**运行环境**
{"gitVersion":"4.0.0-alpha.12","gitCommit":"fc8bcfb","buildDate":"2022-05-26T10:51:12Z","goVersion":"go1.17.10","compiler":"gc","platform":"linux/amd64"}

**Comment by fanux** [comment]
sealos 会去找 .sealos下面的配置文件，第一次运行会创建之

**Comment by fanux** [comment]
报错信息是？

**Comment by fanux** [comment]
为什么关机node去add?  查看 .sealos下面的配置文件。

add 命令中，还应该有 -p参数 指定ssh密码 ：  不需要因为 ssh信息被保存到了配置文件中
add 命令应该要可以成功在node机器上执行配置和安装，加入到集群中 ：后面会出一个join命令，区别是add在master上执行，join在node上执行，因为有些情况下ssh不能使用等情况就需要用到join
