### ISSUE TITLE
sealos delete 把我的master都给删了

### ISSUE THREAD

**Issue by wohuyuelong** [labring/sealos#1068]
**哪个命令或者组件**
sealos delete -m 192.168.1.3 -n 192.168.1.9

**描述这个缺陷**
sealos delete --help中案例都跟了-m参数，我以为是一定要加这个参数的，结果把我的master都给删了，导致后面整个集群没法还原了

**重现步骤（如果有需要可以附加图片）**
1. 先用sealos run.....  创建一个集群
2. 然后，用sealos delete -m 192.168.1.3 -n 192.168.1.9 执行删除
3. 本意是只想删除一个node，结果，看了help中的案例都带了m参数
...

**测试结果**
1. 把master也删除了
2. 后续再用run 或add 根本没法还原了
4. 
5.

**期望结果**
修改 help中的帮助
delete命令参数master，要能有办法还原，现在没法还原

**运行环境**
{"gitVersion":"4.0.0-alpha.12","gitCommit":"485db0c","buildDate":"2022-05-27T11:33:44Z","goVersion":"go1.17.10","compiler":"gc","platform":"linux/amd64"}

**Comment by fanux** [comment]
确实应该有更好的帮助文档和提示信息。。。

**Comment by tanshilin1998** [comment]
maybe before some actual execute, we should tips some real result information

**Comment by cuisongliu** [comment]
> 确实应该有更好的帮助文档和提示信息。。。

sealos delete 时候是有一个二次确认提示用户是否删除节点的提示。

**Comment by fanux** [comment]
https://github.com/labring/sealos/blob/main/cmd/sealos/cmd/delete.go#L35 这里的help信息写详细一些
