### ISSUE TITLE
Support entrypoint in Dockerfile

### ISSUE THREAD

**Issue by fanux** [labring/sealos#1099]
entrypoint is operator friendly：

```
FROM scratch
COPY . .
ENTRYPOINT ["kubectl apply -f mysql-operator.yaml"]
CMD ["kubectl apply -f mysql-instance.yaml"]
```

So that I only need to overwrite the CMD when I want to use my own mysql config.

**Comment by gitccl** [comment]
Hi, I'd like to do this job.

**Comment by fanux** [comment]
@cuisongliu you can show some guide about how to provide this feature.

**Comment by fanux** [comment]
https://github.com/labring/sealos/blob/main/pkg/guest/guest.go
