### ISSUE TITLE
在 Proxmox VE 的 LXC 容器中安装 sealos 失败

### ISSUE THREAD

**Issue by s-leeq** [labring/sealos#1101]
**那个命令或者组件**
eg. sealos init , sealos install , kubernetes cni, docker  and so on 
`sealos init`

**描述你的问题**
我尝试在 PVE 的 LXC 容器中安装 sealos，但是在执行 `sealos init --passwd 'xxx' --master x.x.x.x --pkg-url /root/kube1.22.0.tar.gz --version v1.22.0` 后出现报错：
```
[preflight] The system verification failed. Printing the output from the verification:
KERNEL_VERSION: 5.15.35-1-pve
OS: Linux
CGROUPS_CPU: enabled
CGROUPS_CPUSET: enabled
CGROUPS_DEVICES: enabled
CGROUPS_FREEZER: enabled
CGROUPS_MEMORY: enabled
CGROUPS_PIDS: enabled
CGROUPS_HUGETLB: enabled
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR CRI]: container runtime is not running: output: time="2022-05-31T21:17:14+08:00" level=fatal msg="getting status of runtime: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
, error: exit status 1
        [ERROR SystemVerification]: failed to parse kernel config: unable to load kernel module: "configs", output: "modprobe: FATAL: Module configs not found in directory /lib/modules/5.15.35-1-pve\n", err: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
```

**你看到的一些参考资料**
eg. 文档的引用xxxx
我通过 [这个链接](https://kvaps.medium.com/run-kubernetes-in-lxc-container-f04aa94b6c9c) 中的指引对 LXC 容器进行了一些操作，但是并不会对结果产生影响。

**Comment by s-leeq** [comment]
补充一下，LXC 中的系统为 Debian 11。

报错与 #632 相同，但是那个 issue 貌似没有得到解决，所以我就单独又发了一个 issue。

**Comment by cuisongliu** [comment]
Module configs not found in directory /lib/modules/5.15.35-1-pve

**Comment by cuisongliu** [comment]
> 已解决，但是方案不太优雅：
> 
> 将宿主机中的 `/lib/modules/$(uname -r)/kernel/lib/.config` 文件复制进 LXC 容器中的同名文件夹中（或者直接在宿主机中将此文件挂载入容器中并设置为只读）。
> 
> [参考资料](https://github.com/kubernetes-sigs/kind/issues/61)
> 
> ps: 链接里的 issue 中也提到了这个报错是可以被忽略的。所以希望开发者研究一下，看看是否可以有更优雅的解决方案，谢谢！

这看起来好像是lxc对系统的有些类库的支持度不高，推荐可以使用multipass

**Comment by bigcat133** [comment]
> 已解决，但是方案不太优雅：
> 
> 将宿主机中的 `/lib/modules/$(uname -r)/kernel/lib/.config` 文件复制进 LXC 容器中的同名文件夹中（或者直接在宿主机中将此文件挂载入容器中并设置为只读）。
> 
> [参考资料](https://github.com/kubernetes-sigs/kind/issues/61)
> 
> ps: 链接里的 issue 中也提到了这个报错是可以被忽略的。所以希望开发者研究一下，看看是否可以有更优雅的解决方案，谢谢！
我用的是pve7.3-3，内核版本是5.15.74-1-pve，在这个环境中没有发现对应位置的.config
