### ISSUE TITLE
请教一个问题，4.0版本 好多自定义的参数都没了，是在重构吗，后面还会加回去吗？

### ISSUE THREAD

**Issue by gotosre** [labring/sealos#1106]
请教一个问题，4.0版本 好多自定义的参数都没了，是在重构吗，后面还会加回去吗？

**Comment by cuisongliu** [comment]
> 请教一个问题，4.0版本 好多自定义的参数都没了，是在重构吗，后面还会加回去吗？

是的。更优雅的方式，基本之前的东西都在，只是使用方式变了。你有什么用的需求可以提出来
