### ISSUE TITLE
需求: 希望sealos支持ssh 代理

### ISSUE THREAD

**Issue by songdi676** [labring/sealos#1113]
**哪个命令或者组件**
eg.   sealos run

**详细描述你的需求/任务**
执行 sealos run指令时，执行机和 masterip 、 nodeip网络不互通，需要使用代理才能执行指令

**是否有解决方案，如果有请详述**
通过pkg/utils/ssh/connect.go 添加代理是否可以？

**Comment by cuisongliu** [comment]
> **哪个命令或者组件** eg. sealos run
> 
> **详细描述你的需求/任务** 执行 sealos run指令时，执行机和 masterip 、 nodeip网络不互通，需要使用代理才能执行指令
> 
> **是否有解决方案，如果有请详述** 通过pkg/utils/ssh/connect.go 添加代理是否可以？

join 的方式可能比代理更优雅一些。

**Comment by songdi676** [comment]
感谢回复，我不太理解如何使用join 的方式实现这种网络穿透，我是一名java开发者，go的生态不是很熟悉。
可以详细说一下吗？

**Comment by cuisongliu** [comment]
> 感谢回复，我不太理解如何使用join 的方式实现这种网络穿透，我是一名java开发者，go的生态不是很熟悉。
> 可以详细说一下吗？

就想kubeadm join node 一样，在node节点上直接join到master上 这样更合理一些。用的方式可能不会用ssh去执行了，直接调用openapi实现

**Comment by fanux** [comment]
join 的能力已经在 roadmap 中，这个 issue 先关闭了哈
