### ISSUE TITLE
问题: x509: certificate is valid for 127.0.0.1, 10.96.0.1, 192.168.0.118, 10.103.97.2, not 106.74.24.250

### ISSUE THREAD

**Issue by houjibofa2050** [labring/sealos#1128]
**描述你的问题**
x509: certificate is valid for 127.0.0.1, 10.96.0.1, 192.168.0.118, 10.103.97.2, not 106.*.*.250

我使用内网192.168.0.118部署k8s,我用golang的k8s的客户端使用外网ip  106.*.*.250
访问报证书ip无效，这种情况是不是只能使用公网ip 做部署，才能用公网ip做访问。不能使用内网ip部署

**Comment by zhangguanzhang** [comment]
有个参数--cert 还是啥，你可以部署的时候添加，也就是certSAN的值追加

**Comment by ihipop** [comment]
@zhangguanzhang  请问是哪个参数？新版只有apply方法 没看到这个参数啊？

**Comment by ihipop** [comment]
https://blog.scottlowe.org/2019/07/30/adding-a-name-to-kubernetes-api-server-certificate/ 按照这个方法成功添加了新的地址到san列表
