### ISSUE TITLE
sealos 3指定了svc和pod的CIDR后集群安装失败

### ISSUE THREAD

**Issue by si3041242** [labring/sealos#1145]
之前安装没有问题，这次翻车了，ubuntu的内核版本和之前稍有不同，之前用的内核版本是5.4.0，现在aws提供的ami版本是5.13。指定svc和pod cidr 安装后只能看到一台master节点，不指定可以看到所有master节点，但是svc节点使用了生产网络的cidr，不符合预期，帮忙看下需要怎么搞，感谢
生产部署，master配置4C8G，排除配置问题，我在将内核版本从5.13修改为5.4后报错依旧
系统版本：ubuntu20.04  
内核版本：5.13.0-1022-aws
sealos version：v3.3.8
k8s version：v1.18.8

# 安装命令
sealos init --master 10.196.64.100 --master 10.196.64.101 --master 10.196.64.102 \
    --pkg-url /root/kube1.18.8.tar.gz \
    --pk /root/.ssh/id_rsa \
    --podcidr 10.20.0.0/16 \
    --svccidr 192.168.110.0/22 \
    --version v1.18.8
# 安装中报错，安装完成后 kubectl get node只能看到一台master节点
21:09:36 [INFO] [ssh.go:50] [10.196.64.101:22] modprobe: FATAL: Module nf_conntrack_ipv4 not found in directory /lib/modules/5.13.0-1022-aws
10:05:25 [INFO] [ssh.go:65] [10.196.64.102:22] error execution phase control-plane-prepare/certs: error creating PKI assets: failed to write or validate certificate "apiserver": certificate apiserver is invalid: x509: certificate is valid for 10.103.97.2, 192.168.110.1, 10.196.64.100, 10.196.64.101, 127.0.0.1, 10.196.64.102, not 192.168.108.1
10:05:25 [INFO] [ssh.go:65] [10.196.64.102:22] To see the stack trace of this error execute with --v=5 or higher
10:05:25 [DEBG] [ssh.go:72] [10.196.64.102:22] sed "s/10.196.64.100 apiserver.cluster.local/10.196.64.102 apiserver.cluster.local/g" -i /etc/hosts
10:05:25 [INFO] [ssh.go:65] [10.196.64.101:22] error execution phase control-plane-prepare/certs: error creating PKI assets: failed to write or validate certificate "apiserver": certificate apiserver is invalid: x509: certificate is valid for 127.0.0.1, 10.196.64.100, 10.196.64.101, 10.196.64.102, 10.103.97.2, 192.168.110.1, not 192.168.108.1
不指定svc和pod cidr安装后可以看到加入集群的所有master节点（测试多次结果都如此）

**Comment by si3041242** [comment]
sealos init的报错信息
![image](https://user-images.githubusercontent.com/41499864/174936246-1e0412e0-43d3-4ffc-af1f-b83f695601e3.png)
安装后kubectl get node 没有出现在结果中的master，报错信息如下，内核版本降低后报错还一样。之前我们有一套生产环境内核版本也是5.4，k8s软件版本也是1.18.8
![image](https://user-images.githubusercontent.com/41499864/174936474-1140b9e5-4087-4ae0-bab8-c2b951efdc1a.png)

**Comment by si3041242** [comment]
apiserver 的证书写入有问题，这次我换了和测试环境一样的k8s离线包和sealos，测试环境是腾讯云，生产是aws
帮忙看下哪里可能存在问题。安全组  机器配置  这些都排查过了
![image](https://user-images.githubusercontent.com/41499864/174980914-96428b3f-8f56-4336-b3ce-aee4bfde7504.png)

**Comment by gotosre** [comment]
这位兄台，报错很明显了，证书签发没有包括192.168.108.1，为啥没有包括呢？您检查一下 service cidr 192.168.110.0/22。。。这是合理的划分吗？这么划分，的ip起止是：192.168.108.1 -> 192.168.111.254，apiserver的service cluster ip会用第一个，也就是192.168.108.1，而不是您意淫的192.168.110.1。

修复方法，把service cidr搞正确了，应该就行了

**Comment by zhangguanzhang** [comment]
你的CIDR错了，22位掩码算的话第一个IP并不是你想的 192.168.108.1，可以找个在线CIDR算下第一个IP
