### ISSUE TITLE
Feature:  DEB&RPM release

### ISSUE THREAD

**Issue by cuisongliu** [labring/sealos#1153]
When we publish, we automatically package deb and RPM packages to https://manage.fury.io.

Leave your email and I will add you to the labring organisation of https://manage.fury.io.

**Comment by gitccl** [comment]
Isn't this feature already implemented?

**Comment by cuisongliu** [comment]
https://goreleaser.com/customization/fury/

**Comment by cuisongliu** [comment]
> @cuisongliu I think we need GoReleaser Pro for this feature.

using cmd exec it ?
