### ISSUE TITLE
Feature: sealos join

### ISSUE THREAD

**Issue by cuisongliu** [labring/sealos#1154]
In some scenarios, the ssh protocol cannot be used or connected from the master to node, so we need to design the "sealos join" requirements.

```
sealos  join --master x.x.x.x --node x.x.x.x
```

**Comment by xiao-jay** [comment]
explain：sealos add is master add node，but sealos join is node join master

**Comment by mond77** [comment]
how does the feature go on?

**Comment by cuisongliu** [comment]
Reopen

**Comment by ghostloda** [comment]
join命令的设计是在待加入节点执行的吗？
