### ISSUE TITLE
Optimisation: copy linux_amd64.yml to scripts 

### ISSUE THREAD

**Issue by cuisongliu** [labring/sealos#1162]
[linux_amd64.yml](https://github.com/labring/sealos/blob/main/linux_amd64.yml)  move to scripts dir

**Comment by gebilxs** [comment]
Where does the script need to be changed?

**Comment by ysicing** [comment]
#1167
Whether the goRelease configuration file also needs to be modified？
https://goreleaser.com/customization/nfpm/

**Comment by cuisongliu** [comment]
> #1167
> Whether the goRelease configuration file also needs to be modified？
> https://goreleaser.com/customization/nfpm/

#1153   This issue is tracking this problem. If you are interested, you can commit a PR.
