### ISSUE TITLE
sealos 4   add   nodes  失败

### ISSUE THREAD

**Issue by 15996936252** [labring/sealos#1168]
![-7ad596a0de6feda9](https://user-images.githubusercontent.com/80530848/175525253-52f23fc4-7713-404a-82ec-cbd7c100f091.png)
- Kubernetes version: eg.kube1.24
- Sealos version: v4
- Operating system: eg. centos7.7
- Cluster size: eg 1 master, 1 node
- sealos  add  --nodes  x.x.x.x失败
- 提示bash:第0行:cd :/ var/lib/ sealos/ data/ default/ rootfs/scripts  没有那个文件或目录。

**Comment by 15996936252** [comment]
![586f0a8e9974941a](https://user-images.githubusercontent.com/80530848/175527009-e7abc991-8101-44a5-a5db-276e62c01df3.png)
![-449d16378ebba6c8](https://user-images.githubusercontent.com/80530848/175527023-94e5e28f-8e81-4dca-a263-de44ee7861d4.png)
自己手动创建/ var/lib/ sealos/ data/ default/ rootfs/scripts目录后再add，没有提示错误，但是添加node失败。

**Comment by cuisongliu** [comment]
![image](https://user-images.githubusercontent.com/4150905/175563472-c47b9814-c649-4330-946d-64326cb425a0.png)
看一下你的clusterfile应该是已经存在这个IP了

**Comment by cuisongliu** [comment]
你是在master1上执行的sealos么？

**Comment by 15996936252** [comment]
> 你是在master1上执行的sealos么？

是的，在master1上执行的

**Comment by cuisongliu** [comment]
> > 你是在master1上执行的sealos么？
> 
> 我在master1的host里添加了node2的ip，不知道有没有影响。



贴一下clusterfile?

**Comment by 15996936252** [comment]
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  creationTimestamp: "2022-06-24T09:44:56Z"
  name: default
spec:
  hosts:
  - ips:
    - 192.168.200.101:22
    - 192.168.200.102:22
    roles:
    - master
    - amd64
  - ips:
    - 192.168.200.104:22:22
    - 192.168.200.105:22:22
    roles:
    - node
    - amd64
  image:
  - labring/kubernetes:v1.24.0
  - labring/calico:v3.22.1
  ssh:
    passwd: root
    pk: /root/.ssh/id_rsa
    port: 22
    user: root
status:
  mounts:
  - env:
      criData: /var/lib/containerd
      registryConfig: /etc/registry
      registryData: /var/lib/registry
      registryDomain: sealos.hub
      registryPassword: passw0rd
      registryPort: "5000"
      registryUsername: admin
    imageName: labring/kubernetes:v1.24.0
    labels:
      auth: auth.sh
      check: check.sh
      clean: clean.sh $criData
      clean-registry: clean-registry.sh $registryData $registryConfig
      image: ghcr.io/labring/lvscare:v1.1.3-beta.2
      init: init.sh $criData $registryDomain $registryPort $registryUsername $registryPassword
      init-registry: init-registry.sh $registryPort $registryData $registryConfig
      io.buildah.version: 1.25.0-dev
      sealos.io.type: rootfs
      version: v1.24.0
    mountPoint: /var/lib/containers/storage/overlay/9c404d3a81304fc6990fe6c25a70032fdff62c1e6df0805a5aa351445379e188/merged
    name: default-61zzut9s
    type: rootfs
  - cmd:
    - kubectl apply -f manifests/tigera-operator.yaml
    - kubectl apply -f manifests/calico.yaml
    imageName: labring/calico:v3.22.1
    labels:
      io.buildah.version: 1.25.0-dev
    mountPoint: /var/lib/containers/storage/overlay/7d3f3cfbe3d7c40b19faea6fb0febae22e833db0515ba2c56b4004a08c2285a2/merged
    name: default-aeeczvlu
    type: application


这个是add前的

**Comment by 15996936252** [comment]
[root@master1 ~]# sealos add --nodes 192.168.200.106
2022-06-25 16:39:19 [INFO] start to install app in this cluster
2022-06-25 16:39:19 [INFO] succeeded install app in this cluster: no change apps
2022-06-25 16:39:19 [INFO] start to scale this cluster
2022-06-25 16:39:19 [INFO] checker:hostname [192.168.200.101:22 192.168.200.106:22]
2022-06-25 16:39:20 [INFO] checker:timeSync [192.168.200.101:22 192.168.200.106:22]
192.168.200.106:22: bash: 第 0 行:cd: /var/lib/sealos/data/default/rootfs/scripts: 没有那个文件或目录
Error: failed to execute command(registryData=(/var/lib/registry) registryDomain=(sealos.hub) registryPassword=(passw0rd) registryPort=(5000) registryUsername=(admin) criData=(/var/lib/containerd) registryConfig=(/etc/registry) && cd /var/lib/sealos/data/default/rootfs/scripts && bash check.sh) on host(192.168.200.106:22): output(bash: 第 0 行:cd: /var/lib/sealos/data/default/rootfs/scripts: 没有那个文件或目录), error(Process exited with status 1)
Usage:
  sealos add [flags]

Examples:

add to nodes :
        sealos add --nodes x.x.x.x

add to default cluster: 
        sealos add --masters x.x.x.x --nodes x.x.x.x
        sealos add --masters x.x.x.x-x.x.x.y --nodes x.x.x.x-x.x.x.y


Flags:
  -c, --cluster string   delete a kubernetes cluster with cluster name (default "default")
  -h, --help             help for add
  -m, --masters string   reduce Count or IPList to masters
  -n, --nodes string     reduce Count or IPList to nodes

Global Flags:
      --clusterRootDir string   cluster root directory (default "/var/lib/sealos")
      --debug                   enable debug logger

failed to execute command(registryData=(/var/lib/registry) registryDomain=(sealos.hub) registryPassword=(passw0rd) registryPort=(5000) registryUsername=(admin) criData=(/var/lib/containerd) registryConfig=(/etc/registry) && cd /var/lib/sealos/data/default/rootfs/scripts && bash check.sh) on host(192.168.200.106:22): output(bash: 第 0 行:cd: /var/lib/sealos/data/default/rootfs/scripts: 没有那个文件或目录), error(Process exited with status 1)

第一次add出现这个报错

**Comment by 15996936252** [comment]
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  creationTimestamp: "2022-06-24T09:44:56Z"
  name: default
spec:
  hosts:
  - ips:
    - 192.168.200.101:22
    - 192.168.200.102:22
    roles:
    - master
    - amd64
  - ips:
    - 192.168.200.104:22
    - 192.168.200.105:22
    roles:
    - node
    - amd64
  - ips:
    - 192.168.200.106:22
    roles:
    - node
    - amd64
  image:
  - labring/kubernetes:v1.24.0
  - labring/calico:v3.22.1
  ssh:
    passwd: root
    pk: /root/.ssh/id_rsa
    port: 22
    user: root
status:
  mounts:
  - env:
      criData: /var/lib/containerd
      registryConfig: /etc/registry
      registryData: /var/lib/registry
      registryDomain: sealos.hub
      registryPassword: passw0rd
      registryPort: "5000"
      registryUsername: admin
    imageName: labring/kubernetes:v1.24.0
    labels:
      auth: auth.sh
      check: check.sh
      clean: clean.sh $criData
      clean-registry: clean-registry.sh $registryData $registryConfig
      image: ghcr.io/labring/lvscare:v1.1.3-beta.2
      init: init.sh $criData $registryDomain $registryPort $registryUsername $registryPassword
      init-registry: init-registry.sh $registryPort $registryData $registryConfig
      io.buildah.version: 1.25.0-dev
      sealos.io.type: rootfs
      version: v1.24.0
    mountPoint: /var/lib/containers/storage/overlay/9c404d3a81304fc6990fe6c25a70032fdff62c1e6df0805a5aa351445379e188/merged
    name: default-61zzut9s
    type: rootfs
  - cmd:
    - kubectl apply -f manifests/tigera-operator.yaml
    - kubectl apply -f manifests/calico.yaml
    imageName: labring/calico:v3.22.1
    labels:
      io.buildah.version: 1.25.0-dev
    mountPoint: /var/lib/containers/storage/overlay/7d3f3cfbe3d7c40b19faea6fb0febae22e833db0515ba2c56b4004a08c2285a2/merged
    name: default-aeeczvlu
    type: application


add以后的

**Comment by 15996936252** [comment]
[root@master1 ~]# sealos add --nodes 192.168.200.106
2022-06-25 16:41:38 [INFO] start to install app in this cluster
2022-06-25 16:41:38 [INFO] succeeded install app in this cluster: no change apps
2022-06-25 16:41:38 [INFO] start to scale this cluster
2022-06-25 16:41:38 [INFO] succeeded in scaling this cluster: no change nodes
2022-06-25 16:41:38 [INFO] 
      ___           ___           ___           ___       ___           ___     
     /\  \         /\  \         /\  \         /\__\     /\  \         /\  \    
    /::\  \       /::\  \       /::\  \       /:/  /    /::\  \       /::\  \   
   /:/\ \  \     /:/\:\  \     /:/\:\  \     /:/  /    /:/\:\  \     /:/\ \  \  
  _\:\~\ \  \   /::\~\:\  \   /::\~\:\  \   /:/  /    /:/  \:\  \   _\:\~\ \  \ 
 /\ \:\ \ \__\ /:/\:\ \:\__\ /:/\:\ \:\__\ /:/__/    /:/__/ \:\__\ /\ \:\ \ \__\
 \:\ \:\ \/__/ \:\~\:\ \/__/ \/__\:\/:/  / \:\  \    \:\  \ /:/  / \:\ \:\ \/__/
  \:\ \:\__\    \:\ \:\__\        \::/  /   \:\  \    \:\  /:/  /   \:\ \:\__\  
   \:\/:/  /     \:\ \/__/        /:/  /     \:\  \    \:\/:/  /     \:\/:/  /  
    \::/  /       \:\__\         /:/  /       \:\__\    \::/  /       \::/  /   
     \/__/         \/__/         \/__/         \/__/     \/__/         \/__/  

                  Website :https://www.sealos.io/
                  Address :github.com/labring/sealos

[root@master1 ~]# kubectl get nodes
NAME      STATUS   ROLES           AGE   VERSION
master1   Ready    control-plane   22h   v1.24.0
master2   Ready    control-plane   22h   v1.24.0
node1     Ready    <none>          22h   v1.24.0
node2     Ready    <none>          22h   v1.24.0
[root@master1 ~]# 


又add一次，没有报错，但是没有增加node3

**Comment by cuisongliu** [comment]
> [root@master1 ~]# sealos add --nodes 192.168.200.106
> 
> 2022-06-25 16:39:19 [INFO] start to install app in this cluster
> 
> 2022-06-25 16:39:19 [INFO] succeeded install app in this cluster: no change apps
> 
> 2022-06-25 16:39:19 [INFO] start to scale this cluster
> 
> 2022-06-25 16:39:19 [INFO] checker:hostname [192.168.200.101:22 192.168.200.106:22]
> 
> 2022-06-25 16:39:20 [INFO] checker:timeSync [192.168.200.101:22 192.168.200.106:22]
> 
> 192.168.200.106:22: bash: 第 0 行:cd: /var/lib/sealos/data/default/rootfs/scripts: 没有那个文件或目录
> 
> Error: failed to execute command(registryData=(/var/lib/registry) registryDomain=(sealos.hub) registryPassword=(passw0rd) registryPort=(5000) registryUsername=(admin) criData=(/var/lib/containerd) registryConfig=(/etc/registry) && cd /var/lib/sealos/data/default/rootfs/scripts && bash check.sh) on host(192.168.200.106:22): output(bash: 第 0 行:cd: /var/lib/sealos/data/default/rootfs/scripts: 没有那个文件或目录), error(Process exited with status 1)
> 
> Usage:
> 
>   sealos add [flags]
> 
> 
> 
> Examples:
> 
> 
> 
> add to nodes :
> 
>         sealos add --nodes x.x.x.x
> 
> 
> 
> add to default cluster: 
> 
>         sealos add --masters x.x.x.x --nodes x.x.x.x
> 
>         sealos add --masters x.x.x.x-x.x.x.y --nodes x.x.x.x-x.x.x.y
> 
> 
> 
> 
> 
> Flags:
> 
>   -c, --cluster string   delete a kubernetes cluster with cluster name (default "default")
> 
>   -h, --help             help for add
> 
>   -m, --masters string   reduce Count or IPList to masters
> 
>   -n, --nodes string     reduce Count or IPList to nodes
> 
> 
> 
> Global Flags:
> 
>       --clusterRootDir string   cluster root directory (default "/var/lib/sealos")
> 
>       --debug                   enable debug logger
> 
> 
> 
> failed to execute command(registryData=(/var/lib/registry) registryDomain=(sealos.hub) registryPassword=(passw0rd) registryPort=(5000) registryUsername=(admin) criData=(/var/lib/containerd) registryConfig=(/etc/registry) && cd /var/lib/sealos/data/default/rootfs/scripts && bash check.sh) on host(192.168.200.106:22): output(bash: 第 0 行:cd: /var/lib/sealos/data/default/rootfs/scripts: 没有那个文件或目录), error(Process exited with status 1)
> 
> 
> 
> 第一次add出现这个报错

你add 后看一下/var/lib/sealos/data/default/rootfs/有目录么

**Comment by 15996936252** [comment]
add以后node3没有/var/lib/sealos/data/default/rootfs/ 这个目录

**Comment by 15996936252** [comment]
192.168.200.106:22: bash: 第 0 行:cd: /var/lib/sealos/data/default/rootfs/scripts: 没有那个文件或目录
Error: failed to execute command(cd /var/lib/sealos/data/default/rootfs/scripts && bash check.sh) on host(192.168.200.106:22): output(bash: 第 0 行:cd: /var/lib/sealos/data/default/rootfs/scripts: 没有那个文件或目录), error(Process exited with status 1)

报错有这个提示，node3确实没自动创建那个目录

**Comment by cuisongliu** [comment]
你sealos版本是多少？

**Comment by 15996936252** [comment]
> 你sealos版本是多少？

是4.0的最新版，直接用github里的命令安装的。

**Comment by ke00ke** [comment]
我也碰到了添加节点的问题
[root@slave1 ~]# sealos add --nodes 192.168.101.99
Error: not found `master` role from file
Usage:
  sealos add [flags]

Examples:

add to nodes :
        sealos add --nodes x.x.x.x

add to default cluster: 
        sealos add --masters x.x.x.x --nodes x.x.x.x
        sealos add --masters x.x.x.x-x.x.x.y --nodes x.x.x.x-x.x.x.y


Flags:
  -c, --cluster string   delete a kubernetes cluster with cluster name (default "default")
  -h, --help             help for add
  -m, --masters string   reduce Count or IPList to masters
  -n, --nodes string     reduce Count or IPList to nodes

Global Flags:
      --clusterRootDir string   cluster root directory (default "/var/lib/sealos")
      --debug                   enable debug logger

not found `master` role from file

**Comment by ke00ke** [comment]
我也碰到了添加节点的问题 **not found master role from file**
[root@slave1 ~]# sealos add --nodes 192.168.101.99
Error: not found master role from file
Usage:
sealos add [flags]

Examples:

add to nodes :
sealos add --nodes x.x.x.x

add to default cluster:
sealos add --masters x.x.x.x --nodes x.x.x.x
sealos add --masters x.x.x.x-x.x.x.y --nodes x.x.x.x-x.x.x.y

Flags:
-c, --cluster string delete a kubernetes cluster with cluster name (default "default")
-h, --help help for add
-m, --masters string reduce Count or IPList to masters
-n, --nodes string reduce Count or IPList to nodes

Global Flags:
--clusterRootDir string cluster root directory (default "/var/lib/sealos")
--debug enable debug logger

not found master role from file

**Comment by fanux** [comment]
看下 Clusterfile~

**Comment by cuisongliu** [comment]
下载最新的镜像,看样子是镜像问题
