### ISSUE TITLE
sealos desktop oauth2 login

### ISSUE THREAD

**Issue by fanux** [labring/sealos#1173]
https://github.com/labring/fist/tree/master/auth

desktop -> github login -> create jwt token -> generate kubeconfig and save it

**Comment by Abingcbc** [comment]
@fanux

**Comment by cuisongliu** [comment]
Is it better to use dex docking?

**Comment by Abingcbc** [comment]
@cuisongliu Could you provide a link to its repo or official page? thx! ❤️

**Comment by cuisongliu** [comment]
https://github.com/dexidp/dex  

docking oidc

**Comment by cuisongliu** [comment]
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuring-the-api-server

**Comment by fanux** [comment]
dex is too complicated, we have already implemented the most core capabilities, so there is no need to use dex I think

**Comment by cuisongliu** [comment]
1. https://dexidp.io/docs/using-dex/  Writing Apps That Use Dex  ,using dex sdk can dicking it.
2.  dex support (LDAP, GitHub, SAML2.0, GitLab,OpenID Connect,OAuth 2.0, OpenStack and so on ) https://dexidp.io/docs/connectors/

We only need to integrate dex, and we don't need to care whether it is LDAP or OAuth2.

**Comment by cuisongliu** [comment]
https://github.com/cuisongliu/dex-login  dex login code

**Comment by cuisongliu** [comment]
using  fist+casbin It's also a better plan. We can all think about it together.

**Comment by Abingcbc** [comment]
Casdoor or other SSO platforms already provides JWT token as a certification for user successful login. Maybe we can combine token generated by `fist` with this one?

**Comment by cuisongliu** [comment]
Yes, it can be like this. The main ability of fist is the docking of oidc and k8s, and SSO can use other better solutions.

**Comment by Abingcbc** [comment]
TODO:
- [ ] Not delete PVC when deleting cluster image
- [ ] Update MySQL when service-auth is restarting
- [ ] Fix Casdoor redirect url
- [ ] Use errors.Wrap
- [ ] Fix getOauthToken error
