### ISSUE TITLE
Feature: sealos gen

### ISSUE THREAD

**Issue by cuisongliu** [labring/sealos#1179]
```
sealos gen labring/kubernetes:v1.24.0 --masters 192.168.0.2,192.168.0.3,192.168.0.4 \
	--nodes 192.168.0.5,192.168.0.6,192.168.0.7 --port 24 --passwd xxx
```

Check generated Clusterfile: 'cat .sealos/default/Clusterfile'

**Comment by gitccl** [comment]
Assign to me.

**Comment by gitccl** [comment]
The [Mounts filed in ClusterStatus struct](https://github.com/labring/sealos/blob/faa3d2c5a2d512c0c3c400a4a1ac0eb8e1cb0109/pkg/types/v1beta1/cluster.go#L88) without omitempty, this will cause that status and mounts are outputted even if it was empty.
```yaml
status:
  mounts: null
```

**Comment by cuisongliu** [comment]
> Mounts filed in ClusterStatus struct

```
type ClusterStatus struct {
	Phase      ClusterPhase       `json:"phase,omitempty"`
	Mounts     []MountImage       `json:"mounts, omitempty"`
	Conditions []ClusterCondition `json:"conditions,omitempty" `
}
```

Fix this CRD
