### ISSUE TITLE
BUG: Version: 3.3.9-rc.11 kube1.22.0.tar.gz shell脚本问题

### ISSUE THREAD

**Issue by bbbglimmer** [labring/sealos#1208]
**Which command or component**
Version: 3.3.9-rc.11 
kube1.22.0.tar.gz
kube1.22.0.tar.gz压缩包中kube/shell/init.sh
`sh containerd.sh`
会导致后边${criDriver}无法获取,导致以下文件中的cgroup-driver为空值
cat /etc/systemd/system/kubelet.service.d/containerd.conf 
[Service]
Environment="KUBELET_EXTRA_ARGS=--container-runtime=remote --cgroup-driver= --runtime-request-timeout=15m --container-runtime-endpoint=unix:///run/containerd/containerd.sock --image-service-endpoint=unix:///run/containerd/containerd.sock"

应将kube/shell/init.sh内的该句改成
`. containerd.sh`

**The Description of the bug**

会导致如果已经安装containerd并且配置为systemd后安装k8s时报错
[kubelet-check] Initial timeout of 40s passed.

kubelet报错
kubelet.go:2267] node "master1" not found

**Comment by fanux** [comment]
https://github.com/labring/sealos#quickstart   试下 4.0 哈  我们会逐渐废弃 3.0
