### ISSUE TITLE
安装sealos 3失败

### ISSUE THREAD

**Issue by sunnyForshuine** [labring/sealos#1214]
centos7.9，安装三主一从，hostname sealos01，sealos02，sealos03，sealos04
执行命令：
wget -c https://sealyun-home.oss-cn-beijing.aliyuncs.com/sealos/latest/sealos && \
     chmod +x sealos && mv sealos /usr/bin
sealos init \
	--master 172.31.10.31  --master 172.31.10.32  --master 172.31.10.33  \
	--node 172.31.10.34 \
	--user root \
    --passwd root \
	--pkg-url /usr/local/kube1.22.11.tar.gz \
	--version v1.22.11

![78ca028c2bad95e6ad8ca5025999092](https://user-images.githubusercontent.com/30744648/176116824-bf99b335-c892-4337-b4f0-edd84df5b048.jpg)
![image](https://user-images.githubusercontent.com/30744648/176117614-b39bb2f9-5f2a-4580-b023-82384e29c760.png)

![2df216e1abb9d1a785c499819ac8d18](https://user-images.githubusercontent.com/30744648/176116844-f9d96849-21d7-49d2-b49f-0048a51fccfb.jpg)
![9e2da91c5a26e60a1c3ffc005a5b643](https://user-images.githubusercontent.com/30744648/176116858-4be91972-d31d-4f10-ace5-2b630186d401.jpg)
![4f2923163421c9fbf0fe6993355a5da](https://user-images.githubusercontent.com/30744648/176116865-1b78c4a8-8d20-4b8e-b07f-e603eb2af2a6.jpg)
![image](https://user-images.githubusercontent.com/30744648/176117765-53dd75eb-cbdd-4734-8791-d6a88b6701f2.png)

**Comment by fanux** [comment]
需要查看 kubelet 日志失败信息。  是否可以使用 4.0，我们后续会逐步放弃维护 3.0
