### ISSUE TITLE
Build kubernetes dashboard image

### ISSUE THREAD

**Issue by fanux** [labring/sealos#1227]
https://github.com/labring/sealos/blob/main/docs/4.0/build-example-ingress-helm.md 

https://github.com/kubernetes/dashboard

You need to add admin permission to the dashboard service account

**Comment by cuisongliu** [comment]
If the mirror build can submit the relevant configuration to "https://github.com/labring/cluster-image/tree/main/runtime/applications",  the image can be automatically built.
