### ISSUE TITLE
CI Improvements

### ISSUE THREAD

**Issue by SignorMercurio** [labring/sealos#1265]
## Tasks
There's much to improve on CI workflow now.

Type | Improvements | Issue | PR | Status
:-: | :-: | :-: | :-: | :-:
Makefile | Add commands to build and push images for lvscare | | #1288, #1296, #1299 | ✅ 
Building  | Use `make build` instead of goreleaser build in regular CI checks for PR | | #1278 | ✅ 
Building | Build binaries for image-cri-shim and lvscare | | #1283 | ✅ 
Linting | Use [actions for golangci-lint](https://github.com/marketplace/actions/run-golangci-lint) instead of directly running commands | | #1270 | ✅ 
Linting | Run golangci-lint in parallel for each directory with a `go.mod` | | #1270 | ✅ 
Releasing | Use goreleaser to publish releases on GitHub | #1177 | #1296 | ✅ 
Releasing | Use [actions for goreleaser](https://github.com/marketplace/actions/goreleaser-action) instead of directly running commands | | #1296 | ✅ 
Releasing | Publish DEB and RPM packages | #1153 | #1299 | ✅ 
Workflow | Improve workflow dependency relations, e.g. `check-license` should perform before steps like linting and testing | | #1270 | ✅ 
Workflow | Use pre-built images to further speedup the CI | #1257 | | ❌
Bots | Add [CLA bot](https://colineberhardt.github.io/cla-bot/) | | | ❌

## Questions
- Should we split the process of unit testing and test coverage producing?
- See tasks above ~~Which parts of jobs should be automated through Makefile, and which parts should be with goreleaser?~~
  - ~~(As one of the subquestions) Should we use goreleaser in normal CI checks? Perhaps using `make build` could speedup the process.~~
- ...

cc @cuisongliu @zzjin @berlinsaint

**Comment by cuisongliu** [comment]
- [ ] add cla bot https://colineberhardt.github.io/cla-bot/ 
- [ ] add sign-off tips bot

**Comment by SignorMercurio** [comment]
@berlinsaint Could you please help with the *Releasing* part? I'm not quite familiar with goreleaser. Hopefully we can use the official github actions for goreleaser.

**Comment by zzjin** [comment]
> Should we split the process of unit testing and test coverage producing?
* As golang's unit testing is concurrently, maybe we can spec some packages at command a, others running command b, but do so will have makefile to maintain package info and let test result more difficult to dig, so I suggest do not spilt.
* The test coverage report needs all sub package's coverage info combined so we cannot split it, the answer is no need too.

**Comment by SignorMercurio** [comment]
@zzjin Agreed, but there appears to be some misunderstanding. By saying "split the process of unit testing and test coverage producing", I meant running a workflow step of unit testing before running another step that produces test coverage. Would this be necessary?

**Comment by zzjin** [comment]
> @zzjin Agreed, but there appears to be some misunderstanding. By saying "split the process of unit testing and test coverage producing", I meant running a workflow step of unit testing before running another step that produces test coverage. Would this be necessary?

OK, I got it.
Not necessary, `go test` will run tests concurrently and generate coverage profile when done. one workflow is enough.

**Comment by SignorMercurio** [comment]
> * add sign-off tips bot

This might not necessary as the exisiting DCO bot already do the job. If one PR fails the DCO check, there's detailed instructions on how to sign-off the commits when you click on `Details` for the check:

![image](https://user-images.githubusercontent.com/32540679/178268022-21973166-e796-4ff9-9abd-c6bb810eff0e.png)
