### ISSUE TITLE
Bug: running sealos not in master0

### ISSUE THREAD

**Issue by cyl-007** [labring/sealos#1276]
sealos版本：v4.0.0
服务器：centos7.9/Ubuntu
![2375e5ba4913e97c51ae6d30614bb14](https://user-images.githubusercontent.com/74633249/177984248-948d53a2-ecff-414e-8e6d-fdc2978210a1.jpg)

![1d462e32eb9af0137e27cdcb85caad0](https://user-images.githubusercontent.com/74633249/177984504-956feb1f-149a-4d71-89a5-548355fea815.jpg)

**Comment by cuisongliu** [comment]
应该是跨主机导致的，因为读取配置好多都是读取的当前系统的配置 导致读取失败

1. registry配置
2. image-cri-shim配置

**Comment by fanux** [comment]
在 master0 执行可临时解决这个问题，后面我们会修复。
