### ISSUE TITLE
安装sealos失败

### ISSUE THREAD

**Issue by luanshaotong** [labring/sealos#1284]
**Which command or component**

aws EC2

wget -c https://sealyun-home.oss-cn-beijing.aliyuncs.com/sealos-4.0/latest/sealos-amd64 -O sealos && \
    chmod +x sealos && mv sealos /usr/bin
sealos run labring/kubernetes:v1.24.2 labring/calico:v3.22.1 --masters 172.31.35.229 --nodes 172.31.18.138

**The Description of the bug**

join node时node连不上apiserver
![2152a59a4a17ae78425b87bcde15dea](https://user-images.githubusercontent.com/14962503/178097307-d0d112ae-b329-4c71-a982-10f9ff2b71c5.png)

node的kubelet报错
![9768fd58e2d9bc980ee81d2f22d7bc6](https://user-images.githubusercontent.com/14962503/178097303-bba82032-78bd-462b-85fe-bf2a5db26fe5.png)

**How to reproduce（pictures can be attached if necessary）**
1. aws EC2使用如上命令

**Comment by zhangguanzhang** [comment]
应该是 umask 导致systemd的子配置文件多了x权限
