### ISSUE TITLE
BUG: “sealos build” run out of memory

### ISSUE THREAD

**Issue by luanshaotong** [labring/sealos#1301]
**Which command or component**

sealos build -f Dockerfile

**The Description of the bug**

I'm building cluster image with image list at _images/shim/_. Sealos ran out of memory while pulling a layer of 2.61G, and then killed by system.

![image](https://user-images.githubusercontent.com/14962503/178666630-732c8324-4bed-429c-90a4-5a8c2a1d5e87.png)
![image](https://user-images.githubusercontent.com/14962503/178666714-24576029-49a0-4dcc-b86c-a20dab955fd1.png)

When i use _sealos pull_ to pull the image directly, it passed.

![image](https://user-images.githubusercontent.com/14962503/178666652-ff88562b-1ebb-45d1-936d-77d1a90fbb9a.png)

**How to reproduce（pictures can be attached if necessary）**
1. run sealos on a VM with 2C4G.
2. run _sealos build_ with image layer larger than 2G.

**Test Result**
1. run out of memory while pulling layer larger than 2G

**What you expected to happen**

secucessfully build cluster image

**Operating environment**

RHEL-8.3.0
![image](https://user-images.githubusercontent.com/14962503/178667350-29d235db-9d28-456b-96fc-2158dc666f7d.png)

**Comment by fanux** [comment]
https://github.com/labring/sealos/blob/main/pkg/registry/save.go#L356

**Comment by shy-Xu** [comment]
come,come,come

**Comment by fanux** [comment]
@luanshaotong @shy-Xu is the author of registry module,  great for solving this problem.

**Comment by shy-Xu** [comment]
> @luanshaotong @shy-Xu is the author of registry module, great for solving this problem.
Aha, fanux is my instructor, this module is under his guidance.

**Comment by luanshaotong** [comment]
> > @luanshaotong @shy-Xu is the author of registry module, great for solving this problem.
> 
> Aha, fanux is my instructor, this module is under his guidance.

Nice. And i have a new problem waiting for your help  #1314  233333.

**Comment by cuisongliu** [comment]
@shy-Xu   https://github.com/labring/sealos/issues/1314 Fix it together ？

**Comment by shy-Xu** [comment]
> @shy-Xu #1314 Fix it together ？

My pleasure

**Comment by berlinsaint** [comment]
what's the progress about this?
