### ISSUE TITLE
 a kubeconfig file "/etc/kubernetes/scheduler.conf" exists already but has an unexpected API Server URL: expected: https://120.48.17.16:6443, got: https://apiserver.cluster.local:6443

### ISSUE THREAD

**Issue by wanghao123123** [labring/sealos#1309]
[EROR] Applied to cluster error: failed to init init master0 failed, error: failed to execute command(kubeadm init --config=/var/lib/sealos/data/default/etc/kubeadm-init.yaml --skip-certificate-key-print --skip-token-print -v 0 --ignore-preflight-errors=SystemVerification) on host(120.48.17.16:22): output([init] Using Kubernetes version: v1.20.0
[preflight] Running pre-flight checks
        [WARNING FileExisting-socat]: socat not found in system path

W0714 18:01:38.188949   39681 kubeconfig.go:246] a kubeconfig file "/etc/kubernetes/controller-manager.conf" exists ### **_

> already but has an unexpected API Server URL: expected: https://120.48.17.16:6443, got: https://apiserver.cluster.local:6443

_**
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/controller-manager.conf"
W0714 18:01:38.323750   39681 kubeconfig.go:246] a kubeconfig file "/etc/kubernetes/scheduler.conf" exists already but has an unexpected API Server URL: expected: https://120.48.17.16:6443, got: https://apiserver.cluster.local:6443
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/scheduler.conf"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

        Unfortunately, an error has occurred:
                timed out waiting for the condition

        This error is likely caused by:
                - The kubelet is not running
                - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

        If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
                - 'systemctl status kubelet'
                - 'journalctl -xeu kubelet'

        Additionally, a control plane component may have crashed or exited when started by the container runtime.
        To troubleshoot, list all containers using your preferred container runtimes CLI.

        Here is one example how you may list all Kubernetes containers running in cri-o/containerd using crictl:
                - 'crictl --runtime-endpoint /run/containerd/containerd.sock ps -a | grep kube | grep -v pause'
                Once you have found the failing container, you can inspect its logs with:
                - 'crictl --runtime-endpoint /run/containerd/containerd.sock logs CONTAINERID'

error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher), error(Process exited with status 1). Please clean and reinstall****

**Comment by wanghao123123** [comment]
使用外网ip搭建   版本为1.24.0

**Comment by wanghao123123** [comment]
> provide your sealos run command, should not use the EIP
sealos run labring/kubernetes:v1.20.0 labring/calico:v3.22.1  --masters 120.48.17.16  --nodes 106.12.170.67

**Comment by wanghao123123** [comment]
[WARNING FileExisting-socat]: socat not found in system path
        [WARNING Hostname]: hostname "master" could not be reached
        [WARNING Hostname]: hostname "master": lookup master on 100.100.2.138:53: no such host

already but has an unexpected API Server URL: expected: https://47.99.222.61:6443, got: https://apiserver.cluster.local:6443/

kubelet logs 

08 kubelet.go:2240] node "master" not found

**Comment by cuisongliu** [comment]
systemctl status kubelet

**Comment by wanghao123123** [comment]
> systemctl status kubelet

Status is closed

error logs  node "master" not found

centos7

**Comment by wanghao123123** [comment]
经过测试我发现一个干净的系统，直接使用内网搭建不会出现标题上述问题，但使用公网ip搭建就会出现

**Comment by cuisongliu** [comment]
> 经过测试我发现一个干净的系统，直接使用内网搭建不会出现标题上述问题，但使用公网ip搭建就会出现
