### ISSUE TITLE
BUG: sealos build failed pulling private images

### ISSUE THREAD

**Issue by luanshaotong** [labring/sealos#1314]
**Which command or component**

sealos login registry.cn-hangzhou.aliyuncs.com -u xxx -p xxx
sealos build -f Dockerfile -t xxxxxx

**The Description of the bug**

Login private registry with authentication.
_sealos build_ still fail while pulling an image from the private registry.
however, _sealos pull_ succeed.
![image](https://user-images.githubusercontent.com/14962503/179166157-eb75b30d-d2c6-4590-8178-702b8b2fe807.png)

I think it should be caused by https://github.com/labring/sealos/blob/c8565d10aa97e83d126941d526e513a165423d8e/pkg/registry/util.go#L98
GetAuthInfo() function use `/run/user/0/containers/auth.json` to get authentication, but it should be at `/run/user/1000/containers/auth.json` on my server. 

 
![image](https://user-images.githubusercontent.com/14962503/179166580-4997e047-03bd-456a-b04b-fa9ce7e923fc.png)
Anyway, i do not know how to fix it.

**Operating environment**
ubuntu 18.04
![image](https://user-images.githubusercontent.com/14962503/179167825-3e325d38-3b69-48a0-888d-eb65c8ffd986.png)

**Comment by shy-Xu** [comment]
hard coding

**Comment by shy-Xu** [comment]
Great find

**Comment by cuisongliu** [comment]
sealos login your private registry

**Comment by cuisongliu** [comment]
need using buildak login sdk to login

**Comment by cuisongliu** [comment]
using  
```
func GetAllCredentials(sys *types.SystemContext) (map[string]types.DockerAuthConfig, error)
```

replace it
