### ISSUE TITLE
BUG: strconv.Atoi: parsing "shell-init: error retrieving current directory

### ISSUE THREAD

**Issue by songdi676** [labring/sealos#1315]
**Which command or component**

 sudo sealos apply -f /var/lib/sealos/data/songditest/Clusterfile --debug=true

Describe the bug.
![image](https://user-images.githubusercontent.com/15158819/179193933-1272b114-5b12-4d27-bcb1-ec31827a7db2.png)
`[paasopt@fjrqy-node-2 0715test]$ date +%s
1657876181`

**Comment by songdi676** [comment]
我尝试几次，时间同步检查过了，但是报了下面的错误
![image](https://user-images.githubusercontent.com/15158819/179195257-8810ac66-6051-4d5e-a679-a8bc47b0d029.png)
Applied to cluster error: create from fail: 10.1.12.220:80/paas_public/kube-system/kubernetes:v1.24.2: image not known

**Comment by cuisongliu** [comment]
不是root？ 如果不是root的需求还在开发。
