### ISSUE TITLE
BUG: .kube directory was not generated in home directory

### ISSUE THREAD

**Issue by gitccl** [labring/sealos#1320]
**Which command or component**

sealos run

**The Description of the bug**

`sealos run` will generated .kube directory **in current working directory instead of home directory**. Thus if we not execute `sealos run` in home directory, kubectl will not work.
Related code: https://github.com/labring/sealos/blob/78b9b7f43d489fe9370bf9add10a8dca59e9f3fb/pkg/runtime/kubeconfig.go#L21-L31
https://github.com/labring/sealos/blob/78b9b7f43d489fe9370bf9add10a8dca59e9f3fb/pkg/ssh/sshcmd.go#L54-L57

**Comment by cuisongliu** [comment]
That's no problem, because there may be no kubactel on the host that executes sealos.
