### ISSUE TITLE
BUG: 读取rootfs/etc/registry.yml问题

### ISSUE THREAD

**Issue by songdi676** [labring/sealos#1322]
**Which command or component**

sealos apply

**The Description of the bug**

- rootfs/etc/registry.yml 文件有内容，但是pkg/runtime/registry.go读取后 username，password，domain都是空
- username，password为空串 ，导致 htpasswd()函数返回htpasswdPath空串。导致：copy generator registry htpasswd failed 

![image](https://user-images.githubusercontent.com/15158819/179340050-bb69dd28-6cfc-49aa-a9cb-a90f11c1217d.png)

**Comment by cuisongliu** [comment]
已经修复了，等待下个版本发布即可。
