### ISSUE TITLE
BUG: kubeadm init  [ERROR Port-6443]: Port 6443 is in use

### ISSUE THREAD

**Issue by songdi676** [labring/sealos#1327]
**Which command or component**

sealos apply

**The Description of the bug**
安装前清理了环境，也没有端口占用。
但是执行 sealos apply 报错：
![image](https://user-images.githubusercontent.com/15158819/179348345-f1b5b8eb-5911-434e-887b-279749c14b0b.png)
1.1然后我执行：kubeadm reset -f
1.2手动执行：` kubeadm init --config=/root/.sealos/sdtest1/etc/kubeadm-init.yaml --skip-certificate-key-print --skip-token-print -v 6 --ignore-preflight-errors=SystemVerification` 没有报错：
![image](https://user-images.githubusercontent.com/15158819/179348479-d6d789fc-1ecc-4957-bd92-87fdd95fbb01.png)
2.1执行：kubeadm reset -f
2.2 再次执行sealos apply -f /var/lib/sealos/data/sdtest1/Clusterfile --debug=true 还是报错：
![image](https://user-images.githubusercontent.com/15158819/179348557-76210154-411d-4f9b-912d-a74630d6be65.png)

**Comment by songdi676** [comment]
为什么 执行kubeadm reset -f 后手动运行 kubeadm init 没有问题。
执行sealos apply就会报错。

**Comment by songdi676** [comment]
相同的Clusterfile文件，我使用6月份的 sealos包，使用apply命令安装成功：
![image](https://user-images.githubusercontent.com/15158819/179349719-eb794959-d12f-4692-8fc3-1b99d072723d.png)

**Comment by fanux** [comment]
单节点吗？你看一下 reset 完之后 apiserver kubelet 这些进程是不是确定没了。   因为这个错误也是 sealos 调用 kubeadm 报出来的。

**Comment by cuisongliu** [comment]
![image](https://user-images.githubusercontent.com/4150905/179563759-3fbe3674-688d-4132-8461-e040353bc857.png)
目前看没有清理干净。
