### ISSUE TITLE
calico无法启动

### ISSUE THREAD

**Issue by simamingle** [labring/sealos#1337]
**Which command or component**

eg. sealos init, sealos install ...

**The Description of the bug**

Describe the bug.

**How to reproduce（pictures can be attached if necessary）**
1. 安装1.24.2 arm64版本calico无法启动，报错10.211.55.5:22: W0718 01:25:45.663177    8827 initconfiguration.go:120] Usage of CRI endpoints without URL scheme is deprecated and can cause kubelet errors in the future. Automatically prepending scheme "unix" to the "criSocket" with value "/run/containerd/containerd.sock". Please update your configuration!
2、kubelet报错日志
<img width="1742" alt="image" src="https://user-images.githubusercontent.com/96850542/179453148-6b0b2c12-0df8-4b46-a31c-486961fdf79b.png">
3、pod错误日志
<img width="1732" alt="image" src="https://user-images.githubusercontent.com/96850542/179453231-5a00ecf4-b54a-4050-a070-47c1a36d8017.png">
4、内核版本Linux K8s-master 5.11.12-300.el7.aarch64，操作系统：centos7.9 calico版本：labring/calico:v3.22.1
...

**Test Result**
1. 
3. 
4.

**What you expected to happen**

Expected to xxx

**Operating environment**

- Docker version:   eg. 19.03
- Kubernetes version: eg.kube1.16.tar.gz
- Sealos version: v3.1.0-alpha.2
- Operating system: eg. centos7
- Runtime environment:  eg. physical machine (100G memory, 10 core cpu, 10T storage), virtual machine (virbox, 10G memory, 2 core cpu, 100G storage), cloud(aws, 10G memory, 2 core cpu, 100G storage)
- Cluster size: eg 3 master, 3 node
- Additional information: istio, dashboard ...

**Comment by zhangguanzhang** [comment]
看下kube-proxy的日志

**Comment by fanux** [comment]
看着像连接不上 apiserver?
