### ISSUE TITLE
BUG: After the k8s runs for a period of time, the directory mounted by the mirror will be lost for no reason.

### ISSUE THREAD

**Issue by cuisongliu** [labring/sealos#1345]
mountPath is miss for sealos

**Comment by fanux** [comment]
What path? How to reproduce it?

**Comment by cuisongliu** [comment]
buildah mount path. The restart may reappear, but I haven't tested it. It needs to be tested.

**Comment by SignorMercurio** [comment]
I think this issue is closed by #1429?
