### ISSUE TITLE
Question: 如何刪除透過sealos run指令安裝的helm

### ISSUE THREAD

**Issue by zerox12311** [labring/sealos#1366]
**Which command or component**
透過文件指示安裝的helm
```bash=
sealos run labring/helm:v3.8.2
```
**The Description of the question**
如果想要移除是否有移除方式? 本來預期使用sealos delete卻好像無法移除?

**Comment by fanux** [comment]
helm list -A

然后直接用 helm 命令删除。

后面 sealos 会提供 actions 的能力，让应用自定义自己的删除逻辑或者其它操作

**Comment by fanux** [comment]
helm 本身直接删除二进制即可。rm /usr/bin/helm
