### ISSUE TITLE
Feature: 基于云原生思路，使用 K8 operator机制构建集群

### ISSUE THREAD

**Issue by songdi676** [labring/sealos#1369]
**Which command or component**

eg.  sealos apply
![image](https://user-images.githubusercontent.com/15158819/180160367-3f7baba1-79ee-44e0-aa92-ebc28460f931.png)
当前修改Clusterfile，使用sealos apply不能做扩缩容操作，只能使用 add 和 delete。

**Detailed description of the feature**
1.是否可以开发一个 sealos operator,监听CRD apps.sealos.io/v1beta1.Cluster的版本变化
2.用户通过kubectl 控制Clusterfile， sealos operator Reconciler目标集群

**Comment by fanux** [comment]
你可以来提供这个 feature 不，这在 sealos cloud 中会很有用，也可以加一下我微信 fangnux

**Comment by songdi676** [comment]
首先感谢sealos，我也很希望参与贡献，现在来讲时间不允许。希望以后有机会……

**Comment by fanux** [comment]
从设计思想上来说 apply 是需要支持伸缩的，我们正在开发中，后面也会增加一个控制器
