### ISSUE TITLE
BUG: v1.24.3 init pending

### ISSUE THREAD

**Issue by fanux** [labring/sealos#1384]
![image](https://user-images.githubusercontent.com/8912557/180417738-9e29b7cb-1e2e-4357-9907-c4cee2b56aa4.png)

**Comment by cuisongliu** [comment]
sealos run labring/kubernetes:v1.24.0 labring/kubelet:main  xxxxx



注意：需要使用4.0.0的release 的sealos

**Comment by cuisongliu** [comment]
或者直接编译新的镜像 https://github.com/labring/cluster-image/issues  找到对应大版本的issue 回复自动编译镜像。

根本问题是kubelet的配置在centos里无法生效。

https://github.com/labring/cluster-image/tree/main/config/kubelet/main 这里是变动的代码

**Comment by fanux** [comment]
@cuisongliu 新的代码是否兼容了所有版本镜像？
