### ISSUE TITLE
add Custom installation configuration guide to official docs

### ISSUE THREAD

**Issue by willzhang** [labring/sealos#1385]
## Which command or component
```
sealos gen
```
**Detailed description of the feature**

the Official [getting-started docs](https://www.sealyun.com/docs/category/getting-started) should be:

- Installation
- custom installation

the title `update-cluster` is strange to understand

## If you have solution，please describe it**

and the `custom installation` content should be

1、Run sealos gen to generate a Clusterfile. Example:
```
sealos gen labring/kubernetes:v1.24.0 labring/calico:v3.22.1 
  --masters 192.168.0.2,192.168.0.3,192.168.0.4 
  --nodes 192.168.0.5,192.168.0.6,192.168.0.7 
  --passwd xxx > Clusterfile
```
2、Append your calico custom config or kubeadm custom config to Clusterfile, and follow is a sample config

**don't Hide the configuration code block, otherwise it is easy to be ignored**

```
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  creationTimestamp: null
  name: default
spec:
  hosts:
    - ips:
        - 192.168.0.2:22
        - 192.168.0.3:22
        - 192.168.0.4:22
      roles:
        - master
        - amd64
    - ips:
        - 192.168.0.5:22
        - 192.168.0.6:22
        - 192.168.0.7:22
      roles:
        - node
        - amd64
  image:
    - labring/kubernetes:v1.24.0
    - labring/calico:v3.22.1
  ssh:
    passwd: xxx
    pk: /root/.ssh/id_rsa
    port: 22
    user: root
status: {}
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
networking:
  podSubnet: 10.160.0.0/12
---
apiVersion: apps.sealos.io/v1beta1
kind: Config
metadata:
  name: calico
spec:
  path: manifests/calico.yaml
  data: |
    apiVersion: operator.tigera.io/v1
    kind: Installation
    metadata:
      name: default
    spec:
      # Configures Calico networking.
      calicoNetwork:
        # Note: The ipPools section cannot be modified post-install.
        ipPools:
        - blockSize: 26
          # Note: Must be the same as podCIDR
          cidr: 10.160.0.0/12
          encapsulation: IPIP
          natOutgoing: Enabled
          nodeSelector: all()
        nodeAddressAutodetectionV4:
          interface: "eth.*|en.*"
```

**Comment by zzjin** [comment]
Thankyou for given such detailed solution!

The docs are under `docs` dir and you can straight open one pr to improve it. [direct edit link](https://github.com/labring/sealos/edit/main/docs/4.0/docs/getting-started/update-cluster.md)
When PR get merged, it will automatic synced to sealos's mainsite.

Any PRs are welcome!

**Comment by willzhang** [comment]
Fixed:https://github.com/labring/sealos/pull/1448
