### ISSUE TITLE
nodePort 参数映射的端口本地看不到但是telnet localhost 端口能通

### ISSUE THREAD

**Issue by he-aook** [labring/sealos#1389]
**Which command or component**

eg.  sealos xxx, sealos init

**Detailed description of the feature**
1. nodeport 映射端口本地看不到, 但是telnet localhost 端口能通

**If you have solution，please describe it**

Complete this feature through XXX
1.
<img width="766" alt="image" src="https://user-images.githubusercontent.com/48249754/180600644-41bc2ddb-07a7-4e8f-bd5d-4095c4328214.png">
[root@master 04_redis]# kubectl get svc |grep redis
redis        NodePort    10.96.0.250   <none>        6379:30002/TCP   13m
[root@master 04_redis]# netstat -ntlpa|grep 30002
[root@master 04_redis]#

**Comment by zhangguanzhang** [comment]
```
iptables -t nat -S | grep -A3 30002
```

**Comment by he-aook** [comment]
[root@master ~]# kubectl get svc
NAME          TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)          AGE
alpine-test   NodePort    10.96.2.186   <none>        3308:32001/TCP   25h
kubernetes    ClusterIP   10.96.0.1     <none>        443/TCP          26h
redis         NodePort    10.96.0.250   <none>        6379:30002/TCP   25h
[root@master ~]# iptables -t nat -S | grep -C2 30002
[root@master ~]#

**Comment by zhangguanzhang** [comment]
```
netstat -nlpt | grep :30002
iptables -t nat -S | grep -C2 30002
```

**Comment by he-aook** [comment]
没事的,现在就是看不到, 但是能访问到,实在感谢







At 2022-07-25 09:32:09, "zhangguanzhang" ***@***.***> wrote:

netstat -nlpt | grep :30002
iptables -t nat -S | grep -C2 30002

**Comment by zhangguanzhang** [comment]
containerd的我还没用过，感觉和containerd的有关，或者新版本的 cni-plugins有关

**Comment by fuxingbit** [comment]
是的是的，这次安装没做任何多余配置，默认没有使用docker，使用的containerd，这个可以配置吗？
