### ISSUE TITLE
报错：panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by YouWu-GitHub** [labring/sealos#1393]
**Which command or component**

sealos join

**The Description of the bug**

sealos join --node 10.0.40.22 --node 10.0.40.23

**How to reproduce（pictures can be attached if necessary）**
1. 
问题具体描述：sealos多master节点部署成功后，手动踢出其中一个master节点。然后清理再加入时报错（加入master与node同问题）
2.
问题截图
![image](https://user-images.githubusercontent.com/45085026/180690575-d01caad6-a505-4e86-8d35-df7354c18db7.png)

**Test Result**
1. 
2. 
3.

**What you expected to happen**

加入master与node成功

**Operating environment**

- Docker version:   eg. 19.03
- Kubernetes version: kube1.18.16.tar.gz
- Sealos version v3.3.8, build  go1.13.5
- Operating system: eg. centos7.8
- Runtime environment:   虚拟机 ( VM, 内存 8gb, cpu 4核 ,存储 100gb )
- Cluster size:  3 master, 10 node
- Additional information: istio, dashboard ...

**Comment by YouWu-GitHub** [comment]
原因好像因为我剔除的是master0节点。
请问这种master0不存在后还有办法使用sealos操作集群吗？

**Comment by fanux** [comment]
show me your .sealos/default/Clusterfile file

**Comment by fanux** [comment]
The join command master exec on your master0

**Comment by cuisongliu** [comment]
> The join command master exec on your master0

This is sealos3

**Comment by YouWu-GitHub** [comment]
> 



> 给我看你的 .sealos/default/Clusterfile 文件

您好，我的master0 因为宿主机问题已经无法启动，所以我才在集群中剔除了。
上述的问题是我在master01-02中执行时报出的错误。

[root@master02 ~]# cat .sealos/config.yaml 
masters: []
nodes: []
dnsdomain: ""
apiservercertsans: []
user: root
passwd: root
privatekey: /root/.ssh/id_rsa
apiserverdomian: apiserver.cluster.local
vip: 10.103.97.2
pkgurl: ""
version: v1.14.1
repo: k8s.gcr.io
podcidr: 100.64.0.0/10
svccidr: 10.96.0.0/12
certpath: /root/.sealos/pki
certetcdpath: /root/.sealos/pki/etcd
lvscarename: fanux/lvscare
lvscaretag: latest

**Comment by YouWu-GitHub** [comment]
> 

是的，sealos version v3.3.8

**Comment by fanux** [comment]
@YouWu-GitHub using sealos 4.0~ https://www.sealos.io/docs/cli/run

**Comment by fanux** [comment]
@YouWu-GitHub using https://www.sealos.io/docs/Intro#quickstart sealos 4.0~

**Comment by YouWu-GitHub** [comment]
> @YouWu-GitHub使用https://www.sealos.io/docs/Intro#quickstart sealos 4.0~
好的，谢谢
