### ISSUE TITLE
Question: 新版本不提供离线安装了吗

### ISSUE THREAD

**Issue by itzhoujun** [labring/sealos#1401]
**Which command or component**
sealos init

**The Description of the question**
之前版本是使用sealos init 指定一个离线包进行安装，现在是使用 sealos run labring/kubernetes:v1.24.0 labring/calico:v3.22.1，也找不到离线包的下载地址了。

我们项目是比较需要离线安装的，包括其他周边的labring/kube-prometheus-stack:35.0.0等，有离线包吗

**Comment by cuisongliu** [comment]
sealos pull 然后sealos save 成tar就可以了
