### ISSUE TITLE
建议完善一下各种镜像的使用文档

### ISSUE THREAD

**Issue by itzhoujun** [labring/sealos#1404]
例如sealos run labring/kube-prometheus-stack:35.0.0，是否是封装了https://github.com/prometheus-operator/kube-prometheus ？官方文档对这些镜像没有更多详细介绍，一般人sealos run了之后也不知道怎么用啊。

**Comment by itzhoujun** [comment]
sealos run命令实际上是安装对吗？安装完之后怎么管理呢？

直接用https://github.com/prometheus-operator/kube-prometheus 的话好歹有yaml文件直接kubectl apply或者delete就可以启停服务，用sealos要怎么搞呢？

**Comment by willzhang** [comment]
sealos就执行了helm insall 或者kubectl apply, 剩下的用原生方法管理就行

**Comment by willzhang** [comment]
貌似只能改运行状态的配置文件。

**Comment by itzhoujun** [comment]
@willzhang 用kubectl edit修改吗

**Comment by fanux** [comment]
@itzhoujun 确实需要提供使用文档，目前是用了 prometheus stack，不过修了一些问题，如无法监控 etcd 和 scheduler 的问题。 sealos  的配置管理方式是支持 overwrite 镜像里面的任意文件的，也就是 prometheus 的 yaml。

至于删除每个应用都有不一样的删除方式，所以 sealos 做了更高维度的抽象叫 Actions, 这样用户可以自定义任何针对应用的操作而不只是删除。

以上这些我们都在迭代中，有兴趣也可以参与到文档建设中～

**Comment by hellowang-pj** [comment]
@fanux 你好，请问 ”sealos 的配置管理方式是支持 overwrite 镜像里面的任意文件的“ 是指使用kubectl exec -it到prometheus容器中修改yaml文件吗，不知道我的理解对不对，我想不中断程序修改配置文件，请问支持吗
