### ISSUE TITLE
Question: 安装报错exec remote command failed

### ISSUE THREAD

**Issue by itzhoujun** [labring/sealos#1421]
如图所示：
![image](https://user-images.githubusercontent.com/6897671/181440215-4baad561-565f-45b9-98a9-c4ec478b8d56.png)

**Comment by cuisongliu** [comment]
10.0.4.2 机器上执行一下。你用的哪个版本的k8s

**Comment by itzhoujun** [comment]
> 10.0.4.2 机器上执行一下。你用的哪个版本的k8s

@cuisongliu  我这个就是在10.0.4.2机器上执行的。用的是v1.19.17版本。刚刚还遇到别的问题，不知道是否有关：https://github.com/labring/sealos/issues/1420

**Comment by cuisongliu** [comment]
> > 10.0.4.2 机器上执行一下。你用的哪个版本的k8s
> 
> @cuisongliu 我这个就是在10.0.4.2机器上执行的。用的是v1.19.17版本。刚刚还遇到别的问题，不知道是否有关：#1420

我去删除一下 这个镜像又问题 最新的是1.19.16 尴尬

**Comment by itzhoujun** [comment]
有点倒霉啊，一连踩了好几个坑。
