### ISSUE TITLE
sealos run labring/kubernetes:v1.24.0 安装报错

### ISSUE THREAD

**Issue by everthingcrazy** [labring/sealos#1422]
![5CT3U}{RG7G9D 1T843P9_H](https://user-images.githubusercontent.com/49516791/181481574-45e1bf9a-a40a-4fc1-bf3f-f352109d889d.png)

![H~TX5RLS3R34AO@W_IOLVOL](https://user-images.githubusercontent.com/49516791/181481611-b8bfa2c2-fed5-4fb1-97c9-2d27f2be4301.png)
![A_Y_STO}B0)BJIP8~({8EZQ](https://user-images.githubusercontent.com/49516791/181481627-09694f70-0c69-43ba-8cde-4b4b3ea6f7cc.jpg)

**Comment by cuisongliu** [comment]
crictl ps -a 看一下pod有起来么

**Comment by fanux** [comment]
show me you exec command.
