### ISSUE TITLE
sealos run labring/kubernetes:v1.24.0启动集群报错

### ISSUE THREAD

**Issue by qinyudong89** [labring/sealos#1423]
**环境**
CentOS 8

**部署过程如下**

1. wget https://github.com/labring/sealos/releases/download/v4.0.0/sealos_4.0.0_linux_amd64.tar.gz    && tar zxvf sealos_4.0.0_linux_amd64.tar.gz sealos && chmod +x sealos && mv sealos /usr/bin

2. sealos run labring/kubernetes:v1.24.0 labring/calico:v3.22.1  --masters 192.168.173.69  --nodes 192.168.173.68,192.168.173.67 --passwd 123456@abc#

**报错如下**
2022-07-28 18:27:57 [INFO] Executing pipeline PreProcess in CreateProcessor.
7cecddd9bf9411537ad0122c80c33eb162f6935e6f235137431004a2324da9d5
29516dc98b4b2d4fc899c9b27dfd004e75ee73ef9071ad6835f9ff97f156f58c
invalid argument "never" for "--pull" flag: strconv.ParseBool: parsing "never": invalid syntax
2022-07-28 18:28:23 [EROR] Applied to cluster error: exit status 125

**Comment by cuisongliu** [comment]
本地有buildah ,卸载一下。

**Comment by cuisongliu** [comment]
whereis buildah看一下

**Comment by fanux** [comment]
123456@abc#  =>  '123456@abc#'

**Comment by qinyudong89** [comment]
> Collaborator

解决了非常感谢
