### ISSUE TITLE
BUG: "sealos build" get wrong image name from charts

### ISSUE THREAD

**Issue by luanshaotong** [labring/sealos#1431]
**Which command or component**

sealos build -f Clusterfile . -t luanshaotong/sealos-blazeface:v1.0

**The Description of the bug**

_sealos build_ get wrong image address from chart
![image](https://user-images.githubusercontent.com/14962503/181721794-7597a0f7-34a9-46b9-b167-08c453946010.png)
![image](https://user-images.githubusercontent.com/14962503/181722800-b1f434c5-da27-428b-9cf5-f28be1202d53.png)

**How to reproduce（pictures can be attached if necessary）**

1. make chart in `charts/`
2. sealos build 

![image](https://user-images.githubusercontent.com/14962503/181722468-5a1491c1-3a48-4b57-97dc-b2a3539464ba.png)

**Comment by yyf1986** [comment]
#1433
