### ISSUE TITLE
请问怎么管理镜像啊？

### ISSUE THREAD

**Issue by itzhoujun** [labring/sealos#1434]
最新版没有了docker，要怎么管理镜像啊？用ctr images ls只能看到registry一个镜像，其他镜像在哪呢？我想手动load一个离线的镜像，要怎么load呢？

**Comment by fanux** [comment]
$ ctr image export --platform linux/amd64 postgres-12.tar docker.io/library/postgres:12
$ ctr image import postgres-12.tar

更多使用方式可以 `ctr image import --help`

**Comment by fanux** [comment]
也可以用 nerdctl https://github.com/containerd/nerdctl#image-management

**Comment by itzhoujun** [comment]
@fanux 你好，请教一下。我用ctr images只能看到registry镜像，其他镜像都看不到，import之后k8s无法拉到镜像。
用nerdctl load时需要指定namespace为k8s.io才可以被k8s拉到。
是不是意味着只能用nerdctl？k8s又是如何指定namespace为k8s.io的？建议搞个文档吧，一般人整不会，要哭了。

**Comment by cuisongliu** [comment]
用的是crictl.默认不需要用ctr

**Comment by itzhoujun** [comment]
> 用的是crictl.默认不需要用ctr

crictl怎么load镜像？

**Comment by cuisongliu** [comment]
> > 用的是crictl.默认不需要用ctr
> 
> 
> 
> crictl怎么load镜像？

你是要把docker镜像导入？直接push 到镜像仓库就可以了

**Comment by cuisongliu** [comment]
直接做集群镜像就可以。

**Comment by itzhoujun** [comment]
> 

我的主要场景都是需要离线部署，所有镜像都得离线导入，总不能都做成集群镜像。

**Comment by itzhoujun** [comment]
> 直接做集群镜像就可以。

我的主要场景都是需要离线部署，所有镜像都得离线导入，总不能都做成集群镜像。

**Comment by itzhoujun** [comment]
> > > 用的是crictl.默认不需要用ctr
> > 
> > 
> > crictl怎么load镜像？
> 
> 你是要把docker镜像导入？直接push 到镜像仓库就可以了

命令是？

**Comment by cuisongliu** [comment]
> > 直接做集群镜像就可以。
> 
> 
> 
> 我的主要场景都是需要离线部署，所有镜像都得离线导入，总不能都做成集群镜像。

这个为啥不可以？集群镜像就是解决这个问题的，sealos build 一个集群镜像，集群镜像包含你要离线的镜像

**Comment by itzhoujun** [comment]
> > > 直接做集群镜像就可以。
> > 
> > 
> > 我的主要场景都是需要离线部署，所有镜像都得离线导入，总不能都做成集群镜像。
> 
> 这个为啥不可以？集群镜像就是解决这个问题的，sealos build 一个集群镜像，集群镜像包含你要离线的镜像

大哥你这是互联网思维，我们做安防的插个优盘都要打报告，经常只需要单独更新某一个镜像，在客户现场只有手机热点两三百k的速度下载更新包。任何包都要离线处理且最小化处理。

**Comment by cuisongliu** [comment]
> > > > 直接做集群镜像就可以。
> > > 
> > > 
> > > 我的主要场景都是需要离线部署，所有镜像都得离线导入，总不能都做成集群镜像。
> > 
> > 
> > 这个为啥不可以？集群镜像就是解决这个问题的，sealos build 一个集群镜像，集群镜像包含你要离线的镜像
> 
> 大哥你这是互联网思维，我们做安防的插个优盘都要打报告，经常只需要单独更新某一个镜像，在客户现场只有手机热点两三百k的速度下载更新包。任何包都要离线处理且最小化处理。

集群镜像就算是一个镜像不是也可以打么。。。完全看你集群镜像咋做了。。。。
