### ISSUE TITLE
sealos run -e支持哪些参数？

### ISSUE THREAD

**Issue by itzhoujun** [labring/sealos#1452]
今天无意中在群里看到有人提到-e criData，我才知道可以通过这个参数来修改containerd镜像目录。除了criData外还支持什么参数？

请恕我直言，sealos的文档是真的垃圾，啥啥都没有，花个一两天完善一下文档很难吗？

可能我说话重了，但我个人是非常喜欢sealos的，sealos是我用过安装k8s最方便的工具，没有之一。我在我的博客中也是这么介绍sealos的。
![image](https://user-images.githubusercontent.com/6897671/182307861-092dfdfa-8150-40c4-a300-f1587fecd4e7.png)

希望贵方能够重视文档建设，让新人少踩一些坑。 @fanux

**Comment by itzhoujun** [comment]
群里问到的：
```
criData=/var/lib/containerd
registryData=/var/lib/registry
registryConfig=/etc/registry
registryDomain=sealos.hub
registryPort=5000
registryUsername=admin
registryPassword=passw0rd
```

**Comment by fanux** [comment]
嗯嗯，感谢建议，我们最近在全力迭代一个大版本，完成之后会重点花时间来做一下文档建设。 感谢博客推广～

**Comment by itzhoujun** [comment]
借楼推广博客：http://www.javajun.net/posts/112225/index.html

**Comment by cuisongliu** [comment]
> 群里问到的：
> 
> ```
> criData=/var/lib/containerd
> registryData=/var/lib/registry
> registryConfig=/etc/registry
> registryDomain=sealos.hub
> registryPort=5000
> registryUsername=admin
> registryPassword=passw0rd
> ```

多谢支持，其实所有的镜像都在https://github.com/labring/cluster-image  这个仓库，至于k8s的镜像https://github.com/labring/cluster-image/blob/main/rootfs/Kubefile  这里可看到所有支持的环境变量等。
