### ISSUE TITLE
Feature: 安装时增加日志路径配置

### ISSUE THREAD

**Issue by itzhoujun** [labring/sealos#1453]
**Which command or component**

sealos run

**Detailed description of the feature**
容器默认日志是写到/var/log/pods目录下，有可能将系统盘写满，建议增加-e参数指定日志目录

**Comment by fanux** [comment]
可以先使用 Clusterfile 自定义 kubelet 配置参数。 @cuisongliu 我们是否已经支持了环境变量的渲染？

**Comment by cuisongliu** [comment]
> 可以先使用 Clusterfile 自定义 kubelet 配置参数。 @cuisongliu 我们是否已经支持了环境变量的渲染？

支持的

**Comment by fanux** [comment]
@cuisongliu 是否支持 Clusterfile 配置文件渲染？

**Comment by cuisongliu** [comment]
> @cuisongliu 是否支持 Clusterfile 配置文件渲染？

支持的

**Comment by itzhoujun** [comment]
> 可以先使用 Clusterfile 自定义 kubelet 配置参数。 @cuisongliu 我们是否已经支持了环境变量的渲染？

怎么定义？Clusterfile里找不到kubelet配置，不知道往哪写

**Comment by fanux** [comment]
所有 kubeadm 的配置可以直接写在 Clusterfile 中，用 --- 隔开就行
