### ISSUE TITLE
Question: how to Easier  use custom parameters?

### ISSUE THREAD

**Issue by willzhang** [labring/sealos#1459]
**Which command or component**

sealos gen 

sealos apply

**The Description of the question**

When i want to add kubeadm init custom parameters, i must create an Clusterfile, and put it into Clusterfile

1、sealos gen xxx >Clusterfile , 

2、add follow content to Clusterfile 

```
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
skipPhases:
- addon/kube-proxy

```

3、sealos apply -f Clusterfile

any easy way ignore this operation? like

* build custom parameters to application images

* sealos run --custom-kubeadm-env=skipPhases:addon/kube-proxy

**Some reference materials you see**
eg. the reference of the documentation

**Comment by willzhang** [comment]
@cuisongliu

**Comment by fanux** [comment]
```
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
skipPhases:
- ${kube-proxy}
```
Add this Clusterfile into your image as default Clusterfile

Then:

```
sealos run -e kube-proxy='addon/kube-proxy' kubenetes:v1.12.4
```
