### ISSUE TITLE
Question:  does sealos has a delete api/interface for cluster or application 

### ISSUE THREAD

**Issue by loda13** [labring/sealos#1465]
have seen sealos_create api example:
`create a mysql cluster:

    sealos create mysql:8.0

with custom cluster name:

    sealos create mysql:8.0 -c mysql`
is this for creating diy application?
is there a corresponding delete interface,i've tried delete -c clustername, return:
`Error: node and master not empty in same time`

**Comment by fanux** [comment]
Now you need delete instance using helm or kubectl delete xxx-crd-instance.yaml.

In the feature, application will define it own actions, contains delete.

**Comment by fanux** [comment]
Error: node and master not empty in same time, is a bug..
