### ISSUE TITLE
pod启动后dns无法正常工作

### ISSUE THREAD

**Issue by overstarry** [labring/sealos#1472]
![image](https://user-images.githubusercontent.com/23260162/182827543-c361aff4-5845-49ff-9fe5-d47cf173dad4.png)
环境:
 labring/kubernetes:v1.23.0 
labring/calico:v3.22.1
sealos4
阿里云服务器

**Comment by overstarry** [comment]
![image](https://user-images.githubusercontent.com/23260162/182828762-c9a604d0-7715-4ee4-80ef-35b5a881391a.png)

**Comment by cuisongliu** [comment]
sealos run labring/coredns:v0.0.1

**Comment by overstarry** [comment]
![image](https://user-images.githubusercontent.com/23260162/182984118-5862383b-f774-4376-925a-e395c8df109f.png)
这样是正常的吗 @cuisongliu

**Comment by cuisongliu** [comment]
你看看croedns 的配置

**Comment by overstarry** [comment]
![image](https://user-images.githubusercontent.com/23260162/182984785-4b184117-2408-400c-8301-90f144263fd9.png)

**Comment by overstarry** [comment]
@cuisongliu
