### ISSUE TITLE
BUG: Sealos on centos7.9 based on arm64 problem: Segmentation fault

### ISSUE THREAD

**Issue by Axm11** [labring/sealos#1481]
**Which command or component**

sealos gen
sealos run
sealos
......

**The Description of the bug**

Describe the bug:
An error will be reported if any parameter is added or not when exec sealos，ERR info:
```bash
[root@arm-centos ~]# which sealos
/usr/bin/sealos
[root@arm-centos ~]# 
[root@arm-centos ~]# file /usr/bin/sealos
/usr/bin/sealos: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), statically linked, stripped
[root@arm-centos ~]#
[root@arm-centos ~]# sealos
Segmentation fault
[root@arm-centos ~]#
[root@arm-centos ~]# sealos gen
Segmentation fault
[root@arm-centos ~]#
[root@arm-centos ~]# sealos run
Segmentation fault
[root@arm-centos ~]#
[root@arm-centos ~]# sealos gen labring/kubernetes:v1.18.20-arm64  labring/calico:v3.22.1-arm64 --masters 192.168.x.x --pk > Clusterfile
Segmentation fault
```

**How to reproduce（pictures can be attached if necessary）**
1.  Buy an ecs instance on aliyun.com
2. System info：
os version：CentOS Linux release 7.9.2009 (AltArch)
kernel version：4.18.0-193.28.1.el7.aarch64
cpu/mem：2c/8g
![image](https://user-images.githubusercontent.com/22165259/183062403-c179a18f-935e-46b8-ae47-a1805db9ee91.png)

3. exec command flow：
`$ wget https://github.com/labring/sealos/releases/download/v4.0.0/sealos_4.0.0_linux_arm64.tar.gz \
   && tar zxvf sealos_4.0.0_linux_arm64.tar.gz sealos && chmod +x sealos && mv sealos /usr/bin`

Problem:
1. Is there a problem with sealos？
2. Or how do I execute makefile to get sealos?

**Comment by cuisongliu** [comment]
Keep paying attention to it. #1688
