### ISSUE TITLE
Format: CLI's print column style is not uniform

### ISSUE THREAD

**Issue by runkecheng** [labring/sealos#1484]
**Which command or component**

```
sealos
```

**The Description of the bug**

![image](https://user-images.githubusercontent.com/68526782/183231389-61bccecf-5a4d-4409-8339-dcdfe44a1fa5.png)

Some of first letters are uppercase and some are lowercase

**How to reproduce（pictures can be attached if necessary）**

**Test Result**

**What you expected to happen**

**Operating environment**

**Comment by zzjin** [comment]
Thank you for document issue!

You can help to update it right click link here: [cmd dir](https://github.com/labring/sealos/tree/main/cmd/sealos/cmd) to start contribution! Any PRs are welcome!
