### ISSUE TITLE
Feature: Support push helm charts to private registry

### ISSUE THREAD

**Issue by willzhang** [labring/sealos#1488]
**Which command or component**

sealos build

**Detailed description of the feature**

support push helm charts to private registry.

**If you have solution，please describe it**

refer:https://helm.sh/zh/docs/topics/registries/

```
helm pull charts

# how do it when run sealos build?
helm push charts sealos.hub:5000/helm-charts/$app-name
```

```
echo '{mariadb.auth.database: user0db, mariadb.auth.username: user0}' > values.yaml
```

```
FROM scratch
COPY . .
CMD ["helm upgrade --install $app-name --repo sealos.hub:5000/helm-charts/$app-name -f values.yaml"]
```

**Comment by cuisongliu** [comment]
reopen

**Comment by willzhang** [comment]
helm not support push to http registry yet: https://github.com/helm/helm/pull/10408

**Comment by cuisongliu** [comment]
1. sealos run openebs
   docker.io/labring/openebs:v3.4.0
2. sealos run cert-manager
   docker.io/labring/cert-manager:v1.8.0
3. sealos run zot:v1.4.3
   docker.io/labring/zot:v1.4.3
