### ISSUE TITLE
Bug: sealos 4.0 fail when first run spec multi master nodes.

### ISSUE THREAD

**Issue by lIlIlllllmeng** [labring/sealos#1493]
### **操作系统版本：CentOS Linux release 7.9.2009 (Core) 内核版本：Linux master 4.19.12 执行命令：sealos run labring/kubernetes:v1.19.2 labring/calico:v3.22.1      --masters 192.168.100.111,192.168.100.112      --nodes 192.168.100.113  -p root**

sealos 4.0 labring/kubernetes:v1.19.2 labring/calico:v3.22.1 双master出现安装报错
![图片](https://user-images.githubusercontent.com/94682166/183335482-eeba42c9-edb1-4cba-830c-07cc8e927559.png)
![图片](https://user-images.githubusercontent.com/94682166/183335503-95699ddd-cc98-4819-8082-d34ba8e70a73.png)

**Comment by cuisongliu** [comment]
![image](https://user-images.githubusercontent.com/4150905/183357139-19e60df3-a873-477d-8ac7-18ef9634bdc0.png)
docker？？？？？

**Comment by lIlIlllllmeng** [comment]
> ![image](https://user-images.githubusercontent.com/4150905/183357139-19e60df3-a873-477d-8ac7-18ef9634bdc0.png) docker？？？？？

用的4.0的版本，好像服务器上还没有Docker
![图片](https://user-images.githubusercontent.com/94682166/183359299-e8655c8e-2cbb-471a-aa8a-95388857d92a.png)

**Comment by fanux** [comment]
@lIlIlllllmeng seems the labring/kubernetes:v1.19.2 has some issue. Try to use labring/kubernetes:v1.24.0

**Comment by cuisongliu** [comment]
<img width="795" alt="image" src="https://user-images.githubusercontent.com/4150905/184520827-c510be95-8e9d-416b-b9f1-33d8112e2b6f.png">

在目标主机上执行命令看输出什么报错。
