### ISSUE TITLE
Feature: Apply `service/auth` auth.yaml to casdoor

### ISSUE THREAD

**Issue by zzjin** [labring/sealos#1495]
### Current Implementation Description
When we start a new `service-auth`, for example, first run `kubectl apply casdoor.yaml` + `kubectl apply auth.yaml`
we create a new `service-auth` service with a new `casdoor` runtime and apply the oauth params into it, it works fine.

### Problem
After service started, we want to add/edit some oauth providers or change the callback urls, we cannot just apply the new `auth.yaml` as it is using k8s's `configmap` to manage states, witch `casdoor` is not ever handle it.
Result in no updates will pass to `casdoor` at all.

### Possible Solution
Split `configmap` into two formats(but keep one yaml config?):
1. The `port`/`nodePort` and/or `casdoor`'s sso page config keep using `configmap` as it is used by communications between `service-auth` and `k8s` and `casdoor`.
2. Configs of `OAuth Providers` and other changes will direct update to `casdoor`'s backend using `casdoor`'s `sdk` or `api` call.

**Comment by fanux** [comment]
1. Support readconfig from ENV too.
2. Using some auto update pod when configmap changed controller. like [reloader](https://github.com/stakater/Reloader)

**Comment by zzjin** [comment]
> 

1. Agree to fully remove usage of `configmap` to env or flag
2. Create a new controller just for reconcile config witch only matched `casdoor`'s backend needs is too heavy, as `casdoor`'s backend is not keep its config under k8s etcd. So just get config from `casdoor`'s api and apply to it is enough.

**Comment by Abingcbc** [comment]
The structure of the provider is a bit complicated. Could we pass in a json string as an environment variable?

**Comment by zzjin** [comment]
I think we can just pass yaml conf files like currently implication, and `echo auth.yaml | ./service-auth -f -- -` will do.
`env` can change configs like `port`,`ssoEndpoint` easily, and we can support thing like this.
But Different `oauth` providers have differ configs(from strings to arrays, different names etc), so likely we do not need to support these using env.

Conclusion:
1. Support `env`s for prefer situation.
2. Update support full config using `yaml`.
