### ISSUE TITLE
sealos4.0 安装kuboard时，etcd端口被占用问题

### ISSUE THREAD

**Issue by cype62** [labring/sealos#1508]
直接kubectl apply之后，kuboard的etcd起不来，提示端口占用

![EF255642429F091B50467B213BDC3A5E](https://user-images.githubusercontent.com/37395207/183797038-47520203-55c1-48fc-bc0b-b0c8e05d0bfa.jpg)

**Comment by fanux** [comment]
这个问题在 kuboard 仓库提个 issue 可能更合适一些哈，目测是 kuboard 又起了一个仓库
