### ISSUE TITLE
Feature: query aws instance price

### ISSUE THREAD

**Issue by fanux** [labring/sealos#1513]
China: https://docs.amazonaws.cn/aws/latest/userguide/billing-and-payment.html#price-list

 Global: https://docs.amazonaws.cn/awsaccountbilling/latest/aboutv2/using-pelong.html

**Comment by fanux** [comment]
```
func QueryPrice(infra *v1.Infra) (int64, error)
```

**Comment by HURUIZHE** [comment]
func (i *Infra) QueryPrice() (int64, error)  
completely

**Comment by HURUIZHE** [comment]
https://www.amazonaws.cn/ec2/pricing/ec2-linux-pricing/
