### ISSUE TITLE
Sealos 4.0 arm  Kylin Linux Advanced Server release V10 ;failed symlink

### ISSUE THREAD

**Issue by fungeZuo** [labring/sealos#1516]
arm  Kylin Linux Advanced Server release V10  (Sword) ; 10.10.65.162 is Private image library.

uname -r
5.4.105-200.el7.aarch64

cat /etc/hosts
#Modified By Ufgov
#LocalHost
127.0.0.1      localhost  localhost.com
#APP host
10.10.65.163    ufapp163
10.10.65.162    ufapp162

sealos run \
>   --masters 10.10.65.163 \
>   --nodes 10.10.65.164,10.10.65.165 -p Ufgov@1234 \
>   10.10.65.162/library/kubernetes:v1.23.8 \
>   10.10.65.162/library/calico:v3.22.1 \
>   10.10.65.162/library/helm:v3.8.2 \
>   10.10.65.162/library/ingress-nginx:4.1.0 \
>   10.10.65.162/library/cert-manager:v1.8.0 \
>   10.10.65.162/library/kube-apiserver:v1.23.8 \
>   10.10.65.162/library/kube-controller-manager:v1.23.8 \
>   10.10.65.162/library/kube-scheduler:v1.23.8 \
>   10.10.65.162/library/kube-proxy:v1.23.8 \
>   10.10.65.162/library/pause:3.6 \
>   10.10.65.162/library/etcd:3.5.1-0 \
>   10.10.65.162/library/coredns:v1.8.6

Sealos 4.0 arm  Kylin Linux Advanced Server release V10  (Sword);failed symlink

Describe the bug.

10.10.65.163:22:  INFO [2022-08-10 11:20:09] >> init kube success 
10.10.65.163:22:  INFO [2022-08-10 11:20:09] >> init containerd rootfs success 
2022-08-10 11:20:09 [EROR] Applied to cluster error: copy container default-1ngtwj2u app rootfs failed symlink ../usr/lib/os-release /var/lib/sealos/data/default/rootfs/etc/os-release: file exists
2022-08-10 11:20:09 [INFO] 
      ___           ___           ___           ___       ___           ___
     /\  \         /\  \         /\  \         /\__\     /\  \         /\  \
    /::\  \       /::\  \       /::\  \       /:/  /    /::\  \       /::\  \
   /:/\ \  \     /:/\:\  \     /:/\:\  \     /:/  /    /:/\:\  \     /:/\ \  \
  _\:\~\ \  \   /::\~\:\  \   /::\~\:\  \   /:/  /    /:/  \:\  \   _\:\~\ \  \
 /\ \:\ \ \__\ /:/\:\ \:\__\ /:/\:\ \:\__\ /:/__/    /:/__/ \:\__\ /\ \:\ \ \__\
 \:\ \:\ \/__/ \:\~\:\ \/__/ \/__\:\/:/  / \:\  \    \:\  \ /:/  / \:\ \:\ \/__/
  \:\ \:\__\    \:\ \:\__\        \::/  /   \:\  \    \:\  /:/  /   \:\ \:\__\
   \:\/:/  /     \:\ \/__/        /:/  /     \:\  \    \:\/:/  /     \:\/:/  /
    \::/  /       \:\__\         /:/  /       \:\__\    \::/  /       \::/  /
     \/__/         \/__/         \/__/         \/__/     \/__/         \/__/

                  Website :https://www.sealos.io/
                  Address :github.com/labring/sealos

![NVUGVL 49{@4888(ZE2II C](https://user-images.githubusercontent.com/36251109/183854421-ffb91b4e-f904-42c5-af2a-832b7c11931e.png)

**Comment by cuisongliu** [comment]
Repeated bugs
