### ISSUE TITLE
sealos run 报错：改过hostname并重启后仍然报错hostname重复

### ISSUE THREAD

**Issue by HURUIZHE** [labring/sealos#1519]
[![sealos run](https://i.postimg.cc/9QCBDYMb/RYY3215-SHKI-BVQB-XTLNQ.jpg)](https://postimg.cc/F7CSqc0k)
[![hostname](https://i.postimg.cc/9QCBDYMb/RYY3215-SHKI-BVQB-XTLNQ.jpg)](https://postimg.cc/F7CSqc0k)

**Comment by HURUIZHE** [comment]
**hostname:**
[![hostname](https://i.postimg.cc/9QCBDYMb/RYY3215-SHKI-BVQB-XTLNQ.jpg)](https://postimg.cc/F7CSqc0k)

**Comment by HURUIZHE** [comment]
**hostname:**
[![hostname](https://i.postimg.cc/ydjKzPkG/CTO6-P4-GLOZ-UO56-IT1-XR18-M.jpg)](https://postimg.cc/628grCVV)

**Comment by fanux** [comment]
your node host name is?

https://github.com/labring/sealos/blob/main/pkg/checker/host_checker.go

**Comment by HURUIZHE** [comment]
> your node host name is?
> 
> https://github.com/labring/sealos/blob/main/pkg/checker/host_checker.go

原name是ip地址，我通过hostnamectl set-name改成了"node"，但我没有改文件，或许是这个问题?

**Comment by HURUIZHE** [comment]
> > your node host name is?
> > https://github.com/labring/sealos/blob/main/pkg/checker/host_checker.go
> 
> 原name是ip地址，我通过hostnamectl set-name改成了"node"，但我没有改文件，或许是这个问题?

目前已经改用虚拟机,这个问题不存在了

**Comment by cuisongliu** [comment]
cloud-init 的问题
