### ISSUE TITLE
执行 sealos run labring/kubernetes:v1.24.0 labring/calico:v3.22.1 报错

### ISSUE THREAD

**Issue by yjx-show** [labring/sealos#1521]
执行 ：sealos run labring/kubernetes:v1.24.0 labring/calico:v3.22.1
报错
2022-08-12 13:11:43 [EROR] Applied to cluster error: read admin.conf error in guest: path is /var/lib/sealos/data/default/etc/admin.conf no such file

- Docker version:   19.03.9
- Kubernetes version: kubernetes:v1.24.0
- Sealos version: v4.0
- Operating system: CentOS Linux release 8.4.2105

**Comment by cuisongliu** [comment]
是第一次执行安装操作么，这个应该是需要加--masters --nodes

**Comment by atdasi** [comment]
请问 解决了吗
