### ISSUE TITLE
4.0版本是否支持离线场景下安装？

### ISSUE THREAD

**Issue by GreatLazyMan** [labring/sealos#1526]
离线环境无法拉取k8s.gcr.io的镜像（即使能连公网网络环境所限也不一定能拉到k8s.gcr.io的镜像）。

参考 *https://github.com/labring/sealos/blob/main/docs/4.0/docs/getting-started/customize-cluster.md* 的思路，在 *ClusterConfiguration* 中配置了 *imageRepository* ，但是配置的私有http仓库，而containerd中endpoint没有修改，拉取镜像还是存在问题。

想请教一下，4.0版本是否支持纯离线场景的部署？

**Comment by cuisongliu** [comment]
> 离线环境无法拉取k8s.gcr.io的镜像（即使能连公网网络环境所限也不一定能拉到k8s.gcr.io的镜像）。
> 
> 参考 _https://github.com/labring/sealos/blob/main/docs/4.0/docs/getting-started/customize-cluster.md_ 的思路，在 _ClusterConfiguration_ 中配置了 _imageRepository_ ，但是配置的私有http仓库，而containerd中endpoint没有修改，拉取镜像还是存在问题。
> 
> 想请教一下，4.0版本是否支持纯离线场景的部署？

目前是支持离线环境的，默认会从image-cri-shim进行replace 的。你看一下crictl images

**Comment by cuisongliu** [comment]
如果是centos需要拉取一下最新镜像，之前版本的离线镜像又bug。
