### ISSUE TITLE
Feature: Upgrade the cluster without loss

### ISSUE THREAD

**Issue by myselfghost** [labring/sealos#1531]
**Which command or component**

I am the maintainer of a production cluster and I have some questions about the maintenance of the production cluster.

**Detailed description of the feature**
1.  How to upgrade the version without loss, such as upgrading from 1.23.x to 1.24.x ？
2. In a production cluster, we wan to optionally add additional SANs (hostnames or IPs)  to the API server PKI certificate,how to update ?

**Comment by fanux** [comment]
2. you can use [Clusterfile](https://www.sealos.io/docs/getting-started/customize-cluster) sealos to support all the kubeadm config in Clusterfile

1.  In the feature, just change the image name in Clusterfile and reapply it, sealos will upgrade the cluster (in developing)

**Comment by myselfghost** [comment]
> 2. you can use [Clusterfile](https://www.sealos.io/docs/getting-started/customize-cluster) sealos to support all the kubeadm config in Clusterfile
> 3. In the feature, just change the image name in Clusterfile and reapply it, sealos will upgrade the cluster (in developing)

@fanux 
I'm not talking about the first installation, I just use SANs as an example, how to adjust the parameters after installation in a production cluster.

**Comment by fanux** [comment]
@myselfghost sealos cert command will support add SANS
