### ISSUE TITLE
BUG: sealos rmi error 'image is in use by a container'

### ISSUE THREAD

**Issue by 1oda** [labring/sealos#1535]
![微信截图_20220815152926](https://user-images.githubusercontent.com/10447318/184596365-bbea33bc-844b-4f5a-812b-9b34e22062ec.png)
![微信截图_20220815152851](https://user-images.githubusercontent.com/10447318/184596374-71c466ac-3000-42c5-b81e-0048016b39ce.png)
已经`sealos reset --force`之后，发现清理镜像报错
机器上已经没有containerd或者docker的环境了

**Comment by cuisongliu** [comment]
sealos rmi -f

**Comment by 1oda** [comment]
ok，解决了
