### ISSUE TITLE
Question: after 'sealos apply -f Cluster' create some diy，手动卸载，再次单独使用sealos安装不生效，'no change apps'

### ISSUE THREAD

**Issue by 1oda** [labring/sealos#1537]
使用sealos初始化集群时，自定义Clusterfile拉起了以下镜像
`  - labring/kubernetes:v1.24.0
  - labring/calico:v3.22.1
  - demo/ingress-nginx:v4.2.1
  - demo/kubernetes-dashboard:v5.8.0`
 
![image](https://user-images.githubusercontent.com/10447318/184611494-730f0e97-8ee8-4526-b9fd-10eae5b68fe4.png)

**在初始化后**，运行`sealos run labring/test:v1.1`
拉起了一个test应用**成功**

![image](https://user-images.githubusercontent.com/10447318/184611553-ef088a38-6aaa-4c6b-9a87-3b655e6b7dfa.png)

使用helm卸载以下应用后
`  - demo/ingress-nginx:v4.2.1
  - demo/kubernetes-dashboard:v5.8.0`
![微信截图_20220815152851](https://user-images.githubusercontent.com/10447318/184611666-d9a58782-0f34-47eb-a3d4-7f7b6c58bba0.png)

再次使用类似拉起命令
`sealos run demo/kubernetes-dashboard:v5.8.0`
发现没有改变
![微信截图_20220815172356](https://user-images.githubusercontent.com/10447318/184611704-919b0f33-a5e5-404d-9407-a81ae03474ba.png)

Question: 当前是否不支持类似卸载后再次单独拉起镜像的功能
后续是否支持？

**Comment by fanux** [comment]
加个 -f 参数

**Comment by 1oda** [comment]
> 加个 -f 参数

works
