### ISSUE TITLE
BUG: OOM when sealos run 

### ISSUE THREAD

**Issue by berlinsaint** [labring/sealos#1545]
**Which command or component**
selaos run
Get Stuck in run ,  and machine is nearly dead(4c16g)
**How to reproduce（pictures can be attached if necessary）**
1.  sealos run registry.cn-qingdao.aliyuncs.com/labring/athenaserving:v2.0.0rc1
...

**Test Result**
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/10629930/184782563-931a9f70-ffd3-445f-b9ca-4aa091d005f6.png">

<img width="929" alt="image" src="https://user-images.githubusercontent.com/10629930/184782386-43a79ec9-d604-4e9a-b117-28d5d59356c2.png">

**What you expected to happen**

Expected to not have oopm,

**Operating environment**

- Docker version:   eg. 19.03
- Kubernetes version: eg.kube1.19.13.tar.gz
- Sealos version: 4.0.0
- Operating system: bionic

**Comment by berlinsaint** [comment]
Done. seems that  helm chart  may have some restrictions , for example, if  the registry dir is not put at the right place. @cuisongliu, we should add this in the doc about how to make cluster-images

**Comment by cuisongliu** [comment]
> Resolved. seems like that helm chart may have some restrictions , for example, if the registry dir is not put at the right place. @cuisongliu, we should add this in the doc about how to make cluster-images

https://github.com/labring/cluster-image  add docs for cluster-images
