### ISSUE TITLE
Is there any plan to support terraform?

### ISSUE THREAD

**Issue by ErikXu** [labring/sealos#1546]
Though sealos is very convenient to setup an kubernetes cluster using CLI. I want to use `terraform` to manage my infrastructure depands on the `IaC` concept. So is there any plan to provide a sealos provider to support terraform? Thanks!

**Comment by fanux** [comment]
Yes, the infra module can add a terraform module, but some drives have low performance like alicloud driver, need 3min to start an infra cluster, and call too many useless api, sealos infra driver module only need 30s.

https://github.com/labring/sealos/tree/main/controllers/infra#create-infra
