### ISSUE TITLE
Question: sealos run when one of Dockerfile cmd run err, sealos run exit immediately，is there a way to ignore the error

### ISSUE THREAD

**Issue by 1oda** [labring/sealos#1564]
![XS$A_DH7VJ NS1RBYC4@Z1V](https://user-images.githubusercontent.com/10447318/185157565-23a5349b-24be-499e-9e33-14291b61ce62.png)

运行镜像里的cmd遇到错误时，可以支持忽略错误，执行后续cmd吗，现在直接退出了
`[EROR] Applied to cluster error: exit status 1`

**Comment by fanux** [comment]
CMD ["kubectl apply -f dashboard.yaml || true"]

**Comment by 1oda** [comment]
> CMD ["kubectl apply -f dashboard.yaml || true"]

got
