### ISSUE TITLE
sealos apply -f Clusterfile 报错

### ISSUE THREAD

**Issue by gcpss** [labring/sealos#1566]
![A%Y5(NF6)6C}TRM~H5~P46O](https://user-images.githubusercontent.com/51896005/185282177-31b77231-387d-43cf-a3fd-b4f592ba5e85.png)
![SJLMPRR%`522$)H$)3NJVQ6](https://user-images.githubusercontent.com/51896005/185282201-0329a19d-5aa9-444e-9f20-d47131978f15.png)
![WZ8HM%YJA0A~SA _2OH1B3C](https://user-images.githubusercontent.com/51896005/185282229-0917f04b-e869-4c89-b334-7fc457e84824.png)
kubelet查看一直是未启动状态，kubectl get pod 报 The connection to the server localhost:8080 was refused - did you specify the right host or port?

docker安装包已经完全卸载。

**Comment by cuisongliu** [comment]
crictl ps -a

**Comment by gcpss** [comment]
![image](https://user-images.githubusercontent.com/51896005/185287516-69b4a70a-1053-45de-ba42-9b035c538892.png)

**Comment by fanux** [comment]
sealos version

and show us your Clusterfile

**Comment by cuisongliu** [comment]
得看一下kubelet 日志了 具体的日志发一下？

**Comment by gcpss** [comment]
![image](https://user-images.githubusercontent.com/51896005/185343696-de1c3c4c-edd1-4c98-acf6-5985c384a2f7.png)

**Comment by gcpss** [comment]
[root@master ~]# cat Clusterfile 
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  creationTimestamp: null
  name: default
spec:
  hosts:
  - ips:
    - 192.168.239.69:22
    roles:
    - master
    - amd64
  - ips:
    - 192.168.239.68:22
    - 192.168.239.67:22
    roles:
    - node
    - amd64
  image:
  - labring/kubernetes:v1.24.0
  - labring/calico:v3.22.1
  ssh:
    pk: /root/.ssh/id_rsa
    port: 22
    user: root
    passwd: root
status: {}

**Comment by gcpss** [comment]
![image](https://user-images.githubusercontent.com/51896005/185343939-ee5eafb9-1778-47a8-9ce3-44c45696bd3c.png)

**Comment by cuisongliu** [comment]
![image](https://user-images.githubusercontent.com/4150905/185344292-96c7c0de-9021-436f-9c9b-b53a8ca3003d.png)
应该是系统创建不出来cgroup导致

**Comment by gcpss** [comment]
我先下docker自己改驱动吗？

**Comment by cuisongliu** [comment]
> 我先下docker自己改驱动吗？

你把报错搜一下 我记得是操作系统需要装个什么东西、

**Comment by gcpss** [comment]
可以了，谢谢，就是systemd版本低了。用yum info systemd查看一下可用版本
