### ISSUE TITLE
Deep into IP 10.103.97.2

### ISSUE THREAD

**Issue by ErikXu** [labring/sealos#1577]
Sealos will involve the VIP `10.103.97.2` to handle the` multiple net card` problem. Refer: <https://github.com/labring/sealos/blob/release-v4.0.0/docs/3.0/command/route.md>.

1. If there is a VM with IP `10.103.97.2` in the VPC, they are conflicted?

    I should avoid assign IP `10.103.97.2` to a VM or I need to use another VIP?

2. If I use sealos to setup two clusters in one VPC, The two VIPs are conflicted?

    I should use two different VIPs in different clusters?

If so, is it possible to provide a parameter to the `seal run` command or `Clusterfile ` to indicate the ipvs VIP?

**Comment by fanux** [comment]
1. If there is a VM with IP 10.103.97.2 in the VPC, they are conflicted? YES should not use 10.103 subnet
2. No conflict in theory. 

You don't need to care about this field in most scenarios

For more inquiries please fill out this [form](https://wj.qq.com/s2/10668306/bbba/)
