### ISSUE TITLE
sealos4.0  安装k8s1.22.5失败

### ISSUE THREAD

**Issue by YangShuailing** [labring/sealos#1594]
**Which command or component**

 sealos4 run labring/kubernetes:v1.22.5 labring/calico:v3.22.1      --masters 10.118.3.126  --name myk8s  --passwd 'K8s@12345'

**The Description of the bug**

Describe the bug.

**How to reproduce（pictures can be attached if necessary）**
安装失败：
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/8296374/185857990-f1a9a4d6-d12a-4d6b-9f6f-09fe692fb7cb.png">
#systemctl status containerd
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/8296374/185858178-71468d70-22e4-4e58-a9be-8eea1b6a5d86.png">

 # systemctl status image-cri-shim
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/8296374/185858277-af4ff59a-59e4-4a97-a95a-1454ba54c291.png">
# systemctl status kubelet
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/8296374/185858514-cbe26c9f-dd3a-4cf5-81df-f8f25284958b.png">

registry没有启动
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/8296374/185858652-0c010199-3a5b-4e23-9df0-1d367906f366.png">

...

**Operating environment**

- Kubernetes version: 1.22.5
- Sealos version: v4.0.0
- Operating system: Linux FVCLOD-2 4.18.0-305.el8.x86_64 #1 SMP Thu Apr 29 08:54:30 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
- Runtime environment: vm (15G memory, 10 core cpu, 200G storage)
- Cluster size: 1 master, 0 node
- Additional information: none

**Comment by fanux** [comment]
`nerdctl ps`

**Comment by YangShuailing** [comment]
1、 
nerdctl ps
registr没有启动，
手动起了registry，containerd，kubelet，报错一样。
nerdctl run -d -p 5000:5000 -v /var/lib/registry:/var/lib/registry registry:2
2、containerd报错去sealos.hub拉取镜像，但是host配置的是selayun.hub，手动增加一条host解析，依旧报错。
`failed to pull and unpack image \"sealos.hub:5000/pause:3.5\": failed to resolve reference \"sealos.hub:5000/pause:3.5\": sealos.hub:5000/pause:3.5: not found"`
hosts文件里只有这一条记录，
` 10.118.2.116 selayun.hub `
手动加了一条
10.118.2.116 selayun.hub sealos.hub

<img width="680" alt="image" src="https://user-images.githubusercontent.com/8296374/186042344-fa1a1f31-a4f8-4664-955c-494bd866b27f.png">

**Comment by fanux** [comment]
`pull sealos.hub:5000/kube-apiserver:v1.22.5`

**Comment by cuisongliu** [comment]
10.118.3.126 sealos.hub 


加这个记录

**Comment by fanux** [comment]
似乎已经加了？

**Comment by muicoder** [comment]
https://github.com/labring/cluster-image/pull/125

`v1.15.0`/`v1.24.4`已经验证。

**Comment by YangShuailing** [comment]
选择4.1重装了
