### ISSUE TITLE
用sealos安装的kube-prometheus-stack怎么修改prometheus configmap

### ISSUE THREAD

**Issue by majulong** [labring/sealos#1598]
# Prometheus stack
$ sealos run labring/kube-prometheus-stack:v0.56.0
![image](https://user-images.githubusercontent.com/45955327/186048410-373d2d62-c9b5-45d2-9b46-7ae3f40d50ed.png)
找不到configmap.yaml的文件
请问怎么修改prometheus配置

**Comment by fanux** [comment]
kubectl edit prometheus CR

**Comment by majulong** [comment]
![image](https://user-images.githubusercontent.com/45955327/186059070-7dce29bd-b9e5-4f38-8d63-817f2370090f.png)

**Comment by fanux** [comment]
`helm list -A` then using helm to update the values: https://github.com/bitring/realai/blob/main/kube-prometheus-stack/kube-prometheus-stack.values
