### ISSUE TITLE
Feature: Integrating link mode based lvscare into sealos

### ISSUE THREAD

**Issue by fengxsong** [labring/sealos#1601]
Since `lvscare` already implement ipvs load balancing with link mode, maybe it's time to integrate it into sealos?

1. proposal 1, implemented directly in `KubeadmRuntime`, but this way there will be a lot of changes to do

2. provide a subcommand for patching all lvscare static pod in all masters and nodes.

**Comment by cuisongliu** [comment]
https://github.com/labring/sealos/issues/1441

**Comment by fengxsong** [comment]
OK, so let's discuss this in https://github.com/labring/sealos/issues/1441
