### ISSUE TITLE
BUG: 不支持部署多master情况下使用外部etcd集群方式

### ISSUE THREAD

**Issue by henryhyang** [labring/sealos#1612]
当使用外部etcd集群时，用sealos部署多master的k8s集群，join master时报错：

[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
I0823 18:12:13.244239  129682 checks.go:834] using image pull policy: IfNotPresent
I0823 18:12:13.266949  129682 checks.go:843] image exists: k8s.gcr.io/kube-apiserver:v1.24.3
I0823 18:12:13.284204  129682 checks.go:843] image exists: k8s.gcr.io/kube-controller-manager:v1.24.3
I0823 18:12:13.300357  129682 checks.go:843] image exists: k8s.gcr.io/kube-scheduler:v1.24.3
I0823 18:12:13.317180  129682 checks.go:843] image exists: k8s.gcr.io/kube-proxy:v1.24.3
I0823 18:12:13.333644  129682 checks.go:843] image exists: k8s.gcr.io/pause:3.7
I0823 18:12:13.358896  129682 checks.go:843] image exists: k8s.gcr.io/coredns/coredns:v1.8.6
[download-certs] Downloading the certificates in Secret "kubeadm-certs" in the "kube-system" Namespace
I0823 18:12:13.362238  129682 round_trippers.go:553] GET https://apiserver.cluster.local:6443/api/v1/namespaces/kube-system/secrets/kubeadm-certs?timeout=10s 200 OK in 2 milliseconds
the Secret does not include the required certificate or key - name: external-etcd.crt, path: /etc/k8s/cert/etcd.pem
k8s.io/kubernetes/cmd/kubeadm/app/phases/copycerts.DownloadCerts
        cmd/kubeadm/app/phases/copycerts/copycerts.go:240
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/join.runControlPlanePrepareDownloadCertsPhaseLocal
        cmd/kubeadm/app/cmd/phases/join/controlplaneprepare.go:239
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
......

看代码 upload-certs时没有带kubeadm配置参数，sealos其它代码也没有支持外部etcd集群：
const uploadCertTemplate = "kubeadm init phase upload-certs --upload-certs --certificate-key %s"

希望修复这个问题，使用外部etcd集群的场景还是不少的，Thank you。

Operating environment

Kubernetes version: 1.24.3
Sealos version: v4.0.0
Operating system: Linux 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Runtime environment: vm (32G memory, 8 core cpu, 200G storage)
Cluster size: 2 master, 1 node
Additional information: none

**Comment by cuisongliu** [comment]
直接调整KubeadmInitConfig 就可以了。

**Comment by fanux** [comment]
不支持外部 etcd, 想了解一下为什么必须要使用外部 etcd?

**Comment by henryhyang** [comment]
用k8s推荐的内部etcd，有点问题。这种外部etcd使用的还是不少，能支持吗？目前自己改造了一下，先用着

**Comment by willzhang** [comment]
> 

安全性高吧，遇到有客户有这种要求。

**Comment by fanux** [comment]
sealos 的自定义 kubeadm 配置就能支持，不过我们非常不推荐这样玩。希望这块更标准化一些，就和你用 windows 不会关心注册编译表存在哪个目录一样。
