### ISSUE TITLE
Feature: Image CRD Image hub

### ISSUE THREAD

**Issue by fanux** [labring/sealos#1615]
Add image controller. Store need this CRD

`sealos push kuberetes:v1.25.0`  registry, sealos push need to apply image CRD.

`kubectl get AppImage kubernetes -oyaml`

**Comment by fanux** [comment]
<img width="877" alt="image" src="https://user-images.githubusercontent.com/8912557/186402266-07560160-96ee-42fb-9bdb-de5ad06bfdc4.png">

**Comment by zzjin** [comment]
Maybe image. hub is not benifit from crd controller.

Pros:
1. Build in k8s manage enabled , such as `kubctl`, k8s ui(crd section) support.

Cons:
1. Implemetion `coment`/`rate`/`installed count` data will update frequently as crd will not fit.
2. we will also implement an `api-frontend` to expose `api-server`-`image hub crd` to let seos accesalbe.

**Comment by fanux** [comment]
Seems next.js is very suitable for developing imagehub

**Comment by fanux** [comment]
Pros:
1. use apiserver token or kubeconfig, separate authentication is no longer required
2. No need to introduce a database

Cons:
1. How to search images?

---
about performance:

1. Satisfy performance requirements for a considerable period of time. I think this arch can serve 10k+ developers.
2. We can use an interface, If the performance is not satisfied, this interface can be reimplemented on pgsql
3. Apiserver also support using other storage to replace etcd

about expose api-server:

Just use next.js server side to query apiserver.

**Comment by zzjin** [comment]
> 3\. Apiserver also support using other storage to replace etcd

We need structed database along side with etcd. Not replace it?

**Comment by fanux** [comment]
We can do this when we need it, etcd can meet performance requirements for a long time
