### ISSUE TITLE
BUG: upgrade calico on kubernetes v1.25.0

### ISSUE THREAD

**Issue by fanux** [labring/sealos#1625]
![image](https://user-images.githubusercontent.com/8912557/186636524-43647426-2049-41ee-b029-008f542bca71.png)

**Comment by cuisongliu** [comment]
https://projectcalico.docs.tigera.io/release-notes/ 
v3.24.0+ caclio

**Comment by muicoder** [comment]
https://github.com/labring/cluster-image/pull/125

`v1.15.0`/`v1.24.4`已经验证。
