### ISSUE TITLE
Question: sealos will not use local images if there is a newer one remote?

### ISSUE THREAD

**Issue by ErikXu** [labring/sealos#1633]
**Which command or component**

sealos run 

**The Description of the question**

I want to make the installation faster in another machine and do the following:

1. Use `sealos pull` to pull the necessary images:

``` bash
[root@master]# sealos images
REPOSITORY                     TAG       IMAGE ID       CREATED        SIZE
docker.io/labring/kubernetes   v1.24.0   aa7a10834aae   3 weeks ago    594 MB
docker.io/labring/calico       v3.22.1   a346a0448719   2 months ago   764 MB
```

2. Use `sealos save` to save the images. 

5. Use `sealos load` to move the images to a new machine.

6. Use  `sealos run` to install a new cluster, but sealos will pull a newer image if existed remote:

``` bash
[root@master-new]# sealos images
REPOSITORY                     TAG       IMAGE ID       CREATED        SIZE
docker.io/labring/kubernetes   v1.24.0   3f288950f080   38 hours ago   643 MB    # pull a newer one
<none>                         <none>    aa7a10834aae   3 weeks ago    594 MB    # the previous one is set to none
docker.io/labring/calico       v3.22.1   a346a0448719   2 months ago   764 MB
```

**Comment by cuisongliu** [comment]
buildah default using --pull options , need delete it. --pull using options to sealos .

**Comment by yyf1986** [comment]
I'll fix it

**Comment by yyf1986** [comment]
I checked the parameters of buildah and did not find any difference.But the two ways are really different.

**Comment by muicoder** [comment]
> buildah default using --pull options , need delete it. --pull using options to sealos .

buildash pull --help
   --policy string                 missing, always, or never. (default "missing")
