### ISSUE TITLE
sealos delete节点后再add报错

### ISSUE THREAD

**Issue by itzhoujun** [labring/sealos#1641]
虚拟机重启之后出现了这个问题：https://github.com/labring/sealos/issues/1619

无法解决，只要先delete节点，再add，但是也报错了：
![image](https://user-images.githubusercontent.com/6897671/186894363-7905e7e7-1500-46d5-88ba-722c1600f04c.png)

**Comment by cuisongliu** [comment]
#1640  at add nodes logic fix it.
