### ISSUE TITLE
Feature: 建议默认支持 nerdctl compose，减少从docker项目迁移的工作量

### ISSUE THREAD

**Issue by maxid** [labring/sealos#1648]
**Which command or component**

对于nerdctl compose还是有用户需要用到的，所以建议默认支持，减少从docker项目迁移的工作量

**Detailed description of the feature**
目前sealos v4安装后的 /opt/cni/bin 下缺少 bridge 和 firewall 插件，导致 nerdctl compose 无法创建 bridge 网络，从而启动失败

**If you have solution，please describe it**

Complete this feature through XXX
对于nerdctl 的版本，从官方下载对应的nerdctl-full版本，将nerdctl-full-xx/libexec/cni下的 bridge、firewall拷贝至/opt/cni/bin下，问得到了解决

**Comment by cuisongliu** [comment]
后面直接使用docker 的镜像，这个还在开发中
