### ISSUE TITLE
Feature: brief description of the feature

### ISSUE THREAD

**Issue by Kabulaka** [labring/sealos#1649]
**Which command or component**
how to upgrade to sealos4 is a problem, because the production environment is sealos3.

**Detailed description of the feature**
1. provides a way to upgrade from sealos3 to sealos4, eg: `sealos upgrade --old-cluster-version v1.21.12`

**Comment by fanux** [comment]
Seems you need generate the Clusterfile: https://www.sealos.io/docs/api/sealos_gen
