### ISSUE TITLE
sealos gen 调用kubeadm生成k8s各组件安装的初始化参数

### ISSUE THREAD

**Issue by longyinghua** [labring/sealos#1650]
希望可以通过sealos调一下kubeadm生成一种初始化的配置文件，生辰的配置文件包含k8s安装各组件的基础模板，用户可以自行修改，比如kube-proxy，kube-controller组件，这样用户可以指定自定义的仓库镜像地址，infra基础容器，pod，service网络修改，如果用户不知道kubeadmin可以init初始化参数，那么就得需要找个kubeadmin进行生成参数，生成后在粘贴到Clusterfile中，这样比较麻烦，如果可以直接调kubeadm生成各组件参数，那么Clusterfile更具备定制化，这样更方便离线交付自定义修改参数

**Comment by fengxsong** [comment]
This has been implemented in https://github.com/labring/sealos/pull/1743
