### ISSUE TITLE
sealos安装1.24 集群master 节点断电重启后无法自动恢复

### ISSUE THREAD

**Issue by HereHaveAnPeople** [labring/sealos#1651]
sealos安装1.24 集群master 节点断电重启后无法自动恢复
kubelet 服务状态正常：
![image](https://user-images.githubusercontent.com/54338257/187154004-9d8aaa7b-6961-4686-8500-3fe16d568384.png)

但是服务显示无法连接6443，查看容器状态全部为 Exited
![image](https://user-images.githubusercontent.com/54338257/187154225-a59d45b9-ef5b-4ca1-9489-c0dc7e433d83.png)

有没有哪位大佬，遇到过类似的问题，怎么能够让容器自动拉起。

**Comment by herehavepeople** [comment]
我测试了用kubeadm 安装1.24.3 断电重启，是可以自动恢复的。

**Comment by cuisongliu** [comment]
/etc/hosts 里面有配置么，感觉是丢失hosts的问题

**Comment by HereHaveAnPeople** [comment]
> /etc/hosts 里面有配置么，感觉是丢失hosts的问题

我看里面有新增的条目没有丢失，使用 bash /var/lib/sealos/data/default/rootfs/scripts/init-registry.sh 之后集群就正常了

**Comment by cuisongliu** [comment]
> > /etc/hosts 里面有配置么，感觉是丢失hosts的问题
> 
> 我看里面有新增的条目没有丢失，使用 bash /var/lib/sealos/data/default/rootfs/scripts/init-registry.sh 之后集群就正常了

registry 使用二进制部署再测试一下
