### ISSUE TITLE
sealos can't load docker image

### ISSUE THREAD

**Issue by michael1589** [labring/sealos#1655]
**Which command or component**

```
[root@ecs-cluster-node-1-0001 k8s_install]# sealos load -i kube-webhook-certgen.tar 
Error: loading index: open /var/tmp/oci513443904/index.json: no such file or directory
Usage:
  sealos load [flags]

Examples:
sealos load -i kubernetes.tar

Flags:
  -h, --help               help for load
  -i, --input string       load image from tar archive file
  -t, --transport string   load image transport from tar archive file.(optional value: oci-archive, docker-archive) (default "oci-archive")

Global Flags:
      --cluster-root string   cluster root directory (default "/var/lib/sealos")
      --debug                 enable debug logger

loading index: open /var/tmp/oci513443904/index.json: no such file or directory
```

**The Description of the bug**

Describe the bug.

**How to reproduce（pictures can be attached if necessary）**
1. get docker image:
```
docker pull registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.3.0
```
2. save the image to a tar ball
3. upload the tar ball to a linux environment
4.use sealos to load the tar ball

sealos load -i kube-webhook-certgen.tar 

**What you expected to happen**

sealos can load the tar ball correctly

**Operating environment**

- Kubernetes version: 1.24.0
- Sealos version: {"gitVersion":"4.1.0-rc3","gitCommit":"55cdca07","buildDate":"2022-08-25T02:17:16Z","goVersion":"go1.19","compiler":"gc","platform":"linux/amd64"}
- Operating system: eg. centos7
- Cluster size: eg 3 master, 0 node

**Comment by fanux** [comment]
The docker image cannot be loaded with sealos. The sealos load is the cluster image. The cluster image is built using sealos build. Although cluster image is compatible with the OCI image repository standard, it is not compatible with the local storage method of docker.

**Comment by fanux** [comment]
https://www.sealos.io/docs/examples/build-example-cloudimage  Using sealos build to save distribute application all dependencies into cluster image, you don't need to care about how sealos to save and pull docker image.

**Comment by cuisongliu** [comment]
```
[root@ecs-cluster-node-1-0001 k8s_install]# sealos load -i kube-webhook-certgen.tar 
Error: loading index: open /var/tmp/oci513443904/index.json: no such file or directory
Usage:
  sealos load [flags]

Examples:
sealos load -i kubernetes.tar

Flags:
  -h, --help               help for load
  -i, --input string       load image from tar archive file
  -t, --transport string   load image transport from tar archive file.(optional value: oci-archive, docker-archive) (default "oci-archive")

Global Flags:
      --cluster-root string   cluster root directory (default "/var/lib/sealos")
      --debug                 enable debug logger

loading index: open /var/tmp/oci513443904/index.json: no such file or directory
```
sealos load -i kube-webhook-certgen.tar  -t docker-archive  , you can load docker image using  sealos
