### ISSUE TITLE
BUG: 初始化集群失败

### ISSUE THREAD

**Issue by SKerry1216** [labring/sealos#1656]
sealos 4.0 k8s  1.25 redhat7.2
初始化过程中kubelet启动失败 拒绝连接
192.168.9.122:22: [kubelet-check] It seems like the kubelet isn't running or healthy.
192.168.9.122:22: [kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp [::1]:10248: connect: connection refused.

**Comment by fanux** [comment]
`systemctl status kubelet`

**Comment by SKerry1216** [comment]
> 

正常auto-restart 尝试更改cgroup类型无效 升级sealos至4.10版本无效 仍然出现上述错误

**Comment by SKerry1216** [comment]
> 1.25 只支持sealos 4.1.0-rc3

降级至1.24仍然出现上述错误

**Comment by fanux** [comment]
需要看 kubelet 没起来的原因到底是什么。

**Comment by SKerry1216** [comment]
> 需要看 kubelet 没起来的原因到底是什么。

![image](https://user-images.githubusercontent.com/59678918/187575505-81469a25-f4f6-4273-aa7a-76df5c3d8fbc.png)

**Comment by SKerry1216** [comment]
问题解决 systemd版本过低，升级systemd后问题解决
