### ISSUE TITLE
Feature: cloud init module

### ISSUE THREAD

**Issue by fanux** [labring/sealos#1660]
cloud init font end, support create AWS Kubernetes cluster in GUI, and show the node's base info like public and private IP, ssh passwd and flavor.

<img width="849" alt="image" src="https://user-images.githubusercontent.com/8912557/187415334-1772f9a5-d574-4c5a-ab22-a1c220ff4e66.png">

CloudInit on sealos desktop can help user to create a sealos cloud on any cloud platform.

**Comment by HURUIZHE** [comment]
apiVersion: infra.sealos.io/v1
kind: Infra
metadata:
  name: infra-apply-test
spec:
  cluster: my-cluster
  hosts:
  - roles: [master] # required
    count: 0 # Required
    flavor: "t2.micro"
    image: "ami-05248307900d52e3a"
    disks:
    - capacity: 30
       type: "gp3"
       name: "/dev/sda2"
  - roles: [ node ] # required
    count: 0 # Required
    flavor: "t2.micro"
    image: "ami-05248307900d52e3a"
    disks:
    - capacity: 20
       type: "gp2"
       name: "/dev/sda2"
---
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  name: my-cluster
spec:
  image:
  - labring/kubernetes:v1.24.0
  - labring/calico:v3.22.1

**Comment by fanux** [comment]
<img width="460" alt="image" src="https://user-images.githubusercontent.com/8912557/197494420-fd23c092-74f4-4aa4-b2f0-38868645fde0.png">

<img width="713" alt="image" src="https://user-images.githubusercontent.com/8912557/197495042-3e9620bf-e7bb-46e9-9c05-ef387684dfaf.png">

**Comment by realtuitui** [comment]
Infra用户流草稿
![Infra 草稿1](https://user-images.githubusercontent.com/116551029/197679479-3bfe2f4a-e9d3-4f74-b461-affa0b3b0e16.png)

**Comment by realtuitui** [comment]
Infra用户流草稿
![10 25 Infra draft](https://user-images.githubusercontent.com/116551029/197689117-c83886d6-f9bd-4fd0-972f-c0f2697087c7.png)

**Comment by zzjin** [comment]
![wvqsir8ee3 feishu cn_docx_F7Ghdl4eToOrepx4hGMcrja5nEg (2)](https://user-images.githubusercontent.com/679757/201347953-707e8d19-08f4-4247-b228-e4d2382c0a4a.png)
