### ISSUE TITLE
BUG: requested access to the resource is denied

### ISSUE THREAD

**Issue by aliuq** [labring/sealos#1661]
**Which command or component**

使用默认的单机安装命令 `sealos run kubernetes:v1.24.0 --single`

![image](https://user-images.githubusercontent.com/11707934/187419419-d910a827-77f2-4fc2-8152-27e20ef94620.png)

![image](https://user-images.githubusercontent.com/11707934/187425383-8bb63412-1992-43d0-a286-f8e3fb7eb00f.png)

**Operating environment**

- Docker version:   `none`
- Kubernetes version: `none`
- Sealos version: `v4.1.0-rc3`
- Operating system: `centos7`

**Comment by aliuq** [comment]
如果是因为镜像问题，国内如何加速呢？

**Comment by cuisongliu** [comment]
labring/kubernetes

**Comment by zhengyazhao** [comment]
这么去使用了 还是报错啊 sealos 是4.2.0版本。Error: copying system image from manifest list: parsing image configuration: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/81/81d78195b93df01c96b701cf2fad2c2dcbbed9b42631839c0ec04cd48949f4e0/data?verify=1687170520-PCXuWNlkILVqjWoZGofiWEL4234%3D": dial tcp 104.18.121.25:443: i/o timeout
