### ISSUE TITLE
sealos支持ipv6吗

### ISSUE THREAD

**Issue by Zruto** [labring/sealos#1662]
我尝试用机器的ipv6地址安装集群时报错了，每台机器都设置了ssh免密登录，请问是因为sealos目前还不支持ipv6吗
![20220830-203104](https://user-images.githubusercontent.com/46238825/187437229-82e88f87-50fe-4018-9c5b-20a8b9770faa.jpeg)

**Comment by cuisongliu** [comment]
暂时不支持

**Comment by Zruto** [comment]
请问未来有考虑支持ipv6吗？可以提这个开发需求吗？
