### ISSUE TITLE
Feature Discussion: Support global controller-manager and user spec controller

### ISSUE THREAD

**Issue by zzjin** [labring/sealos#1674]
### Use case
When we create a terminal controller application, we need two crds to deploy, first is a global crd witch runs at spec namespace and watch for secend crd, withc will create user's real terminal pod.

### Problems description
At one k8s cluster, we can just run one and only one deployment of `terminal-controller-manager`, using global namespace like `terminal-system`, with 0-N terminal-use-app on demand, using each user's namespace like `user-ns-1234-acdf`.

When run under `hub`+`image`+`desktop` environment, the typical terminal usage is like blow:

1. User login
2. User Install `Terminal App` at sealos hub page
    2.1 Or run `sealos apply terminal` using cli
3. Apply terminal svc and get endpoint router
4. display window

### Real problem
Here comes the real problem: Applications like `terminal controller` witch have more than one crd to run, when and how to install them such as `terminal-controller-manager`?
So the apply action has to check some statement, check the underlying k8s cluster has already installed and run the `terminal-controller-manager` or not.

If the answer is yes, everything work as claim, But when the answer is no, thing make diffcult.

The apply action is sent using user's token, and can only access user-owned namespace by default, but we want to install(apply) `terminal-controller-manager` to the different and unique namespace, and add `cluster-admin` role, where the user's token don't have permission.

Here also have some risks that even the `ingress/nginx` controller is not installed at the underlying k8s cluster, which seems to be the fact that any application controller like terminal can not get the `ingress` installation status.

### Possible solutions

1. Apply all needed prerequirements at each application's crd files, for example, terminal controller says it's want to use `ingress/nginx` and `terminal-controller-manager` as underlying dependence, and in cluster files, add some tag to comfirm that these underlying dependences will run at given namespaces and have given admin access roles.
2. sealos will have some default underlying dependence such as `calico`/`ingress-nginx`/`minio` installed, and apps can direct use these svcs.

#### To be discussed:

how to apply ignress router with crd? like request ingress-nginx to update access to new sub domian by request route name+service name.

**Comment by fanux** [comment]
Very good proposal, I think we should add a proposal directory to record this content

**Comment by zzjin** [comment]
## Possible resolve method

The application on the hub system have some default action steps:
1. Install
2. Run
3. Update/Keep Running
4. Close
5. Uninstall

All life-circle actions are applied at user's control namespaces, and cannot *escape* to any other namespace, to keep safety and simplify.

**Note: The 3rd life-circle `Update/Keep Running` still needs some discussion, maybe we can delete this, but this statement will be useful for some endpoints to keep run after user closed desktop windows.**

### Reusing cluster-file design

1. `Install` -> **`Must-Have`**. 
    Default is using cluster-files 's `ENDPOINT` or `CMD`, to run some actions already defined.
2 `Run` -> `[Optional]`.
    If an application has no GUI entry-point, run action is no action(witch is default value), when this application need to start some entry-point, crds can defined here.
3. `Update/Keep Running` ->  `[Optional]`.
    Some actions to keep pods(services) running at background after user refresh page or exit window, as also default value is no action.
4. `Close` ->  `[Optional]`.
    Do some cleaner work when user active close application's window, default value is no action.
5. `Uninstall` ->  `[Optional]`.
    Fully remove whole application crds, and cleanup user settings if needed.

### Example
#### Terminal Controller Example:
1. `Install`: Install `terminal-controller-manager`
2. `Run`: Apply user's terminal pod and start http service at given port.
3. `Update/Keep Running`: Keep-alive the terminal pod, so user refresh webpage, can still reuse the http entry-point, or just do nothing is ok.
4. `Close`: Delete the user's terminal pod, or just do nothing to leave terminal pod keep running until reach keep-alive timeout.
5. `Uninstall`: Delete all running terminal pod, and delete the `terminal-controller-manager`.

#### Cloud Init Example
1. `Install`: Install `infra controller`
2. `Run`: Apply `cloud init operator` to provide a user interface.
3. `Update/Keep Running`: do nothing, as described blow.
4. `Close`: do nothing, when user close the `cloud init operator` window, either user has already applied the new infra, or just cancel action, so do nothing works fine.
5. `Uninstall`: Delete all running `infra`s, and delete the `infra controller`.

**Comment by cuisongliu** [comment]
1. 确认一下controller上传模式（管理员上传），因为controller权限有一些需要cluster相关权限，可能上传的如果需要一些cluster权限需要管理员去上传。上传之后在hub上就可以看到对应的APP，租户可以创建对应的CR。
2. 如果不同的controller上架需要确认依赖问题，因为controller安装之前并不知道我们集群有什么组件，它可能会默认安装依赖组件，如果我们已经存在组件的话会导致集群安装了两个相同的组件。

**Comment by fanux** [comment]
This document can be placed in the proposal
