### ISSUE TITLE
sealos 安装k8s失败 Failed to decode the keys ["storage.options.override_kernel_check"] from "/etc/containers/storage.conf". 

### ISSUE THREAD

**Issue by wellenChen** [labring/sealos#1676]
![截图](https://fastly.jsdelivr.net/gh/wellenChen/tuchuang@main/images/16620112499451662011249199.png)

**Comment by cuisongliu** [comment]
Check which module your /etc/containers/storage.conf comes from.

**Comment by fanux** [comment]
You already installed buildah or podman? delete  /etc/containers/storage.conf  and retry
