### ISSUE TITLE
BUG:  can't pull images from docker.io 

### ISSUE THREAD

**Issue by wuxingzhong** [labring/sealos#1684]
k8s can't pull images from docker.io 

![QQ图片20220902094251](https://user-images.githubusercontent.com/7947984/188041149-02748114-80f4-4f15-b57a-4d8111c286d8.jpg)

but  I  can pull the same image use  `ctr` command. 

![QQ图片20220902094245](https://user-images.githubusercontent.com/7947984/188041055-54b74097-31aa-4a54-b052-bdd4cdd9dbff.jpg)

**Operating environment**

- Kubernetes version: kubernetes1.24.4
- Sealos version: v4.1.0
- Operating system: centos8

**Comment by cuisongliu** [comment]
why use ctr..... k8s   not support centos8.

**Comment by cuisongliu** [comment]
> There are some problems in: `/var/lib/kubelet/kubelet-flags.env` on the k8s node
> with the config `--image-service-endpoint=unix:///var/run/image-cri-shim.sock"`

That's right. This is the function of sealos.

**Comment by cuisongliu** [comment]
but....you pull images in online ....

**Comment by cuisongliu** [comment]
https://github.com/labring/sealos/issues/883  see this issue  , maybe you know what is image-cri-shim

**Comment by cuisongliu** [comment]
no , image-shim support online and offline . run a app can build a clusterimage.  https://github.com/labring/cluster-image/tree/main/applications  all applications. ex nginx ,you can exec `sealos run labring/ingress-nginx:4.1.0`

**Comment by cuisongliu** [comment]
https://www.sealos.io/zh-Hans/docs/design/registry-image  can see it.

**Comment by cuisongliu** [comment]
```sealos run labring/ingress-nginx:4.1.0``` using this way run image ???

**Comment by cuisongliu** [comment]
crictl pull nginx:1.21-perl

**Comment by cuisongliu** [comment]
> > crictl pull nginx:1.21-perl
> 
> ![image](https://user-images.githubusercontent.com/7947984/188067197-432da0b2-5890-466a-876c-278618dc03c3.png)

this seem a bug for online images. thanks

**Comment by cuisongliu** [comment]
There should be no problem offline.

**Comment by notevery** [comment]
- centos7.9（kernel 3.10.0-1160.71.1.el7.x86_64）
- sealos 4.0.0
- k8s v1.24.0

** same bug！！！can not pull from dockerhub; my harbor is ok.**

```
  Warning  Failed     11m (x2 over 11m)    kubelet            Failed to pull image "nginx": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/nginx:latest": failed to resolve reference "docker.io/library/nginx:latest": failed to authorize: failed to fetch oauth token: unexpected status: 401 Unauthorized
  Normal   Pulling    10m (x4 over 12m)    kubelet            Pulling image "nginx"
  Warning  Failed     10m (x4 over 11m)    kubelet            Error: ErrImagePull
  Warning  Failed     10m (x2 over 11m)    kubelet            Failed to pull image "nginx": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/nginx:latest": failed to resolve reference "docker.io/library/nginx:latest": failed to authorize: failed to fetch oauth token: unexpected status: 429 Too Many Requests

```

**Comment by ziyouguodu** [comment]
- sealos 4.1.2 
- ubuntu 22.04 LTS
- k8s v1.24.4

`Warning  Failed     28s (x4 over 2m)    kubelet            Failed to pull image "nginx:1.22": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/nginx:1.22": failed to resolve reference "docker.io/library/nginx:1.22": failed to authorize: failed to fetch oauth token: unexpected status: 401 Unauthorized
`

is bug , The online image cannot be pulled. This problem is very serious. !!!
