### ISSUE TITLE
BUG: sealos reset bug

### ISSUE THREAD

**Issue by xiao-jay** [labring/sealos#1686]
**The Description of the bug**

i first install sealos
```
sudo sealos run labring/kubernetes:v1.25.0 labring/calico:v3.22.1 --single
```

```
ubuntu@VM-12-15-ubuntu:~$ sealos reset --debug
are you sure to delete these nodes? Yes [y/yes], No [n/no] : y
Error: enter true iplist, master ip length more than zero
```

- Kubernetes version: v1.25.0
- Sealos version: {"gitVersion":"4.1.2","gitCommit":"b9951850","buildDate":"2022-09-02T02:49:13Z","goVersion":"go1.19","compiler":"gc","platform":"linux/amd64"}
- Operating system: ubuntu

**Comment by cuisongliu** [comment]
Sudo is not supported yet.
