### ISSUE TITLE
sealos4.1.2 can not work on rocky linux 9

### ISSUE THREAD

**Issue by kinbod** [labring/sealos#1688]
**Which command or component**

sealos can not work here.

**The Description of the bug**

Describe the bug.

**How to reproduce（pictures can be attached if necessary）**
rocky linux 9

**Test Result**
[root@rocky1 ~]# sealos images
Segmentation fault (core dumped)

**What you expected to happen**

Expected to xxx

**Operating environment**

- Docker version:   eg. 19.03
- Kubernetes version: eg.kube1.16.tar.gz
- Sealos version: v4.1.2
- Operating system: eg. rocky linux 9 with kernel5.15
- Runtime environment:  eg. physical machine (100G memory, 10 core cpu, 10T storage), virtual machine (virbox, 10G memory, 2 core cpu, 100G storage), cloud(aws, 10G memory, 2 core cpu, 100G storage)
- Cluster size: eg 3 master, 3 node
- Additional information: istio, dashboard ...

**Comment by cuisongliu** [comment]
https://github.com/labring/sealos/issues/1518
https://github.com/labring/sealos/issues/1481

**Comment by cuisongliu** [comment]
[root@iZ2ze9xlcvgkhqhlrjm11eZ ~]# valgrind sealos
==22004== Memcheck, a memory error detector
==22004== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==22004== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==22004== Command: sealos
==22004==
==22004==
==22004== Process terminating with default action of signal 11 (SIGSEGV)
==22004==  Bad permissions for mapped region at address 0x1450E4C
==22004==    at 0x1450E4C: ??? (in /usr/bin/sealos)
==22004==
==22004== HEAP SUMMARY:
==22004==     in use at exit: 0 bytes in 0 blocks
==22004==   total heap usage: 0 allocs, 0 frees, 0 bytes allocated
==22004==
==22004== All heap blocks were freed -- no leaks are possible
==22004==
==22004== For lists of detected and suppressed errors, rerun with: -s
==22004== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
段错误
[root@iZ2ze9xlcvgkhqhlrjm11eZ ~]#

**Comment by cuisongliu** [comment]
```
[root@iZ2ze9xlcvgkhqhlrjm11eZ ~]# gdb sealos
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "aarch64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/bin/sealos...
warning: no loadable sections found in added symbol-file /usr/bin/sealos
(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/sealos
During startup program terminated with signal SIGSEGV, Segmentation fault.
```

**Comment by cuisongliu** [comment]
```
[root@iZ2ze9xlcvgkhqhlrjm11eZ ~]# valgrind -q sealos
==22046==
==22046== Process terminating with default action of signal 11 (SIGSEGV)
==22046==  Bad permissions for mapped region at address 0x1450E4C
==22046==    at 0x1450E4C: ??? (in /usr/bin/sealos)
段错误
```

**Comment by cuisongliu** [comment]
- [ ] add https://nfpm.goreleaser.com/configuration/ for release
- [ ] make file to build release sealos
