### ISSUE TITLE
Feature: 希望sealos提供将镜像push到私有仓库的命令

### ISSUE THREAD

**Issue by itzhoujun** [labring/sealos#1690]
手动操作需要打tag，login，push三个步骤，比较繁琐，如果能够一条命令直接完成三个步骤，对于离线场景的用户来说体验感会非常好。

**Comment by itzhoujun** [comment]
类似 sealos push-local-registry nginx:latest

**Comment by cuisongliu** [comment]
为啥没有直接sealos build镜像。。。

**Comment by itzhoujun** [comment]
sealos的镜像现在支持run的时候传参数，停止服务等等常用操作么？不支持的话使用起来不方便。

**Comment by cuisongliu** [comment]
支持环境变量渲染、参数覆盖等功能

**Comment by itzhoujun** [comment]
有文档吗

**Comment by cuisongliu** [comment]
https://www.sealos.io/docs/examples/build-example-cloudimage

**Comment by fanux** [comment]
如果这里的镜像指 docker 镜像的话那 sealos 完全不需要这样干，只需 sealos build 命令就会自动把应用依赖的所有的 docker 镜像存到集群镜像中， run 的时候自动从 sealos 自带的私有镜像仓库中下载下来。
