### ISSUE TITLE
crictl pull nginx:alpine failed

### ISSUE THREAD

**Issue by amwork2020** [labring/sealos#1708]
sealos install k8s sucessed, but when I use crictl pull image, failed, for example :

crictl pull nginx:alpine
FATA[0002] pulling image: rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/nginx:alpine": failed to resolve reference "docker.io/library/nginx:alpine": failed to authorize: failed to fetch oauth token: unexpected status: 401 Unauthorized 

but use "sealos pull nginx:alpine" is sucessed.

why?

Thanks!

**Operating environment**
- sealos : 4.1.2 4.1.0 4.0.0
- Kubernetes version: 1.24.3, 1.23.10
- Operating system: eg. centos7, alma8, alma9

centos7, alma8, alma9,  Kubernetes version: 1.24.3, 1.23.10 , sealos : 4.1.2 4.1.0 4.0.0, 都试验了，系统是干净的，都是一样的pull 
 failed。

**Comment by fanux** [comment]
crictl other commands can be executed successfully？

**Comment by cuisongliu** [comment]
This is bug.we need build newest image to fix it
