### ISSUE TITLE
BUG: Sealos add --nodes 时报错，但节点已添加成功。

### ISSUE THREAD

**Issue by Scharfsinnig** [labring/sealos#1720]
**Which command or component**
<img width="1621" alt="image" src="https://user-images.githubusercontent.com/9099493/188783261-f82ff7e2-3eb4-4ac0-80ed-dd7d987d0e42.png">

通过执行 `sealos add --nodes ` 指令添加一个节点，具体日志如上图。出现了如下的 error：
```
error Applied to cluster error: update lvscare static pod failed 10.103.142.189:22 failed to execute command(/var/lib/sealos/data/default/rootfs/opt/sealctl  static-pod lvscare --name kube-sealos-lvscare --vip 10.103.97.2:6443 --image ghcr.io/labring/lvscare:v4.1.3   --masters  10.103.142.198:6443 --masters  10.103.142.112:6443 --masters  10.103.142.108:6443) on host(10.103.142.189:22): output(bash: /var/lib/sealos/data/default/rootfs/opt/sealctl: No such file or directory), error(Process exited with status 127)
```

通过指令查看，node 被添加进来了。
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/9099493/188783332-1b7cbda0-19e2-4632-abc7-ad7ce5421a1b.png">

**Operating environment**

- Docker version:  containerd://1.6.2
- Kubernetes version: v1.24.0
- Sealos version: v4.1.3
- Operating system: eg. centos7 
- Runtime environment:  
- Cluster size: 3 master, 2 node

**Comment by fanux** [comment]
看下这个目录里有没有 sealctl `/var/lib/sealos/data/default/rootfs/opt/`

**Comment by Scharfsinnig** [comment]
> sealctl

没有。是否可以拷贝过去？

**Comment by Scharfsinnig** [comment]
> 

看着像是执行 --add-nodes 时，相关目录及文件初始化未正确执行导致。这些如果遇到，如何去操作？是支持手动拷贝，然后再重新执行指令，还是？

**Comment by cuisongliu** [comment]
需要把master0上Clusterfile 里面的status有一个镜像的挂载地址拷贝过去

**Comment by fanux** [comment]
拷贝失败导致？

**Comment by xiao-jay** [comment]
```
root@master1:~/.ssh# kubectl get nodes
NAME      STATUS   ROLES           AGE     VERSION
master1   Ready    control-plane   36m     v1.25.0
master2   Ready    control-plane   4m48s   v1.25.0
node1     Ready    <none>          35m     v1.25.0
node2     Ready    <none>          106s    v1.25.0
```
两master加入node2未出现问题
k8s：1.25
selaos：4.1.3
os：ubuntu
