### ISSUE TITLE
BUG: brief description of the bug

### ISSUE THREAD

**Issue by Scharfsinnig** [labring/sealos#1727]
<img width="801" alt="image" src="https://user-images.githubusercontent.com/9099493/188924995-deb4edf8-0905-47ed-aa42-da74d019ee34.png">
<img width="718" alt="image" src="https://user-images.githubusercontent.com/9099493/188925049-8da2b3f2-23a6-403c-acdf-2f89bd11f08d.png">

白天尝试弄了下新增节点，结果失败。想着重新再来一次，这会重新安装，老是提示 `The machine docker is not clean. Please clean docker the system.`，检查了所有的节点，也没安装这个啊！
一直不通过，一直报错。reset 又没有给全部清楚。

**Comment by Scharfsinnig** [comment]
并且，是多次确定，没有安装 docker，且将 containerd 也彻底卸载了。.sealos 和 sealos 目录也全部删掉了。还是不行。

**Comment by cuisongliu** [comment]
/var/run/docker.sock  这个socket是否存在

**Comment by cuisongliu** [comment]
whereis docker

**Comment by Scharfsinnig** [comment]
> /var/run/docker.sock 这个socket是否存在

都看了，没有。机器都是 clean 的。只装了 sealos。

**Comment by cuisongliu** [comment]
单节点么？

**Comment by cuisongliu** [comment]
每个节点都检测一下。

**Comment by Scharfsinnig** [comment]
> 。
一共6个节点。都检查过不知道多少遍了。所有节点都检测过了。

**Comment by cuisongliu** [comment]
```
check_cmd_exits docker
check_cmd_exits() {
  for cmd; do
    if which "$cmd"; then
      error "The machine $cmd is not clean. Please clean $cmd the system."
    fi
  done
}
```
脚本是这样检测的。

**Comment by Scharfsinnig** [comment]
感谢支持。我后来是通过重做系统，再从新安装一次搞定了。
