### ISSUE TITLE
Feature: 希望能支持cilium和它的Without kube-proxy

### ISSUE THREAD

**Issue by ziyouguodu** [labring/sealos#1728]
希望能支持cilium和它的Without kube-proxy，并在clusterfile支持相关自定义参数

**Comment by cuisongliu** [comment]
https://github.com/labring/cluster-image/tree/main/applications/cilium/v1.12.1

**Comment by cuisongliu** [comment]
labring/cilium:v1.12.0

**Comment by ziyouguodu** [comment]
好的，我看了下默认的cilium配置ipam为cluster-pool，cidr为10.0.0.0/8,  如果自定义网段需要更改这个配置，或者使用kubernets来分配ipam,  这个问题是否自行从dockerfile中重新build或者使用clusterfile？
