### ISSUE TITLE
安装docker版，报错cri命令执行失败

### ISSUE THREAD

**Issue by XiaokangLi** [labring/sealos#1730]
![B3 MBXN12GK%J_ 8%Q DO9](https://user-images.githubusercontent.com/33115408/189021831-215d0327-cef7-4ed0-8dca-9e33667fbeaf.png)
![K2T~M0SXR}H0PAY4VA3~1UM](https://user-images.githubusercontent.com/33115408/189021851-445e69ec-9b7a-4976-b255-34fd9398092e.png)
sealos 4.1.3  部署不成功，报错看不懂为什么要用cri

**Comment by cuisongliu** [comment]
/var/lib/sealos/data/default/rootfs/opt/sealctl cri cgroup-driver --short 看报啥错

**Comment by xrjk** [comment]
2022-09-14 16:09:18 [EROR] container runtime is not running: output: time="2022-09-14T16:09:18+08:00" level=fatal msg="connect: connect endpoint 'unix:///var/run/containerd/containerd.sock', make sure you are running as root and the endpoint has been started: context deadline exceeded"
, error: exit status 1

**Comment by xrjk** [comment]
另外用sealos 4.1.3releases包里的sealctl替换/var/lib/sealos/data/default/rootfs/opt/目录下的sealctl，可以正常运行并返回systemd

**Comment by cuisongliu** [comment]
这个是之前的镜像有问题，你下载最新的镜像，就可以了。

**Comment by fuxingbit** [comment]
![mNlio8oRxP](https://user-images.githubusercontent.com/26339492/200742635-ea82ef76-1e35-456b-93fe-d6913da3bb54.jpg)
遇到同样的问题，请问下载最新的镜像是什么？后面尝试了cri不用docker版可以成功，但目前还是需要安装docker版

**Comment by cuisongliu** [comment]
本地安装containerd了
