### ISSUE TITLE
BUG: 集群内应用容器有时候连接不上

### ISSUE THREAD

**Issue by Jasonliuxj** [labring/sealos#1731]
报错信息
Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "3a4c9a8ee21a245a4e008e6574b7aead16b3efc30db07122381c5c3fb25b4123": OCI runtime exec failed: exec failed: unable to start container process: open /dev/pts/3: operation not permitted: unknown

sealos 版本 1.24

**Comment by cuisongliu** [comment]
执行啥报错的？

**Comment by Jasonliuxj** [comment]
使用的kuboard 管理软件，进入容器时提示的错误

**Comment by cuisongliu** [comment]
> 使用的kuboard 管理软件，进入容器时提示的错误

你看看正常kubectl exec是否正常。如果正常可能需要去kubeboard提问了

**Comment by Jasonliuxj** [comment]
root@k8s-node03:/home/dev# kubectl exec -it kube-sealos-lvscare-k8s-node01  /bin/sh -n kube-system
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
~ # exit
root@k8s-node03:/home/dev# kubectl exec -it kube-sealos-lvscare-k8s-node01  /bin/bash -n kube-system
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "89cd6697e894629a0c004357ba4ec603c59dee7d8b60cd766f38696c303f9432": OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown

**Comment by Jasonliuxj** [comment]
> > 使用的kuboard 管理软件，进入容器时提示的错误
> 
> 你看看正常kubectl exec是否正常。如果正常可能需要去kubeboard提问了
root@k8s-node03:/home/dev# kubectl exec -it kube-sealos-lvscare-k8s-node01 /bin/sh -n kube-system
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
~ # exit
root@k8s-node03:/home/dev# kubectl exec -it kube-sealos-lvscare-k8s-node01 /bin/bash -n kube-system
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "89cd6697e894629a0c004357ba4ec603c59dee7d8b60cd766f38696c303f9432": OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown

**Comment by cuisongliu** [comment]
有的镜像是没有bash这个根据镜像看的。
