### ISSUE TITLE
k8s1.25.0集群安装完成后coredns报错

### ISSUE THREAD

**Issue by evirts** [labring/sealos#1735]
系统：CentOS Linux release 7.9.2009 (Core)
内核：4.9.220-37.el7.x86_64

#sealos版本
[root@master01 ~]# sealos version
{"gitVersion":"4.1.3","gitCommit":"b2ba9705","buildDate":"2022-09-06T06:04:14Z","goVersion":"go1.19","compiler":"gc","platform":"linux/amd64"}

#相关镜像版本如下：
[root@master01 ~]# sealos images
REPOSITORY                     TAG       IMAGE ID       CREATED       SIZE
docker.io/labring/kubernetes   v1.25.0   059b3d624ba8   2 days ago    622 MB
docker.io/labring/calico       v3.24.1   e2122fc58fd3   5 days ago    354 MB
docker.io/labring/helm         v3.8.2    1123e8b4b455   5 weeks ago   45.1 MB

master01、node01都无法通外网
[root@master01 ~]# ping baidu.com
ping: baidu.com: Name or service not known

#hosts解析如下
[root@master01 ~]# cat /etc/hosts
192.168.3.183 master01
192.168.3.66 node01

镜像导入后，开始离线安装
#sealos run docker.io/labring/helm:v3.8.2 docker.io/labring/kubernetes:v1.25.0 docker.io/labring/calico:v3.24.1 --masters 192.168.3.183 --nodes 192.168.3.66 --passwd xx

安装完成信息如下：
![image](https://user-images.githubusercontent.com/10336478/189090801-9b5219fe-77c2-4fcf-b969-864d7aa818f1.png)

[root@master01 ~]# kubectl get nodes
NAME       STATUS   ROLES           AGE     VERSION
master01   Ready    control-plane   9m48s   v1.25.0
node01     Ready    <none>          9m15s   v1.25.0

#查看coredns pod
[root@master01 ~]# kubectl get pods -n kube-system
![image](https://user-images.githubusercontent.com/10336478/189091688-c620f673-07a4-4363-bdba-dd1e7258b610.png)

查看coredns的日志
[root@master01 ~]# kubectl logs coredns-565d847f94-gh6xl -n kube-system
plugin/forward: no nameservers found

#查看coredns的事件信息
[root@master01 ~]# kubectl describe pods coredns-565d847f94-gh6xl -n kube-system

![image](https://user-images.githubusercontent.com/10336478/189091761-21c12523-b3e0-480d-abd7-461b610c714c.png)

**Comment by cuisongliu** [comment]
calico正常么

**Comment by evirts** [comment]
calico正常的，通过deploy创建的nginx等pod都能正常获取到ip

**Comment by fanux** [comment]
宿主的 /etc/resolve.conf 内容是什么？ 可以考虑改成 nameserver 8.8.8.8

**Comment by cuisongliu** [comment]
sealos run docker.io/labring/coredns:v0.0.1
