### ISSUE TITLE
sealos搭建的集群第一个节点坏了以后，集群是否还能够正常工作

### ISSUE THREAD

**Issue by dlscodes** [labring/sealos#1737]
您好，请问`sealos`第一个`master`节点挂了以后，其他的节点是否能够接替该节点的功能。比如利用`sealos`快速`add`/`delete`相关的`node`。感谢作者的分享。

**Comment by fanux** [comment]
HA 的话起 3 个 master 即可。 如果单点需要备份好 etcd 相数据

**Comment by dlscodes** [comment]
您好，如果3个master，第一个master坏掉以后，想继续扩容master是不是就没办法使用sealos命令了

**Comment by dlscodes** [comment]
@fanux 您好，如果3个master，第一个master坏掉以后，想继续扩容master是不是就没办法使用sealos命令了
