### ISSUE TITLE
v1.25版本  不能添加node节点

### ISSUE THREAD

**Issue by 1569099266** [labring/sealos#1752]
error Applied to cluster error: exec auth.sh failed failed to execute command(registryPort=(5000) registryUsername=(admin) criData=(/var/lib/docker) criDockerdData=(/var/lib/cri-dockerd) registryConfig=(/etc/registry) registryData=(/var/lib/registry) registryDomain=(sealos.hub) registryPassword=(passw0rd) && cd /var/lib/sealos/data/default/rootfs/scripts && bash auth.sh $registryDomain $registryPort $registryUsername $registryPassword) on host(192.168.200.222:22): output(WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get "http://sealos.hub:5000/v2/": dial tcp: lookup sealos.hub on 114.114.114.114:53: no such host), error(Process exited with status 1)

**Comment by zhangguanzhang** [comment]
```
dial tcp: lookup sealos.hub on 114.114.114.114:53: no such host
```

**Comment by cuisongliu** [comment]
/etc/hosts  发一下记录？
