### ISSUE TITLE
离线环境下，系统没有apparmor时无法安装集群

### ISSUE THREAD

**Issue by itzhoujun** [labring/sealos#1755]
**Which command or component**
sealos run 安装集群

**The Description of the question**
安装集群时报错：
![image](https://user-images.githubusercontent.com/6897671/189887492-02ea5b98-d63b-4de1-bc05-59339732fb0a.png)
由于是离线场景，无法直接apt安装apparmor，是否可以在集群镜像中带上apparmor实现离线安装呢？

系统：ubuntu18.04
内核：4.15.0

**Comment by itzhoujun** [comment]
最后手动想办法手动弄了deb包安装了apparmor。如果sealos能够兼容缺少apparmor的情况就厉害了。

**Comment by cuisongliu** [comment]
![image](https://user-images.githubusercontent.com/4150905/189946474-6dba375d-5d0c-45ca-9920-d218e2bba671.png)

**Comment by itzhoujun** [comment]
有结论吗

**Comment by fanux** [comment]
这个问题还需要再跟进一下，sealos 在 debian ARM 的服务器上必现 @cuisongliu

**Comment by fanux** [comment]
```
sealos run labring/kubernetes-docker:v1.20.5-4.1.3 labring/calico:v3.22.1 \
  -p xxx --masters 192.168.0.165,192.168.0.82,192.168.0.188 \
  --nodes 192.168.0.52,192.168.0.156,192.168.0.7
```
临时解决办法，用  labring/kubernetes-docker:v1.20.5-4.1.3 这个镜像亲测没什么问题

**Comment by SignorMercurio** [comment]
It seems `disable_apparmor` will not stop the check for the existence of apparmor userland utilities, though it does disable apparmor functionalities.

As mentioned in https://github.com/rancher/k3os/issues/702#issuecomment-849513559, we can either disable apparmor at kernel boot or install the apparmor userland. And https://github.com/rancher/k3os/pull/709 fixed this in the former way. However, we're not likely to tamper with kernel params and will provide a package for installing apparmor offline in the future.

A temporary fix for Ubuntu/Debian would be:

```shell
$ sudo apt install apparmor apparmor-utils
```

**Comment by cuisongliu** [comment]
https://github.com/labring/cluster-image/commit/8b4bb02e739df1ed30b08a642ec9d1ab892c8be3

**Comment by cuisongliu** [comment]
已经解决。重新铺镜像修改这个问题。

**Comment by cuisongliu** [comment]
https://github.com/labring/cluster-image/issues/211
