### ISSUE TITLE
pod经常莫名其妙地因为健康检查不通过而被重启

### ISSUE THREAD

**Issue by itzhoujun** [labring/sealos#1768]
<img width="895" alt="41f56e6d25143c51c5df32d7dc62dcc8" src="https://user-images.githubusercontent.com/6897671/190944808-7281a6d7-6b66-47c7-aeda-a4f26a49e568.png">

<img width="1691" alt="7367fc853578c5024c59ae21085fee80" src="https://user-images.githubusercontent.com/6897671/190944821-f93102e7-80f9-4317-b345-d1f9a040a380.png">
从/var/log/syslog日志看到以下内容，感觉探针请求也被image-cri-shim拦截了？不知道是否有这个有关
<img width="1465" alt="c0ee18da091376e2c92af594d2d67819" src="https://user-images.githubusercontent.com/6897671/190944890-f68f2d88-13ec-4a24-86d9-d53ffceef8e5.png">

**Comment by cuisongliu** [comment]
和shim没关系，这个只是镜像，找不到的话会自动去是线上下载的。

**Comment by itzhoujun** [comment]
有点迷啊。我观察了几次重启过程，发现都是间隔30分钟就重启一次。

**Comment by fanux** [comment]
calico kubeproxy 有没有异常日志

**Comment by itzhoujun** [comment]
> calico kubeproxy 有没有异常日志

没有异常。k8s自带的pod也会出现check失败的情况，每个pod 30分钟就要断网一次的感觉

**Comment by fanux** [comment]
如何复现？ 版本信息提供一下。 如升级最新版本还有这个问题请 reopen

**Comment by itzhoujun** [comment]
内核参数优化：/etc/sysctl.conf末尾增加：
```
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 30
```
执行`sudo sysctl -p`
然后重装k8s，上述问题就没了。但具体原因仍未知

**Comment by Chris0408** [comment]
> 又出现了。晕倒

请问这个问题有定位到原因吗？我们也有类似的问题

**Comment by itzhoujun** [comment]
> > 又出现了。晕倒
> 
> 请问这个问题有定位到原因吗？我们也有类似的问题

是否有创建了大量的service nodePort？

**Comment by Chris0408** [comment]
> > > 又出现了。晕倒
> > 
> > 
> > 请问这个问题有定位到原因吗？我们也有类似的问题
> 
> 是否有创建了大量的service nodePort？

有一些nodeport，但是数量不多，之前查文档，看到新版本K8S集群宿主机内核参数port range跟nodeport 范围重复会有这个问题，改了内核参数之后问题好像没出现了，你是同样的问题吗？
