### ISSUE TITLE
Feature: Helm command migration 

### ISSUE THREAD

**Issue by john-deng** [labring/sealos#1769]
**Which command or component**

Since that sealos could run cloud image which packed with a helm chart, I would like to have helm list / history / rollback feature on sealos

sealos list
sealos history 
sealos rollback

**Detailed description of the feature**
1. show helm list

```bash
sealos list

NAME 	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART        	APP VERSION
mysql	demo     	2       	2022-09-19 13:42:42.637858 +0800 CST	failed  	mysql-9.2.0  	8.0.29
redis	demo     	1       	2022-09-06 17:32:36.091464 +0800 CST	deployed	redis-16.9.11	6.2.7

```

2.  show history

```bash
sealos history mysql


1       	Tue Sep  6 17:00:26 2022	superseded	mysql-9.1.0	8.0.29     	Install complete
2       	Mon Sep 19 13:42:42 2022	failed    	mysql-9.2.0	8.0.29     	Upgrade "mysql" failed: cannot patch "mysql" with kind StatefulSet: StatefulSet.apps "mysql" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```

3. rollback revision

Since the mysql revisoin 2 has problem, I would like to rollback to revision 1

```bash
sealos rollback mysql 1
```

**Comment by willzhang** [comment]
it's for application management, in fact , i want all helm comamnd feature:
```
sealos uninstall app

sealos run app --helm-set key1=values1

sealos run app -f values.yaml
```

The cilium cli command line tool does this with --helm-set

```
cilium install --chart-directory charts/cilium --helm-set kubeProxyReplacement=strict,k8sServiceHost=apiserver.cluster.local,k8sServicePort=6443
```

if sealos support this , it will be a big feature , and it let sealos be able to run all helm application.

now sealos can not build nfs-csi ceph-csi cloud image, Because these applications require many custom parameters similar to IP addresses.

**Comment by fanux** [comment]
sealos not care about helm or other command line.

sealos will use application actions to manage applications, user can define his own actions like uninstall rollback backup recover migration and so on.

https://github.com/labring/sealos/issues/1259
