### ISSUE TITLE
Feature: sealos run xx.tar.gz

### ISSUE THREAD

**Issue by willzhang** [labring/sealos#1770]
**Which command or component**

sealos run

**Detailed description of the feature**

Install from tar.gz offline image package，Make offline installation easier.

**If you have solution，please describe it**

online save imags

```
sealos save -o kubernetes-v1.24.1.tar.gz labring/kubernetes:v1.24.1 labring/calico:v3.22.1
```

offline install
```
sealos run kubernetes-v1.24.1.tar.gz
```

**Comment by cuisongliu** [comment]
sealos load after sealos run ?

**Comment by john-deng** [comment]
Agreed, this feature is really helpful for the offline installation as sealos need to pull, save, load image and run, why not just run the package directory? just put a little more efforts and help the vast majority of users.

Simplicity is beauty!

**Comment by willzhang** [comment]
yes， pull save then load run , It's too complicated.

**Comment by fanux** [comment]
@willzhang can you provide this feature? Check the suffix is "tar.gz" then call the load function first.

**Comment by willzhang** [comment]
> @willzhang can you provide this feature? Check the suffix is "tar.gz" then call the load function first.

no，I'm not good at golang
