### ISSUE TITLE
Feature: supporting setup private registry like harbor 

### ISSUE THREAD

**Issue by kinbod** [labring/sealos#1777]
**Which command or component**

希望在初始化的时候能支持配置增加本地私有仓库，除了sealos.hub外增加私有harbor仓库。

**Detailed description of the feature**
1.
2.
3.

**If you have solution，please describe it**

Complete this feature through XXX
1.
2.
3.

**Comment by willzhang** [comment]
good idea, Harbor is the standard configuration of production environment.

**Comment by fanux** [comment]
@willzhang sealos already has `push` command, so we don't need `upload` command.

If you need harbor, just build a harbor application image like: https://www.sealos.io/docs/getting-started/build-example-cloudimage

Then just use sealos to run it : `sealos run harbor:xxx`

**Comment by fanux** [comment]
@willzhang you can use `sealos tag` `sealos push` to push cloudimage to private registry.

**Comment by willzhang** [comment]
i mean give up use registry

![sealos-harbor.drawio.png](https://s2.loli.net/2022/09/26/wOygz4MtDNsEQ6T.png)

**Comment by cuisongliu** [comment]
https://github.com/labring/sealos/discussions/1436

It may be solved, but it has not been realised yet.

**Comment by fanux** [comment]
Just add a harbor sealos image. Kubelet will pull image from harbor.

**Comment by kinbod** [comment]
> i mean let harbor replace sealos default private registry as second choose, like this
> 
> ![sealos-harbor.drawio.png](https://camo.githubusercontent.com/abaa50368ed6dde560e9fe09a4c42a024a0c8f969ccdaeabd88dce65606f7157/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30392f32362f774f79677a344d74444e73455136542e706e67)

Willzhang, yes,this is just what I want.
