### ISSUE TITLE
BUG: 安装应用时，无法通过 sealos run --cmd  参数覆盖 Kubefile 里面的命令

### ISSUE THREAD

**Issue by 80imike** [labring/sealos#1807]
sealos 版本为 4.1.3

安装应用时，无法通过 sealos run --cmd  参数覆盖 Kubefile(Dockerfile) 里面的命令

以 redis-operator 为例，用下面命令进行安装时：

sealos run  labring/redis-operator:3.1.4 --cmd "helm install redis-operator redis-operator --namespace redis --create-namespace","kubectl apply -f manifests/redis-operator-basic.yaml" --force

依旧以镜像 kubefile 里默认的 cmd 进行安装，Clusterfile 里面的内容也是默认的

![image](https://user-images.githubusercontent.com/1665201/192469781-6d351adb-1187-41d9-8bde-3ac39e38d339.png)

**Comment by SignorMercurio** [comment]
With #1825 merged, this issue should be resolved. If it still persists, please feel free to reopen this issue.
