### ISSUE TITLE
istio1.15.2 新版sealos 会在一直更新嘛 目前还是旧版的

### ISSUE THREAD

**Issue by chenshengshi** [labring/sealos#1817]
istio 已经1.15.2 但是sealos 1.14.2版本而且只有istIod 
可否安装demo呢

**Comment by fanux** [comment]
https://www.sealos.io/docs/getting-started/build-example-cloudimage 是否有兴趣按照这个教程来制作一个 istio 的镜像，然后就可以 sealos run istio 了

**Comment by willzhang** [comment]
Fixed by:https://github.com/labring/cluster-image/pull/174
