### ISSUE TITLE
IPVS rr no destination available

### ISSUE THREAD

**Issue by btdan** [labring/sealos#1846]
I install  sealos and install kubernetes with the command 
sealos run \
    labring/kubernetes:v1.24.0 \
    labring/calico:v3.22.1 \
    --masters <Your master IP address> \
    --nodes <Your worker IP address> \
    -p <Your SSH root password>
and it works well. The kubernetes is installed and begin to work
But however, the most of work node for kubernetes display the messages like this:
![194696192-9122b8b8-1e7f-4430-b767-3febb346102a](https://user-images.githubusercontent.com/5276480/194750070-174874e5-ca57-409f-aef1-d1b404c5b19d.png)

Can anyone help me to solve this problem?
Thanks very much.

**Comment by btdan** [comment]
I set the value  in /etc/sysctl.conf file:
net.ipv4.conf.all.proxy_arp = 1

and the number of messages is reduced  but not disappear.
There are still a little of messages.

**Comment by fanux** [comment]
What is your lvscare version? You can check lvscare static pod on your node.

**Comment by cuisongliu** [comment]
If you have any questions, please tell us the details to check.
