### ISSUE TITLE
请问，sealos是否支持异构芯片安装，比如有3台x86,4台arm安装？是否支持离线异构安装？如何操作？目前暂未在网络上收到相关资料

### ISSUE THREAD

**Issue by baozitao** [labring/sealos#1849]
请问，sealos是否支持异构芯片安装，比如有3台x86,4台arm安装？是否支持离线异构安装？如何操作？目前暂未在网络上收到相关资料

**Comment by cuisongliu** [comment]
异构还不支持

**Comment by fanux** [comment]
https://www.sealos.io/docs/getting-started/offline-install 离线安装参考这里。

**Comment by fanux** [comment]
Sealos join will support this feature
