### ISSUE TITLE
ARM集群离线安装问题

### ISSUE THREAD

**Issue by baozitao** [labring/sealos#1850]
离线安装集群，要运行起来一个集群，除了
labring/kubernetes
abring/calico:v3.24.1
之外，是否没有别的包需要导入？还是都包含在这两个里面了？

我安装集群时，有一个节点没有联网，出现了ContainerCreating的问题，一看是因为没法下载calico导致，也就是说，安装过程中还是会到互联网下载东西？？？？？？？

是否需要将

sealos.hub:5000/coredns/coredns                                  v1.9.3              b19406328e70d       13.4MB
sealos.hub:5000/etcd                                             3.5.4-0             8e041a3b0ba8b       81.1MB
sealos.hub:5000/kube-apiserver                                   v1.25.0             4a10a2c929d54       31.2MB
sealos.hub:5000/kube-controller-manager                          v1.25.0             35cb04d93081d       28.4MB
sealos.hub:5000/kube-proxy                                       v1.25.0             f5e24e0ab5f8d       18.1MB
sealos.hub:5000/kube-scheduler                                   v1.25.0             b933d73979ff4       14.3MB
sealos.hub:5000/labring/docker-cni-plugins                       v1.1.1              aba0e1b9a4f65       35.3MB
sealos.hub:5000/pause                                            3.8                 4e42fb3c9d90e       268kB
sealos.hub:5000/rancher/mirrored-flannelcni-flannel-cni-plugin   v1.1.0              b04a1a4152e14       3.64MB
sealos.hub:5000/rancher/mirrored-flannelcni-flannel              v0.18.1             049fb525e7554       20.5MB

这些都打包导入？？？

**Comment by cuisongliu** [comment]
calico 不需要flannel ，怎么看你还装了flannel?

**Comment by cuisongliu** [comment]
一个节点需要把污点去掉
