### ISSUE TITLE
Sealos images时，出现overlays支持问题

### ISSUE THREAD

**Issue by baozitao** [labring/sealos#1853]
操作系统为麒麟，即ubuntu 16.04，芯片为ARM64，安装sealos后，执行sealos images命令，出现问题
[Error: kernel does not support overlay fs: 'overlay' is not supported over extfs](https://unix.stackexchange.com/questions/689181/error-kernel-does-not-support-overlay-fs-overlay-is-not-supported-over-extfs)

请问有什么解决办法嘛？

**Comment by fanux** [comment]
要装 overlay, 参考这个 stackoverflow 没有效果嘛？

**Comment by baozitao** [comment]
有什么指导手册嘛？银河麒麟4.0.2，飞腾2000cpu安装overlay实在没找到什么资料，翻了不少网页，貌似银河麒麟4.0.2都没有这个内核模块。> 要装 overlay, 参考这个 stackoverflow 没有效果嘛？

**Comment by fanux** [comment]
apt install fuse-overlayfs
