### ISSUE TITLE
安装docker版本集群后集群一直NotReady

### ISSUE THREAD

**Issue by nanwanwang** [labring/sealos#1854]
### **安装命令:** 
![image](https://user-images.githubusercontent.com/13609580/194832361-b29ca928-112e-4a44-aaca-bd80b48bbcf8.png)

###安装后异常信息
![image](https://user-images.githubusercontent.com/13609580/194832639-b4f9d3dc-465c-43d5-bdf9-5aa604cb7162.png)

### 集群一直处于NotReady
![image](https://user-images.githubusercontent.com/13609580/194832802-d3338a33-7f04-4924-90f8-0c26eff527bd.png)
### Core-DNS一直处于Pending状态
![image](https://user-images.githubusercontent.com/13609580/194832969-dd893979-f5c4-4862-83bd-939ae0be1a0c.png)

![image](https://user-images.githubusercontent.com/13609580/194833140-ed709a90-0a02-4ce8-af77-9ab8c6c92ed5.png)

**Comment by cuisongliu** [comment]
sealos run labring/coredns:v0.0.1

**Comment by fanux** [comment]
sealos run labring/kubernetes-docker:v1.20.5-4.1.3 labring/calico:v3.24.1 \
     --masters 192.168.64.2,192.168.64.22,192.168.64.20 \
     --nodes 192.168.64.21,192.168.64.19 -p [your-ssh-passwd]

把 calico 换成 v3.24.1 即可，你这看的是哪个文档？可以顺便更新一下。
