### ISSUE TITLE
How to change the default disk path of docker container?

### ISSUE THREAD

**Issue by btdan** [labring/sealos#1858]
Hello. There are only 50GB disk space for the Ubuntu System.
I deploy kubernetes  cluster with help of Sealos. The command is as follows:
sealos run \
    labring/kubernetes:v1.24.0 \
    labring/calico:v3.22.1 \
    --masters <Your master IP address> \
    --nodes <Your worker IP address> \
    -p <Your SSH root password>

At beginning, All things goes well.
But when I deploy some container in the Kubernetes cluster . Ubuntu system display messages just as follows:
Failed to write entry  (35 items, 918 bytes), ignoring: Read-only file system.

Is this because the disk space is not big enough?
I can and another bigger disk space such as 400GB. But how to change the path of docker container in order to store in this big disk?
Thanks very much.

**Comment by cuisongliu** [comment]
https://github.com/labring/sealos/issues/1592
