### ISSUE TITLE
在centos8.4部署时，最后提示报错：invalid argument "never" for "--pull" flag: strconv.ParseBool: parsing "never": invalid syntax

### ISSUE THREAD

**Issue by xy2019devl** [labring/sealos#1870]
操作系统：CentOS Linux release 8.4.2105

```
[root@k8snode04 ~]#  tar -zxvf sealos_4.1.3_linux_amd64.tar.gz sealos &&  chmod +x sealos && mv sealos /usr/bin
[root@k8snode04 ~]# sealos run labring/kubernetes:v1.25.0 labring/helm:v3.8.2 labring/calico:v3.24.1 --masters 192.168.80.54,192.168.80.55 --nodes 192.168.80.56,192.168.80.57,192.168.80.58 --passwd 1qaz2wsx
2022-10-12T14:00:15 info Start to create a new cluster: master [192.168.80.54 192.168.80.55], worker [192.168.80.56 192.168.80.57 192.168.80.58]
2022-10-12T14:00:15 info Executing pipeline Check in CreateProcessor.
2022-10-12T14:00:15 info checker:hostname [192.168.80.54:22 192.168.80.55:22 192.168.80.56:22 192.168.80.57:22 192.168.80.58:22]
2022-10-12T14:00:16 info checker:timeSync [192.168.80.54:22 192.168.80.55:22 192.168.80.56:22 192.168.80.57:22 192.168.80.58:22]
2022-10-12T14:00:16 info Executing pipeline PreProcess in CreateProcessor.
Resolving "labring/kubernetes" using unqualified-search registries (/etc/containers/registries.conf)
Getting image source signatures
Copying blob 5ac9167b50d9 done  
Copying config c66205961b done  
Writing manifest to image destination
Storing signatures
c66205961bc8f650543cee92361987ce5e1ad77de4c85fc39e2b609734c6f3e8
Resolving "labring/helm" using unqualified-search registries (/etc/containers/registries.conf)
Getting image source signatures
Copying blob 53a6eade9e7e done  
Copying config 1123e8b4b4 done  
Writing manifest to image destination
Storing signatures
1123e8b4b455ed291f3ec7273af62e49458fe3dd141f5e7cb2a4243d6284deec
Resolving "labring/calico" using unqualified-search registries (/etc/containers/registries.conf)
Getting image source signatures
Copying blob f9de59270f64 done  
Copying config e2122fc58f done  
Writing manifest to image destination
Storing signatures
e2122fc58fd32f1c93ac75da5c473aed746f1ad9b31a73d1f81a0579b96e775b
invalid argument "never" for "--pull" flag: strconv.ParseBool: parsing "never": invalid syntax
2022-10-12T14:03:26 error Applied to cluster error: exit status 125
2022-10-12T14:03:26 info 
      ___           ___           ___           ___       ___           ___
     /\  \         /\  \         /\  \         /\__\     /\  \         /\  \
    /::\  \       /::\  \       /::\  \       /:/  /    /::\  \       /::\  \
   /:/\ \  \     /:/\:\  \     /:/\:\  \     /:/  /    /:/\:\  \     /:/\ \  \
  _\:\~\ \  \   /::\~\:\  \   /::\~\:\  \   /:/  /    /:/  \:\  \   _\:\~\ \  \
 /\ \:\ \ \__\ /:/\:\ \:\__\ /:/\:\ \:\__\ /:/__/    /:/__/ \:\__\ /\ \:\ \ \__\
 \:\ \:\ \/__/ \:\~\:\ \/__/ \/__\:\/:/  / \:\  \    \:\  \ /:/  / \:\ \:\ \/__/
  \:\ \:\__\    \:\ \:\__\        \::/  /   \:\  \    \:\  /:/  /   \:\ \:\__\
   \:\/:/  /     \:\ \/__/        /:/  /     \:\  \    \:\/:/  /     \:\/:/  /
    \::/  /       \:\__\         /:/  /       \:\__\    \::/  /       \::/  /
     \/__/         \/__/         \/__/         \/__/     \/__/         \/__/

                  Website :https://www.sealos.io/
                  Address :github.com/labring/sealos

[root@k8snode04 ~]# 
```

**Comment by cuisongliu** [comment]
本地安装了buildah吧 whereis buildah

**Comment by xy2019devl** [comment]
更新系统版本卸载了buildah，还是报错：

[root@k8snode001 ~]# cat /etc/redhat-release 
CentOS Linux release 8.5.2111
[root@k8snode001 ~]# rpm -qa |grep buildah
[root@k8snode001 ~]# rm /root/.sealos -rf
[root@k8snode001 ~]# sealos run labring/kubernetes:v1.25.2-4.1.3 labring/helm:v3.8.2 labring/calico:v3.24.1 --masters 192.168.3.161,192.168.3.162 --nodes 192.168.3.163,192.168.3.164 -p 1qaz2wsx
2022-10-13T15:35:48 info Start to create a new cluster: master [192.168.3.161 192.168.3.162], worker [192.168.3.163 192.168.3.164]
INFO[0000] Not using native diff for overlay, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled 
2022-10-13T15:35:48 info Executing pipeline Check in CreateProcessor.
2022-10-13T15:35:48 info checker:hostname [192.168.3.161:22 192.168.3.162:22 192.168.3.163:22 192.168.3.164:22]
2022-10-13T15:35:49 info checker:timeSync [192.168.3.161:22 192.168.3.162:22 192.168.3.163:22 192.168.3.164:22]
2022-10-13T15:35:49 info Executing pipeline PreProcess in CreateProcessor.
92eca77d26b849c9548f33d5531f716d7aa0584e46140997822b1de4ffd8db9b
1123e8b4b455ed291f3ec7273af62e49458fe3dd141f5e7cb2a4243d6284deec
e2122fc58fd32f1c93ac75da5c473aed746f1ad9b31a73d1f81a0579b96e775b
default-auz8j050
default-7a3a9wv5
default-dgkbkil2
2022-10-13T15:35:49 info Executing pipeline RunConfig in CreateProcessor.
2022-10-13T15:35:49 info Executing pipeline MountRootfs in CreateProcessor.
/usr/bin/which: no docker in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
 INFO [2022-10-13 15:35:50] >> check root,port,cri success 
[1/1]copying files to 192.168.3.164:22  50% [======>        ] (2/4, 32 it/min) [3s:3s]Created symlink /etc/systemd/system/multi-user.target.wants/containerd.service → /etc/systemd/system/containerd.service.
[1/1]copying files to 192.168.3.162:22  75% [==========>    ] (3/4, 35 it/min) [7s:1s] INFO [2022-10-13 15:36:00] >> Health check containerd! 
 INFO [2022-10-13 15:36:00] >> containerd is running 
 INFO [2022-10-13 15:36:00] >> init containerd success 
Created symlink /etc/systemd/system/multi-user.target.wants/image-cri-shim.service → /etc/systemd/system/image-cri-shim.service.
 INFO [2022-10-13 15:36:04] >> Health check image-cri-shim! 
 INFO [2022-10-13 15:36:04] >> image-cri-shim is running 
 INFO [2022-10-13 15:36:04] >> init shim success 
modprobe: FATAL: Module nf_conntrack_ipv4 not found in directory /lib/modules/4.18.0-348.el8.x86_64
* Applying /usr/lib/sysctl.d/10-default-yama-scope.conf ...
kernel.yama.ptrace_scope = 0
* Applying /usr/lib/sysctl.d/50-coredump.conf ...
kernel.core_pattern = |/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e
kernel.core_pipe_limit = 16
* Applying /usr/lib/sysctl.d/50-default.conf ...
kernel.sysrq = 16
kernel.core_uses_pid = 1
kernel.kptr_restrict = 1
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.all.promote_secondaries = 1
net.core.default_qdisc = fq_codel
fs.protected_hardlinks = 1
fs.protected_symlinks = 1
* Applying /usr/lib/sysctl.d/50-libkcapi-optmem_max.conf ...
net.core.optmem_max = 81920
* Applying /usr/lib/sysctl.d/50-pid-max.conf ...
kernel.pid_max = 4194304
* Applying /usr/lib/sysctl.d/60-libvirtd.conf ...
fs.aio-max-nr = 1048576
* Applying /etc/sysctl.d/99-sysctl.conf ...
fs.file-max = 65535
kernel.watchdog_thresh = 30
* Applying /etc/sysctl.d/k8s.conf ...
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.conf.all.rp_filter = 0
* Applying /etc/sysctl.conf ...
fs.file-max = 65535
kernel.watchdog_thresh = 30
net.ipv4.ip_forward = 1
 INFO [2022-10-13 15:36:06] >> init kube success 
 INFO [2022-10-13 15:36:06] >> init containerd rootfs success 
192.168.3.162:22: /usr/bin/which: no docker in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)
192.168.3.162:22:  INFO [2022-10-13 15:37:32] >> check root,port,cri success 
[1/1]copying files to 192.168.3.164:22  93% [=============> ] (14/15, 4 it/s) [3s:0s]192.168.3.162:22:  INFO [2022-10-13 15:37:54] >> Health check containerd! 
192.168.3.162:22:  INFO [2022-10-13 15:37:54] >> containerd is running 
192.168.3.162:22:  INFO [2022-10-13 15:37:54] >> init containerd success 
192.168.3.162:22:  INFO [2022-10-13 15:37:54] >> Health check image-cri-shim!             
[1/1]copying files to 192.168.3.163:22  66% [=========>     ] (10/15, 2 it/s) [42s:3s]192.168.3.162:22:  INFO [2022-10-13 15:37:54] >> image-cri-shim is running 
192.168.3.162:22:  INFO [2022-10-13 15:37:54] >> init shim success 
192.168.3.162:22: modprobe: FATAL: Module nf_conntrack_ipv4 not found in directory /lib/modules/4.18.0-348.el8.x86_64
192.168.3.162:22: * Applying /usr/lib/sysctl.d/10-default-yama-scope.conf ...
192.168.3.162:22: kernel.yama.ptrace_scope = 0
192.168.3.162:22: * Applying /usr/lib/sysctl.d/50-coredump.conf ...
192.168.3.162:22: kernel.core_pattern = |/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e
192.168.3.162:22: kernel.core_pipe_limit = 16
中间省略些过程...................................................................................
192.168.3.163:22: This node has joined the cluster:
192.168.3.163:22: * Certificate signing request was sent to apiserver and a response was received.
192.168.3.163:22: * The Kubelet was informed of the new secure connection details.
192.168.3.163:22: 
192.168.3.163:22: Run 'kubectl get nodes' on the control-plane to see this node join the cluster.
192.168.3.163:22: 
2022-10-13T15:45:23 info succeeded in joining 192.168.3.163:22 as worker
192.168.3.164:22: 
192.168.3.164:22: This node has joined the cluster:
192.168.3.164:22: * Certificate signing request was sent to apiserver and a response was received.
192.168.3.164:22: * The Kubelet was informed of the new secure connection details.
192.168.3.164:22: 
192.168.3.164:22: Run 'kubectl get nodes' on the control-plane to see this node join the cluster.
192.168.3.164:22: 
2022-10-13T15:45:23 info succeeded in joining 192.168.3.164:22 as worker
2022-10-13T15:45:24 info start to sync lvscare static pod to node: 192.168.3.164:22 master: [192.168.3.161:6443 192.168.3.162:6443]
2022-10-13T15:45:24 info start to sync lvscare static pod to node: 192.168.3.163:22 master: [192.168.3.161:6443 192.168.3.162:6443]
192.168.3.163:22: 2022-10-13T15:45:24 info generator lvscare static pod is success
192.168.3.164:22: 2022-10-13T15:45:24 info generator lvscare static pod is success
2022-10-13T15:45:24 info Executing pipeline RunGuest in CreateProcessor.
2022-10-13T15:45:24 info guest cmd is cp opt/helm /usr/bin/
2022-10-13T15:45:24 info guest cmd is kubectl create namespace tigera-operator
namespace/tigera-operator created
2022-10-13T15:45:25 info guest cmd is helm install calico charts/calico --namespace tigera-operator
Error: INSTALLATION FAILED: failed to install CRD crds/calico/crd.projectcalico.org_ipamblocks.yaml: etcdserver: request timed out
2022-10-13T15:45:49 error Applied to cluster error: exit status 1
2022-10-13T15:45:57 info 
      ___           ___           ___           ___       ___           ___
     /\  \         /\  \         /\  \         /\__\     /\  \         /\  \
    /::\  \       /::\  \       /::\  \       /:/  /    /::\  \       /::\  \
   /:/\ \  \     /:/\:\  \     /:/\:\  \     /:/  /    /:/\:\  \     /:/\ \  \
  _\:\~\ \  \   /::\~\:\  \   /::\~\:\  \   /:/  /    /:/  \:\  \   _\:\~\ \  \
 /\ \:\ \ \__\ /:/\:\ \:\__\ /:/\:\ \:\__\ /:/__/    /:/__/ \:\__\ /\ \:\ \ \__\
 \:\ \:\ \/__/ \:\~\:\ \/__/ \/__\:\/:/  / \:\  \    \:\  \ /:/  / \:\ \:\ \/__/
  \:\ \:\__\    \:\ \:\__\        \::/  /   \:\  \    \:\  /:/  /   \:\ \:\__\
   \:\/:/  /     \:\ \/__/        /:/  /     \:\  \    \:\/:/  /     \:\/:/  /
    \::/  /       \:\__\         /:/  /       \:\__\    \::/  /       \::/  /
     \/__/         \/__/         \/__/         \/__/     \/__/         \/__/

                  Website :https://www.sealos.io/
                  Address :github.com/labring/sealos

[root@k8snode001 ~]# kubectl get nodes
NAME         STATUS     ROLES           AGE     VERSION
k8snode001   NotReady   control-plane   6m4s    v1.25.2
k8snode002   NotReady   control-plane   4m6s    v1.25.2
k8snode003   NotReady   <none>          2m31s   v1.25.2
k8snode004   NotReady   <none>          2m30s   v1.25.2
[root@k8snode001 ~]# sealos images
INFO[0000] Not using native diff for overlay, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled 
REPOSITORY                     TAG             IMAGE ID       CREATED        SIZE
docker.io/labring/kubernetes   v1.25.0         c66205961bc8   29 hours ago   589 MB
docker.io/labring/kubernetes   v1.25.2-4.1.3   92eca77d26b8   29 hours ago   589 MB
docker.io/library/docker       latest          72c285f30339   6 days ago     151 MB
docker.io/labring/calico       v3.24.1         e2122fc58fd3   5 weeks ago    354 MB
docker.io/labring/helm         v3.8.2          1123e8b4b455   2 months ago   45.1 MB
[root@k8snode001 ~]#

**Comment by cuisongliu** [comment]
crictl ps -A  看看日志报错

**Comment by fanux** [comment]
etcdserver: request timed out 看着像网络问题连不上 etcd.
