### ISSUE TITLE
How to modify coredns other version for " sealos run labring/coredns:v0.0.1"

### ISSUE THREAD

**Issue by Jasonliuxj** [labring/sealos#1871]
sealos run labring/coredns:v0.0.1

如何修改coredns 版本到1.24 默认版本

**Comment by Jasonliuxj** [comment]
改成coredns:v0.0.1后 访问服务器地址有的会变慢

**Comment by cuisongliu** [comment]
https://github.com/labring/cluster-image/blob/main/config/coredns/v0.0.1/manifests/coredns.sh 这个是的脚本
