### ISSUE TITLE
Feature description: sealos cloud gateway requirements.

### ISSUE THREAD

**Issue by zzjin** [labring/sealos#1873]
## Backend Infomation 
Using sealos cloud for public or private hosts need a full featured network solution to expose service to internet access. 

## Requirements for multi users cluster
For multi users usage, this gateway must have features described below:
1. full featured kubernetes gateways: 
   1. standard network gateway: http support, ssl support, websocket support, keep-alived
   2. dynamic service discovery
   3. etc...
2. user environment separation:
    1.  each users cannot see each other or access each other from internal
    2. one user’s network updates must not affect any other user‘s service
    3. simple and extensionable witch means can easily replace to another

## Problems and disadvantage of current design
Currently, we are using k8s‘s `ingress-nginx` to work with internet access, witch have much limits:
1. there are only one controller to manage all users routers, means when new user apply new service, nginx will reload config file to apply new setting that will cause other in-using users disconnect and reconnect
2. we are using one wildcard certificate, so when one user needs to access service from `https` url, we must sync this wildcart certificate's **private** and public cert to user's namespace (Due to the design of ingress, routes must be created under user's namespace)

## Posible Alternatives
1. [Apisix](https://apisix.apache.org/docs/ingress-controller/getting-started/)
2. [api7](https://api7.ai/)
3. rely on 3rd party service? like gck/aws gateway?
4. to-be-discussion

**Comment by fanux** [comment]
These very excellent documents I think can create a new document directory and put them in

**Comment by fanux** [comment]
- use certmanager reflector to sync cert into user namespace.
- Use webhook to prevent users from getting this secret
- The webhook only allows the ingress controller to obtain the certificate secret
