### ISSUE TITLE
BUG:  kuboard install fail

### ISSUE THREAD

**Issue by mydq** [labring/sealos#1909]
sealos4.1.3
sealos run labring/kubernetes:v1.24.6 labring/calico:v3.24.1  labring/helm:v3.8.2 labring/coredns:v0.0.1  labring/kuboard:v3 

![image](https://user-images.githubusercontent.com/42607771/196403731-0696d948-464c-43c8-8909-cadcf563199c.png)

**Comment by willzhang** [comment]
try this: https://github.com/eip-work/kuboard-press/issues/328

**Comment by fanux** [comment]
@cuisongliu seems kuboard using an external etcd?

**Comment by cuisongliu** [comment]
https://github.com/labring/sealos/issues/1841

**Comment by cuisongliu** [comment]
> @cuisongliu seems kuboard using an external etcd?

yes,But their etcd is independent.

**Comment by fanux** [comment]
@cuisongliu seems @mydq install method same with you but failed?

**Comment by zzjin** [comment]
why server says `ps: command not found`,kuboard's builtin etcd need ps to find process?

**Comment by cuisongliu** [comment]
using kubernetes:v1.23.10  @mydq

**Comment by fanux** [comment]
@cuisongliu so the diff with v1.23.10 and v1.24.6?

**Comment by cuisongliu** [comment]
https://github.com/eip-work/kuboard-press/issues/328  @fanux

**Comment by willzhang** [comment]
> sealos4.1.3 sealos run labring/kubernetes:v1.24.6 labring/calico:v3.24.1 labring/helm:v3.8.2 labring/coredns:v0.0.1 labring/kuboard:v3
> 
> ![image](https://user-images.githubusercontent.com/42607771/196403731-0696d948-464c-43c8-8909-cadcf563199c.png)

maybe you should use kuboard with tested kubernetes version:
https://kuboard.cn/install/v3/install.html#kuboard-v3-x-%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E


```
sealos run labring/kubernetes:v1.23.3 labring/helm:v3.10.0 labring/calico:v3.22.1 --masters 192.168.72.50 --nodes 192.168.72.51,192.168.72.52 --passwd xxx
```

```
root@node1:~# kubectl get nodes -o wide
NAME    STATUS   ROLES                  AGE   VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE           KERNEL-VERSION      CONTAINER-RUNTIME
node1   Ready    control-plane,master   16m   v1.23.3   192.168.72.50   <none>        Ubuntu 22.04 LTS   5.15.0-48-generic   containerd://1.6.2
node2   Ready    <none>                 16m   v1.23.3   192.168.72.51   <none>        Ubuntu 22.04 LTS   5.15.0-48-generic   containerd://1.6.2
node3   Ready    <none>                 16m   v1.23.3   192.168.72.52   <none>        Ubuntu 22.04 LTS   5.15.0-48-generic   containerd://1.6.2

root@node1:~# kubectl -n kuboard get pods 
NAME                              READY   STATUS    RESTARTS        AGE
kuboard-agent-2-796cb78bc-pwxnr   1/1     Running   2 (3m33s ago)   3m50s
kuboard-agent-6c98879547-6jc8d    1/1     Running   2 (3m32s ago)   3m50s
kuboard-etcd-d2zsn                1/1     Running   0               4m52s
kuboard-v3-55fc4444c6-x8q7b       1/1     Running   0               4m52s
root@node1:~# 
```
