### ISSUE TITLE
BUG: casdoor‘s org infos are hardcoded, need configureable

### ISSUE THREAD

**Issue by zzjin** [labring/sealos#1915]
Currently, the builtin casdoor's admin configuer was hard-coded under source code, we need to split into config file to suppport update it.

<img width="791" alt="image" src="https://user-images.githubusercontent.com/679757/196704241-c11be717-6bc5-42ed-8a5c-7219b77e62a9.png">

**Comment by fanux** [comment]
Don't need use auth server to create casdoor configmap and restart pod.

**Comment by Abingcbc** [comment]
- [ ] Optimize hardcoded
- [ ] Optimize the logic to create Casdoor init data
- [ ] Integrate Casdoor operator
- [ ] Doc for deployment and usage
- [ ] Casdoor operator sealos cluster image
- [ ] Service auth sealos cluster image
