### ISSUE TITLE
BUG: semgrep securityContext.runAsNonRoot cause service cannot start

### ISSUE THREAD

**Issue by zzjin** [labring/sealos#1922]
When apply yaml files like: [casdoor.yaml](https://github.com/labring/sealos/blob/main/pkg/auth/conf/casdoor.yaml) pod sercice cannot be ready:
<img width="695" alt="image" src="https://user-images.githubusercontent.com/679757/196906576-fe260314-36bd-4f0d-9d00-1a3b25d7be8d.png">

Error: container has runAsNonRoot and image will run as root (pod: "casdoor-local-cdn-66686cd89c-znh4z_sealos(1ca2c5b0-906c-47cd-8746-1bf875424f50)", container: docker-casbin)

Additional information needed.

**Comment by SignorMercurio** [comment]
Could you please provide the list of containers that need to be run as root so that I can locate their yaml and add `nosemgrep` annotations?

**Comment by fanux** [comment]
https://github.com/labring/sealos/issues/1959 @SignorMercurio maybe we need a webhook to add those security context.
