### ISSUE TITLE
Feature: get image README.md when using sealos push

### ISSUE THREAD

**Issue by lingdie** [labring/sealos#1924]
Dependent on [feature: image hub](https://github.com/labring/sealos/issues/1902#issue-1411314459)

get README.md when using sealos push, and generate image detailInfo by parsing it.

**Comment by fanux** [comment]
1. 通过 labring/mysql:v8.0 拿到 README.md 
2. 构造一个 Image CR，通过 client-go 推送到 sealos cloud

https://github.com/labring/sealos/blob/main/pkg/image/cmd/push.go 在这里增加镜像源数据处理的逻辑。
https://github.com/labring/sealos/blob/main/pkg/image/cmd/create.go#L62 通过 create 把镜像合并成一层，workdir 中就可以获取到 REAEDME.md.

**Comment by fanux** [comment]
```
root@sealos-offic-04:~/.sealos/default# cd /var/lib/containers/storage/overlay/3a81ee93c9c5f1e6b55eb6f69ac61111ce391c742e010f92194a8b1137e113cd/merged
root@sealos-offic-04:/var/lib/containers/storage/overlay/3a81ee93c9c5f1e6b55eb6f69ac61111ce391c742e010f92194a8b1137e113cd/merged# ls
charts  images  init.sh  Kubefile  registry
root@sealos-offic-04:/var/lib/containers/storage/overlay/3a81ee93c9c5f1e6b55eb6f69ac61111ce391c742e010f92194a8b1137e113cd/merged#
```
