### ISSUE TITLE
Feature: sealos support pull arm images on x86 platform

### ISSUE THREAD

**Issue by andyhu1199** [labring/sealos#1929]
**Which command or component**

eg.  sealos pull labring/kubernetes:v1.24.0 --platform arm64

**Detailed description of the feature**
1. Now I have a server of X86, that can sealos pull image from hub, but doesnot have arm server to pull arm images. So expect sealos support pull arm images on x86 platform.
2.
3.

**If you have solution，please describe it**

Complete this feature through XXX
1.
2.
3.

**Comment by cuisongliu** [comment]
You can use the code of the main branch already supported.

**Comment by andyhu1199** [comment]
sealos 4.1.3 already support? or need download the master code to build?

**Comment by cuisongliu** [comment]
> sealos 4.1.3 already support? or need download the master code to build?

need download the main code to build

**Comment by andyhu1199** [comment]
> > sealos 4.1.3 already support? or need download the master code to build?
> 
> need download the main code to build

Got it. Thank You!
