### ISSUE TITLE
sealos4能适配下openeuler吗？

### ISSUE THREAD

**Issue by liutao841204** [labring/sealos#1939]
最近在用1.25.2，用了下4版本的sealos，但系统底层是openeuler2203，因为centos的原因，公司换的这个，但sealos对这个系统不支持，不是很明白，我用3的时候也没出什么问题，到4怎么反而不行了呢？或者有什么建议能给到我。

**Comment by cuisongliu** [comment]
> 用3的时候也没出什么问题，到4怎么反而不行

有报错么。应该是支持centos的，但是openeuler2203 需要看一下支持情况

**Comment by liutao841204** [comment]
我稍后重新安装一下，主要是对一些系统参数的调整报错，你还要收集什么文件吗，或者要以调试模式安装？我一并给你
。

**Comment by fanux** [comment]
支持应该非常容易，可能就是一个小错误修复一下即可。

**Comment by liutao841204** [comment]
我今天安装了下，神奇的事，没报错，竟然可以了，出了警告，我发一下。
![RcyzjkfMAz](https://user-images.githubusercontent.com/24605302/197931855-174fa796-5160-47f0-948e-009e7bf9e758.png)
我在测试一下，看看其它场景怎么样。我用的安装命令：sealos run labring/kubernetes-docker:v1.25.2 docker.io/labring/cilium:v1.12.1 \
     --masters 172.17.x.x \
     --nodes 172.17.x.x,172.17.x.x --password 'xxxxx' --debug  > sealos.log

**Comment by liutao841204** [comment]
zhe这个里面，是我用debug的输出日志。[sealos.log](https://github.com/labring/sealos/files/9865904/sealos.log)

**Comment by liutao841204** [comment]
我多了几个组件，多个几个机器，出现的结果是这个：
[sealos.log](https://github.com/labring/sealos/files/9866162/sealos.log)

用的命令：sealos run labring/kubernetes-docker:v1.25.2 docker.io/labring/cilium:v1.12.1 docker.io/labring/helm:v3.10.0 docker.io/labring/ingress-nginx:4.1.0 --masters 172.17.206.150,172.17.206.151,172.17.206.152 --nodes 172.17.206.153,172.17.206.154,172.17.206.155,172.17.206.156,172.17.206.157,172.17.206.158,172.17.206.159 --passwd 'qwe123ASD#@!' --debug  > sealos.log

**Comment by liutao841204** [comment]
> 我多了几个组件，多个几个机器，出现的结果是这个： [sealos.log](https://github.com/labring/sealos/files/9866162/sealos.log)
> 
> 用的命令：sealos run labring/kubernetes-docker:v1.25.2 docker.io/labring/cilium:v1.12.1 docker.io/labring/helm:v3.10.0 docker.io/labring/ingress-nginx:4.1.0 --masters 172.17.206.150,172.17.206.151,172.17.206.152 --nodes 172.17.206.153,172.17.206.154,172.17.206.155,172.17.206.156,172.17.206.157,172.17.206.158,172.17.206.159 --passwd 'qwe123ASD#@!' --debug > sealos.log

这是是出问题了！！！

**Comment by fanux** [comment]
``` 
Port: 10249 occupied. Please turn off port service. [0m), error(Process exited with status 1)[0m
```
机器没清理干净，可能有残留的 kubelet

**Comment by liutao841204** [comment]
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/24605302/197942336-4ac35b99-4927-4274-a109-cbd51e441405.png">
说是端口占用，这的逻辑我觉得可以改为强制关闭的，发个警告就行，没必要直接中断。

**Comment by liutao841204** [comment]
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/24605302/197945109-d1b29661-d24b-4648-8c4b-531c5d8cfdcc.png">
这个地方，是说起不来docker，我去这台机器上，手动起没问题，有没有可能就是因为慢，没起来呢？

**Comment by liutao841204** [comment]
> <img alt="image" width="1081" src="https://user-images.githubusercontent.com/24605302/197945109-d1b29661-d24b-4648-8c4b-531c5d8cfdcc.png">
> 
> 这个地方，是说起不来docker，我去这台机器上，手动起没问题，有没有可能就是因为慢，没起来呢？

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/24605302/197945285-8f37657e-39a7-4543-99be-304d4b970b77.png">

**Comment by liutao841204** [comment]
基本上应该有结论了：
1.在这个系统上安装不是很稳定，需要多次重置以及安装才可
2.一些机器内docker的检查时间或次数有问题，导致docker没有真正安装好，就开始启动
3.一些对系统的调优命令不兼容，如sysctl

有几个建议：
1、系统在安装时检查节点，如果大于1个master，可以在连接不上这个节点时，跳过它不要中断，毕竟我可以在安装后处理的
2、系统在安装失败时，可以自动清理，或者设置个参数问下要不要帮助自动清理下
3、如果遇到端口占用情况，个人觉得，直接把占用程序kill掉即可，因为也很少有人会在一台不干净的机器上安装，或者设置个询问参数也行
