### ISSUE TITLE
添加新节点可以指定ssh登录密码

### ISSUE THREAD

**Issue by SpringHgui** [labring/sealos#1941]
我先是搭建了一个单节点的集群，后来需要添加节点，于是
```
sealos add --nodes x.x.x.x
```
返回登录ssh失败的错误信息，通过查看sealos帮助信息，没找到能传password的参数，该怎么办

**Comment by cuisongliu** [comment]
> 我先是搭建了一个单节点的集群，后来需要添加节点，于是
> 
> ```
> sealos add --nodes x.x.x.x
> ```
> 
> 返回登录ssh失败的错误信息，通过查看sealos帮助信息，没找到能传password的参数，该怎么办

直接改.sealos里面的Clusterfile
