### ISSUE TITLE
Feature: upgrade the cluster

### ISSUE THREAD

**Issue by fanux** [labring/sealos#1944]
1. sealos run labring/kubernetes:v1.25.0 
2. sealos run labring/kubernetes:v1.25.1
   Compare The desired version is compared with the installed version, and the comparison is found to be different, triggering the upgrade process.

**Comment by fanux** [comment]
kubeadm upgrade.

**Comment by yinheli** [comment]
Any updates about this feature?

**Comment by fanux** [comment]
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

**Comment by mond77** [comment]
I. Version comparison part
程序流（第二次run 新版本）：
1、从本地.sealos文件下取clusterfile，deepcopy赋给desiredcluster；追加到desiredcluster.spec.image切片之后；
2、创建applier时把args中的imagename赋给applier.RunNewImages;
3、Apply()->reconcileCluster(),如果c.RunNewImages不为空（c是applier实例），走c.installApp(c.RunNewImages)

Problelms:
1、images直接append和赋给RunNewImages，没有比对是否重复安装、版本更新；
2、applier功能太局限，在第一次 sealos run之后再run只有runNewImages可以走

My ideas：
1、applier结构体需要扩展限制重复安装、版本更新的字段；
2、然后在reconcileCluster()中需要在扩展限制重复安装、版本更新的功能；

II. NewImages Preparation (to every node through ssh)
(todo)
III. Runtime Module Implementation (use kubeadm)
(todo)

**Comment by mond77** [comment]
#2340
