### ISSUE TITLE
Feature: split crd（metering and user-controller）

### ISSUE THREAD

**Issue by xiao-jay** [labring/sealos#1950]
split to 3 part
user:include `user`,`usergroup`,`usergroupbinding`
metering:include` metering`（Need to access other resource metering）
account:include `account`,`payment`,`deduction`（reduce the money）

**Comment by zzjin** [comment]
Add: design metering support extension (like bandwidth limit and traffic statistics)

**Comment by xiao-jay** [comment]
> 

https://github.com/labring/sealos/issues/1514
sea last comment
