### ISSUE TITLE
Feature: Add node name hosts when install cluster.

### ISSUE THREAD

**Issue by sniperking1234** [labring/sealos#1954]
**Detailed description of the feature**
1.现在sealos安装集群的时候，没有添加节点名称的host，希望后面在安装集群的时候，把节点名称的host也添加进去
![image](https://user-images.githubusercontent.com/7834655/197498404-c25e7ba6-a030-4d1c-b61e-dd18f488d96c.png)

**Comment by fanux** [comment]
这个特性最好通过插件的方式来支持～
