### ISSUE TITLE
Feature: replace uuid with nanoid for user id and user namespace etc.

### ISSUE THREAD

**Issue by maslow** [labring/sealos#1958]
**Which command or component**

@see https://zelark.github.io/nano-id-cc/

**Detailed description of the feature**
1. uuid is smelly and long, takes up a lot of space, and is not beautiful
2. use nanoid with short length. e.g. 6-8 length alpha-numberic characteres would be ok.

**If you have solution，please describe it**

Complete this feature through go-nanoid:

@see github.com/matoous/go-nanoid

**Comment by cuisongliu** [comment]
> **Which command or component**
> 
> @see https://zelark.github.io/nano-id-cc/
> 
> **Detailed description of the feature**
> 
> 1. uuid is smelly and long, takes up a lot of space, and is not beautiful
> 2. use nanoid with short length. e.g. 6-8 length alpha-numberic charactores would be ok.
> 
> **If you have solution，please describe it**
> 
> Complete this feature through go-nanoid:
> 
> @see github.com/matoous/go-nanoid

Uuid is not generated by controoler, but from the front end.

**Comment by zzjin** [comment]
> > **Which command or component**
> > @see https://zelark.github.io/nano-id-cc/
> > **Detailed description of the feature**
> > 
> > 1. uuid is smelly and long, takes up a lot of space, and is not beautiful
> > 2. use nanoid with short length. e.g. 6-8 length alpha-numberic charactores would be ok.
> > 
> > **If you have solution，please describe it**
> > Complete this feature through go-nanoid:
> > @see github.com/matoous/go-nanoid
> 
> Uuid is not generated by controoler, but from the front end.

UUID is reuse as casdoor user id, witch will be unique for all purpose. 
If we changed user unique id with [nano-id](https://zelark.github.io/nano-id-cc/) (or any other id genaretor) with 8-bit characters, it will collision very soon.

<img width="729" alt="image" src="https://user-images.githubusercontent.com/679757/205611713-e063476b-fe75-43df-ba36-fe7744639e8d.png">

In the meantime, we can use nano-id for short-life `crd`s, like terminal controller randomly generate hostname.
<img width="203" alt="image" src="https://user-images.githubusercontent.com/679757/205613066-7c66039a-385f-4775-8da3-9468ed09c1f2.png">

**Comment by maslow** [comment]
Why only 8 characters?
How about 12 characaters which will collision in 1 thousand years. 

The UUID string is up to 36 characters long.  

I would recommend, in any case, choosing a nanoid of length 12~22 instead of a uuid string of length up to 36.

Or compress the UUID to 22 bits, which is also a common practice, UUID is a hexadecimal data in the form of a string, itself is very occupy.

**Comment by zzjin** [comment]
> 12 characaters which will collision in 1 thousand years.

This is only works for 1000req/hour. And only ~113day when 1000req/sec.
Currently, I do not know how speed we can reach, but for system design:
1. userid keep using uuid works fine;
2. others, like auto generated random app name, nanoid works fine.
