### ISSUE TITLE
BUG: sealos can not get uninstall information

### ISSUE THREAD

**Issue by willzhang** [labring/sealos#1974]
**Which command or component**

sealos run

**The Description of the bug**

uninstall app manually , and reinstall , it will failed , you must use `sealos run -f`

**How to reproduce（pictures can be attached if necessary）**

uninstall app which run with `sealos run registry.cn-shenzhen.aliyuncs.com/cnmirror/apisix:2.15.0` before:

```
root@node1:~# helm -n ingress-apisix uninstall apisix
release "apisix" uninstalled
root@node1:~# 
```

**Test Result**
reinstall it again will do nothing
```
root@node1:~# sealos run registry.cn-shenzhen.aliyuncs.com/cnmirror/apisix:2.15.0
2022-10-28T14:28:07 info start to install app in this cluster
3fd087b32ca9c514b7d35a644d51765dd7582eefad5de367bf0efce40d44d921
2022-10-28T14:28:07 info succeeded install app in this cluster: no change apps
2022-10-28T14:28:07 info start to scale this cluster
2022-10-28T14:28:07 info succeeded in scaling this cluster: no change nodes
2022-10-28T14:28:07 info
      ___           ___           ___           ___       ___           ___
     /\  \         /\  \         /\  \         /\__\     /\  \         /\  \
    /::\  \       /::\  \       /::\  \       /:/  /    /::\  \       /::\  \
   /:/\ \  \     /:/\:\  \     /:/\:\  \     /:/  /    /:/\:\  \     /:/\ \  \
  _\:\~\ \  \   /::\~\:\  \   /::\~\:\  \   /:/  /    /:/  \:\  \   _\:\~\ \  \
 /\ \:\ \ \__\ /:/\:\ \:\__\ /:/\:\ \:\__\ /:/__/    /:/__/ \:\__\ /\ \:\ \ \__\
 \:\ \:\ \/__/ \:\~\:\ \/__/ \/__\:\/:/  / \:\  \    \:\  \ /:/  / \:\ \:\ \/__/
  \:\ \:\__\    \:\ \:\__\        \::/  /   \:\  \    \:\  /:/  /   \:\ \:\__\
   \:\/:/  /     \:\ \/__/        /:/  /     \:\  \    \:\/:/  /     \:\/:/  /
    \::/  /       \:\__\         /:/  /       \:\__\    \::/  /       \::/  /
     \/__/         \/__/         \/__/         \/__/     \/__/         \/__/

                  Website :https://www.sealos.io/
                  Address :github.com/labring/sealos
```

**What you expected to happen**

sealos run without -f.

Sealos should be able to check whether the applications installed by itself have been uninstalled.

**Operating environment**

- Docker version:   eg. 19.03
- Kubernetes version: eg.kube1.16.tar.gz
- Sealos version: v3.1.0-alpha.2
- Operating system: eg. centos7
- Runtime environment:  eg. physical machine (100G memory, 10 core cpu, 10T storage), virtual machine (virbox, 10G memory, 2 core cpu, 100G storage), cloud(aws, 10G memory, 2 core cpu, 100G storage)
- Cluster size: eg 3 master, 3 node
- Additional information: istio, dashboard ...

**Comment by fanux** [comment]
sealos has no way of knowing whether the application has been deleted, this problem is best solved by actions
