### ISSUE TITLE
Feature: 建议k8s集群镜像中自带nerdctl

### ISSUE THREAD

**Issue by itzhoujun** [labring/sealos#1981]
最新版本的kubernetest集群镜像中删除了nerdctl，非常不方便，希望加回来。理由如下：
1. 加载docker镜像需要使用sealos，但sealos只能root使用
2. 使用sealos命令加载镜像不是一个合适的方案，例如我的业务系统的部署脚本，原本在任意k8s集群都能执行，但现在无法在sealos安装的集群中使用。

**Comment by fanux** [comment]
可以构建一个专属的集群镜像：
Kubefile:
```
FROM kubernetes:v1.25.0
COPY nerdctl .
CMD ["cp nerdctl /usr/bin"]
```
```
sealos build -t kubernetes-with-nerdctl:v1.25.0 .
```

**Comment by cuisongliu** [comment]
> 最新版本的kubernetest集群镜像中删除了nerdctl，非常不方便，希望加回来。理由如下：
> 
> 1. 加载docker镜像需要使用sealos，但sealos只能root使用
> 2. 使用sealos命令加载镜像不是一个合适的方案，例如我的业务系统的部署脚本，原本在任意k8s集群都能执行，但现在无法在sealos安装的集群中使用。

或者你可以直接用docker的k8s

**Comment by itzhoujun** [comment]
看样子是不打算加回来了。虽然不知道处于什么考虑把nerdctl去掉了，但从用户角度来说，这是个减分项

**Comment by cuisongliu** [comment]
本身就是k8s 角度考虑，不添加其他无用东西。如果想用可自行制作镜像。
