### ISSUE TITLE
Feature: update kubesphere cloud image to v3.3.1

### ISSUE THREAD

**Issue by willzhang** [labring/sealos#1983]
**Which command or component**

sealos build

**Detailed description of the feature**

```
registry.cn-shenzhen.aliyuncs.com/cnmirror/kubesphere:v3.3.1
```

**If you have solution，please describe it**
```
sealos pull registry.cn-shenzhen.aliyuncs.com/cnmirror/kubesphere:v3.3.1
sealos tag registry.cn-shenzhen.aliyuncs.com/cnmirror/kubesphere:v3.3.1 labring/kubesphere:v3.3.1
sealos push labring/kubesphere:v3.3.1
```

**Comment by willzhang** [comment]
@cuisongliu

**Comment by cuisongliu** [comment]
@willzhang   cluster-image repo add sync cluster-image is ok

**Comment by cuisongliu** [comment]
https://github.com/labring/cluster-image/actions/runs/3352120882/jobs/5554043412

**Comment by willzhang** [comment]
Fixed by: https://github.com/labring/cluster-image/pull/215

**Comment by cuisongliu** [comment]
<img width="899" alt="image" src="https://user-images.githubusercontent.com/4150905/198844912-12652023-f181-4d8c-b3c6-3ebeb6a74921.png">
