### ISSUE TITLE
unable to authenticate, attempt methods [none publickey password]

### ISSUE THREAD

**Issue by kylezhou1992** [labring/sealos#1991]
sealos init --passwd '' \
--master 192.168.142.21 \
--node 192.168.142.22 \
--node 192.168.142.23 \
-pkg-url <path> \
--version 1.22.3

sealos version 3.3.9-rc.10

[ssh][192.168.142.21:22]Error create ssh session failed,ssh: handshake failed: ssh: unable toauthenticate, attempted methods [none publickey password], no supported methods remain

互信已经建立，节点可以直连

**Comment by cuisongliu** [comment]
目前已经不维护3.x了。升级4.x用吧
