### ISSUE TITLE
error Applied to cluster error: exec remote command failed IPXXXX /var/lib/sealos/data/default/rootfs/opt/sealctl token exit status 1

### ISSUE THREAD

**Issue by yssy2519** [labring/sealos#1998]
**Which command or component**

sealos install ...

**The Description of the bug**
之前再3台内网机器成功安装sealos 4.0,之后执行sealos reset 重新安装的时候报错
info start to get kubernetes token...
error Applied to cluster error: exec remote command failed 10.4.114.42:22 /var/lib/sealos/data/default/rootfs/opt/sealctl token exit status 1

**How to reproduce（pictures can be attached if necessary）**
[root@master k8s]# sealos run localhost/labring/helm:v3.8.2 localhost/labring/kubernetes:v1.25.0 localhost/labring/calico:v3.24.1 --masters 10.4.114.42 --nodes 10.4.114.43,10.4.114.44 -p '123456'
2022-11-01T15:43:52 info Start to create a new cluster: master [10.4.114.42], worker [10.4.114.43 10.4.114.44]
2022-11-01T15:43:52 info Executing pipeline Check in CreateProcessor.
2022-11-01T15:43:52 info checker:hostname [10.4.114.42:22 10.4.114.43:22 10.4.114.44:22]
2022-11-01T15:43:52 info checker:timeSync [10.4.114.42:22 10.4.114.43:22 10.4.114.44:22]
2022-11-01T15:43:53 info Executing pipeline PreProcess in CreateProcessor.
1123e8b4b455ed291f3ec7273af62e49458fe3dd141f5e7cb2a4243d6284deec
c6bba3bcca6e9370943b50c9cbee328b74638c534a6656ff5b36bb3e7f63b4bd
e2122fc58fd32f1c93ac75da5c473aed746f1ad9b31a73d1f81a0579b96e775b
default-7a4j8do0
default-18fizihr
default-smj6fpdc
2022-11-01T15:43:53 info Executing pipeline RunConfig in CreateProcessor.
2022-11-01T15:43:53 info Executing pipeline MountRootfs in CreateProcessor.
[1/1]copying files to 10.4.114.43:22  25% [==>            ] (1/4, 4 it/s) [0s:0s]which: no docker in (/home/python/python-3.9.5/bin:/home/kafka/local/flume/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/java/jdk1.8.0_201/bin:/usr/java/jdk1.8.0_201/jre/bin:/home/kafka/local/zookeeper-3.4.5/bin:/home/kafka/local/zookeeper-3.4.5/conf:/home/kafka/local/kafka_2.11-2.1.1/bin:/home/kafka/local/zookeeper-3.4.5/bin:/home/kafka/local/zookeeper-3.4.5/conf:/root/bin)
 WARN [2022-11-01 15:44:15] >> Replace disable_apparmor = false to disable_apparmor = true
 INFO [2022-11-01 15:44:15] >> check root,port,cri success
Created symlink from /etc/systemd/system/multi-user.target.wants/containerd.service to /etc/systemd/system/containerd.service.
 INFO [2022-11-01 15:44:17] >> Health check containerd!
 INFO [2022-11-01 15:44:17] >> containerd is running
 INFO [2022-11-01 15:44:17] >> init containerd success
Created symlink from /etc/systemd/system/multi-user.target.wants/image-cri-shim.service to /etc/systemd/system/image-cri-shim.service.
 INFO [2022-11-01 15:44:17] >> Health check image-cri-shim!
 INFO [2022-11-01 15:44:17] >> image-cri-shim is running
 INFO [2022-11-01 15:44:17] >> init shim success
* Applying /usr/lib/sysctl.d/00-system.conf ...
net.bridge.bridge-nf-call-ip6tables = 0
net.bridge.bridge-nf-call-iptables = 0
net.bridge.bridge-nf-call-arptables = 0
* Applying /usr/lib/sysctl.d/10-default-yama-scope.conf ...
kernel.yama.ptrace_scope = 0
* Applying /usr/lib/sysctl.d/50-default.conf ...
kernel.sysrq = 16
kernel.core_uses_pid = 1
kernel.kptr_restrict = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.accept_source_route = 0
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.promote_secondaries = 1
net.ipv4.conf.all.promote_secondaries = 1
fs.protected_hardlinks = 1
fs.protected_symlinks = 1
* Applying /etc/sysctl.d/90-omnibus-gitlab-kernel.sem.conf ...
kernel.sem = 250 32000 32 262
* Applying /etc/sysctl.d/90-omnibus-gitlab-kernel.shmall.conf ...
kernel.shmall = 4194304
* Applying /etc/sysctl.d/90-omnibus-gitlab-kernel.shmmax.conf ...
kernel.shmmax = 17179869184
* Applying /etc/sysctl.d/90-omnibus-gitlab-net.core.somaxconn.conf ...
net.core.somaxconn = 1024
* Applying /etc/sysctl.d/99-sysctl.conf ...
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
* Applying /etc/sysctl.d/k8s.conf ...
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.conf.all.rp_filter = 0
* Applying /etc/sysctl.conf ...
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv4.ip_forward = 1
 INFO [2022-11-01 15:44:17] >> init kube success
 INFO [2022-11-01 15:44:17] >> init containerd rootfs success
10.4.114.43:22: which: no docker in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)
10.4.114.43:22:  WARN [2022-11-01 15:45:23] >> Replace disable_apparmor = false to disable_apparmor = true
10.4.114.43:22:  INFO [2022-11-01 15:45:23] >> check root,port,cri success
10.4.114.44:22: which: no docker in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)
10.4.114.44:22:  WARN [2022-11-01 15:45:22] >> Replace disable_apparmor = false to disable_apparmor = true
10.4.114.44:22:  INFO [2022-11-01 15:45:22] >> check root,port,cri success
10.4.114.43:22: Created symlink from /etc/systemd/system/multi-user.target.wants/containerd.service to /etc/systemd/system/containerd.service.
10.4.114.43:22:  INFO [2022-11-01 15:45:25] >> Health check containerd!
10.4.114.43:22:  INFO [2022-11-01 15:45:25] >> containerd is running
10.4.114.43:22:  INFO [2022-11-01 15:45:25] >> init containerd success
10.4.114.43:22: Created symlink from /etc/systemd/system/multi-user.target.wants/image-cri-shim.service to /etc/systemd/system/image-cri-shim.service.
10.4.114.43:22:  INFO [2022-11-01 15:45:25] >> Health check image-cri-shim!
10.4.114.43:22:  INFO [2022-11-01 15:45:25] >> image-cri-shim is running
10.4.114.43:22:  INFO [2022-11-01 15:45:25] >> init shim success
10.4.114.43:22: 127.0.0.1 oracledb localhost localhost.localdomain
10.4.114.43:22: * Applying /usr/lib/sysctl.d/00-system.conf ...
10.4.114.43:22: net.bridge.bridge-nf-call-ip6tables = 0
10.4.114.43:22: net.bridge.bridge-nf-call-iptables = 0
10.4.114.43:22: net.bridge.bridge-nf-call-arptables = 0
10.4.114.43:22: * Applying /usr/lib/sysctl.d/10-default-yama-scope.conf ...
10.4.114.43:22: kernel.yama.ptrace_scope = 0
10.4.114.43:22: * Applying /usr/lib/sysctl.d/50-default.conf ...
10.4.114.43:22: kernel.sysrq = 16
10.4.114.43:22: kernel.core_uses_pid = 1
10.4.114.43:22: net.ipv4.conf.default.rp_filter = 1
10.4.114.43:22: net.ipv4.conf.all.rp_filter = 1
10.4.114.43:22: net.ipv4.conf.default.accept_source_route = 0
10.4.114.43:22: net.ipv4.conf.all.accept_source_route = 0
10.4.114.43:22: net.ipv4.conf.default.promote_secondaries = 1
10.4.114.43:22: net.ipv4.conf.all.promote_secondaries = 1
10.4.114.43:22: fs.protected_hardlinks = 1
10.4.114.43:22: fs.protected_symlinks = 1
10.4.114.43:22: * Applying /usr/lib/sysctl.d/60-libvirtd.conf ...
10.4.114.43:22: fs.aio-max-nr = 1048576
10.4.114.43:22: * Applying /etc/sysctl.d/99-sysctl.conf ...
10.4.114.43:22: fs.aio-max-nr = 1048576
10.4.114.43:22: fs.file-max = 6815744
10.4.114.43:22: kernel.shmall = 2097152
10.4.114.43:22: kernel.shmmax = 4294967295
10.4.114.43:22: kernel.shmmni = 4096
10.4.114.43:22: kernel.sem = 250 32000 100 128
10.4.114.43:22: net.ipv4.ip_local_port_range = 9000 65500
10.4.114.43:22: net.core.rmem_default = 262144
10.4.114.43:22: net.core.rmem_max = 4194304
10.4.114.43:22: net.core.wmem_default = 262144
10.4.114.43:22: net.core.wmem_max = 1048576
10.4.114.43:22: * Applying /etc/sysctl.d/k8s.conf ...
10.4.114.43:22: net.bridge.bridge-nf-call-ip6tables = 1
10.4.114.43:22: net.bridge.bridge-nf-call-iptables = 1
10.4.114.43:22: net.ipv4.conf.all.rp_filter = 0
10.4.114.43:22: * Applying /etc/sysctl.conf ...
10.4.114.43:22: fs.aio-max-nr = 1048576
10.4.114.43:22: fs.file-max = 6815744
10.4.114.43:22: kernel.shmall = 2097152
10.4.114.43:22: kernel.shmmax = 4294967295
10.4.114.43:22: kernel.shmmni = 4096
10.4.114.43:22: kernel.sem = 250 32000 100 128
10.4.114.43:22: net.ipv4.ip_local_port_range = 9000 65500
10.4.114.43:22: net.core.rmem_default = 262144
10.4.114.43:22: net.core.rmem_max = 4194304
10.4.114.43:22: net.core.wmem_default = 262144
10.4.114.43:22: net.core.wmem_max = 1048576
10.4.114.43:22: net.ipv4.ip_forward = 1
10.4.114.44:22: Created symlink from /etc/systemd/system/multi-user.target.wants/containerd.service to /etc/systemd/system/containerd.service.
10.4.114.43:22:  INFO [2022-11-01 15:45:25] >> init kube success
10.4.114.43:22:  INFO [2022-11-01 15:45:25] >> init containerd rootfs success
10.4.114.44:22:  INFO [2022-11-01 15:45:25] >> Health check containerd!
10.4.114.44:22:  INFO [2022-11-01 15:45:25] >> containerd is running
10.4.114.44:22:  INFO [2022-11-01 15:45:25] >> init containerd success
10.4.114.44:22: Created symlink from /etc/systemd/system/multi-user.target.wants/image-cri-shim.service to /etc/systemd/system/image-cri-shim.service.
10.4.114.44:22:  INFO [2022-11-01 15:45:25] >> Health check image-cri-shim!
10.4.114.44:22:  INFO [2022-11-01 15:45:25] >> image-cri-shim is running
10.4.114.44:22:  INFO [2022-11-01 15:45:25] >> init shim success
10.4.114.44:22: * Applying /usr/lib/sysctl.d/00-system.conf ...
10.4.114.44:22: net.bridge.bridge-nf-call-ip6tables = 0
10.4.114.44:22: net.bridge.bridge-nf-call-iptables = 0
10.4.114.44:22: net.bridge.bridge-nf-call-arptables = 0
10.4.114.44:22: * Applying /usr/lib/sysctl.d/10-default-yama-scope.conf ...
10.4.114.44:22: kernel.yama.ptrace_scope = 0
10.4.114.44:22: * Applying /usr/lib/sysctl.d/50-default.conf ...
10.4.114.44:22: kernel.sysrq = 16
10.4.114.44:22: kernel.core_uses_pid = 1
10.4.114.44:22: net.ipv4.conf.default.rp_filter = 1
10.4.114.44:22: net.ipv4.conf.all.rp_filter = 1
10.4.114.44:22: net.ipv4.conf.default.accept_source_route = 0
10.4.114.44:22: net.ipv4.conf.all.accept_source_route = 0
10.4.114.44:22: net.ipv4.conf.default.promote_secondaries = 1
10.4.114.44:22: net.ipv4.conf.all.promote_secondaries = 1
10.4.114.44:22: fs.protected_hardlinks = 1
10.4.114.44:22: fs.protected_symlinks = 1
10.4.114.44:22: * Applying /usr/lib/sysctl.d/60-libvirtd.conf ...
10.4.114.44:22: fs.aio-max-nr = 1048576
10.4.114.44:22: * Applying /etc/sysctl.d/99-sysctl.conf ...
10.4.114.44:22: * Applying /etc/sysctl.d/k8s.conf ...
10.4.114.44:22: net.bridge.bridge-nf-call-ip6tables = 1
10.4.114.44:22: net.bridge.bridge-nf-call-iptables = 1
10.4.114.44:22: net.ipv4.conf.all.rp_filter = 0
10.4.114.44:22: * Applying /etc/sysctl.conf ...
10.4.114.44:22: net.ipv4.ip_forward = 1
10.4.114.44:22:  INFO [2022-11-01 15:45:25] >> init kube success
10.4.114.44:22:  INFO [2022-11-01 15:45:25] >> init containerd rootfs success
2022-11-01T15:45:27 info Executing pipeline Init in CreateProcessor.
2022-11-01T15:45:27 info start to copy kubeadm config to master0
2022-11-01T15:45:27 info start to generate cert and kubeConfig...
2022-11-01T15:45:27 info start to generator cert and copy to masters...
2022-11-01T15:45:28 info apiserver altNames : {map[apiserver.cluster.local:apiserver.cluster.local kubernetes:kubernetes kubernetes.default:kubernetes.default kubernetes.default.svc:kubernetes.default.svc kubernetes.default.svc.cluster.local:kubernetes.default.svc.cluster.local localhost:localhost master:master] map[10.103.97.2:10.103.97.2 10.4.114.42:10.4.114.42 10.96.0.1:10.96.0.1 127.0.0.1:127.0.0.1]}
2022-11-01T15:45:28 info Etcd altnames : {map[localhost:localhost master:master] map[10.4.114.42:10.4.114.42 127.0.0.1:127.0.0.1 ::1:::1]}, commonName : master
2022-11-01T15:45:29 info start to copy etc pki files to masters
2022-11-01T15:45:29 info start to create kubeconfig...
2022-11-01T15:45:30 info start to copy kubeconfig files to masters
2022-11-01T15:45:30 info start to copy static files to masters
2022-11-01T15:45:30 info start to apply registry
Created symlink from /etc/systemd/system/multi-user.target.wants/registry.service to /etc/systemd/system/registry.service.
 INFO [2022-11-01 15:45:30] >> Health check registry!
 INFO [2022-11-01 15:45:30] >> registry is running
 INFO [2022-11-01 15:45:30] >> init registry success
2022-11-01T15:45:30 info start to init master0...
2022-11-01T15:45:30 info registry auth in node 10.4.114.42:22
2022-11-01T15:45:30 info domain sealos.hub:10.4.114.42 append success
2022-11-01T15:45:30 info domain apiserver.cluster.local:10.4.114.42 append success
W1101 15:45:30.644546    4457 initconfiguration.go:119] Usage of CRI endpoints without URL scheme is deprecated and can cause kubelet errors in the future. Automatically prepending scheme "unix" to the "criSocket" with value "/run/containerd/containerd.sock". Please update your configuration!
[init] Using Kubernetes version: v1.25.0
[preflight] Running pre-flight checks
        [WARNING FileExisting-socat]: socat not found in system path
        [WARNING Hostname]: hostname "master" could not be reached
        [WARNING Hostname]: hostname "master": lookup master on [::1]:53: dial udp [::1]:53: connect: network is unreachable
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Using existing apiserver-kubelet-client certificate and key on disk
[certs] Using existing front-proxy-ca certificate authority
[certs] Using existing front-proxy-client certificate and key on disk
[certs] Using existing etcd/ca certificate authority
[certs] Using existing etcd/server certificate and key on disk
[certs] Using existing etcd/peer certificate and key on disk
[certs] Using existing etcd/healthcheck-client certificate and key on disk
[certs] Using existing apiserver-etcd-client certificate and key on disk
[certs] Using the existing "sa" key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/admin.conf"
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/kubelet.conf"
W1101 15:45:56.522150    4457 kubeconfig.go:249] a kubeconfig file "/etc/kubernetes/controller-manager.conf" exists already but has an unexpected API Server URL: expected: https://10.4.114.42:6443, got: https://apiserver.cluster.local:6443
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/controller-manager.conf"
W1101 15:45:56.617965    4457 kubeconfig.go:249] a kubeconfig file "/etc/kubernetes/scheduler.conf" exists already but has an unexpected API Server URL: expected: https://10.4.114.42:6443, got: https://apiserver.cluster.local:6443
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/scheduler.conf"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[apiclient] All control plane components are healthy after 8.504557 seconds
[upload-config] Storing the configuration used in ConfigMap "kubeadm-config" in the "kube-system" Namespace
[kubelet] Creating a ConfigMap "kubelet-config" in namespace kube-system with the configuration for the kubelets in the cluster
[upload-certs] Skipping phase. Please see --upload-certs
[mark-control-plane] Marking the node master as control-plane by adding the labels: [node-role.kubernetes.io/control-plane node.kubernetes.io/exclude-from-external-load-balancers]
[mark-control-plane] Marking the node master as control-plane by adding the taints [node-role.kubernetes.io/control-plane:NoSchedule]
[bootstrap-token] Configuring bootstrap tokens, cluster-info ConfigMap, RBAC Roles
[bootstrap-token] Configured RBAC rules to allow Node Bootstrap tokens to get nodes
[bootstrap-token] Configured RBAC rules to allow Node Bootstrap tokens to post CSRs in order for nodes to get long term certificate credentials
[bootstrap-token] Configured RBAC rules to allow the csrapprover controller automatically approve CSRs from a Node Bootstrap Token
[bootstrap-token] Configured RBAC rules to allow certificate rotation for all node client certificates in the cluster
[bootstrap-token] Creating the "cluster-info" ConfigMap in the "kube-public" namespace
[kubelet-finalize] Updating "/etc/kubernetes/kubelet.conf" to point to a rotatable kubelet client certificate and key
[addons] Applied essential addon: CoreDNS
[addons] Applied essential addon: kube-proxy

Your Kubernetes control-plane has initialized successfully!

To start using your cluster, you need to run the following as a regular user:

  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config

Alternatively, if you are the root user, you can run:

  export KUBECONFIG=/etc/kubernetes/admin.conf

You should now deploy a pod network to the cluster.
Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
  https://kubernetes.io/docs/concepts/cluster-administration/addons/

You can now join any number of control-plane nodes by copying certificate authorities
and service account keys on each node and then running the following as root:

  kubeadm join apiserver.cluster.local:6443 --token <value withheld> \
        --discovery-token-ca-cert-hash sha256:ad12d4b2f3882138963e810158682e28e42644b4a94449931a2fa4b2e742e6d9 \
        --control-plane --certificate-key <value withheld>

Then you can join any number of worker nodes by running the following on each as root:

kubeadm join apiserver.cluster.local:6443 --token <value withheld> \
        --discovery-token-ca-cert-hash sha256:ad12d4b2f3882138963e810158682e28e42644b4a94449931a2fa4b2e742e6d9
2022-11-01T15:46:09 info Executing pipeline Join in CreateProcessor.
2022-11-01T15:46:09 info [10.4.114.43:22 10.4.114.44:22] will be added as worker
2022-11-01T15:46:09 info start to get kubernetes token...
2022-11-01T15:47:24 error Applied to cluster error: exec remote command failed 10.4.114.42:22 /var/lib/sealos/data/default/rootfs/opt/sealctl token exit status 1
2022-11-01T15:47:24 info
      ___           ___           ___           ___       ___           ___
     /\  \         /\  \         /\  \         /\__\     /\  \         /\  \
    /::\  \       /::\  \       /::\  \       /:/  /    /::\  \       /::\  \
   /:/\ \  \     /:/\:\  \     /:/\:\  \     /:/  /    /:/\:\  \     /:/\ \  \
  _\:\~\ \  \   /::\~\:\  \   /::\~\:\  \   /:/  /    /:/  \:\  \   _\:\~\ \  \
 /\ \:\ \ \__\ /:/\:\ \:\__\ /:/\:\ \:\__\ /:/__/    /:/__/ \:\__\ /\ \:\ \ \__\
 \:\ \:\ \/__/ \:\~\:\ \/__/ \/__\:\/:/  / \:\  \    \:\  \ /:/  / \:\ \:\ \/__/
  \:\ \:\__\    \:\ \:\__\        \::/  /   \:\  \    \:\  /:/  /   \:\ \:\__\
   \:\/:/  /     \:\ \/__/        /:/  /     \:\  \    \:\/:/  /     \:\/:/  /
    \::/  /       \:\__\         /:/  /       \:\__\    \::/  /       \::/  /
     \/__/         \/__/         \/__/         \/__/     \/__/         \/__/

                  Website :https://www.sealos.io/
                  Address :github.com/labring/sealos

**What you expected to happen**

之前都正常用一阵了 这次重新安装sealos reset 之后就不行了 换成4.1.3 新版本也不好用。
感觉是环境被污染了，哪位大佬帮忙看看遇到过这样的问题没有 谢谢啦

**Operating environment**

- centos7.6+
- kubernetes:v1.25.0
- Sealos 4.1.3
- calico:v3.24.1
- helm:v3.8.2
- Cluster size: eg 1 master, 2 node

**Comment by yssy2519** [comment]
最后异常的截图是这样的
![image](https://user-images.githubusercontent.com/31470889/199189266-80fc60d3-92ed-41e3-9f48-e71785adbaa5.png)

**Comment by yssy2519** [comment]
我又手动执行了一下最后这个报错的命令
![image](https://user-images.githubusercontent.com/31470889/199198066-771ba7d6-0cfd-48e9-befc-dc0a00d0c0ad.png)

**Comment by cuisongliu** [comment]
https://github.com/labring/sealos/pull/1936  这个修复这个问题了

**Comment by cuisongliu** [comment]
> 我又手动执行了一下最后这个报错的命令
> ![image](https://user-images.githubusercontent.com/31470889/199198066-771ba7d6-0cfd-48e9-befc-dc0a00d0c0ad.png)

手动删除所有的token再执行

**Comment by cuisongliu** [comment]
> > 我又手动执行了一下最后这个报错的命令
> > ![image](https://user-images.githubusercontent.com/31470889/199198066-771ba7d6-0cfd-48e9-befc-dc0a00d0c0ad.png)
> 
> 手动删除所有的token再执行

kubeadm token 命令

**Comment by yssy2519** [comment]
执行这个命令的时候报错了没办法看到tonken
 kubeadm token list
![image](https://user-images.githubusercontent.com/31470889/199207057-cf117822-a0cd-47c2-afe4-6009f27bf4e4.png)

**Comment by yssy2519** [comment]
> 执行这个命令的时候报错了没办法看到tonken kubeadm token list ![image](https://user-images.githubusercontent.com/31470889/199207057-cf117822-a0cd-47c2-afe4-6009f27bf4e4.png)



> > > 我又手动执行了一下最后这个报错的命令
> > > ![image](https://user-images.githubusercontent.com/31470889/199198066-771ba7d6-0cfd-48e9-befc-dc0a00d0c0ad.png)
> > 
> > 
> > 手动删除所有的token再执行
> 
> kubeadm token 命令

执行这个命令的时候报错了没办法看到tonken
 kubeadm token list
![image](https://user-images.githubusercontent.com/31470889/199207057-cf117822-a0cd-47c2-afe4-6009f27bf4e4.png)

**Comment by yssy2519** [comment]
修好了
root 运行这个命令
 export KUBECONFIG=/etc/kubernetes/admin.conf

之后再运行
kubeadm token list
 kubeadm token delete XXX

sealos reset
sealos 安装就行了 集群已经正常启动了
感谢大佬帮忙

> > > 我又手动执行了一下最后这个报错的命令
> > > ![image](https://user-images.githubusercontent.com/31470889/199198066-771ba7d6-0cfd-48e9-befc-dc0a00d0c0ad.png)
> > 
> > 
> > 手动删除所有的token再执行
> 
> kubeadm token 命令

修好了
root 运行这个命令
 export KUBECONFIG=/etc/kubernetes/admin.conf

之后再运行
kubeadm token list
 kubeadm token delete XXX

sealos reset
sealos 安装就行了 集群已经正常启动了
感谢大佬帮忙
