### ISSUE TITLE
BUG: all cluster image shared one `manifests` directory

### ISSUE THREAD

**Issue by maslow** [labring/sealos#2001]
**Which command or component**

If we have 2 cluster images like this,  both have `apply -f manifests/` command.

```
FROM scratch

USER 65532:65532

COPY manifests ./manifests
COPY registry ./registry
CMD ["kubectl apply -f manifests/"]
```

When executing `sealos run` any of the two images, will `apply` both their `manifests`. 

Fatal bug:

Every time I run `sealos run` on an image, it will apply all the manifests that have been applied in the past, even if a previously used image has been uninstalled and discarded.

**Comment by willzhang** [comment]
maybe should add one directory distinguish with other app
```
kubectl apply -f manifests/<your-app-name>/
```

**Comment by cuisongliu** [comment]
https://github.com/labring/sealos/issues/2014

**Comment by fanux** [comment]
https://github.com/labring/sealos/pull/2048
