### ISSUE TITLE
Question: where  will sealos save images to when run `sealos build/pull`?

### ISSUE THREAD

**Issue by willzhang** [labring/sealos#2008]
### Detailed description of the question.

where  will sealos save images to when run `sealos build/pull/run`?
```
sealos build
sealos pull 
sealos run
```

**Comment by cuisongliu** [comment]
buildah storage where

**Comment by willzhang** [comment]
1、when run sealos build it save to  /var/lib/containers
```
STEP 1/6: FROM scratch
STEP 2/6: ENV hostname rancher.my.org
STEP 3/6: ENV ingressClassName nginx
STEP 4/6: COPY charts charts
STEP 5/6: COPY registry registry
```
theis
```
root@ubuntu:/var/tmp# du -sh /var/lib/containers
15G     /var/lib/containers
root@ubuntu:/var/tmp# du -sh /var/lib/containers
38G     /var/lib/containers
root@ubuntu:/var/tmp# du -sh /var/lib/containers
73G     /var/lib/containers
```

**Comment by willzhang** [comment]
1、when run sealos pull
when at `Copying blob 3b67941b0106` step, it save to /var/tmp
```
root@node1:~# du -sh /var/tmp/
32G     /var/tmp/
```
when at `Writing manifest to image destination` step, it save to /var/lib/containers
```
root@node1:~# du -sh /var/lib/containers
35G     /var/lib/containers
```

finaly the /var/tmp space will release
```
root@node1:~# du -sh /var/tmp/
38M     /var/tmp/
```

result: during run sealos pull it need `image size*2` space.

**Comment by willzhang** [comment]
Pay attention to disk planning in the production environment.

containerd use `/var/lib/containerd/`
sealos use `/var/lib/containers/`

```
root@node-01:~# du -sh /var/lib/containerd/
9.6G    /var/lib/containerd/

root@node-01:~# du -sh /var/lib/containers/
66G     /data/containers/
```
