### ISSUE TITLE
Docs: Construction of sealos development guidelines document

### ISSUE THREAD

**Issue by fanux** [labring/sealos#2009]
### What is the problem this feature will solve?

sealos lacks developer introduction documentation

### If you have solution，please describe it

- what is sealos
    - FAQ
- Basic use of sealos
    - What is sealos image
    - Install a highly available kubernetes cluster using sealos
    - Use sealos image to deploy other applications, database/object storage/ingress, etc.
    - Use sealos cloud
- Basic knowledge of sealos development
    - Docker basic usage and image construction
    - Basic usage and basic concepts of kubernetes
    - Introduction to the core components of kubernetes
    - Understand the role of core components through a deployment creation
- Advanced knowledge of sealos development
    - kubernetes custom resource CRD principle
    - Develop kubernetes custom resource CRD practice
    - Develop custom kubernetes webhook practice
    - Develop kubernetes aggregator server
- sealos development tutorial
    - Build development environment & compile source code
    - Sorting out the core process of sealos run and analyzing the source code structure
    - Module explanation
        - apply module - the expected state of the cluster is consistent with the actual state
        - Introduction to the Cluster structure - throughout
        - SSH SDK - Introduction to Remote Operation Library
        - Runtime module - to actually execute the logic
        - Filesystem module - File distribution
        - Config module - configuration file handling
        - Checker module - pre-check and post-check
        - Plugin Mechanism - Extension Plugin
    - sealos authentication and user management
    - User permission design
    - Controller
        - Application management
        - Cluster management
        - Infrastructure Management
        - Metered billing
        - webterminal
        - User Management

**Comment by cuisongliu** [comment]
https://github.com/labring/sealos/blob/main/DEVELOPGUIDE.md#using-sealos-image-ci  using github ci for container image and sealos image
