### ISSUE TITLE
helm install 相关问题

### ISSUE THREAD

**Issue by lovese** [labring/sealos#2011]
### Detailed description of the question.

我搭建好 k8s 集群后，发现 helm install 安装应用时，拉取不到 dockerhub 上的镜像，然后我用 sealos 拉取镜像后，pod 还是提示拉取镜像失败，这个要怎么解决？

**Comment by cuisongliu** [comment]
用sealos镜像吧，你需要安装什么镜像

**Comment by lovese** [comment]
比如我要安装 portainer ，我用 helm install portainer 安装不了

**Comment by lovese** [comment]
这个集群只能安装sealos镜像吗？不能安装helm仓库的应用么

**Comment by lovese** [comment]
我用 sealos run 之后为什么没有 sealos stop 或者 sealos rm 等命令，不然运行的应用只能用 kubectl 来停止或者删除

**Comment by cuisongliu** [comment]
> 这个集群只能安装sealos镜像吗？不能安装helm仓库的应用么

可以的只是镜像你不一定能拉取下来

**Comment by cuisongliu** [comment]
网络原因会导致这些问题
