### ISSUE TITLE
kubelet初始化错误

### ISSUE THREAD

**Issue by dixon1983** [labring/sealos#2012]
### Sealos Version

4.1.3-arm

### How to reproduce the bug?

操作系统：统信1050d，内核版本4.19.0。cup架构arm64。安装时[kubelet-check] Initial timeout of 40s passed.卡住，最后超时报错。 containerd日志报错：level=error msg="copy shim log" error="read /proc/self/fd/17: file already closed"
11月 02 07:02:13 k8smaster containerd[8311]: time="2022-11-02T07:02:13.291506300+08:00" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:kube-scheduler-k8smaster,Uid:749dfd80a1a94bf2426e4aa416b1b2bc,Namespace:kube-system,Attempt:0  容器没有启动起来，导致后续的操作一直报连接不到k8smaster的6443端口。该端口确实没有被被监听到

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cuisongliu** [comment]
把kubelet日志都打全一些 看一下

**Comment by dixon1983** [comment]
kubelet日志就是重复报找不到主节点
11月 02 08:35:37 k8smaster kubelet[9121]: E1102 08:35:37.301250    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:37 k8smaster kubelet[9121]: E1102 08:35:37.401619    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:37 k8smaster kubelet[9121]: E1102 08:35:37.502260    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:37 k8smaster kubelet[9121]: E1102 08:35:37.602815    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:37 k8smaster kubelet[9121]: E1102 08:35:37.703241    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:37 k8smaster kubelet[9121]: E1102 08:35:37.803970    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:37 k8smaster kubelet[9121]: E1102 08:35:37.817541    9121 kubelet.go:2373] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not
11月 02 08:35:37 k8smaster kubelet[9121]: E1102 08:35:37.904965    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:38 k8smaster kubelet[9121]: E1102 08:35:38.005377    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:38 k8smaster kubelet[9121]: E1102 08:35:38.106330    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:38 k8smaster kubelet[9121]: E1102 08:35:38.206816    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:38 k8smaster kubelet[9121]: E1102 08:35:38.282726    9121 remote_runtime.go:222] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OC
11月 02 08:35:38 k8smaster kubelet[9121]: E1102 08:35:38.282806    9121 kuberuntime_sandbox.go:71] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI run
11月 02 08:35:38 k8smaster kubelet[9121]: E1102 08:35:38.282834    9121 kuberuntime_manager.go:772] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI run
11月 02 08:35:38 k8smaster kubelet[9121]: E1102 08:35:38.282905    9121 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"etcd-k8smaster_kube-system(c761e9096472e6268c26dd85372fcf48)\" with CreatePod
11月 02 08:35:38 k8smaster kubelet[9121]: E1102 08:35:38.307816    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:38 k8smaster kubelet[9121]: E1102 08:35:38.408841    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:38 k8smaster kubelet[9121]: E1102 08:35:38.509725    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:38 k8smaster kubelet[9121]: E1102 08:35:38.610800    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:38 k8smaster kubelet[9121]: E1102 08:35:38.711221    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:38 k8smaster kubelet[9121]: E1102 08:35:38.811818    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:38 k8smaster kubelet[9121]: E1102 08:35:38.912259    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:39 k8smaster kubelet[9121]: E1102 08:35:39.013254    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:39 k8smaster kubelet[9121]: E1102 08:35:39.113351    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:39 k8smaster kubelet[9121]: E1102 08:35:39.213951    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:39 k8smaster kubelet[9121]: E1102 08:35:39.314735    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:39 k8smaster kubelet[9121]: E1102 08:35:39.415260    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:39 k8smaster kubelet[9121]: E1102 08:35:39.516080    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:39 k8smaster kubelet[9121]: E1102 08:35:39.616942    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:39 k8smaster kubelet[9121]: E1102 08:35:39.717401    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:39 k8smaster kubelet[9121]: E1102 08:35:39.817473    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:39 k8smaster kubelet[9121]: E1102 08:35:39.917882    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:40 k8smaster kubelet[9121]: E1102 08:35:40.018305    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:40 k8smaster kubelet[9121]: E1102 08:35:40.118477    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:40 k8smaster kubelet[9121]: E1102 08:35:40.218988    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:40 k8smaster kubelet[9121]: E1102 08:35:40.319293    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:40 k8smaster kubelet[9121]: E1102 08:35:40.419700    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:40 k8smaster kubelet[9121]: E1102 08:35:40.520251    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:40 k8smaster kubelet[9121]: E1102 08:35:40.620894    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:40 k8smaster kubelet[9121]: E1102 08:35:40.722173    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:40 k8smaster kubelet[9121]: E1102 08:35:40.822649    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:40 k8smaster kubelet[9121]: E1102 08:35:40.923077    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:41 k8smaster kubelet[9121]: E1102 08:35:41.023523    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:41 k8smaster kubelet[9121]: E1102 08:35:41.124540    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:41 k8smaster kubelet[9121]: E1102 08:35:41.225134    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:41 k8smaster kubelet[9121]: E1102 08:35:41.326573    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:41 k8smaster kubelet[9121]: W1102 08:35:41.351605    9121 manager.go:1174] Failed to process watch event {EventType:0 Name:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podc761e9096472e6268c26dd85372fcf48.slice/cr
11月 02 08:35:41 k8smaster kubelet[9121]: E1102 08:35:41.427361    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:41 k8smaster kubelet[9121]: E1102 08:35:41.527988    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:41 k8smaster kubelet[9121]: E1102 08:35:41.628620    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:41 k8smaster kubelet[9121]: E1102 08:35:41.678384    9121 controller.go:144] failed to ensure lease exists, will retry in 7s, error: Get "https://apiserver.cluster.local:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lea
11月 02 08:35:41 k8smaster kubelet[9121]: E1102 08:35:41.729471    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:41 k8smaster kubelet[9121]: E1102 08:35:41.829943    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:41 k8smaster kubelet[9121]: E1102 08:35:41.930389    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
11月 02 08:35:42 k8smaster kubelet[9121]: E1102 08:35:42.030940    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"

**Comment by cuisongliu** [comment]
11月 02 08:35:38 k8smaster kubelet[9121]: E1102 08:35:38.282726 9121 remote_runtime.go:222] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OC
11月 02 08:35:38 k8smaster kubelet[9121]: E1102 08:35:38.282806 9121 kuberuntime_sandbox.go:71] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI run
11月 02 08:35:38 k8smaster kubelet[9121]: E1102 08:35:38.282834 9121 kuberuntime_manager.go:772] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI run
11月 02 08:35:38 k8smaster kubelet[9121]: E1102 08:35:38.282905 9121 pod_workers.go:96

这块日志不全。看一下这行什么原因导致

**Comment by dixon1983** [comment]
怎么更进一步看日志呢？日志级别已经到9了

**Comment by cuisongliu** [comment]
> 怎么更进一步看日志呢？日志级别已经到9了

把日志输出到本地看，终端可能看不全

**Comment by dixon1983** [comment]
我没有找到输出到本地的方法，这里面好像有其它错误日志：
E1102 18:35:40.134819    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:40.235478    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:40.247066    9121 remote_runtime.go:222] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create faile
E1102 18:35:40.247136    9121 kuberuntime_sandbox.go:71] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: un
E1102 18:35:40.247164    9121 kuberuntime_manager.go:772] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: un
E1102 18:35:40.247238    9121 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"kube-scheduler-k8smaster_kube-system(749dfd80a1a94bf2426e4aa416b1b2bc)\" with CreatePodSandboxError: \"Failed to create
E1102 18:35:40.336273    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:40.436781    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:40.537793    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
I1102 18:35:40.616794    9121 kubelet_node_status.go:70] "Attempting to register node" node="k8smaster"
E1102 18:35:40.617256    9121 kubelet_node_status.go:92] "Unable to register node with API server" err="Post \"https://apiserver.cluster.local:6443/api/v1/nodes\": dial tcp 172.249.2.57:6443: connect: connection refused" node="k8smaster"
E1102 18:35:40.638383    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:40.654189    9121 kubelet.go:2373] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
E1102 18:35:40.738651    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:40.747453    9121 controller.go:144] failed to ensure lease exists, will retry in 7s, error: Get "https://apiserver.cluster.local:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/k8smaster?timeout=10s": dial tcp
E1102 18:35:40.839813    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:40.940082    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:41.040854    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:41.141920    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:41.242454    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:41.343000    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:41.443661    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:41.544396    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:41.644964    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:41.745354    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:41.845869    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:41.946513    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:42.047344    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:42.148171    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:42.248729    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:42.349192    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:42.449817    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:42.550492    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:42.651209    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:42.752051    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:42.852652    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:42.953537    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:43.053741    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:43.154805    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
W1102 18:35:43.216177    9121 reflector.go:424] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.RuntimeClass: Get "https://apiserver.cluster.local:6443/apis/node.k8s.io/v1/runtimeclasses?limit=500&resourceVersion=0": dia
E1102 18:35:43.216264    9121 reflector.go:140] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: Get "https://apiserver.cluster.local:6443/apis/node.k8s.io/v1/runtimeclasses
E1102 18:35:43.247582    9121 remote_runtime.go:222] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create faile
E1102 18:35:43.247649    9121 kuberuntime_sandbox.go:71] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: un
E1102 18:35:43.247674    9121 kuberuntime_manager.go:772] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: un
E1102 18:35:43.247775    9121 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"etcd-k8smaster_kube-system(c761e9096472e6268c26dd85372fcf48)\" with CreatePodSandboxError: \"Failed to create sandbox f
E1102 18:35:43.255718    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
W1102 18:35:43.320986    9121 manager.go:1174] Failed to process watch event {EventType:0 Name:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod749dfd80a1a94bf2426e4aa416b1b2bc.slice/cri-containerd-a4ce1c8546245eb83aed6226863f5
E1102 18:35:43.355953    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:43.456546    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:43.557228    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:43.657943    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:43.758434    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:43.858955    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:43.959558    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:44.059963    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
 ESCOD

E1102 18:35:40.134819    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:40.235478    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:40.247066    9121 remote_runtime.go:222] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create faile
E1102 18:35:40.247136    9121 kuberuntime_sandbox.go:71] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: un
E1102 18:35:40.247164    9121 kuberuntime_manager.go:772] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: un
E1102 18:35:40.247238    9121 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"kube-scheduler-k8smaster_kube-system(749dfd80a1a94bf2426e4aa416b1b2bc)\" with CreatePodSandboxError: \"Failed to create
E1102 18:35:40.336273    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:40.436781    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:40.537793    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
I1102 18:35:40.616794    9121 kubelet_node_status.go:70] "Attempting to register node" node="k8smaster"
E1102 18:35:40.617256    9121 kubelet_node_status.go:92] "Unable to register node with API server" err="Post \"https://apiserver.cluster.local:6443/api/v1/nodes\": dial tcp 172.249.2.57:6443: connect: connection refused" node="k8smaster"
E1102 18:35:40.638383    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:40.654189    9121 kubelet.go:2373] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
E1102 18:35:40.738651    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:40.747453    9121 controller.go:144] failed to ensure lease exists, will retry in 7s, error: Get "https://apiserver.cluster.local:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/k8smaster?timeout=10s": dial tcp
E1102 18:35:40.839813    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:40.940082    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:41.040854    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:41.141920    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:41.242454    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:41.343000    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:41.443661    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:41.544396    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:41.644964    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:41.745354    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:41.845869    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:41.946513    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:42.047344    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:42.148171    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:42.248729    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:42.349192    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:42.449817    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:42.550492    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:42.651209    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:42.752051    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:42.852652    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:42.953537    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:43.053741    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:43.154805    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
W1102 18:35:43.216177    9121 reflector.go:424] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.RuntimeClass: Get "https://apiserver.cluster.local:6443/apis/node.k8s.io/v1/runtimeclasses?limit=500&resourceVersion=0": dia
E1102 18:35:43.216264    9121 reflector.go:140] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: Get "https://apiserver.cluster.local:6443/apis/node.k8s.io/v1/runtimeclasses
E1102 18:35:43.247582    9121 remote_runtime.go:222] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create faile
E1102 18:35:43.247649    9121 kuberuntime_sandbox.go:71] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: un
E1102 18:35:43.247674    9121 kuberuntime_manager.go:772] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: un
E1102 18:35:43.247775    9121 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"etcd-k8smaster_kube-system(c761e9096472e6268c26dd85372fcf48)\" with CreatePodSandboxError: \"Failed to create sandbox f
E1102 18:35:43.255718    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
W1102 18:35:43.320986    9121 manager.go:1174] Failed to process watch event {EventType:0 Name:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod749dfd80a1a94bf2426e4aa416b1b2bc.slice/cri-containerd-a4ce1c8546245eb83aed6226863f5
E1102 18:35:43.355953    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:43.456546    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:43.557228    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:43.657943    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:43.758434    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:43.858955    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:43.959558    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"
E1102 18:35:44.059963    9121 kubelet.go:2448] "Error getting node" err="node \"k8smaster\" not found"

**Comment by cuisongliu** [comment]
https://blog.csdn.net/hedao0515/article/details/125994188 看样子好像内存不足导致

**Comment by zhangguanzhang** [comment]
```
journalctl -xe --no-pager -u kubelet 
```

**Comment by dixon1983** [comment]
对，我昨天网上也看到这个错误了，我的某个日志里也有这个错误。但是内存其实是够的，有16G呢，我按文章操作释放内存了，仍然是报这个错误。另外一个版本的操作系统在同样的环境下是正常的，现在只能怀疑是国产操作系统的问题了。。。
