### ISSUE TITLE
BUG:  miss mountPath from build clusterfile

### ISSUE THREAD

**Issue by cuisongliu** [labring/sealos#2014]
### Sealos Version

7045a3b

### How to reproduce the bug?

![img_v2_196a9b9a-52e3-402b-9e49-425c987a22dg](https://user-images.githubusercontent.com/4150905/199472674-ae6aad5b-d7cb-4b44-94b5-1f0df931f349.jpg)

It may be necessary to put the data in a fixed directory to prevent it from being automatically cleared by buildah.

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by fanux** [comment]
https://github.com/labring/sealos/pull/2048
