### ISSUE TITLE
BUG: bitnami image don't support arm64 for labring/bitnami-mongodb cluster image

### ISSUE THREAD

**Issue by cuisongliu** [labring/sealos#2036]
### Sealos Version

v4.1.3

### How to reproduce the bug?

![image](https://user-images.githubusercontent.com/7122237/199881419-f1a43bdd-f7a8-45d1-840f-89b01b58a802.png)

![image](https://user-images.githubusercontent.com/7122237/199881356-3133e3b4-9b15-47b0-82da-f44dd6379008.png)

## Reproduce it in arm64 platform

```sh
sealos run labring/bitnami-mongodb:latest
```

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by ysicing** [comment]
Wait for support: https://github.com/bitnami/charts/issues/7305

 try it with this tool: https://github.com/ZCube/bitnami-compat

**Comment by cuisongliu** [comment]
reopen

**Comment by cuisongliu** [comment]
https://github.com/mongodb/mongodb-atlas-kubernetes

**Comment by cuisongliu** [comment]
using kb
