### ISSUE TITLE
BUG: multipass script not work, caused by not create the bridge.

### ISSUE THREAD

**Issue by fanux** [labring/sealos#2042]
### Sealos Version

The main branch

### How to reproduce the bug?

sh create_vm_sealos.sh
/usr/local/bin/multipass
Creating VM...
	multipass launch --name sealos-test-master1 --cpus 2 --mem 4G --disk 100G --network br0-test
launch failed: Invalid arguments supplied
Invalid network options supplied
	multipass launch --name sealos-test-node1 --cpus 2 --mem 4G --disk 100G --network br0-test
launch failed: Invalid arguments supplied
Invalid network options supplied
ERROR: failed to create vm, please retry

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cuisongliu** [comment]
I'm developing a virtual machine for scheduling and easy testing, so that it will be much more convenient for us to test locally later.

**Comment by xiao-jay** [comment]
create a bridge first，
tutorial：https://laogen.cc/multipass-bridge-network-on-linux/

**Comment by xiao-jay** [comment]
If you don't care about the network, you can remove the bridge，remove `--network br0-test` in shell

**Comment by fanux** [comment]
@xiao-jay seems you can create this bridge in your script if not exist.
