### ISSUE TITLE
BUG: sealos cloud could not resolve dns host, run terminal in user namespace

### ISSUE THREAD

**Issue by fanux** [labring/sealos#2056]
### Sealos Version

The main branch

### How to reproduce the bug?

```
root@fprgswxb:~# kubectl get svc
NAME                TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)    AGE
my-first-demo-svc   ClusterIP   10.96.1.110   <none>        8080/TCP   4s
root@fprgswxb:~# curl 10.96.1.110:8080
<h1>Hello world! <h1>
root@fprgswxb:~# curl my-first-demo-svc:8080
curl: (6) Could not resolve host: my-first-demo-svc
root@fprgswxb:~# cat /etc/resolv.conf 
```

**Comment by fanux** [comment]
Check the host /etc/resolv.conf 

Only set `nameserver 8.8.8.8` then restart coreDNS.

**Comment by zzjin** [comment]
Currently it is by desgin to fix ingress class annotation witch we put termnial pod all under `terminal-app` nsmespace, will move to user's namespace when ingress changed is done.
