### ISSUE TITLE
User Login Bug

### ISSUE THREAD

**Issue by cdjianghan** [labring/sealos#2058]
### Sealos Version

lastest

### How to reproduce the bug?

When I logout and login , I am not in the same namesapce , user state lost.

**Comment by zzjin** [comment]
Cannot reproduce at my all accounts.
Please provide more detailed informations.

**Comment by cdjianghan** [comment]
![image](https://user-images.githubusercontent.com/52602064/200217242-af392faf-1ade-45ff-acbc-aa41dabb86c7.png)
the first time when I login ,I'm in this namespace
![image](https://user-images.githubusercontent.com/52602064/200217317-1eb0784c-42ea-4974-b798-eeeb46d4161d.png)
after logout and relogin ,namespace different

**Comment by zzjin** [comment]
#2033 Resolved, needs cloud update.

**Comment by Abingcbc** [comment]
Fixed
