### ISSUE TITLE
Feature: Support configuration file custom vip

### ISSUE THREAD

**Issue by rechardwang** [labring/sealos#2059]
### Detailed description of the question.

RT, 我想在安装时就指定好VIP。。。但是我看官方网站并没有找到对应的设置，求教

**Comment by willzhang** [comment]
https://github.com/labring/sealos/issues/1798

**Comment by willzhang** [comment]
[breeze](https://github.com/wise2c-devops/breeze) 的双负载均衡器实现：

![image](https://user-images.githubusercontent.com/33590311/200263787-c0eda20b-7180-4071-8924-e9dce7370666.png)

- sealos + ipvs for local lb ?
- sealos + kubevip for outside lb ?

**Comment by rechardwang** [comment]
@fanux 求解

**Comment by fanux** [comment]
我花了九牛二虎之力 把haproxy+keepalived 这俩去掉了才让 sealos 这么精简和轻量，你这是想倒退嘛哈哈。 为啥你要自定义 VIP  理论上不需要你关心这个。 支持这个参数的功能比较简单，可以暴露出来。

**Comment by fanux** [comment]
@willzhang sealos 没必要支持除 lvscare 以外的任何负载均衡器，lvscare 就是为 sealos 量身打造的最合适的负载均衡，功能不多不少，轻量又好用，给我一个换的理由～

**Comment by willzhang** [comment]
> @willzhang sealos 没必要支持除 lvscare 以外的任何负载均衡器，lvscare 就是为 sealos 量身打造的最合适的负载均衡，功能不多不少，轻量又好用，给我一个换的理由～

这些场景对接没有vip会存在单点问题，虽然这些场景我都没用过，哈哈
场景1：比如客户自己在集群外开发了一个管理平台，能够对接k8s apiserver, 获取集群监控信息，下发业务配置。
场景2： jenkins 、 gitlab部署在集群外，往集群部署业务
场景3： kubesphere、 rancher纳管多个sealos集群

**Comment by cuisongliu** [comment]
> > @willzhang sealos 没必要支持除 lvscare 以外的任何负载均衡器，lvscare 就是为 sealos 量身打造的最合适的负载均衡，功能不多不少，轻量又好用，给我一个换的理由～
> 
> 这些场景对接没有vip会存在单点问题，还要做域名解析，虽然这些场景我都没用过，哈哈 场景1：比如客户自己在集群外开发了一个管理平台，能够对接k8s apiserver, 获取集群监控信息，下发业务配置。 场景2： jenkins 、 gitlab部署在集群外，往集群部署业务 场景3： kubesphere、 rancher纳管多个sealos集群

你的这个场景适合用我另外一个项目 endpoint-operator ，专门处理集群外部服务的。https://github.com/labring/endpoints-operator

**Comment by willzhang** [comment]
https://github.com/labring/sealos/issues/2106

![image](https://user-images.githubusercontent.com/33590311/202364975-763f1b94-1d92-4132-a297-c31b70b3e597.png)

**Comment by fanux** [comment]
支持 vip 配置透出是比较简单的，可以暴露出来 sealos run --env VIP=x.x.x.x kubernetes:v1.25.4

**Comment by willzhang** [comment]
1、支持自定义域名，不然多集群管理平台不太好对接和区分每个集群
apiserver.cluster01.local
apiserver.cluster02.local
apiserver.cluster03.local

2、或者支持透出ip或vip
