### ISSUE TITLE
BUG:  sealos gen unknown kubernetes version

### ISSUE THREAD

**Issue by cuisongliu** [labring/sealos#2069]
### Sealos Version

v4.1.4-rc1

### How to reproduce the bug?

sealos gen labring/kubernetes:v1.24.0 labring/helm:v3.8.2 labring/calico:v3.22.1 --masters 192.168.64.77 --nodes 192.168.64.78
2022-11-08T22:17:08 error error version format  1.25.0

### What is the expected behavior?

Are we adding a version number to this command parameter, because this command does not actually pull the image, making it impossible to get the real image name?
sealos gen labring/kubernetes:v1.24.0 labring/helm:v3.8.2 labring/calico:v3.22.1 --masters 192.168.64.77 --nodes 192.168.64.78 --version v1.24.0

Or shall we also pull the image at the gen cmd?

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by fanux** [comment]
The Clusterfile must have version filed? I think don't need to generate version in Clusterfile, because when apply sealos will get this version from sealos image.

**Comment by cuisongliu** [comment]
> The Clusterfile must have version filed? I think don't need to generate version in Clusterfile, because when apply sealos will get this version from sealos image.

The main reason is that kubeadm needs this configuration, but clusterfile does not need it.
