### ISSUE TITLE
BUG: Failed to compile sealos at centos

### ISSUE THREAD

**Issue by 3293172751** [labring/sealos#2071]
### Sealos Version

latest

### How to reproduce the bug?

**My configuration：**
![$Y8OK@RCC@L5$NW NJ C( P](https://user-images.githubusercontent.com/86140903/200767766-38a9b997-c360-4a3e-b6c5-247bc4e662b4.png)

**I want to try to install `sealos` on `centos`**

**centos7:**
Linux VM-4-6-centos 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

>  **I think it's the version**  ⚡

### What is the expected behavior?

**The command I use：**

```bash
wget  https://github.com/labring/sealos/releases/download/v4.1.3/sealos_4.1.3_linux_amd64.tar.gz  && \
tar -zxvf sealos_4.1.3_linux_amd64.tar.gz sealos &&  chmod +x sealos && mv sealos /usr/bin 
```

```bash
yum -y install gcc-c++-x86_64-linux-gnu
```

```bash
make build
```

** Version information: **

### What do you see instead?

```bash
[root@iZbp1evo5cnwagauz3w188Z sealos]# make build
===========> Building binary lvscare v4.1.4.rc1 for linux_amd64
===========> Building binary sealctl v4.1.4.rc1 for linux_amd64
===========> Building binary sealos v4.1.4.rc1 for linux_amd64
# runtime/cgo
_cgo_export.c:3:20: fatal error: stdlib.h: No such file or directory
 #include <stdlib.h>
                    ^
compilation terminated.
make[1]: *** [go.build.linux_amd64.sealos] Error 2
make: *** [build] Error 2

```

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by fanux** [comment]
@3293172751 Using ubuntu instead centos~

**Comment by zzjin** [comment]
Centos is using `go env`s gcc linker: `CC=gcc`. 
But currently, our `make build` scripts is using a hardcoded linker called `CC=x86_64-linux-gnu-gcc` under make scripts.

Need some update to support both centos+other linux release.
@SignorMercurio

**Comment by 3293172751** [comment]
[https://github.com/labring/sealos/blob/main/scripts/make-rules/golang.mk#L64](https://github.com/labring/sealos/blob/main/scripts/make-rules/golang.mk#L64
)

#### solve
```bash
cd /sealos/sealos/scripts/make-rules && vim golang.mk
```
**alter L64:**
`CC=x86_64-linux-gnu-gcc; \`   --> `GCC=x86_64-linux-gnu-gcc; \`

**end-yep**
