### ISSUE TITLE
BUG: k8s 1.25 coreDNS error

### ISSUE THREAD

**Issue by xiao-jay** [labring/sealos#2074]
### Sealos Version

v:4.1.4-rc1

### How to reproduce the bug?

```
$ sealos run labring/kubernetes:v1.25.0 labring/helm:v3.8.2 labring/calico:v3.24.1 \
     --masters 192.168.64.2,192.168.64.22,192.168.64.20 \
     --nodes 192.168.64.21,192.168.64.19 -p [your-ssh-passwd]
```
```
kubectl get pod -A
kube-system        coredns-565d847f94-5b2wt                   0/1     CrashLoopBackOff   2271 (4m1s ago)   8d
kube-system        coredns-565d847f94-jtw9f                   0/1     CrashLoopBackOff   2271 (88s ago)    8d
```

```
root@laf-test-master1:/home/ubuntu# kubectl logs coredns-565d847f94-5b2wt  -n kube-system
.:53
[INFO] plugin/reload: Running configuration SHA512 = 591cf328cccc12bc490481273e738df59329c62c0b729d94e8b61db9961c2fa5f046dd37f1cf888b953814040d180f52594972691cd6ff41be96639138a43908
CoreDNS-1.9.3
linux/amd64, go1.18.2, 45b0a11
[FATAL] plugin/loop: Loop (127.0.0.1:58433 -> :53) detected for zone ".", see https://coredns.io/plugins/loop#troubleshooting. Query: "HINFO 8407610317041155683.2379619262876814132."
```

k8s version 1.24 won't have this problem
```
sealos run labring/kubernetes:v1.24.0 labring/helm:v3.8.2 labring/calico:v3.22.1
```

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by fanux** [comment]
```
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . 8.8.8.8
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-05T12:28:44Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "309801"
  uid: a5e1d96b-d0d9-4fa0-95c6-1d49be7254d5
```
kubectl edit configmap coredns -n kube-system

**Comment by xiao-jay** [comment]
我发现sealos run labring/kubernetes:v1.25.0 labring/helm:v3.8.2 labring/calico:v3.24.1 \
sealos 4.1.4-rc1 coreDNS有问题，sealos 4.1.3没问题，应该是最新releasesealos哪边有问题

**Comment by cuisongliu** [comment]
> 我发现sealos run labring/kubernetes:v1.25.0 labring/helm:v3.8.2 labring/calico:v3.24.1 
> sealos 4.1.4-rc1 coreDNS有问题，sealos 4.1.3没问题，应该是最新release sealos哪边有问题

是的 应该是runtime的kubeadm模块有点问题。

**Comment by cuisongliu** [comment]
https://github.com/labring/sealos/issues/1668

**Comment by licocon** [comment]
我遇到过，等我找找。

**Comment by licocon** [comment]
kubectl edit cm coredns -n kube-system

apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
          lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf {
          max_concurrent 1000
        }
        cache 30
       # loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"Corefile":".:53 {\n    errors\n    health {\n      lameduck 5s\n    }\n    ready\n    kubernetes cluster.local in-addr.arpa ip6.arpa {\n      fallthrough in-addr.arpa ip6.arpa\n    }\n    prometheus :9153\n    forward . /etc/resolv.conf {\n      max_concurrent 1000\n    }\n    cache 30\n    loop\n    reload\n    loadbalance\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"coredns","namespace":"kube-system"}}
  creationTimestamp: "2022-07-18T09:21:11Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "40947"
  uid: 4a9d98d3-4632-4001-997a-7c433c56db02


把loop删掉，然后在吧kubedns  pod删掉。让他自己拉起来

**Comment by cuisongliu** [comment]
```
ok, err := isServiceActive("systemd-resolved")
	if err != nil {
		klog.Warningf("cannot determine if systemd-resolved is active: %v", err)
	}
	if ok {
		if kc.config.ResolverConfig == nil {
			kc.config.ResolverConfig = utilpointer.String(kubeletSystemdResolverConfig)
		} else {
			if *kc.config.ResolverConfig != kubeletSystemdResolverConfig {
				warnDefaultComponentConfigValue(kind, "resolvConf", kubeletSystemdResolverConfig, *kc.config.ResolverConfig)
			}
		}
	}
```
