### ISSUE TITLE
sealos push 时出错

### ISSUE THREAD

**Issue by DeathInTheAir** [labring/sealos#2088]
### Detailed description of the question.

在4.1.3 和4.1.4-rc1都遇到。

error pushing image "xxx.com/ops/prometheus-custom:2.39.1" to "xxx.com/ops/prometheus-custom:2.39.1": writing manifest: uploading manifest 2.39.1 to xxx.com/ops/prometheus-custom: received unexpected HTTP status: 500 Internal Server Error

镜像仓库是harbor，harbor日志提示：
36.254.13.91 - - [11/Nov/2022:07:34:46 +0000] "PATCH /v2/ops/prometheus-custom/blobs/uploads/627573f2-9c37-48fd-af63-3aa2e2cc9e51?_state=uO0SHw-xqKz6gMBw64QFRPwqynaJDMbfll7d49ZTq-l7Ik5hbWUiOiJvcHMvcHJvbWV0aGV1cy1jdXN0b20iLCJVVUlEIjoiNjI3NTczZjItOWMzNy00OGZkLWFmNjMtM2FhMmUyY2M5ZTUxIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDIyLTExLTExVDA3OjM0OjQxLjU5NjAwMjc3N1oifQ%3D%3D HTTP/1.1" 202 0 "" "Buildah/1.26.1"
36.254.13.91 - - [11/Nov/2022:07:34:51 +0000] "PUT /v2/ops/prometheus-custom/blobs/uploads/627573f2-9c37-48fd-af63-3aa2e2cc9e51?_state=mXhii3dkWYoXfwYIwQtGW0urbpS05hJ71Y83IQ4IW2B7Ik5hbWUiOiJvcHMvcHJvbWV0aGV1cy1jdXN0b20iLCJVVUlEIjoiNjI3NTczZjItOWMzNy00OGZkLWFmNjMtM2FhMmUyY2M5ZTUxIiwiT2Zmc2V0Ijo0NTAwNDk3ODYsIlN0YXJ0ZWRBdCI6IjIwMjItMTEtMTFUMDc6MzQ6NDFaIn0%3D&digest=sha256%3A53e2b4821760806bc8939139c837a32bb0427b7111e41c86cefaf33b6b853ad4 HTTP/1.1" 201 0 "" "Buildah/1.26.1"
time="2022-11-11T07:34:52.038619805Z" level=error msg="response completed with error" auth.user.name=admin err.code="blob unknown" err.detail=sha256:a071571bb21a2d7cb9053059811c6315de0097f0500edee46c742cae6290542f err.message="blob unknown to registry" go.version=go1.12.12 http.request.host=bc-registry-pre.rootcloudapp.com http.request.id=9d0bde88-a35e-431d-91dd-837e3b27ed32 http.request.method=HEAD http.request.remoteaddr=127.0.0.1 http.request.uri="/v2/ops/prometheus-custom/blobs/sha256:a071571bb21a2d7cb9053059811c6315de0097f0500edee46c742cae6290542f" http.request.useragent="Buildah/1.26.1" http.response.contenttype="application/json; charset=utf-8" http.response.duration=3.83378ms http.response.status=404 http.response.written=157 vars.digest="sha256:a071571bb21a2d7cb9053059811c6315de0097f0500edee46c742cae6290542f" vars.name="ops/prometheus-custom" 
36.254.13.91 - - [11/Nov/2022:07:34:52 +0000] "HEAD /v2/ops/prometheus-custom/blobs/sha256:a071571bb21a2d7cb9053059811c6315de0097f0500edee46c742cae6290542f HTTP/1.1" 404 157 "" "Buildah/1.26.1"
36.254.13.91 - - [11/Nov/2022:07:34:52 +0000] "POST /v2/ops/prometheus-custom/blobs/uploads/ HTTP/1.1" 202 0 "" "Buildah/1.26.1"
36.254.13.91 - - [11/Nov/2022:07:34:52 +0000] "PATCH /v2/ops/prometheus-custom/blobs/uploads/3652c0ca-cd6f-4ea0-ad15-9a2c6dff3869?_state=lM40tsQi3iMfsSaZ1_1-_zPSbjSkoKKeSrIKRTPu5HN7Ik5hbWUiOiJvcHMvcHJvbWV0aGV1cy1jdXN0b20iLCJVVUlEIjoiMzY1MmMwY2EtY2Q2Zi00ZWEwLWFkMTUtOWEyYzZkZmYzODY5IiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDIyLTExLTExVDA3OjM0OjUyLjA1MTU1NDgzOFoifQ%3D%3D HTTP/1.1" 202 0 "" "Buildah/1.26.1"
36.254.13.91 - - [11/Nov/2022:07:34:52 +0000] "PUT /v2/ops/prometheus-custom/blobs/uploads/3652c0ca-cd6f-4ea0-ad15-9a2c6dff3869?_state=V-KhFPdew7QJeSGh0TPPJ-kpXfV3Iw0nLe2aJsJzv3x7Ik5hbWUiOiJvcHMvcHJvbWV0aGV1cy1jdXN0b20iLCJVVUlEIjoiMzY1MmMwY2EtY2Q2Zi00ZWEwLWFkMTUtOWEyYzZkZmYzODY5IiwiT2Zmc2V0IjoxMDcxLCJTdGFydGVkQXQiOiIyMDIyLTExLTExVDA3OjM0OjUyWiJ9&digest=sha256%3Aa071571bb21a2d7cb9053059811c6315de0097f0500edee46c742cae6290542f HTTP/1.1" 201 0 "" "Buildah/1.26.1"
10.67.20.6 - - [11/Nov/2022:07:34:53 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.19"

**Comment by fanux** [comment]
How to reproduce.
