### ISSUE TITLE
sealos build 如果想要应用镜像包含依赖镜像，是不是必须"copy registry registry"

### ISSUE THREAD

**Issue by DeathInTheAir** [labring/sealos#2089]
### Detailed description of the question.

1、sealos build 如果想要应用镜像包含依赖镜像，是不是必须"copy registry registry"
2、如果一定需要显示是指copy registry，那么是如果保障构建多个应用镜像能重复利用镜像层的？否则每个应用镜像都需要重新下载，或者包含全部的registry 数据，而非本身所依赖的

**Comment by willzhang** [comment]
1、是的，这是核心功能
2、build阶段，每个应用镜像都是独立打包的，只能直接下载到自己目录下，没办法共享层，pull阶段，是统一合并到registry目录，可以共享层
