### ISSUE TITLE
华为云安装k8s集群失败

### ISSUE THREAD

**Issue by 37705109** [labring/sealos#2098]
### Sealos Version

v4.1.3

### How to reproduce the bug?

sealos run docker.io/labring/kubernetes-docker:v1.23.13 labring/helm:v3.8.2 labring/calico:v3.24.1 \ --masters 192.168.0.22 --nodes 192.168.0.97,192.168.0.191 -p *****  
![image](https://user-images.githubusercontent.com/25220287/201583131-83eed2d6-e269-4778-a3c0-ff172b3dc520.png)

error Applied to cluster error: invalid reference format

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by fanux** [comment]
<img width="844" alt="image" src="https://user-images.githubusercontent.com/8912557/201837525-81b02fb8-69b4-4e21-87f5-3f073a623ddc.png">
没huan换行转意了？

**Comment by fanux** [comment]
问题如果还存在请重新打开
