### ISSUE TITLE
BUG: 通过LVS访问apiserver 部分节点不通

### ISSUE THREAD

**Issue by songdi676** [labring/sealos#2108]
### Sealos Version

v4.0.0

### How to reproduce the bug?

- 集群某台主机创建pod失败
`Normal  Scheduled  lly assigned moa-nsmtapp-sol/a19xtf8mm-80a-containeri-moamanage-75f9c4cd87-s6jsc to x86-test-nsrqy95  Wed Nov 16 15:41:17 +0800 CST 2022
Warning  FailedCreatePodSandBox  t "https://apiserver.cluster.local:6443/version?timeout=32s": dial tcp 10.103.97.2:6443: i/o timeout  Wed Nov 16 15:47:34 +0800 CST 2022
`
- 该主机lvs规则如下
`shell
[paasopt@x86-test-nsrqy95 ~]$ sudo ipvsadm -Ln -t 10.103.97.2:6443
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.103.97.2:6443 rr
  -> 10.45.117.25:6443            Masq    1      2          0         
  -> 10.45.117.26:6443            Masq    1      0          0         
  -> 10.45.117.27:6443            Masq    1      1          0         
[paasopt@x86-test-nsrqy95 ~]$`
![M% 7YU3R)Q`}L~OAJM2(EH8](https://user-images.githubusercontent.com/15158819/202331772-204794cb-d3b0-4076-9bb3-635d737ad325.png)

- 通过CURL访问，50%几率能调通，失败现象为调用接口阻塞超时；直接调用3台主机的apiserver都是没有问题的
![VG2$CVLVL%T9)JFS`@7SNN](https://user-images.githubusercontent.com/15158819/202331463-6b5422f3-d066-409f-abd2-ab2ddeebada2.png)

### Operating environment

```markdown
- Sealos 4.0.0:
- Docker version:
- Kubernetes 1.24.2:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by zhangguanzhang** [comment]
ipset list

**Comment by songdi676** [comment]
> ```
> sudo ipset list
> ```

`[paasopt@x86-test-nsrqy95 ~]$ sudo ipset list
Name: KUBE-CLUSTER-IP
Type: hash:ip,port
Revision: 5
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 8696
References: 2
Number of entries: 143
Members:
10.68.135.246,tcp:39080
10.68.101.223,tcp:35621
10.68.160.21,tcp:59000
10.68.67.1,tcp:38888
10.68.117.192,tcp:38081
10.68.101.113,tcp:38888
10.68.175.18,tcp:39200
10.68.44.142,tcp:58890
10.68.240.41,tcp:39200
10.68.144.154,tcp:38090
10.68.50.158,tcp:48084
10.68.176.67,tcp:38080
10.68.89.181,tcp:38081
10.68.210.75,tcp:39200
10.68.164.85,tcp:8848
10.68.66.212,tcp:39080
10.68.134.107,tcp:48085
10.68.235.58,tcp:58881
10.68.53.68,tcp:39200
10.68.74.188,tcp:39200
10.68.213.49,tcp:39060
10.68.226.15,tcp:8081
10.68.14.163,tcp:39200
10.68.88.249,tcp:39204
10.68.14.72,tcp:39202
10.68.116.1,tcp:49081
10.68.212.119,tcp:3456
10.68.8.201,tcp:48180
10.68.0.10,udp:53
10.68.129.75,tcp:50002
10.68.65.87,tcp:38080
10.68.12.149,tcp:48097
10.68.162.218,tcp:9094
10.68.75.107,tcp:39202
10.68.61.58,tcp:9848
10.68.106.21,tcp:39200
10.68.242.254,tcp:39200
10.68.147.117,tcp:48080
10.68.33.120,tcp:443
10.68.111.137,tcp:39080
10.68.193.3,tcp:39200
10.68.89.47,tcp:39011
10.68.221.0,tcp:38898
10.68.0.10,tcp:53
10.68.96.198,tcp:58889
10.68.234.155,tcp:48088
10.68.255.207,tcp:39080
10.68.37.168,tcp:48098
10.68.37.103,tcp:39217
10.68.52.155,tcp:48848
10.68.11.1,tcp:39082
10.68.108.74,tcp:9100
10.68.218.105,tcp:60000
10.68.212.220,tcp:50001
10.68.22.81,tcp:39200
10.68.129.29,tcp:16443
10.68.81.122,tcp:48103
10.68.163.222,tcp:39200
10.68.61.58,tcp:9849
10.68.79.174,tcp:38081
10.68.214.65,tcp:38081
10.68.28.26,tcp:48090
10.68.185.140,tcp:39084
10.68.230.100,tcp:38081
10.68.66.156,tcp:38080
10.68.225.58,tcp:16443
10.68.102.20,tcp:48092
10.68.12.63,tcp:38899
10.68.12.28,tcp:39080
10.68.9.43,tcp:39201
10.68.104.35,tcp:39200
10.68.241.54,tcp:30005
10.68.130.190,tcp:39200
10.68.242.252,tcp:39221
10.68.228.144,tcp:39221
10.68.124.119,tcp:39200
10.68.95.29,tcp:38080
10.68.16.110,tcp:16443
10.68.88.203,tcp:39221
10.68.114.111,tcp:39011
10.68.40.131,tcp:30000
10.68.120.248,tcp:39200
10.68.0.10,tcp:9153
10.68.226.15,tcp:8080
10.68.30.38,tcp:30004
10.68.209.146,tcp:39200
10.68.49.193,tcp:39200
10.68.151.220,tcp:30001
10.68.244.166,tcp:39200
10.68.155.184,tcp:38081
10.68.140.211,tcp:39200
10.68.89.47,tcp:39200
10.68.134.188,tcp:38888
10.68.156.86,tcp:38090
10.68.218.158,tcp:30000
10.68.7.104,tcp:39083
10.68.217.188,tcp:39080
10.68.26.119,tcp:38080
10.68.40.151,tcp:38081
10.68.232.135,tcp:39201
10.68.246.208,tcp:39200
10.68.62.133,tcp:48099
10.68.12.229,tcp:30003
10.68.242.127,tcp:48091
10.68.127.211,tcp:48086
10.68.36.158,tcp:39200
10.68.240.236,tcp:39200
10.68.48.145,tcp:35621
10.68.206.66,tcp:38081
10.68.10.245,tcp:48091
10.68.244.62,tcp:16443
10.68.58.234,tcp:38080
10.68.231.26,tcp:39200
10.68.34.208,tcp:38081
10.68.115.38,tcp:38081
10.68.223.132,tcp:30005
10.68.226.208,tcp:30005
10.68.217.34,tcp:48088
10.68.80.241,tcp:39200
10.68.147.8,tcp:49900
10.68.187.183,tcp:39217
10.68.200.248,tcp:9100
10.68.45.88,tcp:38081
10.68.164.85,tcp:9848
10.68.52.155,tcp:49848
10.68.61.58,tcp:8848
10.68.73.31,tcp:48083
10.68.0.1,tcp:443
10.68.225.2,tcp:48087
10.68.250.246,tcp:39200
10.68.55.100,tcp:58888
10.68.88.116,tcp:39080
10.68.113.182,tcp:5473
10.68.101.17,tcp:39200
10.68.192.215,tcp:59001
10.68.153.74,tcp:30000
10.68.32.50,tcp:39200
10.68.205.43,tcp:30002
10.68.139.28,tcp:39077
10.68.169.252,tcp:38081
10.68.236.104,tcp:39200
10.68.199.86,tcp:48080
10.68.61.58,tcp:7848

Name: KUBE-EXTERNAL-IP-LOCAL
Type: hash:ip,port
Revision: 5
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 120
References: 0
Number of entries: 0
Members:

Name: KUBE-LOAD-BALANCER-SOURCE-CIDR
Type: hash:ip,port,net
Revision: 7
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 384
References: 0
Number of entries: 0
Members:

Name: KUBE-NODE-PORT-UDP
Type: bitmap:port
Revision: 3
Header: range 0-65535
Size in memory: 8300
References: 0
Number of entries: 0
Members:

Name: KUBE-NODE-PORT-SCTP-HASH
Type: hash:ip,port
Revision: 5
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 120
References: 0
Number of entries: 0
Members:

Name: KUBE-NODE-PORT-LOCAL-SCTP-HASH
Type: hash:ip,port
Revision: 5
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 120
References: 0
Number of entries: 0
Members:

Name: KUBE-HEALTH-CHECK-NODE-PORT
Type: bitmap:port
Revision: 3
Header: range 0-65535
Size in memory: 8300
References: 1
Number of entries: 0
Members:

Name: KUBE-LOOP-BACK
Type: hash:ip,port,ip
Revision: 5
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 448
References: 1
Number of entries: 4
Members:
10.45.103.35,tcp:9100,10.45.103.35
172.20.150.65,tcp:9100,172.20.150.65
172.20.150.99,tcp:9080,172.20.150.99
172.20.150.123,tcp:8080,172.20.150.123

Name: KUBE-LOAD-BALANCER-FW
Type: hash:ip,port
Revision: 5
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 120
References: 0
Number of entries: 0
Members:

Name: KUBE-NODE-PORT-TCP
Type: bitmap:port
Revision: 3
Header: range 0-65535
Size in memory: 8300
References: 1
Number of entries: 10
Members:
20003
20004
20006
20007
22001
27048
28048
29100
29256
55828

Name: KUBE-NODE-PORT-LOCAL-TCP
Type: bitmap:port
Revision: 3
Header: range 0-65535
Size in memory: 8300
References: 0
Number of entries: 0
Members:

Name: KUBE-LOAD-BALANCER
Type: hash:ip,port
Revision: 5
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 120
References: 0
Number of entries: 0
Members:

Name: KUBE-LOAD-BALANCER-SOURCE-IP
Type: hash:ip,port,ip
Revision: 5
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 128
References: 0
Number of entries: 0
Members:

Name: KUBE-NODE-PORT-LOCAL-UDP
Type: bitmap:port
Revision: 3
Header: range 0-65535
Size in memory: 8300
References: 0
Number of entries: 0
Members:

Name: KUBE-LOAD-BALANCER-LOCAL
Type: hash:ip,port
Revision: 5
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 120
References: 0
Number of entries: 0
Members:

Name: KUBE-EXTERNAL-IP
Type: hash:ip,port
Revision: 5
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 120
References: 0
Number of entries: 0
Members:

Name: KUBE-6-LOAD-BALANCER
Type: hash:ip,port
Revision: 5
Header: family inet6 hashsize 1024 maxelem 65536
Size in memory: 136
References: 0
Number of entries: 0
Members:

Name: KUBE-6-LOAD-BALANCER-SOURCE-CID
Type: hash:ip,port,net
Revision: 7
Header: family inet6 hashsize 1024 maxelem 65536
Size in memory: 1176
References: 0
Number of entries: 0
Members:

Name: KUBE-6-NODE-PORT-LOCAL-TCP
Type: bitmap:port
Revision: 3
Header: range 0-65535
Size in memory: 8300
References: 0
Number of entries: 0
Members:

Name: KUBE-6-NODE-PORT-UDP
Type: bitmap:port
Revision: 3
Header: range 0-65535
Size in memory: 8300
References: 0
Number of entries: 0
Members:

Name: KUBE-6-EXTERNAL-IP
Type: hash:ip,port
Revision: 5
Header: family inet6 hashsize 1024 maxelem 65536
Size in memory: 136
References: 0
Number of entries: 0
Members:

Name: KUBE-6-NODE-PORT-TCP
Type: bitmap:port
Revision: 3
Header: range 0-65535
Size in memory: 8300
References: 0
Number of entries: 0
Members:

Name: KUBE-6-NODE-PORT-SCTP-HASH
Type: hash:ip,port
Revision: 5
Header: family inet6 hashsize 1024 maxelem 65536
Size in memory: 136
References: 0
Number of entries: 0
Members:

Name: KUBE-6-LOAD-BALANCER-LOCAL
Type: hash:ip,port
Revision: 5
Header: family inet6 hashsize 1024 maxelem 65536
Size in memory: 136
References: 0
Number of entries: 0
Members:

Name: KUBE-6-NODE-PORT-LOCAL-SCTP-HAS
Type: hash:ip,port
Revision: 5
Header: family inet6 hashsize 1024 maxelem 65536
Size in memory: 136
References: 0
Number of entries: 0
Members:

Name: KUBE-6-LOOP-BACK
Type: hash:ip,port,ip
Revision: 5
Header: family inet6 hashsize 1024 maxelem 65536
Size in memory: 152
References: 0
Number of entries: 0
Members:

Name: KUBE-6-EXTERNAL-IP-LOCAL
Type: hash:ip,port
Revision: 5
Header: family inet6 hashsize 1024 maxelem 65536
Size in memory: 136
References: 0
Number of entries: 0
Members:

Name: KUBE-6-LOAD-BALANCER-FW
Type: hash:ip,port
Revision: 5
Header: family inet6 hashsize 1024 maxelem 65536
Size in memory: 136
References: 0
Number of entries: 0
Members:

Name: KUBE-6-LOAD-BALANCER-SOURCE-IP
Type: hash:ip,port,ip
Revision: 5
Header: family inet6 hashsize 1024 maxelem 65536
Size in memory: 152
References: 0
Number of entries: 0
Members:

Name: KUBE-6-NODE-PORT-LOCAL-UDP
Type: bitmap:port
Revision: 3
Header: range 0-65535
Size in memory: 8300
References: 0
Number of entries: 0
Members:

Name: KUBE-6-HEALTH-CHECK-NODE-PORT
Type: bitmap:port
Revision: 3
Header: range 0-65535
Size in memory: 8300
References: 1
Number of entries: 0
Members:

Name: KUBE-6-CLUSTER-IP
Type: hash:ip,port
Revision: 5
Header: family inet6 hashsize 1024 maxelem 65536
Size in memory: 136
References: 0
Number of entries: 0
Members:

Name: cali40masq-ipam-pools
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 1048576
Size in memory: 440
References: 1
Number of entries: 1
Members:
172.20.0.0/16

Name: cali40this-host
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 1048576
Size in memory: 312
References: 3
Number of entries: 4
Members:
172.20.150.64
10.45.103.35
127.0.0.1
127.0.0.0

Name: cali40all-hosts-net
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 1048576
Size in memory: 5688
References: 2
Number of entries: 85
Members:
10.47.213.25
10.45.117.35
10.45.103.14
10.45.103.31
10.45.103.49
10.45.117.34
10.45.103.16
10.45.117.171
10.47.213.19
10.47.213.23
10.45.103.54
10.45.103.46
10.45.117.173
10.45.103.13
10.47.213.28
10.45.103.18
10.45.117.172
10.47.213.2
10.45.103.41
10.45.103.58
10.47.213.21
10.47.213.10
10.45.103.52
10.47.213.16
10.45.117.33
10.45.103.19
10.45.103.23
10.47.213.27
10.45.103.12
10.47.213.13
10.45.103.22
10.47.213.1
10.47.213.6
10.47.213.4
10.47.213.26
10.45.117.170
10.45.103.11
10.45.103.44
10.45.103.35
10.45.117.36
10.45.103.53
10.45.103.57
10.45.103.56
10.47.213.12
10.47.213.14
10.45.103.17
10.45.103.26
10.47.213.30
10.47.213.3
10.45.117.26
10.45.103.25
10.45.103.48
10.45.103.60
10.45.103.36
10.45.103.37
10.47.213.9
10.45.103.34
10.45.103.51
10.45.103.50
10.45.117.236
10.47.213.7
10.47.213.20
10.45.103.43
10.47.213.15
10.47.213.8
10.45.103.32
10.47.213.29
10.45.103.40
10.45.103.39
10.45.103.47
10.47.213.17
10.45.103.33
10.47.213.18
10.45.103.55
10.47.213.22
10.47.213.5
10.45.103.38
10.47.213.24
10.45.103.59
10.45.103.42
10.45.117.27
10.45.103.15
10.45.103.45
10.45.117.25
10.47.213.11

Name: cali40all-ipam-pools
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 1048576
Size in memory: 440
References: 1
Number of entries: 1
Members:
172.20.0.0/16`

10.45.117.25,10.45.117.26,10.45.117.27 为3台master

**Comment by songdi676** [comment]
> 看下正常节点上有没有
> 
> ```
> ipset list | grep 97.2
> ```

![~PB5CXSYC UMFIW6HF9E3Q3](https://user-images.githubusercontent.com/15158819/202339736-25ec3fc7-7adb-4116-ac4e-ef48c58fd7c1.png)
以上是正常节点信息，正常节点和异常一点ipset list | grep 97.2 都没有该IP信息

**Comment by fanux** [comment]
Check the lvscare pod log.

**Comment by zhangguanzhang** [comment]
部分节点不通，但是ipvsadm里有就是没做snat导致的，看看snat是iptables 单独的规则还是像kube-proxy的ipvs那样一个ipset匹配

**Comment by songdi676** [comment]
> Check the lvscare pod log.

lvscare 版本 v1.1.3-beta.2
![WOL1L_}FR3(ZB(B83}`$97](https://user-images.githubusercontent.com/15158819/202368221-bc0aa21a-ede4-4ed0-aad2-5ced49301426.png)
