### ISSUE TITLE
在阿里云两个不同账号的实例下安装的问题

### ISSUE THREAD

**Issue by dixon1983** [labring/sealos#2114]
### Sealos Version

4.1.3

### How to reproduce the bug?

阿里云服务器，两个不同账号创建的实例。云服务一般有两个ip，外网ip和内网ip，外网ip是能互相访问的，内网ip不能互相访问。但是ifconfig查看服务器网卡，实际上只有内网ip。用sealos安装的时候，masters和nodes都只能写外网ip，这样在安装的时候，会报拉取不到镜像
![Uploading QQ图片20221117133325.jpg…]()

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by fanux** [comment]
不支持外网IP 目前
