### ISSUE TITLE
Question: 使用sealos 命令如何每个Node都安装一个ingress

### ISSUE THREAD

**Issue by liuziyuan** [labring/sealos#2127]
### Detailed description of the question.

使用sealos命令ingress后，发现他只在一个Node下产生了实例。我希望每个Node都会有一个ingress实例。请问应该如何进行配置与安装。

**Comment by xiao-jay** [comment]
你得修改源yaml文件，https://www.cnblogs.com/fawaikuangtu123/p/11031012.html，这是一个example， 你可以找找有没有daemonset版的ingress
