### ISSUE TITLE
Question: 如何卸载已经安装好的组件(Ingress)

### ISSUE THREAD

**Issue by liuziyuan** [labring/sealos#2129]
### Detailed description of the question.

在安装好Ingress之后，我想delete了这个实例，但是没有找到ingress的Yaml文件所在。
是否可以提供一下sealos run安装组件时，yaml所在的路径。
又或者有其他命令可以直接删除

**Comment by licocon** [comment]
k8s能直接删嘛？

**Comment by fanux** [comment]
cat .sealos/default/Clusterfile  Status 里面有个 merge 目录能找到。 后面我们有 actions 的设计可以删除各种应用。
