### ISSUE TITLE
问下，主节点和子节点不同架构的cpu.如何部署k8s集群

### ISSUE THREAD

**Issue by licocon** [labring/sealos#2132]
### Detailed description of the question.

主节点：甲骨文arm机器
子节点:甲骨文amd机器。
白嫖来的。安装时发现子节点的containerd报错。
由于实在arm机器上执行的命令。猜测是不是子节点也装了arm的containred了。
如果可以解决，请帮助我。如果不行，我就放弃子节点了。

**Comment by fanux** [comment]
这块我们正在开发哈，完成了之后使用方式还是一条命令，会自动判断架构。

**Comment by licocon** [comment]
有交流群嘛？

还有哈，提一下。文档前提需求写的不全。需要关闭防火墙以及一些东西。完全重装干净的系统不太行。。。昨天装下来发现的
