### ISSUE TITLE
BUG: run labring/ingress-nginx:4.1.0 error occur

### ISSUE THREAD

**Issue by tanshilingithub** [labring/sealos#2153]
### Sealos Version

v4.1.3

### How to reproduce the bug?

wget  https://github.com/labring/sealos/releases/download/v4.1.3/sealos_4.1.3_linux_amd64.tar.gz  && \
    tar -zxvf sealos_4.1.3_linux_amd64.tar.gz sealos &&  chmod +x sealos && mv sealos /usr/bin

sealos run labring/kubernetes:v1.24.1 labring/helm:v3.8.2 labring/calico:v3.24.1 --single
kubectl taint node --all node-role.kubernetes.io/control-plane-
kubectl taint nodes --all node-role.kubernetes.io/master:NoSchedule-
sealos run labring/openebs:v1.9.0
sealos run labring/ingress-nginx:4.1.0

### What is the expected behavior?

ingress-controller running stable

### What do you see instead?

W1128 08:16:39.096276   28343 reflector.go:442] k8s.io/client-go@v0.23.5/tools/cache/reflector.go:167: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
I1128 08:17:03.218844   28343 trace.go:205] Trace[363070220]: "Reflector ListAndWatch" name:k8s.io/client-go@v0.23.5/tools/cache/reflector.go:167 (28-Nov-2022 08:16:50.026) (total time: 13100ms):
Trace[363070220]: [13.100762357s] [13.100762357s] END
Error: INSTALLATION FAILED: failed pre-install: timed out waiting for the condition
2022-11-28T08:17:55 error Applied to cluster error: exit status 1

[root@192 ~]# kubectl -n ingress-nginx logs -f --tail 300 ingress-nginx-admission-create-fq5gd
W1128 08:12:38.934183       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
{"err":"secrets \"ingress-nginx-admission\" not found","level":"info","msg":"no secret found","source":"k8s/k8s.go:229","time":"2022-11-28T08:12:39Z"}
{"level":"info","msg":"creating new secret","source":"cmd/create.go:28","time":"2022-11-28T08:12:39Z"}

### Operating environment

```markdown
- Sealos version: 4.1.3
- Docker version: containerd v1.6.2
- Kubernetes version: 1.24.1
- Operating system: centos7
- Runtime environment: containerd
- Cluster size: 1
- Additional information:
```

**Comment by tanshilingithub** [comment]
how can i uninstall it and reinstall it? how can i found the other version for it?

**Comment by fanux** [comment]
helm list -a

**Comment by tanshilingithub** [comment]
I'm sorry, I'm having a hard time verifying something right now, my environment has changed a lot,
now i use this way:
```
kubectl apply -f https://github.com/tanshilingithub/monitoring/raw/main/docs/ingress-nginx/v1.5.1/deploy.yaml
```
i need to update image registry for my local environment

**Comment by tanshilingithub** [comment]
![image](https://user-images.githubusercontent.com/114631466/204234327-19b60b43-586f-400b-bcad-cc1d63537ea7.png)
the helm list was empty

**Comment by tanshilingithub** [comment]
it just use the helm to install that?so i just to uninstall it by helm?

**Comment by fanux** [comment]
helm list -A

sealos will use actions to delete app : https://github.com/labring/sealos/blob/main/proposal/design/zh/App%20actions%20%E8%AE%BE%E8%AE%A1.md
