### ISSUE TITLE
Question: how to build a custom k8s image?

### ISSUE THREAD

**Issue by lixd** [labring/sealos#2155]
### Detailed description of the question.

how to build a custom k8s image?
i found some docs to tourist how to build app image,like calico,but don't found how to build k8s image.
is there some tourist docs?

### Some reference materials you see.

[build-example-cloudimage](https://docs.sealos.io/docs/getting-started/build-example-cloudimage)

**Comment by fanux** [comment]
1. Get the cluster rootfs, cat `.sealos/default/Clusterfile`

like: 
```
    imageName: labring/kubernetes:v1.21.14-4.1.3
...
/var/lib/containers/storage/overlay/2e622bad0b815cbedb43fb41238429010262206d9a758c3dd8d9b325417c7a74/merged
```
2. cd /var/lib/containers/storage/overlay/2e622bad0b815cbedb43fb41238429010262206d9a758c3dd8d9b325417c7a74/merged

3. modify something you want
4. sealos build -t your-kubernetes:latest .

The Kubefile is simple:
```
FROM scratch 
COPY . .
```
