### ISSUE TITLE
在用sealos 安装 k8s时，设置docker registry 私有仓库账号密码是 admin/Harbor12345 .使用 sealos add --nodes 172.18.17.240 添加节点报错

### ISSUE THREAD

**Issue by huangkaiyan10** [labring/sealos#2171]
![6GRY9E9U~CMH KG$C2)%6TN](https://user-images.githubusercontent.com/5146180/205057634-c4a53810-1912-4e64-aac4-13e0fdaa5cd1.png)

sealos add --nodes 172.18.17.240

在用sealos 安装 k8s时，设置docker registry 私有仓库账号密码是 admin/Harbor12345 .使用 sealos add --nodes 172.18.17.240 添加节点报错。

**Comment by huangkaiyan10** [comment]
sealos 4.1.3

**Comment by fanux** [comment]
How to reproduce? The install command? and show me the .sealos/default/Clusterfile

**Comment by huangkaiyan10** [comment]
sealos run --env registryPort=5000  --env registryPassword=Harbor12345 labring/kubernetes-docker:v1.19.14-4.1.3 labring/calico:v3.22.1 --masters 172.18.17.225 -p 'tct123!@#'
[Clusterfile.txt](https://github.com/labring/sealos/files/10137048/Clusterfile.txt)

**Comment by huangkaiyan10** [comment]
![image](https://user-images.githubusercontent.com/5146180/205183918-3529786c-a3e4-4f70-a762-5c579ef37648.png)

**Comment by ZChongchong** [comment]
###  After installed sealos I create cluster：
```shell
sealos run --env registryPort=5000 --env registryPassword=Harbor12345 labring/kubernetes-docker:v1.19.14-4.1.3 labring/calico:v3.22.1 --masters 192.168.26.144 -p '123456'
``` 
### success：
```shell
root@master:~# kubectl get node
NAME     STATUS     ROLES    AGE   VERSION
master   NotReady   master   32s   v1.19.14
``` 
### add the node：
```shell
sealos add --nodes 192.168.26.145
``` 
### success：
```shell
root@master:~# kubectl get node
NAME     STATUS     ROLES    AGE     VERSION
master   Ready      master   5m48s   v1.19.14
n1       NotReady   <none>   12s     v1.19.14
``` 

I repeated the experiment several times according to his configuration, and there was no problem. I think there was a problem with his related settings.
