### ISSUE TITLE
BUG:  when delete master , get apiserver config found etcd address is not sync newset config yet.

### ISSUE THREAD

**Issue by cuisongliu** [labring/sealos#2189]
### Sealos Version

7045a3b

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by fanux** [comment]
Add more details?

**Comment by cuisongliu** [comment]
when delete master , get apiserver config  found etcd address is not sync newset config yet.

**Comment by cuisongliu** [comment]
https://github.com/labring/sealos/blob/88c1746ba7b9a477afc792f8210e6b3b704db363/pkg/runtime/kubeadm.go#L380 
127.0.0.1 is better ?
