### ISSUE TITLE
华为openeuler系统安装 sealos 的 k8s 集群问题

### ISSUE THREAD

**Issue by txl7771328** [labring/sealos#2194]
### Detailed description of the question.

大家好，咱们的 sealos 安装 k8s 目前好像不支持华为 openeuler 系统，目前国内大部分企业在转型国产系统，希望各位大牛尽快适配这个系统，谢谢

**Comment by txl7771328** [comment]
![image](https://user-images.githubusercontent.com/20164763/205857363-b01f50a4-25c1-4764-ae4b-a2476272fa41.png)
an'z安装报错

**Comment by txl7771328** [comment]
重新执行后 可以了 ，加了点内存，原来内存是 4G ，是内存不足的问题？

**Comment by fanux** [comment]
像是文件没下载全
