### ISSUE TITLE
sealos Join node报错

### ISSUE THREAD

**Issue by licocon** [labring/sealos#2202]
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/36863277/206082196-80b83e92-24db-4056-8595-bfb1b9fc96bd.png">
如题，昨天初始化了集群，今天想加一台机器，报错如上。服务器密码和之前的集群密码均一致

**Comment by xiao-jay** [comment]
你master节点能够使用ssh 连接 192.167.25.97，比如`ssh root@192.167.25.87`？

**Comment by licocon** [comment]
可以的。
<img width="952" alt="image" src="https://user-images.githubusercontent.com/36863277/206111621-e3e4470a-f1af-4f1a-b2ff-83e6fc4d8499.png">

**Comment by licocon** [comment]
所有服务器的密码均一致。。。

**Comment by xiao-jay** [comment]
我发现了，你第一次输入的是192.167.25.97，然后你下面ssh连接的时候输入的是192.168.25.97

**Comment by xiao-jay** [comment]
我还顺着错误信息看了半天源码😂

**Comment by licocon** [comment]
输入97也一样。。。
<img width="2141" alt="image" src="https://user-images.githubusercontent.com/36863277/206116776-19e4bfd7-8c05-4c4e-8fdd-1c3f1052dfca.png">

**Comment by xiao-jay** [comment]
看一下`cat ~/.sealos/default/Clusterfile `中是否有ssh密码

**Comment by licocon** [comment]
<img width="992" alt="image" src="https://user-images.githubusercontent.com/36863277/206131922-1d80a8e1-439f-4032-9147-96dc2bf5b7e1.png">
有的

**Comment by licocon** [comment]
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/36863277/206338190-865cca41-a684-496e-a3e4-3384737bd137.png">
现在是4.1.3 。昨天我降级了。之前安装的[v4.1.4-rc1] ，报模板错误。我降级到4.1.3

**Comment by fengxsong** [comment]
192.167.x.x 这个段非内网的地址来的哦～

**Comment by licocon** [comment]
要把那个删掉吗哈哈
