### ISSUE TITLE
sealos metering roadmap

### ISSUE THREAD

**Issue by fanux** [labring/sealos#2224]
- [ ] Quota is not enough to clean up user resource policy
- [ ] Informal and resource metering record list

**Comment by cyberpunk-admin** [comment]
Maybe I can do something for these tasks, but how do I start? Quota not enough seems to only need to modify the spec of metering CR.

**Comment by fanux** [comment]
@cyberpunk-admin book me a meeting to introduce you：https://calendly.com/fhtjob/sealos
