### ISSUE TITLE
Enhancement: ImageHub needs use env to locale user controller‘s namespace, do not hardcoded.

### ISSUE THREAD

**Issue by zzjin** [labring/sealos#2252]
https://github.com/labring/sealos/blob/main/controllers/imagehub/api/v1/image_webhook.go#L35

Since user controller may be deploy to any system namespace, so you need up update this to read ns name from env like: --env USER_NAMESPACE=xxx

**Comment by lingdie** [comment]
done at this [pr](https://github.com/labring/sealos/pull/2253)
