### ISSUE TITLE
failed to render env template

### ISSUE THREAD

**Issue by netyang123** [labring/sealos#2263]
### Detailed description of the question.

vmware 17  debian11.5
master cpu4h memory 4g 
node cpu1h memory 2g

wget https://github.com/labring/sealos/releases/download/v4.1.3/sealos_4.1.3_linux_amd64.tar.gz \
   && tar zxvf sealos_4.1.3_linux_amd64.tar.gz sealos && chmod +x sealos && mv sealos /usr/bin

sealos run labring/kubernetes:v1.25.0 labring/helm:v3.8.2 labring/calico:v3.24.1 \
     --masters 192.168.19.111 \
     --nodes 192.168.19.112 -p root
     
 
![微信图片_20221214192417](https://user-images.githubusercontent.com/120566488/207583191-5a680139-42fa-43d9-8e4f-c429ea841ba2.png)

**Comment by cuisongliu** [comment]
The image has been updated. Pull the image again.
