### ISSUE TITLE
FATA[0000] pulling image: rpc error: code = Unknown desc = Error response from daemon: Head "http://sealos.hub:5000/v2/pause/manifests/3.6": no basic auth credentials

### ISSUE THREAD

**Issue by 37705109** [labring/sealos#2266]
### Sealos Version

v4.1.3

### How to reproduce the bug?

1.执行命令
sealos gen labring/kubernetes-docker:v1.23.15 labring/helm:v3.9.4 labring/calico:v3.22.1 --masters 172.18.9.30 --nodes 172.18.9.31 -p *** > Clusterfile 
2.部署集群
sealos apply -f Clusterfile
3.报错
![image](https://user-images.githubusercontent.com/25220287/207786753-42b7090c-135b-444a-88e4-81e3381ff611.png)

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by fanux** [comment]
https://github.com/labring/sealos/releases/tag/v4.1.4-rc3 try this version.

**Comment by cyf33** [comment]
> https://github.com/labring/sealos/releases/tag/v4.1.4-rc3 try this version.

still not working
