### ISSUE TITLE
为啥会取拉取ks8.gcr.io镜像呢，如何解决

### ISSUE THREAD

**Issue by feixia5712** [labring/sealos#2268]
### Sealos Version

v4.1.3

### How to reproduce the bug?

![image](https://user-images.githubusercontent.com/12670758/207830516-159c8df2-b0be-420e-9167-31c82ab12fd5.png)

### What is the expected behavior?

请问如何解决

### What do you see instead?

1

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:1
```

### Additional information

1

**Comment by feixia5712** [comment]
![image](https://user-images.githubusercontent.com/12670758/207830938-d80c4ef2-8d77-470d-a409-676b1a52fa23.png)

**Comment by feixia5712** [comment]
我记得第一遍执行得时候没啥问题，然后卸载，再安装，多次不知道为啥出这个问题了

**Comment by cuisongliu** [comment]
已经修复 重新拉取镜像即可
