### ISSUE TITLE
Feature: sealos status using check post

### ISSUE THREAD

**Issue by cuisongliu** [labring/sealos#2271]
### What is the problem this feature will solve?

Check the status of each service.

For example, image-shim,crictl registry, etc.

**Comment by cuisongliu** [comment]
- [ ] registry status, port is ok (5000,5001)
- [ ] cri status (docker/containerd) 
- [ ] image-cri-shim status, pull image is ok ?
- [ ] crictl images
- [ ] kubelet status
- [ ] crictl ps -a
- [ ] kubectl get pods -n kube-system

**Comment by fengxsong** [comment]
`sealos status` maybe more appropriate. 😄

**Comment by cuisongliu** [comment]
sealos check --pre  or  sealos check --post ，default is post check

**Comment by zzjin** [comment]
sealos doctor

**Comment by cuisongliu** [comment]
sealos status using post check , sealos run/apply --dry-run using pre check  ?
