### ISSUE TITLE
安装时提示PullImage from image service failed，sealos.hub:5000/pause:3.7拉起失败

### ISSUE THREAD

**Issue by Lion66666** [labring/sealos#2282]
### Sealos Version

4.1.4-rc3

### How to reproduce the bug?

使用这个命令运行失败
sealos run labring/kubernetes-docker:v1.24.1 labring/helm:v3.8.2 labring/calico:v3.24.1 --single

报下面的错误
E1219 20:07:20.171304   11469 remote_image.go:218] "PullImage from image service failed" err="rpc error: code = Unknown desc = Error response from daemon: Head \"http://sealos.hub:5000/v2/pause/manifests/3.7\": no basic auth credentials" image="sealos.hub:5000/pause:3.7"
FATA[0000] pulling image: rpc error: code = Unknown desc = Error response from daemon: Head "http://sealos.hub:5000/v2/pause/manifests/3.7": no basic auth credentials
2022-12-19T20:07:20 error Applied to cluster error: failed to init exec auth.sh failed exit status 1

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cyf33** [comment]
same problem!
sealos BuildVersion: 4.1.4-rc3-43497b9b

after run
`sealos run labring/kubernetes-docker:v1.21.14 labring/calico:v3.22.1 --masters 192.168.102.177 --nodes 192.168.101.220,192.168.101.221 --pk /root/.ssh/id_rsa` 

got
> FATA[0000] pulling image: rpc error: code = Unknown desc = Error response from daemon: Head "http://sealos.hub:5000/v2/pause/manifests/3.4.1": no basic auth credentials

**Comment by gotosre** [comment]
+1

**Comment by xiao-jay** [comment]
可以问一下你们操作系统是什么吗，然后服务器是干净的吗，有提前装什么东西吗，我使用multipass 创amd64的ubuntu虚拟机没复线问题
```
sealos run labring/kubernetes:v1.24.1 labring/helm:v3.8.2 labring/calico:v3.24.1 --masters $master_ip --nodes $node_ip
```
```
root@yyj-2282-master1:~/.sealos/default# sealos version
{"gitVersion":"4.1.4-rc3","gitCommit":"43497b9b","buildDate":"2022-12-15T15:16:03Z","goVersion":"go1.19.4","compiler":"gc","platform":"linux/amd64"}
root@yyj-2282-master1:~/.sealos/default# kubectl get nodes
NAME               STATUS   ROLES           AGE   VERSION
yyj-2282-master1   Ready    control-plane   60m   v1.24.1
yyj-2282-node1     Ready    <none>          59m   v1.24.1
```
@Lion66666

**Comment by cyf33** [comment]
> 可以问一下你们操作系统是什么吗，然后服务器是干净的吗，有提前装什么东西吗，我使用multipass 创amd64的ubuntu虚拟机没复线问题
> 
> ```
> sealos run labring/kubernetes:v1.24.1 labring/helm:v3.8.2 labring/calico:v3.24.1 --masters $master_ip --nodes $node_ip
> ```
> 
> ```
> root@yyj-2282-master1:~/.sealos/default# sealos version
> {"gitVersion":"4.1.4-rc3","gitCommit":"43497b9b","buildDate":"2022-12-15T15:16:03Z","goVersion":"go1.19.4","compiler":"gc","platform":"linux/amd64"}
> root@yyj-2282-master1:~/.sealos/default# kubectl get nodes
> NAME               STATUS   ROLES           AGE   VERSION
> yyj-2282-master1   Ready    control-plane   60m   v1.24.1
> yyj-2282-node1     Ready    <none>          59m   v1.24.1
> ```
> 
> @Lion66666

Linux version 3.10.0-957.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) )
在干净的环境试过，也在用yum装过docker但卸载掉的环境试过，都不行

**Comment by gotosre** [comment]
kubernetes-docker这个镜像有问题，但是kubernetes没有，根据报错，尝试 docker pulll sealos.hub:5000/pause:3.2，没问题，但是 安装过程中, auth.sh执行就有问题，提示无鉴权信息。

**Comment by cuisongliu** [comment]
好像是/pause:3.2 镜像版本问题

**Comment by cyf33** [comment]
还有，十月份我用sealos 4.1.3部署labring/kubernetes-docker:v1.21.14的时候是没问题的，现在有问题是什么原因

**Comment by cuisongliu** [comment]
是因为之前的shim没有跟着版本走。。。之前的shim用的4.1.4的 导致这次改4.1.3的shim好多镜像都用不了

**Comment by cyf33** [comment]
> 是因为之前的shim没有跟着版本走。。。之前的shim用的4.1.4的 导致这次改4.1.3的shim好多镜像都用不了

。。。等修复

**Comment by li-gaozhe** [comment]
CentOS 7.9 运行sealos  run     --masters 172.29.165.171 --nodes 172.29.165.181,172.29.165.182 -p test123@123     labring/kubernetes-docker:v1.23.10     labring/calico:v3.22.1 --pk /root/.ssh/id_rsa报错
FATA[0000] pulling image: rpc error: code = Unknown desc = Error response from daemon: Head "http://sealos.hub:5000/v2/pause/manifests/3.6": no basic auth credentials 
2022-12-22T11:48:26 error Applied to cluster error: failed to init exec auth.sh failed exit status 1

**Comment by Lion66666** [comment]
> 可以问一下你们操作系统是什么吗，然后服务器是干净的吗，有提前装什么东西吗，我使用multipass 创amd64的ubuntu虚拟机没复线问题
> 
> ```
> sealos run labring/kubernetes:v1.24.1 labring/helm:v3.8.2 labring/calico:v3.24.1 --masters $master_ip --nodes $node_ip
> ```
> 
> ```
> root@yyj-2282-master1:~/.sealos/default# sealos version
> {"gitVersion":"4.1.4-rc3","gitCommit":"43497b9b","buildDate":"2022-12-15T15:16:03Z","goVersion":"go1.19.4","compiler":"gc","platform":"linux/amd64"}
> root@yyj-2282-master1:~/.sealos/default# kubectl get nodes
> NAME               STATUS   ROLES           AGE   VERSION
> yyj-2282-master1   Ready    control-plane   60m   v1.24.1
> yyj-2282-node1     Ready    <none>          59m   v1.24.1
> ```
> 
> @Lion66666

服务器是干净的，服务器系统是 CentOS Linux release 7.6.1810 (Core) ，我装的是 labring/kubernetes-docker

**Comment by Lion66666** [comment]
> 是因为之前的shim没有跟着版本走。。。之前的shim用的4.1.4的 导致这次改4.1.3的shim好多镜像都用不了

请问，预计什么时候能修复呢

**Comment by cuisongliu** [comment]
曲线救国一下 今天修复一下。

**Comment by cuisongliu** [comment]
已经解决了，docker支持 1.18-1.25 ， 1.26 还没有正式发布。需要等release 4.1.4之后
