### ISSUE TITLE
BUG: admin.conf:no such file or directory (SyncNewVersionConfig for old version) 

### ISSUE THREAD

**Issue by Swifto0** [labring/sealos#2285]
### Sealos Version

v4.1.4-rc3-43497b9b

### How to reproduce the bug?

CentOS7
安装k8s:v1.25.0
运行单节点或多节点安装都报错：
error applied to cluster error:read admin.conf error in guest: open /root/.sealos/default/etc/admin.conf:no such file or directory

### Operating environment

```markdown
- Sealos version:v4.1.4-rc3-43497b9b
- Docker version:
- Kubernetes version:v1.25.0
- Operating system:CentOS7
- Runtime environment:
- Cluster size:single/1Master(4CPU 8G Memory)-2Node(2CPU 4GMemory)
- Additional information:
```

**Comment by fanux** [comment]
是否在 master0 节点上执行？

**Comment by StringKe** [comment]
遇到同样的问题 `sealos run labring/kubernetes:v1.25.0 labring/helm:v3.8.2 labring/calico:v3.24.1 --single`

**Comment by goDaryl** [comment]
how to do ?

**Comment by cuisongliu** [comment]
need sync new version config from old version cluster

**Comment by cuisongliu** [comment]
```
processor.SyncNewVersionConfig(c.ClusterDesired.Name)
```
