### ISSUE TITLE
BUG: brief description of the bug

### ISSUE THREAD

**Issue by Mmaoxiaodong** [labring/sealos#2315]
### Sealos Version

v4.1.3

### How to reproduce the bug?

这是什么原因导致的？ssh超时原因吗？
error Applied to cluster error: failed to run checker: checker: failed to create ssh client, wait for [192.168.44.153:22] ssh ready timeout:  [ssh 192.168.44.153:22]create ssh session failed, ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain, ensure that the IP address or password is correct

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

### Additional information

error Applied to cluster error: failed to run checker: checker: failed to create ssh client, wait for [192.168.44.153:22] ssh ready timeout:  [ssh 192.168.44.153:22]create ssh session failed, ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain, ensure that the IP address or password is correct

**Comment by fengxsong** [comment]
Have you configured your username and password/privatekey correctly? Need more informations.

**Comment by fanux** [comment]
Make sure the ssh connection is ok, and use single quotes if the password has special characters. If there is still a problem, reopen this issue
