### ISSUE TITLE
Feature: sealos gen Error: unknown flag: --single

### ISSUE THREAD

**Issue by willzhang** [labring/sealos#2318]
### What is the problem this feature will solve?

```
root@ubuntu:~# sealos gen registry.cn-shenzhen.aliyuncs.com/cnmirror/kubernetes:v1.25.3 --single
Error: unknown flag: --single
```

**Comment by fanux** [comment]
Why is it not considered a single node if the host list = 0?  because of applications image?

**Comment by cuisongliu** [comment]
The single parameter doesn't seem to make much sense
