### ISSUE TITLE
Question: kubernetes-dashboard 生成的token 登录一次就401失效

### ISSUE THREAD

**Issue by liuziyuan** [labring/sealos#2341]
### Detailed description of the question.

使用`kubectl -n kubernetes-dashboard create token admin-user` 命令生成了一个token，登陆到dashboard后，退出登录。
再使用此token登录，页面在token下报 Unauthorized (401): Invalid credentials provided 

然后重新登录，又试验了几次，登录成功了又

===================
几个小时候，我再次登录N次， 依旧还是Unauthorized (401): Invalid credentials provided

**Comment by fanux** [comment]
超时了吧，这个问题可能更适合在 kubernetes dashboard 那边提问我觉得。
