### ISSUE TITLE
BUG: coredns blocked

### ISSUE THREAD

**Issue by BussanQ** [labring/sealos#2349]
### Sealos Version

v4.1.3

### How to reproduce the bug?

sealos run docker.io/labring/kubernetes-docker:v1.21.14 labring/helm:v3.8.2 labring/calico:v3.24.1  --single
coredns显示blocked
![IMG_3017](https://user-images.githubusercontent.com/10459811/211193666-356c6f38-07a9-418e-ae01-ed0f34da9c39.PNG)

### What is the expected behavior?

coredns正常

### Operating environment

```markdown
- Sealos version: v4.1.3
- Docker version: v20.10.22
- Kubernetes version: v1.21.14-docker
- Operating system: centos7
- Cluster size: 1master
```

**Comment by wubolive** [comment]
同问，运行完集群后coredns状态为Blocked
```
$ sealos run labring/kubernetes-docker:v1.20.5-4.1.3 labring/helm:v3.8.2 labring/calico:v3.24.1 --single
$ kubectl get pod -A
NAMESPACE         NAME                                 READY   STATUS    RESTARTS   AGE
kube-system       coredns-74ff55c5b-rx2hc              0/1     Pending   0          99s
kube-system       coredns-74ff55c5b-wtjdp              0/1     Pending   0          99s
kube-system       etcd-kubernetes                      1/1     Running   0          114s
kube-system       kube-apiserver-kubernetes            1/1     Running   0          114s
kube-system       kube-controller-manager-kubernetes   1/1     Running   0          114s
kube-system       kube-proxy-wfsm4                     1/1     Running   0          99s
kube-system       kube-scheduler-kubernetes            1/1     Running   0          114s
tigera-operator   tigera-operator-6f669b6c4f-p5qsn     1/1     Running   0          99s

$ kubectl taint node --all node.kubernetes.io/not-ready-

$ kubectl get pod -A
NAMESPACE         NAME                                 READY   STATUS    RESTARTS   AGE
kube-system       coredns-74ff55c5b-rx2hc              0/1     Blocked   0          2m17s
kube-system       coredns-74ff55c5b-wtjdp              0/1     Blocked   0          2m17s
kube-system       etcd-kubernetes                      1/1     Running   0          2m32s
kube-system       kube-apiserver-kubernetes            1/1     Running   0          2m32s
kube-system       kube-controller-manager-kubernetes   1/1     Running   0          2m32s
kube-system       kube-proxy-wfsm4                     1/1     Running   0          2m17s
kube-system       kube-scheduler-kubernetes            1/1     Running   0          2m32s
tigera-operator   tigera-operator-6f669b6c4f-p5qsn     1/1     Running   0          2m17s

$ kubectl describe pod coredns-74ff55c5b-wtjdp -n kube-system
......
Events:
  Type     Reason            Age    From               Message
  ----     ------            ----   ----               -------
  Warning  FailedScheduling  2m55s  default-scheduler  0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
  Warning  FailedScheduling  2m55s  default-scheduler  0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
  Normal   Scheduled         43s    default-scheduler  Successfully assigned kube-system/coredns-74ff55c5b-wtjdp to kubernetes
```

**Comment by cuisongliu** [comment]
看一下dns pod的配置

**Comment by BussanQ** [comment]
> 看一下dns pod的配置

拉起的就是官方镜像，没做任何修改

kubectl get cm -n kube-system -oyaml coredns
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system


kubectl get deploy -n kube-system -oyaml coredns
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-01-08T01:59:08Z"
  generation: 1
  labels:
    k8s-app: kube-dns
  name: coredns
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kube-dns
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: kube-dns
    spec:
      containers:
      - args:
        - -conf
        - /etc/coredns/Corefile
        image: k8s.gcr.io/coredns/coredns:v1.8.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: coredns
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 9153
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 8181
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 170Mi
          requests:
            cpu: 100m
            memory: 70Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/coredns
          name: config-volume
          readOnly: true
      dnsPolicy: Default
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: coredns
      serviceAccountName: coredns
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: Corefile
            path: Corefile
          name: coredns
        name: config-volume
status:
  conditions:
  - lastTransitionTime: "2023-01-08T01:59:19Z"
    lastUpdateTime: "2023-01-08T01:59:19Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2023-01-08T02:09:20Z"
    lastUpdateTime: "2023-01-08T02:09:20Z"
    message: ReplicaSet "coredns-558bd4d5db" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 1
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 2

**Comment by BussanQ** [comment]
> 看一下dns pod的配置

kubectl get po -n kube-system  -o yaml coredns-558bd4d5db-dvzt8
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-01-08T01:59:20Z"
  generateName: coredns-558bd4d5db-
  labels:
    k8s-app: kube-dns
    pod-template-hash: 558bd4d5db
  name: coredns-558bd4d5db-dvzt8
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: coredns-558bd4d5db
spec:
  containers:
  - args:
    - -conf
    - /etc/coredns/Corefile
    image: k8s.gcr.io/coredns/coredns:v1.8.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /health
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: coredns
    ports:
    - containerPort: 53
      name: dns
      protocol: UDP
    - containerPort: 53
      name: dns-tcp
      protocol: TCP
    - containerPort: 9153
      name: metrics
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /ready
        port: 8181
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        memory: 170Mi
      requests:
        cpu: 100m
        memory: 70Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - NET_BIND_SERVICE
        drop:
        - all
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/coredns
      name: config-volume
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-9zwpv
      readOnly: true
  dnsPolicy: Default
  enableServiceLinks: true
  nodeName: xxx
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 2000000000
  priorityClassName: system-cluster-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: coredns
  serviceAccountName: coredns
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      items:
      - key: Corefile
        path: Corefile
      name: coredns
    name: config-volume
  - name: kube-api-access-9zwpv
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-01-08T02:00:05Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-01-08T02:00:05Z"
    message: 'containers with unready status: [coredns]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-01-08T02:00:05Z"
    message: 'containers with unready status: [coredns]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-01-08T02:00:05Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: k8s.gcr.io/coredns/coredns:v1.8.0
    imageID: ""
    lastState: {}
    name: coredns
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: Blocked
  hostIP: xxx
  message: 'Cannot enforce NoNewPrivs: illegal version string "v1alpha2"'
  phase: Pending
  qosClass: Burstable
  reason: NoNewPrivs
  startTime: "2023-01-08T02:00:05Z"

**Comment by wubolive** [comment]
新发现，/var/log/message 日志报错：
```
Jan  9 13:45:03 kubernetes kubelet: E0109 13:45:03.450128    8331 pod_workers.go:191] Error syncing pod 39e954a0-75a8-471c-a319-513958ca3d42 ("coredns-74ff55c5b-xvw6m_kube-system(39e954a0-75a8-471c-a319-513958ca3d42)"), skipping: pod cannot be run: Cannot enforce NoNewPrivs: illegal version string "v1alpha2"
Jan  9 13:45:06 kubernetes kubelet: E0109 13:45:06.657214    8331 kubelet.go:2188] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```

**Comment by cuisongliu** [comment]
illegal version string "v1alpha2" 。。。。好像是cri-dockerd的问题。

**Comment by wubolive** [comment]
> illegal version string "v1alpha2" 。。。。好像是cri-dockerd的问题。

用的是 `labring/kubernetes-docker:v1.20.5-4.1.3` 镜像

**Comment by BussanQ** [comment]
> illegal version string "v1alpha2" 。。。。好像是cri-dockerd的问题。

所以你们需要更新镜像吗？以前的sealos版本部署成功过，而且这个好像和k8s版本也有关系，这两天用同样的calico 3.24.1镜像，1.25的docker版本镜像能运行成功，1.22、1.21都有这个block问题

**Comment by wubolive** [comment]
亲测，更换为`labring/kubernetes-docker:v1.25.0-4.1.3`版本运行没问题。

**Comment by muicoder** [comment]
Use cri-dockerd v0.2.6 below kubernetes-v1.26.

**Comment by muicoder** [comment]
> Use cri-dockerd v0.2.6 below kubernetes-v1.26.

The 4.1.3/4.1.4 image has been updated!

**Comment by luanshaotong** [comment]
2023.2.1，k8s 1.19镜像依然存在这个问题。

**Comment by muicoder** [comment]
https://github.com/kubean-io/kubean/issues/487

**Comment by muicoder** [comment]
docker默认加载的seccomp配置内容
> https://github.com/moby/moby/blob/master/profiles/seccomp/default.json

**Comment by muicoder** [comment]
> labring/kubernetes-docker:v1.25.6-4.1.3

![image](https://user-images.githubusercontent.com/13899572/215986627-cfce9bd4-2dcb-4de2-83be-b51ddfc3db28.png)

**Comment by luanshaotong** [comment]
@muicoder 感谢支持，排查发现是我的配置问题。

**Comment by luanshaotong** [comment]
@muicoder 1.19还是有问题，这个后面不修了吗？

**Comment by muicoder** [comment]
> @muicoder 1.19还是有问题，这个后面不修了吗？

发下镜像版本，重现定位一下

**Comment by luanshaotong** [comment]
labring/kubernetes-docker:v1.19.6-4.1.4
labring/kubernetes-docker:v1.19.6-4.1.3
需要安装后的截图吗
