### ISSUE TITLE
sealos 3 failed to install on ubuntu22.04

### ISSUE THREAD

**Issue by zzlingyun** [labring/sealos#2359]
### Sealos Version

v3.3

### How to reproduce the bug?

在ubuntu-22.04-server版镜像下，使用sealos3版本无法安装k8s，
测试命令sealos init --passwd 123456 - --master 192.168.100.72:10086  --pkg-url /home/bridge/kube1.17.15.tar.gz --version v1.17.15

kubeadm init --config=/root/kubeadm-config.yaml --upload-certs -v 0系统在这个位置卡住

最后一遍尝试的时候kubelet能启动但是报错很多，并且cpu 100% 所有容器都是created状态
Jan 09 13:36:36 zkdn kubelet[92689]: E0109 13:36:36.489966   92689 pod_workers.go:191] Error syncing pod d2d29b192e9b213b35c9006b0f22cc78 ("kube-scheduler-zkdn_kube-system(d2d29b192e9b213b35c9006b0f22c>
Jan 09 13:36:36 zkdn kubelet[92689]: E0109 13:36:36.490613   92689 kuberuntime_manager.go:741] createPodSandbox for pod "kube-apiserver-zkdn_kube-system(1e2163ff6c5e8a2de867b9749b055404)" failed: rpc e>
Jan 09 13:36:36 zkdn kubelet[92689]: W0109 13:36:36.323789   92689 cni.go:239] Unable to update cni config: no networks found in /etc/cni/net.d
Jan 09 13:36:36 zkdn kubelet[92689]: E0109 13:36:36.687494   92689 pod_workers.go:191] Error syncing pod 1e2163ff6c5e8a2de867b9749b055404 ("kube-apiserver-zkdn_kube-system(1e2163ff6c5e8a2de867b9749b055>
Jan 09 13:36:36 zkdn kubelet[92689]: E0109 13:36:36.788139   92689 controller.go:136] failed to ensure node lease exists, will retry in 7s, error: Get "https://apiserver.cluster.local:6443/apis/coordin>
Jan 09 13:36:36 zkdn kubelet[92689]: E0109 13:36:36.866278   92689 kubelet.go:2209] node "zkdn" not found
Jan 09 13:36:36 zkdn kubelet[92689]: E0109 13:36:36.874851   92689 kubelet.go:2129] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin i>
Jan 09 13:36:37 zkdn kubelet[92689]: E0109 13:36:37.007131   92689 kubelet.go:2209] node "zkdn" not found

### What is the expected behavior?

13:00:09 [INFO] [ssh.go:27] [ssh][192.168.100.72:10086] kubeadm init --config=/root/kubeadm-config.yaml --upload-certs -v 0
13:04:12 [DEBG] [ssh.go:39] [ssh][192.168.100.72:10086]command result is: W0109 13:00:10.072455   12694 common.go:77] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta1". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0109 13:00:10.073320   12694 common.go:77] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta1". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0109 13:00:10.169883   12694 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
[init] Using Kubernetes version: v1.19.16
[preflight] Running pre-flight checks
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
        [WARNING FileExisting-ethtool]: ethtool not found in system path
        [WARNING FileExisting-socat]: socat not found in system path
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Using existing apiserver-kubelet-client certificate and key on disk
[certs] Using existing front-proxy-ca certificate authority
[certs] Using existing front-proxy-client certificate and key on disk
[certs] Using existing etcd/ca certificate authority
[certs] Using existing etcd/server certificate and key on disk
[certs] Using existing etcd/peer certificate and key on disk
[certs] Using existing etcd/healthcheck-client certificate and key on disk
[certs] Using existing apiserver-etcd-client certificate and key on disk
[certs] Using the existing "sa" key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/admin.conf"
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/kubelet.conf"
W0109 13:00:11.381685   12694 kubeconfig.go:242] a kubeconfig file "/etc/kubernetes/controller-manager.conf" exists already but has an unexpected API Server URL: expected: https://192.168.100.72:6443, got: https://apiserver.cluster.local:6443
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/controller-manager.conf"
W0109 13:00:11.954142   12694 kubeconfig.go:242] a kubeconfig file "/etc/kubernetes/scheduler.conf" exists already but has an unexpected API Server URL: expected: https://192.168.100.72:6443, got: https://apiserver.cluster.local:6443
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/scheduler.conf"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

        Unfortunately, an error has occurred:
                timed out waiting for the condition

        This error is likely caused by:
                - The kubelet is not running
                - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

        If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
                - 'systemctl status kubelet'
                - 'journalctl -xeu kubelet'

        Additionally, a control plane component may have crashed or exited when started by the container runtime.
        To troubleshoot, list all containers using your preferred container runtimes CLI.

        Here is one example how you may list all Kubernetes containers running in docker:
                - 'docker ps -a | grep kube | grep -v pause'
                Once you have found the failing container, you can inspect its logs with:
                - 'docker logs CONTAINERID'

error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher

13:04:12 [EROR] [ssh.go:42] [ssh][192.168.100.72:10086]Error exec command failed: Process exited with status 1
13:04:12 [EROR] [init.go:204] [192.168.100.72:10086] install kubernetes failed. please clean and uninstall.

### Operating environment

```markdown
- Sealos version:3.3
- Docker version:19.03
- Kubernetes version:1.17.16/1.18.20/1.19.16
- Operating system: ubuntu-22.04-server
- Runtime environment:
- Cluster size:1个master\  1个master 1个node
- Additional information:
```

**Comment by cuisongliu** [comment]
3.x 不维护了 直接用 4.x吧

**Comment by cuisongliu** [comment]
docker ps -a | grep kube | grep -v pause  看一下有docker镜像么
