### ISSUE TITLE
BUG: v4.1.4 kubernetes-docker image run coredns error 

### ISSUE THREAD

**Issue by wubolive** [labring/sealos#2361]
### Sealos Version

v4.1.4

### How to reproduce the bug?

sealos v4.1.4 版本kubernetes-docker运行集群，coredns pod 启动失败
```
$ sealos run labring/kubernetes-docker:v1.25.0-4.1.4 --single
$ kubectl taint node --all node.kubernetes.io/not-ready-
$ kubectl get pod -A 
NAMESPACE     NAME                                 READY   STATUS              RESTARTS   AGE
kube-system   coredns-787d4945fb-87jfp             0/1     ContainerCreating   0          2m53s
kube-system   coredns-787d4945fb-hswps             0/1     ContainerCreating   0          2m53s
kube-system   etcd-kubernetes                      1/1     Running             0          3m7s
kube-system   kube-apiserver-kubernetes            1/1     Running             0          3m7s
kube-system   kube-controller-manager-kubernetes   1/1     Running             0          3m7s
kube-system   kube-proxy-dlrmv                     1/1     Running             0          2m53s
kube-system   kube-scheduler-kubernetes            1/1     Running             0          3m7s
$ kubectl describe pod coredns-787d4945fb-87jfp -n kube-system
......
Events:
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  3m10s                  default-scheduler  0/1 nodes are available: 1 node(s) had untolerated taint {node.kubernetes.io/not-ready: }. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling..
  Normal   Scheduled         2m41s                  default-scheduler  Successfully assigned kube-system/coredns-787d4945fb-87jfp to kubernetes
  Warning  FailedMount       2m10s (x7 over 2m41s)  kubelet            MountVolume.SetUp failed for volume "config-volume" : object "kube-system"/"coredns" not registered
  Warning  NetworkNotReady   2m8s (x18 over 2m41s)  kubelet            network is not ready: container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```
经测试，`v1.22.10-4.1.4`、`v1.25.0-4.1.4`、`v1.26.0-4.1.4`均存在此问题。

### What is the expected behavior?

sealos run 启动集群 `kubectl get pod -n kube-system` Pod is Running

### Operating environment

```markdown
- Sealos version: v4.1.4
- Docker version: 20.10.22
- Kubernetes version: v1.25.0
- Operating system: centos7
- Runtime environment:
- Cluster size: 1 master
- Additional information:
```

**Comment by cuisongliu** [comment]
需要安装calico

**Comment by qqpuser** [comment]
我也遇到无法安装coredns 环境是：银河麒麟v10  arm架构下离线安装出现错误:

sealos version:  v4.1.4-rc4

sealos run labring/kubernetes-docker:v1.26 labring/helm:v3.10.3 labring/calico:v3.25.0  --masters 192.168.1.2 --nodes 192.168.1.3  --passwd '123456'
[root@node12 ~]# kubectl get pod -A
NAMESPACE          NAME                                                     READY     STATUS         RESTARTS      AGE
calico-apiserver   calico-apiserver-9d847d946-8dfkh           1/1          Running            0                58m
calico-apiserver   calico-apiserver-9d847d946-wzjrh            1/1          Running            0                58m
calico-system      calico-kube-controllers-6b7b9c649d-6lpvk   1/1     Running            0                59m
calico-system      calico-node-hw985                                    1/1          Running            0                59m
calico-system      calico-node-xv2n6                                     1/1          Running            0                59m
calico-system      calico-typha-68586bbf7f-tk4tg                  1/1          Running            0                59m
calico-system      csi-node-driver-xssqd                                 2/2         Running            0                59m
calico-system      csi-node-driver-zknt4                                 2/2          Running            0                59m
kube-system        coredns-787d4945fb-268hc                       0/1         CrashLoopBackOff   16 (2m10s ago)   59m
kube-system        coredns-787d4945fb-n8hkz                       0/1         CrashLoopBackOff   16 (2m29s ago)   59m
kube-system        etcd-node1                                                1/1          Running            0                59m
kube-system        kube-apiserver-node1                               1/1          Running            0                59m
kube-system        kube-controller-manager-node1              1/1          Running            0                59m
kube-system        kube-proxy-28r6d                                     1/1          Running            0                59m
kube-system        kube-proxy-kz8k9                                     1/1          Running            0                59m
kube-system        kube-scheduler-node1                              1/1         Running            0                59m
kube-system        kube-sealos-lvscare-node2                       1/1         Running            0                59m
tigera-operator    tigera-operator-54b47459dd-598wn        1/1         Running            0                59m

$kubectl describe pod coredns-787d4945fb-n8hkz -n kube-system
.....
Events:
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  54m                    default-scheduler  0/1 nodes are available: 1 node(s) had untolerated taint {node.kubernetes.io/not-ready: }. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling..
  Normal   Scheduled         54m                    default-scheduler  Successfully assigned kube-system/coredns-787d4945fb-n8hkz to node6
  Normal   Pulling           54m                    kubelet            Pulling image "registry.k8s.io/coredns/coredns:v1.9.3"
  Normal   Pulled            54m                    kubelet            Successfully pulled image "registry.k8s.io/coredns/coredns:v1.9.3" in 355.770859ms (3.710791995s including waiting)
  Warning  Failed            53m (x4 over 54m)      kubelet            Error: failed to start container "coredns": Error response from daemon: failed to create shim task: OCI runtime create failed: container_linux.go:318: starting container process caused "process_linux.go:281: applying cgroup configuration for process caused \"No such device or address\"": unknown
  Normal   Created           52m (x5 over 54m)      kubelet            Created container coredns
  Normal   Pulled            52m (x4 over 54m)      kubelet            Container image "registry.k8s.io/coredns/coredns:v1.9.3" already present on machine
  Warning  BackOff           4m16s (x246 over 54m)  kubelet            Back-off restarting failed container coredns in pod coredns-787d4945fb-n8hkz_kube-system(76cb4e0b-662c-418f-b67c-8e24cd9f1eff)

**Comment by cuisongliu** [comment]
logs -f coredns-787d4945fb-268hc

**Comment by qqpuser** [comment]
> logs -f coredns-787d4945fb-268hc

没有日志输出，删除pod后也没日志

![image](https://user-images.githubusercontent.com/18298143/216805137-e0d8a82e-d722-482a-b984-06101626dd2b.png)

**Comment by 46797536** [comment]
谢谢，这个需要手动把cgroup 都改成cgroupfs就可以了
