### ISSUE TITLE
Question: brief description of the question

### ISSUE THREAD

**Issue by HereHaveAnPeople** [labring/sealos#2363]
### Detailed description of the question.

使用 sealos 版本如下：
![image](https://user-images.githubusercontent.com/54338257/211455283-da173c74-5a07-4411-b0ad-91f56b5dfe18.png)

当我添加了3个主节点后，把最开始的部署（sealos 命令所在的主机）的master down 掉，集群命令不可用了，down 其他的master 没有问题。
请问这是什么问题那。

部署命令：
sealos gen docker.io/labring/kubernetes-docker:v1.20.15 docker.io/labring/calico  \
   --masters 192.168.66.10 \
   --nodes 192.168.66.11,192.168.66.12 --passwd '123123' > Clusterfile

sealos apply
添加master 命令：
sealos add --master  ip

**Comment by cuisongliu** [comment]
master0比较关键，不能down掉。里面有registry以及部署的核心内容。

**Comment by HereHaveAnPeople** [comment]
master0 不就是单点了嘛。多master只是为了etcd 变成集群吗？
