### ISSUE TITLE
BUG: v4.1.4 CMD不生效

### ISSUE THREAD

**Issue by BussanQ** [labring/sealos#2364]
### Sealos Version

v4.1.4

### How to reproduce the bug?

FROM docker.io/labring/kubernetes-docker:v1.21.14
COPY cni ./cni
COPY images ./images
COPY registry ./registry
CMD ["kubectl apply -f cni/tigera-operator.yaml","kubectl apply -f cni/custom-resources.yaml"]

sealos build -t localhost/kubernetes:v1.21.14-cni .
sealos run localhost/kubernetes:v1.21.14-cni  --single
部署后并没有执行CMD里的命令，没有calico相关pod运行

kubectl get po -A -o wide

NAMESPACE     NAME                                           READY   STATUS    RESTARTS   AGE    
kube-system   coredns-558bd4d5db-7l2jx        0/1          Pending   0          2m18s  
kube-system   coredns-558bd4d5db-c62zv      0/1         Pending   0          2m18s  
kube-system   etcd-aim                                         1/1          Running   0          2m26s  
kube-system   kube-apiserver-aim                       1/1          Running   0          2m26s  
kube-system   kube-controller-manager-aim      1/1          Running   0          2m26s  
kube-system   kube-proxy-dfcr6                          1/1          Running   0          2m18s  
kube-system   kube-scheduler-aim                      1/1          Running   0          2m26s

**Comment by fanux** [comment]
@cuisongliu this bug need hotfix!

**Comment by FlyingOnion** [comment]
```dockerfile
FROM docker.io/labring/kubernetes-docker:v1.21.14
COPY cni ./cni
COPY images ./images
COPY registry ./registry
RUN kubectl apply -f cni/tigera-operator.yaml
RUN kubectl apply -f cni/custom-resources.yaml
```
@BussanQ 建议改成这样，CMD 不是用来干这个的

**Comment by BussanQ** [comment]
@FlyingOnion 不是我想用，是官网文档就是这样说明的，而且我也没在官网找到有这个RUN命令

**Comment by FlyingOnion** [comment]
> @FlyingOnion 不是我想用，是官网文档就是这样说明的，而且我也没在官网找到在Kubefile里有这个RUN命令

你用的旧的版本吧，现在v4.1.3，v4.1.4分支里面都找不到 sealos build 这个命令了，现在构建镜像都挪到 sealer。

https://github.com/labring/sealos/tree/release-v4.1.4/cmd/sealos/cmd

https://github.com/sealerio/sealer/tree/main/cmd/sealer/cmd/image

kubefile 最终都要转换为 Dockerfile 用 buildah 构建。这不是在 shell 环境里面，所以构建的时候 `kubectl apply -f cni/tigera-operator.yaml` 这个字符串会被当成一个命令执行。这一点在 docker build 和 buildah 都是一样的。

所以要不合并为一个命令，写成
```dockerfile
CMD ["kubectl", "apply", "-f", "cni/tigera-operator.yaml", "-f", "cni/custom-resources.yaml"]
```

要不放 shell 脚本里面执行，写成
```sh
#!/bin/sh
kubectl apply -f cni/tigera-operator.yaml
kubectl apply -f cni/custom-resources.yaml
```

```dockerfile
CMD ["sh", "install.sh"]
```

**Comment by BussanQ** [comment]
> > @FlyingOnion 不是我想用，是官网文档就是这样说明的，而且我也没在官网找到在Kubefile里有这个RUN命令
> 
> 你用的旧的版本吧，现在v4.1.3，v4.1.4分支里面都找不到 sealos build 这个命令了，现在构建镜像都挪到 sealer。
> 
> https://github.com/labring/sealos/tree/release-v4.1.4/cmd/sealos/cmd
> 
> https://github.com/sealerio/sealer/tree/main/cmd/sealer/cmd/image
> 
> kubefile 最终都要转换为 Dockerfile 用 buildah 构建。这不是在 shell 环境里面，所以构建的时候 `kubectl apply -f cni/tigera-operator.yaml` 这个字符串会被当成一个命令执行。这一点在 docker build 和 buildah 都是一样的。
> 
> 所以要不合并为一个命令，写成
> 
> ```dockerfile
> CMD ["kubectl", "apply", "-f", "cni/tigera-operator.yaml", "-f", "cni/custom-resources.yaml"]
> ```
> 
> 要不放 shell 脚本里面执行，写成
> 
> ```shell
> #!/bin/sh
> kubectl apply -f cni/tigera-operator.yaml
> kubectl apply -f cni/custom-resources.yaml
> ```
> 
> ```dockerfile
> CMD ["sh", "install.sh"]
> ```

@fanux @FlyingOnion 你这是官方回复吗？据我所知sealos和sealer现在算是两个独立的项目，而且我说清楚了是4.1.4版本CMD命令不生效，你写成脚本也是不生效。另外你确定现在没有sealos build了？

**Comment by FlyingOnion** [comment]
@BussanQ 我就是个关注项目的独立开发者，是的我没仔细看代码，您是对的。🙂🙂

**Comment by cuisongliu** [comment]
> @BussanQ 我就是个关注项目的独立开发者，是的我没仔细看代码，您是对的。slightly_smiling_faceslightly_smiling_face

项目的确是俩项目，而且处理逻辑sealos和sealer对于Kubefile不一样。所以不能拿sealer逻辑来说sealos的问题。

**Comment by cuisongliu** [comment]
https://github.com/labring-actions/bug-verfiy/blob/main/.github/workflows/2364.yml

**Comment by dinoallo** [comment]
研究了下，这段代码应该是问题所在：
After digging, it seems like this part of code may present the problem:
https://github.com/labring/sealos/blob/419203376b5b2a521b5dde1521ce254132021f6f/pkg/guest/guest.go#L77-L107

原因在于自己打包的 k8s 为 `RootfsImage` 而非 `AppImage` ，而目前的 `getGuestCmd` 只处理 `AppImage` 因而被忽略，镜像中的 `CMD` metadata 是正确的，但没被执行。
It's caused by custom-flavored k8s being identified as `RootfsImage` rather than `AppImage`, and `getGuestCmd` only handles the cases where images are the later ones. So even `CMD`s are correctly processed in image's metadata, they won't even get a change to be executed.

**Comment by BussanQ** [comment]
那sealos build有定义为AppImage的参数吗 @dinoallo @cuisongliu

**Comment by cuisongliu** [comment]
> 那sealos build有定义为AppImage的参数吗 @dinoallo @cuisongliu

默认build的镜像就是APP的类型

**Comment by cuisongliu** [comment]
> 研究了下，这段代码应该是问题所在： After digging, it seems like this part of code may present the problem:
> 
> https://github.com/labring/sealos/blob/419203376b5b2a521b5dde1521ce254132021f6f/pkg/guest/guest.go#L77-L107
> 
> 原因在于自己打包的 k8s 为 `RootfsImage` 而非 `AppImage` ，而目前的 `getGuestCmd` 只处理 `AppImage` 因而被忽略，镜像中的 `CMD` metadata 是正确的，但没被执行。 It's caused by custom-flavored k8s being identified as `RootfsImage` rather than `AppImage`, and `getGuestCmd` only handles the cases where images are the later ones. So even `CMD`s are correctly processed in image's metadata, they won't even get a change to be executed.

那把这个过滤去掉就可以。
