### ISSUE TITLE
apply 安装幂等问题，安装失败再次无法安装

### ISSUE THREAD

**Issue by feixia5712** [labring/sealos#2368]
### Detailed description of the question.

![image](https://user-images.githubusercontent.com/12670758/211480241-e01989ab-c1ac-47b6-8367-9cb9b9e09fcc.png)

**Comment by willzhang** [comment]
get install method first , and `db0c7cfb6223 ` is image id
```
sealos inspect db0c7cfb6223 |grep CMD
```
uninstall manual by 
```
helm uninstall  xxx
```

or you can use -f, it will force reinstall auto  (for sealos v4.1.4-xx)
```
sealos run -f xxx
```

**Comment by feixia5712** [comment]
我这都没有那个命名空间promethues
![image](https://user-images.githubusercontent.com/12670758/211520978-36561827-0a17-4243-b7ef-65936d2fa6cf.png)

**Comment by willzhang** [comment]
提示成功并不代表安装上了，因为之前装过一次，sealos以为已经安装了，就跳过了

**Comment by willzhang** [comment]
如果安装失败应该直接失败，不能认为已经安装成功了，helm命令都没执行，sealos这逻辑有问题。
