### ISSUE TITLE
使用sealos 命令安装的calico，没有calicoctl命令？

### ISSUE THREAD

**Issue by liuziyuan** [labring/sealos#2379]
我想改造我的学习集群，使用metallb作为LB 与 Ingress网络交互。
现在metallb 在 calico网络中 提供了一个简便集成方式，通过执行以下命令对calico进行修改
```
calicoctl patch BGPConfig default --patch '{"spec": {"serviceLoadBalancerIPs": [{"cidr": "10.11.0.0/16"},{"cidr":"10.1.5.0/24"}]}}'
```
但是通过sealos 安装的calico组件是没有calicoctl 命令的。
我有什么方案可以在sealos的集群中快速修改并应用这段配置

**Comment by willzhang** [comment]
sealos 就是用helm 装的calico，剩下的就自己做就行
![image](https://user-images.githubusercontent.com/33590311/211791813-bfed3212-e9d4-4669-b45e-96260cac2069.png)

@muicoder 给官方镜像加上calictl命令是否合适？

**Comment by fanux** [comment]
@liuziyuan 可以 FROM 官方的镜像自己在上面再加一层，然后 用 sealos build 即可。

参考：
https://github.com/labring-actions/cluster-image/blob/main/applications/calico/latest/Kubefile
https://www.sealos.io/docs/build-cloud-image/build-cloudImage-with-binary-file

**Comment by liuziyuan** [comment]
> sealos 就是用 helm 装的 calico，剩下的就自己参考官方文档配置就行，没有calicoctl就自己装，或者自己打个calico镜像把calicoctl做进去，参考代码：https://github.com/labring-actions/cluster-image/blob/main/applications/calico/latest/Kubefile
> 
> ![image](https://user-images.githubusercontent.com/33590311/211791813-bfed3212-e9d4-4669-b45e-96260cac2069.png)
> 
> @muicoder 给官方镜像加上calicoctl命令是否合适？

附议，期待sealos官方提供的镜像里有这个功能。

**Comment by muicoder** [comment]
> > sealos 就是用 helm 装的 calico，剩下的就自己参考官方文档配置就行，没有calicoctl就自己装，或者自己打个calico镜像把calicoctl做进去，参考代码：https://github.com/labring-actions/cluster-image/blob/main/applications/calico/latest/Kubefile
> > 
> > ![image](https://user-images.githubusercontent.com/33590311/211791813-bfed3212-e9d4-4669-b45e-96260cac2069.png)
> > 
> > @muicoder 给官方镜像加上calicoctl命令是否合适？
> 
> 附议，期待sealos官方提供的镜像里有这个功能。

https://projectcalico.docs.tigera.io/maintenance/clis/calicoctl/install
