### ISSUE TITLE
Sealos如何与已有的etcd集群配置

### ISSUE THREAD

**Issue by liuziyuan** [labring/sealos#2385]
### Detailed description of the question.

当前已经有了etcd的服务集群，在sealos 命令安装k8s master节点的时候，在哪里可以配置etcd集群的IP地址？

**Comment by fanux** [comment]
1. 相当不推荐用已有集群的方式构建集群，未来 scale 的时候都是问题，我个人觉得相当没有必要。
2. sealos 支持完全自定义 kubeadm 配置来解决这个问题：https://www.sealos.io/docs/getting-started/customize-cluster 在 Clusterfile 中自定义 kubeadm 配置即可，会自动 overwrite.
