### ISSUE TITLE
Feature: Customize Kubelet For each node 针对各 Node 定制 Kubelet

### ISSUE THREAD

**Issue by Thrimbda** [labring/sealos#2394]
### What is the problem this feature will solve?

for each node, we may willing to use [different kubelet configuration](https://kubernetes.io/zh-cn/docs/setup/production-environment/tools/kubeadm/kubelet-integration/#providing-instance-specific-configuration-details), please provide a way to implement this.

对于每个 node，可能会需要不同的 [kubelet 配置](https://kubernetes.io/zh-cn/docs/setup/production-environment/tools/kubeadm/kubelet-integration/#providing-instance-specific-configuration-details)

### What alternatives have you considered?

I have tried to use [patches](https://kubernetes.io/zh-cn/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#patches) to address the problem, yet without documentation, I haven't make it work yet

我尝试使用 [patches](https://kubernetes.io/zh-cn/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#patches) 来解决这个问题，然而还没搞明白怎么定制 kubeadm-join-node.yaml 从而让他 work

**Comment by willzhang** [comment]
https://www.sealyun.com/docs/getting-started/customize-cluster

**Comment by Thrimbda** [comment]
Thanks for the reply, made it work by patch kubelet config afterward
