### ISSUE TITLE
BUG: sealos安装集群时指定的nodeip地址识别错误

### ISSUE THREAD

**Issue by omaidb** [labring/sealos#2398]
传入参数
```shell
sealos run labring/kubernetes:v1.24.0 \
--masters 172.16.0.123 \
--nodes 172.16.0.130,172.16.0.138
```
结果将nodes的ip地址172.16.0.`138`识别为172.16.0.`38`

<img width="1386" alt="image" src="https://user-images.githubusercontent.com/18365223/212240668-f9a292a6-64bc-4a07-922b-18ba5205f2d1.png">

**Comment by omaidb** [comment]
操作系统版本Rock Linux9
是从yum源中安装的 sealos。版本为：4.1.4-1
<img width="612" alt="image" src="https://user-images.githubusercontent.com/18365223/212241081-1c91064d-11a0-4039-a607-eb7ed0a4f6be.png">

**Comment by cuisongliu** [comment]
--debug 打开日志执行看一下

**Comment by bxy4543** [comment]
日志中有提示 `override following app`， 所以应该是先执行了错误的ip，在执行正确ip后就报错，  所以问题应该是执行错误ip 仍然保存了正确状态的问题

**Comment by mixinkexue** [comment]
1
