### ISSUE TITLE
龙蜥系统 安装calico 工作节点异常报错 

### ISSUE THREAD

**Issue by LzhWxz** [labring/sealos#2399]
### Sealos Version

v4.1.3

### How to reproduce the bug?

![图片](https://user-images.githubusercontent.com/58496818/212250039-b2048916-f3b0-410f-abf0-ca45552a520d.png)

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by fanux** [comment]
确定是因为不支持 ipvs 的原因？

**Comment by LzhWxz** [comment]
是的 改成iptables 就可以启动了 原因不是很清楚 网上又说是不支持高版本内核的 我的是4.19.91的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月17日(星期二) 下午4:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [labring/sealos] 龙蜥系统 安装calico 工作节点异常报错  (Issue #2399)





 
确定是因为不支持 ipvs 的原因？

**Comment by fanux** [comment]
这个版本内核应该是没问题的

**Comment by LzhWxz** [comment]
那还是有问题？只要是ipvs模式就calico启动失败



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月29日(星期天) 晚上10:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [labring/sealos] 龙蜥系统 安装calico 工作节点异常报错  (Issue #2399)





 
这个版本内核应该是没问题的

**Comment by cuisongliu** [comment]
目前支持的是ipvs的，主要是lvscare也得必须是ipvs才可以。
