### ISSUE TITLE
Question: 运行sealos run labring/redis-operator:3.1.4的时候，支持直接修改命名空间么？

### ISSUE THREAD

**Issue by ge2009** [labring/sealos#2407]
### Detailed description of the question.

运行sealos run labring/redis-operator:3.1.4的时候，支持直接修改命名空间么？

**Comment by fanux** [comment]
https://github.com/labring-actions/cluster-image/blob/main/applications/redis-operator/3.1.4/Kubefile  集群镜像在这里，可以自己定制化。

定制教程： https://www.sealos.io/docs/getting-started/build-example-cloudimage

如果希望可以通过参数控制 ns 参考： https://www.sealos.io/docs/examples/how-to-use-env

**Comment by willzhang** [comment]
fixed:https://github.com/labring-actions/cluster-image/pull/287
