### ISSUE TITLE
安装集群报错   template: image-cri-shim.yaml.tmpl:21: function "semverCompare" not defined'

### ISSUE THREAD

**Issue by lz0701** [labring/sealos#2439]
### Sealos Version

4.1.3

### How to reproduce the bug?

[root@k8-master /]# sealos run labring/kubernetes:v1.24.0 labring/calico:v3.22.1 --single --debug
2023-01-18T18:54:25 debug loading from existing cluster
2023-01-18T18:54:25 debug cluster info: apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  creationTimestamp: "2023-01-18T10:12:59Z"
  name: default
spec:
  hosts:
  - ips:
    - 192.168.1.240:0
    roles:
    - master
    - amd64
  image:
  - labring/kubernetes:v1.24.0
  - labring/calico:v3.22.1
  ssh:
    user: root
status:
  conditions:
  - lastHeartbeatTime: "2023-01-18T10:12:59Z"
    message: 'render env to rootfs failed: failed to create template: /var/lib/containers/storage/overlay/6020074e76c2853e968c787c51e33e981866bb29d86db5c9d242a1264bb3669c/merged/etc/image-cri-shim.yaml.tmpl
      template: image-cri-shim.yaml.tmpl:21: function "semverCompare" not defined'
    reason: ApplyClusterError
    status: "False"
    type: ApplyClusterSuccess
  mounts:

### What is the expected behavior?

message: 'render env to rootfs failed: failed to create template: /var/lib/containers/storage/overlay/6020074e76c2853e968c787c51e33e981866bb29d86db5c9d242a1264bb3669c/merged/etc/image-cri-shim.yaml.tmpl
      template: image-cri-shim.yaml.tmpl:21: function "semverCompare" not defined'
    reason: ApplyClusterError

### What do you see instead?

message: 'render env to rootfs failed: failed to create template: /var/lib/containers/storage/overlay/6020074e76c2853e968c787c51e33e981866bb29d86db5c9d242a1264bb3669c/merged/etc/image-cri-shim.yaml.tmpl
      template: image-cri-shim.yaml.tmpl:21: function "semverCompare" not defined'
    reason: ApplyClusterError

### Operating environment

```markdown
- Sealos version:4.1.3
- Docker version:
- Kubernetes version:1.24
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

### Additional information

centos8 纯净系统 
sealos run labring/kubernetes:v1.24.0 labring/calico:v3.22.1 --single --debug

**Comment by cuisongliu** [comment]
view /var/lib/containers/storage/overlay/6020074e76c2853e968c787c51e33e981866bb29d86db5c9d242a1264bb3669c/merged/etc/image-cri-shim.yaml.tmpl

**Comment by fanux** [comment]
升级到 sealos 4.1.4 版本即可
