### ISSUE TITLE
BUG: Sealos cloud provider 集群名字 不能包含非法字符

### ISSUE THREAD

**Issue by lingdie** [labring/sealos#2453]
### Sealos Version

sealos cloud

### How to reproduce the bug?

创建集群时，填写集群名称如果包含非法字符就没任何提示失败。

### What is the expected behavior?

提示不应该包含非法字符。
参考 https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names

**Comment by fanux** [comment]
Will add regular expression
