### ISSUE TITLE
Feature: add cni-plugin to kubernetes rootfs

### ISSUE THREAD

**Issue by willzhang** [labring/sealos#2456]
### What is the problem this feature will solve?

this app need cni-plugin

- multus-cni
- flannel
- kube-router
- calico

we can use sealos scp copy cni-plugin binary to all nodes during cluster install, but when run sealos add nodes this action not run again.  

### If you have solution，please describe it
download from

https://github.com/containernetworking/plugins/releases

### What alternatives have you considered?

The official kubeadm based installation method will install cni-plugin to the/opt/cni/bin directory by default.:

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
```
apt install -y kubeadm
```
There are many places where cni-plugin needs to be used. Should it be consistent with the official default behavior
```
root@ubuntu:~# ls /opt/cni/bin/
bandwidth  calico       dhcp   firewall  host-device  install  loopback  portmap  sbr     tuning  vrf
bridge     calico-ipam  dummy  flannel   host-local   ipvlan   macvlan   ptp      static  vlan
root@ubuntu:~# 
```

**Comment by fengxsong** [comment]
Try using patch type cloudimage

**Comment by cuisongliu** [comment]
https://github.com/labring-actions/cluster-image/blob/42f1523a2cfca8348b96ec8fc8ad28d5cee1d5fc/applications/flannel/v0.19.0/manifests/kube-flannel.yml#L136 

It may need to be modified separately, or a separate install-cni ds

**Comment by cuisongliu** [comment]
https://github.com/labring-actions/cluster-image/issues/295 

using this image install cni plugins
