### ISSUE TITLE
双网卡安装想指定NodeIP对应的网卡

### ISSUE THREAD

**Issue by JimLeeee** [labring/sealos#2465]
### Sealos Version

4.1.4

### How to reproduce the bug?

1、机器有两个IP，默认路由是公网IP，建集群时指定IP为内网IP，但是集群起来后node IP显示为公网IP
2、机器网卡非eth,calico启动失败

### What is the expected behavior?

node IP为内网IP

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by FlyingOnion** [comment]
能否给个执行命令看看？

**Comment by fanux** [comment]
命令行只能写内网地址不能写公网地址

**Comment by willzhang** [comment]
是否与这个类似：https://github.com/labring/sealos/issues/2594
