### ISSUE TITLE
option for sealos login to increase the mirror pull limit

### ISSUE THREAD

**Issue by pthirumalachar** [labring/sealos#2487]
### Detailed description of the question.

Hello,
I am trying to run - `sealos run labring/kubernetes:v1.24.0 labring/calico:v3.22.1 --masters $IP_ADDR -p $PASSWORD`.
However I am getting an error like - " error Applied to cluster error: initializing source docker://labring/kubernetes:v1.24.0: reading manifest v1.24.0 in docker.io/labring/kubernetes: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit".
Is there a way, I could pass the credentials of docker hub?
Thanks for all your help in advance
Padmini

**Comment by zzjin** [comment]
You can use our cloud public registry, doc is here: https://www.sealos.io/docs/cloud/apps/appstore/use-sealos-registry

Currently, you need do login action to pull images, as we are focusing provide a way to pull public images anonymous asap.

**Comment by pthirumalachar** [comment]
> You can use our cloud public registry, doc is here: https://www.sealos.io/docs/cloud/apps/appstore/use-sealos-registry
> 
> Currently, you need do login action to pull images, as we are focusing provide a way to pull public images anonymous asap.

Thank You
