### ISSUE TITLE
如何指定kubelet的root-dir目录？

### ISSUE THREAD

**Issue by ghostloda** [labring/sealos#2489]
### Detailed description of the question.

使用sealos部署集群的时候，可以指定kubelet的工作目录吗？或者哪里可以添加更多KUBELET_EXTRA_ARGS启动参数？

**Comment by willzhang** [comment]
如果KUBELET_EXTRA_ARGS 可以是kubeletConfiguration, 可以用这个方法
![image](https://user-images.githubusercontent.com/33590311/216752321-d3470faa-aebc-4cf2-9909-28df444a3704.png)

**Comment by ghostloda** [comment]
> 如果KUBELET_EXTRA_ARGS 在kubeletConfiguration里面可以定义, 可以用这个方法 ![image](https://user-images.githubusercontent.com/33590311/216752321-d3470faa-aebc-4cf2-9909-28df444a3704.png)

我看了一下，这个KUBELET_EXTRA_ARGS不在kubeletConfiguration里面的，是否可以在集群镜像中的kubelet-flags.env.tmpl中添加一个单独的kubeletData ENV。

**Comment by ghostloda** [comment]
通过制作build集群镜像解决
