### ISSUE TITLE
BUG: 离线镜像load以后 run的时候还是会拉取镜像

### ISSUE THREAD

**Issue by nightwhite** [labring/sealos#2523]
### Sealos Version

v4.1.4

### How to reproduce the bug?

![image](https://user-images.githubusercontent.com/22722256/217278721-b41c3760-b3e2-4ce2-8916-6acc0b970264.png)

部署laf时 把相关的镜像打包成离线tar,导入到另外一台机器load以后,run的时候还是会去拉取镜像

图中,有2个重复的为,一个是load的一个是拉取的

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by lingdie** [comment]
提供下run的时候完整的命令，推测是没有修改镜像的tag

**Comment by nightwhite** [comment]
我用sealos 命令改成 docker.io 还是会去拉取镜像

**Comment by cdjianghan** [comment]
能不能详细的说明一下复现bug的流程

**Comment by nightwhite** [comment]
![image](https://user-images.githubusercontent.com/22722256/217456961-9e3912b0-207b-4280-8d4c-df749d2f9b4b.png)
改完了,执行 sealos run labring/kubernetes:v1.24.9 labring/flannel:v0.19.0 labring/helm:v3.8.2 --single

**Comment by cdjianghan** [comment]
看了下，应该是底层拉取镜像的过程之中有问题，你可以换一种使用方式
例如pull alpine:3.17会自动转成 docker.io/library/alpine:3.17，那么它save的时候应该是要用 sealos save -o alpine.tar docker.io/library/alpine:3.17，scp到其他节点。

**Comment by cdjianghan** [comment]
你再sealos run的时候如果使用 sealos run localhost/labring/kubernetes:v1.24.9 localhost/labring/flannel:v0.19.0 localhost/labring/helm:v3.8.2
这样是否还会出现你那个问题呢

**Comment by nightwhite** [comment]
sealos run docker.io/labring/kubernetes:v1.24.9 这种也是会去拉取镜像

**Comment by nightwhite** [comment]
sealos run localhost/labring/kubernetes:v1.24.9 localhost/labring/flannel:v0.19.0 localhost/labring/helm:v3.8.2 这样可以的
