### ISSUE TITLE
安装的集群无法修改网卡，集群版本1.26.1

### ISSUE THREAD

**Issue by chenshengshi** [labring/sealos#2527]
### Sealos Version

4.1.4

### How to reproduce the bug?

1、我执行机器有2个网卡 一个 192网段 一个10网段
2、集群安装Clusterfile 指定配置的是192网段的，安装成功后查看kubectl  get node -o wide 集群节点ip 默认10网段了
3、想着修改 把calico网卡名称固定 指定到192网段的网卡 执行 kubectl  edit daemonsets.apps/calico-node -n calico-system 把其中interface=bond.*|eth.*|en.* 改成interface=enp0s8 
4、但是保存没有报错 在进去后看 interface=bond.*|eth.*|en.*  改了完全不生效

请问我想改calico 网卡名称是要怎么改呢

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cuisongliu** [comment]
https://www.sealos.io/docs/getting-started/customize-cluster

**Comment by chenshengshi** [comment]
我Clusterfile  这个文件也写死了 网卡名称   interface: "enp0s8"  但是 集群启动后 使用的IP还是enp0s3 网卡的IP
