### ISSUE TITLE
sealos add nodes  报错

### ISSUE THREAD

**Issue by chenshengshi** [labring/sealos#2528]
### Sealos Version

4.1.4

### How to reproduce the bug?

![image](https://user-images.githubusercontent.com/43060901/217441982-48159a60-3ba7-4fac-8ee3-256c2f3971c9.png)

新增一个node节点时候报错，请问这个问题要怎么解决呢

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cuisongliu** [comment]
本地没有iptables
