### ISSUE TITLE
安装 sealos工具无法运行命令， /usr/bin/sealos：无法执行二进制文件: 可执行文件格式错误

### ISSUE THREAD

**Issue by zexin123** [labring/sealos#2531]
### Detailed description of the question.

运行命令，安装sealos   运行命令报   无法执行二进制文件: 可执行文件格式错误  。
 wget https://github.com/labring/sealos/releases/download/v4.1.4/sealos_4.1.4_linux_arm64.tar.gz \
   && tar zxvf sealos_4.1.4_linux_arm64.tar.gz sealos && chmod +x sealos && mv sealos /usr/bin

系统信息
操作系统：银河麒麟 4.19.90-52.14.v2207.a.ky10.loongarch64
芯片：龙芯
4.19.90-52.14.v2207.a.ky10.loongarch64 #1 SMP Sat Nov 19 15:31:31 CST 2022 loongarch64 loongarch64 loongarch64 GNU/Linux

![image](https://user-images.githubusercontent.com/30694740/217703758-0b9b2302-d3a9-4bf4-adeb-22bed7b72b95.png)

是没法支持以上操作系统吗？需要自己构建吗

**Comment by cuisongliu** [comment]
本地执行 arch 
file sealos

**Comment by zexin123** [comment]
> 本地执行 arch file sealos
![image](https://user-images.githubusercontent.com/30694740/217707741-1658bc41-9901-40f0-9956-edda49f36b49.png)

**Comment by cuisongliu** [comment]
先执行arch 再执行file sealos

**Comment by zexin123** [comment]
> file sealos
还是报无法执行
![image](https://user-images.githubusercontent.com/30694740/217712685-20d96258-d828-4ba4-bda4-1861262fb287.png)

**Comment by cuisongliu** [comment]
麒麟应该是不支持标准ARM 再机器上编译把

**Comment by zexin123** [comment]
> 麒麟应该是不支持标准ARM 再机器上编译把
这个吗？请问下    这句     arm64 环境下需要添加 :arm64 后缀。   是加在哪里
![image](https://user-images.githubusercontent.com/30694740/217763603-48b4a2db-f0e9-48bb-abb7-53caac69af07.png)
