### ISSUE TITLE
coredns镜像用的是registry.k8s.io域名下？

### ISSUE THREAD

**Issue by SpringHgui** [labring/sealos#2539]
### Detailed description of the question.

集群创建时没问题，能正常启动`coreDns`，但遇到手动销毁`coreDns`的pod之后，无法启动成功了，查看事件发现是镜像拉取失败

**Comment by cuisongliu** [comment]
How to reproduce, the mirror address has not changed, and the registry has cached a copy.

**Comment by SpringHgui** [comment]
也许是当磁盘不足时，触发垃圾回收，镜像被清理，当pod被销毁后，并没有自动拉起成功，失败原因是镜像拉取失败导致pod无法启动

**Comment by fanux** [comment]
镜像会被缓存到 sealos 的私有镜像仓库中，理论上机器上的被删除了也会自动从私有镜像仓库中拉取
