### ISSUE TITLE
构建时候报错，可能什么原因

### ISSUE THREAD

**Issue by zexin123** [labring/sealos#2544]
运行命令
git clone https://github.com/labring/sealos.git
cd sealos
GOARCH=arm64 make build BINS=sealos

报错
 Building binary sealos v4.1.5.alpha2.dirty for linux_arm64
 github.com/labring/sealos/pkg/client-go/kubernetes
pkg/client-go/kubernetes/healthy.go:88:29: undefined: url.JoinPath
note: module requires Go 1.20
 runtime/cgo
gcc_arm64.S: Assembler messages:
gcc_arm64.S:28: 致命错误：no match insn: stp    x29,x30,[sp,
make[1]: *** [scripts/make-rules/golang.mk:60：go.build.linux_arm64.sealos] 错误 2
make: *** [Makefile:58：build] 错误 2**

**Comment by fanux** [comment]
如果在 mac 上 需要装个虚拟机，可以参考这个：https://github.com/labring/sealos/blob/main/DEVELOPGUIDE.md#example-how-to-build-sealos-on-macosarm64-using-multipass

**Comment by cuisongliu** [comment]
只支持Linux编译
