### ISSUE TITLE
树莓派(Raspberry Pi)4上执行单节点安装报错

### ISSUE THREAD

**Issue by baozitao** [labring/sealos#2559]
### Sealos Version

{"gitVersion":"4.1.4","gitCommit":"bf121904","buildDate":"2023-01-06T08:51:53Z","goVersion":"go1.19.4","compiler":"gc","platform":"linux/arm64"}

### How to reproduce the bug?

执行安装命令
sealos run labring/kubernetes:v1.25.0 labring/calico:v3.24.1 --single

### What do you see instead?

kubeadm join apiserver.cluster.local:6443 --token <value withheld> \
	--discovery-token-ca-cert-hash sha256:cebee7de1220e4d3a062474240c71adfc3cd60117481143564f2cefcc4a42c0a
2023-02-12T23:22:55 info Executing pipeline Join in CreateProcessor.
2023-02-12T23:22:55 info start to get kubernetes token...
2023-02-12T23:22:59 info Executing pipeline RunGuest in CreateProcessor.
namespace/tigera-operator created
bash: line 1: helm: command not found
**2023-02-12T23:22:59 error Applied to cluster error: exit status 127**
Error: exit status 127
exit status 127

### Operating environment

```markdown
- Sealos version:4.1.4
- containerd version:v1.6.16 
- Kubernetes version:1.25.0
- Operating system:ubuntu 22.04 for Raspberry Pi
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by lingdie** [comment]
try to run cmd
> sealos run labring/kubernetes:v1.25.0 labring/calico:v3.24.1 labring/helm:v3.10.3 --single
