### ISSUE TITLE
Proposal: predefine a directory to store configuration file like kubeadm, kubelet configs

### ISSUE THREAD

**Issue by fengxsong** [labring/sealos#2562]
### Create the respective sealos cluster image distribution

1. predefine a directory name, like `init-configs` or whatever, in sealos's code base;
2. place customized kubeadm/kubelet/kubeproxy config files in it, and build a customized cluster image from the official image.
3. run `sealos apply` with the newly built cluster image without providing kubernetes's related config files, `sealos` will automatically merge those files into the default kubeadmConfigs.

**Comment by fengxsong** [comment]
cc @cuisongliu

**Comment by cuisongliu** [comment]
That's right, I think the directory is kubeadm or directly defined in the etc/kubeadm.yaml configuration.
