### ISSUE TITLE
安装好后，coredns无法启动

### ISSUE THREAD

**Issue by wanghesir** [labring/sealos#2568]
### Detailed description of the question.

sealos 版本4.1.4
使用的自定义安装配置，配置文件见附件
[Clusterfile.txt](https://github.com/labring/sealos/files/10720262/Clusterfile.txt)
安装成功了，但是coredns显示CrashLoopBackOff，看coredns的log是“networ: plugin type=calico failed (add): cannot find a qualified ippool”，
请帮忙是哪里配置有误吗，什么原因导致的？谢谢

### Some reference materials you see.

https://www.sealos.io/zh-Hans/docs/getting-started/customize-cluster

**Comment by fanux** [comment]
What is the kubernetes image version?

**Comment by wanghesir** [comment]
- labring/kubernetes-docker:v1.26.1
  - labring/helm:v3.11.0
  - labring/calico:v3.25.0

**Comment by wanghesir** [comment]
> What is the kubernetes image version?
labring/kubernetes-docker:v1.26.1
labring/helm:v3.11.0
labring/calico:v3.25.0
