### ISSUE TITLE
BUG: image-cri-shim 报错http: non-successful response

### ISSUE THREAD

**Issue by ziggy7** [labring/sealos#2575]
### Sealos Version

v4.1.4

### How to reproduce the bug?

莫名其妙出现，相同版本的sealos和离线镜像，一开始可以成功

### What is the expected behavior?

成功搭建集群

### What do you see instead?

sealos run报错
E0214 10:16:36.398531   15259 remote_image.go:222] "PullImage from image service failed" err="rpc error: code = Unknown desc = Error response from daemon: Gio/v2/\": dial tcp: lookup k8s.gcr.io on [::1]:53: read udp [::1]:56218->[::1]:53: read: connection refused" image="k8s.gcr.io/pause:3.8"
FATA[0000] pulling image: rpc error: code = Unknown desc = Error response from daemon: Get "https://k8s.gcr.io/v2/": dial tcp: lookup k8s.gcr.io on [::1]:538->[::1]:53: read: connection refused 
2023-02-14T10:16:36 error Applied to cluster error: failed to init exec auth.sh failed exit status 1
Error: failed to init exec auth.sh failed exit status 1
failed to init exec auth.sh failed exit status 1

systemctl status image-cri-shim.service
● image-cri-shim.service - image-cri-shim
   Loaded: loaded (/etc/systemd/system/image-cri-shim.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2023-02-14 10:16:28 CST; 19min ago
 Main PID: 14815 (image-cri-shim)
    Tasks: 20
   Memory: 32.1M
   CGroup: /system.slice/image-cri-shim.service
           └─14815 /usr/bin/image-cri-shim -f /etc/image-cri-shim.yaml

Feb 14 10:16:28 node1 image-cri-shim[14815]: 2023-02-14T10:16:28 info Username: admin
Feb 14 10:16:28 node1 image-cri-shim[14815]: 2023-02-14T10:16:28 info Password: passw0rd
Feb 14 10:16:28 node1 image-cri-shim[14815]: 2023-02-14T10:16:28 info CRIVersion: v1alpha2
Feb 14 10:16:28 node1 image-cri-shim[14815]: 2023-02-14T10:16:28 info socket info shim: /var/run/image-cri-shim.sock ,image: /var/run/cri-dockerd.sock, registry: http://sealos.hub:5000
Feb 14 10:16:28 node1 image-cri-shim[14815]: 2023-02-14T10:16:28 info Finding the CRI API image version
Feb 14 10:16:28 node1 image-cri-shim[14815]: 2023-02-14T10:16:28 info changed ownership of socket "/var/run/image-cri-shim.sock" to root/root
Feb 14 10:16:28 node1 image-cri-shim[14815]: 2023-02-14T10:16:28 info changed permissions of socket "/var/run/image-cri-shim.sock" to -rw-rw----
Feb 14 10:16:36 node1 image-cri-shim[14815]: 2023-02-14T10:16:36 info actual imageName: pause:3.8
Feb 14 10:16:36 node1 image-cri-shim[14815]: 2023-02-14T10:16:36 warn list tag for pause error: Get "http://sealos.hub:5000/v2/pause/tags/list": http: non-successful response (status=404 body="{\"errors\":[{\"code\":\"NAME_UNKNOWN\",\"message\":\"repository name not known to registry\",\"detail\":{\"name\":\"pause\"}}]}\n")
Feb 14 10:16:36 node1 image-cri-shim[14815]: 2023-02-14T10:16:36 info image: k8s.gcr.io/pause:3.8, newImage: k8s.gcr.io/pause:3.8, action: PullImage

### Operating environment

```markdown
- Sealos version:v4.1.4
- Docker version:
- Kubernetes version:
- Operating system:centos7
- Runtime environment:
- Cluster size:
- Additional information:
```

### Additional information

试了4.1.4和4.1.5的sealos，以及1.24和1.25的k8s，试了docker和containerd的k8s，都是报这个错误

**Comment by ziggy7** [comment]
[root@node1 ~]# docker images
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE
[root@node1 ~]# docker ps -a
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

**Comment by ziggy7** [comment]
[root@node1 ~]#  cat /etc/containers/registries.conf
unqualified-search-registries = ["docker.io"]

[[registry]]
prefix = "docker.io/labring"
location = "docker.io/labring"

**Comment by ziggy7** [comment]
相同版本的sealos和镜像，另一台机器也可以sealos run成功

**Comment by lingdie** [comment]
网络问题？
可以尝试使用sealos registry `hub.sealos.cn`
e.g:
> sealos run hub.sealos.cn/labring/kubernetes:v1.25

部分镜像尚未同步，如果出现类似
```initializing source docker://hub.sealos.cn/labring/kubernetes:v1.25: reading manifest v1.25 in hub.sealos.cn/labring/kubernetes: manifest unknown: manifest unknown```
错误可以提issue并@我

**Comment by ziggy7** [comment]
使用的离线镜像包在内网装的，应该不是网络问题，之前都可以成功

**Comment by muicoder** [comment]
Error: failed to init exec auth.sh failed exit status 1

**Comment by lingdie** [comment]
> Error: failed to init exec auth.sh failed exit status 1

看着像是registry的问题？

**Comment by muicoder** [comment]
```
systemctl status registry
```
看看registry

**Comment by ziggy7** [comment]
> systemctl status registry

[root@node1 ~]# systemctl status registry
● registry.service - registry: The sealos registry
   Loaded: loaded (/etc/systemd/system/registry.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2023-02-14 11:01:54 CST; 3s ago
     Docs: https://www.sealos.io/docs/Intro
  Process: 28452 ExecStart=/usr/bin/registry serve /etc/registry/registry_config.yml (code=exited, status=1/FAILURE)
 Main PID: 28452 (code=exited, status=1/FAILURE)

Feb 14 11:01:54 node1 systemd[1]: Unit registry.service entered failed state.
Feb 14 11:01:54 node1 systemd[1]: registry.service failed.

**Comment by lingdie** [comment]
registry没起来，主机的5000端口又被占用过没？

**Comment by ziggy7** [comment]
没被占用过，不过我sealos reset之后，kill掉了在5000 LISTEN的registry，然后sealos run，就成功了

**Comment by cuisongliu** [comment]
> > systemctl status registry
> 
> [root@node1 ~]# systemctl status registry ● registry.service - registry: The sealos registry Loaded: loaded (/etc/systemd/system/registry.service; enabled; vendor preset: disabled) Active: activating (auto-restart) (Result: exit-code) since Tue 2023-02-14 11:01:54 CST; 3s ago Docs: https://www.sealos.io/docs/Intro Process: 28452 ExecStart=/usr/bin/registry serve /etc/registry/registry_config.yml (code=exited, status=1/FAILURE) Main PID: 28452 (code=exited, status=1/FAILURE)
> 
> Feb 14 11:01:54 node1 systemd[1]: Unit registry.service entered failed state. Feb 14 11:01:54 node1 systemd[1]: registry.service failed.

ls /var/lib/registry 看看有内容不

**Comment by ziggy7** [comment]
问题已解决

> 没被占用过，不过我sealos reset之后，kill掉了在5000 LISTEN的registry，然后sealos run，就成功了

**Comment by ziggy7** [comment]
刚刚run完再reset又出现了这个问题，还是以相同的方式解决了

> 没被占用过，不过我sealos reset之后，kill掉了在5000 LISTEN的registry，然后sealos run，就成功了

**Comment by lingdie** [comment]
> 刚刚run完再reset又出现了这个问题，还是以相同的方式解决了
> 
> > 没被占用过，不过我sealos reset之后，kill掉了在5000 LISTEN的registry，然后sealos run，就成功了

有reset的log没？我尝试复现下

**Comment by muicoder** [comment]
```
systemctl stop containerd
```
手动运行一下，应该是reset最后stop没成功吧

**Comment by ziggy7** [comment]
> > 刚刚run完再reset又出现了这个问题，还是以相同的方式解决了
> > > 没被占用过，不过我sealos reset之后，kill掉了在5000 LISTEN的registry，然后sealos run，就成功了
> 
> 有reset的log没？我尝试复现下

是.sealos/logs/sealos.log吗，我看了下好像没什么问题

**Comment by lingdie** [comment]
ok
