### ISSUE TITLE
Question: switch to `registry.k8s.io`

### ISSUE THREAD

**Issue by lingdie** [labring/sealos#2576]
### Detailed description of the question.

`k8s.gcr.io` Image Registry Will Be Frozen From the 3rd of April 2023
We need to switch k8s cluster image to `registry.k8s.io` ?

Ref to: https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/

**Comment by cuisongliu** [comment]
We don't need to care about these, we don't care about any mirror warehouse image-shim will handle it for you.
