### ISSUE TITLE
BUG: kubesphere安装失败

### ISSUE THREAD

**Issue by ziggy7** [labring/sealos#2584]
### Sealos Version

v4.1.4

### How to reproduce the bug?

sealos run labring/kubernetes-docker: v1.25 labring/calico:v3.24.1 labring/openebs:v1.9.0  labring/metrics-server:v0.6.2 --single
安装成功，然后
sealos run registry.cn-shenzhen.aliyuncs.com/cnmirror/kubesphere:v3.3.1

### What do you see instead?

[root@master ~]# kubectl get pod -n kubesphere-system
NAME                                    READY   STATUS             RESTARTS      AGE
ks-apiserver-5f7b5dcd4c-822ql           0/1     CrashLoopBackOff   1 (10s ago)   4m30s
ks-console-6f59755f65-nf25q             1/1     Running            0             4m30s
ks-controller-manager-5cc5fd674-bf8rv   1/1     Running            0             4m30s
ks-installer-75d4fb4d65-vpcmp           1/1     Running            0             6m12s

[root@master ~]# kubectl logs ks-apiserver-5f7b5dcd4c-822ql  -n kubesphere-system
W0214 16:28:57.672720       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0214 16:28:57.673945       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0214 16:28:57.681188       1 options.go:191] ks-apiserver starts without redis provided, it will use in memory cache. This may cause inconsistencies when running ks-apiserver with multiple replicas.
I0214 16:28:57.681229       1 interface.go:50] start helm repo informer
I0214 16:28:57.867392       1 apiserver.go:417] Start cache objects
Error: failed to fetch group version resources batch/v1beta1: the server could not find the requested resource
2023/02/14 16:28:57 failed to fetch group version resources batch/v1beta1: the server could not find the requested resource

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

### Additional information

3个月前装kubesphere3.3.0时候没遇过这个问题，试了几个最近更新的k8s镜像与3.3.0/3.3.1，都是k8s集群可以安装成功，kubesphere安装报这个错误

**Comment by ziggy7** [comment]
> 这个镜像是sealos 打包的集群镜像吗

是的
<img width="604" alt="image" src="https://user-images.githubusercontent.com/52338997/218683955-a88be021-93bb-4f21-8b83-8cf40047c5ac.png">

**Comment by cuisongliu** [comment]
版本不兼容把 1.25 的api 和老版本不大兼容，可以降低一下k8s版本试试。

**Comment by cuisongliu** [comment]
看样子是sealctl 在arm 上的编译问题。

**Comment by ziggy7** [comment]
> 版本不兼容把 1.25 的api 和老版本不大兼容，可以降低一下k8s版本试试。

换1.24可以了
