### ISSUE TITLE
sealos gen生成的Clusterfile没有修改containerd容器的配置

### ISSUE THREAD

**Issue by chenshengshi** [labring/sealos#2585]
### What is the problem this feature will solve?

![image](https://user-images.githubusercontent.com/43060901/218720881-54e7ed32-7a3b-402a-be46-b70971d442c1.png)

用sealos命令指定--root 路径也不行 
Clusterfile没有修改containerd容器的配置

**Comment by cuisongliu** [comment]
需要使用环境变量渲染 --env criData

**Comment by cuisongliu** [comment]
去除命令无用参数。

**Comment by cuisongliu** [comment]
@fengxsong
