### ISSUE TITLE
sealos run 一个集群报错

### ISSUE THREAD

**Issue by chenshengshi** [labring/sealos#2586]
### Sealos Version

4.1.4

### How to reproduce the bug?

执行命令
sealos run --cluster-root=/data/sealos/ --env criData=/data/cri/lib/containerd labring/kubernetes:v1.26.1-4.1.4 labring/calico:v3.25.0 \
     --masters 192.168.1.2 \
     --nodes 192.168.1.3,192.168.1.4 --passwd css

W0214 19:37:56.275711   15036 initconfiguration.go:305] error unmarshaling configuration schema.GroupVersionKind{Group:"kubeproxy.config.k8s.io", Version:"v1alpha1", Kind:"KubeProxyConfiguration"}: strict decoding error: unknown field "udpIdleTimeout"
W0214 19:37:56.278071   15036 configset.go:177] error unmarshaling configuration schema.GroupVersionKind{Group:"kubeproxy.config.k8s.io", Version:"v1alpha1", Kind:"KubeProxyConfiguration"}: strict decoding error: unknown field "udpIdleTimeout"
W0214 19:37:56.284137   15036 initconfiguration.go:119] Usage of CRI endpoints without URL scheme is deprecated and can cause kubelet errors in the future. Automatically prepending scheme "unix" to the "criSocket" with value "/run/containerd/containerd.sock". Please update your configuration!
W0214 19:37:56.284419   15036 utils.go:69] The recommended value for "healthzBindAddress" in "KubeletConfiguration" is: 127.0.0.1; the provided value is: 0.0.0.0
[init] Using Kubernetes version: v1.26.1
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'

[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Using existing apiserver-kubelet-client certificate and key on disk
[certs] Using existing front-proxy-ca certificate authority
[certs] Using existing front-proxy-client certificate and key on disk
[certs] Using existing etcd/ca certificate authority
[certs] Using existing etcd/server certificate and key on disk
[certs] Using existing etcd/peer certificate and key on disk
[certs] Using existing etcd/healthcheck-client certificate and key on disk
[certs] Using existing apiserver-etcd-client certificate and key on disk
[certs] Using the existing "sa" key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/admin.conf"
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/kubelet.conf"
W0214 19:38:40.602686   15036 kubeconfig.go:264] a kubeconfig file "/etc/kubernetes/controller-manager.conf" exists already but has an unexpected API Server URL: expected: https://192.168.1.2:6443, got: https://apiserver.cluster.local:6443
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/controller-manager.conf"
W0214 19:38:40.905452   15036 kubeconfig.go:264] a kubeconfig file "/etc/kubernetes/scheduler.conf" exists already but has an unexpected API Server URL: expected: https://192.168.1.2:6443, got: https://apiserver.cluster.local:6443
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/scheduler.conf"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s

[kubelet-check] Initial timeout of 40s passed.

Unfortunately, an error has occurred:
        timed out waiting for the condition

This error is likely caused by:
        - The kubelet is not running
        - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
        - 'systemctl status kubelet'
        - 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI.
Here is one example how you may list all running Kubernetes containers by using crictl:
        - 'crictl --runtime-endpoint unix:///run/containerd/containerd.sock ps -a | grep kube | grep -v pause'
        Once you have found the failing container, you can inspect its logs with:
        - 'crictl --runtime-endpoint unix:///run/containerd/containerd.sock logs CONTAINERID'
error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher
2023-02-14T19:42:41 error Applied to cluster error: failed to init init master0 failed, error: exit status 1. Please clean and reinstall
Error: failed to init init master0 failed, error: exit status 1. Please clean and reinstall
failed to init init master0 failed, error: exit status 1. Please clean and reinstall
root@debain2:~#

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cuisongliu** [comment]
看一下kubelet的日志

**Comment by chenshengshi** [comment]
bain2 kubelet[24886]: E0214 20:30:17.992856   24886 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-scheduler\" with Cr>
Feb 14 20:30:17 debain2 kubelet[24886]: I0214 20:30:17.991764   24886 scope.go:115] "RemoveContainer" containerID="13dabd618dbc8ae32c13b6221c28ed9e1fe4aaf443bcc1f4caf5d89b7751c020"
Feb 14 20:30:17 debain2 kubelet[24886]: E0214 20:30:17.786235   24886 controller.go:146] failed to ensure lease exists, will retry in 7s, error: Get "https://apiserver.cluster.local:64>
Feb 14 20:30:15 debain2 kubelet[24886]: E0214 20:30:15.263100   24886 eviction_manager.go:261] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"deba>
Feb 14 20:30:14 debain2 kubelet[24886]: E0214 20:30:14.916396   24886 event.go:276] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.Object>
Feb 14 20:30:13 debain2 kubelet[24886]: E0214 20:30:13.631073   24886 reflector.go:140] vendor/k8s.io/client-go/informers/factory.go:150: Failed to watch *v1.Node: failed to list *v1.N>
Feb 14 20:30:13 debain2 kubelet[24886]: W0214 20:30:13.630753   24886 reflector.go:424] vendor/k8s.io/client-go/informers/factory.go:150: failed to list *v1.Node: Get "https://apiserve>
Feb 14 20:30:12 debain2 kubelet[24886]: E0214 20:30:12.994598   24886 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-controller-manager\>
Feb 14 20:30:12 debain2 kubelet[24886]: I0214 20:30:12.993970   24886 scope.go:115] "RemoveContainer" containerID="3bf79ad3fa7477363a666a9818f4219d8dee219d9d82ff598b8139783d2c9a7b"
Feb 14 20:30:11 debain2 kubelet[24886]: E0214 20:30:11.729037   24886 certificate_manager.go:471] kubernetes.io/kube-apiserver-client-kubelet: Failed while requesting a signed certific>
Feb 14 20:30:11 debain2 kubelet[24886]: E0214 20:30:11.141606   24886 kubelet_node_status.go:92] "Unable to register node with API server" err="Post \"https://apiserver.cluster.local:6>
Feb 14 20:30:11 debain2 kubelet[24886]: I0214 20:30:11.139314   24886 kubelet_node_status.go:70] "Attempting to register node" node="debain2"
Feb 14 20:30:10 debain2 kubelet[24886]: E0214 20:30:10.777805   24886 controller.go:146] failed to ensure lease exists, will retry in 7s, error: Get "https://apiserver.cluster.local:64>
Feb 14 20:30:08 debain2 kubelet[24886]: E0214 20:30:08.001522   24886 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-apiserver\" with Cr>
Feb 14 20:30:07 debain2 kubelet[24886]: I0214 20:30:07.999207   24886 scope.go:115] "RemoveContainer" containerID="4a42259a08793418e5b4c508f13148e6a76afe5790466cd63ac18486baae37f8"
Feb 14 20:30:06 debain2 kubelet[24886]: E0214 20:30:06.993842   24886 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-scheduler\" with Cr>
Feb 14 20:30:06 debain2 kubelet[24886]: I0214 20:30:06.992829   24886 scope.go:115] "RemoveContainer" containerID="13dabd618dbc8ae32c13b6221c28ed9e1fe4aaf443bcc1f4caf5d89b7751c020"
Feb 14 20:30:05 debain2 kubelet[24886]: E0214 20:30:05.218690   24886 eviction_manager.go:261] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"deba>
Feb 14 20:30:04 debain2 kubelet[24886]: E0214 20:30:04.752723   24886 event.go:276] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.Object>
Feb 14 20:30:04 debain2 kubelet[24886]: E0214 20:30:04.134905   24886 kubelet_node_status.go:92] "Unable to register node with API server" err="Post \"https://apiserver.cluster.local:6>
Feb 14 20:30:04 debain2 kubelet[24886]: I0214 20:30:04.133307   24886 kubelet_node_status.go:70] "Attempting to register node" node="debain2"
Feb 14 20:30:03 debain2 kubelet[24886]: E0214 20:30:03.774940   24886 controller.go:146] failed to ensure lease exists, will retry in 7s, error: Get "https://apiserver.cluster.local:64>
Feb 14 20:29:59 debain2 kubelet[24886]: E0214 20:29:59.990558   24886 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-controller-manager\>
Feb 14 20:29:59 debain2 kubelet[24886]: I0214 20:29:59.989899   24886 scope.go:115] "RemoveContainer" containerID="3bf79ad3fa7477363a666a9818f4219d8dee219d9d82ff598b8139783d2c9a7b"
Feb 14 20:29:57 debain2 kubelet[24886]: E0214 20:29:57.121553   24886 kubelet_node_status.go:92] "Unable to register node with API server" err="Post \"https://apiserver.cluster.local:6>
Feb 14 20:29:57 debain2 kubelet[24886]: I0214 20:29:57.119413   24886 kubelet_node_status.go:70] "Attempting to register node" node="debain2"
Feb 14 20:29:56 debain2 kubelet[24886]: E0214 20:29:56.953018   24886 reflector.go:140] vendor/k8s.io/client-go/informers/factory.go:150: Failed to watch *v1.CSIDriver: failed to list >
Feb 14 20:29:56 debain2 kubelet[24886]: W0214 20:29:56.952854   24886 reflector.go:424] vendor/k8s.io/client-go/informers/factory.go:150: failed to list *v1.CSIDriver: Get "https://api>
Feb 14 20:29:56 debain2 kubelet[24886]: E0214 20:29:56.771878   24886 controller.go:146] failed to ensure lease exists, will retry in 7s, error: Get "https://apiserver.cluster.local:64>
Feb 14 20:29:56 debain2 kubelet[24886]: E0214 20:29:56.225515   24886 reflector.go:140] vendor/k8s.io/client-go/informers/factory.go:150: Failed to watch *v1.RuntimeClass: failed to li>
Feb 14 20:29:56 debain2 kubelet[24886]: W0214 20:29:56.225365   24886 reflector.go:424] vendor/k8s.io/client-go/informers/factory.go:150: failed to list *v1.RuntimeClass: Get "https://>
Feb 14 20:29:55 debain2 kubelet[24886]: E0214 20:29:55.215900   24886 eviction_manager.go:261] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"deba>
Feb 14 20:29:54 debain2 kubelet[24886]: E0214 20:29:54.992999   24886 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-scheduler\" with Cr>
Feb 14 20:29:54 debain2 kubelet[24886]: I0214 20:29:54.990957   24886 scope.go:115] "RemoveContainer" containerID="13dabd618dbc8ae32c13b6221c28ed9e1fe4aaf443bcc1f4caf5d89b7751c020"
Feb 14 20:29:54 debain2 kubelet[24886]: E0214 20:29:54.751028   24886 event.go:276] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.Object>
Feb 14 20:29:53 debain2 kubelet[24886]: E0214 20:29:53.994291   24886 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-apiserver\" with Cr>
Feb 14 20:29:53 debain2 kubelet[24886]: I0214 20:29:53.991361   24886 scope.go:115] "RemoveContainer" containerID="4a42259a08793418e5b4c508f13148e6a76afe5790466cd63ac18486baae37f8"
Feb 14 20:29:50 debain2 kubelet[24886]: E0214 20:29:50.789274   24886 reflector.go:140] vendor/k8s.io/client-go/informers/factory.go:150: Failed to watch *v1.Service: failed to list *v>
Feb 14 20:29:50 debain2 kubelet[24886]: W0214 20:29:50.788503   24886 reflector.go:424] vendor/k8s.io/client-go/informers/factory.go:150: failed to list *v1.Service: Get "https://apise>
Feb 14 20:29:50 debain2 kubelet[24886]: E0214 20:29:50.112082   24886 kubelet_node_status.go:92] "Unable to register node with API server" err="Post \"https://apiserver.cluster.local:6>
Feb 14 20:29:50 debain2 kubelet[24886]: I0214 20:29:50.109751   24886 kubelet_node_status.go:70] "Attempting to register node" node="debain2"

**Comment by cuisongliu** [comment]
有完整日志么，没有有效信息
