### ISSUE TITLE
Question: master0 down掉如何修复

### ISSUE THREAD

**Issue by HereHaveAnPeople** [labring/sealos#2589]
### 多master 高可用问题.

在用sealos 部署多master 集群时， 如果第一个master down 掉。那么也会导致整个k8s集群不可用，请问这个有什么其他的解决方案嘛？

**Comment by lingdie** [comment]
第一个master down掉是指执行`sealos cli`的master吗

**Comment by lingdie** [comment]
或许我们可以在CRD里存一份clusterfile？ @cuisongliu

**Comment by HereHaveAnPeople** [comment]
我部署的时候sealos cli 和 第一个master 是同一台。

**Comment by cuisongliu** [comment]
> 或许我们可以在CRD里存一份clusterfile？ @cuisongliu

1. 安装的时候registry尽量不要放到master0 且 多个副本
2.  clusterfile存储到k8s 然后换节点也可以使用
3. registry挂掉可以随意切节点

这样就可以了。

**Comment by fanux** [comment]
And copy ~/.sealos dir to other masters.

**Comment by HereHaveAnPeople** [comment]
我想问一下：
1. 现在 registry 和 master0 在一起了，这种方式还有用吗？
2. clusterfile 怎么存储到k8s里面，其他的master 怎么配置使用？

**Comment by AEGEGE** [comment]
<img width="1895" alt="image" src="https://github.com/labring/sealos/assets/20395332/51074823-bc54-4bf4-a737-5fb9c8f7c3a7">
我是遇到了这个错误，版本号v4.2.0,手动将/etc/hosts添加到 /etc/kubernetes/manifests/{kube-controller-manager.yaml,kube-scheduler.yaml}解决的。
