### ISSUE TITLE
sealos命令如何升级现有集群版本

### ISSUE THREAD

**Issue by leeloveying** [labring/sealos#2593]
### Detailed description of the question.

sealos命令如何升级现有集群版本？
当前版本：v1.24.0
目标版本：v1.25.0

**Comment by fanux** [comment]
https://www.sealos.io/docs/examples/how-to-upgrade-cluster

**Comment by leeloveying** [comment]
感谢回答
另通过以上方法进行升级时报错，报错信息如下：
error Applied to cluster error: render env to rootfs failed: failed to create template: /var/lib/containers/storage/overlay/eecbe18489396ff42232e2c23f4a80e5944f13b879c8c53b59ea0938cffdffd1/merged/etc/image-cri-shim.yaml.tmpl template: image-cri-shim.yaml.tmpl:21: function "semverCompare" not defined
当前集群环境信息：
sealos版本：{"gitVersion":"4.1.3","gitCommit":"b2ba9705","buildDate":"2022-09-06T06:04:14Z","goVersion":"go1.19","compiler":"gc","platform":"linux/amd64"}
集群版本：labring/kubernetes:v1.24.0 labring/calico:v3.22.1
升级集群版本：labring/kubernetes:v1.25.0
请帮忙看下是什么原因导致？

**Comment by leeloveying** [comment]
> https://www.sealos.io/docs/examples/how-to-upgrade-cluster

以上，请大佬帮忙看下

**Comment by fanux** [comment]
Upgrade the sealos version to v4.1.5-rc1

**Comment by leeloveying** [comment]
补充下sealos版本信息：
SealosVersion:
  buildDate: "2023-02-11T05:20:54Z"
  compiler: gc
  gitCommit: 9a46eafd
  gitVersion: 4.1.5-rc1
  goVersion: go1.20
  platform: linux/amd64

**Comment by leeloveying** [comment]
> Upgrade the sealos version to v4.1.5-rc1

升级后也不行，有好的解决方案吗？

**Comment by james-curtis** [comment]
> > Upgrade the sealos version to v4.1.5-rc1
> 
> 升级后也不行，有好的解决方案吗？

尝试删除 ~/.sealos
