### ISSUE TITLE
Feature: support pod image pull policy with  IfNotPresent

### ISSUE THREAD

**Issue by willzhang** [labring/sealos#2595]
### What is the problem this feature will solve?

k8s pods have `IfNotPresent` image(not cluster application image) pull policy Invalid in the cluster deployed by sealos.

Sealos always goes to public image registry to pull the image, although the image has been manually loaded locally.

**Comment by fanux** [comment]
This is a bug, and already fixed in main. You can tag the image, sealos will not pull again.
