### ISSUE TITLE
Feature: support Print image pull error log during `sealos run cluster`

### ISSUE THREAD

**Issue by willzhang** [labring/sealos#2596]
### What is the problem this feature will solve?

in the first node, let the 5000 port used by another registry.
```
podman run -d -p 5000:5000 registry
```
run cluster
```
sealos run labiring/kubernetes:v1.25.3 --single
```

Sealos will be stuck all the time to pull cluster image,  and sealos don't know that his own registry is not started because 5000 port used by others.

### If you have solution，please describe it

Check whether the registry is alive and throw an error to user before pulling the image.

**Comment by lingdie** [comment]
I have this quitsion before, shell we support user can customize registry port?

**Comment by willzhang** [comment]
if registry down, sealos will pull from registry.k8s.io, This registry is not accessible, just give a error:
```
local registry connect failed, pulling from registry.k8s.io

pulling from registry.k8s.io faild, timeout.

```

**Comment by bxy4543** [comment]
https://github.com/labring-actions/runtime-cache/blob/dac3c56d21ea6d40095d4d10e59f3401cdecb2e3/registry/scripts/init-registry.sh#L26
`check_registry_port_inuse $registryPort` in rootfs registry scripts
