### ISSUE TITLE
Feature: using promptui replace confirm

### ISSUE THREAD

**Issue by cuisongliu** [labring/sealos#2600]
### What is the problem this feature will solve?

https://github.com/manifoldco/promptui/blob/master/_examples/confirm/main.go

**Comment by nowinkeyy** [comment]
Hi @cuisongliu 
I'm interested in this. I want to use `promptui.Select` instead of entering the yes/no string. What do you think?

**Comment by nowinkeyy** [comment]
Or use `promptui.Prompt` to match yes/no strings

**Comment by cuisongliu** [comment]
Very good, you can write some related examples after you realize it.

**Comment by nowinkeyy** [comment]
Hi @cuisongliu 
I wrote an example of `promptui.Prompt`
![image](https://user-images.githubusercontent.com/72536832/234007436-7782bae3-e390-46b9-8263-de1cc7c199a1.png)

**Comment by cuisongliu** [comment]
> Hi @cuisongliu
> I wrote an example of `promptui.Prompt`
> ![image](https://user-images.githubusercontent.com/72536832/234007436-7782bae3-e390-46b9-8263-de1cc7c199a1.png)

This is a good way of writing. Does it work? Can you take a look at the actual interaction effect?
