### ISSUE TITLE
Feature: Disable cloud user list other user's namespaces.

### ISSUE THREAD

**Issue by zzjin** [labring/sealos#2602]
### What is the problem this feature will solve?

Currently, one cloud user can access its own namespace, but can list all other's namespaces.
Will leak user login/register informations.

**Comment by dinoallo** [comment]
Remove `list` here should fix it, but more tests are required.
https://github.com/labring/sealos/blob/5d5e8227a1f781d1c3e3058aff59ba595f803350/controllers/user/controllers/usergroupuserbinding_controller.go#L100
