### ISSUE TITLE
Feature: sealos build support reuse local images

### ISSUE THREAD

**Issue by willzhang** [labring/sealos#2604]
### step 1
```
sealos pull docker.io/labring/nginx:1.23.2
or docker pull docker.io/labring/nginx:1.23.2
```

### step 2
```
echo "docker.io/labring/nginx:1.23.2" > images/shim/nginxImages
```
### step 3
Disconnect public network

### step 4
```
sealos build -t test .
```
sealos will pull docker.io/labring/nginx:1.23.2 all the time from public network, and it will pull failed because i Disconnect public network.

gcr.io or registry.k8s.io , this registry can not access from china. if use docker pull and retag, sealos current not support this method.

it's mean you must be able to access the network outside the wall. or change charts or yaml images registry one by one to registry inside the wall.

### If you have solution，please describe it

there have two storage location :

- /var/lib/containers  【cloud image   && Normal Docker Image】
- ./registry                  【Normal Docker Image】

when sealos build, at pull step, check pull image id， if find in  /var/lib/containers, just save it to  ./registry

**Comment by fengxsong** [comment]
> there have two storage location :

> /var/lib/containers 【cloud image && Normal Docker Image】
> ./registry 【Normal Docker Image】
> when sealos build, at pull step, check pull image id， if find in /var/lib/containers, just save it to ./registry

No, they are not the same thing.

**Comment by cuisongliu** [comment]
sealos pull docker.io/labring/nginx:1.23.2
sealos push sealos.hub:5000/labring/nginx:1.23.2

echo "sealos.hub:5000/labring/nginx:1.23.2" > images/shim/nginxImages

sealos build -t test .
