### ISSUE TITLE
gen失败

### ISSUE THREAD

**Issue by chenshengshi** [labring/sealos#2611]
### Sealos Version

sealos_4.1.5-rc1_linux_amd64.tar.gz

### How to reproduce the bug?

![image](https://user-images.githubusercontent.com/43060901/219560842-307c1ebf-4d85-4df9-8f0f-8231c8905f8b.png)

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cuisongliu** [comment]
fixed by main code
