### ISSUE TITLE
BUG:  ubuntu操作系统 安装 single 集群失败. 

### ISSUE THREAD

**Issue by jihaojie** [labring/sealos#2612]
### Sealos Version

sealos_4.1.4

### How to reproduce the bug?

sealos 版本：
wget  https://github.com/labring/sealos/releases/download/v4.1.4/sealos_4.1.4_linux_amd64.tar.gz  && \
    tar -zxvf sealos_4.1.4_linux_amd64.tar.gz sealos &&  chmod +x sealos && mv sealos /usr/bin

执行的命令:
 sealos run labring/kubernetes-docker:v1.20.5-4.1.4 labring/helm:v3.8.2 labring/calico:v3.24.1      --single 

安装single 集群失败.   报错如下

![image](https://user-images.githubusercontent.com/24754918/219566329-e2423482-acc5-4b33-b7a3-401d6613dbed.png)

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cuisongliu** [comment]
rm -rf .sealos/default/Clusterfile  retry it.
