### ISSUE TITLE
当服务器SSH端口不是22时，sealos scp命令依然连接的22端口

### ISSUE THREAD

**Issue by caibenxiang** [labring/sealos#2615]
### Sealos Version

v4.1.4

### How to reproduce the bug?

![9WQCJNVOD~C_3SZ2CI H%4O](https://user-images.githubusercontent.com/4568241/219828193-e0263536-3faf-4256-9e69-5ab0dd3d4863.png)
在  ~/.sealos/default/Clusterfile 配置文件中，已经写了 192.168.168.6:20022 的连接IP和端口
在正常安装K8S集群的过程中，该设置生效
但是在后面安装flanneld的过程中，当镜像执行到 scp 命令的时候，sealos报错。
报错显示去连接的 192.168.168.6 服务器的22端口，但是我并未设置任何22端口。

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by henryhyang** [comment]
![image](https://user-images.githubusercontent.com/37874767/219852170-4b830121-891e-4a98-8074-c4c5ec144b61.png)
这里要指定自定义端口

**Comment by caibenxiang** [comment]
> ![image](https://user-images.githubusercontent.com/37874767/219852170-4b830121-891e-4a98-8074-c4c5ec144b61.png) 这里要指定自定义端口

试过去改了，依然会连接到22端口

**Comment by lingdie** [comment]
`port` has a default value `22`, see:

https://github.com/lingdie/sealos/blob/67259a9cf5530f4c0465a158b8415a8106ac8b70/pkg/apply/args.go#L54

``

**Comment by lingdie** [comment]
When install, read clusterfile again so that port args not be used.
https://github.com/labring/sealos/blob/c4839d81dfb6b496ab9d37a672921e720fd98741/pkg/apply/processor/install.go#L84
