### ISSUE TITLE
我想用sealos安装k8s docker版本的docker.io/labring/kubernetes-docker:v1.26 

### ISSUE THREAD

**Issue by chenshengshi** [labring/sealos#2619]
### Detailed description of the question.

1、请问一下sealos安装默认是/var/lib/docker目录，我想要修改到/data目录 如何修改Clusterfile呢

**Comment by cuisongliu** [comment]
docker inspect docker.io/labring/kubernetes-docker:v1.26

有环境变量支持修改，运行的时候把环境变量加上就好了。

**Comment by cuisongliu** [comment]
https://github.com/labring/sealos/issues/1732 用法可以参照这个。

**Comment by chenshengshi** [comment]
docker的参数是--env data-root=/data 对么

**Comment by chenshengshi** [comment]
> docker inspect docker.io/labring/kubernetes-docker:v1.26
> 
> 有环境变量支持修改，运行的时候把环境变量加上就好了。


docker的参数是--env data-root=/data 对么
