### ISSUE TITLE
sealos 安装kubespehre 3.3.1

### ISSUE THREAD

**Issue by chenshengshi** [labring/sealos#2621]
### Detailed description of the question.

sealos 4.1.4

ks-apiserver 报错 这个如何解决呢 是啥问题
![image](https://user-images.githubusercontent.com/43060901/220034731-6b6fd1af-fe67-4c48-b2b0-8b049fb92172.png)

**Comment by cuisongliu** [comment]
降低k8s版本。版本不匹配

**Comment by chenshengshi** [comment]
我目前安装的kubernetes-docker1.26

**Comment by cuisongliu** [comment]
得看一下kubespehre 3.3.1 兼容哪个版本
