### ISSUE TITLE
sealos apply -f Clusterfile无法更新apiserver配置

### ISSUE THREAD

**Issue by AEGEGE** [labring/sealos#2622]
### Detailed description of the question.

目前测试的版本是sealos 4.1.4

通过Clusterfile部署完k8s集群，一切正常，在使用一段时间后我想为apiserver增加以下配置
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
networking:
  PodSubnet: 11.233.0.0/16
  ServiceSubnet: 11.234.0.0/22
apiServer:
  extraArgs:
    max-mutating-requests-inflight: '1000'
    max-requests-inflight: '800'
    kubelet-timeout: 5s
    event-ttl: 1h0m0s
    default-watch-cache-size: '1500'
    watch-cache: 'true'

再次使用sealos apply -f Clusterfile发现不会有任何变更，但是如果是初次安装配置是可以载入的

**Comment by cuisongliu** [comment]
这个配置默认是初始化配置的。

**Comment by AEGEGE** [comment]
初始化之后能通过一个统一的配置文件来维护集群状态吗？

**Comment by cuisongliu** [comment]
> 

你是想安装后修改CIDR这类信息么？

**Comment by AEGEGE** [comment]
CIDR一般是不会动的，主要是一下几个配置可能会动

**Comment by cuisongliu** [comment]
> CIDR一般是不会动的，主要是一下几个配置可能会动

k8s 默认是可以修改的，但是需要执行一下修改配置的命令。

**Comment by cuisongliu** [comment]
配置默认生成在.sealos/default/etc/kubeadm-init.yaml

**Comment by AEGEGE** [comment]
下面这些可能会动，这个默认生成的改动k8s这些组件会自动载入吗？
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
etcd:
  ...
apiServer:
  ...
controllerManager:
  ...

apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration

apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration

**Comment by cuisongliu** [comment]
https://github.com/labring/sealos/blob/main/docs/4.0/docs/getting-started/customize-cluster-buildimage.md  
可以修改一下配置 ，初始化执行会自动载入。

**Comment by AEGEGE** [comment]
初始化我是验证过了，确实没问题，跟官方配置一样，我的意思是在运行一段时间，比如节点增加之后，pod数量过多之后集群会报一些错，需要优化apiServer、controllerManager、kubelet等一些配置参数进行调优，这个时候更新template，在执行apply去载入新的配置进行升级

**Comment by cuisongliu** [comment]
> 确实没问题，跟官方配置一样，我的意思是在运行一段时间，比如节点增加之后，pod数量过多之后集群会报一些错，需要优化apiServer、controllerManager、kubelet等一些配置参数进行调优，这个时候更新template，在执行apply去载入新的配置进行升级

这个可能需要后期支持了。暂时是不支持的，要不就是得用原生kubeadm的方式了。

**Comment by AEGEGE** [comment]
好的，目前单独去修改/etc/kubernetes/manifests/下的配置也是可以生效
