### ISSUE TITLE
sealos安装k8s docker指定文件路径 参数是什么呢？

### ISSUE THREAD

**Issue by chenshengshi** [labring/sealos#2625]
### Detailed description of the question.

我Clusterfile文件配置
spec:
  env:
  - dataroot=/data/docker

spec:
  env:
  - data-root=/data/docker 均不生效，要如何指定呢？

----------------------
-criData 这个是指定containerd数据目录 是否有指定docker的数据目录呢

**Comment by cuisongliu** [comment]
inspect一下镜像名称 里面的环境变量对应替换即可。

**Comment by cuisongliu** [comment]
https://github.com/labring-actions/bug-verify/actions/runs/4211974573/jobs/7310676596 看一下这个流水线的clusterfile

**Comment by cuisongliu** [comment]
https://github.com/labring-actions/bug-verify/actions/runs/4228906639/jobs/7344794987  docker的用法可以参照这个。

**Comment by baodelu** [comment]
> https://github.com/labring-actions/bug-verify/actions/runs/4228906639/jobs/7344794987 docker的用法可以参照这个。

这个连接现在不能用了，请问如何解决docker数据存储路径位置的问题，还有如何修改bip
