### ISSUE TITLE
failed to init generator config init kubeadm config error: signal: segmentation fault

### ISSUE THREAD

**Issue by 46797536** [labring/sealos#2646]
### Sealos Version

4.15-rc2，4.15-rc1，4.14

### How to reproduce the bug?

sealos run labring/kubernetes-docker:v1.25-arm64 labring/helm:v3.10.3-arm64 labring/calico:v3.24.5-arm64  --single

### Operating environment

```markdown
- Sealos version:4.15-rc2
- Docker version: 23.0.1
- Kubernetes version: 1.25
- Operating system:麒麟v10
- Runtime environment:64c128G
- Cluster size:1master
- Additional information:
```

**Comment by cuisongliu** [comment]
可能需要自己编译了，我在阿里云上测试没问题，如果可以提供机器可以测一下。

**Comment by 46797536** [comment]
> 可能需要自己编译了，我在阿里云上测试没问题，如果可以提供机器可以测一下。
非常感谢[cuisongliu]，通过使用下面这个镜像临时解决了
docker.io/cuisongliu/k8s-docker:1.25-arm
