### ISSUE TITLE
想问下 desktop 的镜像部署文档在哪呢

### ISSUE THREAD

**Issue by xchenhao** [labring/sealos#2651]
看了文档好像没有找到 desktop 的文档或镜像，想问下 desktop 的镜像部署文档在哪呢？

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by fanux** [comment]
目前我们还没发布镜像哈，后续会发出来。 现在可以先在线体验其是否能满足你的需求。

**Comment by zhangsean** [comment]
桌面操作才是最大亮点呀，没有桌面，命令行就没有优势了
