### ISSUE TITLE
BUG: sealos image command error

### ISSUE THREAD

**Issue by sniperking1234** [labring/sealos#2655]
### Sealos Version

v4.1.4

### How to reproduce the bug?

Run ` sealos login quay.io -u aaa -p bbb`
Then command result is `Error: too many arguments, login takes only 1 argument`

**Comment by cuisongliu** [comment]
sealos login  -u aaa -p bbb  quay.io

**Comment by cuisongliu** [comment]
https://github.com/labring/sealos/blob/b28cf0e3f776329ab41e93ab186cb191c37bfdda/.github/workflows/test_registry.yml#L76

**Comment by sniperking1234** [comment]
https://docs.sealos.io/zh-Hans/docs/design/private-registry#login-to-the-private-registry
文档更新一下吧
