### ISSUE TITLE
Feature: support assign registry role to nodes in `run` commands

### ISSUE THREAD

**Issue by willzhang** [labring/sealos#2671]
### Sealos Version

v4.1.4-rc2

### How to reproduce the bug?

```
sealos run labring/kubernetes:v1.25.6 labring/helm:v3.11.0 labring/calico:v3.24.5 \
--masters 192.168.72.33 \
--registry 192.168.72.34 --single
```

### What is the expected behavior?

sealos run support --registry flag

### What do you see instead?

```
root@node33:~# sealos run labring/kubernetes:v1.25.6 labring/helm:v3.11.0 labring/calico:v3.24.5 --masters 192.168.72.33 --registry 192.168.72.34 --single
Error: unknown flag: --registry
```

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

### Additional information

feature issue: https://github.com/labring/sealos/pull/1963

**Comment by bxy4543** [comment]
I guess it is related to these changes https://github.com/labring/sealos/pull/2096.

**Comment by cuisongliu** [comment]
Need to discuss whether to keep this parameter.

**Comment by willzhang** [comment]
--registrys 192.168.116.135,192.168.116.136

**Comment by cuisongliu** [comment]
Use clusterfile and set role to registry, cmd does not add registry parameters.
