### ISSUE TITLE
部署单master节点时tigera-operator服务一直重启，calico服务没有创建

### ISSUE THREAD

**Issue by 46797536** [labring/sealos#2675]
### Sealos Version

4.15-rc3

### How to reproduce the bug?

sealos run labring/kubernetes-docker:v1.25.6 labring/helm:v3.8.2 labring/calico:v3.24.5 \
--masters 192.168.10.37 --nodes 192.168.10.46,192.168.10.86 

### What do you see instead?

单maste节点带不带--single参数收一样
sealos run labring/kubernetes-docker:v1.25.6 labring/helm:v3.8.2 labring/calico:v3.24.5 \
--masters 192.168.10.37 --nodes 192.168.10.46,192.168.10.86 
![image](https://user-images.githubusercontent.com/46241382/221455170-f4765884-75f0-46fc-9666-053701bd1971.png)

多节点正常
sealos run labring/kubernetes-docker:v1.25.6 labring/helm:v3.8.2 labring/calico:v3.24.5 \
--masters 192.168.10.37,192.168.10.46,192.168.10.86
![image](https://user-images.githubusercontent.com/46241382/221455278-d3e23a8e-cd39-4aab-af25-03cd0ca88f74.png)

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by fanux** [comment]
我看你执行的命令是多节点的？

**Comment by 46797536** [comment]
单maste节点
--masters 192.168.10.37 --nodes 192.168.10.46,192.168.10.86

**Comment by cuisongliu** [comment]
https://github.com/labring-actions/bug-verify/actions/runs/4161615545/jobs/7199803657 我测试rc3是没有问题的，发下你的操作系统架构以及其他信息我们复现一下

**Comment by cuisongliu** [comment]
但是我用的是3.24.1 你换个calico的版本试试
