### ISSUE TITLE
pod网段有没有办法直接通过变量注入就行调整

### ISSUE THREAD

**Issue by 46797536** [labring/sealos#2677]
### What is the problem this feature will solve?

目前只能通过sealos apply -f Clusterfile --values values.yaml方式进行修改
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
networking:
  dnsDomain: {{ default "cluster.local" .Values.networking.dnsDomain }}
  serviceSubnet: {{ default "10.96.0.0/18" .Values.networking.serviceSubnet }}
  podSubnet: {{ default "100.64.0.0/17" .Values.networking.podSubnet }}

这边希望通过变量方式进行调整
sealos run labring/kubernetes-docker:v1.25.6 labring/helm:v3.8.2 labring/calico:v3.24.5 --env podSubnet=xx

**Comment by cuisongliu** [comment]
https://www.sealos.io/docs/getting-started/customize-cluster-buildimage
