### ISSUE TITLE
The newest kubesphere docker images for arm64 platform

### ISSUE THREAD

**Issue by lixinyancici** [labring/sealos#2699]
### Detailed description of the question.

I found that, for the newest kubesphere v3.3.1 or v3.3.2 only have amd64 images, can you upload arm64

**Comment by willzhang** [comment]
code here, need manaul build , github action have no enough disk space error:
https://github.com/labring-actions/cluster-image/tree/main/applications/kubesphere/v3.3.2

sealos build -t kubesphere:v3.3.2 .
