### ISSUE TITLE
Question: apiserver无法启动要怎么处理

### ISSUE THREAD

**Issue by JonChanGit** [labring/sealos#2707]
### Detailed description of the question.

我修改了首个主节点的apiServer的配置后apiserver无法启动，并且在删除这个配置后也未启动apiserver

这个问题要怎么处理

### Some reference materials you see.

sealos 版本 4.1.3

**Comment by JonChanGit** [comment]
我现在出现apiserver负载过高的问题，想咨询下有没有推荐配置

**Comment by cuisongliu** [comment]
根据你负载来的，比如但是master的配置一般都得比较高，尤其是固态硬盘。这里推荐配置无法给出，需要你们的环境才好。不过一般线上环境 4c16g这样 简单跑跑问题不大。
