### ISSUE TITLE
 sealos add nodes failed to copy join node kubeadm config generator config join kubeadm config

### ISSUE THREAD

**Issue by liuhaichaogithub** [labring/sealos#2716]
### Detailed description of the question.

增加节点时报错
![image](https://user-images.githubusercontent.com/40063899/222645735-85468d57-7b28-40c0-b790-f800ca6b3391.png)

node linux log
![image](https://user-images.githubusercontent.com/40063899/222646108-5351f6d4-20ef-4a90-a843-d89b6b7bfd9e.png)

如果节点上有运行的docker与镜像，sealos delete nodes 会把那个机器上的镜像也删掉吗？

**Comment by liuhaichaogithub** [comment]
![image](https://user-images.githubusercontent.com/40063899/222661939-77803404-2cd5-4ca6-9ca0-0b63943a4637.png)

**Comment by cuisongliu** [comment]
本地装了containerd ?

**Comment by cuisongliu** [comment]
本地识别了2个CRI所以报错了。清理干净后重试就好了。
