### ISSUE TITLE
Use `sealos run labring/kubernetes:[version]` to upgrade kubernetes components need some confirm.

### ISSUE THREAD

**Issue by zzjin** [labring/sealos#2719]
When using `sealos run labring/kubernetes` to upgrade a newer major kubernetes version, we need to tell user that some important components may not support new version. 
There seems need to add one confirm to let users accept what may broken.

Some core components list below:
* coredns
* calico
* cri-image-shim
* containerd/cri-dockerd

**Comment by cuisongliu** [comment]
cri-image-shim
containerd/cri-dockerd

**Comment by mond77** [comment]
What's the range of k8s version that we need to consider about? after 1.23 or earlier?

**Comment by zzjin** [comment]
Maybe not hardcoded spec version, but instead always warn user when upgrade kubernetes across minor versions?

**Comment by mond77** [comment]
Yeah. There is no readily available information for hardcoded spec version, and it does take a lot of work to trial and error.And it is not necessarily universal. Just warning user to care about the main components.
