### ISSUE TITLE
ssh免密报错，ssh可以免密登陆，可是sealos报错，无法连接

### ISSUE THREAD

**Issue by baozitao** [labring/sealos#2725]
### Sealos Version

CriVersionInfo:   RuntimeApiVersion: v1   RuntimeName: containerd   RuntimeVersion: v1.6.19   Version: 0.1.0 KubernetesVersionInfo:   clientVersion:     buildDate: "2022-08-23T17:44:59Z"     compiler: gc     gitCommit: a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2     gitTreeState: clean     gitVersion: v1.25.0     goVersion: go1.19     major: "1"     minor: "25"     platform: linux/amd64   kustomizeVersion: v4.5.7   serverVersion:     buildDate: "2022-08-23T17:38:15Z"     compiler: gc     gitCommit: a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2     gitTreeState: clean     gitVersion: v1.25.0     goVersion: go1.19     major: "1"     minor: "25"     platform: linux/amd64 SealosVersion:   buildDate: "2023-03-02T03:58:14Z"   compiler: gc   gitCommit: 8d4e12bd   gitVersion: 4.1.6   goVersion: go1.20.1   platform: linux/amd64

### How to reproduce the bug?

我有三个节点
node1:192.168.8.51
node2:192.168.8.52
node3:192.168.8.53

192.168.8.51已经通过单节点创建了，目前需要在node1上执行命令增加两个节点 
sealos add --nodes 192.168.8.52,192.168.8.53

能够在node1节点上顺利通过ssh免密登陆到 node2、node3,但是sealos 还是报以下错误，连接补上

error Applied to cluster error: failed to run checker: checker: failed to create ssh client, [ssh 192.168.8.52:22]create ssh session failed, ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain

### Operating environment

```markdown
- Sealos version:v4.1.6
- Docker version:crictl version v1.25.0
- Kubernetes version:v1.25.0
- Operating system:ubuntu 20.04
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by KissAngeles** [comment]
兄弟我遇到和你一样的问题，怎么解决的你？

**Comment by cuisongliu** [comment]
要看问题具体排查，一般来说，单机部署后会默认加一个免密登录的配置，可能这个配置并不是你新节点的登录配置。可以尝试升级到4.2.2之后再看一下具体问题。具体问题具体排查，并不是说k8s装不起就换k3s 这不是一个良好的解决问题的思路。

**Comment by baozitao** [comment]
主要是我的使用的生产环境也是国产化，麒麟，老系统，所以资源有限，所以就没有深度研究，应该不是什么大问题，大概率是~/.ssh/isa文件的密钥对不上吧

**Comment by sandy420** [comment]
怎么这个问题石沉大海了呢?Sealos官方的同学出来解答一下呢
