### ISSUE TITLE
BUG: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by svolence** [labring/sealos#2734]
### Sealos Version

v4.1.4/v4.1.6

### How to reproduce the bug?

1.22

Failed to pull image "xxxx" x509: certificate signed by unknown authority

### What is the expected behavior?

pull image success

### Operating environment

```markdown
- Sealos version:v4.1.4/v4.1.6
- Docker version:no
- Kubernetes version:1.22
- Operating system:centos 7.5
- Runtime environment:
- Cluster size:1master2node
- Additional information:
```

**Comment by willzhang** [comment]
what command you run?

**Comment by svolence** [comment]
> 

sealos apply -f clusterfile

**Comment by svolence** [comment]
@willzhang sealos apply -f clusterfile

**Comment by cuisongliu** [comment]
It is best to use the build image method. External docking mirroring may require the basic standard structure of registry.yml.

**Comment by willzhang** [comment]
> @willzhang sealos apply -f clusterfile manual execution `sealos pull image` is normal Using private image, pod pull failed with `x509: certificate signed by unknown authority`

```
sealos run labring/kubernetes:v1.25.6 labring/helm:v3.11.0 labring/calico:v3.24.5
```

ca.crt is harbor ca, and 192.168.10.10 is harbor registry url
```
root@node1:~# containerd -v
containerd github.com/containerd/containerd v1.6.17 299b677800044531671d336af5f0976fd2e6ac70
root@node1:~# 

mkdir -p /etc/containerd/certs.d/192.168.10.10
cp ca.crt /etc/containerd/certs.d/192.168.10.10/ca.crt

```
test with
```
sealos run labring/nerdctl:v1.2.1
nerdctl pull 192.168.10.10/library/xxx:xxx
```

**Comment by cuisongliu** [comment]
> > @willzhang sealos apply -f clusterfile manual execution `sealos pull image` is normal Using private image, pod pull failed with `x509: certificate signed by unknown authority`
> 
> ```
> sealos run labring/kubernetes:v1.25.6 labring/helm:v3.11.0 labring/calico:v3.24.5 --single
> ```
> 
> ca.crt is harbor ca, and 192.168.10.10 is harbor registry url
> 
> ```
> root@node1:~# containerd -v
> containerd github.com/containerd/containerd v1.6.17 299b677800044531671d336af5f0976fd2e6ac70
> root@node1:~# 
> 
> mkdir -p /etc/containerd/certs.d/192.168.10.10
> cp ca.crt /etc/containerd/certs.d/192.168.10.10/ca.crt
> ```
> 
> test with
> 
> ```
> sealos run labring/nerdctl:v1.2.1
> nerdctl pull 192.168.10.10/library/xxx:xxx
> ```

Maybe he meant to go directly to kubelet to harbor to pull the image, not from sealos.hub.

**Comment by svolence** [comment]
> > > @willzhang sealos apply -f clusterfile manual execution `sealos pull image` is normal Using private image, pod pull failed with `x509: certificate signed by unknown authority`
> > 
> > 
> > ```
> > sealos run labring/kubernetes:v1.25.6 labring/helm:v3.11.0 labring/calico:v3.24.5 --single
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ca.crt is harbor ca, and 192.168.10.10 is harbor registry url
> > ```
> > root@node1:~# containerd -v
> > containerd github.com/containerd/containerd v1.6.17 299b677800044531671d336af5f0976fd2e6ac70
> > root@node1:~# 
> > 
> > mkdir -p /etc/containerd/certs.d/192.168.10.10
> > cp ca.crt /etc/containerd/certs.d/192.168.10.10/ca.crt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > test with
> > ```
> > sealos run labring/nerdctl:v1.2.1
> > nerdctl pull 192.168.10.10/library/xxx:xxx
> > ```
> 
> Maybe he meant to go directly to kubelet to harbor to pull the image, not from sealos.hub.

yes, i meant to go directly to kubelet to harbor to pull the image，Manually execute the command `nerdctl pull 192.168.10.10/library/xxx: xxx` is successful

**Comment by cuisongliu** [comment]
Reopen

**Comment by cuisongliu** [comment]
直接registry管理去做， https://github.com/labring/sealos/issues/3138
