### ISSUE TITLE
Feature: Multi-mirror registry support

### ISSUE THREAD

**Issue by cuisongliu** [labring/sealos#2744]
### What is the problem this feature will solve?

```
domain, _, _ := unstructured.NestedString(registryConfig, "domain")
	port, _, _ := unstructured.NestedString(registryConfig, "port")
	username, _, _ := unstructured.NestedString(registryConfig, "username")
	password, _, _ := unstructured.NestedString(registryConfig, "password")
	data, _, _ := unstructured.NestedString(registryConfig, "data")
	ip, _, _ := unstructured.NestedString(registryConfig, "ip")
```

**Comment by cuisongliu** [comment]
镜像不会从多个仓库传输镜像，sealos run的镜像放sealos.hub  其他的比如你有自己的镜像仓库直接接入，后面会有命令支持添加集成外部仓库，目前的配置其实已经支持，只是需要改配置比较繁琐。后面会一起集成一下。

**Comment by kinbod** [comment]
> 镜像不会从多个仓库传输镜像，sealos run的镜像放sealos.hub 其他的比如你有自己的镜像仓库直接接入，后面会有命令支持添加集成外部仓库，目前的配置其实已经支持，只是需要改配置比较繁琐。后面会一起集成一下。

我看有一种mirror的方案，可以轮询下载，设置主机名的多个mirror之后会轮询尝试pull镜像，直到找到可以下载到的，然后还以重写rewrite镜像标签。

**Comment by cuisongliu** [comment]
后面可能需要单独的方案去做这个。搞个同步或者什么的，目前可能先做多镜像支持。后面再一步一步实现。

**Comment by cuisongliu** [comment]
> > 镜像不会从多个仓库传输镜像，sealos run的镜像放sealos.hub 其他的比如你有自己的镜像仓库直接接入，后面会有命令支持添加集成外部仓库，目前的配置其实已经支持，只是需要改配置比较繁琐。后面会一起集成一下。
> 
> 我看有一种mirror的方案，可以轮询下载，设置主机名的多个mirror之后会轮询尝试pull镜像，直到找到可以下载到的，然后还以重写rewrite镜像标签。

有方案的文章什么的么，我可以先了解看一下是否符合预期。

**Comment by kinbod** [comment]
> > > 镜像不会从多个仓库传输镜像，sealos run的镜像放sealos.hub 其他的比如你有自己的镜像仓库直接接入，后面会有命令支持添加集成外部仓库，目前的配置其实已经支持，只是需要改配置比较繁琐。后面会一起集成一下。
> > 
> > 
> > 我看有一种mirror的方案，可以轮询下载，设置主机名的多个mirror之后会轮询尝试pull镜像，直到找到可以下载到的，然后还以重写rewrite镜像标签。
> 
> 有方案的文章什么的么，我可以先了解看一下是否符合预期。

https://docs.rke2.io/zh/install/containerd_registry_configuration

**Comment by cuisongliu** [comment]
> > 后面可能需要单独的方案去做这个。搞个同步或者什么的，目前可能先做多镜像支持。后面再一步一步实现。
> 
> 多镜像源支持吗？？

底层是支持的，只是可能需要改的配置比较多，后面我直接上层命令支持就不需要那么繁琐改了。
