### ISSUE TITLE
BUG: 使用4.1.6版本部署出现的问题

### ISSUE THREAD

**Issue by simamingle** [labring/sealos#2754]
### Sealos Version

4.1.6

### How to reproduce the bug?

![6b7358489afd7d35aaa1ceae9e21cd55](https://user-images.githubusercontent.com/96850542/223704795-368710bb-2c09-4a40-98b4-6b12f5ba6b2a.png)
![554d4fac98f20b7beda0ec7e54f5c758](https://user-images.githubusercontent.com/96850542/223704847-4e83275a-79ef-4792-b3fd-88347dc78852.png)
使用4.1.6版本在欧拉操作系统部署出现的问题

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by fanux** [comment]
提供一下操作系统信息，如何复现。

**Comment by bxy4543** [comment]
Clusterfile 贴下
