### ISSUE TITLE
sealos增加node节点始终报这个错误

### ISSUE THREAD

**Issue by txl7771328** [labring/sealos#2755]
sealos 4.1.3 版本增加node节点始终报以下错误，更换 sealos4.14 版本依旧，不知道哪里出了问题
2023-03-08T22:21:24 info start to install app in this cluster
2023-03-08T22:21:24 info succeeded install app in this cluster: no change apps
2023-03-08T22:21:24 info start to scale this cluster
2023-03-08T22:21:24 info Executing pipeline JoinCheck in ScaleProcessor.
2023-03-08T22:21:24 info checker:hostname [10.0.171.198:22 10.0.70.128:22]
2023-03-08T22:21:24 info checker:timeSync [10.0.171.198:22 10.0.70.128:22]
2023-03-08T22:21:25 info Executing pipeline PreProcess in ScaleProcessor.
2023-03-08T22:21:25 error Applied to cluster error: failed to init runtime, cluster image kubernetes version cannot be empty
2023-03-08T22:21:25 info 
      ___           ___           ___           ___       ___           ___
     /\  \         /\  \         /\  \         /\__\     /\  \         /\  \
    /::\  \       /::\  \       /::\  \       /:/  /    /::\  \       /::\  \
   /:/\ \  \     /:/\:\  \     /:/\:\  \     /:/  /    /:/\:\  \     /:/\ \  \
  _\:\~\ \  \   /::\~\:\  \   /::\~\:\  \   /:/  /    /:/  \:\  \   _\:\~\ \  \
 /\ \:\ \ \__\ /:/\:\ \:\__\ /:/\:\ \:\__\ /:/__/    /:/__/ \:\__\ /\ \:\ \ \__\
 \:\ \:\ \/__/ \:\~\:\ \/__/ \/__\:\/:/  / \:\  \    \:\  \ /:/  / \:\ \:\ \/__/
  \:\ \:\__\    \:\ \:\__\        \::/  /   \:\  \    \:\  /:/  /   \:\ \:\__\
   \:\/:/  /     \:\ \/__/        /:/  /     \:\  \    \:\/:/  /     \:\/:/  /
    \::/  /       \:\__\         /:/  /       \:\__\    \::/  /       \::/  /
     \/__/         \/__/         \/__/         \/__/     \/__/         \/__/

                  Website :https://www.sealos.io/
                  Address :github.com/labring/sealos

**Comment by txl7771328** [comment]
sealos delete 后再 add 问题依旧

**Comment by cuisongliu** [comment]
inspect k8s的镜像，可能镜像版本太低。sealos的检测没过。

**Comment by txl7771328** [comment]
sealos端镜像版本还是新添加的节点镜像版本？ 不应该啊，重来没换过其他镜像版本

**Comment by txl7771328** [comment]
![image](https://user-images.githubusercontent.com/20164763/223894169-3d96ff0c-eb07-4837-a45e-f5a32d69c381.png)

**Comment by txl7771328** [comment]
需要添加的node节点没有镜像
![image](https://user-images.githubusercontent.com/20164763/223894912-141bef0a-990d-47ce-9e2f-507aeb15d02b.png)

**Comment by cuisongliu** [comment]
cluster image kubernetes version cannot be empty .
看一下clusterfile

**Comment by txl7771328** [comment]
![image](https://user-images.githubusercontent.com/20164763/223908276-91671580-73d8-4cec-8627-ceab46f95c09.png)

**Comment by cuisongliu** [comment]
重新搞镜像吧 要不sealos版本回退，高版本需要检测镜像的版本。

sealos inspect kubernete 一下看看

**Comment by cuisongliu** [comment]
写你的镜像名称

**Comment by txl7771328** [comment]
![image](https://user-images.githubusercontent.com/20164763/223972006-59bebab4-5a0d-4db7-839d-71bc87c7e5c0.png)
![image](https://user-images.githubusercontent.com/20164763/223972056-70d7d2b9-b513-4611-a92e-f693728bcfdf.png)

**Comment by cuisongliu** [comment]
应该是你后来运行的镜像错误把当前配置覆盖了。看一下本地有之前运行的clusterfile么

**Comment by txl7771328** [comment]
sealos本机只有这一个
![image](https://user-images.githubusercontent.com/20164763/223973064-1e322a1c-09dd-465d-aae6-eee8ec763823.png)

**Comment by txl7771328** [comment]
![image](https://user-images.githubusercontent.com/20164763/223975623-14582de7-1cdd-4b51-9909-0b6e933deb4f.png)
截图带名字的留言我先删了啊

**Comment by txl7771328** [comment]
我重新用sealos gen生成了一个Clusterfile文件 和我.sealos目录下的文件相同

**Comment by txl7771328** [comment]
新添加的节点做过这个操作，安装kubelet kubeadm docker kubectl，后来都卸载干净了
