### ISSUE TITLE
内网无法使用sealos pull labring/kubernetes:v1.25.0 拉取镜像,能否提供文件下载链接

### ISSUE THREAD

**Issue by ningmingxiao** [labring/sealos#2767]
### What is the problem this feature will solve?

旧版本
 https://sealyun.oss-cn-beijing.aliyuncs.com/7b6af025d4884fdd5cd51a674994359c-1.18.0/kube1.18.0.tar.gz 没法下载了
新的安装方式可以提供镜像的压缩包么?
内网无法使用sealos pull labring/kubernetes:v1.25.0 拉取镜像

**Comment by cuisongliu** [comment]
> https://sealyun.oss-cn-beijing.aliyuncs.com/7b6af025d4884fdd5cd51a674994359c-1.18.0/kube1.18.0.tar.gz

链接:https://pan.baidu.com/s/1fu_l8yL_K6BLpSIugKhvAg?pwd=47f5 提取码:47f5 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by ningmingxiao** [comment]
> > https://sealyun.oss-cn-beijing.aliyuncs.com/7b6af025d4884fdd5cd51a674994359c-1.18.0/kube1.18.0.tar.gz
> 
> 链接:https://pan.baidu.com/s/1fu_l8yL_K6BLpSIugKhvAg?pwd=47f5 提取码:47f5 复制这段内容后打开百度网盘手机App，操作更方便哦
> 
> sealos 3.x 使用旧版本，新版本只能用docker.io的镜像

可以wget下载么? 就像老版本那样
