### ISSUE TITLE
sealos4.1.4版本

### ISSUE THREAD

**Issue by chenshengshi** [labring/sealos#2782]
### Sealos Version

4.1.4

### How to reproduce the bug?

我安装集群的时候出现如下错误 请问如何解决
![1678358828735](https://user-images.githubusercontent.com/43060901/224001584-15adc953-ae6b-451f-ba3e-436759b1163b.png)

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cuisongliu** [comment]
初始化不支持多master，需要升级到4.1.5/4.1.6
