### ISSUE TITLE
sealos apply bug

### ISSUE THREAD

**Issue by chenshengshi** [labring/sealos#2783]
### Sealos Version

4.1.6

### How to reproduce the bug?

首先执行执行
sealos gen --env criData=/data/docker  docker.io/labring/kubernetes-docker:v1.24.9-4.1.3  labring/helm:v3.10.0 labring/calico:v3.25.0   labring/metrics-server:v0.6.2   --masters 192.168.10.140    --nodes 192.168.10.52,192.168.10.8   --passwd VodF3KyLktxSz1X9Vm > Clusterfile
sealos -f Clusterfile

在执行
sealos gen --env criData=/data/docker  docker.io/labring/kubernetes-docker:v1.24.9-4.1.3  labring/helm:v3.10.0 labring/calico:v3.25.0   labring/metrics-server:v0.6.2   --masters 192.168.10.140,192.168.10.212    --nodes 192.168.10.52   --passwd VodF3KyLktxSz1X9Vm > Clusterfile

发现：
主节点新增了 ，node节点未删除

手动删除
提示
Error: parameter error: to delete node IP 192.168.10.8:22 must in cluster IP list

![image](https://user-images.githubusercontent.com/43060901/224026675-4ed100af-11ef-4acd-b979-254973fb0fee.png)
![image](https://user-images.githubusercontent.com/43060901/224026776-f049800d-df96-463c-9141-e714e63ed895.png)

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cuisongliu** [comment]
https://github.com/labring/sealos/pull/2759 修复了，等后面发4.1.7吧。
