### ISSUE TITLE
BUG: image-shim request registry link did not break, resulting in a large number of links

### ISSUE THREAD

**Issue by dundun9** [labring/sealos#2784]
### Sealos Version

v4.1.4

### How to reproduce the bug?

查看cri-shim到registry的链接数量
![image](https://user-images.githubusercontent.com/50027289/224037539-ed8d2d81-5b6c-4a24-a9b9-4830e86d1994.png)
![image](https://user-images.githubusercontent.com/50027289/224037570-74492aff-dddb-4c41-ba7b-5d09ba980aa6.png)

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by Riverdd** [comment]
我也遇到了同样的问题，请教一下，有什么临时的解决方案吗？

**Comment by bxy4543** [comment]
temporary solution: systemctl restart image-cri-shim.service

**Comment by Riverdd** [comment]
thx.
