### ISSUE TITLE
Feature: One command to nuke everything about sealos in a standalone single-node cluster.

### ISSUE THREAD

**Issue by zimtsui** [labring/sealos#2788]
### What is the problem this feature will solve?

After host IP address of a standalone single-node cluster changes (e.g. a laptop computer connects to another WIFI), `sealos reset` doesn't work.

That's because IP setting in `~/.sealos/default/Clusterfile` remains the old one.

![image](https://user-images.githubusercontent.com/31283202/224247768-c3374d2e-323e-4bc6-a73b-b9f2ee4d6254.png)

The `192.168.3.97` in the screenshot is the former IP address.

### What alternatives have you considered?

Manually modify the IP setting to new IP in `~/.sealos/default/Clusterfile`, and then `sealos reset`.

**Comment by cuisongliu** [comment]
maybe modify ~/.sealos/default/Clusterfile is better, add flag --single to reset is not  better solution/
