### ISSUE TITLE
Question: sealos build 缓存的镜像不是期望的镜像

### ISSUE THREAD

**Issue by cnfzh66** [labring/sealos#2800]
### Detailed description of the question.

sealos build 获取的镜像始终是chart包里面默认的values文件的镜像，不是prod.values.yaml里面指定覆盖的镜像
[root@k8s-node01 redis]# tree .
.
├── charts
│   ├── prod.values.yaml
│   └── redis-4.0.4.tgz
└── Kubefile
[root@k8s-node01 redis]# cat Kubefile 
FROM scratch
LABEL VERSION="4.0.4"
COPY . .
CMD ["helm -n middleware upgrade --install -f charts/prod.values.yaml redis charts/redis-4.0.4.tgz --create-namespace"]

prod.values.yaml的内容:
.......................................
replicaCount: 1
image: sealos.hub:5000/library/redis
tag: 4.0.4
pullPolicy: IfNotPresent
.......................................

chart包里面默认的values.yaml的tag是4.0.14
[root@k8s-node01 redis]# sealos build -t redis:4.0.14 .
2023-03-14T10:20:05 info lookup in path /data/kubefile/redis/charts
2023-03-14T10:20:05 info sub chart is redis-4.0.4.tgz
Pulling image: sealos.hub:5000/library/redis:4.0.14
Error: failed to save images: save domain sealos.hub:5000 image sealos.hub:5000/library/redis:4.0.14: get library/redis tag descriptor error: unknown tag=4.0.14, try "sealos login" if you are using a private registry

请问要怎么调整？？

### Some reference materials you see.

sealos version: 4.1.6

**Comment by cnfzh66** [comment]
[root@k8s-node01 charts]# helm template -f prod.values.yaml redis redis-4.0.4.tgz --debug
........................................
      containers:
        - name: redis
          image: sealos.hub:5000/library/redis:4.0.4
          imagePullPolicy: "IfNotPresent"
........................................

**Comment by fengxsong** [comment]
please check out [custom-values](https://docs.sealos.io/docs/build-cloud-image/build-cloudImage-with-helm-charts#custom-valuesyaml) section.

**Comment by cnfzh66** [comment]
> please check out [custom-values](https://docs.sealos.io/docs/build-cloud-image/build-cloudImage-with-helm-charts#custom-valuesyaml) section.

[root@k8s-node01 charts]# helm template -f prod.values.yaml redis redis-4.0.4.tgz|grep image:
          image: sealos.hub:5000/library/redis:4.0.4

**Comment by fengxsong** [comment]
rename `prod.values.yaml` to `redis.values.yaml`

**Comment by cnfzh66** [comment]
> rename `prod.values.yaml` to `redis.values.yaml`

可以可以
[root@k8s-node01 redis]# sealos build -t redis:4.0.4 .
2023-03-14T11:37:48 info lookup in path /data/kubefile/redis/charts
2023-03-14T11:37:48 info sub chart is redis-4.0.4.tgz
Pulling image: sealos.hub:5000/library/redis:4.0.4
20b27738f9d2: Download complete 
51649e11256b: Download complete 
a1866de57c37: Download complete 
0834f3265b79: Download complete 
bdb837737d3a: Download complete 
ec1fea567e44: Download complete 
c8ffb6a9a5bc: Download complete 
Status: images save success
2023-03-14T11:37:51 info saving images sealos.hub:5000/library/redis:4.0.4
STEP 1/4: FROM scratch
STEP 2/4: LABEL VERSION="4.0.4"
STEP 3/4: COPY . .
STEP 4/4: CMD ["helm -n middleware upgrade --install -f charts/redis.values.yaml redis charts/redis-4.0.4.tgz --create-namespace"]
COMMIT redis:4.0.4
Getting image source signatures
Copying blob ebc88f2fa3c2 done  
Copying config c565169283 done  
Writing manifest to image destination
Storing signatures
--> c565169283f
Successfully tagged localhost/redis:4.0.4
c565169283f55456e0c9c4d33bea84fbfe8e334d04a871ad3bfd6a1d800924dd

[root@k8s-node01 redis]# tree -L 2
.
├── charts
│   ├── redis-4.0.4.tgz
│   └── redis.values.yaml
├── Kubefile
└── registry
    └── docker
