### ISSUE TITLE
BUG: Cannot start offline sealos cluster, due to misleading of offline docs 

### ISSUE THREAD

**Issue by omaidb** [labring/sealos#2801]
### Sealos Version

eg. v4.1.7

### How to reproduce the bug?

1. 环境声明
OS: RHEL8
sealos version 4.1.7 二进制安装
<img width="587" alt="image" src="https://user-images.githubusercontent.com/18365223/224972154-a852da12-8f14-4cf3-8aeb-a00d8925926c.png">

2. 做了哪些配置
刚开的新机器，什么配置都没做

3. 运行了什么命令
```shell
# 下载k8s镜像---官网示例命令
sealos pull labring/kubernetes:v1.25.0
sealos images
# 单机安装--官网给的示例命令
sealos run kuberentes:v1.25.0 --single
```
4. 发生了什么错误
单机安装k8s没有成功。
<img width="985" alt="image" src="https://user-images.githubusercontent.com/18365223/224975513-9cec788d-a58f-4937-a290-625fb5474243.png">

### What is the expected behavior?

预期的行为是正常启动一个k8s单机集群

### What do you see instead?

$sealos run kuberentes:v1.25.0 --single
2023-03-14T18:24:05 info Start to create a new cluster: master [172.16.0.159], worker [], registry 172.16.0.159
2023-03-14T18:24:05 info Executing pipeline Check in CreateProcessor.
2023-03-14T18:24:05 info checker:hostname [172.16.0.159:22]
2023-03-14T18:24:05 info checker:timeSync [172.16.0.159:22]
2023-03-14T18:24:05 info Executing pipeline PreProcess in CreateProcessor.
Resolving "kuberentes" using unqualified-search registries (/etc/containers/registries.conf)
Trying to pull docker.io/library/kuberentes:v1.25.0...
2023-03-14T18:24:09 error Applied to cluster error: initializing source docker://kuberentes:v1.25.0: reading manifest v1.25.0 in docker.io/library/kuberentes: errors:
denied: requested access to the resource is denied
unauthorized: authentication required

Error: initializing source docker://kuberentes:v1.25.0: reading manifest v1.25.0 in docker.io/library/kuberentes: errors:
denied: requested access to the resource is denied
unauthorized: authentication required

### Operating environment

```markdown
- Sealos version: v4.1.7
- Docker version: 未安装
- Kubernetes version: 1.25
- Operating system: rhel8
- Runtime environment: 未指定
- Cluster size: 629 MB
- Additional information: 无
```

### Additional information

我就是按照管网的示例命令想试下如何快速启动一个单机k8s集群，但是失败了

**Comment by cuisongliu** [comment]
sealos run labring/kuberentes:v1.25.0 --single

**Comment by cuisongliu** [comment]
```
# 下载k8s镜像---官网示例命令
sealos pull labring/kubernetes:v1.25.0
sealos images
# 单机安装--官网给的示例命令
sealos run kuberentes:v1.25.0 --single
```

这个文档再那个位置有点问题

**Comment by zzjin** [comment]
> 这个文档再那个位置有点问题

docs/4.0/docs/getting-started/offline-install.md
