### ISSUE TITLE
proposal: grouping all of the sealos's subcommands

### ISSUE THREAD

**Issue by fengxsong** [labring/sealos#2816]
As more and more subcommands are implemented in the `sealos` command, for better understanding of each commands and improving user experience, we might need to group all of those subcommands like what `kubectl` does.

Using module `k8s.io/kubectl/pkg/util/templates` might do that trick

**Comment by fengxsong** [comment]
ping @cuisongliu

**Comment by cuisongliu** [comment]
sealctl
```
addHostsCommandFmt    = "hosts add --ip %s  --domain %s"
	deleteHostsCommandFmt = "hosts delete  --domain %s"
	hostnameCommandFmt    = "hostname"
	tokenCommandFmt       = "token"
	cGroupCommandFmt      = "cri cgroup-driver --short"
	socketCommandFmt      = "cri socket"
```
