### ISSUE TITLE
为什么我的config配置不生效

### ISSUE THREAD

**Issue by AEGEGE** [labring/sealos#2827]
### Detailed description of the question.

我在Clusterfile中添加了下列配置，在部署后containerd的root目录没有改变，能指导一下正确的配置方法吗？
`---
apiVersion: apps.sealos.io/v1beta1
kind: Config
metadata:
  name: containerd-config
spec:
  strategy: override
  path: etc/config.toml
  data: |
    version = 2
    root = "/data/containerd"
    state = "/run/containerd"
    oom_score = 0

    [grpc]
      address = "/run/containerd/containerd.sock"
      uid = 0
      gid = 0
      max_recv_message_size = 16777216
      max_send_message_size = 16777216

    [debug]
      address = "/run/containerd/containerd-debug.sock"
      uid = 0
      gid = 0
      level = "warn"

    [timeouts]
      "io.containerd.timeout.shim.cleanup" = "5s"
      "io.containerd.timeout.shim.load" = "5s"
      "io.containerd.timeout.shim.shutdown" = "3s"
      "io.containerd.timeout.task.state" = "2s"

    [plugins]
      [plugins."io.containerd.grpc.v1.cri"]
        sandbox_image = "sealos.hub:5000/pause:3.6"
        max_container_log_line_size = -1
        max_concurrent_downloads = 20
        [plugins."io.containerd.grpc.v1.cri".containerd]
          snapshotter = "overlayfs"
          default_runtime_name = "runc"
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
              runtime_type = "io.containerd.runc.v2"
              runtime_engine = ""
              runtime_root = ""
              [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
                SystemdCgroup = true
                __options__
        [plugins."io.containerd.grpc.v1.cri".registry]
          config_path = "/etc/containerd/certs.d"
          [plugins."io.containerd.grpc.v1.cri".registry.configs]
              [plugins."io.containerd.grpc.v1.cri".registry.configs."sealos.hub:5000".auth]
                username = "__username__"
                password = "__password__"
`

**Comment by cuisongliu** [comment]
这个是个模板，可能得覆盖模板，直接覆盖这个配置可能不管用，最好重新做镜像最好。

**Comment by AEGEGE** [comment]
官网给的介绍是第一次运行的时候添加就行
```
More use cases
We can use this mechanism to customize images already built OR customize some component's config without rebuild it. For example, adding custom containerd configuration.

add Config in Clusterfile before first run.
```

**Comment by fengxsong** [comment]
override file `etc/config.toml.tmpl`

**Comment by AEGEGE** [comment]
> override file `etc/config.toml.tmpl`

好使

**Comment by AEGEGE** [comment]
https://docs.sealos.io/zh-Hans/docs/cli/customize-config
这个地址下的配置指引也建议改一下吧

**Comment by wanhebin** [comment]
> > override file `etc/config.toml.tmpl`
> 
> 好使

请问， etc/config.toml.tmpl 文件是默认就存在，还是需要把Clusterfile复制并改名为 config.toml.tmpl ？
因为我在 `.sealos/default/etc` 目录下并没有发现这个文件。
