### ISSUE TITLE
sealos 安装kubesphere失败

### ISSUE THREAD

**Issue by chenshengshi** [labring/sealos#2828]
### Detailed description of the question.
![image](https://user-images.githubusercontent.com/43060901/225819347-ac3aecb0-9209-4e49-b252-30dbb74e3954.png)

![image](https://user-images.githubusercontent.com/43060901/225819831-78f4486c-885b-49e8-a3a2-d070d255d636.png)

![image](https://user-images.githubusercontent.com/43060901/225819006-cd81ad94-3377-4b17-8f60-d0af1be59287.png)

检查apiservice 
![image](https://user-images.githubusercontent.com/43060901/225819081-98c5e55a-ac53-4cfb-ae66-da69e9323960.png)

请问这个怎么解决呢

sealos版本 4.1.7  集群v1.24.9-4.1.3 calio v3.25.0

**Comment by cuisongliu** [comment]
The kubesphere version is compatible. Maybe this version is not simple to correspond to k8s.
