### ISSUE TITLE
Feature: Add a check for the expected state of a non-odd master

### ISSUE THREAD

**Issue by bxy4543** [labring/sealos#2829]
### What is the problem this feature will solve?

#2605  ： A non-odd number of masters can easily lead to etcd errors, so add a check for a non-odd number of masters.
Add a check for the expected state of a non-odd master:

add non-add master checker in host_checker.go like: [checkTimeSync](https://github.com/labring/sealos/blob/af1bae9b54c75c6ef54c3334b935a83d7cabd8e0/pkg/checker/host_checker.go#L47)

**Comment by pixeldin** [comment]
Maybe I can try this out, can you assign it to me?
