### ISSUE TITLE
Failed to create user

### ISSUE THREAD

**Issue by fenggolang** [labring/sealos#2837]
### What is the problem this feature will solve?

<img width="1736" alt="image" src="https://user-images.githubusercontent.com/16982786/226272410-67bc3ce5-c63f-4056-b9a2-c33e27f3c249.png">

**Comment by zzjin** [comment]
You are trying to test on a design doc page: [/docs/4.0/docs/design/user.md](https://sealos.io/docs/design/user) , which are design introduction doc, not by hand working code.
If you want to apply a User CRD, you must install user controller first. [Readme.md](https://github.com/labring/sealos/tree/main/controllers/user)
