### ISSUE TITLE
Feature: Refactoring Sealos to Support k3s, k0s Runtime

### ISSUE THREAD

**Issue by cubxxw** [labring/sealos#2863]
## Problem Description

Sealos currently does not support the k3s runtime and requires the redesign of the runtime interface to avoid excessive coupling with the Processor and to add verification.

Here is a record of [testing various k3s installation methods](https://docker.nsddd.top/Cloud-Native-k8s/15.html). If you're curious about k3s, be sure to read [this note](https://docker.nsddd.top/Cloud-Native-k8s/14.html), as well as k3s • **[official](https://www.rancher.cn/k3s/) and [documentation](https://docs.rancher.cn/)**, and its GitHub • **[open source address](https://github.com/k3s-io/k3s/)**.

<br>

#### Design a new runtime interface

Redesign the runtime interface to avoid excessive coupling with the Processor and add verification.

#### Design ideas for the k3s runtime module

To support the k3s runtime, we need to add a new runtime module. This module needs to support the following functions:

+ Execute k3s installation commands
+ Execute k3s upgrade commands
+ Execute k3s uninstall commands

#### Design the k3s directory and filesystem distribution using Sealos' image distribution logic

To support the k3s runtime, we need to use Sealos' image distribution logic to design the k3s directory and filesystem distribution of the k3s image.

#### Optimize the packaging of kubeadm and k3s binaries

To support the k3s runtime, we need to optimize the packaging of kubeadm and k3s binaries.

#### Provide unit test and CI flow to ensure code quality

To ensure code quality, we need to provide unit testing and CI flow.

<br>

## Tasks

| Type          | Improvements                                                 | Issue        | PR    | Status |
| ------------- | ------------------------------------------------------------ | ------------ | ----- | ------ |
| 🚀 Feature     | Design a new runtime interface to avoid excessive coupling with the Processor and add verification | #1943, #2037 |  #3741,#3691     | ✅      |
| 🔨 Enhancement | Implement the k3s runtime module to support k3s installation, upgrade, and uninstall commands |              |       | ❌      |
| 🔧 Maintenance | Design the k3s directory and filesystem distribution using Sealos' image distribution logic |              |       | ❌      |
| 👌 Refactoring | Optimize the packaging of kubeadm and k3s binaries           |              |       | ❌      |
| 🧪 Testing     | Provide unit testing and CI flow to ensure code quality      |              |       | ❌      |
| 📈 Metrics     | Compare k3s and k0s, as well as Kubernetes for various changes in sealos, for users to choose according to their scenarios |              |       | ❌      |
| 🎯 Fix         | The current logic of sealos run will parse the environment variable $, which inevitably needs to be fixed. | #2861        | #2862 | ✅      |

**Comment by cuisongliu** [comment]
repen

**Comment by cuisongliu** [comment]
```
type serviceType int

const (
	openRC serviceType = iota
	systemd
)

const systemdTpl = `
[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
Wants=network-online.target
After=network-online.target

[Install]
WantedBy=multi-user.target

[Service]
Type=notify
EnvironmentFile=-/etc/default/%N
EnvironmentFile=-/etc/sysconfig/%N
EnvironmentFile=-{{ .envFile }}
KillMode=process
Delegate=yes
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
ExecStartPre=/bin/sh -xc '! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service'
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart={{ .binDir }}/k3s {{ .exec }}
`

const openRCTpl = `
#!/sbin/openrc-run

LOG_FILE=/var/log/k3s.log

depend() {
    after network-online
    want cgroups
}

start_pre() {
    rm -f /tmp/k3s.*
}

supervisor=supervise-daemon
name=k3s
command="{{ .binDir }}/k3s"
command_args={{ .exec }}

output_log=${LOG_FILE}
error_log=${LOG_FILE}

pidfile="/var/run/k3s.pid"
respawn_delay=5
respawn_max=0

set -o allexport
if [ -f /etc/environment ]; then . /etc/environment; fi
if [ -f {{ .envFile }} ]; then . {{ .envFile }}; fi
set +o allexport
`

```

**Comment by cuisongliu** [comment]
using sealos v4.4.0+
