### ISSUE TITLE
如何在不影响集群正常运行情况下，将私服默认地址master0迁移至云私服仓库

### ISSUE THREAD

**Issue by yuanfeifan** [labring/sealos#2868]
### Detailed description of the question.

目的想解决私服仓库**master0单节点**问题，想将sealos.hub:5000这个私服地址由默认master0地址切换至类似nexus私服仓库，需要改哪些配置呢。麻烦sealos大佬给解答下。

**Comment by yuanfeifan** [comment]
> 

现在有个问题是这样的，我将master0宕机后，在其它的master做新增、删除节点的操作（sealos add/delete）,都会去校验master0的ssh，由于宕机，会出现错误
![9JI{AUZXPB_S2KT30PP FUA](https://user-images.githubusercontent.com/40484831/227895467-274ddbbd-48f0-4203-ae69-336358de0d07.png)，有什么办法规避掉必须校验master0的ssh没

**Comment by cuisongliu** [comment]
可能需要切换master0才行，得备份.sealos目录

**Comment by yuanfeifan** [comment]
> 
如何切换master0呢   麻烦给点相关资料学习下呗

**Comment by cuisongliu** [comment]
1. 备份.sealos拷贝到其他节点
2. 修改Clusterfile的master0节点
3. 迁移/var/lib/sealos目录到对应节点
4. 并把registry的软链迁移过去。

**Comment by yuanfeifan** [comment]
> 1. 备份.sealos拷贝到其他节点
> 2. 修改Clusterfile的master0节点
> 3. 迁移/var/lib/sealos目录到对应节点
> 4. 并把registry的软链迁移过去。



> 1. 备份.sealos拷贝到其他节点
> 2. 修改Clusterfile的master0节点
> 3. 迁移/var/lib/sealos目录到对应节点
> 4. 并把registry的软链迁移过去。

master0切换到新的节点，并将registry软连接过去，使用密码登录新节点的registry，验证失败了。请教下这种情况怎么解决呢

**Comment by yuanfeifan** [comment]
> > > 1. 备份.sealos拷贝到其他节点
> > > 2. 修改Clusterfile的master0节点
> > > 3. 迁移/var/lib/sealos目录到对应节点
> > > 4. 并把registry的软链迁移过去。
> > 
> > 
> > > 1. 备份.sealos拷贝到其他节点
> > > 2. 修改Clusterfile的master0节点
> > > 3. 迁移/var/lib/sealos目录到对应节点
> > > 4. 并把registry的软链迁移过去。
> > 
> > 
> > master0切换到新的节点，并将registry软连接过去，使用密码登录新节点的registry，验证失败了。请教下这种情况怎么解决呢
> 
> hosts修改了吗

修改了的   指向本机IP的仓库

**Comment by cuisongliu** [comment]
registry启动了么
