### ISSUE TITLE
Question: Failed to execute test file normally

### ISSUE THREAD

**Issue by LZiHaN** [labring/sealos#2870]
### Detailed description of the question.

I can't run the unit test properly, the following problem occurs.
`[root@VM-4-10-centos apply]# go test -v utils.go args.go utils_test.go -test.run TestPreProcessIPList
go build github.com/proglottis/gpgme:
# pkg-config --cflags  -- gpgme
Package gpgme was not found in the pkg-config search path.
Perhaps you should add the directory containing `gpgme.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gpgme', required by 'virtual:world', not found
pkg-config: exit status 1
go build github.com/containers/storage/pkg/devicemapper:
# pkg-config --cflags  -- devmapper
Package devmapper was not found in the pkg-config search path.
Perhaps you should add the directory containing `devmapper.pc'
to the PKG_CONFIG_PATH environment variable
Package 'devmapper', required by 'virtual:world', not found
pkg-config: exit status 1
# github.com/containers/storage/drivers/btrfs
/home/gopath/pkg/mod/github.com/containers/storage@v1.45.4/drivers/btrfs/btrfs.go:12:10: fatal error: btrfs/ioctl.h: No such file or directory
 #include <btrfs/ioctl.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
FAIL    command-line-arguments [build failed]
FAIL`
`[root@VM-4-10-centos apply]# cat /etc/centos-release
CentOS Linux release 8.5.2111`

**Comment by cuisongliu** [comment]
brew install gpgme
