### ISSUE TITLE
contained运行没有docker请问node节点拉取docker.io的image失败

### ISSUE THREAD

**Issue by wangcaijie** [labring/sealos#2874]
### Detailed description of the question.

Failed to pull image "wangcaijie/speedsmart:v1.0": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/wang

Normal   Scheduled  50m                  default-scheduler  Successfully assigned zhkt/speedsmart-7ddb6d79b-zwpgs to master
  Warning  Failed     2m40s                kubelet            Failed to pull image "wangcaijie/speedsmart:v1.0": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/wangcaijie/speedsmart:v1.0": failed to copy: read tcp 172.16.30.11:60982->104.18.125.25:443: read: connection reset by peer
  Warning  Failed     2m40s                kubelet            Error: ErrImagePull
  Normal   BackOff    2m38s                kubelet            Back-off pulling image "wangcaijie/speedsmart:v1.0"
  Warning  Failed     2m38s                kubelet            Error: ImagePullBackOff
  Normal   Pulling    2m27s (x2 over 50m)  kubelet            Pulling image "wangcaijie/speedsmart:v1.0"

wangcaijie/speedsmart:v1.0 在dockerhub上面  docker可以拉取
版本：kubernetes:v1.25.0
docker：无
sealos4 搭建

**Comment by cubxxw** [comment]
Can you describe in more detail, such as how you install sealos, how you pull image commands, or yaml files?

**Comment by cuisongliu** [comment]
need login ?  https://github.com/labring/sealos/issues/2826 same this ?
