### ISSUE TITLE
使用sealos部署k8s在内网出现错误，未成功

### ISSUE THREAD

**Issue by chengdakeai** [labring/sealos#2877]
### Detailed description of the question.

我有ABC台服务器已经是k8s集群，并且是kubeadm启动的。但是我现在把这个k8s集群卸载，并使用sealos启动集群。
sealos run docker.io/labring/kubernetes:v1.25.0 docker.io/labring/helm:v3.8.2 docker.io/labring/calico:v3.24.5 --masters 10.253.17.22 --nodes 10.253.17.23,10.253.17.24 -p 123456 
sealos是4.1.7 ，并且我在vmware虚拟机上安装好多次均可以成功！但是现在出现问题了。
 
`W0329 15:03:04.067200   46208 strict.go:47] unknown configuration schema.GroupVersionKind{Group:"kubeadm.k8s.io", Version:"v1beta3", Kind:"InitConfiguration"} for scheme definitions in "k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/scheme/scheme.go:31" and "k8s.io/kubernetes/cmd/kubeadm/app/componentconfigs/scheme.go:28"
no kind "InitConfiguration" is registered for version "kubeadm.k8s.io/v1beta3" in scheme "k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/scheme/scheme.go:31"
To see the stack trace of this error execute with --v=5 or higher
2023-03-29T15:03:04 error Applied to cluster error: failed to init init master0 failed, error: exit status 1. Please clean and reinstall
Error: failed to init init master0 failed, error: exit status 1. Please clean and reinstall
`

**Comment by cuisongliu** [comment]
--debug 执行一下 大概率是cgroup的问题

**Comment by chengdakeai** [comment]
`I0329 17:00:19.466210    1978 initconfiguration.go:246] loading configuration from "/root/.sealos/default/etc/kubeadm-init.yaml"
W0329 17:00:19.467553    1978 strict.go:47] unknown configuration schema.GroupVersionKind{Group:"kubeadm.k8s.io", Version:"v1beta3", Kind:"InitConfiguration"} for scheme definitions in "k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/scheme/scheme.go:31" and "k8s.io/kubernetes/cmd/kubeadm/app/componentconfigs/scheme.go:28"
no kind "InitConfiguration" is registered for version "kubeadm.k8s.io/v1beta3" in scheme "k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/scheme/scheme.go:31"
2023-03-29T17:00:19 error Applied to cluster error: failed to init init master0 failed, error: exit status 1. Please clean and reinstall
2023-03-29T17:00:19 debug write cluster file to local storage: /root/.sealos/default/Clusterfile
Error: failed to init init master0 failed, error: exit status 1. Please clean and reinstall
`  还是这种问题

**Comment by cuisongliu** [comment]
sealos run  --masters 10.253.17.22 --nodes 10.253.17.23,10.253.17.24 -p 123456 --debug  docker.io/labring/kubernetes:v1.25.0 docker.io/labring/helm:v3.8.2 docker.io/labring/calico:v3.24.5

**Comment by chengdakeai** [comment]
`I0330 10:11:37.617264   65426 initconfiguration.go:246] loading configuration from "/root/.sealos/default/etc/kubeadm-init.yaml"
W0330 10:11:37.619087   65426 strict.go:54] error unmarshaling configuration schema.GroupVersionKind{Group:"kubelet.config.k8s.io", Version:"v1beta1", Kind:"KubeletConfiguration"}: error unmarshaling JSON: while decoding JSON: json: unknown field "localStorageCapacityIsolation"
W0330 10:11:37.619538   65426 strict.go:54] error unmarshaling configuration schema.GroupVersionKind{Group:"kubeproxy.config.k8s.io", Version:"v1alpha1", Kind:"KubeProxyConfiguration"}: error unmarshaling JSON: while decoding JSON: json: unknown field "detectLocal"
W0330 10:11:37.619563   65426 strict.go:47] unknown configuration schema.GroupVersionKind{Group:"kubeadm.k8s.io", Version:"v1beta3", Kind:"InitConfiguration"} for scheme definitions in "k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/scheme/scheme.go:31" and "k8s.io/kubernetes/cmd/kubeadm/app/componentconfigs/scheme.go:28"
no kind "InitConfiguration" is registered for version "kubeadm.k8s.io/v1beta3" in scheme "k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/scheme/scheme.go:31"
2023-03-30T10:11:37 error Applied to cluster error: failed to init init master0 failed, error: exit status 1. Please clean and reinstall
2023-03-30T10:11:37 debug write cluster file to local storage: /root/.sealos/default/Clusterfile
Error: failed to init init master0 failed, error: exit status 1. Please clean and reinstall
` 还是这样的问题，囧

**Comment by cuisongliu** [comment]
能贴一下完整日志么。。。。

**Comment by bxy4543** [comment]
Maybe the original cluster was not cleaned up. How about reinstalling after using sealos reset?

**Comment by chengdakeai** [comment]
我已经sealos reset了但是还没成功，我放弃了。但是有大哥把这个部署好了，我准备去问问他
