### ISSUE TITLE
非ROOT下指定用户sealos安装会出错

### ISSUE THREAD

**Issue by eshow** [labring/sealos#2883]
### Detailed description of the question.

sudo sealos run --debug \
  --masters XXX --nodes xxxx -u dev-p ${SEALOSPWD} \
  localhost/labring/kubernetes:v1.23.15 \
  localhost/labring/helm:v3.8.2 \
  localhost/labring/calico:v3.22.1 \
  localhost/labring/coredns:v0.0.1 \
  localhost/labring/openebs:v1.9.0  \
  kubegems/kubegems-stack:v1.23

会出现下列问题：
**error 1:**
 error Applied to cluster error: read admin.conf error in guest: open /root/.sealos/default/etc/admin.conf: no such file or directory
 debug write cluster file to local storage: /root/.sealos/default/Clusterfile
Error: read admin.conf error in guest: open /root/.sealos/default/etc/admin.conf: no such file or directory
read admin.conf error in guest: open /root/.sealos/default/etc/admin.conf: no such file or directory
无法创建admin.conf文件，etc下面的文件都无法创建
**error 2:**
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
Authentication is required to manage system services or units.
Authenticating as: root

已指定-u的参数，仍然使用root用户去认证？

**Comment by cubxxw** [comment]
Does the `-u` dev user have permission?

**Comment by cubxxw** [comment]
@fengxsong

**Comment by fengxsong** [comment]
当前还未支持非root用户安装k8s集群，即通过`-u/--user`指定的用户只能为root。

**Comment by ghostloda** [comment]
> 当前还未支持非root用户安装k8s集群，即通过`-u/--user`指定的用户只能为root。

Hi @fengxsong ，支持非root用户部署k8s,这个功能有计划吗？

**Comment by ghostloda** [comment]
@fengxsong @cuisongliu 我看到有很多支持非root的issue,是否可以把这个问题优先级提高一些呢？只允许root用户部署的话，没有办法在生成环境部署k8s。

**Comment by lllicg** [comment]
> @fengxsong @cuisongliu 我看到有很多需要支持非root的issue,是否可以把这个问题优先级提高一些呢？只允许root用户部署的话，没有办法在生成环境部署k8s。

+1

**Comment by cuisongliu** [comment]
https://github.com/labring/sealos/pull/3421
