### ISSUE TITLE
怎么能重新生成或者导出这个文件

### ISSUE THREAD

**Issue by he-aook** [labring/sealos#2890]
### Detailed description of the question.

/root/.sealos/default/Clusterfile

### Some reference materials you see.

<img width="756" alt="image" src="https://user-images.githubusercontent.com/48249754/229038784-a7406603-07b1-46fd-8b25-e4ef989fbbf5.png">

**Comment by he-aook** [comment]
I accidentally deleted /root/sealos last week and now I need to add nodes, but I can’t add them

**Comment by cubxxw** [comment]
oh, is there any way to restore it other than backup? @cuisongliu

**Comment by he-aook** [comment]
.sealos  all deleted,

**Comment by he-aook** [comment]
就是上面我截图, 我复制了部分进去, 结果添加节点还是失败的

**Comment by he-aook** [comment]
实在不行, 是我们生产环境, 没办法调整

**Comment by cubxxw** [comment]
Can sealos save the Clusterfile file in Kubernetes configmap when installing with kubeadm? @cuisongliu

**Comment by cuisongliu** [comment]
> ### Detailed description of the question.
> /root/.sealos/default/Clusterfile
> 
> ### Some reference materials you see.
> <img alt="image" width="756" src="https://user-images.githubusercontent.com/48249754/229038784-a7406603-07b1-46fd-8b25-e4ef989fbbf5.png">

According to this configuration, the application part is removed, and the content modification can be kept in other positions. This should add node but not master. Pay attention to fill in the corresponding mountPoint

**Comment by cuisongliu** [comment]
> Can sealos save the Clusterfile file in Kubernetes configmap when installing with kubeadm? @cuisongliu

yes. we can save clusterfile to configmap

**Comment by he-aook** [comment]
<img width="1377" alt="image" src="https://user-images.githubusercontent.com/48249754/229078395-df2d4aa8-0b2b-4d06-a231-f2e09fee32b1.png">
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/48249754/229078495-f1181584-7175-40a3-9a7d-6c300b00dbaa.png">
这块不行, 这个路径之前的我不知道, name也没保存, 对不上, 执行就会报错 @cuisongliu

**Comment by he-aook** [comment]
集群的name怎么能读到 ?

**Comment by he-aook** [comment]
<img width="804" alt="image" src="https://user-images.githubusercontent.com/48249754/229356357-a18414cb-458f-4b6f-846c-7b07c9c06289.png">
是我在新的服务器上这样重新运行按照一个集群, 然后把这个文件复制过来, 再继续sealos add --nodes x.x.x.x 吗?

**Comment by he-aook** [comment]
![Uploading image.png…]()
是这个目录下其他启动容器的路径替换一下继续添加node呗?

**Comment by he-aook** [comment]
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/48249754/229458332-03a3f4e3-7c3c-4f62-b9c2-7185c50e4553.png">
尝试了一下不行, 怎么能找到安装的时候这个路径呢, 现在没办法确定 @cuisongliu

**Comment by he-aook** [comment]
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/48249754/229509644-83b87456-56ca-4882-8b66-cc1bfc371064.png">
能找到Kubefile这个路径了, 但还是报错了

**Comment by he-aook** [comment]
已处理,

**Comment by Chris0408** [comment]
> 已处理,

请问下这个问题最终是怎么处理的？我也遇到节点加不进入的类似问题

**Comment by he-aook** [comment]
不好意思, 麻烦明天再描述一下, 今天刚看到邮件
, 我当时是我自己给删掉这个文件了, 晚上更新集群的时候, 发现真个都不能用了, 最后没办法, sealos 从4.0直接升级到4.17版本了,















在 2023-07-11 21:18:05，"Chris Jin" ***@***.***> 写道：

已处理,

请问下这个问题最终是怎么处理的？我也遇到节点加不进入的类似问题

**Comment by he-aook** [comment]
ok
















在 2023-07-11 21:18:05，"Chris Jin" ***@***.***> 写道：

已处理,

请问下这个问题最终是怎么处理的？我也遇到节点加不进入的类似问题
