### ISSUE TITLE
修改kubelet路径后calico csipod不能正常启动

### ISSUE THREAD

**Issue by Nathan7512** [labring/sealos#2898]
### Sealos Version

v4.1.7

### How to reproduce the bug?

1.os：ubuntu 22.04
k8s：kubernetes-docker v1.21
cni：calico v3.24.5
helm： helm v3.11.0
2.修改ClusterFile
![image](https://user-images.githubusercontent.com/44249947/229403692-910c007e-f89b-4002-8c03-2577543036d5.png)
KubeletExtraArgs参数添加 root-dir: /data/kubelet
使用ClusterFile部署集群
3.部署集群后calico csi pod不能正常启动，日志显示该pod在/var/lib/kubelet路径下查找plugin registry目录，但kubelet路径已经移动到/data目录，导致pod不能正常启动。

### What is the expected behavior?

pod能够正常启动

### Operating environment

```markdown
os：ubuntu 22.04
k8s：kubernetes-docker v1.21
cni：calico v3.24.5
helm： helm v3.11.0
```

### Additional information

是否可以修改配置使pod启动时查找路径和kubelet启动参数保持一致？

**Comment by bxy4543** [comment]
need specified [Installation.spec.kubeletVolumePluginPath](https://docs.tigera.io/calico/latest/reference/installation/api#operator.tigera.io/v1.Installation)

**Comment by bxy4543** [comment]
> > need specified [Installation.spec.kubeletVolumePluginPath](https://docs.tigera.io/calico/latest/reference/installation/api#operator.tigera.io/v1.Installation)
> 
> 感谢，我还有一个路径相关的问题。在使用criData变量设置docker路径后，新目录的确存在了docker文件夹，但默认位置/var/lib/docker也存在。请问是否除criData变量外，还需指定其他配置才可以完全移动docker默认路径呢？

应该不需要了
