### ISSUE TITLE
sealos 4.2.0 更新certSANs的疑问

### ISSUE THREAD

**Issue by zhengbucuo888** [labring/sealos#2907]
### Detailed description of the question.

![image](https://user-images.githubusercontent.com/31462232/229683383-2b776c83-a41f-4147-989e-4596f09cbec7.png)
使用sealos cert --alt-names test.test.com更新certSANs，不是所有证书都更新？

**Comment by bxy4543** [comment]
/etc/kubernetes/pki下证书全部都会更新，如果是其他位置的证书暂时不能更新

**Comment by zhengbucuo888** [comment]
这个后续是否考虑支持？

**Comment by zhengbucuo888** [comment]
> /etc/kubernetes/pki下证书全部都会更新，如果是其他位置的证书暂时不能更新
这个后续是否考虑支持？

**Comment by zhengbucuo888** [comment]
这个后续是否考虑支持？

**Comment by bxy4543** [comment]
> 这个后续是否考虑支持？

集群如何安装的呢，提供下配置文件

**Comment by zhengbucuo888** [comment]
> 



> > 这个后续是否考虑支持？
> 
> 集群如何安装的呢，提供下配置文件

正常安装，我就是在测试下sealos4.2的证书更新功能而已。
