### ISSUE TITLE
Feature Rueuest: Add helm binary into terminal ttyd image.

### ISSUE THREAD

**Issue by zzjin** [labring/sealos#2910]
Currently terminal image is only have kubectl and sealos binaries built-in, most of our user also needs helm binary, so pls add helm command.

Refer: https://github.com/cuisongliu/go-docker-dev/blob/master/Dockerfile

Steps:
1. move self host repo files to labring-actions/cluster-image repo
2. add github actions to support auto build docker images.
3. modify Dockerfile to add binaries needed.

**Comment by bxy4543** [comment]
But it is not a cluster image, this is a container image, maybe other repo should be placed.

**Comment by fanux** [comment]
https://github.com/cuisongliu/go-docker-dev/blob/master/Dockerfile maybe this project need to move to terminal subdir.

**Comment by zzjin** [comment]
How about: https://github.com/labring-actions/cluster-image/tree/main/dockerimages this dir?

**Comment by bxy4543** [comment]
> How about: https://github.com/labring-actions/cluster-image/tree/main/dockerimages this dir?

ok

**Comment by cuisongliu** [comment]
https://github.com/labring-actions/cluster-image/actions/runs/4644132502/jobs/8219283514
