### ISSUE TITLE
The metrics server is not working properly

### ISSUE THREAD

**Issue by Nathan7512** [labring/sealos#2912]
### Detailed description of the question.

os: ubuntu22.04
k8s: labring/kubernetes-docker:v1.21
helm: labring/helm:v3.11.0
plugin: labring/metrics-server:v0.6.2

After the cluster deployment is complete, the  `kubectl top pod`  command works fine, but the `kubectl top node` command is not available. The output is **error: metrics not available yet**.
![image](https://user-images.githubusercontent.com/44249947/229987077-cadf0cd8-8620-4e13-badd-e64fbe603db2.png)

**Comment by Nathan7512** [comment]
After manually switching to version 0.4.4, the kubectl top node command can display output, but the memory consumption is 0. I guess it has something to do with the configuration of apiserver or metrics-server, which makes it impossible to get the correct node information, but I'm not sure. [ref https://github.com/kubernetes-sigs/metrics-server/issues/828](https://github.com/kubernetes-sigs/metrics-server/issues/828)

**Comment by Nathan7512** [comment]
![image](https://user-images.githubusercontent.com/44249947/230014435-b2c30923-1a21-4e39-8016-6e4514ce4561.png)

**Comment by Nathan7512** [comment]
After the k8s version is replaced with 1.22, the metrics-server command works normally. Considering it is related to the cgroup version, the ubuntu 22.04 cgroup version is v2.
It is unclear how the low version k8s can avoid this problem on ubuntu22.04. Moreover, it is uncertain whether the different cgroup versions will affect other functions other than metrics-server.
[metrics server ref](https://github.com/kubernetes-sigs/metrics-server/blob/master/KNOWN_ISSUES.md#kubelet-doesnt-report-metrics-for-all-or-subset-of-nodes)

**Comment by fengxsong** [comment]
some cgroup sub drivers are not yet supported in some certain kernel versions.
