### ISSUE TITLE
三个master节点不能高可用

### ISSUE THREAD

**Issue by dixon1983** [labring/sealos#2913]
### Sealos Version

4.1.3

### How to reproduce the bug?

我用A作为master节点安装好了k8s集群，然后又通过add的方式增加了两个master节点B和C，现在发现B或者C挂了，集群不会有问题。但是如果A挂了，整个集群的网络就瘫痪了，从外部无法访问集群。在B或者C上执行kubectl get pods命令,会报apiserver无法访问，必须等到A恢复了，集群才能恢复。是哪里还需要设置么？下图中的ip:248是服务器B
![QQ图片20230405165320](https://user-images.githubusercontent.com/35091088/230032187-8ea54561-fd0e-4844-8416-6a0cd7390499.png)

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by bxy4543** [comment]
看下是不是etcd挂掉了

**Comment by fanux** [comment]
看是否能复现这个问题

**Comment by cuisongliu** [comment]
看一下三个etcd的配置？？？

**Comment by dixon1983** [comment]
这个确认到问题了，就是etcd的配置不对，add的时候没有自动添加三个，得手动添加

**Comment by fanux** [comment]
@dixon1983 @cuisongliu 那就是 sealos 的 bug？

**Comment by cuisongliu** [comment]
确认一下，是不是所有节点etcd 都是master0的地址？如果都是127.0.0.1应该没问题的

**Comment by cuisongliu** [comment]
刚才看了一下代码，代码有问题，可以升级到4.1.7看一下问题还存在不
