### ISSUE TITLE
Question: 服务器重启之后kube-apiserver起不来

### ISSUE THREAD

**Issue by XinuxC** [labring/sealos#2914]
### Detailed description of the question.

服务器重启后kubelet,containerd服务正常,kube-apiserver无法启动,怎么拉起?

The connection to the server apiserver.cluster.local:6443 was refused - did you specify the right host or port?

# crictl ps -a
CONTAINER           IMAGE               CREATED             STATE               NAME                        ATTEMPT             POD ID              POD
57ddd4f47b64f       a8a176a5d5d69       33 seconds ago      Exited              etcd                        24                  0d34b291e38fd       etcd-server-1
b604b8cc7f6b5       4d2edfd10d3e3       3 minutes ago       Exited              kube-apiserver              22                  71afbd3295ecf       kube-apiserver-server-1
277c473e97ac4       1a54c86c03a67       16 minutes ago      Running             kube-controller-manager     3                   355fbc568e5b4       kube-controller-manager-server-1
496967bd231f3       bef2cf3115095       16 minutes ago      Running             kube-scheduler              2                   6b956ad437576       kube-scheduler-server-1
160356f1f93b5       bef2cf3115095       About an hour ago   Exited              kube-scheduler              1                   f794e2796d5cf       kube-scheduler-server-1
83ace9adc8812       1a54c86c03a67       About an hour ago   Exited              kube-controller-manager     2                   738d9773f18fa       kube-controller-manager-server-1
849cd19e01ed2       75392e3500e36       2 days ago          Exited              calico-node                 0                   97d2592894c50       calico-node-sbsbf
5af95d4518923       67fd9ab484510       2 days ago          Exited              install-cni                 0                   97d2592894c50       calico-node-sbsbf
afca8e1b6b3b6       f1bf9f7296b3b       2 days ago          Exited              flexvol-driver              0                   97d2592894c50       calico-node-sbsbf
2e179c2b95576       417ab3368bad1       2 weeks ago         Exited              csi-node-driver-registrar   1                   b725cd8885c5e       csi-node-driver-tmmfh
9f7dc0a6b0ac8       6a8c8f9f60dc6       2 weeks ago         Exited              calico-csi                  1                   b725cd8885c5e       csi-node-driver-tmmfh
867059c4bb12a       5185b96f0becf       2 weeks ago         Exited              coredns                     1                   4c87da783d3af       coredns-565d847f94-98xgt
abcc96c2b3d93       5185b96f0becf       2 weeks ago         Exited              coredns                     1                   703ca80b2da68       coredns-565d847f94-8fpgd
e5a4dee92f4e0       58a9a0c6d96f2       2 weeks ago         Exited              kube-proxy                  1                   9dc76e01f43fc       kube-proxy-8fh4h
55f27080499d8       792ec15461e78       2 weeks ago         Exited              calico-apiserver            1                   018264385a2c2       calico-apiserver-7595b4f4b8-d65rf
170285f3218d8       f9c3c1813269c       2 weeks ago         Exited              calico-kube-controllers     1                   362ae26e02c5f       calico-kube-controllers-85666c5b94-fmzdp

**Comment by xiao-jay** [comment]
可以看一下etc/hosts的内容吗

发自我的iPhone

**Comment by XinuxC** [comment]
> 

192.168.2.201 server-1
192.168.2.202 server-2
192.168.2.203 server-3
192.168.2.201 sealos.hub
192.168.2.201 apiserver.cluster.local

**Comment by xiao-jay** [comment]
那看起来不是这个问题，可以用看一下kubelet状态吗 systemctl status kubelet，请把sealos版本也带上 sealos version


发自我的iPhone

**Comment by XinuxC** [comment]
> systemctl status kubelet

● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since 三 2023-04-05 20:25:14 CST; 27min ago
     Docs: http://kubernetes.io/docs/
  Process: 925 ExecStopPost=/usr/bin/kubelet-post-stop.sh (code=exited, status=0/SUCCESS)
  Process: 1436 ExecStartPre=/usr/bin/kubelet-pre-start.sh (code=exited, status=0/SUCCESS)
 Main PID: 1459 (kubelet)
    Tasks: 14
   Memory: 78.1M
   CGroup: /system.slice/kubelet.service
           └─1459 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/li...

4月 05 20:52:14 server-1 kubelet[1459]: E0405 20:52:14.089416    1459 kubelet.go:2448] "Error getting node" err="node \"server-1\" not found"
4月 05 20:52:14 server-1 kubelet[1459]: E0405 20:52:14.190015    1459 kubelet.go:2448] "Error getting node" err="node \"server-1\" not found"
4月 05 20:52:14 server-1 kubelet[1459]: E0405 20:52:14.260104    1459 file.go:182] "Provided manifest path is a directory, not recursing into man...sts/back"
4月 05 20:52:14 server-1 kubelet[1459]: E0405 20:52:14.290895    1459 kubelet.go:2448] "Error getting node" err="node \"server-1\" not found"
4月 05 20:52:14 server-1 kubelet[1459]: E0405 20:52:14.391848    1459 kubelet.go:2448] "Error getting node" err="node \"server-1\" not found"
4月 05 20:52:14 server-1 kubelet[1459]: E0405 20:52:14.492686    1459 kubelet.go:2448] "Error getting node" err="node \"server-1\" not found"
4月 05 20:52:14 server-1 kubelet[1459]: E0405 20:52:14.593537    1459 kubelet.go:2448] "Error getting node" err="node \"server-1\" not found"
4月 05 20:52:14 server-1 kubelet[1459]: E0405 20:52:14.686582    1459 controller.go:144] failed to ensure lease exists, will retry in 7s, error: ...n refused
4月 05 20:52:14 server-1 kubelet[1459]: E0405 20:52:14.694435    1459 kubelet.go:2448] "Error getting node" err="node \"server-1\" not found"
4月 05 20:52:14 server-1 kubelet[1459]: E0405 20:52:14.716240    1459 event.go:276] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"...Timestamp
Hint: Some lines were ellipsized, use -l to show in full.

sealos version
CriVersionInfo:
  RuntimeApiVersion: v1
  RuntimeName: containerd
  RuntimeVersion: v1.6.19
  Version: 0.1.0
SealosVersion:
  buildDate: "2023-03-02T03:58:14Z"
  compiler: gc
  gitCommit: 8d4e12bd
  gitVersion: 4.1.6
  goVersion: go1.20.1
  platform: linux/amd64

WARNING: Failed to get kubernetes version.
Check kubernetes status or use command "sealos run" to launch kubernetes

**Comment by bxy4543** [comment]
reboot all nodes? etcd exited, you need to restore the etcd state first.

**Comment by XinuxC** [comment]
> reboot all nodes? etcd exited, you need to restore the etcd state first.

yes, I found out the etcd couldn't start up due to missing the snapshot,still working out this problem

**Comment by XinuxC** [comment]
ETCD missing snapshot
