### ISSUE TITLE
Sealos run失败后再次run就会报这个错误

### ISSUE THREAD

**Issue by yinmin2020** [labring/sealos#2916]
### Sealos Version

4.14

### How to reproduce the bug?

1.sealos run XXX镜像
2.因为某些原因没有run成功
3.调整后再次run就报这个错误
4.其实是第二步没run成功后，再次run的话需要执行sealos reset下才可以

### What is the expected behavior?

希望确认下这个问题并修复一下

### What do you see instead?

![e467757c5558647d00e7fa0ca9a86c8](https://user-images.githubusercontent.com/65068467/230332113-982fb837-ffcc-4f73-adfb-b2c0f73ee05f.png)

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by bxy4543** [comment]
新版本没有发现这个问题，可以试试新版本

**Comment by yinmin2020** [comment]
好的 我试试看
