### ISSUE TITLE
Sealos build自定义镜像运行后没有执行CMD里的命令

### ISSUE THREAD

**Issue by yinmin2020** [labring/sealos#2917]
### Sealos Version

4.14

### How to reproduce the bug?

1.构建了含有ingress-nginx的helm集群镜像
2.sealos run使用了single模式（单机）
3.集群拉起后发现COPY进去的helm包是有了 但是没有执行helm install

### What is the expected behavior?

这个没有执行CMD，是不是需要多节点才可以运行CMD里的命令？

### What do you see instead?

![image](https://user-images.githubusercontent.com/65068467/230332986-0e0d799b-2732-473c-88a9-7f5b0b11a9b8.png)
![a041e773af080ab9559c678b8f3260b6](https://user-images.githubusercontent.com/65068467/230333094-ec26391e-3b68-4ff5-8a04-8b82938e8c93.png)
![image](https://user-images.githubusercontent.com/65068467/230333179-3105fe2c-f2f3-4051-91a7-903c9c7ad988.png)

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by bxy4543** [comment]
Change to `FROM scratch`, then build the image with name `customize-image-name`, and execute: `sealos run labring/helm:v3.10.0 kubernetes:v1.25.6 labring/calico:v3.25.0  customize-image-name`
