### ISSUE TITLE
3 node master cannot  high availability

### ISSUE THREAD

**Issue by 17096835560** [labring/sealos#2940]
### Detailed description of the question.

sealos 4.1.7

Installing a 3-node master cluster using sealos，
`sealos run labring/kubernetes:v1.25.0 labring/helm:v3.8.2 labring/calico:v3.24.1 \
     --masters 192.168.10.129,192.168.10.134,192.168.10.131 \
     --nodes 192.168.10.132,192.168.10.133 -p '123456'`
When the master3 shutsdown, the cluster will crash
`kubectl get node -A
Get "https://apiserver.cluster.local:6443/api/v1/nodes?limit=500": dial tcp 192.168.10.129:6443: connect: connection refused - error from a previous attempt: unexpected EOF`

**Comment by bxy4543** [comment]
```
root@jh-node001:~# kubectl get no -owide
NAME         STATUS     ROLES           AGE     VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
jh-node001   Ready      control-plane   19h     v1.25.6   172.30.27.20   <none>        Ubuntu 22.04.1 LTS   5.15.0-58-generic   containerd://1.6.19
jh-node002   NotReady   control-plane   7m11s   v1.25.6   172.30.27.22   <none>        Ubuntu 22.04.1 LTS   5.15.0-58-generic   containerd://1.6.19
jh-node003   Ready      control-plane   6m25s   v1.25.6   172.30.27.21   <none>        Ubuntu 22.04.1 LTS   5.15.0-58-generic   containerd://1.6.19
```

The cluster is still available after disconnecting node002, when one node in a three-node etcd cluster fails, it may cause a state failure due to the potential loss of quorum or network issues.
