### ISSUE TITLE
添加节点是提示机器名重复，删除后仍然会提示

### ISSUE THREAD

**Issue by dixon1983** [labring/sealos#2954]
### Sealos Version

4.1.3

### How to reproduce the bug?

添加节点是提示机器名重复，删除后仍然会提示
![QQ图片20230418124037](https://user-images.githubusercontent.com/35091088/232673575-ee14bb84-8cf7-413d-9d69-704b1fe508c7.png)

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cuisongliu** [comment]
check your hostname all node and add node hostname

**Comment by dixon1983** [comment]
> 已经检查过了，没有重复的，而且add 的node节点，我已经改了hostname，还是会同样的错误

**Comment by cuisongliu** [comment]
add failed node ip is write Clusterfile ??? check your clusterfile ?

**Comment by dixon1983** [comment]
已经找到问题了，是集群里面ingress导致添加的ip映射到master节点的一个虚拟ip了，所以报重复
