### ISSUE TITLE
install k8s  by change registryDomain but certs dirname unchaged on arm64

### ISSUE THREAD

**Issue by DoubleJ213** [labring/sealos#2957]
### Sealos Version

4.1.7

### How to reproduce the bug?

arm64

sealos run --env registryDomain=helloword.hub \
    localhost/labring/kubernetes:v1.25.0-arm64 localhost/labring/helm:v3.8.2-arm64 localhost/labring/calico:v3.25.1-arm64 \
    --single

output :

http: server gave HTTP response to HTTPS client

### What is the expected behavior?

I found the subdir is named sealos.hub:5000 under the directory  /etc/containerd/certs.d/   . which  maybe helloword.hub:5000.

and file  sealos.hub\:5000/hosts.toml  is right.

amd64 no the problem. 

### Operating environment

```markdown
SealosVersion:
  buildDate: "2023-03-10T06:46:42Z"
  compiler: gc
  gitCommit: ed0a75b9
  gitVersion: 4.1.7
  goVersion: go1.20.1
  platform: linux/arm64


images:
localhost/labring/calico:v3.25.1-arm64   864116046a75
localhost/labring/kubernetes:v1.25.0-arm64  c58ca0cb9d3c
localhost/labring/helm:v3.8.2-arm64    fd34b282caa9
```

**Comment by bxy4543** [comment]
https://github.com/labring-actions/runtime/blob/40f4fbc4ee2a7741a2f55096dc434edde92f8914/containerd/scripts/init-cri.sh#L17-L23
https://github.com/labring-actions/runtime/blob/40f4fbc4ee2a7741a2f55096dc434edde92f8914/containerd/Kubefile#L3
@cuisongliu It looks like the `REGISTRY_DOMAIN` `REGISTRY_PORT` parameter is not used.

**Comment by cuisongliu** [comment]
using newest image fix it.
