### ISSUE TITLE
add节点的时候报错：cluster image kubernetes version cannot be empty

### ISSUE THREAD

**Issue by dixon1983** [labring/sealos#2958]
### Sealos Version

4.1.3

### How to reproduce the bug?

添加节点的时候遇到这个新问题，麻烦帮忙看一
![QQ图片20230418124037](https://user-images.githubusercontent.com/35091088/232806167-c4a2220a-f053-4176-a71b-4871d5b618a1.png)
下

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by dixon1983** [comment]
添加和删除节点，都报这个同样的错误

**Comment by cuisongliu** [comment]
https://github.com/labring/sealos/pull/2856  fix it
