### ISSUE TITLE
为什么sealos4.2部署的集群，registry仓库连接数很高?

### ISSUE THREAD

**Issue by zhengbucuo888** [labring/sealos#2965]
### Detailed description of the question.

![image](https://user-images.githubusercontent.com/31462232/233246988-58380912-9fa1-41c7-91e8-fdf09bbf2408.png)
![image](https://user-images.githubusercontent.com/31462232/233247047-0ca9c748-b6c1-4549-adaf-0bc443b586f5.png)

为什么sealos4.2部署的集群，registry仓库连接数很高?4.13部署的集群registry都没这么高

**Comment by zhengbucuo888** [comment]
![image](https://user-images.githubusercontent.com/31462232/233248013-17158a31-b5e6-450c-b654-f6b35bafb8a9.png)

**Comment by fengxsong** [comment]
download the latest `image-cri-shim` binary and replace it.

**Comment by zhengbucuo888** [comment]
直接sealos run image-cri-shim就好了是吧？

**Comment by zhengbucuo888** [comment]
> this issue had already been fixed. plz download the latest `image-cri-shim` binary and replace it then restart image-cri-shim service.

请教下具体的执行过程，不是很懂

**Comment by zhengbucuo888** [comment]
> using latest image-cri-shim

请教下具体的执行过程，不是很懂

**Comment by zhengbucuo888** [comment]
我知道了，谢谢2位大佬
