### ISSUE TITLE
Is there any work related to official documents that can be assigned to me, both in Chinese and English.Question: brief description of the question

### ISSUE THREAD

**Issue by kinbod** [labring/sealos#2979]
### Detailed description of the question.

官方文档方面的工作有没有，可以分派给我，中英文都可以。

### Some reference materials you see.

Is there any work related to official documents that can be assigned to me, both in Chinese and English.

**Comment by cubxxw** [comment]
Read the contributions and official documentation, where required @kinbod

**Comment by willzhang** [comment]
yes, some docs need to change  chinese:
https://www.sealyun.com/docs/getting-started/offline-install
https://www.sealyun.com/zh-Hans/docs/category/build-cloud-images
