### ISSUE TITLE
 How to solve the problem that  cluster status is not ClusterSuccess

### ISSUE THREAD

**Issue by ElonMuskkkkkk** [labring/sealos#2983]
### How to solve the problem that _**cluster status is not ClusterSuccess**?
I have installed the sealos and excute the following steps:
1.
`wget https://github.com/labring/sealos/releases/download/v4.1.4/sealos_4.1.4_linux_amd64.tar.gz && tar zxvf sealos_4.1.4_linux_amd64.tar.gz sealos && chmod +x sealos && mv sealos /usr/bin`
2.
```
echo "deb [trusted=yes] https://apt.fury.io/labring/ /" | sudo tee /etc/apt/sources.list.d/labring.list
sudo apt update
sudo apt install sealos
```
3.
```
sealos pull labring/kubernetes:v1.25.0
sealos save -o kubernetes.tar labring/kubernetes:v1.25.0
```
4.
```
sealos load -i kubernetes.tar
sealos images 
sealos run kuberentes:v1.25.0 --single 
```
The first error what I met is such as the following pictrue:
<img width="857" alt="屏幕截图 2023-04-24 110130" src="https://user-images.githubusercontent.com/94599859/233974029-a79581ff-5015-4a00-8338-8caf19edf526.png">

And the second I delete all packages related to sealos and try again.
But the error is that  cluster status is not ClusterSuccess
Runtime environment is wsl2 + unbuntu22.04

**Comment by bxy4543** [comment]
sealos run kuberentes:v1.25.0 --single  ==> sealos run labring/kuberentes:v1.25.0 --single 
use [4.2.0 version](https://github.com/labring/sealos/releases/tag/v4.2.0)

**Comment by ElonMuskkkkkk** [comment]
> sealos run kuberentes:v1.25.0 --single ==> sealos run labring/kuberentes:v1.25.0 --single use [4.2.0 version](https://github.com/labring/sealos/releases/tag/v4.2.0)

@bxy4543 hello,I have delete the package of sealos and install according to the new version.But there is also some problems.
<img width="851" alt="image" src="https://user-images.githubusercontent.com/94599859/233998258-13be8d66-fa80-4d36-9099-a85c58c31337.png">
The error is that **initializing source docker://labring/kuberentes:v1.25.0: reading manifest v1.25.0 in docker.io/labring/kuberentes: requested access to the resource is denied**
The images is such as the following:
<img width="665" alt="image" src="https://user-images.githubusercontent.com/94599859/233998641-30c51fe7-effe-4fe1-89dc-565bec492ffc.png">

**Comment by ElonMuskkkkkk** [comment]
> @ElonMuskkkkkk `kubernetes` diff `kuberentes`

@bxy4543 thank you，I copied the commands in the Manual  without checking, which caused this error. Now I corrected this small error, but there were still new problems in the subsequent execution.
<img width="668" alt="image" src="https://user-images.githubusercontent.com/94599859/234020379-161cc542-f01e-4da9-93a7-607e6d109279.png">

**Comment by ElonMuskkkkkk** [comment]
> What kind of environment? It seems that systemctl cannot be used normally

@bxy4543 My enviroment is as follows:

<img width="470" alt="image" src="https://user-images.githubusercontent.com/94599859/234148285-3c19c1f2-5f59-4eec-be1b-cf016110cdbd.png">

<img width="847" alt="image" src="https://user-images.githubusercontent.com/94599859/234148485-539d8d4c-0645-4e86-a2af-51db063fc46c.png">

The version of the ubuntu is 22.04

**Comment by bxy4543** [comment]
https://learn.microsoft.com/zh-cn/windows/wsl/wsl-config#systemd-support

**Comment by StLeoX** [comment]
这个报错到底是什么意思啊？是一个通用的错误消息吗？

**Comment by bxy4543** [comment]
> 这个报错到底是什么意思啊？是一个通用的错误消息吗？

哪个？

**Comment by StLeoX** [comment]
> > 这个报错到底是什么意思啊？是一个通用的错误消息吗？
> 
> 哪个？

"Error: cluster status is not ClusterSuccess"

**Comment by bxy4543** [comment]
> > > 这个报错到底是什么意思啊？是一个通用的错误消息吗？
> > 
> > 
> > 哪个？
> 
> "Error: cluster status is not ClusterSuccess"

安装过程哪一步失败了，reset下重新安装吧
