### ISSUE TITLE
BUG: wrong log output to Clusterfile when run `sealos gen`

### ISSUE THREAD

**Issue by zzjin** [labring/sealos#2984]
### Sealos Version

v4.2.0

### How to reproduce the bug?

1. Prepare tow machines as master0,node0, and master0 can access node0
2. Run command `sealos gen hub.sealos.cn/labring/kubernetes:v1.25.6 --masters 10.170.0.5 --nodes 10.170.0.6 > Clusterfile`
3. apply Clusterfile with `sealos apply -f Clusterfile`

Error output:
```
Error: error converting YAML to JSON: yaml: control characters are not allowed
```

### What is the expected behavior?

Run apply successful.

### What do you see instead?

Error Above.

### Operating environment

```markdown
- Sealos version: v.4.2.0
- Operating system: Ubuntu 22.04.2 LTS
- Additional information: GCP
```

### Additional information

The Clusterfile generated shows wrong log output:

```yaml
2023-04-24T15:48:13 ^[[33mwarn^[[0m ^[[33mfailed to get host arch: failed to create ssh session for 10.170.0.6: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain, defaults to amd64^[[0m
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  creationTimestamp: null
  name: default
```

but I can ssh into node machine and exec arch:
```
root@zz-master0:~# ssh 10.170.0.6
root@zz-node0:~# arch
x86_64
root@zz-node0:~#
```

--- 
log output info from: https://github.com/labring/sealos/blob/main/pkg/apply/utils.go#L93 
Here comes two error:
1. sealos gen will redirect `logger` output to `Clusterfile`, not stdout.
2. <del>When we can ensure ssh connective to nodes, but `getHostArch` func still throw an error.</del>  <- This is due to ssh key file not specific.FIxed.

**Comment by bxy4543** [comment]
1. Modify the warning log to stderr
2. Modify the use of the gen command in the document to stdout > Clusterfile， like `sealos gen xxx 1>Clusterfile`

**Comment by fengxsong** [comment]
`sealos gen` has an `-o` flag to write generated template into a named file.
