### ISSUE TITLE
Feature: sealos run --config-file nginx-config.yaml --values values.yaml

### ISSUE THREAD

**Issue by willzhang** [labring/sealos#2989]
### What is the problem this feature will solve?
When installing a large number of plugins at once, extract common parameters into values. yaml.

but templates only support sealos apply with Clusterfile, not support sealos run --config-file
https://www.sealyun.com/docs/cli/apply#using-templates-experimental

### If you have solution，please describe it

sealos run --config-file nginx-config.yaml --values values.yaml

**Comment by cuisongliu** [comment]
https://www.sealyun.com/docs/lifecycle-management/operations/run-cluster/template-apply-cluster
