### ISSUE TITLE
Feature: Support one-key clearing similar to sealos destroy -f Clusterfile

### ISSUE THREAD

**Issue by LZiHaN** [labring/sealos#3003]
### What is the problem this feature will solve?

`sealos apply -f Clusterfile` can be used to destroy all applications through `sealos destroy -f Clusterfile`.
I can't seem to find the corresponding in the api docs.[api](https://sealos.io/zh-Hans/docs/api/sealos_apply)

### If you have solution，please describe it

All application and node configurations can be cleared by `sealos destroy -f Clusterfile`.

### What alternatives have you considered?

The reason for using `apply` is to facilitate deployment, and `destroy` is also for this purpose.

**Comment by cuisongliu** [comment]
usng sealos reset ?

**Comment by nowinkeyy** [comment]
> usng sealos reset ?

I used sealos reset, but I didn't seem to clear it.

**Comment by cuisongliu** [comment]
clear what ? cleat cluster ? app images?

**Comment by nowinkeyy** [comment]
> clear what ? cleat cluster ? app images?

app images.

**Comment by LZiHaN** [comment]
anything about sealos.

**Comment by cuisongliu** [comment]
> anything about sealos.

about sealos or about sealos cluster ? if cluster ,maybe fix reset logic
