### ISSUE TITLE
sealos 4.2.0 版本部署v1.24.0 v1.25.0 报错无法安装

### ISSUE THREAD

**Issue by z641205699** [labring/sealos#3014]
### Detailed description of the question.

安装过程日志：
2023-04-28T11:05:20 info domain apiserver.cluster.local:172.22.1.100 append success
W0428 11:05:20.480411   20490 initconfiguration.go:306] error unmarshaling configuration schema.GroupVersionKind{Group:"kubelet.config.k8s.io", Version:"v1beta1", Kind:"KubeletConfiguration"}: strict decoding error: unknown field "localStorageCapacityIsolation"
W0428 11:05:20.485337   20490 configset.go:177] error unmarshaling configuration schema.GroupVersionKind{Group:"kubelet.config.k8s.io", Version:"v1beta1", Kind:"KubeletConfiguration"}: strict decoding error: unknown field "localStorageCapacityIsolation"
W0428 11:05:20.486264   20490 initconfiguration.go:120] Usage of CRI endpoints without URL scheme is deprecated and can cause kubelet errors in the future. Automatically prepending scheme "unix" to the "criSocket" with value "/run/containerd/containerd.sock". Please update your configuration!
W0428 11:05:20.486314   20490 utils.go:69] The recommended value for "healthzBindAddress" in "KubeletConfiguration" is: 127.0.0.1; the provided value is: 0.0.0.0
[init] Using Kubernetes version: v1.24.0
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Using existing apiserver-kubelet-client certificate and key on disk
[certs] Using existing front-proxy-ca certificate authority
[certs] Using existing front-proxy-client certificate and key on disk
[certs] Using existing etcd/ca certificate authority
[certs] Using existing etcd/server certificate and key on disk
[certs] Using existing etcd/peer certificate and key on disk
[certs] Using existing etcd/healthcheck-client certificate and key on disk
[certs] Using existing apiserver-etcd-client certificate and key on disk
[certs] Using the existing "sa" key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/admin.conf"
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/kubelet.conf"
W0428 11:05:41.790778   20490 kubeconfig.go:249] a kubeconfig file "/etc/kubernetes/controller-manager.conf" exists already but has an unexpected API Server URL: expected: https://172.22.1.100:6443, got: https://apiserver.cluster.local:6443
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/controller-manager.conf"
W0428 11:05:41.944300   20490 kubeconfig.go:249] a kubeconfig file "/etc/kubernetes/scheduler.conf" exists already but has an unexpected API Server URL: expected: https://172.22.1.100:6443, got: https://apiserver.cluster.local:6443
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/scheduler.conf"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

Unfortunately, an error has occurred:
        timed out waiting for the condition

This error is likely caused by:
        - The kubelet is not running
        - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
        - 'systemctl status kubelet'
        - 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI.
Here is one example how you may list all running Kubernetes containers by using crictl:
        - 'crictl --runtime-endpoint unix:///run/containerd/containerd.sock ps -a | grep kube | grep -v pause'
        Once you have found the failing container, you can inspect its logs with:
        - 'crictl --runtime-endpoint unix:///run/containerd/containerd.sock logs CONTAINERID'
error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher
2023-04-28T11:09:42 error Applied to cluster error: failed to init init master0 failed, error: exit status 1. Please clean and reinstall
Error: failed to init init master0 failed, error: exit status 1. Please clean and reinstall

查看系统错误日志

[root@master01 opt]# systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Fri 2023-04-28 11:05:42 CST; 4min 23s ago
     Docs: http://kubernetes.io/docs/
  Process: 20704 ExecStartPre=/usr/bin/kubelet-pre-start.sh (code=exited, status=0/SUCCESS)
 Main PID: 20723 (kubelet)
    Tasks: 13
   Memory: 31.6M
   CGroup: /system.slice/kubelet.service
           └─20723 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --container-runtime=remote --container-runtime-endpo...

Apr 28 11:10:05 master01 kubelet[20723]: E0428 11:10:05.062995   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:05 master01 kubelet[20723]: E0428 11:10:05.163972   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:05 master01 kubelet[20723]: E0428 11:10:05.265069   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:05 master01 kubelet[20723]: E0428 11:10:05.365692   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:05 master01 kubelet[20723]: E0428 11:10:05.466369   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:05 master01 kubelet[20723]: E0428 11:10:05.581407   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:05 master01 kubelet[20723]: E0428 11:10:05.681959   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:05 master01 kubelet[20723]: E0428 11:10:05.782953   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:05 master01 kubelet[20723]: E0428 11:10:05.883799   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:05 master01 kubelet[20723]: E0428 11:10:05.984726   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"

查看错误日志

Apr 28 11:10:22 master01 kubelet[20723]: E0428 11:10:22.809969   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:22 master01 kubelet[20723]: E0428 11:10:22.816858   20723 kubelet.go:2344] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plu
Apr 28 11:10:22 master01 kubelet[20723]: E0428 11:10:22.910660   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:23 master01 kubelet[20723]: E0428 11:10:23.011643   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:23 master01 kubelet[20723]: E0428 11:10:23.112725   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:23 master01 kubelet[20723]: E0428 11:10:23.213589   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:23 master01 kubelet[20723]: E0428 11:10:23.314628   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:23 master01 kubelet[20723]: E0428 11:10:23.415228   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:23 master01 kubelet[20723]: E0428 11:10:23.515918   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:23 master01 kubelet[20723]: W0428 11:10:23.587200   20723 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.Service: Get "https://apiserver.cluster.local:6443/api/v1/services?limit=50
Apr 28 11:10:23 master01 kubelet[20723]: E0428 11:10:23.587268   20723 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://apiserver.cluster.local:
Apr 28 11:10:23 master01 kubelet[20723]: E0428 11:10:23.616745   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:23 master01 kubelet[20723]: E0428 11:10:23.717044   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:23 master01 kubelet[20723]: E0428 11:10:23.818125   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:23 master01 kubelet[20723]: E0428 11:10:23.918779   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:24 master01 kubelet[20723]: E0428 11:10:24.019644   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:24 master01 kubelet[20723]: E0428 11:10:24.119854   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:24 master01 kubelet[20723]: E0428 11:10:24.220524   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:24 master01 kubelet[20723]: E0428 11:10:24.226284   20723 event.go:276] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"master01.1759fa4c9a827e47", GenerateN
Apr 28 11:10:24 master01 kubelet[20723]: E0428 11:10:24.321515   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:24 master01 kubelet[20723]: E0428 11:10:24.422308   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:24 master01 kubelet[20723]: E0428 11:10:24.522995   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:24 master01 kubelet[20723]: E0428 11:10:24.623830   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:24 master01 kubelet[20723]: E0428 11:10:24.723946   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:24 master01 kubelet[20723]: E0428 11:10:24.824253   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:24 master01 kubelet[20723]: E0428 11:10:24.924951   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:25 master01 kubelet[20723]: E0428 11:10:25.025798   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:25 master01 kubelet[20723]: E0428 11:10:25.125948   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:25 master01 kubelet[20723]: E0428 11:10:25.226750   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:25 master01 kubelet[20723]: E0428 11:10:25.327682   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:25 master01 kubelet[20723]: E0428 11:10:25.428310   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:25 master01 kubelet[20723]: E0428 11:10:25.529018   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:25 master01 kubelet[20723]: E0428 11:10:25.629850   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:25 master01 kubelet[20723]: E0428 11:10:25.730143   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:25 master01 kubelet[20723]: E0428 11:10:25.831156   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:25 master01 kubelet[20723]: E0428 11:10:25.932098   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:26 master01 kubelet[20723]: E0428 11:10:26.032803   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:26 master01 kubelet[20723]: E0428 11:10:26.133819   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:26 master01 kubelet[20723]: E0428 11:10:26.234893   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:26 master01 kubelet[20723]: E0428 11:10:26.335402   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 11:10:26 master01 kubelet[20723]: E0428 11:10:26.435944   20723 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"

**Comment by cuisongliu** [comment]
https://github.com/labring-actions/bug-verify/actions/runs/4826079115/jobs/8597576949 我这里测试正常，你看一下crictl ps -a。crictl images  有数据么

**Comment by z641205699** [comment]
我系统centos7.9 阿里云服务器
过程原有阐述：我降低sealos4.1.7 又会出现另外的问题。我最开始问题是在阿里云部署coredns 在容器pod内。 只能ping IP正常， ping域的话不管是baidu.com 还是内部域都找不到 ，所以我就想重新换一个版本测试。没想到就无法安装了。
[root@master01 ~]# crictl ps -a
CONTAINER           IMAGE               CREATED             STATE               NAME                ATTEMPT             POD ID              POD
[root@master01 ~]# crictl images
IMAGE                                     TAG                 IMAGE ID            SIZE
sealos.hub:5000/coredns/coredns           v1.8.6              a4ca41631cc7a       13.6MB
sealos.hub:5000/etcd                      3.5.3-0             aebe758cef4cd       102MB
sealos.hub:5000/kube-apiserver            v1.24.0             529072250ccc6       33.8MB
sealos.hub:5000/kube-controller-manager   v1.24.0             88784fb4ac2f6       31MB
sealos.hub:5000/kube-proxy                v1.24.0             77b49675beae1       39.5MB
sealos.hub:5000/kube-scheduler            v1.24.0             e3ed7dee73e93       15.5MB
sealos.hub:5000/pause                     3.7                 221177c6082a8       311kB

**Comment by z641205699** [comment]
我在此基础上尝试了3个版本 k8s v1.25.0 v1.24.0 v1.26.0
初始化操作：
1 修改了hostname
2 更新了时区
3 添加了所有主机hosts
4 使用了默认22端口

启动命令分别使用了
sealos run labring/kubernetes:v1.26.0 labring/helm:v3.8.2 labring/calico:v3.24.1
或者
sealos gen labring/kubernetes:v1.25.0 labring/helm:v3.8.2 labring/calico:v3.24.1

**Comment by z641205699** [comment]
![image](https://user-images.githubusercontent.com/45276423/235052264-bc66725f-b62c-4130-956d-405fd93f07a7.png)
要不qq群里我们沟通快一点

**Comment by cuisongliu** [comment]
> 我系统centos7.9 阿里云服务器
> 过程原有阐述：我降低sealos4.1.7 又会出现另外的问题。我最开始问题是在阿里云部署coredns 在容器pod内。 只能ping IP正常， ping域的话不管是baidu.com 还是内部域都找不到 ，所以我就想重新换一个版本测试。没想到就无法安装了。
> [root@master01 ~]# crictl ps -a
> CONTAINER IMAGE CREATED STATE NAME ATTEMPT POD ID POD
> [root@master01 ~]# crictl images
> IMAGE TAG IMAGE ID SIZE
> sealos.hub:5000/coredns/coredns v1.8.6 a4ca41631cc7a 13.6MB
> sealos.hub:5000/etcd 3.5.3-0 aebe758cef4cd 102MB
> sealos.hub:5000/kube-apiserver v1.24.0 529072250ccc6 33.8MB
> sealos.hub:5000/kube-controller-manager v1.24.0 88784fb4ac2f6 31MB
> sealos.hub:5000/kube-proxy v1.24.0 77b49675beae1 39.5MB
> sealos.hub:5000/kube-scheduler v1.24.0 e3ed7dee73e93 15.5MB
> sealos.hub:5000/pause 3.7 221177c6082a8 311kB

这个需要改coredns,阿里云机器dns冲突。

**Comment by cuisongliu** [comment]
> 我系统centos7.9 阿里云服务器
> 过程原有阐述：我降低sealos4.1.7 又会出现另外的问题。我最开始问题是在阿里云部署coredns 在容器pod内。 只能ping IP正常， ping域的话不管是baidu.com 还是内部域都找不到 ，所以我就想重新换一个版本测试。没想到就无法安装了。
> [root@master01 ~]# crictl ps -a
> CONTAINER IMAGE CREATED STATE NAME ATTEMPT POD ID POD
> [root@master01 ~]# crictl images
> IMAGE TAG IMAGE ID SIZE
> sealos.hub:5000/coredns/coredns v1.8.6 a4ca41631cc7a 13.6MB
> sealos.hub:5000/etcd 3.5.3-0 aebe758cef4cd 102MB
> sealos.hub:5000/kube-apiserver v1.24.0 529072250ccc6 33.8MB
> sealos.hub:5000/kube-controller-manager v1.24.0 88784fb4ac2f6 31MB
> sealos.hub:5000/kube-proxy v1.24.0 77b49675beae1 39.5MB
> sealos.hub:5000/kube-scheduler v1.24.0 e3ed7dee73e93 15.5MB
> sealos.hub:5000/pause 3.7 221177c6082a8 311kB

journalctl -xeu kubelet 日志发一下

**Comment by z641205699** [comment]
Apr 28 13:47:53 master01 kubelet[22239]: E0428 13:47:53.903191   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:54 master01 kubelet[22239]: E0428 13:47:54.004083   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:54 master01 kubelet[22239]: E0428 13:47:54.104649   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:54 master01 kubelet[22239]: E0428 13:47:54.205434   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:54 master01 kubelet[22239]: E0428 13:47:54.306019   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:54 master01 kubelet[22239]: E0428 13:47:54.406544   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:54 master01 kubelet[22239]: E0428 13:47:54.452398   22239 kubelet.go:2344] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plu
Apr 28 13:47:54 master01 kubelet[22239]: E0428 13:47:54.506980   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:54 master01 kubelet[22239]: E0428 13:47:54.607454   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:54 master01 kubelet[22239]: E0428 13:47:54.708082   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:54 master01 kubelet[22239]: E0428 13:47:54.808971   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:54 master01 kubelet[22239]: E0428 13:47:54.909943   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:55 master01 kubelet[22239]: E0428 13:47:55.010900   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:55 master01 kubelet[22239]: E0428 13:47:55.111666   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:55 master01 kubelet[22239]: E0428 13:47:55.212395   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:55 master01 kubelet[22239]: E0428 13:47:55.312981   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:55 master01 kubelet[22239]: E0428 13:47:55.413793   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:55 master01 kubelet[22239]: E0428 13:47:55.514408   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:55 master01 kubelet[22239]: E0428 13:47:55.615036   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:55 master01 kubelet[22239]: E0428 13:47:55.715681   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:55 master01 kubelet[22239]: E0428 13:47:55.816537   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:55 master01 kubelet[22239]: E0428 13:47:55.917678   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:56 master01 kubelet[22239]: E0428 13:47:56.018738   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:56 master01 kubelet[22239]: E0428 13:47:56.119154   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:56 master01 kubelet[22239]: E0428 13:47:56.219968   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:56 master01 kubelet[22239]: E0428 13:47:56.320498   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:56 master01 kubelet[22239]: E0428 13:47:56.421006   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:56 master01 kubelet[22239]: E0428 13:47:56.521792   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:56 master01 kubelet[22239]: E0428 13:47:56.542539   22239 controller.go:144] failed to ensure lease exists, will retry in 7s, error: Get "https://apiserver.cluster.local:6443/apis/coordination.k8s.io/v1/namespaces/kube-n
Apr 28 13:47:56 master01 kubelet[22239]: E0428 13:47:56.621921   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:56 master01 kubelet[22239]: E0428 13:47:56.722327   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:56 master01 kubelet[22239]: E0428 13:47:56.823099   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:56 master01 kubelet[22239]: E0428 13:47:56.924031   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:57 master01 kubelet[22239]: E0428 13:47:57.024911   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:57 master01 kubelet[22239]: E0428 13:47:57.125494   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:57 master01 kubelet[22239]: E0428 13:47:57.226180   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:57 master01 kubelet[22239]: E0428 13:47:57.326624   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:57 master01 kubelet[22239]: E0428 13:47:57.427156   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:57 master01 kubelet[22239]: E0428 13:47:57.527658   22239 kubelet.go:2419] "Error getting node" err="node \"master01\" not found"
Apr 28 13:47:57 master01 kubelet[22239]: I0428 13:47:57.552091   22239 kubelet_node_status.go:70] "Attempting to register node" node="master01"
Apr 28 13:47:57 master01 kubelet[22239]: E0428 13:47:57.552530   22239 kubelet_node_status.go:92] "Unable to register node with API server" err="Post \"https://apiserver.cluster.local:6443/api/v1/nodes\": dial tcp 172.22.1.100:6443:

**Comment by charnet1019** [comment]
sealos 4.2.0  k8s: 1.26.4 一样的问题，好像还是到外网拉的镜像
![image](https://user-images.githubusercontent.com/18616254/235066329-3d716fc0-ce8e-4435-915e-7cb64227b051.png)

**Comment by z641205699** [comment]
等下 大佬定位到了 在处理

**Comment by z641205699** [comment]
首先 感谢大佬 cuisongliu 帮忙处理接近2个小时 排查和模拟故障问题

问题原因：
定位到是centos7.9 系统问题导致

解决方案一：
修改覆盖：/etc/systemd/system/kubelet.service.d/10-kubeadm.conf 文件内容
```
# Note: This dropin only works with kubeadm and kubelet v1.11+
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"
Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml"
# This is a file that "kubeadm init" and "kubeadm join" generates at runtime, populating the KUBELET_KUBEADM_ARGS variable dynamically
EnvironmentFile=-/var/lib/kubelet/kubeadm-flags.env

# This is a file that the user can use for overrides of the kubelet args as a last resort. Preferably, the user should use
# the .NodeRegistration.KubeletExtraArgs object in the configuration files instead. KUBELET_EXTRA_ARGS should be sourced from this file.
# EnvironmentFile=-/var/lib/kubelet/kubelet-flags.env
Environment="KUBELET_EXTRA_ARGS= --container-runtime=remote --pod-infra-container-image=sealos.hub:5000/pause:3.8 --runtime-request-timeout=15m --container-runtime-endpoint=unix:///run/containerd/containerd.sock --image-service-endpoint=unix:///var/run/image-cri-shim.sock"
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS
```
然后重新cp到kubernetes:v1.24.0本地镜像重新打包

解决方案二：
使用开发镜像：labring/kubernetes:v1.24


解决方案三：
正在更新正式版 镜像：labring/kubernetes:v1.24.0

**Comment by cuisongliu** [comment]
原因是centos下无法加载加载配置
1. 查看crictl ps ,crictl images 发现image有但是没有ps kubelet无法启动（启动的话ps肯定有数据）
2. 查看日志发现拉取镜像都是外部镜像 （kubelet对接shim有问题）
3. 查看kubelet相关配置，（/etc/systemd/system/kubelet.service.d/10-kubeadm.conf配置和kubelet.env配置）
4. 查看进程”ps -ef | grep kubelet | grep image “ 发现image-cri-shim并没有写到进程，service相关配置没有加载Kubelet.env 

最后调整service配置直接写Environment 覆盖参数

**Comment by DoubleJ213** [comment]
on arm with v1.25.8 still have the problem

E0505 11:30:09.376704   10501 remote_image.go:242] "PullImage from image service failed" err="rpc error: code = Unavailable desc = error reading from server: EOF" image=":/"
FATA[0000] pulling image: rpc error: code = Unavailable desc = error reading from server: EOF 
cp: cannot stat ‘../etc/kubelet-flags.env’: No such file or directory

**Comment by SupRenekton** [comment]
arm的镜像有修复么
