### ISSUE TITLE
BUG: kubernetes/manifsets not updated and kubelet pull images from registry.k8s.io

### ISSUE THREAD

**Issue by jeffguorg** [labring/sealos#3023]
### Sealos Version

v4.2.0 

### How to reproduce the bug?

simply
- sealos run labring/kubernetes:v1.26.4-4.2.0 labring/cilium:v1.13.0

### What is the expected behavior?

kubernetes up and running

### What do you see instead?

kubeadm timeout waiting for kube-apiserver

### Operating environment

```markdown
- Sealos version: v4.2.0
- Docker version: containerd v1.6.20 from sealos
- Kubernetes version: v1.26.4-4.2.0
- Operating system: RockyLinux 9 with SELinux disabled
- Runtime environment: Hyper-V VM with all CPU cores, 32G RAM and plenty of storage(at least 100G available)
- Cluster size: 1 node to test it out
- Additional information:
```

### Additional information

I digged it up and found that sealos pulled the image with the references of
- sealos.hub:5000/etcd
- sealos.hub:5000/kube-apiserver
- ...
and not tagged to any other form

but the manifest is still registry.k8s.io/...

not sure how the image is packaged, but I think it's where the problem is

**Comment by cuisongliu** [comment]
What‘s your question?

**Comment by cuisongliu** [comment]
crictl images?

**Comment by bxy4543** [comment]
> but the manifest is still registry.k8s.io/...

Is there any relevant error log info ?
