### ISSUE TITLE
sealos reset failed

### ISSUE THREAD

**Issue by henryhyang** [labring/sealos#3027]
### Detailed description of the question.
Sealos 4.2.0

卸载sealos，执行如下命令，不能正常卸载：
sealos reset --masters 10.161.42.241:22 

看了ClusterFile，一开始是有spec.hosts，但是到了后面 打印的信息上已经没有它了，就报了这个错误：

![image](https://user-images.githubusercontent.com/37874767/235572029-5cd44a9d-b12e-4c44-84b6-115c22faa30b.png)

![image](https://user-images.githubusercontent.com/37874767/235572122-14686560-8615-45f9-ad0c-f58052621c08.png)

**Comment by bxy4543** [comment]
sealos delete --masters 10.161.42.241

**Comment by henryhyang** [comment]
使用delete不行：
![image](https://user-images.githubusercontent.com/37874767/235871964-bc0121be-f521-4cfd-b744-5258c7bc3c83.png)

**Comment by bxy4543** [comment]
If you want to delete a node, execute `sealos delete --masters xxx`
If you want to reset nodes,  only execute `sealos reset `

**Comment by henryhyang** [comment]
> 

就是用的reset命令，不能删除本机master

**Comment by cuisongliu** [comment]
你是怎么安装的

**Comment by henryhyang** [comment]
> 你是怎么安装的
使用ClusterFile安装的，如下：
sealos --debug apply -f ./clusterfile

clusterfile内容：
![image](https://user-images.githubusercontent.com/37874767/236712225-fc3c282a-b7a3-42fb-b754-64619d254095.png)

**Comment by henryhyang** [comment]
此问题已定位出来了，pkg/apply/reset.go这里把它置为空了：
![image](https://github.com/labring/sealos/assets/37874767/24be5c42-2d2e-41e6-a96f-b4d4dfc6d6e4)
