### ISSUE TITLE
Sealos got stuck when compiling, how to solve this problem？

### ISSUE THREAD

**Issue by ElonMuskkkkkk** [labring/sealos#3032]
### Detailed description of the question.

I tried many types of virtual machines, including multipass and wsl, the result is the same，as following:
```
make build BINS=sealos
===========> Building binary sealos v4.2.0 for linux_amd64
```
My environment is ubuntu22.04 LTS
Go version is 1.20.4
My virtual machine is pure, without any other redundant software installed, such as docker, k8s.
How to solve it?

**Comment by cuisongliu** [comment]
This seems to have succeeded.The file is in the bin directory.

**Comment by ElonMuskkkkkk** [comment]
> This seems to have succeeded.The file is in the bin directory.
@cuisongliu There is only an empty directory in the bin directory that is name linux_amd64,but nothing executable in it.

**Comment by xiao-jay** [comment]
@ElonMuskkkkkk  you can do next step to solve the problem
1、export GOPROXY=https://proxy.golang.com.cn,direct
2、go mod tidy
3、make build BINS=sealos
