### ISSUE TITLE
sealos 部署时内网出现的错误 怎么解决私网的问题 

### ISSUE THREAD

**Issue by Fleezesd** [labring/sealos#3035]
### 相关k8s 镜像都是传到内网harbor再给sealos 那台机器 所以sealos run harbor.xxx/labring-kubernetes:v1.25.0 出现了这类问题

E0505 14:21:53.179730   94018 remote_image.go:242] "PullImage from image service failed" err="rpc error: code = Unavailable desc = error reading from server: EOF" image=":/"
FATA[0000] pulling image: rpc error: code = Unavailable desc = error reading from server: EOF

**Comment by cuisongliu** [comment]
你的意思是把容器镜像传harbor了？？？那集群镜像呢。。。看样子你的这个是镜像拉不下来。

**Comment by Fleezesd** [comment]
是说apiserver Etcd 这些组件的镜像么  目前harbor只存了这些
![截屏2023-05-05 14 46 27](https://user-images.githubusercontent.com/55348860/236392918-51990cb8-45b1-474e-8fd7-ed64b501dcce.png)

**Comment by cuisongliu** [comment]
sealos 登录到harbor了么

**Comment by cuisongliu** [comment]
日志全一些。。。看不出是哪个东西出的问题。。。

**Comment by Fleezesd** [comment]
5月 05 16:01:47 gms-1.kunpeng.cloud.com image-cri-shim[10358]: 2023-05-05T16:01:47 warn get image :/ manifest error could not parse reference: :/
5月 05 16:01:47 image-cri-shim[10358]: panic: runtime error: invalid memory address or nil pointer dereference
5月 05 16:01:47 image-cri-shim[10358]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xb05338]
5月 05 16:01:47 image-cri-shim[10358]: goroutine 125 [running]:
5月 05 16:01:47 image-cri-shim[10358]: github.com/labring/image-cri-shim/pkg/server.(*v1ImageService).PullImage(0x40001ab000, {0xf5d500, 0x4000716ff0}, 0x40001aa100)
5月 05 16:01:47 image-cri-shim[10358]: github.com/labring/image-cri-shim/pkg/server/cri_server_v1.go:76 +0xb8
5月 05 16:01:47  image-cri-shim[10358]: k8s.io/cri-api/pkg/apis/runtime/v1._ImageService_PullImage_Handler({0xc80800?, 0x40001ab000}, {0xf5d500, 0x4000716ff0}, 0x40002ce1c0, 0x0)
5月 05 16:01:47  image-cri-shim[10358]: k8s.io/cri-api@v0.26.2/pkg/apis/runtime/v1/api.pb.go:10214 +0x164
5月 05 16:01:47 image-cri-shim[10358]: google.golang.org/grpc.(*Server).processUnaryRPC(0x400020c000, {0xf629f8, 0x4000623d40}, 0x40001de480, 0x40007162a0, 0x17973f0, 0x0)

**Comment by Fleezesd** [comment]
看image-cri-shim的日志 有出现获取image出现错误的问题

**Comment by Fleezesd** [comment]
5月 05 16:01:47 image-cri-shim[10358]: 2023-05-05T16:01:47 warn get image :/ manifest error could not parse reference: :/
5月 05 16:01:47 image-cri-shim[10358]: panic: runtime error: invalid memory address or nil pointer dereference
5月 05 16:01:47 image-cri-shim[10358]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xb05338]
5月 05 16:01:47 image-cri-shim[10358]: goroutine 125 [running]:
5月 05 16:01:47 image-cri-shim[10358]: github.com/labring/image-cri-shim/pkg/server.(*v1ImageService).PullImage(0x40001ab000, {0xf5d500, 0x4000716ff0}, 0x40001aa100)
5月 05 16:01:47 image-cri-shim[10358]: github.com/labring/image-cri-shim/pkg/server/cri_server_v1.go:76 +0xb8
5月 05 16:01:47 image-cri-shim[10358]: k8s.io/cri-api/pkg/apis/runtime/v1._ImageService_PullImage_Handler({0xc80800?, 0x40001ab000}, {0xf5d500, 0x4000716ff0}, 0x40002ce1c0, 0x0)
5月 05 16:01:47 image-cri-shim[10358]: k8s.io/cri-api@v0.26.2/pkg/apis/runtime/v1/api.pb.go:10214 +0x164
5月 05 16:01:47 image-cri-shim[10358]: google.golang.org/grpc.(*Server).processUnaryRPC(0x400020c000, {0xf629f8, 0x4000623d40}, 0x40001de480, 0x40007162a0, 0x17973f0, 0x0)

**Comment by Fleezesd** [comment]
登录harbor了 在sealos run 时都是去对应仓库里拿镜像 是在启动的过程中出现的问题

**Comment by Fleezesd** [comment]
which: no docker in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
 WARN [2023-05-05 16:14:31] >> Replace disable_apparmor = false to disable_apparmor = true
 INFO [2023-05-05 16:14:31] >> check root,port,cri success
Created symlink from /etc/systemd/system/multi-user.target.wants/containerd.service to /etc/systemd/system/containerd.service.
 INFO [2023-05-05 16:14:33] >> Health check containerd!
 INFO [2023-05-05 16:14:33] >> containerd is running
 INFO [2023-05-05 16:14:33] >> init containerd success
Created symlink from /etc/systemd/system/multi-user.target.wants/image-cri-shim.service to /etc/systemd/system/image-cri-shim.service.
 INFO [2023-05-05 16:14:33] >> Health check image-cri-shim!
 INFO [2023-05-05 16:14:33] >> image-cri-shim is running
 INFO [2023-05-05 16:14:33] >> init shim success
127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4
::1 localhost localhost.localdomain localhost6 localhost6.localdomain6
* Applying /usr/lib/sysctl.d/00-system.conf ...
net.bridge.bridge-nf-call-ip6tables = 0
net.bridge.bridge-nf-call-iptables = 0
net.bridge.bridge-nf-call-arptables = 0
* Applying /usr/lib/sysctl.d/10-default-yama-scope.conf ...
kernel.yama.ptrace_scope = 0
* Applying /usr/lib/sysctl.d/50-default.conf ...
kernel.sysrq = 16
kernel.core_uses_pid = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.accept_source_route = 0
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.promote_secondaries = 1
net.ipv4.conf.all.promote_secondaries = 1
fs.protected_hardlinks = 1
fs.protected_symlinks = 1
* Applying /etc/sysctl.d/99-sysctl.conf ...
* Applying /etc/sysctl.d/sealos-k8s.conf ...
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.conf.all.rp_filter = 0
net.ipv4.ip_forward = 1
sysctl: setting key "net.ipv4.ip_local_port_range": 无效的参数
net.ipv4.ip_local_port_range = "1024 65535"
net.core.somaxconn = 65535
fs.file-max = 1048576
* Applying /etc/sysctl.conf ...
E0505 16:14:34.261802   12295 remote_image.go:242] "PullImage from image service failed" err="rpc error: code = Unavailable desc = error reading from server: EOF" image=":/"
FATA[0000] pulling image: rpc error: code = Unavailable desc = error reading from server: EOF
 INFO [2023-05-05 16:14:34] >> init kubelet success
 INFO [2023-05-05 16:14:34] >> init rootfs success
Created symlink from /etc/systemd/system/multi-user.target.wants/registry.service to /etc/systemd/system/registry.service.
 INFO [2023-05-05 16:14:34] >> Health check registry!
 INFO [2023-05-05 16:14:34] >> registry is running
 INFO [2023-05-05 16:14:34] >> init registry success
2023-05-05T16:14:34 info Executing pipeline Init in CreateProcessor.
2023-05-05T16:14:34 info start to copy kubeadm config to master0
2023-05-05T16:14:35 info start to generate cert and kubeConfig...
2023-05-05T16:14:35 info start to generator cert and copy to masters...2023-05-05T16:14:38 info start to copy etc pki files to masters
2023-05-05T16:14:38 info start to copy etc pki files to masters
2023-05-05T16:14:38 info start to create kubeconfig...
2023-05-05T16:14:39 info start to copy kubeconfig files to masters
2023-05-05T16:14:39 info start to copy static files to masters
2023-05-05T16:14:39 info start to init master0...bash: auth.sh: 未找到命令
2023-05-05T16:14:39 error Applied to cluster error: failed to init exec auth.sh failed exit status 127

**Comment by cuisongliu** [comment]
用sealos 4.2.0

**Comment by Fleezesd** [comment]
😂 解决了 非常感谢 言简意赅
