### ISSUE TITLE
sealos 4.2.0安装docker.io/labring/kubernetes-docker:v1.16.15-4.2.0失败

### ISSUE THREAD

**Issue by AEGEGE** [labring/sealos#3036]
### Detailed description of the question.

执行命令
`sealos run docker.io/labring/kubernetes-docker:v1.16.15-4.2.0 labring/helm:v3.10.3 labring/calico:v3.24.5   --masters 192.168.2.66,192.168.2.67,192.168.2.68   --passwd '123456'`

报错信息：
`192.168.2.67:22 Image is up to date for sealos.hub:5000/pause@sha256:f78411e19d84a252e53bff71a4407a5686c46983a2c2eeed83929b888179acea 192.168.2.67:22  INFO [2023-05-05 11:21:28] >> init kubelet success  192.168.2.67:22  INFO [2023-05-05 11:21:28] >> init rootfs success  Image is up to date for sealos.hub:5000/pause@sha256:f78411e19d84a252e53bff71a4407a5686c46983a2c2eeed83929b888179acea 192.168.2.68:22 Image is up to date for sealos.hub:5000/pause@sha256:f78411e19d84a252e53bff71a4407a5686c46983a2c2eeed83929b888179acea 192.168.2.68:22  INFO [2023-05-05 11:21:28] >> init kubelet success  INFO [2023-05-05 11:21:28] >> init kubelet success  192.168.2.68:22  INFO [2023-05-05 11:21:28] >> init rootfs success  INFO [2023-05-05 11:21:28] >> init rootfs success  2023-05-05T11:21:28 info Executing pipeline Init in CreateProcessor. 2023-05-05T11:21:28 info start to copy kubeadm config to master0 2023-05-05T11:21:28 error Applied to cluster error: failed to init generator config init kubeadm config error: exit status 1`

**Comment by cuisongliu** [comment]
--debug看一下错误信息

**Comment by AEGEGE** [comment]
debug get nodes [192.168.2.66:22] cri socket is [2023-05-05T14:50:44 error found multiple CRI sockets, please use --cri-socket to select one: /var/run/cri-dockerd.sock, /run/containerd/containerd.sock]
2023-05-05T14:50:44 debug node: 192.168.2.66:22 , criSocket: 2023-05-05T14:50:44 error found multiple CRI sockets, please use --cri-socket to select one: /var/run/cri-dockerd.sock, /run/containerd/containerd.sock
2023-05-05T14:50:44 debug not trying to parse private key file cause it's not exists
2023-05-05T14:50:44 debug start to exec remote 192.168.2.66:22 shell: /var/lib/sealos/data/default/rootfs/opt/sealctl cri cgroup-driver --short
2023-05-05T14:50:44 debug host 192.168.2.66:22 is local, command via exec
2023-05-05T14:50:44 debug failed to exec remote 192.168.2.66:22 shell: /var/lib/sealos/data/default/rootfs/opt/sealctl cri cgroup-driver --short output: &{default} error: exit status 1
2023-05-05T14:50:44 error Applied to cluster error: failed to init generator config init kubeadm config error: exit status 1
2023-05-05T14:50:44 debug write cluster file to local storage: /root/.sealos/default/Clusterfile

**Comment by AEGEGE** [comment]
能用自己安装的docker吗？

**Comment by cuisongliu** [comment]
error found multiple CRI sockets, please use --cri-socket to select one: /var/run/cri-dockerd.sock, /run/containerd/containerd.sock

本地有containerd 卸载了在用

**Comment by AEGEGE** [comment]
镜像自带的docker，版本有点低，能用自己安装的docker版本吗？如何操作？

**Comment by cuisongliu** [comment]
主要你用的k8s版本比较低，这个是匹配k8s版本的。如果想改需要重新制作基础镜像。

**Comment by AEGEGE** [comment]
请问下列报错是怎么回事？
`The cluster-info ConfigMap does not yet contain a JWS signature for token ID "lsnsb7", will try again`

**Comment by cuisongliu** [comment]
这个没有报错啊。。。

**Comment by AEGEGE** [comment]
安装失败啊，上面说签名不对
`I0505 16:25:45.289129  976769 token.go:223] [discovery] The cluster-info ConfigMap does not yet contain a JWS signature for token ID "lsnsb7", will try again
could not find a JWS signature in the cluster-info ConfigMap for token ID "lsnsb7"
k8s.io/kubernetes/cmd/kubeadm/app/discovery/token.getClusterInfo.func1
        cmd/kubeadm/app/discovery/token/token.go:224
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
        vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:157
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil
        vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:158
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil
        vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:135`

**Comment by AEGEGE** [comment]
发一个全一点的
`Error: exec kubeadm join in 192.168.10.29 failed failed to execute command(kubeadm join --config=/root/.sealos/testk8s/etc/kubeadm-join-master.yaml -v 6 --ignore-preflight-errors=SystemVerification) on host(192.168.10.29): output(I0505 16:20:49.708820  976769 join.go:414] [preflight] found NodeName empty; using OS hostname as NodeName
I0505 16:20:49.708885  976769 joinconfiguration.go:76] loading configuration from "/root/.sealos/testk8s/etc/kubeadm-join-master.yaml"
W0505 16:20:49.710394  976769 initconfiguration.go:120] Usage of CRI endpoints without URL scheme is deprecated and can cause kubelet errors in the future. Automatically prepending scheme "unix" to the "criSocket" with value "/run/containerd/containerd.sock". Please update your configuration!
[preflight] Running pre-flight checks
I0505 16:20:49.710485  976769 preflight.go:92] [preflight] Running general checks
I0505 16:20:49.710552  976769 checks.go:282] validating the existence of file /etc/kubernetes/kubelet.conf
I0505 16:20:49.710574  976769 checks.go:282] validating the existence of file /etc/kubernetes/bootstrap-kubelet.conf
I0505 16:20:49.710588  976769 checks.go:106] validating the container runtime
I0505 16:20:49.723333  976769 checks.go:331] validating the contents of file /proc/sys/net/bridge/bridge-nf-call-iptables
I0505 16:20:49.723406  976769 checks.go:331] validating the contents of file /proc/sys/net/ipv4/ip_forward
I0505 16:20:49.723440  976769 checks.go:646] validating whether swap is enabled or not
I0505 16:20:49.723490  976769 checks.go:372] validating the presence of executable crictl
I0505 16:20:49.723537  976769 checks.go:372] validating the presence of executable conntrack
I0505 16:20:49.723569  976769 checks.go:372] validating the presence of executable ip
I0505 16:20:49.723595  976769 checks.go:372] validating the presence of executable iptables
I0505 16:20:49.723629  976769 checks.go:372] validating the presence of executable mount
I0505 16:20:49.723657  976769 checks.go:372] validating the presence of executable nsenter
I0505 16:20:49.723685  976769 checks.go:372] validating the presence of executable ebtables
I0505 16:20:49.723713  976769 checks.go:372] validating the presence of executable ethtool
I0505 16:20:49.723738  976769 checks.go:372] validating the presence of executable socat
I0505 16:20:49.723759  976769 checks.go:372] validating the presence of executable tc
I0505 16:20:49.723776  976769 checks.go:372] validating the presence of executable touch
I0505 16:20:49.723805  976769 checks.go:518] running all checks
I0505 16:20:49.732439  976769 checks.go:403] checking whether the given node name is valid and reachable using net.LookupHost
I0505 16:20:49.732610  976769 checks.go:612] validating kubelet version
I0505 16:20:49.789281  976769 checks.go:132] validating if the "kubelet" service is enabled and active
I0505 16:20:49.807274  976769 checks.go:205] validating availability of port 10250
I0505 16:20:49.807440  976769 checks.go:432] validating if the connectivity type is via proxy or direct
I0505 16:20:49.807485  976769 join.go:531] [preflight] Discovering cluster-info
I0505 16:20:49.807518  976769 token.go:80] [discovery] Created cluster-info discovery client, requesting info from "192.168.10.28:6443"
I0505 16:20:49.819942  976769 round_trippers.go:553] GET https://192.168.10.28:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s 200 OK in 11 milliseconds
I0505 16:20:49.820361  976769 token.go:223] [discovery] The cluster-info ConfigMap does not yet contain a JWS signature for token ID "lsnsb7", will try again
I0505 16:20:55.743854  976769 round_trippers.go:553] GET https://192.168.10.28:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s 200 OK in 16 milliseconds
I0505 16:20:55.744069  976769 token.go:223] [discovery] The cluster-info ConfigMap does not yet contain a JWS signature for token ID "lsnsb7", will try again
I0505 16:21:02.168630  976769 round_trippers.go:553] GET https://192.168.10.28:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s 200 OK in 13 milliseconds
I0505 16:21:02.168841  976769 token.go:223] [discovery] The cluster-info ConfigMap does not yet contain a JWS signature for token ID "lsnsb7", will try again
I0505 16:21:08.174615  976769 round_trippers.go:553] GET https://192.168.10.28:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s 200 OK in 3 milliseconds
I0505 16:21:08.174771  976769 token.go:223] [discovery] The cluster-info ConfigMap does not yet contain a JWS signature for token ID "lsnsb7", will try again
I0505 16:21:13.852149  976769 round_trippers.go:553] GET https://192.168.10.28:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s 200 OK in 15 milliseconds
I0505 16:21:13.852303  976769 token.go:223] [discovery] The cluster-info ConfigMap does not yet contain a JWS signature for token ID "lsnsb7", will try again
I0505 16:21:19.500294  976769 round_trippers.go:553] GET https://192.168.10.28:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s 200 OK in 6 milliseconds
I0505 16:21:19.500442  976769 token.go:223] [discovery] The cluster-info ConfigMap does not yet contain a JWS signature for token ID "lsnsb7", will try again
I0505 16:21:25.551921  976769 round_trippers.go:553] GET https://192.168.10.28:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s 200 OK in 15 milliseconds
I0505 16:21:25.552151  976769 token.go:223] [discovery] The cluster-info ConfigMap does not yet contain a JWS signature for token ID "lsnsb7", will try again
I0505 16:21:30.664829  976769 round_trippers.go:553] GET https://192.168.10.28:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s 200 OK in 9 milliseconds
I0505 16:21:30.664995  976769 token.go:223] [discovery] The cluster-info ConfigMap does not yet contain a JWS signature for token ID "lsnsb7", will try again
I0505 16:21:35.921210  976769 round_trippers.go:553] GET https://192.168.10.28:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s 200 OK in 16 milliseconds
I0505 16:21:35.921361  976769 token.go:223] [discovery] The cluster-info ConfigMap does not yet contain a JWS signature for token ID "lsnsb7", will try again
I0505 16:21:41.082603  976769 round_trippers.go:553] GET https://192.168.10.28:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s 200 OK in 10 milliseconds
I0505 16:21:41.082794  976769 token.go:223] [discovery] The cluster-info ConfigMap does not yet contain a JWS signature for token ID "lsnsb7", will try again
I0505 16:21:46.556247  976769 round_trippers.go:553] GET https://192.168.10.28:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s 200 OK in 16 milliseconds`

**Comment by cuisongliu** [comment]
1.16 应该不支持，从18开始支持。太低了，低版本只是做了镜像 但是没做支持，kubeadm的底层接口变了。

**Comment by cuisongliu** [comment]
用4.2.0试试

**Comment by AEGEGE** [comment]
可以通过配置文件修改仓库的默认账户密码吗？

**Comment by cuisongliu** [comment]
通过环境变量--env设置

**Comment by AEGEGE** [comment]
> 通过环境变量--env设置

指定环境变量中- registryData=/data/registry,发现安装完之后只是在/data/下创建了一个软连接，实际目录还是在/var/lib/sealos/data/myk8s/rootfs/registry下，
