### ISSUE TITLE
cannot get  pause image's name on arm

### ISSUE THREAD

**Issue by DoubleJ213** [labring/sealos#3037]
### Sealos Version

4.1.7

### How to reproduce the bug?

Centos7.6 
arm

kubernetes image 1.25.8 . The latest？

1. E0505 16:37:57.306906    2832 remote_image.go:242] "PullImage from image service failed" err="rpc error: code = Unavailable desc = error reading from server: EOF" image=":/"
FATA[0000] pulling image: rpc error: code = Unavailable desc = error reading from server: EOF 

crictl pull ${registryDomain}:${registryPort}/${sandboxImage}

cannot get pause image's name.

2. cp: cannot stat ‘../etc/kubelet-flags.env’: No such file or directory

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cuisongliu** [comment]
https://sealos.io/docs/getting-started/sealos_rootfs_cluster_image_guide 

using 4.2.0 ,the latest image support 4.2.0
