### ISSUE TITLE
v1.24.x 安装失败

### ISSUE THREAD

**Issue by rainbowechoes** [labring/sealos#3038]
### Sealos Version

v4.2.0

### How to reproduce the bug?

1 master + 3 node

4 个虚拟机都是 ubuntu 20.04 

在 master 节点上使用一下命令安装：
```shell
sudo sealos run labring/kubernetes:v1.24.2 labring/helm:v3.8.2 labring/calico:v3.24.1 --masters 192.168.188.137 --nodes 192.168.188.138,192.168.188.142,192.168.188.143 -u xxx -p xxx
```

输出：
<img width="1898" alt="image" src="https://user-images.githubusercontent.com/38370475/236431206-92398352-7f40-4da2-b5d7-3ca15b54bd49.png">

### What is the expected behavior?

未能正常安装 k8s 集群

### Operating environment

```markdown
- Sealos version: 4.2.0
- Kubernetes version: 1.24.x
- Operating system: ubuntu 20.04
```

**Comment by cuisongliu** [comment]
https://github.com/labring/sealos/issues/2883
