### ISSUE TITLE
sealos安装的kubesphere nodejs版本默认太低

### ISSUE THREAD

**Issue by chenshengshi** [labring/sealos#3079]
### What is the problem this feature will solve?

现在 npm构建项目越来越少了， 基本用yarn构建比较多，而yarn构建依赖于node版本，默认版本node 是10.13 希望未来可以改一下node版本为16xxx或者更高

**Comment by willzhang** [comment]
> 

你这是ks devops 用的构建镜像吗，这个镜像版本可以自己改或者自制的，另外这种问题应该在[kubesphere项目](https://github.com/kubesphere/kubesphere/issues)提问更好。
