### ISSUE TITLE
sealos 安装报错

### ISSUE THREAD

**Issue by chenshanping** [labring/sealos#3098]
### Detailed description of the question.

{"level":"error","ts":"2023-05-16T12:51:36.981+0800","msg":"\u001b[31mApplied to cluster error: failed to init exec auth.sh failed exit status 127\u001b[0m"}

**Comment by cuisongliu** [comment]
auth.sh 查看你的镜像和sealos的对应版本，如果用的kubernetes:v1.xx.x 这样的版本是需要升级sealos的。
