### ISSUE TITLE
在sealos安装的 k8集群中的  /etc/kubernetes/mainfests中更新api-server.yml的启动参数，导致kubectl不能访问k8资源

### ISSUE THREAD

**Issue by SsLaLal** [labring/sealos#3125]
### Detailed description of the question.

- --feature-gates=RemoveSelfLink=false
这个是我新加的启动参数

然后发现kubectl提示
The connection to the server apiserver.cluster.local:6443 was refused - did you specify the right host or port?

对应master节点，也变为not ready状态

查看kubelet信息提示

root@105-szdz-master:/etc/kubernetes/manifests# systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
     Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/kubelet.service.d
             └─10-kubeadm.conf
     Active: active (running) since Wed 2023-05-24 16:37:38 CST; 16h ago
       Docs: http://kubernetes.io/docs/
    Process: 3070255 ExecStartPre=/usr/bin/kubelet-pre-start.sh (code=exited, status=0/SUCCESS)
   Main PID: 3070285 (kubelet)
      Tasks: 29 (limit: 38393)
     Memory: 69.5M
     CGroup: /system.slice/kubelet.service
             └─3070285 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.c>

May 25 08:41:45 105-szdz-master kubelet[3070285]: E0525 08:41:45.932737 3070285 kubelet_node_status.go:447] "Unable to update node status" e>
May 25 08:41:47 105-szdz-master kubelet[3070285]: E0525 08:41:47.053718 3070285 event.go:276] Unable to write event: '&v1.Event{TypeMeta:v1.>
May 25 08:41:47 105-szdz-master kubelet[3070285]: W0525 08:41:47.229934 3070285 reflector.go:324] object-"tigera-operator"/"kubernetes-servi>
May 25 08:41:47 105-szdz-master kubelet[3070285]: E0525 08:41:47.229984 3070285 reflector.go:138] object-"tigera-operator"/"kubernetes-servi>
May 25 08:41:47 105-szdz-master kubelet[3070285]: E0525 08:41:47.944650 3070285 controller.go:144] failed to ensure lease exists, will retry>
May 25 08:41:48 105-szdz-master kubelet[3070285]: I0525 08:41:48.853673 3070285 status_manager.go:664] "Failed to get status for pod" podUID>
May 25 08:41:48 105-szdz-master kubelet[3070285]: I0525 08:41:48.853978 3070285 status_manager.go:664] "Failed to get status for pod" podUID>
May 25 08:41:48 105-szdz-master kubelet[3070285]: I0525 08:41:48.854230 3070285 status_manager.go:664] "Failed to get status for pod" podUID>
May 25 08:41:51 105-szdz-master kubelet[3070285]: W0525 08:41:51.728387 3070285 reflector.go:324] object-"tigera-operator"/"kubernetes-servi>
May 25 08:41:51 105-szdz-master kubelet[3070285]: E0525 08:41:51.728435 3070285 reflector.go:138] object-"tigera-operator"/"kubernetes-servi>

请问除了删除我加的那行启动参数，还有其他的解决方式吗

**Comment by zhangguanzhang** [comment]
kube-apiserver是staticPod，你修改yaml后它无法启动就用容器运行时去查看它的日志。
一般是改错pod字段不规范，或者是参数不对。前者看kubelet日志，后者docker ps -a | grep kube-apiserver
