### ISSUE TITLE
BUG: sealos cloud 开启websocket协议失败

### ISSUE THREAD

**Issue by vevlins** [labring/sealos#3136]
### Sealos Version

sealos cloud

### How to reproduce the bug?

1. 创建应用，选择websocket协议
2. 点击生成

### What do you see instead?

applyApp 接口报错："Ingress in version \"v1\" cannot be handled as a Ingress: json: cannot unmarshal number into Go struct field ObjectMeta.metadata.annotations of type string"

预期 ingress.yaml 中的两个值类型应为字符类型：
<img width="999" alt="image" src="https://github.com/labring/sealos/assets/15275921/8aa54759-7f1b-49e0-aa68-00bc06cc860a">

**Comment by fanux** [comment]
fangnux 加我微信拉你进支持群哈

**Comment by zzjin** [comment]
Fixed.
