### ISSUE TITLE
请问怎么才能在部署sealos使用calico插件的时候开启metrics

### ISSUE THREAD

**Issue by AEGEGE** [labring/sealos#3165]
### Detailed description of the question.

我现在的Cluster关于calico部分是
`apiVersion: apps.sealos.io/v1beta1
kind: Config
metadata:
  name: calico
spec:
  path: charts/calico/values.yaml
  strategy: merge
  data: |
    installation:
      enabled: true
      kubernetesProvider: ""
      calicoNetwork:
        mtu: 0
        ipPools:
        - blockSize: 26
          cidr: 11.234.0.0/16
          encapsulation: IPIP
          natOutgoing: Enabled
          nodeSelector: all()
        nodeAddressAutodetectionV4:
          interface: "eth.*|en.*"`

请问需要怎么修改才行

**Comment by cuisongliu** [comment]
helm show values projectcalico/tigera-operator --version v3.26.0 

看一下你的calico版本看一下有支持values有没有相关的
