### ISSUE TITLE
Question: any way to set registry proxy for `sealos build`？

### ISSUE THREAD

**Issue by luanshaotong** [labring/sealos#3167]
### Detailed description of the question.

Some charts with gcr images in operators can't be built without a registry proxy.

**Comment by cuisongliu** [comment]
HTTP_PROXY=socket5://127.0.0.1:7890 SEALOS_REGISTRY_SYNC_EXPERIMENTAL=true sealos build xxxxx 

using main sealos version

**Comment by cuisongliu** [comment]
https://github.com/containers/skopeo/issues/1433

**Comment by luanshaotong** [comment]
That does work! Maybe we need to improve the documentation about this.
