### ISSUE TITLE
rocky8.8    registry status is error

### ISSUE THREAD

**Issue by chenkq520** [labring/sealos#3168]
### Sealos Version

4.2.1-rc3-ac62c855

### How to reproduce the bug?

rocky8.8在安装时，会报错：
 INFO [2023-05-30 02:32:59] >> Health check registry! 
 ERROR [2023-05-30 02:33:00] >> registry status is error 
2023-05-30T02:33:00 error Applied to cluster error: exit status 1

检查是因为registry.service的问题导致的，手动执行systemctl start  registry.service也无法启动，
对/etc/systemd/system/registry.service文件进行修改后可以正常启动：
ExecStart=/usr/bin/registry serve /etc/registry/registry_config.yml改为
ExecStart=/bin/bash -c "/usr/bin/registry serve /etc/registry/registry_config.yml"

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cuisongliu** [comment]
这种情况下不大适合修改官方镜像，你可以自己改一下镜像，毕竟是特殊情况，后面用户可以自行build镜像后就方便了。你可以基于现在的镜像把要修改的文件修改一下就好le .

**Comment by chenkq520** [comment]
这个需要在哪个镜像里哪个路径修改？我自己修改一下，谢谢！


Chenkq
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "labring/sealos"                                                                                    ***@***.***&gt;;
Date:&nbsp;Tue, May 30, 2023 05:34 PM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [labring/sealos] rocky8.8    registry status is error (Issue #3168)





 
这种情况下不大适合修改官方镜像，你可以自己改一下镜像，毕竟是特殊情况，后面用户可以自行build镜像后就方便了。你可以基于现在的镜像把要修改的文件修改一下就好le .

**Comment by cuisongliu** [comment]
https://docs.sealos.io/docs/lifecycle-management/operations/run-cluster/config-customize-app_images-config-rootfs_mage#更多用例 可以参考一下这个方法调整一下镜像配置。
