### ISSUE TITLE
BUG: delete database will not stop cost

### ISSUE THREAD

**Issue by moonrailgun** [labring/sealos#3273]
### Sealos Version

v4.2(cloud)

### How to reproduce the bug?

1. Create mongo database in sealos cloud
2. Delete it
3. wait for some hours

### What is the expected behavior?

Stop costing

### What do you see instead?

![image](https://github.com/labring/sealos/assets/6964737/0353f8b9-9bca-4e7b-8024-6eeecc0ce479)

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

### Additional information

BTW, i found some service cannot control with ui, and will spend costs.

![image](https://github.com/labring/sealos/assets/6964737/5d10fd7f-3db1-4de3-9c33-a875310794a9)

**Comment by moonrailgun** [comment]
BTW, i delete all apps.

Its my app launchpad

![image](https://github.com/labring/sealos/assets/6964737/2a6bf117-2241-4af2-9549-c422925460bd)

**Comment by bxy4543** [comment]
the terminal is started as a pod, so the terminal will also have a small cost.

**Comment by moonrailgun** [comment]
Yep, I wanna if i stop somthing, cost should be stop.

**Comment by bxy4543** [comment]
the terminal will be automatically deleted after a period of no request, because if you delete it immediately, it will affect the smoothness of the terminal.

**Comment by moonrailgun** [comment]
Obviously I'm not talking about the terminal.
I'm talking about databases and others like adminer and bytebase

**Comment by bxy4543** [comment]
👌I think this may be that the database has not been completely cleaned up and there are still residues. we will observe the problem and solve it

**Comment by moonrailgun** [comment]
Same with `adminer` and `bytebase`... 

I just wanna to use more sealos in the free bonus..

![image](https://github.com/labring/sealos/assets/6964737/c400d0b5-cc68-4e8b-9893-1cd98003b7cd)

Even though I haven't created any apps, the cost is the highest in the past few days

**Comment by bxy4543** [comment]
Please show all your resources by executing `kubectl get all`command

**Comment by moonrailgun** [comment]
![image](https://github.com/labring/sealos/assets/6964737/d030fcb4-c5dc-4df4-befa-c0efd148bc7e)
