### ISSUE TITLE
Feature: Modify directory /var/lib/containers/storage/overlay best practice

### ISSUE THREAD

**Issue by cuisongliu** [labring/sealos#3275]
### What is the problem this feature will solve?

change this directory /var/lib/containers/storage/overlay

using env or config to change 

ref: https://github.com/labring/sealos/issues/3228

**Comment by fengxsong** [comment]
PR #3293 added a debug log that informs the default storage config file path. Modify or add the `storage.graphroot` property in that file should meet your needs.
