### ISSUE TITLE
BUG: not include full i18n support

### ISSUE THREAD

**Issue by moonrailgun** [labring/sealos#3294]
### Sealos Version

v4.2

### How to reproduce the bug?

1. Open sealos cloud
2. Switch language to english
3. open builtin application like cost center/app launchpad
4. UI still display with chinese. 

### What is the expected behavior?

Show with english

### What do you see instead?

UI still display with chinese. 

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

### Additional information

I am ready to write document about deploy my application with sealos for globals. And i wanna take shot screens with full english.

BTW, I have switch my browser language with english first, and its not work.

![image](https://github.com/labring/sealos/assets/6964737/53fde365-e034-4e30-b63c-831d4d81d103)

**Comment by moonrailgun** [comment]
![0ddaac32abaf6e0be0374e963f71ee4](https://github.com/labring/sealos/assets/6964737/a807fd8a-dbea-4e34-a74d-e238cbf5d603)

I am glad to see this problem has been improve, but its still has no-i18n word in detail panel

**Comment by moonrailgun** [comment]
another problem is:

![image](https://github.com/labring/sealos/assets/6964737/c7b433f1-85de-4fbf-a78d-abbcf1c74656)

its should be a space between two words

**Comment by c121914yu** [comment]
Have already solved
