### ISSUE TITLE
arrch64 not yet supported

### ISSUE THREAD

**Issue by lx18511322835** [labring/sealos#3316]
### Sealos Version

v4.2.0

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

### Additional information

![图片](https://github.com/labring/sealos/assets/50075970/e1790a23-3e95-464c-96d9-ad704ecc6c95)

**Comment by cuisongliu** [comment]
arch 执行一下 ?

**Comment by lx18511322835** [comment]
![图片](https://github.com/labring/sealos/assets/50075970/707d70c0-b812-4670-aad0-6ac1372c608a)

**Comment by cuisongliu** [comment]
应该是主机上每个节点打印setlocate 的问题，需要看一下你服务的配置。是不是哪里不对。这个问题我先关了，有问题再提issue
