### ISSUE TITLE
BUG: add master  error

### ISSUE THREAD

**Issue by overstarry** [labring/sealos#3319]
### Sealos Version

4.2.0

### How to reproduce the bug?

sealos add --masters

### What is the expected behavior?

add success

### What do you see instead?

can't apply rootfs type images and version  not [v1beta1 v1beta2]

### Operating environment

```markdown
- Kubernetes version: 1.25.7
```

**Comment by cuisongliu** [comment]
The mirror version is wrong. Please download the mirror corresponding to the version.

**Comment by overstarry** [comment]
So how do I solve

**Comment by overstarry** [comment]
@cuisongliu

**Comment by cuisongliu** [comment]
kubernetes:v1.24.0-4.2.0

**Comment by overstarry** [comment]
info new cluster version v1.24.0 behind the current version v1.25.7

**Comment by overstarry** [comment]
@cuisongliu Can only be reset？
