### ISSUE TITLE
registry 5000 is heavily occupied, causing connection exhaustion

### ISSUE THREAD

**Issue by 37705109** [labring/sealos#3344]
### Sealos Version

v4.1.3

### How to reproduce the bug?

使用sealos v4.1.3版本部署的k8s 集群 v1.23.12版本，在运行一段时间后，会有大量的registry连接被占用导致服务器连接被耗尽
![`I%K$}E7QH0`YBK%4UF2UQ3](https://github.com/labring/sealos/assets/25220287/e51d790c-23c1-41f1-ad6a-390acf84fd43)

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cuisongliu** [comment]
替换最新的image-cri-shim即可
