### ISSUE TITLE
Feature: Port issues

### ISSUE THREAD

**Issue by juukee** [labring/sealos#3363]
### What is the problem this feature will solve?

After importing an image, only one port can be opened and cannot be bound to the image port inside the container

### What alternatives have you considered?

https://cloud.sealos.io/

**Comment by zzjin** [comment]
Currently, we have default support one port accessable by ingress controller, but anyone can edit svc/deploy yaml manually, by using `Terminal` app like a pro.

**Comment by juukee** [comment]
> Currently, we have default support one port accessable by ingress controller, but anyone can edit svc/deploy yaml manually, by using `Terminal` app like a pro.

But for users, visual editing will be more convenient and also an extension of this function,  This will be a huge improvement and change

**Comment by zzjin** [comment]
We have plan to support install `kuboard` with one click, which should resolve your problem?
As always, `AppLaunchpad` app is not an other k8s gui , but a cloudify app which cooperate well with other sealos apps.

**Comment by juukee** [comment]
one click maybe can resolve this problem, i not sure that cant provide multiport port and more easy to install.  
Based on my current experience, I am unable to install the application smoothly. 
My idea is that when I see a good GitHub warehouse, I can run it directly by clicking the button
