### ISSUE TITLE
When will ipv6 be available? Is there a plan for this?

### ISSUE THREAD

**Issue by AEGEGE** [labring/sealos#3365]
### Sealos Version

v4.2.0

### What is the expected behavior?

如题

### What do you see instead?

如题

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cuisongliu** [comment]
in plan v4.3.0  https://github.com/labring/sealos/issues/2919 this issue
