### ISSUE TITLE
BUG: brief description of the bug

### ISSUE THREAD

**Issue by EthanD4869** [labring/sealos#3367]
### Sealos Version

v4.2.0

### How to reproduce the bug?

1. Run 'sealos pull registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20230407@sha256:543c40fd093964bc9ab509d3e791f9989963021f1e9e4c9c7b6700b02bfb227b'
2. Run 'sealos save -o ingress-nginx-kube.tar registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20230407@sha256:543c40fd093964bc9ab509d3e791f9989963021f1e9e4c9c7b6700b02bfb227b'
3. Run 'sealos load --input ingress-nginx-kube.tar'

### What is the expected behavior?

Getting image source signatures
Copying blob db3f553fdf5e skipped: already exists  
Copying blob 80f00805faa8 skipped: already exists  
Copying blob a422c864361f skipped: already exists  
Copying blob c4629cdd872f skipped: already exists  
Copying blob 927ef23185e7 skipped: already exists  
Copying blob c23224575d87 skipped: already exists  
Copying blob b4aa04aa577f skipped: already exists  
Copying blob 4e700e4525b7 skipped: already exists  
Copying blob b49267e86090 skipped: already exists  
Copying blob f59b22b6c64c skipped: already exists  
Copying config 8479b0b5be done  
Writing manifest to image destination
Storing signatures
8479b0b5be55c4c4070adced2de08377663b076ae2dcb97b6011b61a90469b6d

### What do you see instead?

Error: Digest of source image's manifest would not match destination reference

### Operating environment

```markdown
- Sealos version:v4.2.0
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

### Additional information

tag一下就work了，考虑到是不是tag名太长的问题？
1. Run 'sealos pull registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20230407@sha256:543c40fd093964bc9ab509d3e791f9989963021f1e9e4c9c7b6700b02bfb227b'
2. Run 'sealos tag registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20230407@sha256:543c40fd093964bc9ab509d3e791f9989963021f1e9e4c9c7b6700b02bfb227b registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20230407'
3. Run 'sealos save -o ingress-nginx-kube.tar registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20230407'
4. Run 'sealos load --input ingress-nginx-kube.tar'

**Comment by cuisongliu** [comment]
sealos 管理的是集群镜像，并不是容器镜像，这么用意义不大。而且使用Digest 方式底层无法寻址到对应的镜像。
