### ISSUE TITLE
BUG: update time should be correct

### ISSUE THREAD

**Issue by moonrailgun** [labring/sealos#3375]
### Sealos Version

v4.2 cloud

### What is the expected behavior?

update time is a useful feature, although at most of time don't care hours.

But as a pro product, I think we should show diff with 24 hour and 12 hour format

If we use 12 hour, Its should display as 02:00:00 PM

If we use 24 hour, Its should display as 14:00:00

I have no idea what(or why) is 02:00:00.

### What do you see instead?

![image](https://github.com/labring/sealos/assets/6964737/908d0367-eb67-422a-8d70-804a80fcd76f)

![image](https://github.com/labring/sealos/assets/6964737/71e862d2-f2c8-47ed-81cc-1ff1e7dd59d6)

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by c121914yu** [comment]
![image](https://github.com/labring/sealos/assets/50446880/65abcf11-487c-4fee-94e4-f7bf5efba12a)
I am using the current browser time directly. 
I'm not quite sure what the problem is

**Comment by moonrailgun** [comment]
Maybe you should use `HH:mm:ss`(24 hour) or `hh:mm:ss a`(12 hour)

**Comment by c121914yu** [comment]
done
