### ISSUE TITLE
Feature: sealos save more than one images into a tar

### ISSUE THREAD

**Issue by lingdie** [labring/sealos#3400]
### What is the problem this feature will solve?

sealos save command can only save one image into a tar file at one time. There should be an enhancement for this.

![image](https://github.com/labring/sealos/assets/56745951/e1b8e56d-f94f-483d-8cb1-d4f8c22f3c83)

### If you have solution，please describe it

just like docker:
> docker save imageA imageB > t.tar

and

> docker load t.tar

I think we should support:

> sealos save -o t.tar imageA imageB imageC

and 

> sealos load -i t.tar

will load all these images.

**Comment by yangxggo** [comment]
sealos "save" calls push image logic, and the pushCmd function handles one image each time.It calls "buildah.Push" to do the real work. 
By the way, buildah can save multi images into one file,  but it only supports docker-archive.

**Comment by cuisongliu** [comment]
using merge is better, same buildah sdk not support it.

**Comment by fengxsong** [comment]
https://github.com/labring/sealos/pull/3442
