### ISSUE TITLE
BUG: The main node is the amd64 architecture, the child node is the arm64 architecture, and the installation machine reports an error

### ISSUE THREAD

**Issue by zhaops-hub** [labring/sealos#3411]
### Sealos Version

4.2.3

### How to reproduce the bug?

1. 安装主节点(linux/amd64)
2. 在主节点安装子节点(linux/arm64), 执行的命令: 
`sealos run labring/kubernetes:v1.25.0-arm64 --masters 192.168.31.37 -p 'soyuan.123' -f`
3. 安装报错
`[1/1]copying files to 192.168.31.37:22 100% [===============] (0/1, 0 it/min)2023-06-27T12:56:58 error Applied to cluster error: failed to copy rootfs default-kgxr5ehx: failed to copy entry /var/lib/containers/storage/overlay/e8256c18f8c615d79555eb05683232d0a8da2bd09aefbaab888ba303f054f8d9/merged/Kubefile -> /var/lib/sealos/data/default/rootfs/Kubefile to 192.168.31.37:22: sha256 sum not match /var/lib/containers/storage/overlay/e8256c18f8c615d79555eb05683232d0a8da2bd09aefbaab888ba303f054f8d9/merged/Kubefile(bff4a29c3c8b73d35cb6b4a0f191a4ba2b2139aa078dccc723bb3b9dad9e5f7d) != /var/lib/sealos/data/default/rootfs/Kubefile(a8d525332e2ec14b73bd82d17c3dae86b647ac7fbbecb07eb61ddea779d4a357), maybe network corruption?`

 
/var/lib/containers/storage/overlay/77bc6edbf85d490a16ef1c60285a6a3fe0d33d0e5f9a3a703d99d2d0f44cbc2a/merged/Kubefile
/var/lib/sealos/data/default/rootfs/Kubefile
比对一下把，这俩文件md5不一样。导致
 

### What is the expected behavior?

安装arm架构子节点成功.

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cuisongliu** [comment]
暂时还不支持异构
