### ISSUE TITLE
BUG: lvscare using  load balance traffic

### ISSUE THREAD

**Issue by luzejia** [labring/sealos#3416]
### Sealos Version

v4.1.4

### How to reproduce the bug?

1、use keepalived to implement a vip between two machine(real-server-1,real-server-2), and make sure vip is working normally
2、Use the following commands to load balance traffic through lvscare(execute on the above two machines)
```
./lvscare care --vs keepalived-vip:80 --rs real-server-1-ip:80 --rs real-server-2-ip:80 --mode link --run-once
```

### What is the expected behavior?

Accessing vip both outside the machine and inside the machine can achieve the effect of traffic load balancing

### What do you see instead?

When accessing vip from outside the machine, when the traffic is forwarded by vip-master to another real-server, it will not work.When the traffic is handled by the vip-master itself, it is normal.

Like this:

outer ------> vip-master(real-server-1) -------> real-server-1-nginx       ok
outer ------> vip-master(real-server-1) -------> real-server-2 -------> real-server-2-nginx      fail

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cuisongliu** [comment]
maybe using kube-vip + lvscare is better ?

**Comment by fanux** [comment]
@cuisongliu Why need kube-vip? Seems just run lvscare on client node, you can bind the vip on network interface. More info: https://github.com/labring/lvscare

**Comment by cuisongliu** [comment]
Linked mode doesn't seem to work. Traffic forwarding of the external machine failed. kube-vip handles external traffic and lvscare handles internal traffic. This is how it's been resolved so far.
