### ISSUE TITLE
how to visit the webui??

### ISSUE THREAD

**Issue by ivanmissu** [labring/sealos#3422]
i have installed the sealos.
<img width="1190" alt="image" src="https://github.com/labring/sealos/assets/8721615/e9bccdcc-d320-4d5e-a7e6-ae7da775a9f8">

how to visit sealoscloud webui ??

**Comment by fanux** [comment]
Here, only Kubernetes was installed, no web UI. The cluster image for Sealos is currently in production.

If needed, you can visit https://cloud.sealos.io
