### ISSUE TITLE
BUG: sealos UI can't create db by default config

### ISSUE THREAD

**Issue by xiaobiaozhao** [labring/sealos#3494]
### Sealos Version

4.4.2

### How to reproduce the bug?

<img width="824" alt="image" src="https://github.com/labring/sealos/assets/52393536/c32d5309-8ac3-4b1e-993c-c7083859960c">
<img width="546" alt="image" src="https://github.com/labring/sealos/assets/52393536/2563a050-c60e-4581-9d86-b083bca5f651">

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by lingdie** [comment]
@c121914yu plz close this issue after fix.

**Comment by c121914yu** [comment]
Which environment? cloud.sealos.io or private deployment

**Comment by lingdie** [comment]
> Which environment? cloud.sealos.io or private deployment

private deployment.

**Comment by sakcer** [comment]
To obtain more information by entering the following command in the terminal:
`kubectl describe clusters.apps.kubeblocks.io <database-name>`
Generally, you would need to apply this file: `kubectl apply -f sc.yaml`
```sc.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    cas.openebs.io/config: |
      - name: StorageType
        value: "hostpath"
      - name: BasePath
        value: "/var/openebs/local"
    openebs.io/cas-type: local
  name: openebs-backup
provisioner: openebs.io/local
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

**Comment by lingdie** [comment]
this pr will fixed this. https://github.com/labring/sealos/pull/3491
