### ISSUE TITLE
BUG: sealos apply abort after save clusterfile

### ISSUE THREAD

**Issue by cuisongliu** [labring/sealos#3547]
### Sealos Version

4.3.0

### How to reproduce the bug?

![image](https://github.com/labring/sealos/assets/4150905/aaa91f19-a5b6-45c7-91cd-98c2b851ca0d)

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by bxy4543** [comment]
not reproduced：
![image](https://github.com/labring/sealos/assets/69408038/63ce5792-b451-429e-a8dd-2fe3d6aac133)
