### ISSUE TITLE
BUG: The customer logo area at the bottom of the official homepage only has half of the Baidu logo

### ISSUE THREAD

**Issue by NMTuan** [labring/sealos#3551]
### Sealos Version

current

### How to reproduce the bug?

![image](https://github.com/labring/sealos/assets/2149763/b57b5a72-e4e3-48ec-804d-e41de0379e5e)

### What do you see instead?

显示一个完整logo把，不管是不是真客户，显示一半总显得不尊重

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by bxy4543** [comment]
https://sealos.io/ fix
