### ISSUE TITLE
BUG: brief description of the bug

### ISSUE THREAD

**Issue by lscool66** [labring/sealos#3573]
### Sealos Version

4.3.0-7ee53f1d

### How to reproduce the bug?

sealos run labring/kubernetes:v1.21.0 labring/helm:v3.8.2 labring/calico:v3.22.1

安装后coredns  Pending

### What is the expected behavior?

```
[root@fedora38 ~]# kubectl get pods -A
NAMESPACE         NAME                               READY   STATUS    RESTARTS   AGE
kube-system       coredns-74ff55c5b-58m75            0/1     Pending   0          21m
kube-system       coredns-74ff55c5b-qsssw            0/1     Pending   0          21m
kube-system       etcd-fedora38                      1/1     Running   1          42s
kube-system       kube-apiserver-fedora38            1/1     Running   1          43s
kube-system       kube-controller-manager-fedora38   1/1     Running   1          41s
kube-system       kube-proxy-rf4fw                   1/1     Running   0          21m
kube-system       kube-scheduler-fedora38            1/1     Running   0          43s
tigera-operator   tigera-operator-d499f5c8f-xndbv    1/1     Running   1          6m5s
[root@fedora38 ~]# kubectl describe -n kube-system pod coredns-74ff55c5b-58m75
Name:                 coredns-74ff55c5b-58m75
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 <none>
Labels:               k8s-app=kube-dns
                      pod-template-hash=74ff55c5b
Annotations:          <none>
Status:               Pending
IP:
IPs:                  <none>
Controlled By:        ReplicaSet/coredns-74ff55c5b
Containers:
  coredns:
    Image:       k8s.gcr.io/coredns:1.7.0
    Ports:       53/UDP, 53/TCP, 9153/TCP
    Host Ports:  0/UDP, 0/TCP, 0/TCP
    Args:
      -conf
      /etc/coredns/Corefile
    Limits:
      memory:  170Mi
    Requests:
      cpu:        100m
      memory:     70Mi
    Liveness:     http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:    http-get http://:8181/ready delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /etc/coredns from config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from coredns-token-sqf29 (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      coredns
    Optional:  false
  coredns-token-sqf29:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  coredns-token-sqf29
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  kubernetes.io/os=linux
Tolerations:     CriticalAddonsOnly op=Exists
                 node-role.kubernetes.io/control-plane:NoSchedule
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  6m37s                 default-scheduler  0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
  Warning  FailedScheduling  8m35s (x15 over 21m)  default-scheduler  0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
  Warning  FailedScheduling  48s                   default-scheduler  0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
[root@fedora38 ~]#

```

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by yangxggo** [comment]
are you sure you set the "labring/helm:v3.8.2" before "labring/calico:v3.22.1" ?

show the output of  `cat ~/.sealos/default/Clusterfile`

**Comment by lscool66** [comment]
> are you sure you set the "labring/helm:v3.8.2" before "labring/calico:v3.22.1" ?
> 
> show the output of `cat ~/.sealos/default/Clusterfile`

reset 重装好了。但是还有个问题
```
[root@fedora38 ~]# kubectl get pods -A
NAMESPACE           NAME                                       READY   STATUS    RESTARTS   AGE
calico-system       calico-kube-controllers-57fbd7bd59-vggxf   1/1     Running   0          7m12s
calico-system       calico-node-zfmrq                          1/1     Running   0          7m12s
calico-system       calico-typha-757f88568f-btxqv              1/1     Running   0          7m12s
kube-system         coredns-558bd4d5db-9dstb                   1/1     Running   0          7m18s
kube-system         coredns-558bd4d5db-fkcqt                   1/1     Running   0          7m18s
kube-system         etcd-fedora38                              1/1     Running   0          7m33s
kube-system         kube-apiserver-fedora38                    1/1     Running   0          7m33s
kube-system         kube-controller-manager-fedora38           1/1     Running   2          7m33s
kube-system         kube-proxy-jjqmh                           1/1     Running   0          7m18s
kube-system         kube-scheduler-fedora38                    1/1     Running   1          7m32s
kubesphere-system   ks-installer-846c78ddbf-d6nwv              1/1     Running   0          5m31s
tigera-operator     tigera-operator-d499f5c8f-zrp7r            1/1     Running   2          7m18s
```

装完kubesphere-system没有端口能访问页面


```
[root@fedora38 ~]# kubectl logs ks-installer-846c78ddbf-d6nwv -n kubesphere-system
2023-07-25T08:38:02+08:00 INFO     : shell-operator latest
2023-07-25T08:38:02+08:00 INFO     : HTTP SERVER Listening on 0.0.0.0:9115
2023-07-25T08:38:02+08:00 INFO     : Use temporary dir: /tmp/shell-operator
2023-07-25T08:38:02+08:00 INFO     : Initialize hooks manager ...
2023-07-25T08:38:02+08:00 INFO     : Search and load hooks ...
2023-07-25T08:38:02+08:00 INFO     : Load hook config from '/hooks/kubesphere/installRunner.py'
2023-07-25T08:38:02+08:00 INFO     : Load hook config from '/hooks/kubesphere/schedule.sh'
2023-07-25T08:38:02+08:00 INFO     : Initializing schedule manager ...
2023-07-25T08:38:02+08:00 INFO     : KUBE Init Kubernetes client
2023-07-25T08:38:02+08:00 INFO     : KUBE-INIT Kubernetes client is configured successfully
2023-07-25T08:38:02+08:00 INFO     : MAIN: run main loop
2023-07-25T08:38:02+08:00 INFO     : MAIN: add onStartup tasks
2023-07-25T08:38:02+08:00 INFO     : QUEUE add all HookRun@OnStartup
2023-07-25T08:38:02+08:00 INFO     : Running schedule manager ...
2023-07-25T08:38:02+08:00 INFO     : MSTOR Create new metric shell_operator_live_ticks
2023-07-25T08:38:02+08:00 INFO     : MSTOR Create new metric shell_operator_tasks_queue_length
2023-07-25T08:38:02+08:00 INFO     : GVR for kind 'ClusterConfiguration' is installer.kubesphere.io/v1alpha1, Resource=clusterconfigurations
2023-07-25T08:38:02+08:00 INFO     : EVENT Kube event '10421250-0062-4c5d-9145-ff66db350145'
2023-07-25T08:38:02+08:00 INFO     : QUEUE add TASK_HOOK_RUN@KUBE_EVENTS kubesphere/installRunner.py
2023-07-25T08:38:05+08:00 INFO     : TASK_RUN HookRun@KUBE_EVENTS kubesphere/installRunner.py
2023-07-25T08:38:05+08:00 INFO     : Running hook 'kubesphere/installRunner.py' binding 'KUBE_EVENTS' ...
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'

PLAY [localhost] ***************************************************************

TASK [download : Generating images list] ***************************************
skipping: [localhost]

TASK [download : Synchronizing images] *****************************************

TASK [kubesphere-defaults : KubeSphere | Setting images' namespace override] ***
skipping: [localhost]

TASK [kubesphere-defaults : KubeSphere | Configuring defaults] *****************
ok: [localhost] => {
    "msg": "Check roles/kubesphere-defaults/defaults/main.yml"
}

TASK [preinstall : KubeSphere | Stopping if Kubernetes version is nonsupport] ***
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [preinstall : KubeSphere | Checking StorageClass] *************************
changed: [localhost]

TASK [preinstall : KubeSphere | Stopping if StorageClass was not found] ********
skipping: [localhost]

TASK [preinstall : KubeSphere | Checking default StorageClass] *****************
changed: [localhost]

TASK [preinstall : KubeSphere | Stopping if default StorageClass was not found] ***
fatal: [localhost]: FAILED! => {
    "assertion": "\"(default)\" in default_storage_class_check.stdout",
    "changed": false,
    "evaluated_to": false,
    "msg": "Default StorageClass was not found !"
}

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=1    skipped=4    rescued=0    ignored=0
```

日志有报错

**Comment by lscool66** [comment]
> > are you sure you set the "labring/helm:v3.8.2" before "labring/calico:v3.22.1" ?
> > show the output of `cat ~/.sealos/default/Clusterfile`
> 
> reset 重装好了。但是还有个问题
> 
> ```
> [root@fedora38 ~]# kubectl get pods -A
> NAMESPACE           NAME                                       READY   STATUS    RESTARTS   AGE
> calico-system       calico-kube-controllers-57fbd7bd59-vggxf   1/1     Running   0          7m12s
> calico-system       calico-node-zfmrq                          1/1     Running   0          7m12s
> calico-system       calico-typha-757f88568f-btxqv              1/1     Running   0          7m12s
> kube-system         coredns-558bd4d5db-9dstb                   1/1     Running   0          7m18s
> kube-system         coredns-558bd4d5db-fkcqt                   1/1     Running   0          7m18s
> kube-system         etcd-fedora38                              1/1     Running   0          7m33s
> kube-system         kube-apiserver-fedora38                    1/1     Running   0          7m33s
> kube-system         kube-controller-manager-fedora38           1/1     Running   2          7m33s
> kube-system         kube-proxy-jjqmh                           1/1     Running   0          7m18s
> kube-system         kube-scheduler-fedora38                    1/1     Running   1          7m32s
> kubesphere-system   ks-installer-846c78ddbf-d6nwv              1/1     Running   0          5m31s
> tigera-operator     tigera-operator-d499f5c8f-zrp7r            1/1     Running   2          7m18s
> ```
> 
> 装完kubesphere-system没有端口能访问页面
> 
> ```
> [root@fedora38 ~]# kubectl logs ks-installer-846c78ddbf-d6nwv -n kubesphere-system
> 2023-07-25T08:38:02+08:00 INFO     : shell-operator latest
> 2023-07-25T08:38:02+08:00 INFO     : HTTP SERVER Listening on 0.0.0.0:9115
> 2023-07-25T08:38:02+08:00 INFO     : Use temporary dir: /tmp/shell-operator
> 2023-07-25T08:38:02+08:00 INFO     : Initialize hooks manager ...
> 2023-07-25T08:38:02+08:00 INFO     : Search and load hooks ...
> 2023-07-25T08:38:02+08:00 INFO     : Load hook config from '/hooks/kubesphere/installRunner.py'
> 2023-07-25T08:38:02+08:00 INFO     : Load hook config from '/hooks/kubesphere/schedule.sh'
> 2023-07-25T08:38:02+08:00 INFO     : Initializing schedule manager ...
> 2023-07-25T08:38:02+08:00 INFO     : KUBE Init Kubernetes client
> 2023-07-25T08:38:02+08:00 INFO     : KUBE-INIT Kubernetes client is configured successfully
> 2023-07-25T08:38:02+08:00 INFO     : MAIN: run main loop
> 2023-07-25T08:38:02+08:00 INFO     : MAIN: add onStartup tasks
> 2023-07-25T08:38:02+08:00 INFO     : QUEUE add all HookRun@OnStartup
> 2023-07-25T08:38:02+08:00 INFO     : Running schedule manager ...
> 2023-07-25T08:38:02+08:00 INFO     : MSTOR Create new metric shell_operator_live_ticks
> 2023-07-25T08:38:02+08:00 INFO     : MSTOR Create new metric shell_operator_tasks_queue_length
> 2023-07-25T08:38:02+08:00 INFO     : GVR for kind 'ClusterConfiguration' is installer.kubesphere.io/v1alpha1, Resource=clusterconfigurations
> 2023-07-25T08:38:02+08:00 INFO     : EVENT Kube event '10421250-0062-4c5d-9145-ff66db350145'
> 2023-07-25T08:38:02+08:00 INFO     : QUEUE add TASK_HOOK_RUN@KUBE_EVENTS kubesphere/installRunner.py
> 2023-07-25T08:38:05+08:00 INFO     : TASK_RUN HookRun@KUBE_EVENTS kubesphere/installRunner.py
> 2023-07-25T08:38:05+08:00 INFO     : Running hook 'kubesphere/installRunner.py' binding 'KUBE_EVENTS' ...
> [WARNING]: No inventory was parsed, only implicit localhost is available
> [WARNING]: provided hosts list is empty, only localhost is available. Note that
> the implicit localhost does not match 'all'
> 
> PLAY [localhost] ***************************************************************
> 
> TASK [download : Generating images list] ***************************************
> skipping: [localhost]
> 
> TASK [download : Synchronizing images] *****************************************
> 
> TASK [kubesphere-defaults : KubeSphere | Setting images' namespace override] ***
> skipping: [localhost]
> 
> TASK [kubesphere-defaults : KubeSphere | Configuring defaults] *****************
> ok: [localhost] => {
>     "msg": "Check roles/kubesphere-defaults/defaults/main.yml"
> }
> 
> TASK [preinstall : KubeSphere | Stopping if Kubernetes version is nonsupport] ***
> ok: [localhost] => {
>     "changed": false,
>     "msg": "All assertions passed"
> }
> 
> TASK [preinstall : KubeSphere | Checking StorageClass] *************************
> changed: [localhost]
> 
> TASK [preinstall : KubeSphere | Stopping if StorageClass was not found] ********
> skipping: [localhost]
> 
> TASK [preinstall : KubeSphere | Checking default StorageClass] *****************
> changed: [localhost]
> 
> TASK [preinstall : KubeSphere | Stopping if default StorageClass was not found] ***
> fatal: [localhost]: FAILED! => {
>     "assertion": "\"(default)\" in default_storage_class_check.stdout",
>     "changed": false,
>     "evaluated_to": false,
>     "msg": "Default StorageClass was not found !"
> }
> 
> PLAY RECAP *********************************************************************
> localhost                  : ok=4    changed=2    unreachable=0    failed=1    skipped=4    rescued=0    ignored=0
> ```
> 
> 日志有报错

解决了 需要有个存储方面的镜像
``sealos run registry.cn-shenzhen.aliyuncs.com/cnmirror/openebs:v3.4.0 \
registry.cn-shenzhen.aliyuncs.com/cnmirror/kubesphere:v3.3.2``
