### ISSUE TITLE
sealos4.2.3 use the command sealos add --nodes 1.1.1.1, error error Applied to cluster error: exit status 1

### ISSUE THREAD

**Issue by huyleyye** [labring/sealos#3597]
![image](https://github.com/labring/sealos/assets/54439900/a0ba23c9-dd00-46d9-bdcd-310c6ddaae4c)

**Comment by huyleyye** [comment]
need help

**Comment by huyleyye** [comment]
Kubernetes1.16.15

**Comment by bxy4543** [comment]
add `--debug` after the command to print the log?

**Comment by huyleyye** [comment]
> add `--debug` after the command to print the log?


debug failed to exec remote 1.1.1.1:22 shell: /var/lib/sealos/data/default/rootfs/opt/sealctl token /root/.sealos/default/etc/kubeadm-init.yaml 9108b3fb10f469ba77c1d84f79f44fb8e042d17ab8d957c67d12e646a119c3aa output: &{default} error: exit status 1

**Comment by cuisongliu** [comment]
version is to lower, need using kubernetes v1.18+

**Comment by huyleyye** [comment]
> 

what a bad thing it is

**Comment by huyleyye** [comment]
> 

Is there any solution to the 1.16.15 version of k8s?

**Comment by cuisongliu** [comment]
> Is there any solution to the 1.16.15 version of k8s?

nothing, kubeadm not support it.

**Comment by cuisongliu** [comment]
Version 1.16 is too low. I suggest to upgrade the version

**Comment by huyleyye** [comment]
> 1.16版本太低了。我建议升级版本

谢谢，我会采取手动安装再试试
