### ISSUE TITLE
BUG: delete dockerhub kubesphere arm image

### ISSUE THREAD

**Issue by willzhang** [labring/sealos#3618]
### Sealos Version

v4.3.0

### How to reproduce the bug?

Kubesphere does not support the arm operating system，because some upstream images that kubesphere relies on do not have an arm architecture. Please remove this image from dockerhub to avoid misleading users.
```
docker.io/labring/kubesphere:v3.3.0-arm64
```

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cuisongliu** [comment]
done
