### ISSUE TITLE
BUG: brief description of the bug

### ISSUE THREAD

**Issue by Zhou555555** [labring/sealos#3625]
### Sealos Version

3.3.9

### How to reproduce the bug?

 sealos init --passwd '123456' --master 172.16.2.29 --node 172.16.2.50 --pkg-url /root/kube1.19.16.tar.gz  --version v1.19.16
![image](https://github.com/labring/sealos/assets/91447081/7f1580a5-39a3-4dd9-90ea-6cc364f8cd4f)
图片中的三个报错对k8s使用有没有影响呢？需要如何修正呢

### Operating environment

```markdown
- Sealos version:3.3.9
- Docker version:20.10.7
- Kubernetes version:1.19.16
- Operating system:麒麟v10(arm)
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cuisongliu** [comment]
没有影响，3.x已经不维护，如果需要可能需要自己改代码了。
