### ISSUE TITLE
Feature: sealos 应用使用多个域名访问

### ISSUE THREAD

**Issue by kxkxpack** [labring/sealos#3632]
### What is the problem this feature will solve?

请问下，什么时候可以支持多个域名绑定呢

**Comment by cuisongliu** [comment]
没太明白你的意思，支持绑定多个域名？哪个模块？

**Comment by kxkxpack** [comment]
> 没太明白你的意思，支持绑定多个域名？哪个模块？

就是一个应用里绑定多个域名

**Comment by kxkxpack** [comment]
> 

YES ,就是这个意思，比如我创建个A应用，A应用只能绑定一个域名，不是特别方便

**Comment by kxkxpack** [comment]
![image](https://github.com/labring/sealos/assets/131777219/557a3088-ec0d-464f-8746-7ee4eacc334a)
就是这儿，能不能多绑定几个

**Comment by zzjin** [comment]
Currently you can apply more `Ingress` CRs maunally using `Terminal` app.
You can use command `kubectl get ingress` to check how other route works.

Note: Could you provide some additional infomations about where and why you want to add more outside domains for your application? We can consider whether to add this feature on `launchpad` app.

---

目前可以通过在 `Terminal` 里面手动新增一个 `Ingress` 的 `CR` 的方式来新增一个域名
`kubectl get ingress` 可以查看目前的路由的写法

Note: 能够给一下是需要什么应用有多个域名的访问需求吗? 我们可以做一下调研看是否需要做到 `launchpad` 界面上

**Comment by kxkxpack** [comment]
> Currently you can apply more `Ingress` CRs maunally using `Terminal` app. You can use command `kubectl get ingress` to check how other route works.
> 
> Note: Could you provide some additional infomations about where and why you want to add more outside domains for your application? We can consider whether to add this feature on `launchpad` app.
> 
> 目前可以通过在 `Terminal` 里面手动新增一个 `Ingress` 的 `CR` 的方式来新增一个域名 `kubectl get ingress` 可以查看目前的路由的写法
> 
> Note: 能够给一下是需要什么应用有多个域名的访问需求吗? 我们可以做一下调研看是否需要做到 `launchpad` 界面上



> Currently you can apply more `Ingress` CRs maunally using `Terminal` app. You can use command `kubectl get ingress` to check how other route works.
> 
> Note: Could you provide some additional infomations about where and why you want to add more outside domains for your application? We can consider whether to add this feature on `launchpad` app.
> 
> 目前可以通过在 `Terminal` 里面手动新增一个 `Ingress` 的 `CR` 的方式来新增一个域名 `kubectl get ingress` 可以查看目前的路由的写法
> 
> Note: 能够给一下是需要什么应用有多个域名的访问需求吗? 我们可以做一下调研看是否需要做到 `launchpad` 界面上

ONE-API  需要调用API   用单独的一个域名去调用比较好
