### ISSUE TITLE
BUG: Unable to install again after uninstalling the app

### ISSUE THREAD

**Issue by fangzhengjin** [labring/sealos#3700]
### Sealos Version

v4.3.0

### How to reproduce the bug?

1. 安装ingress: `sealos run docker.io/labring/ingress-nginx:v1.8.0`
2. 卸载ingress `sealos run docker.io/labring/ingress-nginx:v1.8.0 -e uninstall=true`
3. 再次安装会提示
<img width="801" alt="image" src="https://github.com/labring/sealos/assets/12680972/e75541be-d363-40fd-90d4-0776bd242252">

经检查发现, uninstall 被写在了集群配置文件中, 也就是说目前只有执行过卸载, 任何应用都将无法安装, 需要手动将下方环境变量删掉方可正常安装
<img width="499" alt="image" src="https://github.com/labring/sealos/assets/12680972/cd215a1d-c30c-47e7-94f7-fe3b62bba9b1">

**Comment by willzhang** [comment]
related to this issue:
https://github.com/labring/sealos/issues/3657

**Comment by cuisongliu** [comment]
using main sealos
