### ISSUE TITLE
BUG: Unable to find the correct clusterfile path after customizing the cluster name

### ISSUE THREAD

**Issue by Esun127** [labring/sealos#3716]
### Sealos Version

4.3.0

### How to reproduce the bug?

1, 使用sealos run --cluster myk8s ...
2, 使用sealos gen --cluster myk8s ... > cluster.yaml
    sealos apply -f cluster.yaml

### Operating environment

```markdown
- Sealos version: v4.3.0
- Docker version:  
- Kubernetes version: 
- Operating system: centos 7.9
- Runtime environment:
- Cluster size: 3 nodes
- Additional information:
```

**Comment by bxy4543** [comment]
sealos gen --cluster myk8s ...  -o clusterfile.yaml
