### ISSUE TITLE
BUG: brief description of the bug

### ISSUE THREAD

**Issue by lopman87** [labring/sealos#3731]
### Sealos Version

3.3.9-rc.11

### How to reproduce the bug?

1.麒麟v10操作系统
2.安装kube1.18.14

### What is the expected behavior?

安装成功

### What do you see instead?

![image](https://github.com/labring/sealos/assets/10387219/fe5ee2ff-1324-4f7a-8e19-750b87b1df6b)

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by lopman87** [comment]
安装失败，大佬们怎么解决啊

**Comment by cuisongliu** [comment]
3.x不做维护，请在4.x上测试后提交issue
