### ISSUE TITLE
BUG: After the sealos cloud is deployed, the applaunchpad-related certificate prompts that it is untrustworthy

### ISSUE THREAD

**Issue by JasonRinnki** [labring/sealos#3752]
### Sealos Version

v4.3.0

### How to reproduce the bug?

主域名上传证书没有问题，但是其它的域名都提示不可信
![image](https://github.com/labring/sealos/assets/135125734/89349a52-870c-487b-a960-1b0193a540a4)
![image](https://github.com/labring/sealos/assets/135125734/d8fce8a4-a052-46fe-80f6-ce7f95dfbe29)
这个如何解决

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by bxy4543** [comment]
自信任 证书

**Comment by JasonRinnki** [comment]
好的，谢谢
