### ISSUE TITLE
Feature: kubefile rander tmpl files preview.

### ISSUE THREAD

**Issue by lingdie** [labring/sealos#3774]
### What is the problem this feature will solve?

![img_v2_6459e403-f34a-48ed-bad6-09a6ed55ae4g](https://github.com/labring/sealos/assets/56745951/e4c8a915-f7d7-4c8f-983c-8d05c72c3ef2)

I hope to previe what will be generated after `sealos run` but not run `sealos run`.

**Comment by cuisongliu** [comment]
sealos create --env xxx
