### ISSUE TITLE
BUG: when registry node is not master0 , and registry login method is not default

### ISSUE THREAD

**Issue by cuisongliu** [labring/sealos#3783]
### Sealos Version

4.3.2

### How to reproduce the bug?

<img width="1181" alt="image" src="https://github.com/labring/sealos/assets/4150905/44fd4092-4cd1-47db-9ace-f8c2f1b5e4c1">

When obtaining the registry node, if its login method is not the default, an error may be reported

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cuisongliu** [comment]
由于场景特殊，先加个日志，等后续出现问题在修复。

**Comment by cuisongliu** [comment]
1. master0 22端口，且新增一个registry角色的node（端口2222）作为镜像仓库
2. 新增一个node node是非免密登录，使用密码添加节点获取不到registry的信息导致添加失败。

**Comment by yangxggo** [comment]
assign

**Comment by yangxggo** [comment]
cannot reproduce it.

**Comment by cuisongliu** [comment]
![image](https://github.com/labring/sealos/assets/4150905/84749a4a-83ec-43b6-8fb4-fd36fa0f7b42)
![image](https://github.com/labring/sealos/assets/4150905/55ec61ba-341f-4796-bf95-93fc94b844f4)
