### ISSUE TITLE
sealos run docker.io/labring/sealos-cloud:latest 报错  scripts/init.sh: line 79: sealos: command not found

### ISSUE THREAD

**Issue by yssy2519** [labring/sealos#3794]
### Sealos Version

4.3.0

### How to reproduce the bug?

sealos run docker.io/labring/sealos-cloud:latest\
    --env cloudDomain="116.204.76.109.nip.io"

### What do you see instead?

192.168.0.83:22 ++ tr -cd a-z0-9
192.168.0.83:22 ++ head -c64
192.168.0.83:22 ++ base64 -w 0
192.168.0.83:22 + sed -i -e 's;<your-jwt-secret-base64>;bGRicm81cWM3NWcxeTAwejhmdm9uNWFlcDRjNzY5cXl6b3hrazFjM2k1dDA4OHh0OWs2OHZjbzQ0OTczNXNoMQ==;' etc/sealos/desktop-config.yaml
192.168.0.83:22 + sed -i -e 's;<your-password-salt-base64>;bm1yZGg0c3A5MTZiaDEwNTc1ajl2bG5yN3UyZmNjbGpqOHZiNG9nMG1ycW4yNXFkNW9yN3Z4Y2xxNWF0OHd6Zg==;' etc/sealos/desktop-config.yaml
192.168.0.83:22 + create_tls_secret
192.168.0.83:22 + grep -q '<tls-crt-placeholder>' manifests/tls-secret.yaml
192.168.0.83:22 + echo 'mock tls secret'
192.168.0.83:22 mock tls secret
192.168.0.83:22 + kubectl apply -f manifests/mock-cert.yaml
192.168.0.83:22 clusterissuer.cert-manager.io/selfsigned-issuer unchanged
192.168.0.83:22 certificate.cert-manager.io/sealos-cloud unchanged
192.168.0.83:22 + echo 'mock tls cert has been created successfully.'
192.168.0.83:22 mock tls cert has been created successfully.
192.168.0.83:22 + sealos_run_controller
192.168.0.83:22 + sealos run tars/user.tar --env cloudDomain=116.204.76.109.nip.io --env apiserverPort=6443
192.168.0.83:22 scripts/init.sh: line 79: sealos: command not found
Error: run command `export SEALOS_SYS_KUBE_VERSION="v1.25.6" sandboxImage="pause:3.8" cloudDomain="116.204.76.109.nip.io" cloudPort="" SEALOS_SYS_CRI_ENDPOINT="/var/run/containerd/containerd.sock" registryData="/var/lib/registry" registryConfig="/etc/registry" SEALOS_SYS_SEALOS_VERSION="4.3.0" mongodbUri="" policy="default" criData="/var/lib/containerd" registryPassword="passw0rd" defaultVIP="10.103.97.2" disableApparmor="false" registryDomain="sealos.hub" registryPort="5000" registryUsername="admin" ; cd /var/lib/sealos/data/default/applications/default-hn5mcdym/workdir && bash scripts/init.sh` on 192.168.0.83:22, output: + cloudDomain=127.0.0.1.nip.io

mock tls cert has been created successfully.
+ sealos_run_controller
+ sealos run tars/user.tar --env cloudDomain=116.204.76.109.nip.io --env apiserverPort=6443
scripts/init.sh: line 79: sealos: command not found
, error: Process exited with status 127,

### Operating environment

```markdown
安装流程和版本是这样的 前面都正常 安装desktop的时候报错了
sealos gen labring/kubernetes:v1.25.6 \
    labring/helm:v3.12.0 \
    labring/calico:v3.24.1 \
    labring/cert-manager:v1.8.0 \
    labring/openebs:v3.4.0 \
    --masters xxxxx \
    --nodes xxxxx,xxxxx > Clusterfile

sealos run docker.io/labring/kubernetes-reflector:v7.0.151\
    docker.io/labring/ingress-nginx:v1.5.1\
    docker.io/labring/zot:v1.4.3\
    docker.io/labring/kubeblocks:v0.5.3\
    --env policy=anonymousPolicy\
    --config-file ingress-nginx-config.yaml

执行到这里报错了
sealos run docker.io/labring/sealos-cloud:latest\
    --env cloudDomain="116.204.76.109.nip.io"
```

**Comment by lingdie** [comment]
run cmd `which sealos`.

**Comment by yssy2519** [comment]
> `which sealos`

![image](https://github.com/labring/sealos/assets/31470889/98e20f86-d1de-4925-ac7c-0ee36fc7b52b)

**Comment by lingdie** [comment]
log shows `sealos: command not found`, please add more information about this.

**Comment by yssy2519** [comment]
> 日志显示`sealos: command not found`，请添加更多相关信息。

[root@ecs-1927-0002 ~]# sealos run docker.io/labring/sealos-cloud:latest\
>     --env cloudDomain="116.204.76.109.nip.io"
2023-08-30T09:37:48 info start to install app in this cluster
2023-08-30T09:37:48 info Executing SyncStatusAndCheck Pipeline in InstallProcessor
2023-08-30T09:37:48 info Executing ConfirmOverrideApps Pipeline in InstallProcessor
2023-08-30T09:37:48 info are you sure to override these following apps?
docker.io/labring/sealos-cloud:latest
Yes [y/yes], No [n/no]: yes
2023-08-30T09:37:53 info Executing PreProcess Pipeline in InstallProcessor
2023-08-30T09:37:53 info Executing pipeline MountRootfs in InstallProcessor.
[1/1]copying files to 192.168.0.83:22 100% [===============] (0/13, 0 it/min)2023-08-30T09:38:08 info Executing pipeline MirrorRegistry in InstallProcessor.
2023-08-30T09:38:08 info Executing UpgradeIfNeed Pipeline in InstallProcessor
192.168.0.83:22 + cloudDomain=127.0.0.1.nip.io
192.168.0.83:22 + cloudPort=
192.168.0.83:22 + mongodbUri=
192.168.0.83:22 + tlsCrtPlaceholder='<tls-crt-placeholder>'
192.168.0.83:22 + tlsKeyPlaceholder='<tls-key-placeholder>'
192.168.0.83:22 + saltKey=
192.168.0.83:22 + install
192.168.0.83:22 + prepare
192.168.0.83:22 + source etc/sealos/.env
192.168.0.83:22 ++ cloudDomain=116.204.76.109.nip.io
192.168.0.83:22 ++ cloudPort=
192.168.0.83:22 ++ mongodbUri=
192.168.0.83:22 + kubectl apply -f manifests/namespace.yaml
192.168.0.83:22 namespace/sealos-system unchanged
192.168.0.83:22 namespace/sealos unchanged
192.168.0.83:22 + kubectl apply -f manifests/notifications_crd.yaml
192.168.0.83:22 customresourcedefinition.apiextensions.k8s.io/notifications.notification.sealos.io unchanged
192.168.0.83:22 + gen_mongodbUri
192.168.0.83:22 + '[' -z '' ']'
192.168.0.83:22 + echo 'no mongodb uri found, create mongodb and gen mongodb uri'
192.168.0.83:22 no mongodb uri found, create mongodb and gen mongodb uri
192.168.0.83:22 + kubectl apply -f manifests/mongodb.yaml
192.168.0.83:22 cluster.apps.kubeblocks.io/sealos-mongodb unchanged
192.168.0.83:22 serviceaccount/sealos-mongodb-sa unchanged
192.168.0.83:22 role.rbac.authorization.k8s.io/sealos-mongodb-role unchanged
192.168.0.83:22 rolebinding.rbac.authorization.k8s.io/sealos-mongodb-rolebinding unchanged
192.168.0.83:22 ++ kubectl get secret -n sealos sealos-mongodb-conn-credential
192.168.0.83:22 + '[' -z 'NAME                             TYPE     DATA   AGE
192.168.0.83:22 sealos-mongodb-conn-credential   Opaque   8      16h' ']'
192.168.0.83:22 + chmod +x scripts/gen-mongodb-uri.sh
192.168.0.83:22 ++ scripts/gen-mongodb-uri.sh
192.168.0.83:22 + mongodbUri=mongodb://root:9jpn8kfc@sealos-mongodb-mongodb-0.sealos-mongodb-mongodb-headless.sealos.svc:27017
192.168.0.83:22 + gen_saltKey
192.168.0.83:22 ++ kubectl get secret desktop-frontend-secret -n sealos -o 'jsonpath={.data.password_salt}'
192.168.0.83:22 ++ true
192.168.0.83:22 + password_salt=
192.168.0.83:22 + [[ -z '' ]]
192.168.0.83:22 ++ tr -dc a-z0-9
192.168.0.83:22 ++ head -c64
192.168.0.83:22 ++ base64 -w 0
192.168.0.83:22 + saltKey=bm1yZGg0c3A5MTZiaDEwNTc1ajl2bG5yN3UyZmNjbGpqOHZiNG9nMG1ycW4yNXFkNW9yN3Z4Y2xxNWF0OHd6Zg==
192.168.0.83:22 + mutate_desktop_config
192.168.0.83:22 ++ echo -n mongodb://root:9jpn8kfc@sealos-mongodb-mongodb-0.sealos-mongodb-mongodb-headless.sealos.svc:27017
192.168.0.83:22 ++ base64 -w 0
192.168.0.83:22 + sed -i -e 's;<your-mongodb-uri-base64>;bW9uZ29kYjovL3Jvb3Q6OWpwbjhrZmNAc2VhbG9zLW1vbmdvZGItbW9uZ29kYi0wLnNlYWxvcy1tb25nb2RiLW1vbmdvZGItaGVhZGxlc3Muc2VhbG9zLnN2YzoyNzAxNw==;' etc/sealos/desktop-config.yaml
192.168.0.83:22 ++ tr -cd a-z0-9
192.168.0.83:22 ++ head -c64
192.168.0.83:22 ++ base64 -w 0
192.168.0.83:22 + sed -i -e 's;<your-jwt-secret-base64>;bGRicm81cWM3NWcxeTAwejhmdm9uNWFlcDRjNzY5cXl6b3hrazFjM2k1dDA4OHh0OWs2OHZjbzQ0OTczNXNoMQ==;' etc/sealos/desktop-config.yaml
192.168.0.83:22 + sed -i -e 's;<your-password-salt-base64>;bm1yZGg0c3A5MTZiaDEwNTc1ajl2bG5yN3UyZmNjbGpqOHZiNG9nMG1ycW4yNXFkNW9yN3Z4Y2xxNWF0OHd6Zg==;' etc/sealos/desktop-config.yaml
192.168.0.83:22 + create_tls_secret
192.168.0.83:22 + grep -q '<tls-crt-placeholder>' manifests/tls-secret.yaml
192.168.0.83:22 + echo 'mock tls secret'
192.168.0.83:22 mock tls secret
192.168.0.83:22 + kubectl apply -f manifests/mock-cert.yaml
192.168.0.83:22 clusterissuer.cert-manager.io/selfsigned-issuer unchanged
192.168.0.83:22 certificate.cert-manager.io/sealos-cloud unchanged
192.168.0.83:22 + echo 'mock tls cert has been created successfully.'
192.168.0.83:22 mock tls cert has been created successfully.
192.168.0.83:22 + sealos_run_controller
192.168.0.83:22 + sealos run tars/user.tar --env cloudDomain=116.204.76.109.nip.io --env apiserverPort=6443
192.168.0.83:22 scripts/init.sh: line 79: sealos: command not found
Error: run command `export SEALOS_SYS_KUBE_VERSION="v1.25.6" sandboxImage="pause:3.8" cloudDomain="116.204.76.109.nip.io" cloudPort="" SEALOS_SYS_CRI_ENDPOINT="/var/run/containerd/containerd.sock" registryData="/var/lib/registry" registryConfig="/etc/registry" SEALOS_SYS_SEALOS_VERSION="4.3.0" mongodbUri="" policy="default" criData="/var/lib/containerd" registryPassword="passw0rd" defaultVIP="10.103.97.2" disableApparmor="false" registryDomain="sealos.hub" registryPort="5000" registryUsername="admin" ; cd /var/lib/sealos/data/default/applications/default-hn5mcdym/workdir && bash scripts/init.sh` on 192.168.0.83:22, output: + cloudDomain=127.0.0.1.nip.io
+ cloudPort=
+ mongodbUri=
+ tlsCrtPlaceholder='<tls-crt-placeholder>'
+ tlsKeyPlaceholder='<tls-key-placeholder>'
+ saltKey=
+ install
+ prepare
+ source etc/sealos/.env
++ cloudDomain=116.204.76.109.nip.io
++ cloudPort=
++ mongodbUri=
+ kubectl apply -f manifests/namespace.yaml
namespace/sealos-system unchanged
namespace/sealos unchanged
+ kubectl apply -f manifests/notifications_crd.yaml
customresourcedefinition.apiextensions.k8s.io/notifications.notification.sealos.io unchanged
+ gen_mongodbUri
+ '[' -z '' ']'
+ echo 'no mongodb uri found, create mongodb and gen mongodb uri'
no mongodb uri found, create mongodb and gen mongodb uri
+ kubectl apply -f manifests/mongodb.yaml
cluster.apps.kubeblocks.io/sealos-mongodb unchanged
serviceaccount/sealos-mongodb-sa unchanged
role.rbac.authorization.k8s.io/sealos-mongodb-role unchanged
rolebinding.rbac.authorization.k8s.io/sealos-mongodb-rolebinding unchanged
++ kubectl get secret -n sealos sealos-mongodb-conn-credential
+ '[' -z 'NAME                             TYPE     DATA   AGE
sealos-mongodb-conn-credential   Opaque   8      16h' ']'
+ chmod +x scripts/gen-mongodb-uri.sh
++ scripts/gen-mongodb-uri.sh
+ mongodbUri=mongodb://root:9jpn8kfc@sealos-mongodb-mongodb-0.sealos-mongodb-mongodb-headless.sealos.svc:27017
+ gen_saltKey
++ kubectl get secret desktop-frontend-secret -n sealos -o 'jsonpath={.data.password_salt}'
++ true
+ password_salt=
+ [[ -z '' ]]
++ tr -dc a-z0-9
++ head -c64
++ base64 -w 0
+ saltKey=bm1yZGg0c3A5MTZiaDEwNTc1ajl2bG5yN3UyZmNjbGpqOHZiNG9nMG1ycW4yNXFkNW9yN3Z4Y2xxNWF0OHd6Zg==
+ mutate_desktop_config
++ echo -n mongodb://root:9jpn8kfc@sealos-mongodb-mongodb-0.sealos-mongodb-mongodb-headless.sealos.svc:27017
++ base64 -w 0
+ sed -i -e 's;<your-mongodb-uri-base64>;bW9uZ29kYjovL3Jvb3Q6OWpwbjhrZmNAc2VhbG9zLW1vbmdvZGItbW9uZ29kYi0wLnNlYWxvcy1tb25nb2RiLW1vbmdvZGItaGVhZGxlc3Muc2VhbG9zLnN2YzoyNzAxNw==;' etc/sealos/desktop-config.yaml
++ tr -cd a-z0-9
++ head -c64
++ base64 -w 0
+ sed -i -e 's;<your-jwt-secret-base64>;bGRicm81cWM3NWcxeTAwejhmdm9uNWFlcDRjNzY5cXl6b3hrazFjM2k1dDA4OHh0OWs2OHZjbzQ0OTczNXNoMQ==;' etc/sealos/desktop-config.yaml
+ sed -i -e 's;<your-password-salt-base64>;bm1yZGg0c3A5MTZiaDEwNTc1ajl2bG5yN3UyZmNjbGpqOHZiNG9nMG1ycW4yNXFkNW9yN3Z4Y2xxNWF0OHd6Zg==;' etc/sealos/desktop-config.yaml
+ create_tls_secret
+ grep -q '<tls-crt-placeholder>' manifests/tls-secret.yaml
+ echo 'mock tls secret'
mock tls secret
+ kubectl apply -f manifests/mock-cert.yaml
clusterissuer.cert-manager.io/selfsigned-issuer unchanged
certificate.cert-manager.io/sealos-cloud unchanged
+ echo 'mock tls cert has been created successfully.'
mock tls cert has been created successfully.
+ sealos_run_controller
+ sealos run tars/user.tar --env cloudDomain=116.204.76.109.nip.io --env apiserverPort=6443
scripts/init.sh: line 79: sealos: command not found
, error: Process exited with status 127,

这是完整的日志了

**Comment by bxy4543** [comment]
Is the execution machine the master0 ?

**Comment by yssy2519** [comment]
> Is the execution machine the master0 ?

yes

**Comment by bxy4543** [comment]
https://docs.sealos.io/docs/self-hosting/installation
