### ISSUE TITLE
BUG: sealos upgrade cluster

### ISSUE THREAD

**Issue by cuisongliu** [labring/sealos#3798]
### Sealos Version

4.3.0

### How to reproduce the bug?

![img_v2_b7290d2b-96f9-4de6-a3cf-29b80092a1fg](https://github.com/labring/sealos/assets/4150905/539d19e0-da54-4f12-932e-52fc6b462093)

1.23.8  upgrade to 1.24.0

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by fengxsong** [comment]
fixed in https://github.com/labring/sealos/pull/3588

**Comment by cuisongliu** [comment]
v4.3.1+
