### ISSUE TITLE
BUG: sealos reset failed

### ISSUE THREAD

**Issue by shuoshadow** [labring/sealos#3818]
### Sealos Version

v4.3.3

### How to reproduce the bug?

root@dev-devops-sealos01:~# sealos reset --masters="192.168.40.233" 
2023-09-01T08:12:29 info are you sure to delete these nodes?
Yes [y/yes], No [n/no]: y
2023-09-01T08:12:31 info start to delete Cluster: master [192.168.40.233], node []
2023-09-01T08:12:31 info start to reset nodes: []
2023-09-01T08:12:31 info start to reset masters: [192.168.40.233:22]
2023-09-01T08:12:31 info start to reset node: 192.168.40.233:22
/usr/bin/kubeadm
[preflight] Running pre-flight checks
W0901 08:12:31.455000   28383 removeetcdmember.go:106] [reset] No kubeadm config, using etcd pod spec to get data directory
[reset] Deleted contents of the etcd data directory: /var/lib/etcd
[reset] Stopping the kubelet service
[reset] Unmounting mounted directories in "/var/lib/kubelet"
[reset] Deleting contents of directories: [/etc/kubernetes/manifests /var/lib/kubelet /etc/kubernetes/pki]
[reset] Deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/bootstrap-kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]

The reset process does not clean CNI configuration. To do so, you must remove /etc/cni/net.d

The reset process does not reset or clean up iptables rules or IPVS tables.
If you wish to reset iptables, you must do so manually by using the "iptables" command.

If your cluster was setup to utilize IPVS, run ipvsadm --clear (or similar)
to reset your system's IPVS tables.

The reset process does not clean your kubeconfig files and you must remove them manually.
Please, check the contents of the $HOME/.kube/config file.
bash: line 1: /var/lib/sealos/data/default/rootfs/opt/sealctl: No such file or directory
bash: line 1: /var/lib/sealos/data/default/rootfs/opt/sealctl: No such file or directory
bash: line 1: /var/lib/sealos/data/default/rootfs/opt/sealctl: No such file or directory
2023-09-01T08:12:31 error failed to clean node route and ipvs failed, exit status 127
2023-09-01T08:12:31 error delete apiserver hosts failed exit status 127
2023-09-01T08:12:31 error delete master 192.168.40.233:22 failed add lvscare domain hosts failed exit status 127
2023-09-01T08:12:31 info Executing pipeline Bootstrap in DeleteProcessor
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x2ea0572]

goroutine 1 [running]:
github.com/labring/sealos/pkg/bootstrap.NewContextFrom(0xc0006d86c0)
        github.com/labring/sealos/pkg/bootstrap/context.go:69 +0x1f2
github.com/labring/sealos/pkg/bootstrap.New(0x0?)
        github.com/labring/sealos/pkg/bootstrap/bootstrap.go:49 +0x1d
github.com/labring/sealos/pkg/apply/processor.(*DeleteProcessor).UndoBootstrap(0xc0006758a0, 0xc0006d86c0)
        github.com/labring/sealos/pkg/apply/processor/delete.go:83 +0x28c
github.com/labring/sealos/pkg/apply/processor.DeleteProcessor.Execute({{0x3c6bba0?, 0xc000539bc0?}, {0x3c61e90?, 0xc0005b00d0?}}, 0xc0005b00d0?)
        github.com/labring/sealos/pkg/apply/processor/delete.go:50 +0x35c
github.com/labring/sealos/pkg/apply/applydrivers.(*Applier).deleteCluster(0xc000586600)
        github.com/labring/sealos/pkg/apply/applydrivers/apply_drivers_default.go:264 +0x53
github.com/labring/sealos/pkg/apply/applydrivers.(*Applier).Delete(0xc000586600)
        github.com/labring/sealos/pkg/apply/applydrivers/apply_drivers_default.go:255 +0xe7
github.com/labring/sealos/cmd/sealos/cmd.newResetCmd.func1(0xc000004f00?, {0xc0006f41c0?, 0x1?, 0x1?})
        github.com/labring/sealos/cmd/sealos/cmd/reset.go:54 +0xa3
github.com/spf13/cobra.(*Command).execute(0xc000004f00, {0xc0006f41a0, 0x1, 0x1})
        github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x509a940)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
github.com/labring/sealos/cmd/sealos/cmd.Execute()
        github.com/labring/sealos/cmd/sealos/cmd/root.go:49 +0x25
main.main()
        github.com/labring/sealos/cmd/sealos/main.go:27 +0x29

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by bxy4543** [comment]
`192.168.40.233` master kubeadm does not exist, it seems that reset is not needed, you can try `sealos delete --masters 192.168.40.233`
