### ISSUE TITLE
BUG: Sealos 无法添加node

### ISSUE THREAD

**Issue by Accpet** [labring/sealos#3819]
### Sealos Version

v1.6.23

### How to reproduce the bug?

1、sealos add --nodes 1xx.xx.33.168

### What is the expected behavior?

添加节点

### What do you see instead?

error error occur while sending mount image default-aw2iyr9l: failed to copy entry /var/lib/containers/storage/overlay/7d9cf4bd86755dfb0914476bd1472d52093a17f1fe61e088a8a225468060eef4/merged/Kubefile -> /var/lib/sealos/data/default/rootfs/Kubefile to xxx.xxx.33.168:0: failed to connect: dial tcp xxx.xxx.33.168:0: connect: connection refused
2023-09-01T16:26:25 error Applied to cluster error: failed to copy entry /var/lib/containers/storage/overlay/7d9cf4bd86755dfb0914476bd1472d52093a17f1fe61e088a8a225468060eef4/merged/Kubefile -> /var/lib/sealos/data/default/rootfs/Kubefile to xxx.xxx.33.168:0: failed to connect: dial tcp xxx.xxx.33.168:0: connect: connection refused

### Operating environment

```markdown
- Sealos version:v1.6.23
- Docker version:
- Kubernetes version:1.26.2
- Operating system:CentoOS7.9
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by bxy4543** [comment]
v1.6.23 ? wrong sealos version，
`xxx.xxx.33.168:0: connect: connection refused` : This seems to be a problem with the machine being disconnected. Please check whether the machine is connected via ssh normally.

**Comment by Accpet** [comment]
> v1.6.23 ? wrong sealos version， `xxx.xxx.33.168:0: connect: connection refused` : This seems to be a problem with the machine being disconnected. Please check whether the machine is connected via ssh normally.

是的 端口ssh服务应该是22端口 不知道为什么是0？

**Comment by bxy4543** [comment]
4版本以前的都不维护了的

**Comment by cuisongliu** [comment]
> > v1.6.23 ? wrong sealos version， `xxx.xxx.33.168:0: connect: connection refused` : This seems to be a problem with the machine being disconnected. Please check whether the machine is connected via ssh normally.
> 
> 是的 端口ssh服务应该是22端口 不知道为什么是0？

使用sealos 4.3.3 修复了这个问题
