### ISSUE TITLE
BUG: save image error when build cluster

### ISSUE THREAD

**Issue by shuoshadow** [labring/sealos#3820]
### Sealos Version

v4.3.3

### How to reproduce the bug?

![image](https://github.com/labring/sealos/assets/10016360/b90222a2-a0dc-4254-9447-62c09a4a0d9f)

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cuisongliu** [comment]
<img width="792" alt="image" src="https://github.com/labring/sealos/assets/4150905/be98c9d7-2ea1-4b7a-97ae-4fb87a88021a">
我这没有问题，看一下是不是架构不匹配。

**Comment by shuoshadow** [comment]
@cuisongliu 请问你说的架构是指什么？

**Comment by fengxsong** [comment]
this issue may sometimes caused by docker.io's flow control policy.

**Comment by shuoshadow** [comment]
@fengxsong 请问下，刚开始build没有错误，应该会缓存镜像文件吧？为什么我后面重复build的时候，偶尔会出现各种拉取镜像出错的情况呢？已存在的镜像不是应该不会再重复拉取吗？

**Comment by cuisongliu** [comment]
> this issue may sometimes caused by docker.io's flow control policy.

应该是，每小时拉取的频率docker有限制。

**Comment by shuoshadow** [comment]
按理build一次后应该不会再去拉取，我这个build才几个镜像，为什么会超过频率呢

**Comment by cuisongliu** [comment]
> 按理build一次后应该不会再去拉取，我这个build才几个镜像，为什么会超过频率呢

会拉取，只是已经存在不会重复拉取，但是api是被docker进行计算的。
