### ISSUE TITLE
BUG: warning is displayed during the build process 

### ISSUE THREAD

**Issue by shuoshadow** [labring/sealos#3826]
### Sealos Version

v4.3.3

### How to reproduce the bug?

![image](https://github.com/labring/sealos/assets/10016360/e615d1c0-6afd-4ded-b7c1-a38ef5d19f6c)
```shell
2023-09-04T05:59:32 info domain apiserver.cluster.local:192.168.40.233 append success
W0904 05:59:32.270348  170379 initconfiguration.go:306] error unmarshaling configuration schema.GroupVersionKind{Group:"kubeproxy.config.k8s.io", Version:"v1alpha1", Kind:"KubeProxyConfiguration"}: strict decoding error: unknown field "udpIdleTimeout"
W0904 05:59:32.270753  170379 configset.go:177] error unmarshaling configuration schema.GroupVersionKind{Group:"kubeproxy.config.k8s.io", Version:"v1alpha1", Kind:"KubeProxyConfiguration"}: strict decoding error: unknown field "udpIdleTimeout"
W0904 05:59:32.272039  170379 initconfiguration.go:120] Usage of CRI endpoints without URL scheme is deprecated and can cause kubelet errors in the future. Automatically prepending scheme "unix" to the "criSocket" with value "/var/run/cri-dockerd.sock". Please update your configuration!
W0904 05:59:32.272074  170379 utils.go:69] The recommended value for "healthzBindAddress" in "KubeletConfiguration" is: 127.0.0.1; the provided value is: 0.0.0.0
[init] Using Kubernetes version: v1.27.5
```

应该如何解决以上几个worning呢

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cuisongliu** [comment]
不影响使用，忽略即可

**Comment by shuoshadow** [comment]
@cuisongliu 我如果想自定义KubeletConfiguration配置的话，应该怎么做呢？我看了官方文档，只有一个kubeadm.yml的配置可以参考，我把配置写在里面也不生效
官网的：
![image](https://github.com/labring/sealos/assets/10016360/a3cc6765-a0f3-445e-bb98-1eab764d5a35)

我自己写的配置：
![image](https://github.com/labring/sealos/assets/10016360/8c2c5f26-4122-4947-a9d8-19664b8217ab)

**Comment by cuisongliu** [comment]
你如何判断的不生效？ 默认值就是0.0.0.0 这个啊

**Comment by cuisongliu** [comment]
> 我就贴出来了，而且healthzBindAddress默认是127.0.0.1，你看下官网就知道了。
> W0904 05:59:32.272074 170379 utils.go:69]

好像warn没有影响吧，你非要改么。。。你改不是要改127.0.0.1 么，你配置还是0.0.0.0 而且有些配置不支持修改，你如果非要改的话可能得改代码了。

**Comment by shuoshadow** [comment]
> > 我就贴出来了，而且healthzBindAddress默认是127.0.0.1，你看下官网就知道了。
> > W0904 05:59:32.272074 170379 utils.go:69]
> 
> 好像warn没有影响吧，你非要改么。。。你改不是要改127.0.0.1 么，你配置还是0.0.0.0 而且有些配置不支持修改，你如果非要改的话可能得改代码了。

嗯，不能改的话我想想其他办法，只是想看看能不能自定义kubelet的参数

**Comment by cuisongliu** [comment]
> > > 我就贴出来了，而且healthzBindAddress默认是127.0.0.1，你看下官网就知道了。
> > > W0904 05:59:32.272074 170379 utils.go:69]
> > 
> > 
> > 好像warn没有影响吧，你非要改么。。。你改不是要改127.0.0.1 么，你配置还是0.0.0.0 而且有些配置不支持修改，你如果非要改的话可能得改代码了。
> 
> 嗯，不能改的话我想想其他办法，只是想看看能不能自定义kubelet的参数

可以改啊，你不是想改成127么，那你配置写0.0.0.0 ？？？？不感觉逻辑不对么

**Comment by shuoshadow** [comment]
看不懂就不要回了

**Comment by cuisongliu** [comment]
<img width="645" alt="image" src="https://github.com/labring/sealos/assets/4150905/1dee6e89-ee1d-49bd-97b0-33c0ddd18957">
你写的配置不是0.0.0.0  你不是想改成127.0.0.1 么？ 你这个配置不是应该改成127.0.0.1 才对么
