### ISSUE TITLE
The port opened by the code-server in the template market cannot be accessed externally

### ISSUE THREAD

**Issue by weisiqian** [labring/sealos#3829]
### Sealos Version

v4.0

### How to reproduce the bug?

1、私有化部署sealos desktop

2、进入 desktop 中的模板市场，然后部署这个模板
![image](https://github.com/labring/sealos/assets/19994951/27336106-b579-404b-887e-55d4eaa15f9d)

3、部署完成后通过变更应用的方式修改外网地址为自定义域名

4、访问自定义域名进入code-server编辑器页面，然后打开terminal 安装 nvm 并切换 nodejs 版本为 v16.20.0

5、使用 npm create vue@latest 创建 vue 应用，全都使用默认选项

6、修改vite.config.js 配置 vue 应用的 base 路径和启动端口为如下内容
![image](https://github.com/labring/sealos/assets/19994951/05ddda44-6a75-4186-a39f-fe3b7db4a049)
```
import { fileURLToPath, URL } from 'node:url'

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  },
  server: {
    port: 3030,
  },
  base: "/proxy/3030",
})
```

7、在应用根目录输入 npm run dev 运行

8、通过 code-server 的自定义域名使用 子路径的方式无法访问vue页面

![image](https://github.com/labring/sealos/assets/19994951/42c65c07-a681-4ed5-9419-b743c9867f8c)

![image](https://github.com/labring/sealos/assets/19994951/87b8b00c-325f-4be4-b0e6-6c1d32a4fa7a)

通过子路径的方式访问 /proxy/3030 会被重定向到 /proxy/3030//proxy/3030

9、通过 code-server 的自定义域名的子域名访问vue页面会提示证书错误
![image](https://github.com/labring/sealos/assets/19994951/b942395b-ddeb-471e-9345-078c8cb94029)

10、调整浏览器的安全配置为不校验证书后再次通过子域名的方式访问会提示 404

![image](https://github.com/labring/sealos/assets/19994951/772e34f2-2414-4cd2-890f-aa55335783bc)

### What is the expected behavior?

1、期望支持通过 subpath 的方式访问 code-server 中暴露的 http 服务
2、期望支持通过 subdomain 的方式访问 code-server 中暴露的 http 服务
3、自定义域名的时候支持上传自定义证书

### What do you see instead?

既不能通过 subpath 的方式访问 code-server 中暴露的 vue 应用 也不能通过 subdomain 的方式访问

### Operating environment

```markdown
root@node:~# sealos version
CriVersionInfo:
  RuntimeApiVersion: v1
  RuntimeName: containerd
  RuntimeVersion: v1.6.21
  Version: 0.1.0
KubernetesVersionInfo:
  clientVersion:
    buildDate: "2023-01-18T19:22:09Z"
    compiler: gc
    gitCommit: ff2c119726cc1f8926fb0585c74b25921e866a28
    gitTreeState: clean
    gitVersion: v1.25.6
    goVersion: go1.19.5
    major: "1"
    minor: "25"
    platform: linux/amd64
  kustomizeVersion: v4.5.7
  serverVersion:
    buildDate: "2023-01-18T19:15:26Z"
    compiler: gc
    gitCommit: ff2c119726cc1f8926fb0585c74b25921e866a28
    gitTreeState: clean
    gitVersion: v1.25.6
    goVersion: go1.19.5
    major: "1"
    minor: "25"
    platform: linux/amd64
SealosVersion:
  buildDate: "2023-04-23T14:23:15Z"
  compiler: gc
  gitCommit: f696a621
  gitVersion: 4.2.0
  goVersion: go1.20.3
  platform: linux/amd64
```

**Comment by zzjin** [comment]
Cannot re-produce by using vscode's extension: `live preview`,
![image](https://github.com/labring/sealos/assets/679757/9722083d-7e9e-40ae-b7fe-faedc01917a5)

Maybe its a bug of your vite/vue config?

**Comment by zzjin** [comment]
Fixed.
coder-server's doc shows taht it needs touse `absproxy/:port`.@see https://coder.com/docs/code-server/latest/guide#proxying-to-a-vue-app
