### ISSUE TITLE
Feature: when master0 breaks down, other masters can use sealos cluster management commands

### ISSUE THREAD

**Issue by MuJianning** [labring/sealos#3859]
### What is the problem this feature will solve?

当master0发生故障时，其他master可以使用sealos集群管理命令。

When master0 breaks down, other masters can use sealos cluster management commands.

我的master0发生故障，无法恢复。但是其他master不能使用sealos集群管理命令。即使在其他master安装sealos工具（apt install sealos）也因缺失~/.sealos/和/var/lib/sealos/data/default/rootfs/registry/等重要信息而无法正常工作。

My master0 breaks down and cannot be recovered. But other masters cannot use sealos cluster management commands. Even if the sealos tool is installed on other masters (apt install sealos), it cannot function properly due to missing important information such as ~/. sealos/ and /var/lib/sealos/data/default/rootfs/registry/.

### If you have solution，please describe it

目前没有解决方案，只能重建集群。

No solution for now but rebuild cluster.

### What alternatives have you considered?

用kubeadm取代sealos。

Replace sealos with kubeadm.

**Comment by cuisongliu** [comment]
用kubeadm取代sealos。  这个方式不可行，只需要同步配置即可。
至于registry我感觉你安装的时候就不应该只安装到master0节点。

**Comment by ghostloda** [comment]
> 用kubeadm取代sealos。 这个方式不可行，只需要同步配置即可。

添加switch命令，取代异常的master0, 例如：sealos switch  --master 192.168.0.5 。
switch在后台将.sealos/ 同步到新的master1。这样是否可以？

**Comment by bxy4543** [comment]
> 

不需要新添加命令，在集群初始化和加入节点操作成功后同步master ~/.sealos数据就可以的

**Comment by ghostloda** [comment]
> > 
> 
> 不需要新添加命令，在集群初始化和加入节点操作成功后同步master ~/.sealos数据就可以的

我明白了，保持master节点之间的~/.sealos数据同步。

**Comment by wanghesir** [comment]
我们也有同样需求，我觉得仓库信息/var/lib/sealos/data/default/rootfs/registry/ 等数据也需要同步的

**Comment by cuisongliu** [comment]
> 我们也有同样需求，我觉得仓库信息/var/lib/sealos/data/default/rootfs/registry/ 等数据也需要同步的

这个当前支持的，你安装集群的时候 设置role=registry 就可以了

**Comment by wanghesir** [comment]
能否详细介绍一下如何设置role=registry，或者提供文档？谢谢

**Comment by cuisongliu** [comment]
sealos gen  然后把节点role添加 registry 然后apply即可。

**Comment by gogogo2156** [comment]
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  creationTimestamp: null
  name: default
spec:
  hosts:
    - ips:
        - 192.168.63.128:22
        - 192.168.63.127:22
        - 192.168.63.126:22
      roles:
        - master
        - amd64
        - registry 
    - ips:
        - 192.168.63.125:22
        - 192.168.63.124:22
      roles:
        - node
        - amd64
  image:
    - labring/kubernetes:v1.26.1
    - labring/helm:v3.11.0
    - labring/calico:v3.25.0
  ssh:
    pk: /root/.ssh/id_rsa
    port: 22
status: {}

**Comment by cuisongliu** [comment]
> apiVersion: apps.sealos.io/v1beta1
> kind: Cluster
> metadata:
> name: default
> spec:
> hosts:
> - ips:
> - 192.168.63.128:22
> - 192.168.63.127:22
> - 192.168.63.126:22
> roles:
> - master
> - amd64
> - registry
> - ips:
> - 192.168.63.125:22
> - 192.168.63.124:22
> roles:
> - node
> - amd64
> image:
> - labring/kubernetes:v1.26.1
> - labring/helm:v3.11.0
> - labring/calico:v3.25.0
> ssh:
> pk: /root/.ssh/id_rsa
> port: 22
> status: {}
> 是这样添加吗？添加后是什么效果，会在3个master上都安装仓库，并互相同步吗？谢谢

是的，每次安装app会往三个仓库发送镜像。可能会慢，但是如果master0坏了 你只要把每个节点的sealos.hub对应的IP改掉就好了

**Comment by gogogo2156** [comment]
好的，这个功能是从sealos哪个版本开始支持的？

**Comment by cuisongliu** [comment]
> 好的，这个功能是从sealos哪个版本开始支持的？

https://github.com/labring/sealos/pull/2096 这个PR

**Comment by gogogo2156** [comment]
好的，谢谢。

> > > 
> > 
> > 
> > 不需要新添加命令，在集群初始化和加入节点操作成功后同步master ~/.sealos数据就可以的
> 
> 我明白了，保持master节点之间的~/.sealos数据同步。

这个功能是需要新开发的吧？

**Comment by bxy4543** [comment]
> 好的，谢谢。
> 
> > > > 
> > > 
> > > 
> > > 不需要新添加命令，在集群初始化和加入节点操作成功后同步master ~/.sealos数据就可以的
> > 
> > 
> > 我明白了，保持master节点之间的~/.sealos数据同步。
> 
> 这个功能是需要新开发的吧？

是的，也可以手动执行 sealos scp -r master src target 命令来同步~/.sealos数据到其他master节点

**Comment by gogogo2156** [comment]
请问这个功能做完了吗？是否计划合入到新的版本中？谢谢

**Comment by bxy4543** [comment]
最新版应该已经支持了 @gogogo2156

**Comment by gogogo2156** [comment]
最新版是指v4.3.7吗？需要去配置开启吗？谢谢

**Comment by xpy3306** [comment]
怎么在安装时，用命令指定部署3个registry
