### ISSUE TITLE
GitHub actions yielded the following error.

### ISSUE THREAD

**Issue by cuisongliu** [labring/sealos#3880]
GitHub actions yielded the following error.

The command that failed is `sudo sealos images`. Here are the relevant lines from the logs:

```
2023-09-10T13:31:16 info lookup in path /home/runner/work/sealos/sealos/service/auth/deploy/charts
2023-09-10T13:31:16 info path /home/runner/work/sealos/sealos/service/auth/deploy/charts is not exists, skip
Pulling image: docker.io/bitnami/mysql:8.0.31
Pulling image: docker.io/casbin/casdoor:latest
Pulling image: docker.io/labring/docker-casbin:main
Pulling image: ghcr.io/labring/sealos-auth-service:edc1307c
Error: failed to save images: save domain docker.io image docker.io/labring/docker-casbin:main: get labring/docker-casbin tag descriptor error: unknown tag=main, try "sealos login" if you are using a private registry
```

This is likely a linting or type-checking issue with the source code. Update the code changed by the PR. Don't modify the existing tests.

_Originally posted by @sweep-ai[bot] in https://github.com/labring/sealos/issues/3879#issuecomment-1712815335_

**Comment by lingdie** [comment]
pr https://github.com/labring/sealos/pull/3885 fix this issue.
