### ISSUE TITLE
Feature: k3s runtime support

### ISSUE THREAD

**Issue by cuisongliu** [labring/sealos#3900]
### What is the problem this feature will solve?

- [x] k3s init and reset https://github.com/labring/sealos/pull/3865
- [x] k3s init test  https://github.com/labring/sealos/pull/3875
- [ ] k3s upgrade
- [ ] k3s renew cert
- [x] k3s registry update password
- [x] n master n nodes support https://github.com/labring/sealos/pull/3944 
- [x] ipvs manager
- [ ] k3s test

### What alternatives have you considered?

https://github.com/labring/sealos/issues/2863

**Comment by cuisongliu** [comment]
1. reset 直接指定master和node无法reset 不执行脚本
2. 删除节点后无法重加入节点 等6分钟都无法加入，
```
 balancer k3s-agent-load-balancer 127.0.0.1:6444 -> [apiserver.cluster.local:6443] [default: apiserver.cluster.local:6443]"
et CA certs: Get \"https://127.0.0.1:6444/cacerts\": read tcp 127.0.0.1:52942->127.0.0.1:6444: read: connection reset by peer"
et CA certs: Get \"https://127.0.0.1:6444/cacerts\": read tcp 127.0.0.1:16982->127.0.0.1:6444: read: connection reset by peer"
```
3. endable 服务加超时处理

**Comment by codering** [comment]
最最新版本已经可以用k3s runtime 了吗？

**Comment by cuisongliu** [comment]
> 最新版本已经可以用k3s runtime 了吗？

4.4的最新版支持，但是集群镜像需要更换一下。更换成  k3s:1.25-latest 。但是没有做全面的测试

**Comment by cuisongliu** [comment]
需要做测试

**Comment by BanKnight** [comment]
> 需要做测试

什么时候做好测试呢？我想试下部署k3s版本了
