### ISSUE TITLE
Feature: brief description of the feature

### ISSUE THREAD

**Issue by longlongawy** [labring/sealos#3933]
### What is the problem this feature will solve?

主机环境有多个网卡bond0 :10.220.210.106 bond1:10.230.154.160，使用sealos 安装k8时是否可以指定网卡？

当前使用问题是使用sealos run 部署k8s后，主机状态和k8s组件状态均正常，k8s组件的pod ip和flannel ip 为10.220网段，但是主机ip为10.230网段，主机和k8s组件间的pod网络不通

**Comment by willzhang** [comment]
k8s组件的pod ip和flannel ip 为10.220网段，主机网卡bond0 也是10.220. 这样pod子网和主机网卡子网冲突了吧
另外sealos只会用有默认路由的网卡的IP地址，参考：[10.220.](https://github.com/labring/sealos/issues/2594)
