### ISSUE TITLE
When sealos deploys a cluster, how to configure and modify the containerd default data storage directory ‘/usr/bin/containerd’

### ISSUE THREAD

**Issue by zhaoying8023** [labring/sealos#3964]
### What is the problem this feature will solve?

 sealos部署集群时，containerd 默认数据存储目录‘/usr/bin/containerd’如何配置修改

**Comment by cuisongliu** [comment]
https://docs.sealos.io/zh-Hans/docs/lifecycle-management/advanced-guide/image-build-standardized

<img width="1136" alt="image" src="https://github.com/labring/sealos/assets/4150905/5478d2ae-f365-4df1-a2a6-190a482d2a9d">
