### ISSUE TITLE
BUG: Sealos constantly prompts for port conflicts

### ISSUE THREAD

**Issue by EmptyZeroRain** [labring/sealos#4000]
### Sealos Version

4.3.3

### How to reproduce the bug?

I have 3 Centos virtual machines with Docker installed on them. Then, I run the installation method provided on your official website and constantly prompt for port errors
2.The prompt is as follows
Using official documents https://www.sealyun.com/zh-Hans/docs/lifecycle-management/quick-start/ Install Cluster Install Kuberentes
info Start to create a new cluster: master [192.168.199.130], worker [192.168.199.129 192.168.199.128], registry 192.168.199.130
2023-09-26T23:23:11 info Executing pipeline Check in CreateProcessor.
2023-09-26T23:23:11 info checker:hostname [192.168.199.130:22 192.168.199.129:22 192.168.199.128:22]
2023-09-26T23:23:11 info checker:timeSync [192.168.199.130:22 192.168.199.129:22 192.168.199.128:22]
2023-09-26T23:23:12 info Executing pipeline PreProcess in CreateProcessor.
2023-09-26T23:23:12 info Executing pipeline RunConfig in CreateProcessor.
2023-09-26T23:23:12 info Executing pipeline MountRootfs in CreateProcessor.
2023-09-26T23:23:38 info Executing pipeline MirrorRegistry in CreateProcessor.          
2023-09-26T23:23:38 info trying default http mode to sync images to hosts [192.168.199.130:22]
2023-09-26T23:23:40 info Executing pipeline Bootstrap in CreateProcessor
 INFO [2023-09-26 23:23:40] >> Check port kubelet port 10249..10259, reserved port 5050..5054 inuse. Please wait... 
 ERROR [2023-09-26 23:23:40] >> docker already exist, uninstall docker and retry 
192.168.199.128:22   INFO [2023-09-26 23:23:40] >> Check port kubelet port 10249..10259, reserved port 5050..5054 inuse. Please wait... 
192.168.199.130:22   INFO [2023-09-26 23:23:40] >> Check port kubelet port 10249..10259, reserved port 5050..5054 inuse. Please wait... 
192.168.199.128:22   ERROR [2023-09-26 23:23:40] >> docker already exist, uninstall docker and retry 
192.168.199.130:22   ERROR [2023-09-26 23:23:40] >> docker already exist, uninstall docker and retry 
2023-09-26T23:23:40 error Applied to cluster error: exit status 1
  
Using the ss - lntup command to view ports, there is no
root@master ~]# ss -lntup
Netid  State      Recv-Q Send-Q                                     Local Address:Port                                                    Peer Address:Port              
udp    UNCONN     0      0                                                      *:68                                                                 *:*                   users:(("dhclient",pid=856,fd=6))
udp    UNCONN     0      0                                              127.0.0.1:323                                                                *:*                   users:(("chronyd",pid=809,fd=5))
udp    UNCONN     0      0                                                  [::1]:323                                                             [::]:*                   users:(("chronyd",pid=809,fd=6))
tcp    LISTEN     0      128                                                    *:22                                                                 *:*                   users:(("sshd",pid=1050,fd=3))
tcp    LISTEN     0      100                                            127.0.0.1:25                                                                 *:*                   users:(("master",pid=1184,fd=13))
tcp    LISTEN     0      128                                                 [::]:22                                                              [::]:*                   users:(("sshd",pid=1050,fd=4))
tcp    LISTEN     0      100                                                [::1]:25                                                              [::]:*                   users:(("master",pid=1184,fd=14))

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by willzhang** [comment]
sealos reset --force
systemctl disable --now kubelet

and use a new image here: https://github.com/labring-actions/cluster-image-docs/blob/main/docs/aliyun-shanghai/rootfs.md

eg
```
sealos run registry.cn-shanghai.aliyuncs.com/labring/kubernetes:v1.25.14
```
