### ISSUE TITLE
After the node restarts, kube-scheduler image pull error

### ISSUE THREAD

**Issue by gitfxx** [labring/sealos#4003]
### Sealos Version

v4.2.0

### How to reproduce the bug?

单机集群环境
节点重启后发现pod一直处在pending状态
查看apiserver状态正常
查看scheduler状态，显示镜像拉取失败
![image](https://github.com/labring/sealos/assets/28646240/8f61d5c5-5725-474a-946f-fc34a7e54140)
![image](https://github.com/labring/sealos/assets/28646240/7ba3414c-49ee-4dfb-a219-32456537dd1f)

查看节点镜像，实际为sealos.hub:5000/kube-scheduler:v1.25.0，不知道为什么会去拉取sealos.hub:5000/kube-scheduler:v1.25.0
临时解决，把镜像名改了一下

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by bxy4543** [comment]
`crictl pull registry.k8s.io/kube-scheduler:v1.25.0`  呢

**Comment by bxy4543** [comment]
> > > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> > 
> > 
> > `crictl pull registry.k8s.io/kube-scheduler:v1.25.0`
> 
> 离线节点，没有网络，疑问的是为什么拉取的镜像还不固定？

优先从sealos registry里拉取镜像，crictl image里应该带有sea.hub前缀的镜像的

**Comment by bxy4543** [comment]
拉不下来镜像 排查三个点：
```
systemctl status image-cri-shim #排查image-cri-shim状态是否正常
systemctl status registry #排查registry状态是否正常，以及/var/lib/registry内镜像元数据目录是否存在
systemctl restart kubelet #修复后重新启动kubelet恢复
```
