### ISSUE TITLE
BUG: exec /manager: exec format error

### ISSUE THREAD

**Issue by hulingfeng211** [labring/sealos#4025]
### Sealos Version

4.3.4

### How to reproduce the bug?

sudo sealos run docker.io/labring/sealos-cloud:latest\
    --env cloudDomain="192.168.64.5.nip.io"

### What do you see instead?

start to authorize sealos
create admin-user
Error from server (InternalError): error when creating "manifests/admin-user.yaml": Internal error occurred: failed calling webhook "muser.kb.io": failed to call webhook: Post "https://user-webhook-service.user-system.svc:443/mutate-user-sealos-io-v1-user?timeout=10s": no endpoints available for service "user-webhook-service"
Error: exit status 1

<img width="1481" alt="image" src="https://github.com/labring/sealos/assets/1949715/044f3a79-ff74-4ba7-ad3a-031a0dcbebd1">

### Operating environment

```markdown
- Sealos version:4.3.4
- Docker version:
- Kubernetes version:1.25.6
- Operating system:ubuntu-23.04
- Runtime environment:
- Cluster size:single
- Additional information:
```

**Comment by hulingfeng211** [comment]
hardware: mac pro 14 m1

**Comment by cuisongliu** [comment]
这个问题你删除pod就可以，原因是你有cr了，然后会自动检测执行webhook,但是webhook没有起来导致的。
