### ISSUE TITLE
Docs: Database data import on sealos

### ISSUE THREAD

**Issue by lcRuri** [labring/sealos#4038]
### Documentation Section

A database started through sealos wants to synchronize data from a database on another server

### What is the current documentation state?

我想通过sealos数据库作为我在sealos上的服务的数据库。现在已经有了表结构，想要将数据从我的一台服务器上的数据库导入sealos上创建的数据库

**Comment by 15927926075** [comment]
我在群里找一下你，先测试一下迁移
