### ISSUE TITLE
k8s 1.21.5 uses containerd instead of docker. Can I allow docker to exist in the environment when installing k8s?

### ISSUE THREAD

**Issue by victory460** [labring/sealos#4050]
### Sealos Version

4.3.0

### How to reproduce the bug?

能不能安装k8s时，可以允许环境中有docker存在，因为存量机器，卸载docker不方便，有docker app

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cuisongliu** [comment]
可能需要定制一下rootfs 改一下配置才行

**Comment by victory460** [comment]
> 可能需要定制一下rootfs 改一下配置才行

你好，有没有其它简单的方法哇？现在基本上都是用的containerd了，目前sealos部署k8s前 都得卸载docker，对一些存量的机器部署不太友好，因为上面已经有docker应用了。

**Comment by fengxsong** [comment]
I don't think this is a best pratise, how can you sure those two containerd instances(docker is also relied on containerd) won't effect each other.

**Comment by victory460** [comment]
你好，非常感谢你的回答。那是否可以提供一个配置选项去跳过检查docker，进而支持对这种已有docker应用的研发环境去部署k8s.

**Comment by bxy4543** [comment]
> 你好，非常感谢你的回答。那是否可以提供一个配置选项去跳过检查docker，进而支持对这种已有docker应用的研发环境去部署k8s. @fengxsong

想办法别让`command -v docker` 识别到就行

**Comment by victory460** [comment]
如果我使用labring/kubernetes-docker版本的镜像，还需要卸载原来的docker吗？

**Comment by cuisongliu** [comment]
> > 你好，非常感谢你的回答。那是否可以提供一个配置选项去跳过检查docker，进而支持对这种已有docker应用的研发环境去部署k8s. @fengxsong
> 
> 想办法别让`command -v docker` 识别到就行

不仅仅跳过识别，还得让cri-dockerd识别docker的socket。
