### ISSUE TITLE
After the deployment is completed, it cannot be accessed through the domain name, and the page displays nginx404

### ISSUE THREAD

**Issue by oldwang12138** [labring/sealos#4152]
### Discussed in https://github.com/labring/sealos/discussions/4146

<div type='discussions-op-text'>

<sup>Originally posted by **oldwang12138** October 23, 2023</sup>
master0：192.168.1.200
node0：192.168.1.201
访问电脑主机：192.168.1.199
域名：www.example.com
安装命令：curl -sfL https://raw.githubusercontent.com/labring/sealos/main/scripts/cloud/install.sh -o /tmp/install.sh && bash /tmp/install.sh 
尝试操作一：
1、中英文选择：1
2、master0节点：192.168.1.200
3、node0节点：192.168.1.201
4、ssh免密已配置
5、cloudDomain：www.example.com
6、端口10443
7、输入证书：n
尝试操作二：
1、中英文选择：1
2、master0节点：192.168.1.200
3、node0节点：192.168.1.201
4、ssh免密已配置
5、cloudDomain：192.168.1.200.www.example.com
6、端口10443
7、输入证书：n
尝试操作三：
1、中英文选择：1
2、master0节点：192.168.1.200
3、node0节点：192.168.1.201
4、ssh免密已配置
5、cloudDomain：192.168.1.200.nip.io
6、端口10443
7、输入证书：n
目前三种方法均无法访问，我在访问主机hosts里添加指定解析也不行，ubuntu也已关闭防火墙，目前不知道问题在哪有大神指教下吗？
</div>

**Comment by bxy4543** [comment]
节点 kubectl get pod -A 看下pod状态是否正常呢

**Comment by oldwang12138** [comment]
> 节点 kubectl get pod -A 看下pod状态是否正常呢？

![image](https://github.com/labring/sealos/assets/44352658/bed291a1-e323-45fc-bb45-101d4c4fceb3)

**Comment by bxy4543** [comment]
那你试试`curl 192.168.1.200.nip.io` 呢
