### ISSUE TITLE
sealos-cloud failed to initialize admin user

### ISSUE THREAD

**Issue by PollosD** [labring/sealos#4158]
### Sealos Version

v4.3.5

### How to reproduce the bug?

1.ubuntu22.04
2.一键安装到最后的sealos-cloud，初始化admin用户时init-job报错，查看pod日志如下
error User.user.sealos.io "admin" is invalid: metadata.labels: Invalid value: "2023-10-24T07:52:21Z": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?') preset admin user in kubernetes failed

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by lingdie** [comment]
pr https://github.com/labring/sealos/pull/4160 will fix this, thanks for your advice.

**Comment by lingdie** [comment]
ps: use `sealos rmi` to remove deprecated sealos cloud image.

**Comment by PollosD** [comment]
> ps: use `sealos rmi` to remove deprecated sealos cloud image.
那请问我是需要用最新的脚本重装安装吗

**Comment by lingdie** [comment]
> > ps: use `sealos rmi` to remove deprecated sealos cloud image.
> > 那请问我是需要用最新的脚本重装安装吗

只需要把原来的 sealos-cloud 镜像删掉 然后 sealos reset 之后 重新执行脚本即可
