### ISSUE TITLE
install labring/kubernetes:v1.28.2 failed

### ISSUE THREAD

**Issue by ls-2018** [labring/sealos#4173]
### Sealos Version

4.3.5

### How to reproduce the bug?

<img width="1371" alt="image" src="https://github.com/labring/sealos/assets/38821215/60becc54-99fb-40a8-a0a9-d83dce1c5d6d">

 

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by ls-2018** [comment]
It is recommended to add a cluster version that sealos can install

**Comment by cuisongliu** [comment]
暂时还不支持，API改了。如果想用可以用4.4的版本运行k3s 支持1.28

**Comment by cuisongliu** [comment]
https://github.com/labring/sealos/issues/3689

**Comment by dailq09** [comment]
> 暂时还不支持，API改了。如果想用可以用4.4的版本运行k3s 支持1.28

sealos 4.4:
sealos run k3s:1.28.3报错如下:
Error: unknown command "initsystem" for "sealctl"

**Comment by willzhang** [comment]
> > 暂时还不支持，API改了。如果想用可以用4.4的版本运行k3s 支持1.28
> 
> sealos 4.4: sealos run k3s:1.28.3报错如下: Error: unknown command "initsystem" for "sealctl"

https://github.com/labring/sealos/issues/4304

**Comment by cuisongliu** [comment]
> > 暂时还不支持，API改了。如果想用可以用4.4的版本运行k3s 支持1.28
> 
> 
> 
> sealos 4.4:
> 
> sealos run k3s:1.28.3报错如下:
> 
> Error: unknown command "initsystem" for "sealctl"
> 
> 

镜像有问题，1.28应该还没做
