### ISSUE TITLE
BUG: cloud.sealos.io cannot delete the application

### ISSUE THREAD

**Issue by thlearncom** [labring/sealos#4179]
### Sealos Version

v4.3.5

### How to reproduce the bug?

Previously created a container, when I no longer need it, click to delete this application.

### What is the expected behavior?

Can be deleted normally.

### What do you see instead?

Prompt to delete the application exception, try multiple times but cannot delete. Now, even when I pause running it, its CPU and memory are still consuming resources.

### Operating environment

```markdown
Online business of https://cloud.sealos.io/
```

**Comment by bxy4543** [comment]
what is the user ID?

**Comment by thlearncom** [comment]
> what is the user ID?

It's cc1kf5h2@sealos

**Comment by bxy4543** [comment]
refresh and try again. Is there any relevant screenshot information?

**Comment by thlearncom** [comment]
I have tried dozens of times, but I still cannot delete it properly. Moreover, even if I pause it, it continues to deduct fees.
<img width="1052" alt="Snipaste_2023-11-01_16-01-35" src="https://github.com/labring/sealos/assets/104374208/934e7440-3584-4c5f-8e8a-21df7c783714">
<img width="672" alt="Snipaste_2023-11-01_16-02-04" src="https://github.com/labring/sealos/assets/104374208/cfd938bc-3bb8-4003-9a15-e2f585d9d331">

**Comment by thlearncom** [comment]
I want to know what the problem is? Why do I still need to pay for it even though there is no such project? Why can't the only other project be deleted?
![image](https://github.com/labring/sealos/assets/104374208/a23d2fc9-da4f-4e59-baaa-b93dee74c0ee)

**Comment by bxy4543** [comment]
solved, the deduction record is generated when using the domain name and detecting the ownership of the `pandora2.xx.xx` domain name.

**Comment by thlearncom** [comment]
Thank you, but I still can't delete this app.
<img width="1057" alt="Snipaste_2023-11-08_20-29-10" src="https://github.com/labring/sealos/assets/104374208/d521c3d6-c9e0-495a-b7c9-592ea352d6d1">

**Comment by bxy4543** [comment]
You can contact us at the forum: https://forum.laf.run/
