### ISSUE TITLE
Calico problem, 2 out of 4 calico-node pods cannot get up, 0/1 running

### ISSUE THREAD

**Issue by wubin1989** [labring/sealos#4199]
### Sealos Version

v4.3.5

### How to reproduce the bug?

执行命令：sealos run labring/kubernetes:v1.25.0 labring/helm:v3.8.2 labring/calico:v3.24.1 --masters 192.168.56.9,192.168.56.10,192.168.56.11 --nodes 192.168.56.12

有两个calico的pod始终不能正常运行。尝试了`kubectl set env daemonset/calico-node -n calico-system IP_AUTODETECTION_METHOD=interface=eth.*` 这个命令，还是不行。麻烦帮忙看看！

<img width="733" alt="image" src="https://github.com/labring/sealos/assets/12456315/e4026a06-48e6-4a85-a93d-3fc3a98e6869">

![image](https://github.com/labring/sealos/assets/12456315/5e4d21a0-c9dc-42a6-9881-077f0cf33f48)

<img width="666" alt="image" src="https://github.com/labring/sealos/assets/12456315/4dbe2e68-cad6-404b-be5c-83d96004240d">

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by bxy4543** [comment]
https://github.com/labring-actions/cluster-image/tree/main/applications/calico
