### ISSUE TITLE
How can I use more customized parameters

### ISSUE THREAD

**Issue by use-epoll** [labring/sealos#4219]
### Sealos Version

4.3.3

### How to reproduce the bug?

How do I configure some custom parameters for cilium when deploying a k8s cluster with sealos

### Operating environment

```markdown
- Sealos version: 4.3.3
- Docker version: 23.x
- Kubernetes version: 1.26.x
- Operating system: ubuntu22.04
- Runtime environment: runc
- Cluster size: 10-50 nodes
- Additional information:
```

**Comment by bxy4543** [comment]
https://sealos.io/zh-Hans/docs/self-hosting/lifecycle-management/operations/run-cluster/gen-apply-cluster
