### ISSUE TITLE
error Applied to cluster error: failed to init masters: init master0 failed, error: signal: killed. Please clean and reinstall

### ISSUE THREAD

**Issue by hlovingness** [labring/sealos#4249]
### Sealos Version

5.0.0

### How to reproduce the bug?

sealos run labring/kubernetes:v1.28.3 labring/helm:v3.12.3 labring/calico:v3.26.1

### Operating environment

```markdown
sealos run labring/kubernetes:v1.28.3 labring/helm:v3.12.3 labring/calico:v3.26.1
```

### Additional information

1103 15:49:46.624647   90615 initconfiguration.go:307] error unmarshaling configuration schema.GroupVersionKind{Group:"kubeproxy.config.k8s.io", Version:"v1alpha1", Kind:"KubeProxyConfiguration"}: strict decoding error: unknown field "udpIdleTimeout"
W1103 15:49:46.625445   90615 configset.go:177] error unmarshaling configuration schema.GroupVersionKind{Group:"kubeproxy.config.k8s.io", Version:"v1alpha1", Kind:"KubeProxyConfiguration"}: strict decoding error: unknown field "udpIdleTimeout"
W1103 15:49:46.626890   90615 initconfiguration.go:120] Usage of CRI endpoints without URL scheme is deprecated and can cause kubelet errors in the future. Automatically prepending scheme "unix" to the "criSocket" with value "/run/containerd/containerd.sock". Please update your configuration!
W1103 15:49:46.626924   90615 utils.go:69] The recommended value for "healthzBindAddress" in "KubeletConfiguration" is: 127.0.0.1; the provided value is: 0.0.0.0
[init] Using Kubernetes version: v1.28.3
[preflight] Running pre-flight checks
        [WARNING FileExisting-socat]: socat not found in system path
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
2023-11-03T15:54:46 error Applied to cluster error: failed to init masters: init master0 failed, error: signal: killed. Please clean and reinstall
Error: failed to init masters: init master0 failed, error: signal: killed. Please clean and reinstall

**Comment by cuisongliu** [comment]
不支持1.28

**Comment by hlovingness** [comment]
我安装1.27成功了，但是又出现了新问题
