### ISSUE TITLE
When will kubernetes v1.28.3 be supported?

### ISSUE THREAD

**Issue by dailq09** [labring/sealos#4270]
### Sealos Version

4.3.7

### How to reproduce the bug?

sealos run时当前不支持kubernetes v1.28.3，请问下大概什么时候可以支持

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by fanux** [comment]
@cuisongliu the robot to build cluster image kubernetes:v1.28.3?

**Comment by cuisongliu** [comment]
https://kubernetes.io/zh-cn/docs/reference/config-api/kubelet-config.v1beta1/

需要升级kubeadm以及cri-shim的相关的API  ，升级后支持的最低版本为1.22 同步需要调整集群镜像。

仓库的k8s依赖要升级成最低1.27+ 才能支持

目前需要解决

- 仓库依赖 1.27+
- kubeadm的API依赖升级 废弃老版本的k8s支持
- image-cri-shim 升级cri 全部为v1 不支持老版本的cri
- containerd 升级1.6+ 低版本不支持

**Comment by cuisongliu** [comment]
https://github.com/labring/sealos/issues/3689

**Comment by dailq09** [comment]
> https://kubernetes.io/zh-cn/docs/reference/config-api/kubelet-config.v1beta1/
> 
> 需要升级kubeadm以及cri-shim的相关的API ，升级后支持的最低版本为1.22 同步需要调整集群镜像。
> 
> 仓库的k8s依赖要升级成最低1.27+ 才能支持
> 
> 目前需要解决
> 
> * 仓库依赖 1.27+
> * kubeadm的API依赖升级 废弃老版本的k8s支持
> * image-cri-shim 升级cri 全部为v1 不支持老版本的cri
> * containerd 升级1.6+ 低版本不支持

是在你们的计划中么，将sealos run k8s v1.28以上？....

**Comment by lingdie** [comment]
对的

**Comment by dailq09** [comment]
sealos的哪个版本可以支持kubernetes v1.28.3?

**Comment by lingdie** [comment]
现在暂时不支持
