### ISSUE TITLE
BUG: Error modifying the local storage size of pod

### ISSUE THREAD

**Issue by nightwhite** [labring/sealos#4287]
### Sealos Version

sealos-desktop-frontend: eb2f0aed

### How to reproduce the bug?

Modify the size of local storage
![image](https://github.com/labring/sealos/assets/22722256/f6336f3e-cac5-4c56-bfde-27221f895660)

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by bxy4543** [comment]
default localpath storageclass not support resize
