### ISSUE TITLE
The shell script has a bug

### ISSUE THREAD

**Issue by fu7100** [labring/sealos#4323]
### Sealos Version

v4.3.7

### How to reproduce the bug?

环境：centos7
master：1
node：2
k8s版本1.21.4

使用官方镜像metrics:v0.6.4安装

# sealos run localhost/labring/metrics-server:v0.6.4 --debug
...
2023-11-20T23:09:02 debug start to run command `sudo -E /bin/bash -c 'cd /var/lib/sealos/data/default/applications/default-xlg8pe4k/workdir && helm upgrade -i metrics-server charts/metrics-server -n kube-system --set args='{--kubelet-insecure-tls=true,--kubelet-preferred-address-types=InternalIP}''` via exec
Error: Kubernetes cluster unreachable: Get "http://localhost:8080/version": dial tcp [::1]:8080: connect: connection refused

### What is the expected behavior?

metrics-server被正常安装

### What do you see instead?

如果使用手动复制debug里面的命令安装就会报错
sudo -E /bin/bash -c 'cd /var/lib/sealos/data/default/applications/default-xlg8pe4k/workdir && helm upgrade -i metrics-server charts/metrics-server -n kube-system --set args='{--kubelet-insecure-tls=true,--kubelet-preferred-address-types=InternalIP}''

报错：Error: Kubernetes cluster unreachable: Get "http://localhost:8080/version": dial tcp [::1]:8080: connect: connection refused

但是如果执行这条就没问题
cd /var/lib/sealos/data/default/applications/default-xlg8pe4k/workdir && helm upgrade -i metrics-server charts/metrics-server -n kube-system --set args='{--kubelet-insecure-tls=true,--kubelet-preferred-address-types=InternalIP}'

### Operating environment

```markdown
- Sealos version: v4.3.7
- Docker version: 
- Kubernetes version: 1.21
- Operating system: centos7.9
- Runtime environment: containerd
- Cluster size:
- Additional information:
```

**Comment by bxy4543** [comment]
非root用户吗？

**Comment by fu7100** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> Non-root user?

是的用户名不是root，但是它具有root权限。

**Comment by fu7100** [comment]
> 非root用户吗？

对非root用户，但具有root权限。

**Comment by bxy4543** [comment]
看起来像是因为sudo -E 导致其没有正确找到Kubeconfig配置

**Comment by fu7100** [comment]
> 看起来像是因为sudo -E 导致其没有正确找到Kubeconfig配置

我的用户叫ctg，它的家目录是/home/ctg，但是他是root
[root@master ~]# pwd
/home/ctg
[root@master ~]# id
uid=0(root) gid=0(root) groups=0(root) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
[root@master ~]#

**Comment by bxy4543** [comment]
ls $HOME/.kube 和ls /root/.kube看下
