### ISSUE TITLE
Inquiry About Deploying NoCoDB on Sealos

### ISSUE THREAD

**Issue by kl2111** [labring/sealos#4373]
### What is the problem this feature will solve?

I have been exploring the documentation and resources available at both [NoCoDB GitHub page](https://github.com/nocodb/nocodb) and [Sealos GitHub page](https://github.com/labring/sealos), but I am yet to find a definitive answer.

Recently, I attempted to set up NoCoDB within Sealos (sealos.io). I created a new application and configured it as follows:

Image Name: nocodb/nocodb:latest
Container Exposed Port: 8080
Environment Configuration:
NC_DB=mysql2://root:6****z4f@do****u-mysql.ns-s5xl6r8t.svc:3306?u=root&p=6****z4f&d=do****u
NC_AUTH_JWT_SECRET=569a1821-0a93-45e8-87ab-eb857f20a010
Local Storage: usr/app/data/

However, I have encountered an issue where the application remains in a 'creating' state and does not progress further. I am uncertain of the problem's root cause.

Could you please provide any guidance or reference information that might help in successfully deploying NoCoDB on Sealos? Any assistance or direction in this matter would be greatly appreciated.

**Comment by bxy4543** [comment]
sorry to see this issue too late, it seems that the app has been deleted

**Comment by kl2111** [comment]
thank you for reply.

I was able to successfully install nocodb on my Mac computer's local Docker using the following information. Can I use this same information([links](https://github.com/nocodb/nocodb#quick-try)) to install it on sealos?

```
# for MySQL
docker run -d --name nocodb-mysql \
-v "$(pwd)"/nocodb:/usr/app/data/ \
-p 8080:8080 \
-e NC_DB="mysql2://host.docker.internal:3306?u=root&p=password&d=d1" \
-e NC_AUTH_JWT_SECRET="569a1821-0a93-45e8-87ab-eb857f20a010" \
nocodb/nocodb:latest
```

> sorry to see this issue too late, it seems that the app has been deleted

**Comment by kl2111** [comment]
> sorry to see this issue too late, it seems that the app has been deleted

Installing the n8n application also encountered problems. Unlike nocodb, n8n has an instance, but it cannot operate normally.

![20231202_2200Google Chromesealos Cloud](https://github.com/labring/sealos/assets/66360035/65a026c0-b93e-487c-aa3f-ae27eeb64eb7)

**Comment by bxy4543** [comment]
![image](https://github.com/labring/sealos/assets/69408038/32b7a31e-c725-4b8d-9c72-177761ae54fa)
![image](https://github.com/labring/sealos/assets/69408038/1e8d9c90-be9a-456d-9cef-ae0688d36167)
@kl2111 
My test is OK, and the problem I have is that it can be started only by using the mysql2 driver link address. I wonder if you have the same problem?
