### ISSUE TITLE
Feature: Add flowise in the template market

### ISSUE THREAD

**Issue by csjuXYZ** [labring/sealos#4386]
### What is the problem this feature will solve?

Convenient flowise project deployment
https://github.com/FlowiseAI/Flowise

**Comment by zjy365** [comment]
@csjuXYZ 

Thank you for bringing this to our attention! The template is now supported, and you can deploy it using the following link:

[Flowise Template Deployment Link](https://template.cloud.sealos.io/deploy?templateName=flowise)

If you have any further questions or need additional assistance, feel free to let us know. We appreciate your support!
