### ISSUE TITLE
Use the environment variable serviceSubnet, podSubnet cannot take effect

### ISSUE THREAD

**Issue by xrjk** [labring/sealos#4387]
### Sealos Version

4.3.7

### How to reproduce the bug?

sealos run -e serviceSubnet=172.16.0.0/16 -e podSubnet=192.168.0.0/16 docker.io/labring/kubernetes-docker:v1.24.17-4.3.7 --masters 10.1.1.1,10.1.1.2,10.1.1.3 --nodes 10.1,1,4,10.1.1.5,10.1.1.6

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by xrjk** [comment]
apiVersion: v1
data:
  ClusterConfiguration: |
    apiServer:
      certSANs:
      - 127.0.0.1
      - apiserver.cluster.local
      - 10.103.97.2
      - 10.8.3.13
      extraArgs:
        audit-log-format: json
        audit-log-maxage: "7"
        audit-log-maxbackup: "10"
        audit-log-maxsize: "100"
        audit-log-path: /var/log/kubernetes/audit.log
        audit-policy-file: /etc/kubernetes/audit-policy.yml
        authorization-mode: Node,RBAC
        enable-aggregator-routing: "true"
        feature-gates: EphemeralContainers=true
      extraVolumes:
      - hostPath: /etc/kubernetes
        mountPath: /etc/kubernetes
        name: audit
        pathType: DirectoryOrCreate
      - hostPath: /var/log/kubernetes
        mountPath: /var/log/kubernetes
        name: audit-log
        pathType: DirectoryOrCreate
      - hostPath: /etc/localtime
        mountPath: /etc/localtime
        name: localtime
        pathType: File
        readOnly: true
      timeoutForControlPlane: 4m0s
    apiVersion: kubeadm.k8s.io/v1beta3
    certificatesDir: /etc/kubernetes/pki
    clusterName: kubernetes
    controlPlaneEndpoint: apiserver.cluster.local:6443
    controllerManager:
      extraArgs:
        bind-address: 0.0.0.0
        cluster-signing-duration: 876000h
        feature-gates: EphemeralContainers=true
      extraVolumes:
      - hostPath: /etc/localtime
        mountPath: /etc/localtime
        name: localtime
        pathType: File
        readOnly: true
    dns: {}
    etcd:
      local:
        dataDir: /var/lib/etcd
        extraArgs:
          listen-metrics-urls: http://0.0.0.0:2381
    imageRepository: registry.k8s.io
    kind: ClusterConfiguration
    kubernetesVersion: v1.24.17
    networking:
      dnsDomain: cluster.local
      podSubnet: 100.64.0.0/10
      serviceSubnet: 10.96.0.0/22
    scheduler:
      extraArgs:
        bind-address: 0.0.0.0
        feature-gates: EphemeralContainers=true
      extraVolumes:
      - hostPath: /etc/localtime
        mountPath: /etc/localtime
        name: localtime
        pathType: File
        readOnly: true
kind: ConfigMap
metadata:
  creationTimestamp: "2023-12-07T02:42:47Z"
  name: kubeadm-config
  namespace: kube-system
  resourceVersion: "204"
  uid: e6b5bf9d-a6e9-430a-9b8d-3c32337c9f96

**Comment by xrjk** [comment]
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  creationTimestamp: "2023-12-07T02:42:48Z"
  name: default
spec:
  hosts:
  - ips:
    - 10.8.3.13:22
    roles:
    - master
    - amd64
  image:
  - docker.io/labring/kubernetes-docker:v1.24.17-4.3.7
  ssh: {}
status:
  conditions:
  - lastHeartbeatTime: "2023-12-07T02:42:48Z"
    message: Applied to cluster successfully
    reason: Ready
    status: "True"
    type: ApplyClusterSuccess
  mounts:
  - env:
      SEALOS_SYS_CRI_ENDPOINT: /var/run/cri-dockerd.sock
      SEALOS_SYS_IMAGE_ENDPOINT: /var/run/image-cri-shim.sock
      criData: /var/lib/docker
      criDockerdData: /var/lib/cri-dockerd
      defaultVIP: 10.103.97.2
      podSubnet: 192.168.0.0/24
      registryConfig: /etc/registry
      registryData: /var/lib/registry
      registryDomain: sealos.hub
      registryPassword: passw0rd
      registryPort: "5000"
      registryUsername: admin
      sandboxImage: pause:3.7
      serviceSubnet: 172.16.0.0/16
    imageName: docker.io/labring/kubernetes-docker:v1.24.17-4.3.7
    labels:
      check: check.sh $registryData
      clean: clean.sh && bash clean-cri.sh $criData $criDockerdData
      clean-registry: clean-registry.sh $registryData $registryConfig
      image: ghcr.io/labring/lvscare:v4.3.7
      init: init-cri.sh && bash init.sh
      init-registry: init-registry.sh $registryData $registryConfig
      io.buildah.version: 1.30.0
      org.opencontainers.image.description: kubernetes-v1.24.17 container image
      org.opencontainers.image.licenses: MIT
      org.opencontainers.image.source: https://github.com/labring-actions/cache
      sealos.io.type: rootfs
      sealos.io.version: v1beta1
      version: v1.24.17
      vip: $defaultVIP
    mountPoint: /var/lib/containers/storage/overlay/b271f6c438827df91fe3efdc086754c1e3e72f82ac79dde1e293ad1f017cb1e8/merged
    name: default-lt6qc4rr
    type: rootfs
  phase: ClusterSuccess

**Comment by xrjk** [comment]
clusterfile 里的podSubnet: 192.168.0.0/24 serviceSubnet: 172.16.0.0/16 已经改了的呀，我用上面文件 sealos apply -f Clusterfile 问题依旧

**Comment by bxy4543** [comment]
你是安装好之后在apply的吗？

**Comment by cuisongliu** [comment]
你的用法不对。在安装集群之前修改，不支持安装后修改。
