### ISSUE TITLE
Error: failed to init runtime, cluster image kubernetes version cannot be empty

### ISSUE THREAD

**Issue by 2997215859** [labring/sealos#4399]
### Sealos Version

master-5c01b5a

### How to reproduce the bug?

``` install sealos
curl -sfL https://raw.githubusercontent.com/labring/sealos/main/scripts/cloud/install.sh -o /tmp/install.sh && bash /tmp/install.sh
```

### What is the expected behavior?

init fail when install sealos, follow:
![image](https://github.com/labring/sealos/assets/13400243/f95c2852-e143-4d10-be8e-eccf2e49674b)

Error: failed to init runtime, cluster image kubernetes version cannot be empty
<img width="977" alt="img_v3_0261_1512c944-1362-4b98-a2d5-1343065d68fg" src="https://github.com/labring/sealos/assets/13400243/38a96f1e-132b-478f-9a61-f57c24579dd3">

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by bxy4543** [comment]
`sealos reset` and retry install sealos cloud
