### ISSUE TITLE
sealos When deploying calico, it will scan the network card information of the host. It will look for the network card information starting with en and eth to obtain the IP. Can you add one starting with br?

### ISSUE THREAD

**Issue by charles-liming** [labring/sealos#4419]
### What is the problem this feature will solve?

sealos 部署 calico 的时候会扫描宿主机的网卡信息，会找en开头，eth开头的网卡信息，获取ip,这块能不能增加一个br 开头的，
我们服务器之前做虚拟化全部都是配置了桥接网卡，ip 绑定到了br上，现在的情况是部署calico 卡主了，原因是br 不在扫描范围

**Comment by cuisongliu** [comment]
调整一下网卡就可以了，这个你调整一下运行参数，具体的看一下镜像定义。

**Comment by bxy4543** [comment]
https://github.com/labring-actions/cluster-image/tree/main/applications/calico
修改nodeAddressAutodetectionV4.interface
