### ISSUE TITLE
sealos.io cannot open

### ISSUE THREAD

**Issue by a1576471428** [labring/sealos#4431]
### Sealos Version

v4.1.3

### How to reproduce the bug?

open  sealos.io

### What do you see instead?

![image](https://github.com/labring/sealos/assets/26965732/a8dd3ce7-557b-43d4-98d5-c5005e4e91c7)

![image](https://github.com/labring/sealos/assets/26965732/5cce7f55-9293-44cf-b78d-253f92e5c58d)

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by bxy4543** [comment]
https://sealos.run/
