### ISSUE TITLE
k3s failed to delete nodes, failed to reset the cluster, and could not add workload nodes after manual cleanup.

### ISSUE THREAD

**Issue by 46797536** [labring/sealos#4460]
### Sealos Version

v4.4.0-beta3

### How to reproduce the bug?

1、部署v1.24.17+k3s1后，使用sealos delete 和 sealos reset 命令删除失败
![image](https://github.com/labring/sealos/assets/46241382/f733b07d-d534-4a53-8b6a-95b034ad3671)

2、手动清理服务和删除目录后，重新部署集群时在添加节点环节报错
![image](https://github.com/labring/sealos/assets/46241382/843021f3-4c10-45d7-a26b-a2c0408fde70)

![image](https://github.com/labring/sealos/assets/46241382/73dc7edf-7737-44c0-9abc-7d121a4e1ca5)
异常节点日志
![image](https://github.com/labring/sealos/assets/46241382/600d8813-2f5a-4ef5-85ad-4f4da9053904)

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by bxy4543** [comment]
sealos版本多少呢

**Comment by bxy4543** [comment]
sealos版本需要大于v5.0.0

**Comment by 46797536** [comment]
> > sealos版本需要大于v5.0.0
> 
> 改成v5.0.0 beta4后可以删除，但是重新部署经常出现 工作节点加入集群时报： ![image](https://private-user-images.githubusercontent.com/46241382/294849114-1eb5caa3-048b-4ac5-8cc8-bc960938ee31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDQxMDMsIm5iZiI6MTcwNDcwMzgwMywicGF0aCI6Ii80NjI0MTM4Mi8yOTQ4NDkxMTQtMWViNWNhYTMtMDQ4Yi00YWM1LThjYzgtYmM5NjA5MzhlZTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA4NTAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMTA3NzliNzU4ZTAxYjk1MGJiMTIwMWY3MzYyNjUyZjlmOWU2ZTlkMzQ0OTViMTUyMDM4YzA0MTFlZWRmYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ezaSDhUrWUp4qozT2Ezn-LXYD3cuT39rmEpheouflWA) sealos部署时报错： ![image](https://private-user-images.githubusercontent.com/46241382/294849187-44d79f7e-32cd-4d0c-a368-f684ddd5a51e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDQxMDMsIm5iZiI6MTcwNDcwMzgwMywicGF0aCI6Ii80NjI0MTM4Mi8yOTQ4NDkxODctNDRkNzlmN2UtMzJjZC00ZDBjLWEzNjgtZjY4NGRkZDVhNTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA4NTAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3ZjdlMmY1NWY2MzFhNTM1NDc1NTc3ZDI3MTMwMDNmMzE0ZjQyNDZkMjkwODEyYThjZjNkYWQxZWM2NDQ5ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eFFEfcfZgVVNAPPHwh-UCAWC0QShJyn-hon7aw5hbQs)

好像是ipvs没启动成功，vip telnet不通，用master节点ip能telnet通

**Comment by qwehua-github** [comment]
有解决吗


---
Is there any solution?
