### ISSUE TITLE
BUG: sealos build cluster image error

### ISSUE THREAD

**Issue by lingdie** [labring/sealos#4478]
### Sealos Version

v4.3.7

### How to reproduce the bug?

kubefile:
```
FROM scratch

USER 65532:65532

COPY registry registry

CMD "echo success"
```

one deployment yaml in `mainfests` dir

![image](https://github.com/labring/sealos/assets/56745951/59712662-a6f3-43b4-9f05-eca980d44e10)

then, build image:
![image](https://github.com/labring/sealos/assets/56745951/033f68c1-04a8-49eb-9d91-4bc9b20c6769)

at lates, run this image, an error occurs:

![image](https://github.com/labring/sealos/assets/56745951/0a5dc954-4045-4013-93ed-b0e4ed67c976)

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cuisongliu** [comment]
因为你只有registry目录，但是registry目录不会复制。所以导致目录不存在。。。ah
