### ISSUE TITLE
Is there currently a version of sealos that supports deployment by non-root users?

### ISSUE THREAD

**Issue by 1473371932** [labring/sealos#4505]
### What is the problem this feature will solve?

如题，或者说目前所有版本都不支持呢？我在 Changlog 中没有找到对应内容

**Comment by luanshaotong** [comment]
据我所知，没有。这个功能非常少见，并且不够明确。你希望的non-root是指ssh连接用户是非root，还是指用户不能切换为root，还是指当前用户连sudo权限都没有？在我看来没有sudo权限是无法安装的，因为涉及更改多个系统相关的配置。不能切换为root用户但具备sudo权限是很奇怪的需求，至少我没有想到使用场景。非root用户ssh是可实现的，我曾经写过类似的脚本，在其他的k8s发行版中。不过不清楚sealos是否支持这种小众需求。

**Comment by geyaandy** [comment]
> 据我所知，没有。这个功能非常少见，并且不够明确。你希望的non-root是指ssh连接用户是非root，还是指用户不能切换为root，还是指当前用户连sudo权限都没有？在我看来没有sudo权限是无法安装的，因为涉及更改多个系统相关的配置。不能切换为root用户但具备sudo权限是很奇怪的需求，至少我没有想到使用场景。非root用户ssh是可实现的，我曾经写过类似的脚本，在其他的k8s发行版中。不过不清楚sealos是否支持这种小众需求。

我这边有个类似需求，目前生产主机都是不用用root直接登录的，必须用非root用户（此用户可以有sudo权限）登录后切到root，这种情况sealos安装的时候指定了此用户（有sudo权限）但是会安装失败（ #4324），使用root用户就没有此问题，不知道这是否是4.3.7版本的一个bug

**Comment by Maple1401** [comment]
需求+1

生产都是非 root 用户登录，登录后可sudo 或 su - root， 希望尽快支持普通用户  ssh ，再切换 root 部署的方式。

**Comment by fengxsong** [comment]
As far as I know it's already supported. you can run `sealos` command without `root`/`sudo` privileges(but certain requirements must be met such as `uidmap` and `fuse-overlayfs`) and use any user with sudo privileges as the user for remote ssh connections to create a new cluster.

@1473371932 @Maple1401 @geyaandy

**Comment by luanshaotong** [comment]
> As far as I know it's already supported. you can run `sealos` command without `root`/`sudo` privileges(but certain requirements must be met such as `uidmap` and `fuse-overlayfs`) and use any user with sudo privileges as the user for remote ssh connections to create a new cluster.
> 
> @1473371932 @Maple1401 @geyaandy

@fengxsong 是不是指直接修改clusterfile中的ssh字段？[https://sealos.io/docs/self-hosting/lifecycle-management/reference/sealos/commands/apply](url)

**Comment by fengxsong** [comment]
> > As far as I know it's already supported. you can run `sealos` command without `root`/`sudo` privileges(but certain requirements must be met such as `uidmap` and `fuse-overlayfs`) and use any user with sudo privileges as the user for remote ssh connections to create a new cluster.
> > @1473371932 @Maple1401 @geyaandy
> 
> @fengxsong 是不是指直接修改clusterfile中的ssh字段？[https://sealos.io/docs/self-hosting/lifecycle-management/reference/sealos/commands/apply](url)

yes.

**Comment by geyaandy** [comment]
你好，邮件我已收到~！祝你的生活越来越好..........
