### ISSUE TITLE
BUG: failed to run labring/kubernetes:1.29.1 duel to connection errors.

### ISSUE THREAD

**Issue by luanshaotong** [labring/sealos#4514]
### Sealos Version

4.3.7

### How to reproduce the bug?

 `sealos run labring/kubernetes:v1.29.1-4.3.7`

### What do you see instead?

Stucked in pulling images.
![1706343282073](https://github.com/labring/sealos/assets/14962503/6a7058bb-59b6-408c-8736-a424e886487b)
Logs from containerd: 
![1706343302234](https://github.com/labring/sealos/assets/14962503/2b66bcd0-43b6-4e07-b8fd-baf3f6ed5e69)
I think those images should be involved in the cluster image, but they are not.

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system: ubuntu 22.04
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by bxy4543** [comment]
1.29 需要 sealos 版本大于 v5.0

**Comment by zaunist** [comment]
> 1.29 需要 sealos 版本大于 v5.0

这里是网络连接超时，我使用 sealos 官网文档安装，官网给出来的脚本就会安装失败。这里在拉镜像的时候，会去 https://us-west2-docker.pkg.dev 这个地址，国内应该是无法访问的。

**Comment by luanshaotong** [comment]
> 1.29 需要 sealos 版本大于 v5.0

@bxy4543 So why the image tag contains 4.3.7？
