### ISSUE TITLE
Docs: In the privatized deployment guide, does the one-click script have to be executed under the root user? If so, I hope there will be an explicit explanation

### ISSUE THREAD

**Issue by yujianet** [labring/sealos#4516]
### Documentation Section

Sealos 集群部署

### What is the current documentation state?

[Sealos 集群部署](https://sealos.io/zh-Hans/docs/self-hosting/sealos/installation#:~:text=%24%20curl%20%2DsfL%20https%3A%2F%2Fmirror.ghproxy.com%2Fhttps%3A%2F%2Fraw.githubusercontent.com%2Flabring%2Fsealos%2Fmain%2Fscripts%2Fcloud%2Finstall.sh%20%2Do%20%2Ftmp%2Finstall.sh%20%26%26%20bash%20%2Ftmp%2Finstall.sh%20%5C)
在ubuntu系统中，默认是普通用户角色，但执行一键安装脚本却提示“mkdir没有/root权限”。
我仔细确认了文档中的命令行提示符 `$ curl -sfL https ...` 是以$开头，说明是普通权限用户，而且没有sudo。
但很可惜，执行失败，在经过互联网搜索后，才发现一篇《[sealos踩坑记录](https://www.cnblogs.com/lgjbky/p/17265845.html)》中提到“一定用root用户”。而后正常安装。

**Comment by bxy4543** [comment]
需要root权限下安装cloud
