### ISSUE TITLE
After deploying fastgpt and filling in the openai api key, the language model suddenly disappeared for a while.

### ISSUE THREAD

**Issue by 17607683785** [labring/sealos#4522]
### Sealos Version

v4.1.3

### How to reproduce the bug?

<img width="398" alt="Snipaste_2024-02-03_17-03-38" src="https://github.com/labring/sealos/assets/107823857/a04ab27b-4922-45b8-b344-82e265649855">

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by zjy365** [comment]
It should be that the relevant configuration file of fastgpt is incorrect.
