### ISSUE TITLE
[Password] After changing the password and logging in again, it prompts "Incorrect user or password"

### ISSUE THREAD

**Issue by taurusduan** [labring/sealos#4525]
### Sealos Version

4.3.7

### How to reproduce the bug?

1，已经安装了证书。
2，密码是复制的，不存在中途出现错误的可能性。
3，登录不了，也无法提供其他东西了。
4，有什么重置密码的手段吗？

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by bxy4543** [comment]
@xudaotutou

**Comment by bxy4543** [comment]
执行`kubectl get pod -n sealos -l app.kubernetes.io/instance=sealos-mongodb` 看下数据库是否正常
