### ISSUE TITLE
Feature: labring/calico CMD delete -f chart.values.yaml

### ISSUE THREAD

**Issue by wisheen** [labring/sealos#4543]
### What is the problem this feature will solve?

chart.values.yaml generate by init.sh, helm upgrade -i -f chart.values.yaml will be overriding charts/calico/values.yaml. If you want to customize Clusterfile file, it will not take effect.
~~~yml
---
apiVersion: apps.sealos.io/v1beta1
kind: Config
metadata:
  creationTimestamp: null
  name: calico
spec:
  data: |
    installation:
      enabled: true
      kubernetesProvider: ""
      calicoNetwork:
        nodeAddressAutodetectionV4:
          interface: "eth0"
  path: charts/calico/values.yaml
  strategy: merge
~~~

### If you have solution，please describe it

1. calico default value firstFound maybe better
2. delete helm -f chart.values.yaml
3. If change the default value is best directly modify charts/calico/values.yml in kubeimage

**Comment by willzhang** [comment]
Here maybe help: https://github.com/labring-actions/cluster-image/tree/main/applications/calico
