### ISSUE TITLE
BUG: deploy cluster not using internal registry

### ISSUE THREAD

**Issue by LiaoSirui** [labring/sealos#4561]
### Sealos Version

v4.3.7

### How to reproduce the bug?

deploy cluster using 

```bash
sealos run \
    \
    -e criData=/var/lib/containerd \
    -e registryData=/var/lib/registry \
    -e registryDomain=platform-local.hub \
    -e registryPort=5000 \
    \
    docker.io/labring/kubernetes:v1.28.7-4.3.7 \
    docker.io/labring/cilium:v1.14.7 \
    docker.io/labring/helm:v3.14.1 \
    docker.io/labring/nerdctl:v1.7.0 \
    \
    --port=22 \
    --user='root' \
    --pk='/root/.ssh/id_rsa' \
    \
    --debug=true \
    \
    --masters 10.244.244.20
```

### What is the expected behavior?

deploy cluster using internal registry

### What do you see instead?

[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
I0305 21:05:34.300215  107333 checks.go:828] using image pull policy: IfNotPresent
I0305 21:05:34.332485  107333 checks.go:854] pulling: registry.k8s.io/kube-apiserver:v1.28.7

### Operating environment

```markdown
- Sealos version: v4.3.7
- Docker version:
- Kubernetes version: none
- Operating system: rocky linux 9.3
- Runtime environment: none
- Cluster size: single node
- Additional information:
```

**Comment by LiaoSirui** [comment]
maybe same: https://github.com/labring/sealos/issues/4514

**Comment by cuisongliu** [comment]
using 5.x的sealos

**Comment by caijian76** [comment]
使用sealos 5可以初始化安装k8s v1.28，但是从v1.27升级到v1.28，依然遇到相同的问题。
