### ISSUE TITLE
BUG: etcd container can`t restart

### ISSUE THREAD

**Issue by liuhaichaogithub** [labring/sealos#4584]
### Sealos Version

v4.1.6

### How to reproduce the bug?

Sealos  v4.1.6   k8s 1.26  use docker runingtime   , When the cluster runs for a period of time, it will inexplicably hang up，etcd container cant up ，use docker start cli err is 
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to create new parent process: namespace path: lstat /proc/23674/ns/ipc: no such file or directory: unknown
Error: failed to start containers: 7d10ef08273c

![image](https://github.com/labring/sealos/assets/40063899/38a9d8aa-dc6e-4ca2-906d-be866700a036)

### What is the expected behavior?

Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to create new parent process: namespace path: lstat /proc/23674/ns/ipc: no such file or directory: unknown
Error: failed to start containers: 7d10ef08273c

### What do you see instead?

Sealos  v4.1.6   k8s 1.26  use docker runingtime   , When the cluster runs for a period of time, it will inexplicably hang up，etcd container cant up ，use docker start cli err is 
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to create new parent process: namespace path: lstat /proc/23674/ns/ipc: no such file or directory: unknown
Error: failed to start containers: 7d10ef08273c

![image](https://github.com/labring/sealos/assets/40063899/38a9d8aa-dc6e-4ca2-906d-be866700a036)

### Operating environment

```markdown
- Sealos version:4.1.6
- Docker version:23.0.1
- Kubernetes version:1.26
- Operating system: centos 7.6
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cuisongliu** [comment]
升级一下runc应该可以解决
