### ISSUE TITLE
BUG: unable to install sealos-cloud by one step. install script

### ISSUE THREAD

**Issue by perlinson** [labring/sealos#4610]
### Sealos Version

v4.3.7

### How to reproduce the bug?

run curl -sfL https://mirror.ghproxy.com/https://raw.githubusercontent.com/labring/sealos/main/scripts/cloud/install.sh -o /tmp/install.sh && bash /tmp/install.sh \   --image-registry=registry.cn-shanghai.aliyuncs.com --zh \   --proxy-prefix=https://mirror.ghproxy.com

### What do you see instead?

kubectl apply -f manifests/deploy.yaml -f manifests/rbac.yaml -f manifests/ingress.yaml
serviceaccount/desktop-frontend created
service/desktop-frontend created
configmap/desktop-frontend-config created
deployment.apps/desktop-frontend created
clusterrole.rbac.authorization.k8s.io/auth-system-manager-role created
clusterrolebinding.rbac.authorization.k8s.io/desktop-user-editor-role-binding created
clusterrolebinding.rbac.authorization.k8s.io/desktop-operationrequest-editor-role-binding created
clusterrolebinding.rbac.authorization.k8s.io/desktop-deleterequest-editor-role-binding created
role.rbac.authorization.k8s.io/recharge-gift-cm-reader created
rolebinding.rbac.authorization.k8s.io/recharge-gift-cm-reader-rolebinding created
clusterrole.rbac.authorization.k8s.io/account-editor-role created
clusterrolebinding.rbac.authorization.k8s.io/desktop-account-editor-role-binding created
Warning: annotation "kubernetes.io/ingress.class" is deprecated, please use 'spec.ingressClassName' instead
Error from server (InternalError): error when creating "manifests/ingress.yaml": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": failed to call webhook: Post "[https://ingress-nginx-controller-admission.ingress-nginx.svc:443/networking/v1/ingresses?timeout=10s](https://ingress-nginx-controller-admission.ingress-nginx.svc/networking/v1/ingresses?timeout=10s)": no endpoints available for service "ingress-nginx-controller-admission"
Error: exit status 1
Error: exit status 1

### Operating environment

```markdown
SealosVersion:
  buildDate: "2023-10-30T16:19:05Z"
  compiler: gc
  gitCommit: f39b2339
  gitVersion: 4.3.7
  goVersion: go1.20.10
  platform: linux/amd64
```

### Additional information

是用的家庭宽带，系统是 ubuntu 22.04  内存11g

**Comment by codecoron** [comment]
I also meet this issue 
> sealos pull -q registry.cn-shanghai.aliyuncs.com/labring/kubeblocks-redis:v0.8.2
Error: initializing source docker://registry.cn-shanghai.aliyuncs.com/labring/kubeblocks-redis:v0.8.2: reading manifest v0.8.2 in registry.cn-shanghai.aliyuncs.com/labring/kubeblocks-redis: requested access to the resource is denied

**Comment by bxy4543** [comment]
`kubectl get pod -A`
execute the command to check whether the basic components are started successfully.
