### ISSUE TITLE
BUG: Kirin v10 arm machine uses sealos 4.3.7 to install k8s and reports an error

### ISSUE THREAD

**Issue by gogogo2156** [labring/sealos#4626]
### Sealos Version

4.3.7

### How to reproduce the bug?

Clusterfile如下：
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  name: default
spec:
  hosts:
  - ips:
    - 10.2.241.11:22
    roles:
    - master
    - arm64
  - ips:
    - 10.2.241.12:22
    - 10.2.241.13:22
    roles:
    - node
    - arm64
  image:
  - xx.x.xxx.x:8088/basic/labring/kubernetes-docker:v1.27.12-4.3.7-arm64
  - xx.x.xxx.x:8088/basic/labring/helm:v3.14.1-arm64
  - xx.x.xxx.x:8088/basic/labring/calico:v3.26.1-arm64
  ssh:
    pk: /root/.ssh/id_rsa
    port: 22
status: {}

执行：sealos apply -f Clusterfile

### What is the expected behavior?

请帮忙分析什么原因导致的？谢谢

### What do you see instead?

执行：systemctl status kubelet 信息如下：

   Memory: 56.1M
   CGroup: /system.slice/kubelet.service
           └─1963451 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --container-ru>

Mar 26 16:21:06 node01 kubelet[1963451]: I0326 16:21:06.948625 1963451 pod_container_deletor.go:80] "Container not found in pod's containers" containerID="01b914388ea5aa3ffda7c84f30199956c8c358b>
Mar 26 16:21:06 node01 kubelet[1963451]: I0326 16:21:06.967373 1963451 pod_container_deletor.go:80] "Container not found in pod's containers" containerID="a7d1b0c6641f2102ad7f17b66ea8f5f8976927d>
Mar 26 16:21:06 node01 kubelet[1963451]: I0326 16:21:06.988180 1963451 pod_container_deletor.go:80] "Container not found in pod's containers" containerID="b88f11875387d4aa6a9083fd1bea6e4b62a5274>
Mar 26 16:21:07 node01 kubelet[1963451]: E0326 16:21:07.721716 1963451 pod_workers.go:1294] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"etcd\" with CrashLoopBackOff: \">
Mar 26 16:21:07 node01 kubelet[1963451]: E0326 16:21:07.933028 1963451 pod_workers.go:1294] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-controller-manager\" with C>
Mar 26 16:21:07 node01 kubelet[1963451]: E0326 16:21:07.962439 1963451 pod_workers.go:1294] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-scheduler\" with CrashLoopB>
Mar 26 16:21:07 node01 kubelet[1963451]: E0326 16:21:07.963466 1963451 pod_workers.go:1294] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-apiserver\" with CrashLoopB>
Mar 26 16:21:08 node01 kubelet[1963451]: I0326 16:21:08.007799 1963451 pod_container_deletor.go:80] "Container not found in pod's containers" containerID="2a9c2675f6bc7b750fdf59134021b93b833c3e3>
Mar 26 16:21:08 node01 kubelet[1963451]: I0326 16:21:08.022454 1963451 pod_container_deletor.go:80] "Container not found in pod's containers" containerID="4d192d4ee9833fe0f5acb40b6cad44fe356a1d6>
Mar 26 16:21:08 node01 kubelet[1963451]: I0326 16:21:08.044307 1963451 pod_container_deletor.go:80] "Container not found in pod's containers" containerID="cc027e4ef2ec381d831b39be324ad25288a7e4c>
lines 1-23/23 (END)

执行journalctl -xeu kubelet 错误信息见附件
[0.txt](https://github.com/labring/sealos/files/14755528/0.txt)

### Operating environment

```markdown
- Sealos version: 4.3.7
- Docker version: 25.0.5
- Kubernetes version:v1.27.12
- Operating system: 4.19.90-52.22.v2207.ky10.aarch64
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by SupRenekton** [comment]
请问下，问题解决了么，我也碰到了和你类似的问题，有解决办法能告知下么，谢谢
