### ISSUE TITLE
BUG: ssh cannot connect to sealos after running in centos7.9 environment. The saelos parameter nofile is configured too large.

### ISSUE THREAD

**Issue by Michaelxu2022** [labring/sealos#4641]
### Sealos Version

v4.3.7

### How to reproduce the bug?

1.安装干净的centos7.9系统   2. ssh 版本9.4，系统内核版本5.4

2.saelos run后，所有服务器节点ssh断开，无法再次连接。经调试发现系统报错Could not set limit for ‘nofile’: Operation not permitted

### Operating environment

```markdown
- Sealos version:4.3.7
- Docker version:
- Kubernetes version:v1.27.7
- Operating system: centos7.9
- Runtime environment: 8c16g 200G disk
- Cluster size:3 master, 3 node
- Additional information:
```

**Comment by bxy4543** [comment]
你使用的云服务器吗？
参考这个[问题帮助](https://www.alibabacloud.com/help/en/ecs/could-not-set-limit-for-nofile-operation-not-permitted-is-displayed-when-you-log-on-to-an-ecs-instance-through-ssh)

**Comment by Michaelxu2022** [comment]
[EXTERNAL EMAIL]
请看我截图，这个值1048576是saelos设置的。并非我改的。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Michaelxu2022** [comment]
请问下saelos 在代码里面哪定义的1048476呢？
