### ISSUE TITLE
BUG: can not git clone repo

### ISSUE THREAD

**Issue by knightgao** [labring/sealos#4690]
### Sealos Version

laster

### How to reproduce the bug?

warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'service/license/src/components/Account/index.tsx'
  'service/license/src/components/account/index.tsx'
  'service/license/src/components/Signin/auth/useAuthList.tsx'
  'service/license/src/components/signin/auth/useAuthList.tsx'
  'service/license/src/components/Signin/auth/useCustomError.tsx'
  'service/license/src/components/signin/auth/useCustomError.tsx'
  'service/license/src/components/Signin/auth/useLanguage.tsx'
  'service/license/src/components/signin/auth/useLanguage.tsx'
  'service/license/src/components/Signin/auth/usePassword.tsx'
  'service/license/src/components/signin/auth/usePassword.tsx'
  'service/license/src/components/Signin/auth/useProtocol.tsx'
  'service/license/src/components/signin/auth/useProtocol.tsx'
  'service/license/src/components/Signin/auth/useSms.tsx'
  'service/license/src/components/signin/auth/useSms.tsx'
  'service/license/src/components/Signin/background.tsx'
  'service/license/src/components/signin/background.tsx'
  'service/license/src/components/Signin/index.tsx'
  'service/license/src/components/signin/index.tsx'

### What is the expected behavior?

git clone repo

### Operating environment

```markdown
1
```

### Additional information

warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'service/license/src/components/Account/index.tsx'
  'service/license/src/components/account/index.tsx'
  'service/license/src/components/Signin/auth/useAuthList.tsx'
  'service/license/src/components/signin/auth/useAuthList.tsx'
  'service/license/src/components/Signin/auth/useCustomError.tsx'
  'service/license/src/components/signin/auth/useCustomError.tsx'
  'service/license/src/components/Signin/auth/useLanguage.tsx'
  'service/license/src/components/signin/auth/useLanguage.tsx'
  'service/license/src/components/Signin/auth/usePassword.tsx'
  'service/license/src/components/signin/auth/usePassword.tsx'
  'service/license/src/components/Signin/auth/useProtocol.tsx'
  'service/license/src/components/signin/auth/useProtocol.tsx'
  'service/license/src/components/Signin/auth/useSms.tsx'
  'service/license/src/components/signin/auth/useSms.tsx'
  'service/license/src/components/Signin/background.tsx'
  'service/license/src/components/signin/background.tsx'
  'service/license/src/components/Signin/index.tsx'
  'service/license/src/components/signin/index.tsx'

**Comment by zjy365** [comment]
The error you're encountering is related to case-sensitive paths on a case-insensitive filesystem, which is common on filesystems like those used by macOS and Windows. These filesystems treat files with names that differ only by case as the same file, leading to conflicts.
