### ISSUE TITLE
添加集群失败，提示usage of cri endpoints without url scheme is deprecated and can cause kubelete error in the future.

### ISSUE THREAD

**Issue by Johnnes-Xnn** [labring/sealos#4711]
### Sealos Version

v4.3.0

### What do you see instead?

![Uploading 微信截图_202404261
![lQLPKGt947MSqRHNA0HNBnOw6nM5MFvUzwkGFwdcayfdAA_1651_833](https://github.com/labring/sealos/assets/49221563/2e287b84-d044-4808-b69a-b6eb94a2623f)
![lQLPKG9fDqnz2PnNAk7NBoKw8OnY2II4svgGF-7I9o6KAA_1666_590](https://github.com/labring/sealos/assets/49221563/ba1a2d56-ce47-452a-972d-cec372d8a9c1)
55544.png…]()

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by Johnnes-Xnn** [comment]
更新图片
![Uploading 微信截图_20240426155544.png…]()

**Comment by Johnnes-Xnn** [comment]
![lQLPKGt947MSqRHNA0HNBnOw6nM5MFvUzwkGFwdcayfdAA_1651_833](https://github.com/labring/sealos/assets/49221563/ae1e8ab7-4d48-455c-9f10-9886e8601daa)

地址：https://github.com/labring/sealos/assets/49221563/ae1e8ab7-4d48-455c-9f10-9886e8601daa

**Comment by Johnnes-Xnn** [comment]
![微信截图_20240426155544](https://github.com/labring/sealos/assets/49221563/aab5da43-f6b9-4146-8c1a-538d7cc794a1)

报错图片地址：https://github.com/labring/sealos/assets/49221563/aab5da43-f6b9-4146-8c1a-538d7cc794a

**Comment by Johnnes-Xnn** [comment]
![lQLPKGt947MSqRHNA0HNBnOw6nM5MFvUzwkGFwdcayfdAA_1651_833](https://github.com/labring/sealos/assets/49221563/e21a0516-fd4a-4e38-91b7-7dbd004666d5)

报错图片地址：https://github.com/labring/sealos/assets/49221563/e21a0516-fd4a-4e38-91b7-7dbd004666d5

**Comment by ghostloda** [comment]
看起来是kubelet健康检查失败，看下kubelet服务是否正常运行。
