### ISSUE TITLE
添加node节点遇到 Error: can't apply application type images only since RootFS type image is not applied yet，这个问题是什么原因？

### ISSUE THREAD

**Issue by fu7100** [labring/sealos#4746]
### Sealos Version

v4.3.7

### How to reproduce the bug?

sealos add --nodes xxxx --debug

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cuisongliu** [comment]
镜像版本太老

**Comment by fu7100** [comment]
> 镜像版本太老

是什么镜像版本太老？ 我是同一套k8s添加node，镜像都是一样的。

**Comment by fu7100** [comment]
这个问题有人遇到过吗，急！！！

**Comment by ricardolrl** [comment]
我将labring/kubernetes:v1.26.15的镜像mount至本地后 根据Kubefile重新构建镜像 可以构建成功 但是sealos run的时候会出现该错误 Error: can't apply application type images only since RootFS type image is not applied yet @cuisongliu

**Comment by fu7100** [comment]
> 我将labring/kubernetes:v1.26.15的镜像mount至本地后 根据Kubefile重新构建镜像 可以构建成功 但是sealos run的时候会出现该错误 Error: can't apply application type images only since RootFS type image is not applied yet @cuisongliu

兄弟解决了吗？ 不知道这个报错是啥意思呢

**Comment by ricardolrl** [comment]
> 么意思呢

这个是镜像的问题 镜像构建的时候没有指定type

**Comment by fu7100** [comment]
这个问题已经解决了，是因为执行add的机器上镜像被删除导致的。

**Comment by bxy4543** [comment]
> 这个问题已经解决了，是因为执行add的机器上镜像被删除导致的。

close issue
