### ISSUE TITLE
BUG: The local registry has a large number of network connections that will not be released

### ISSUE THREAD

**Issue by xmwilldo** [labring/sealos#4774]
### Sealos Version

v4.1.4

### How to reproduce the bug?

1.netstat -anpl|grep 5000
<img width="1080" alt="CleanShot 2024-06-13 at 13 57 36@2x" src="https://github.com/labring/sealos/assets/16560252/4ad3b82c-eada-46f0-ae3c-158f9590d1a3">

### Operating environment

```markdown
- Sealos version: v4.1.4
- Docker version: v23.0.0
- Kubernetes version: v1.25.6
- Operating system: ubuntu20.04
- Runtime environment: cloud(tencent, 8G memory, 2core cpu, 50G storage)
- Cluster size: 1 master,1 node
- Additional information:
```

**Comment by ghostloda** [comment]
Same to https://github.com/labring/sealos/issues/3344
