### ISSUE TITLE
BUG: Modifying pod_cidr via pod_subnet does not take effect

### ISSUE THREAD

**Issue by cnmac** [labring/sealos#4779]
### Sealos Version

v4.3.7

### How to reproduce the bug?

1. sealos reset
2. rm ~/.sealos/ -rf 
3. sealos gen docker.io/labring/kubernetes:v1.27.14 --masters 192.168.x.x --pk=$HOME/.ssh/id_rsa -o ./Clusterfile
4. sed -i "s|100.64.0.0/10|100.77.0.0/10|g" ./Clusterfile
5. sed -i "s|10.96.0.0/22|10.99.0.0/22|g" ./Clusterfile
6. sealos apply -f ./Clusterfile
7. sealos run labring/helm:v3.14.1
8. sealos run labring/cilium:v1.14.11 --env ExtraValues="ipam.mode=kubernetes"
9. kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o wide

### What is the expected behavior?

The IP address assigned to the expected pod is 100.77.x.x

### What do you see instead?

In fact, the IP assigned to the pod is 100.64.x.x:
![image](https://github.com/labring/sealos/assets/21333000/c1030583-ce99-4f23-bb91-a71860943261)
The running configuration of the kube-controller-manager pod is as follows：
![image](https://github.com/labring/sealos/assets/21333000/0b2205bf-4f4b-40ec-a2f4-e5ab6f49d7b7)

### Operating environment

```markdown
- Sealos version: 4.3.7
- Docker version: none
- Kubernetes version: 1.27.14
- Operating system: centos7
- Runtime environment: 32core 128G
- Cluster size: 1
- Additional information: none
```

**Comment by gclm** [comment]
这个问题 5.0.0-beta5 版本也存在
<img width="1086" alt="image" src="https://github.com/labring/sealos/assets/27618687/09827cff-ad38-4848-aa80-375604e8241d">

**Comment by lingdie** [comment]
![image](https://github.com/labring/sealos/assets/56745951/a5276b0c-f6fe-4a18-9868-adcccb08a3b3)
![image](https://github.com/labring/sealos/assets/56745951/434c843f-cf1f-4aff-a8b8-8d34ec971ea0)
