### ISSUE TITLE
Can you add more details about the offline installation of k8s?

### ISSUE THREAD

**Issue by camuselliot** [labring/sealos#4793]
### Documentation Section

离线安装 K8s

### What is your suggestion?

老师，您好。
首先在有网络的环境中导出集群镜像： 这里面能否增加
具体k8s和各种网络插件 给一个最佳的推荐  
在执行命令 sealos run kubernetes.tar 
遇到以下错误 
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
^[2^NW0621 15:16:42.324677   16367 checks.go:835] detected that the sandbox image "sealos.hub:5000/pause:3.9" of the container runtime is inconsistent with that used by kubeadm. It is recommended that using "registry.k8s.io/pause:3.9" as the CRI sandbox image.
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR ImagePull]: failed to pull image registry.k8s.io/kube-apiserver:v1.28.11: output: E0621 15:08:59.182331   16827 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \"registry.k8s.io/kube-apiserver:v1.28.11\": failed to resolve reference \"registry.k8s.io/kube-apiserver:v1.28.11\": failed to do request: Head \"https://us-west2-docker.pkg.dev/v2/k8s-artifacts-prod/images/kube-apiserver/manifests/v1.28.11\": dial tcp 74.125.23.82:443: i/o timeout" image="registry.k8s.io/kube-apiserver:v1.28.11"
time="2024-06-21T15:08:59+08:00" level=fatal msg="pulling image: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \"registry.k8s.io/kube-apiserver:v1.28.11\": failed to resolve reference \"registry.k8s.io/kube-apiserver:v1.28.11\": failed to do request: Head \"https://us-west2-docker.pkg.dev/v2/k8s-artifacts-prod/images/kube-apiserver/manifests/v1.28.11\": dial tcp 74.125.23.82:443: i/o timeout"
, error: exit status 1
	[ERROR ImagePull]: failed to pull image registry.k8s.io/kube-controller-manager:v1.28.11: output: E0621 15:11:33.659002   16943 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/kube-controller-manager:v1.28.11\": failed to resolve reference \"registry.k8s.io/kube-controller-manager:v1.28.11\": failed to do request: Head \"https://us-west2-docker.pkg.dev/v2/k8s-artifacts-prod/images/kube-controller-manager/manifests/v1.28.11\": dial tcp 74.125.204.82:443: i/o timeout" image="registry.k8s.io/kube-controller-manager:v1.28.11"
time="2024-06-21T15:11:33+08:00" level=fatal msg="pulling image: failed to pull and unpack image \"registry.k8s.io/kube-controller-manager:v1.28.11\": failed to resolve reference \"registry.k8s.io/kube-controller-manager:v1.28.11\": failed to do request: Head \"https://us-west2-docker.pkg.dev/v2/k8s-artifacts-prod/images/kube-controller-manager/manifests/v1.28.11\": dial tcp 74.125.204.82:443: i/o timeout"
, error: exit status 1
	[ERROR ImagePull]: failed to pull image registry.k8s.io/kube-scheduler:v1.28.11: output: E0621 15:14:07.264143   17021 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/kube-scheduler:v1.28.11\": failed to resolve reference \"registry.k8s.io/kube-scheduler:v1.28.11\": failed to do request: Head \"https://us-west2-docker.pkg.dev/v2/k8s-artifacts-prod/images/kube-scheduler/manifests/v1.28.11\": dial tcp 74.125.204.82:443: i/o timeout" image="registry.k8s.io/kube-scheduler:v1.28.11"
time="2024-06-21T15:14:07+08:00" level=fatal msg="pulling image: failed to pull and unpack image \"registry.k8s.io/kube-scheduler:v1.28.11\": failed to resolve reference \"registry.k8s.io/kube-scheduler:v1.28.11\": failed to do request: Head \"https://us-west2-docker.pkg.dev/v2/k8s-artifacts-prod/images/kube-scheduler/manifests/v1.28.11\": dial tcp 74.125.204.82:443: i/o timeout"
, error: exit status 1
	[ERROR ImagePull]: failed to pull image registry.k8s.io/kube-proxy:v1.28.11: output: E0621 15:16:42.295317   17286 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \"registry.k8s.io/kube-proxy:v1.28.11\": failed to resolve reference \"registry.k8s.io/kube-proxy:v1.28.11\": failed to do request: Head \"https://us-west2-docker.pkg.dev/v2/k8s-artifacts-prod/images/kube-proxy/manifests/v1.28.11\": dial tcp 108.177.125.82:443: i/o timeout" image="registry.k8s.io/kube-proxy:v1.28.11"
time="2024-06-21T15:16:42+08:00" level=fatal msg="pulling image: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \"registry.k8s.io/kube-proxy:v1.28.11\": failed to resolve reference \"registry.k8s.io/kube-proxy:v1.28.11\": failed to do request: Head \"https://us-west2-docker.pkg.dev/v2/k8s-artifacts-prod/images/kube-proxy/manifests/v1.28.11\": dial tcp 108.177.125.82:443: i/o timeout"
, error: exit status 1
	[ERROR ImagePull]: failed to pull image registry.k8s.io/pause:3.9: output: E0621 15:19:05.165352   17615 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = Unavailable desc = error reading from server: EOF" image="registry.k8s.io/pause:3.9"
time="2024-06-21T15:19:05+08:00" level=fatal msg="pulling image: rpc error: code = Unavailable desc = error reading from server: EOF"
, error: exit status 1
	[ERROR ImagePull]: failed to pull image registry.k8s.io/etcd:3.5.12-0: output: time="2024-06-21T15:19:05+08:00" level=fatal msg="validate service connection: validate CRI v1 image API for endpoint \"unix:///run/containerd/containerd.sock\": rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial unix /run/containerd/containerd.sock: connect: no such file or directory\""
, error: exit status 1
	[ERROR ImagePull]: failed to pull image registry.k8s.io/coredns/coredns:v1.10.1: output: E0621 15:21:39.262383   18253 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/coredns/coredns:v1.10.1\": failed to resolve reference \"registry.k8s.io/coredns/coredns:v1.10.1\": failed to do request: Head \"https://us-west2-docker.pkg.dev/v2/k8s-artifacts-prod/images/coredns/coredns/manifests/v1.10.1\": dial tcp 108.177.125.82:443: i/o timeout" image="registry.k8s.io/coredns/coredns:v1.10.1"
time="2024-06-21T15:21:39+08:00" level=fatal msg="pulling image: failed to pull and unpack image \"registry.k8s.io/coredns/coredns:v1.10.1\": failed to resolve reference \"registry.k8s.io/coredns/coredns:v1.10.1\": failed to do request: Head \"https://us-west2-docker.pkg.dev/v2/k8s-artifacts-prod/images/coredns/coredns/manifests/v1.10.1\": dial tcp 108.177.125.82:443: i/o timeout"
, error: exit status 1

### Why is this change beneficial?

可能因为特殊原因 很多人会遇到这种情况

**Comment by connorshen** [comment]
没人解决

---
No one solves
