### ISSUE TITLE
BUG: sealos registry copy无法鉴权通过，即便执行过sealos login命令，依然会提示：authentication required

### ISSUE THREAD

**Issue by fu7100** [labring/sealos#4802]
### Sealos Version

v4.3.7

### How to reproduce the bug?
执行命令：
[root@master sealos4.4.0]# sealos  registry copy reg.ide.local:5000/titanide/busybox:latest sealos.hub:5000
Getting image source signatures
Error: trying to reuse blob sha256:5cc84ad355aaa64f46ea9c7bbcc319a9d808ab15088a27209c9e70ef86e5a2aa at destination: checking whether a blob sha256:5cc84ad355aaa64f46ea9c7bbcc319a9d808ab15088a27209c9e70ef86e5a2aa exists in sealos.hub:5000/titanide/busybox: authentication required

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by lingdie** [comment]
两个镜像仓库都要login吧

**Comment by fu7100** [comment]
> 两个镜像仓库都要login吧

尝试过不行
