### ISSUE TITLE
How to install through sealos when Dockerhub cannot be accessed

### ISSUE THREAD

**Issue by liuchengwen** [labring/sealos#4826]
### If you have solution，please describe it

![微信图片_20240629132646](https://github.com/labring/sealos/assets/22442450/7cf69ac3-211c-436e-899a-11d54a4ab05c)

**Comment by zijiren233** [comment]
try use `registry.cn-shanghai.aliyuncs.com/labring` mirror

**Comment by willzhang** [comment]
Image list in aliyun mirror:
https://sealos.io/zh-Hans/docs/self-hosting/lifecycle-management/quick-start/deploy-kubernetes
https://github.com/labring-actions/cluster-image-docs/blob/main/docs/aliyun-shanghai/rootfs.md
