### ISSUE TITLE
BUG: Failed to add node node

### ISSUE THREAD

**Issue by gclm** [labring/sealos#4829]
### Sealos Version

5.0.0-beta5

### How to reproduce the bug?

sealos add --nodes 10.0.12.12 --debug

### What is the expected behavior?

添加节点成功

### What do you see instead?

<img width="1438" alt="image" src="https://github.com/labring/sealos/assets/27618687/277697e1-244f-44b7-9c55-486dbf3b0475">
完整的debug日志在下面链接中
[node.log](https://github.com/user-attachments/files/16043343/node.log)

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by bxy4543** [comment]
run `ipvsadm -L -n` on the added node to view the ipvs rules.

**Comment by gclm** [comment]
问题已经解决，双网卡，需要看是组网网卡是那个
