### ISSUE TITLE
多网卡适配方案下, sealos init 会默认给主机添加一条路由. 

### ISSUE THREAD

**Issue by oldthreefeng** [labring/sealos#483]
**哪个命令或者组件**
sealos  init   #409  #468 

**详细描述你的需求/任务**
详细描述你的需求和任务要求
多网卡适配方案下, sealos init 会默认给主机添加一条路由
假定 默认路由ip为 `192.168.160.1` .
部署的`node`主机ip为 `172.16.111.123`  . 默认的master主机ip为`172.16.111.121`

node节点得添加VIP `10.103.97.2` 到` 172.16.111.121`  的一个路由. 不然ipvs不通

```
ip route add  10.103.97.2  via 172.16.111.123
```

**是否有解决方案，如果有请详述**
通过更改`lvscare`来解决这个问题.

**Comment by oldthreefeng** [comment]
@fanux  给 lvscare创建一张网卡可行么. 或者直接复用 ipvs网卡？ 

```
ip link add sealyun-ipvs0 type dummy
ip  addr add 10.103.97.12/32 dev sealyun-ipvs0
```

**Comment by fanux** [comment]
@oldthreefeng 确认没问题可以，我之前貌似想创建网卡，忘记是在本机还是在什么情况下不通来着就放弃了。   
1. 我觉得负载master这个场景能通加网卡没问题。
2. lvscare通过SDK创建这个dummy网卡更合适，调用ip命令担心有些环境没这个命令

**Comment by oldthreefeng** [comment]
> lvscare通过SDK创建这个dummy网卡更合适，调用ip命令担心有些环境没这个命令

我写的route 应该可以再改改, 实现操作网卡应该也不难.

**Comment by fanux** [comment]
> > lvscare通过SDK创建这个dummy网卡更合适，调用ip命令担心有些环境没这个命令
> 
> 我写的route 应该可以再改改, 实现操作网卡应该也不难.

操作网卡 lvscare代码里有的

**Comment by oldthreefeng** [comment]
> 操作网卡 lvscare代码里有的 

看来得加上去了。 

今天碰到一个用户出现了问题。 **如果node节点是多网卡， 并且node节点出意外重启了** 。
这个时候。 我们手动给加的路由会丢失， 导致 node连不上master。 
```
1月 22 05:20:41 server103 kubelet[1390]: E0122 05:20:41.776047    1390 controller.go:136] failed to ensure node lease exists, will retry in 7s, error: Get https://apiserver.cluster.local:6443/apis/c
1月 22 05:20:41 server103 kubelet[1390]: E0122 05:20:41.809637    1390 kubelet.go:2268] node "xxx" not found
```
临时解决.  把这条路由补回来。
```
$ sealos route add --host 10.103.97.2 --gateway $nodeIP
或者使用
$ ip route add  10.103.97.2  via  $nodeIP
```

**Comment by hhstu** [comment]
哈喽，这个问题目前的状态是什么？

**Comment by fanux** [comment]
这个特性可以直接在lvscare中实现
