### ISSUE TITLE
BUG: brief descricontainer_linux.go:318: starting container process caused "process_linux.go:281: applying cgroup configuration for process caused \"No such device or address\""ption of the bug

### ISSUE THREAD

**Issue by SupRenekton** [labring/sealos#4836]
### Sealos Version

sealos_4.3.7_linux_arm64.tar.gz

### How to reproduce the bug?

国产linux系统：4.19.90-24.4.v2101.ky10.aarch64 #1 SMP Mon May 24 14:45:37 CST 2021 aarch64 aarch64 aarch64 GNU/Linux
sealos gen labring/kubernetes:v1.25.16 \
  labring/helm:v3.13.2 \
  labring/calico:v3.24.6 \
  --masters x.x.x.x,x.x.x.x,x.x.x.x --output Clusterfile
Clusterfile配置没有修改，直接apply：sealos apply -f Clusterfile

k8s集群建起来后，只有coredns显示pod没起来，CrashLoopBackOff状态
报错信息：
failed to create containerd task: failed to create shim task : OCI runtime create failed: container_linux.go:318: starting container process caused "process_linux.go:281: applying cgroup configuration for process caused \"No such device or address\""

### What do you see instead?

2个coredns pod CrashLoopBackOff，其他pod状态正常
failed to create containerd task: failed to create shim task : OCI runtime create failed: container_linux.go:318: starting container process caused "process_linux.go:281: applying cgroup configuration for process caused \"No such device or address\""

### Operating environment

```markdown
- Sealos version: sealos_4.3.7_linux_arm64.tar.gz
- Docker version: 无
- Kubernetes version: kubernetes:v1.25.16
- Operating system: 4.19.90-24.4.v2101.ky10.aarch64
- Runtime environment: 
- Cluster size: 3个Master节点
- Additional information:
  labring/helm:v3.13.2
  labring/calico:v3.24.6
```

**Comment by bxy4543** [comment]
安装前检查下节点是不是已经安装了runc

**Comment by SupRenekton** [comment]
> 安装前检查下节点是不是已经安装了runc

是有containerd的，然后现在我改了下containerd的cgroup配置，重启了下containerd后coredns正常了，不过有点奇怪，本来kubelet的cgroup配置应该和运行时的cgroup保持一致的，我三台麒麟的系统上kubelet的cgroup是systemd，containerd的cgroup改成SystemdCgroup = false后反而正常了，不是到是不是国产的麒麟系统有什么bug

**Comment by bxy4543** [comment]
> > 安装前检查下节点是不是已经安装了runc
> 
> 是有containerd的，然后现在我改了下containerd的cgroup配置，重启了下containerd后coredns正常了，不过有点奇怪，本来kubelet的cgroup配置应该和运行时的cgroup保持一致的，我三台麒麟的系统上kubelet的cgroup是systemd，containerd的cgroup改成SystemdCgroup = false后反而正常了，不是到是不是国产的麒麟系统有什么bug

因为系统上本身安装了导致的，需要先卸载掉，新版本安装前应该会检测的，

**Comment by fengxsong** [comment]
国产化的系统都只能用cgroupfs，至少我遇到的都是这样。

**Comment by cuisongliu** [comment]
> 国产化的系统都只能用cgroupfs，至少我遇到的都是这样。

+1
