### ISSUE TITLE
Chore: Replace go-gomail/gomail with wneessen/go-mail

### ISSUE THREAD

**Issue by wneessen** [labring/sealos#4840]
### What is the problem this feature will solve?

I've noticed that https://github.com/labring/sealos/blob/main/controllers/account/controllers/utils/email.go is using https://github.com/go-gomail/gomail for sending SMTP mails. go-mail/gomail is not actively maintained anymore and hasn't seen an update/response to an issue by the maintainer/merged PR in more than 6-7 years.

### If you have solution，please describe it

I am the maintainer of https://github.com/wneessen/go-mail which is pretty similar to go-mail/gomail but actively maintained and following modern standards and idiomatic Go. If there is any interest, I am willing to replace go-gomail/gomail in `email.go` to wneessen/go-mail.

Let me know if a PR is of interest.

### What alternatives have you considered?

N/A

**Comment by bxy4543** [comment]
Thanks for providing
