### ISSUE TITLE
God help me! ! ! Kirin sp3 system arm architecture machine, deploying k8s is stuck here in kubelet startup/etc/kubernetes/manifest static pod, kubelet reports error getting node xxx not found

### ISSUE THREAD

**Issue by SupRenekton** [labring/sealos#4871]
### Sealos Version

sealos_4.3.7_linux_arm64.tar.gz

### How to reproduce the bug?

操作系统：麒麟V10（SP3）/(Lance)-aarch64-Build23/20230324
内核版本：4.19.90-52.22.v2207.ky10.aarch64
sealos版本：4.3.7_linux_arm64、其他版本的也都试过了
k8s版本：1.23.17、1.24.2、1.25.5、1.25.6、1.25.16、1.29.6都试过了

### What is the expected behavior?

卡在Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests"
静态pod如kube-apiserver、kube-controller-manager、kube-scheduler这些都起不来；kubelet状态是running，报错静态pod容器捡不起来，getting node xxx not found；containerd状态running，报错failed to get sandbox container task: no running task found

然后比较奇怪的是我之前用麒麟V10(SP2)的系统利用sealos4.3.7是能够正常拉起k8s集群的，只不过有个cgroup的问题导致coredns起不来，需要改containerd的cgropu配置，改的和kubelet的cgroup不一致才行，这样我觉得有隐患，所以听取网上意见更换成麒麟SP3系统，其他的都不变，结果连集群都拉不起来了！！！！！！ 来个大神救我，卡2天了，难受

### Operating environment

```markdown
- Sealos version:4.3.7
- Docker version:
- Kubernetes version:1.25.16
- Operating system:
- Runtime environment:
- Cluster size:3个master
- Additional information:
```

**Comment by SupRenekton** [comment]
![微信图片_20240709161958](https://github.com/labring/sealos/assets/35164543/878fdedc-c2a4-4e23-b523-2a16ad41a116)

**Comment by SupRenekton** [comment]
![微信图片_202407091619581](https://github.com/labring/sealos/assets/35164543/9ad92bf4-4f6e-46eb-a385-ce1a15c79554)
![微信图片_202407091619582](https://github.com/labring/sealos/assets/35164543/93b5262d-975a-4698-9faf-7b483c21ea9a)
![微信图片_202407091619587](https://github.com/labring/sealos/assets/35164543/6bea785c-3c17-4b17-8174-590deba1d430)
![微信图片_202407091619588](https://github.com/labring/sealos/assets/35164543/0424e82d-d3c7-4407-9ff3-2a97195f925d)
![微信图片_202407091619584](https://github.com/labring/sealos/assets/35164543/5b0546ac-e79d-4d9b-ad4a-d371de3780a8)
![微信图片_202407091619585](https://github.com/labring/sealos/assets/35164543/9716d613-68a1-440a-bd90-fc32e234e076)
![微信图片_202407091619586](https://github.com/labring/sealos/assets/35164543/435899de-5874-479b-91ae-7a18cd051427)

**Comment by SupRenekton** [comment]
![微信图片_20240709165155](https://github.com/labring/sealos/assets/35164543/8a387002-c7c2-443b-ae6e-e204f422fde7)

**Comment by bxy4543** [comment]
crictl ps -a
crictl logs  看看容器日志

**Comment by SupRenekton** [comment]
> crictl ps -a crictl logs 看看容器日志

![微信图片_20240709171140](https://github.com/labring/sealos/assets/35164543/7363eafb-aa05-4756-b066-a94d1fdbcb42)
报错是解析符号链接失败，不太懂啥意思

**Comment by bxy4543** [comment]
containerd日志排查下呢

**Comment by SupRenekton** [comment]
自己解决了，应该是runc的问题，sp3麒麟系统自带的/usr/local/bin/runc换成sp2的runc后就正常了

**Comment by daihy8759** [comment]
sp2 的 runc 哪里来呢
