### ISSUE TITLE
/usr/bin/runc is not an executable program

### ISSUE THREAD

**Issue by linuxflow-hqukz** [labring/sealos#4877]
### Sealos Version

5.0.0-beta5

### How to reproduce the bug?

执行sealos apply -f Clusterfile  ，Clusterfile如下： xxxx均为内网IP
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  name: default
spec:
  hosts:
  - ips:
    - x.x.x.x:22
    roles:
    - master
    - amd64
  - ips:
    - x.x.x.x:22
    roles:
    - node
    - amd64
  image:
  - x.x.x.x:8080/labring/kubernetes:v1.29.6
  - x.x.x.x:8080/labring/helm:v3.9.4
  - x.x.x.x:8080/labring/cilium:v1.14.9
  ssh:
    passwd: "PASSWORD"
    pk: /root/.ssh/id_rsa
    port: 22
status: {}
执行完成后，会报错，报错内容为：
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

Unfortunately, an error has occurred:
        timed out waiting for the condition

This error is likely caused by:
        - The kubelet is not running
        - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
        - 'systemctl status kubelet'
        - 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI.
Here is one example how you may list all running Kubernetes containers by using crictl:
        - 'crictl --runtime-endpoint unix:///run/containerd/containerd.sock ps -a | grep kube | grep -v pause'
        Once you have found the failing container, you can inspect its logs with:
        - 'crictl --runtime-endpoint unix:///run/containerd/containerd.sock logs CONTAINERID'
error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher
2024-07-10T11:29:16 error Applied to cluster error: failed to init masters: init master0 failed, error: exit status 1. Please clean and reinstall
Error: failed to init masters: init master0 failed, error: exit status 1. Please clean and reinstall
检查kubelet状态，错误提示：
Jul 10 12:08:00 k8s-master-01 kubelet[24373]: E0710 12:08:00.064905   24373 kuberuntime_manager.go:1172] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v2.task/k8s.io/a035ab8223d9d9db07cc92d89fa259d6708dc59ba4ab523e1216cd7458025bdd/log.json: no such file or directory): fork/exec /usr/bin/runc: exec format error: unknown" pod="kube-system/kube-scheduler-k8s-master-01"
检查containerd状态，错误提示：
Jul 10 12:09:21 k8s-master-01 containerd[24036]: time="2024-07-10T12:09:21.072501176+08:00" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:kube-scheduler-k8s-master-01,Uid:0a9e7e740d78dd02274543ddd3c28942,Namespace:kube-system,Attempt:0,} failed, error" error="failed to create containerd task: failed to create shim task: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v2.task/k8s.io/580589d578e6fa9d791ba8b2cffd221b4c1c24159015fbf34ee0891ebd427d16/log.json: no such file or directory): fork/exec /usr/bin/runc: exec format error: unknown"
最终通过file /usr/bin/runc发现/usr/bin/runc不是可执行程序，
![微信图片_20240710121357](https://github.com/labring/sealos/assets/146060041/98a44917-bb12-45c5-97c1-b91e03185064)

在另外一个节点执行 yum install runc -y，安装完成再查看file /usr/bin/runc为可执行程序。
![a244443b81728790faf0f6cc606a8c8](https://github.com/labring/sealos/assets/146060041/7eaf45b3-1c37-4443-954d-555dc736f6d3)

### Operating environment

```markdown
- Sealos version:5.0.0-beta5
- Docker version:无
- Kubernetes version:1.29.6
- Operating system:CentOS 7.9
- Runtime environment:虚拟机 4核16G内存64G存储
- Cluster size:
- Additional information:
```

**Comment by bxy4543** [comment]
The installation failed because runc 1.13 was not available for download when it was released. This problem has been fixed by using the latest image.

**Comment by fu7100** [comment]
我也遇到类似的问题，请问是怎么解决？
