### ISSUE TITLE
BUG:  The latest version ( v5.0.0 ) of the sealos privatization deployment will fail due to a public image pull issue

### ISSUE THREAD

**Issue by ai-liuys** [labring/sealos#4892]
### Sealos Version

v5.0.0

### How to reproduce the bug?

1.  centos 7.8 
2.  sealos-v5.0.0 deploy k8s in private cloud environment
3.  SHELL:  curl -sfL https://mirror.ghproxy.com/https://raw.githubusercontent.com/labring/sealos/v5.0.0-beta5/scripts/cloud/install.sh -o /tmp/install.sh && bash /tmp/install.sh   --cloud-version=v5.0.0-beta5   --image-registry=registry.cn-shanghai.aliyuncs.com --zh   --proxy-prefix=https://mirror.ghproxy.com

4.  ERROR INFO:  
W0712 03:47:59.829652   67789 images.go:80] could not find officially supported version of etcd for Kubernetes v1.27.11, falling back to the nearest etcd version (3.5.0-0)
[config/images] Pulled k8s.gcr.io/kube-apiserver:v1.27.11
[config/images] Pulled k8s.gcr.io/kube-controller-manager:v1.27.11
[config/images] Pulled k8s.gcr.io/kube-scheduler:v1.27.11
[config/images] Pulled k8s.gcr.io/kube-proxy:v1.27.11
failed to pull image "k8s.gcr.io/pause:3.5": output: E0712 03:49:52.907061   67905 remote_image.go:167] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"k8s.gcr.io/pause:3.5\": failed to resolve reference \"k8s.gcr.io/pause:3.5\": failed to do request: Head \"https://k8s.gcr.io/v2/pause/manifests/3.5\": dial tcp 108.177.97.82:443: connect: connection refused" image="k8s.gcr.io/pause:3.5"
time="2024-07-12T03:49:52-04:00" level=fatal msg="pulling image: rpc error: code = Unknown desc = failed to pull and unpack image \"k8s.gcr.io/pause:3.5\": failed to resolve reference \"k8s.gcr.io/pause:3.5\": failed to do request: Head \"https://k8s.gcr.io/v2/pause/manifests/3.5\": dial tcp 108.177.97.82:443: connect: connection refused"
, error: exit status 1
To see the stack trace of this error execute with --v=5 or higher
2024-07-12T03:49:52 error Applied to cluster error: failed to init masters: master pull image failed, error: exit status 1
Error: failed to init masters: master pull image failed, error: exit status  1

### What is the expected behavior?

i think this is a bug ,  if user use this scripts to deploy k8s by sealos , this will try to get images from docker.io/xxx ;

in the sealo project shoud considering  the internet is diffrent , this project  code shoud make user skip to get images form docker.io/xxx .

The code can avoid such an error, like 
---
 W0712 03:47:59.829652   67789 images.go:80] could not find officially supported version of etcd for Kubernetes v1.27.11, falling back to the nearest etcd version (3.5.0-0)
[config/images] Pulled k8s.gcr.io/kube-apiserver:v1.27.11
[config/images] Pulled k8s.gcr.io/kube-controller-manager:v1.27.11
[config/images] Pulled k8s.gcr.io/kube-scheduler:v1.27.11
[config/images] Pulled k8s.gcr.io/kube-proxy:v1.27.11
failed to pull image "k8s.gcr.io/pause:3.5": output: E0712 03:49:52.907061   67905 remote_image.go:167] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"k8s.gcr.io/pause:3.5\": failed to resolve reference \"k8s.gcr.io/pause:3.5\": failed to do request: Head \"https://k8s.gcr.io/v2/pause/manifests/3.5\": dial tcp 108.177.97.82:443: connect: connection refused" image="k8s.gcr.io/pause:3.5"
time="2024-07-12T03:49:52-04:00" level=fatal msg="pulling image: rpc error: code = Unknown desc = failed to pull and unpack image \"k8s.gcr.io/pause:3.5\": failed to resolve reference \"k8s.gcr.io/pause:3.5\": failed to do request: Head \"https://k8s.gcr.io/v2/pause/manifests/3.5\": dial tcp 108.177.97.82:443: connect: connection refused"
, error: exit status 1
To see the stack trace of this error execute with --v=5 or higher

### Operating environment

```markdown
- Sealos version: v5.0.0(latest)
- Docker version: null
- Kubernetes version: v1.27.11
- Operating system: centos-7.8
- Runtime environment: containerd
- Cluster size: 1
- Additional information: mabey code shoud fix this bug , otherwise user will not success deploy k8s . 
This is a sad story！！！
```

**Comment by lingdie** [comment]
你的操作系统内核版本是多少？

麻烦给出 `uname -a` 的结果。

**Comment by ai-liuys** [comment]
操作系统内核版本： 
[root@nro-node-01 ~]# uname -a
Linux nro-node-01 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

More:   
1.  测试发现的，我看了相关的源码，根据实验现象推测应该是私有环境中的  127.0.0.1/xxx/xxx:xxx  镜像需要重命名成为   k8s.gcr.io/kube-controller-manager:v1.27.11  等资源镜像就可以了；
2.  我不晓得是否存在隐藏配置项是否可以实现此能力。2024年6月之前国内还是可以拉取到这些镜像的，但是自从  dockerHub 把中国大陆封禁以后就无法拉取这些镜像文件了。
3. 如果用户是香港地区的服务器或者国外的服务器部署环境自然没啥问题。 BTW

**Comment by lingdie** [comment]
请在系统内核高于5.09的机器上测试部署，系统内核过低无法安装sealos cloud

**Comment by ai-liuys** [comment]
thank you , 按照建议系统内核升级到 > 5.4 的机器上测试部署,  系统成功的完成了部署，非常感谢！
由于集群部署资源的限制， sealos 会是一个很好的部署方案备选。
这个问题可以关闭。感谢 * more

**Comment by StLeoX** [comment]
你好 @ai-liuys 你把 sealos 回退到什么版本
