### ISSUE TITLE
Support modifying kubelet rootdir when installing k8s cluster

### ISSUE THREAD

**Issue by lllicg** [labring/sealos#4997]
### What is the problem this feature will solve?

Is it possible to support modifying kubelet root-dir during the installation of k8s cluster. In the file /usr/lib/systemd/system/kubelet.service. d/10-kubeadm. conf, add KUBELET_EXTRA_ARGS="-- root dir=/data/dock/kubelet"

**Comment by cuisongliu** [comment]
不建议这样做，建议还是做软链接，如果这样操作可能会导致监控以及kb一些组件的不可用。
