### ISSUE TITLE
BUG: sealos reset nil pointer

### ISSUE THREAD

**Issue by zijiren233** [labring/sealos#5007]
### Sealos Version

v5.0.0

### How to reproduce the bug?

sealos reset

### What do you see instead?

![img_v3_02e7_f295c4c1-12ee-405a-aecf-79ce047fe78g](https://github.com/user-attachments/assets/a8292b3a-7bbc-4081-accd-b783b657d627)

### Operating environment

```markdown
- Sealos version: v5.0.0
- Kubernetes version: v1.27.11
```

**Comment by yangxggo** [comment]
You need to provide more premise descriptions, such as: 1. The status of the cluster before reset, 2. The number of master and node nodes, 3. Which version of sealos was used to initialize and install the cluster, and has it been upgraded?

**Comment by yangxggo** [comment]
You need to provide more descriptions, such as: 
1. The status of the cluster before reset.
2. The number of master and node nodes.
3. Which version of sealos was used to initialize and install the cluster? 
4. Have the cluster and sealos versions been updated?

**Comment by yangxggo** [comment]
Did you specify master or node by --masters or --nodes when you running `sealos reset`?

**Comment by zijiren233** [comment]
> Did you specify master or node by --masters or --nodes when you running `sealos reset`?运行 `sealos reset` 时，您是否通过 --masters 或 --nodes 指定了主节点或节点？

No, Just run `sealos reset`
