### ISSUE TITLE
BUG: There is a fake ip:10.103.97.2 in the Clusterfile with sealos v5.0.0 gen

### ISSUE THREAD

**Issue by snakeliwei** [labring/sealos#5029]
### Sealos Version

v5.0.0

### How to reproduce the bug?

sealos gen registry.cn-shanghai.aliyuncs.com/labring/kubernetes:v1.28.12            registry.cn-shanghai.aliyuncs.com/labring/helm:v3.14.1            registry.cn-shanghai.aliyuncs.com/labring/cilium:v1.15.8            --masters 10.10.16.5,10.10.16.7,10.10.16.8            --nodes 10.10.16.11,10.10.16.12,10.10.16.14            -i '/root/.ssh/id_rsa' --output ~/Clusterfile

### What is the expected behavior?
```
apiServer:
  certSANs:
  - 127.0.0.1
  - apiserver.cluster.local
  - 10.10.16.5
  - 10.10.16.7
  - 10.10.16.8
 ```

### What do you see instead?

```
apiServer:
  certSANs:
  - 127.0.0.1
  - apiserver.cluster.local
  - 10.103.97.2
  - 10.10.16.5
  - 10.10.16.7
  - 10.10.16.8
 ```

### Operating environment

```markdown
- Sealos version: v5.0.0
- Docker version: v20.10.7
- Kubernetes version: v1.28.12
- Operating system: Rocky 9.4
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by fanux** [comment]
10.103.97.2 is the local LB IP
