### ISSUE TITLE
BUG: deploy nginx Error: can't apply application type images only since RootFS type image is not applied yet

### ISSUE THREAD

**Issue by biao-lvwan** [labring/sealos#5033]
### Sealos Version

5.0.0-beta5

### How to reproduce the bug?

![image](https://github.com/user-attachments/assets/b2616a1e-a7d8-48bf-ac17-9f011cf3f322)
Follow the helm installation steps on the official website: https://sealos.run/docs/self-hosting/lifecycle-management/operations/build-image/build-image-helm_charts, an error occurred during run

### What is the expected behavior?

Hope nginx can be pulled up

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by willzhang** [comment]
这里有些示例和镜像：https://github.com/labring-actions/cluster-image/tree/main/applications/nginx
