### ISSUE TITLE
sealos run Error: signal: killed

### ISSUE THREAD

**Issue by sharkat** [labring/sealos#5106]
### Sealos Version

5.0.0

### How to reproduce the bug?

![QQ_1727251467658](https://github.com/user-attachments/assets/2812456b-11fd-4af8-b4d8-8cc4a7694723)
![QQ_1727251490677](https://github.com/user-attachments/assets/82097b4b-280f-4ce5-a903-670af50825fd)
![QQ_1727251530883](https://github.com/user-attachments/assets/55699506-b733-4760-993b-7c38a632e726)
![QQ_1727251563595](https://github.com/user-attachments/assets/b1921db2-9517-4dbe-b8fa-b28185ae4a09)
![QQ_1727251595720](https://github.com/user-attachments/assets/e69c02af-7b8a-430d-8832-8bbcd2efb3af)

### What is the expected behavior?

sealos run images:v0.0.1 执行相关脚本通过helm install中间件 调用检查脚本 等待相关pod就绪，手动执行脚本没问题，通过run执行到中途Error: signal: killed 就报错了。

### What do you see instead?

Error: signal: killed 

### Operating environment

```markdown
- Sealos version:5.0.0
- Docker version:
- Kubernetes version:1.27.7
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by bxy4543** [comment]
脚本加上 set -ex 打印下报错看看

**Comment by sharkat** [comment]
> 脚本加上 set -ex 打印下报错看看



> 脚本加上 set -ex 打印下报错看看

好的 稍等 我重新build个镜像，我手动直接去/var/lib/sealos/data/default/ 执行脚本是没报错的。我试试

**Comment by sharkat** [comment]
> 脚本加上 set -ex 打印下报错看看

 sealos run harbor.xxxx.com/sealos/middleware:v0.0.9
2024-09-25T17:07:51 info start to install app in this cluster
2024-09-25T17:07:51 info Executing SyncStatusAndCheck Pipeline in InstallProcessor
2024-09-25T17:07:51 info Executing ConfirmOverrideApps Pipeline in InstallProcessor
2024-09-25T17:07:51 info Executing PreProcess Pipeline in InstallProcessor
Trying to pull harbor.xxxx.com/sealos/middleware:v0.0.9
Getting image source signatures
Copying blob dfcacdfca3a2 done  
Copying config 8a6a61263a done  
Writing manifest to image destination
Storing signatures
2024-09-25T17:09:02 info Executing pipeline MountRootfs in InstallProcessor.
2024-09-25T17:09:06 info Executing pipeline MirrorRegistry in InstallProcessor.
2024-09-25T17:09:06 info trying default http mode to sync images to hosts [192.168.31.103:22]
2024-09-25T17:09:24 info Executing UpgradeIfNeed Pipeline in InstallProcessor
+ source install_tools.sh
++ set -ex

---------------------------------------------------------------------------------------------
+ print_colored_message warning 'create namespace and node node labels '
+ '[' warning == success ']'
+ '[' warning == failure ']'
+ '[' warning == warning ']'
+ echo -e '\e[33m---------------------------------------------------------------------------------------------
WARNING

create namespace and node node labels 

---------------------------------------------------------------------------------------------\e[0m'
---------------------------------------------------------------------------------------------
WARNING

create namespace and node node labels 

---------------------------------------------------------------------------------------------
+ kubectl create namespace model
namespace/model created
+ kubectl create namespace harbor
namespace/harbor created
+ kubectl create namespace logging
namespace/logging created
+ kubectl label nodes --all nvidia.com/gpu=T4
node/nv4090-server103 labeled
+ kubectl label nodes --all gpu=gpu
node/nv4090-server103 labeled
+ kubectl label nodes --all task-type=train
node/nv4090-server103 labeled
+ install_redis
+ helm_install redis charts/redis/ model charts/redis/values.yaml
+ local release_name=redis
+ local chart_path=charts/redis/
+ local namespace=model
+ local values_file=charts/redis/values.yaml
+ local max_retries=30
+ print_colored_message warning '正在安装 redis...'
+ '[' warning == success ']'
+ '[' warning == failure ']'
+ '[' warning == warning ']'
+ echo -e '\e[33m---------------------------------------------------------------------------------------------
WARNING

正在安装 redis...

---------------------------------------------------------------------------------------------\e[0m'
---------------------------------------------------------------------------------------------
WARNING

正在安装 redis...

---------------------------------------------------------------------------------------------
+ helm install redis charts/redis/ --namespace model -f charts/redis/values.yaml
NAME: redis
LAST DEPLOYED: Wed Sep 25 17:09:24 2024
NAMESPACE: model
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: redis
CHART VERSION: 18.8.2
APP VERSION: 7.2.4

** Please be patient while the chart is being deployed **

Redis&reg; can be accessed via port 6379 on the following DNS name from within your cluster:

    redis-master.model.svc.cluster.local



To get your password run:

    export REDIS_PASSWORD=$(kubectl get secret --namespace model redis -o jsonpath="{.data.redis-password}" | base64 -d)

To connect to your Redis&reg; server:

1. Run a Redis&reg; pod that you can use as a client:

   kubectl run --namespace model redis-client --restart='Never'  --env REDIS_PASSWORD=$REDIS_PASSWORD  --image harbor.xffuture.com/sealer-public/redis:7.2.4-debian-11-r2 --command -- sleep infinity

   Use the following command to attach to the pod:

   kubectl exec --tty -i redis-client \
   --namespace model -- bash

2. Connect using the Redis&reg; CLI:
   REDISCLI_AUTH="$REDIS_PASSWORD" redis-cli -h redis-master

To connect to your database from outside the cluster execute the following commands:

    export NODE_IP=$(kubectl get nodes --namespace model -o jsonpath="{.items[0].status.addresses[0].address}")
    export NODE_PORT=$(kubectl get --namespace model -o jsonpath="{.spec.ports[0].nodePort}" services redis-master)
    REDISCLI_AUTH="$REDIS_PASSWORD" redis-cli -h $NODE_IP -p $NODE_PORT
+ wait_for_pods_ready model 30
+ local namespace=model
+ local max_retries=30
+ local count=0
+ print_colored_message warning '正在检查命名空间 '\''model'\'' 中的 Pods 是否运行中...'
+ '[' warning == success ']'
+ '[' warning == failure ']'
+ '[' warning == warning ']'
+ echo -e '\e[33m---------------------------------------------------------------------------------------------
WARNING

正在检查命名空间 '\''model'\'' 中的 Pods 是否运行中...

---------------------------------------------------------------------------------------------\e[0m'
---------------------------------------------------------------------------------------------
WARNING

正在检查命名空间 'model' 中的 Pods 是否运行中...

---------------------------------------------------------------------------------------------
+ '[' 0 -lt 30 ']'
+ sleep 30
++ kubectl get pods --namespace=model -o custom-columns=NAME:.metadata.name,STATUS:.status.phase
++ grep -v Running
++ grep -v Succeeded
++ grep -v NAME
+ non_running_pods='redis-master-0   Pending'
+ '[' -n 'redis-master-0   Pending' ']'
+ print_colored_message warning 'Pods 未进入 Running 状态，请耐心等待Pod准备就绪... \nredis-master-0   Pending'
+ '[' warning == success ']'
+ '[' warning == failure ']'
+ '[' warning == warning ']'
+ echo -e '\e[33m---------------------------------------------------------------------------------------------
WARNING

Pods 未进入 Running 状态，请耐心等待Pod准备就绪... \nredis-master-0   Pending

---------------------------------------------------------------------------------------------\e[0m'
---------------------------------------------------------------------------------------------
WARNING

Pods 未进入 Running 状态，请耐心等待Pod准备就绪... 
redis-master-0   Pending

---------------------------------------------------------------------------------------------
+ count=1
+ '[' 1 -lt 30 ']'
+ sleep 30
++ kubectl get pods --namespace=model -o custom-columns=NAME:.metadata.name,STATUS:.status.phase
++ grep -v Running
++ grep -v Succeeded
++ grep -v NAME
+ non_running_pods=
+ '[' -n '' ']'
+ print_colored_message success '命名空间 '\''model'\'' 中的所有 Pods 都在运行中...'
+ '[' success == success ']'
+ echo -e '\e[32m---------------------------------------------------------------------------------------------
SUCCESS

命名空间 '\''model'\'' 中的所有 Pods 都在运行中...

---------------------------------------------------------------------------------------------\e[0m'
---------------------------------------------------------------------------------------------
SUCCESS

命名空间 'model' 中的所有 Pods 都在运行中...

---------------------------------------------------------------------------------------------
+ return 0
+ install_minio
+ helm_install minio charts/minio/ model charts/minio/values.yaml
+ local release_name=minio
+ local chart_path=charts/minio/
+ local namespace=model
+ local values_file=charts/minio/values.yaml
+ local max_retries=30
+ print_colored_message warning '正在安装 minio...'
+ '[' warning == success ']'
+ '[' warning == failure ']'
+ '[' warning == warning ']'
+ echo -e '\e[33m---------------------------------------------------------------------------------------------
WARNING

正在安装 minio...

---------------------------------------------------------------------------------------------\e[0m'
---------------------------------------------------------------------------------------------
WARNING

正在安装 minio...

---------------------------------------------------------------------------------------------
+ helm install minio charts/minio/ --namespace model -f charts/minio/values.yaml
NAME: minio
LAST DEPLOYED: Wed Sep 25 17:10:26 2024
NAMESPACE: model
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: minio
CHART VERSION: 13.0.0
APP VERSION: 2024.1.11

** Please be patient while the chart is being deployed **

MinIO&reg; can be accessed via port  on the following DNS name from within your cluster:

   minio.model.svc.cluster.local

To get your credentials run:

   export ROOT_USER=$(kubectl get secret --namespace model minio -o jsonpath="{.data.root-user}" | base64 -d)
   export ROOT_PASSWORD=$(kubectl get secret --namespace model minio -o jsonpath="{.data.root-password}" | base64 -d)

To connect to your MinIO&reg; server using a client:

- Run a MinIO&reg; Client pod and append the desired command (e.g. 'admin info'):

   kubectl run --namespace model minio-client \
     --rm --tty -i --restart='Never' \
     --env MINIO_SERVER_ROOT_USER=$ROOT_USER \
     --env MINIO_SERVER_ROOT_PASSWORD=$ROOT_PASSWORD \
     --env MINIO_SERVER_HOST=minio \
     --image harbor.xffuture.com/sealer-public/minio-client:2024.1.11-debian-11-r0 -- admin info minio

To access the MinIO&reg; web UI:

- Get the MinIO&reg; URL:

   You should be able to access your new MinIO&reg; web UI through

   http://minio-console.xffutrue.com/minio/
+ wait_for_pods_ready model 30
+ local namespace=model
+ local max_retries=30
+ local count=0
+ print_colored_message warning '正在检查命名空间 '\''model'\'' 中的 Pods 是否运行中...'
+ '[' warning == success ']'
+ '[' warning == failure ']'
+ '[' warning == warning ']'
+ echo -e '\e[33m---------------------------------------------------------------------------------------------
WARNING

正在检查命名空间 '\''model'\'' 中的 Pods 是否运行中...

---------------------------------------------------------------------------------------------\e[0m'
---------------------------------------------------------------------------------------------
WARNING

正在检查命名空间 'model' 中的 Pods 是否运行中...

---------------------------------------------------------------------------------------------
+ '[' 0 -lt 30 ']'
+ sleep 30
++ kubectl get pods --namespace=model -o custom-columns=NAME:.metadata.name,STATUS:.status.phase
++ grep -v Running
++ grep -v Succeeded
++ grep -v NAME
+ non_running_pods='minio-7bc4b55974-htrdt   Pending'
+ '[' -n 'minio-7bc4b55974-htrdt   Pending' ']'
+ print_colored_message warning 'Pods 未进入 Running 状态，请耐心等待Pod准备就绪... \nminio-7bc4b55974-htrdt   Pending'
+ '[' warning == success ']'
+ '[' warning == failure ']'
+ '[' warning == warning ']'
+ echo -e '\e[33m---------------------------------------------------------------------------------------------
WARNING

Pods 未进入 Running 状态，请耐心等待Pod准备就绪... \nminio-7bc4b55974-htrdt   Pending

---------------------------------------------------------------------------------------------\e[0m'
---------------------------------------------------------------------------------------------
WARNING

Pods 未进入 Running 状态，请耐心等待Pod准备就绪... 
minio-7bc4b55974-htrdt   Pending

---------------------------------------------------------------------------------------------
+ count=1
+ '[' 1 -lt 30 ']'
+ sleep 30
++ kubectl get pods --namespace=model -o custom-columns=NAME:.metadata.name,STATUS:.status.phase
++ grep -v Running
++ grep -v Succeeded
++ grep -v NAME
+ non_running_pods='minio-7bc4b55974-htrdt   Pending'
+ '[' -n 'minio-7bc4b55974-htrdt   Pending' ']'
+ print_colored_message warning 'Pods 未进入 Running 状态，请耐心等待Pod准备就绪... \nminio-7bc4b55974-htrdt   Pending'
+ '[' warning == success ']'
+ '[' warning == failure ']'
+ '[' warning == warning ']'
+ echo -e '\e[33m---------------------------------------------------------------------------------------------
WARNING

Pods 未进入 Running 状态，请耐心等待Pod准备就绪... \nminio-7bc4b55974-htrdt   Pending

---------------------------------------------------------------------------------------------\e[0m'
---------------------------------------------------------------------------------------------
WARNING

Pods 未进入 Running 状态，请耐心等待Pod准备就绪... 
minio-7bc4b55974-htrdt   Pending

---------------------------------------------------------------------------------------------
+ count=2
+ '[' 2 -lt 30 ']'
+ sleep 30
++ kubectl get pods --namespace=model -o custom-columns=NAME:.metadata.name,STATUS:.status.phase
++ grep -v Running
++ grep -v Succeeded
++ grep -v NAME
+ non_running_pods=
+ '[' -n '' ']'
+ print_colored_message success '命名空间 '\''model'\'' 中的所有 Pods 都在运行中...'
+ '[' success == success ']'
+ echo -e '\e[32m---------------------------------------------------------------------------------------------
SUCCESS

命名空间 '\''model'\'' 中的所有 Pods 都在运行中...

---------------------------------------------------------------------------------------------\e[0m'
---------------------------------------------------------------------------------------------
SUCCESS

命名空间 'model' 中的所有 Pods 都在运行中...

---------------------------------------------------------------------------------------------
+ return 0
+ install_kafka
+ helm_install kafka charts/kafka/ model charts/kafka/values.yaml
+ local release_name=kafka
+ local chart_path=charts/kafka/
+ local namespace=model
+ local values_file=charts/kafka/values.yaml
+ local max_retries=30
+ print_colored_message warning '正在安装 kafka...'
+ '[' warning == success ']'
+ '[' warning == failure ']'
+ '[' warning == warning ']'
+ echo -e '\e[33m---------------------------------------------------------------------------------------------
WARNING

正在安装 kafka...

---------------------------------------------------------------------------------------------\e[0m'
---------------------------------------------------------------------------------------------
WARNING

正在安装 kafka...

---------------------------------------------------------------------------------------------
+ helm install kafka charts/kafka/ --namespace model -f charts/kafka/values.yaml
NAME: kafka
LAST DEPLOYED: Wed Sep 25 17:11:57 2024
NAMESPACE: model
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: kafka
CHART VERSION: 23.0.5
APP VERSION: 3.5.0
---------------------------------------------------------------------------------------------
 WARNING

    By specifying "serviceType=LoadBalancer" and not configuring the authentication
    you have most likely exposed the Kafka service externally without any
    authentication mechanism.

    For security reasons, we strongly suggest that you switch to "ClusterIP" or
    "NodePort". As alternative, you can also configure the Kafka authentication.

---------------------------------------------------------------------------------------------

** Please be patient while the chart is being deployed **

Kafka can be accessed by consumers via port 9092 on the following DNS name from within your cluster:

    kafka.model.svc.cluster.local

Each Kafka broker can be accessed by producers via port 9092 on the following DNS name(s) from within your cluster:

    kafka-0.kafka-headless.model.svc.cluster.local:9092
    kafka-1.kafka-headless.model.svc.cluster.local:9092
    kafka-2.kafka-headless.model.svc.cluster.local:9092

To create a pod that you can use as a Kafka client run the following commands:

    kubectl run kafka-client --restart='Never' --image harbor.xffuture.com/sealer-public/kafka:3.5.0-debian-11-r21 --namespace model --command -- sleep infinity
    kubectl exec --tty -i kafka-client --namespace model -- bash

    PRODUCER:
        kafka-console-producer.sh \
            --broker-list kafka-0.kafka-headless.model.svc.cluster.local:9092,kafka-1.kafka-headless.model.svc.cluster.local:9092,kafka-2.kafka-headless.model.svc.cluster.local:9092 \
            --topic test

    CONSUMER:
        kafka-console-consumer.sh \
            --bootstrap-server kafka.model.svc.cluster.local:9092 \
            --topic test \
            --from-beginning

To connect to your Kafka server from outside the cluster, follow the instructions below:

    Kafka brokers domain: You can get the external node IP from the Kafka configuration file with the following commands (Check the EXTERNAL listener)

        1. Obtain the pod name:

        kubectl get pods --namespace model -l "app.kubernetes.io/name=kafka,app.kubernetes.io/instance=kafka,app.kubernetes.io/component=kafka"

        2. Obtain pod configuration:

        kubectl exec -it KAFKA_POD -- cat /opt/bitnami/kafka/config/server.properties | grep advertised.listeners

    Kafka brokers port: You will have a different node port for each Kafka broker. You can get the list of configured node ports using the command below:

        echo "$(kubectl get svc --namespace model -l "app.kubernetes.io/name=kafka,app.kubernetes.io/instance=kafka,app.kubernetes.io/component=kafka,pod" -o jsonpath='{.items[*].spec.ports[0].nodePort}' | tr ' ' '\n')"
+ wait_for_pods_ready model 30
+ local namespace=model
+ local max_retries=30
+ local count=0
+ print_colored_message warning '正在检查命名空间 '\''model'\'' 中的 Pods 是否运行中...'
+ '[' warning == success ']'
+ '[' warning == failure ']'
+ '[' warning == warning ']'
+ echo -e '\e[33m---------------------------------------------------------------------------------------------
WARNING

正在检查命名空间 '\''model'\'' 中的 Pods 是否运行中...

---------------------------------------------------------------------------------------------\e[0m'
---------------------------------------------------------------------------------------------
WARNING

正在检查命名空间 'model' 中的 Pods 是否运行中...

---------------------------------------------------------------------------------------------
+ '[' 0 -lt 30 ']'
+ sleep 30
++ kubectl get pods --namespace=model -o custom-columns=NAME:.metadata.name,STATUS:.status.phase
++ grep -v Running
++ grep -v Succeeded
++ grep -v NAME
+ non_running_pods='kafka-0                  Pending
kafka-1                  Pending
kafka-2                  Pending'
+ '[' -n 'kafka-0                  Pending
kafka-1                  Pending
kafka-2                  Pending' ']'
+ print_colored_message warning 'Pods 未进入 Running 状态，请耐心等待Pod准备就绪... \nkafka-0                  Pending
kafka-1                  Pending
kafka-2                  Pending'
+ '[' warning == success ']'
+ '[' warning == failure ']'
+ '[' warning == warning ']'
+ echo -e '\e[33m---------------------------------------------------------------------------------------------
WARNING

Pods 未进入 Running 状态，请耐心等待Pod准备就绪... \nkafka-0                  Pending
kafka-1                  Pending
kafka-2                  Pending

---------------------------------------------------------------------------------------------\e[0m'
---------------------------------------------------------------------------------------------
WARNING

Pods 未进入 Running 状态，请耐心等待Pod准备就绪... 
kafka-0                  Pending
kafka-1                  Pending
kafka-2                  Pending

---------------------------------------------------------------------------------------------
+ count=1
+ '[' 1 -lt 30 ']'
+ sleep 30
++ kubectl get pods --namespace=model -o custom-columns=NAME:.metadata.name,STATUS:.status.phase
++ grep -v Running
++ grep -v Succeeded
++ grep -v NAME
+ non_running_pods=
+ '[' -n '' ']'
+ print_colored_message success '命名空间 '\''model'\'' 中的所有 Pods 都在运行中...'
+ '[' success == success ']'
+ echo -e '\e[32m---------------------------------------------------------------------------------------------
SUCCESS

命名空间 '\''model'\'' 中的所有 Pods 都在运行中...

---------------------------------------------------------------------------------------------\e[0m'
---------------------------------------------------------------------------------------------
SUCCESS

命名空间 'model' 中的所有 Pods 都在运行中...

---------------------------------------------------------------------------------------------
+ return 0
+ install_logging
+ apply_k8s_manifest manifests/logging/ logging
+ local manifest_path=manifests/logging/
+ local namespace=logging
+ local max_retries=30
+ print_colored_message warning '正在应用 Kubernetes 配置文件: manifests/logging/...'
+ '[' warning == success ']'
+ '[' warning == failure ']'
+ '[' warning == warning ']'
+ echo -e '\e[33m---------------------------------------------------------------------------------------------
WARNING

正在应用 Kubernetes 配置文件: manifests/logging/...

---------------------------------------------------------------------------------------------\e[0m'
---------------------------------------------------------------------------------------------
WARNING

正在应用 Kubernetes 配置文件: manifests/logging/...

---------------------------------------------------------------------------------------------
+ kubectl apply -f manifests/logging/ -n logging
service/kibana created
deployment.apps/kibana created
daemonset.apps/log-pilot created
configmap/logstash-k8s-conf-stage created
deployment.apps/logstash-k8s created
configmap/fluent-bit-config created
serviceaccount/fluent-bit created
clusterrole.rbac.authorization.k8s.io/fluent-bit-read created
clusterrolebinding.rbac.authorization.k8s.io/fluent-bit-read created
daemonset.apps/fluent-bit created
+ wait_for_pods_ready logging 30
+ local namespace=logging
+ local max_retries=30
+ local count=0
+ print_colored_message warning '正在检查命名空间 '\''logging'\'' 中的 Pods 是否运行中...'
+ '[' warning == success ']'
+ '[' warning == failure ']'
+ '[' warning == warning ']'
+ echo -e '\e[33m---------------------------------------------------------------------------------------------
WARNING

正在检查命名空间 '\''logging'\'' 中的 Pods 是否运行中...

---------------------------------------------------------------------------------------------\e[0m'
---------------------------------------------------------------------------------------------
WARNING

正在检查命名空间 'logging' 中的 Pods 是否运行中...

---------------------------------------------------------------------------------------------
+ '[' 0 -lt 30 ']'
+ sleep 30
++ kubectl get pods --namespace=logging -o custom-columns=NAME:.metadata.name,STATUS:.status.phase
++ grep -v Running
++ grep -v Succeeded
++ grep -v NAME
+ non_running_pods='fluent-bit-q72q6                Pending
kibana-7449bbff7d-splng         Pending'
+ '[' -n 'fluent-bit-q72q6                Pending
kibana-7449bbff7d-splng         Pending' ']'
+ print_colored_message warning 'Pods 未进入 Running 状态，请耐心等待Pod准备就绪... \nfluent-bit-q72q6                Pending
kibana-7449bbff7d-splng         Pending'
+ '[' warning == success ']'
+ '[' warning == failure ']'
+ '[' warning == warning ']'
+ echo -e '\e[33m---------------------------------------------------------------------------------------------
WARNING

Pods 未进入 Running 状态，请耐心等待Pod准备就绪... \nfluent-bit-q72q6                Pending
kibana-7449bbff7d-splng         Pending

---------------------------------------------------------------------------------------------\e[0m'
---------------------------------------------------------------------------------------------
WARNING

Pods 未进入 Running 状态，请耐心等待Pod准备就绪... 
fluent-bit-q72q6                Pending
kibana-7449bbff7d-splng         Pending

---------------------------------------------------------------------------------------------
+ count=1
+ '[' 1 -lt 30 ']'
+ sleep 30
++ kubectl get pods --namespace=logging -o custom-columns=NAME:.metadata.name,STATUS:.status.phase
++ grep -v Running
++ grep -v Succeeded
++ grep -v NAME
+ non_running_pods=
+ '[' -n '' ']'
+ print_colored_message success '命名空间 '\''logging'\'' 中的所有 Pods 都在运行中...'
+ '[' success == success ']'
+ echo -e '\e[32m---------------------------------------------------------------------------------------------
SUCCESS

命名空间 '\''logging'\'' 中的所有 Pods 都在运行中...

---------------------------------------------------------------------------------------------\e[0m'
---------------------------------------------------------------------------------------------
SUCCESS

命名空间 'logging' 中的所有 Pods 都在运行中...

---------------------------------------------------------------------------------------------
+ return 0
+ install_harbor
+ helm_install harbor charts/harbor/ harbor charts/harbor/values.yaml
+ local release_name=harbor
+ local chart_path=charts/harbor/
+ local namespace=harbor
+ local values_file=charts/harbor/values.yaml
+ local max_retries=30
+ print_colored_message warning '正在安装 harbor...'
+ '[' warning == success ']'
+ '[' warning == failure ']'
+ '[' warning == warning ']'
+ echo -e '\e[33m---------------------------------------------------------------------------------------------
WARNING

正在安装 harbor...

---------------------------------------------------------------------------------------------\e[0m'
---------------------------------------------------------------------------------------------
WARNING

正在安装 harbor...

---------------------------------------------------------------------------------------------
+ helm install harbor charts/harbor/ --namespace harbor -f charts/harbor/values.yaml
NAME: harbor
LAST DEPLOYED: Wed Sep 25 17:13:59 2024
NAMESPACE: harbor
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Please wait for several minutes for Harbor deployment to complete.
Then you should be able to visit the Harbor portal at http://aigc-harbor.xffuture.com
For more details, please visit https://github.com/goharbor/harbor
+ wait_for_pods_ready harbor 30
+ local namespace=harbor
+ local max_retries=30
+ local count=0
+ print_colored_message warning '正在检查命名空间 '\''harbor'\'' 中的 Pods 是否运行中...'
+ '[' warning == success ']'
+ '[' warning == failure ']'
+ '[' warning == warning ']'
+ echo -e '\e[33m---------------------------------------------------------------------------------------------
WARNING

正在检查命名空间 '\''harbor'\'' 中的 Pods 是否运行中...

---------------------------------------------------------------------------------------------\e[0m'
---------------------------------------------------------------------------------------------
WARNING

正在检查命名空间 'harbor' 中的 Pods 是否运行中...

---------------------------------------------------------------------------------------------
+ '[' 0 -lt 30 ']'
+ sleep 30
Error: signal: killed
看起来也没报错

**Comment by bxy4543** [comment]
你本地直接执行命令，紧跟着执行`echo $?` 看下执行状态就知道为啥了
