### ISSUE TITLE
BUG: Problem adding custom domain name to sealos.io

### ISSUE THREAD

**Issue by alltobebetter** [labring/sealos#5155]
### Sealos Version

None

### How to reproduce the bug?

I tried to add a custom domain name to my project today, but I found that it could not be added successfully, even though I had parsed it 6 hours later, as shown in the picture:

![pic](https://github.com/user-attachments/assets/f32289f8-6272-49b6-9342-684d166e22a2)

I have also seen many users reporting this problem. Is it possible to try without verifying the CNAME? My parsing is on CloudFlare.

![image](https://github.com/user-attachments/assets/25e9ebee-f426-4d6c-a64c-9efcf6e8e98d)

### What is the expected behavior?

i hope to improve

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by fanqichao** [comment]
Hi I also met the same problem.
![image](https://github.com/user-attachments/assets/09045f89-6432-47d9-b5bc-a6b3498f0419)
