### ISSUE TITLE
install Cilium version 1.16.0  error

### ISSUE THREAD

**Issue by dxygit1** [labring/sealos#5184]
### Sealos Version

5.0.1

### How to reproduce the bug?

sealos run registry.cn-shanghai.aliyuncs.com/labring/kubernetes:v1.28.9 registry.cn-shanghai.aliyuncs.com/labring/helm:v3.9.4 registry.cn-shanghai.aliyuncs.com/labring/cilium:v1.16.1     

cilium  1.16.0 or 1.16.1  

```
ℹ️  Using Cilium version 1.16.0
 Auto-detected cluster name: kubernetes
 Auto-detected kube-proxy has been installed

Error: Unable to install Cilium: execution error at (cilium/templates/cilium-configmap.yaml:71:5): kubeProxyReplacement must be explicitly set to a valid value (true or false) to continue.

```

### What is the expected behavior?

Where do I need to specify kubeProxyReplacement

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by dxygit1** [comment]
It is normal for me to use 1.15.8, but there will be problems above 1.16.0

**Comment by SpringHgui** [comment]
+1 v1.16.1

**Comment by dxygit1** [comment]
v1.16.1 has the same issue.
 sealos run registry.cn-shanghai.aliyuncs.com/labring/kubernetes:v1.28.9 registry.cn-shanghai.aliyuncs.com/labring/helm:v3.9.4 registry.cn-shanghai.aliyuncs.com/labring/cilium:v1.16.1   
```bash
 2024-11-26T14:00:00 info Executing pipeline RunGuest in CreateProcessor.
ℹ️  Using Cilium version 1.16.1
 Auto-detected cluster name: kubernetes
 Auto-detected kube-proxy has been installed

Error: Unable to install Cilium: execution error at (cilium/templates/cilium-configmap.yaml:71:5): kubeProxyReplacement must be explicitly set to a valid value (true or false) to continue.
Error: exit status 1
```

**Comment by pokitpeng** [comment]
How to resolved this issue?
