### ISSUE TITLE
RedHat 8.3 merged nf_conntrack_ipv4 in nf_conntrack but still advertise 4.18

### ISSUE THREAD

**Issue by oldthreefeng** [labring/sealos#554]
ipvs 模块load更改. 

这个修改pr: https://github.com/kubernetes/kubernetes/pull/97070
修复后, 应该不需要检查. 
```
if  modprobe_nf_conntrack_ipv4  ; then 
    do nf_conntrack_ipv4
else 
    do nf_conntrack
fi
```

**Comment by oldthreefeng** [comment]
目前建议不要在 redhat/centos 8.3+ 上安装; 
硬要装的, 建议升级内核.

**Comment by omaidb** [comment]
我在rocky8上安装的,内核是5.16.
但是出现了安装3master,只成功了一个master的问题...

**Comment by omaidb** [comment]
> 目前建议不要在 redhat/centos 8.3+ 上安装; 
> 
> 硬要装的, 建议升级内核. 

内核升级到多少吧

**Comment by fanux** [comment]
可以试下sealos 4.0 如有问题 reopen此issue
