### ISSUE TITLE
用户需求

### ISSUE THREAD

**Issue by cuisongliu** [labring/sealos#751]
这里主要收集一些外部用户的需求

**Comment by cuisongliu** [comment]
需求：
k8s版本要求1.22.3
需要支持IPV4/IPV6双协议栈

**Comment by zq940609** [comment]
需求:
k8s版本要求1.18.8
需要支持Alibaba Cloud Linux (Aliyun Linux) 2.1903 LTS (Hunting Beagle) 系统

**Comment by cuisongliu** [comment]
国产化的要求增多，实际生产环境中，经常遇到x86服务器和arm服务器共存在一个集群中，目前sealos还不支持，希望增加该功能。  https://github.com/fanux/sealos/issues/758

**Comment by newIDforLOL** [comment]
1、至少README.md中默认密码不要用123456，看起来就不稳...
2、建议（或至少提供参数用于）启用firewalld进行安全控制。

**Comment by cuisongliu** [comment]
> 1、至少README.md中默认密码不要用123456，看起来就不稳...
> 2、建议（或至少提供参数用于）启用firewalld进行安全控制。

1. 那不是默认密码，是你主机的服务器密码，根据实际情况修改。

**Comment by guowei-gong** [comment]
要求不要这么方便，导致leader认为我工作不包含

**Comment by jdxia** [comment]
安装完成后, 显示所有配置文件的路径.
containerd容器默认把aliyun的加速镜像添加进去

**Comment by jdxia** [comment]
安装前做一些检查和警告, 比如ubuntu的
# cat /etc/resolv.conf 
里面的是 127.0.0.53的话, 给用户提示, 这个dns会导致pod里面无法ping baidu
并且给出, 对应修复的脚本

**Comment by cuisongliu** [comment]
> 并且给出, 对应修复的脚本

sealos4.0 自动修复Ubuntu的dns的问题了

**Comment by Designxiaozai** [comment]
需求:支持sudo操作 或者非root用户操作

**Comment by 13567436138** [comment]
支持双栈了么
