### ISSUE TITLE
加master节点失败，报panic：runtime error：index of range [0] with length 0

### ISSUE THREAD

**Issue by cyl-007** [labring/sealos#798]
![05fbca502e18864efcc091cb4a74564](https://user-images.githubusercontent.com/74633249/147672516-ccc58a05-049d-4892-a342-11c01f759f5e.png)

**Comment by cyl-007** [comment]
初步定位原因：config.yaml配置丢失master和node节点信息导致
临时解决方案：sealos init gen的输入比对补充配置

**Comment by cuisongliu** [comment]
join需要优化，token逻辑。获取返回值容易出现panic，以及校验

**Comment by Hanvans** [comment]
get
