### ISSUE TITLE
K8S init 初始化报错，请问什么问题？

### ISSUE THREAD

**Issue by gitlihua** [labring/sealos#819]
![image](https://user-images.githubusercontent.com/23493734/148166105-809a8a7f-f0b2-4fc8-b650-da4c1cb843c9.png)

**Comment by cuisongliu** [comment]
本机装了docker？

**Comment by gitlihua** [comment]
没有安装docker  是按照安装文档来安装的

**Comment by oldthreefeng** [comment]
1. 一般是默认安装的docker是禁用了contianerd 的cri功能，导致的 。
2. 系统的磁盘文件不支持overlay2。 

https://github.com/fanux/sealos/issues/582 看一下这个

**Comment by gitlihua** [comment]
我将K8S包换成v1.23.1  报如下错误

![image](https://user-images.githubusercontent.com/23493734/148182473-65d22195-edbc-460d-a903-fe5d04c1c704.png)

**Comment by oldthreefeng** [comment]
这个问题 一般有两种可能： 
1. sealos版本不是最新版
2. 下载的tar包损坏
