### ISSUE TITLE
缺陷: k8s v1.22.0 初始化安装失败

### ISSUE THREAD

**Issue by xel237268** [labring/sealos#837]
在阿里云centeros7.6执行如下命令：
sealos init --passwd 'xxxxxx' \
	--master xxx.xxx.x.x \
	--node yyy.yyy.y.y \
	--pkg-url /root/kube1.22.0.tar.gz ### \
	--version v1.22.0
现象如下：
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

	Unfortunately, an error has occurred:
		timed out waiting for the condition

	This error is likely caused by:
		- The kubelet is not running
		- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

	If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
		- 'systemctl status kubelet'
		- 'journalctl -xeu kubelet'

	Additionally, a control plane component may have crashed or exited when started by the container runtime.
	To troubleshoot, list all containers using your preferred container runtimes CLI.

	Here is one example how you may list all Kubernetes containers running in cri-o/containerd using crictl:
		- 'crictl --runtime-endpoint /run/containerd/containerd.sock ps -a | grep kube | grep -v pause'
		Once you have found the failing container, you can inspect its logs with:
		- 'crictl --runtime-endpoint /run/containerd/containerd.sock logs CONTAINERID'

error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher

22:38:18 [EROR] [ssh.go:28] [ssh][xxx.xxx.x.x]Error exec command failed: Process exited with status 1
22:38:18 [EROR] [init.go:173] [xxx.xxx.x.x] install kubernetes failed. please clean and uninstall.

重新执行sealos clean --all再次执行上述命令还是不行
机器docker全部卸载干净

**Comment by cuisongliu** [comment]
1.22 是containerd

**Comment by xel237268** [comment]
> 1.22 是containerd

我知道 containerd是起来的，就是最终安装失败的，和网络有关系吗

**Comment by xel237268** [comment]
> 1.22 是containerd

之前我安装过1.20版本 后来clean all集群后，安装1.22就不行了。

**Comment by cuisongliu** [comment]
估计是没清理干净。

**Comment by cuisongliu** [comment]
看看报错日志是什么，把日志级别调高一些

**Comment by xel237268** [comment]
> 看看报错日志是什么，把日志级别调高一些

/etc/kubernetes/manifests/ 这里面的yml配置文件的镜像都是k8s.gcr.io这个开头的 会不会是没有翻墙拉取镜像失败

**Comment by cuisongliu** [comment]
> > 看看报错日志是什么，把日志级别调高一些
> 
> /etc/kubernetes/manifests/ 这里面的yml配置文件的镜像都是k8s.gcr.io这个开头的 会不会是没有翻墙拉取镜像失败

不会的，这个离线部署的。执行的时候 -v 9 你看看报错么
