### ISSUE TITLE
缺陷: 集群部署后coredns和calico-kube-controllers不能正常运行

### ISSUE THREAD

**Issue by DearEirs** [labring/sealos#840]
**描述这个缺陷**
sealos init 后发现coredns 处于Notready状态， 并且calico-kube-controllers在不断重启。 尝试过通过kubectl delete po的方式去重启coredns，calico-kube-controllers甚至是直接重启虚拟机， 但是都没有恢复，具体的影响是k8s集群内部容器网络不通，
容器状态如图
![image](https://user-images.githubusercontent.com/19787897/150485854-c05103e2-0773-4e90-a439-626362e53e29.png)
coredns日志如图
![image](https://user-images.githubusercontent.com/19787897/150485905-b9864d43-5ca9-42a4-8404-f6bcc11a2c7a.png)
calico-kube-controllers日志如图
![image](https://user-images.githubusercontent.com/19787897/150485943-54ceed87-db22-48a7-8b09-ee1ebcfb1bc4.png)

**运行环境**
- Kubernetes版本 : kube1.22.0.tar.gz
- sealos版本: v3.3.9-rc.10
- 操作系统:  centos7
- 运行模式:  虚拟机 ( kvm, 内存 48gb, cpu 16核 ,存储 500gb ) 
- 集群规模:   3master 0node

**Comment by cuisongliu** [comment]
是openstack上的么

**Comment by oldthreefeng** [comment]
有 calico-kube-controllers 的日志么。

**Comment by DearEirs** [comment]
> 是openstack上的么

不是， 是物理机器上起了3台kvm的虚拟机

**Comment by DearEirs** [comment]
> 有 calico-kube-controllers 的日志么。

第三个图就是calico-kube-controllers的日志

**Comment by zhangguanzhang** [comment]
看日志就是pod无法访问 kubernetes这个svc，看看转发是不是被关闭了

**Comment by Hanvans** [comment]
pod /etc/reslove 里边有coredns 地址没

**Comment by wayne666** [comment]
这个问题修复了吗？我也碰到了，机器是公有云的虚机

**Comment by omaidb** [comment]
> 看日志就是pod无法访问kubernetes这个svc，看看转向不是被关闭了

大佬,怎么看啊

**Comment by zhangguanzhang** [comment]
> > 看日志就是pod无法访问kubernetes这个svc，看看转向不是被关闭了
> 
> 大佬,怎么看啊

```
docker info
iptables -S
```

**Comment by omaidb** [comment]
> > > 看日志就是pod无法访问kubernetes这个svc，看看转向不是被关闭了
> 
> > 
> 
> > 大佬,怎么看啊
> 
> 
> 
> ```
> 
> docker info
> 
> iptables -S
> 
> ```

好的

**Comment by fanux** [comment]
使用sealos 4.0如果复现 请重开此issue.
