### ISSUE TITLE
需求: containerd 升级到 1.5.10

### ISSUE THREAD

**Issue by sheaven79** [labring/sealos#901]
**哪个命令或者组件**
sealos init

**详细描述你的需求/任务**
现在安装包内默认的containerd 1.5.5，在实际使用过程中遇到了，更新镜像版本后老的 pods 出现一直卡在 Terminating 情况（不手工强制清理会一直存在）

**是否有解决方案，如果有请详述**
通过升级 containerd 到 1.5.10 能够解决（已实测）
1. 升级最新的 libseccomp-2.5.3
2. 升级containerd 1.5.10

**Comment by fanux** [comment]
OK 后续版本中会升级containerd
