### ISSUE TITLE
sealos 4.0 

### ISSUE THREAD

**Issue by fanux** [labring/sealos#913]
1. join,delete,run(增量)
2. shim（稳定性）
3. buildah push imgaes
4. buildah sdk集成
4. registry (registry sdk集成)
5. helm
5. chroot

**Comment by cuisongliu** [comment]
shim检测  done

**Comment by cuisongliu** [comment]
多镜像 done

**Comment by cuisongliu** [comment]
1. join,delete,run(增量)
2. shim（稳定性）
3. buildah push imgaes
4. buildah sdk集成
4. registry (registry sdk集成)
5. helm
5. chroot

**Comment by cuisongliu** [comment]
join,delete,run done
