### ISSUE TITLE
提出几个优化点，烦请考虑一下

### ISSUE THREAD

**Issue by eadou** [labring/sealos#915]
1、在线集群如何滚动升级，不能一次全部升级所有节点，这样的话生产业务会造成一次重启，若是升级出意外所有的业务都会暂停；
2、使用sealos升级时候是否会修改核心组件的参数配置，还是会继承老版本已经修改的参数配置；
3、目前containerd 1.6版本能否纳入到集群升级中，或者纳入到集群版本安装包中；
4、从1.19版本升级到1.20版本过程中，由于弃用docker，使用containerd作为容器运行时，这个目前升级似乎不支持。

**Comment by cuisongliu** [comment]
1. containerd 1.6  有什么优化的？目前最新的1.5.8 有问题么？
2. sealos 4.0会重优化这些内容
