### ISSUE TITLE
从1.19升到1.20，或者手动升级后的问题

### ISSUE THREAD

**Issue by thesky8163** [labring/sealos#927]
sealos一键安装的k8s集群
1.从1.19升级1.20提示要使用containerd
2.手动从docker切换到containerd
3.按k8s官方手动升级k8s 1.19到 1.23后，无法使用sealos加入节点，报错信息：sealos还是认为k8s是1.19版本，还是认为k8s使用的是docker

**Comment by fanux** [comment]
这个版本跨度确实有点大了，看一下root下面的sealos配置
