### ISSUE TITLE
缺陷:使用sealos join --master ip地址无法加入现有master集群

### ISSUE THREAD

**Issue by PJzer0** [labring/sealos#930]
**哪个命令或者组件**
eg. sealos join --master 192.168.123.2

**描述这个缺陷**
无法加入新的master节点

**重现步骤（如果有需要可以附加图片）**
1. 5台机的k8s集群：sealos init --passwd 'root' --master 192.168.123.2  --master 192.168.123.3  --master 192.168.123.4 --node 192.168.123.5 --node 192.168.123.6 --pkg-url /root/kube1.22.0.tar.gz --version v1.22.0（Redhat8.5干净环境此步骤正常）
2.在任意一台master节点部署docker，该master重启后，此机异常，一直处于notready状态
3.删除docker后依旧异常，重启相关k8s服务依旧失败
4.通过删除该异常master节点，然后通过sealos join --master 192.168.123.xxx重新加入，无法成功加入到现有master中（--master无法加入成功，测试--node正常）

**Comment by fanux** [comment]
2. not ready的时候提供一下kubelet日志
4. 是否有加入不成功的日志？

**Comment by cuisongliu** [comment]
长时间未回复，先关闭这个issue了。有问题可以重新打开这个issue追踪。
