### ISSUE TITLE
缺陷:  sealos clean --all 后再执行 sealos init 节点一直无法ready

### ISSUE THREAD

**Issue by trey03** [labring/sealos#938]
sealos 版本： 3.3.9-rc.11
kubernetes版本： 1.20.15

在第一次执行 sealos init 后，k8s集群的所有节点都能很就ready状态，这时如果sealos clean --all 后再执行同样sealos init 节点就会一直无法ready，尝试过多次都是一样的，个人排查验证的情况来看跟sealos clean --all后 节点上的containerd服务没有被停掉。

我试着clean --all后把所有的节点都手动执行 systemctl stop containerd 后再sealos init 发现节点可以ready。

**Comment by cuisongliu** [comment]
clean 不删 containerd,后面修复一下。
