### ISSUE TITLE
sealos安装时cni选cilium，想咨询几个问题？

### ISSUE THREAD

**Issue by fsckzy** [labring/sealos#942]
sealos 安装k8s 1.20最新的包，想用cilium。
我们的系统是centos7，内核升级到lt5.4
1.请问下是否推荐在生产环境使用cilium？
2.cni选了cilium，还会安装kube-proxy吗？

**Comment by fanux** [comment]
目前kube-proxy是默认带上了，cilium我们目前实践不是太多，仅仅是跑过
