### ISSUE TITLE
centos 7.9上安装使用默认 calico 插件集群起不来

### ISSUE THREAD

**Issue by yiqi19940531** [labring/sealos#951]
centos 7.9上安装使用默认 calico 插件集群起不来

<img width="1440" alt="截屏2022-04-26 11 11 53" src="https://user-images.githubusercontent.com/58947258/165218306-1466c4ce-cd19-4539-a859-afcaacce9007.png">
<img width="1439" alt="截屏2022-04-26 11 09 47" src="https://user-images.githubusercontent.com/58947258/165218337-8ce2e368-460e-4a20-b6c9-02d8fd0a5f85.png">

我查看了 常见问题 https://www.sealyun.com/instructions/7
但是没找到直接相关的错误

**Comment by yiqi19940531** [comment]
<img width="1440" alt="截屏2022-04-26 13 31 56" src="https://user-images.githubusercontent.com/58947258/165228738-a5cb8c72-7418-425a-a353-e27d875ad748.png">
<img width="1440" alt="截屏2022-04-26 13 32 06" src="https://user-images.githubusercontent.com/58947258/165228756-48bb9912-3d2e-419f-8e97-63e9571c5366.png">
<img width="1440" alt="截屏2022-04-26 13 32 50" src="https://user-images.githubusercontent.com/58947258/165228765-0d525df2-f135-4581-a3bd-4dde96e8921c.png">
我还尝试了其他CNI，比如flannel和cilium，目前的状态是CNI的pod起来了，但是corednspod起不来（提示：etwork is not ready: container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized）
但如果查看cilium的pod日志看不到任何error

**Comment by zhangguanzhang** [comment]
没有cni的配置文件在 `/etc/cni/net.d/` 目录，所以报错 cni 配置没初始化

**Comment by yiqi19940531** [comment]
<img width="1439" alt="截屏2022-04-26 18 02 40" src="https://user-images.githubusercontent.com/58947258/165276010-dc52ac14-d5be-4803-a8a5-87769ead2e7f.png">
这块确实也是我不太熟悉的地方，但是单看这个路径下的文件是存在的，现在的问题是cilium的pod都起来了，但是coredns的pod起不来。cilium的pod看log也没有看到error。

**Comment by yiqi19940531** [comment]
但在同样的网络环境下面，我把操作一同换成Ubuntu就可以了！

**Comment by zhangguanzhang** [comment]
cilium 依赖 ebpf，也就是需要挂载 debugfs 相关的，我不懂 cilium ，无法给与帮助，flannel的话我可以看看

**Comment by zhangguanzhang** [comment]
cilium 依赖 ebpf ，需要挂载 debufs，如果是flannel的话我可以帮你看看，cilium的话就无能为力了

**Comment by cuisongliu** [comment]
内核多少 我看calico的报错是ipset版本问题。

**Comment by yandechao** [comment]
看看dns配置了没（/etc/resolv.conf文件是否有配置nameserver），之前coredns遇到的问题是dns没配置导致起不来。

**Comment by zhfish** [comment]
<img width="659" alt="image" src="https://user-images.githubusercontent.com/287033/167902650-246a29ce-06b3-445b-9eb3-1f7ed8497643.png">
<img width="698" alt="image" src="https://user-images.githubusercontent.com/287033/167902899-98e7072d-3d67-437f-8b57-b0590e1ce76c.png">

我也是这个问题，默认装好，calico 起不来，cilium 没问题
centos7.9，内核5.16，kube1.22.8

**Comment by hincky** [comment]
> <img alt="image" width="659" src="https://user-images.githubusercontent.com/287033/167902650-246a29ce-06b3-445b-9eb3-1f7ed8497643.png">
> 
> <img alt="image" width="698" src="https://user-images.githubusercontent.com/287033/167902899-98e7072d-3d67-437f-8b57-b0590e1ce76c.png">
> 
> 我也是这个问题，默认装好，calico 起不来，cilium 没问题 centos7.9，内核5.16，kube1.22.8

检查一下你的安全组有没有开179端口，calico的BGP是基于179通信的

**Comment by zhfish** [comment]
> > <img alt="image" width="659" src="https://user-images.githubusercontent.com/287033/167902650-246a29ce-06b3-445b-9eb3-1f7ed8497643.png">
> 
> > 
> 
> > <img alt="image" width="698" src="https://user-images.githubusercontent.com/287033/167902899-98e7072d-3d67-437f-8b57-b0590e1ce76c.png">
> 
> > 
> 
> > 我也是这个问题，默认装好，calico 起不来，cilium 没问题 centos7.9，内核5.16，kube1.22.8
> 
> 
> 
> 检查一下你的安全组有没有开179端口，calico的BGP是基于179通信的

内网不开防火墙，我查过一次问题，我记得是ipset版本不对付，我换了cilium用
