### ISSUE TITLE
etcd backup and restore

### ISSUE THREAD

**Issue by 651764643** [labring/sealos#955]
操作步骤:
   1. 原集群中有一台服务器关机后导致一台master丢失，通过sealos etcd restore命令恢复集群，然后再添加新的工作节点出现如下问题

19:07:51 [INFO] [ssh.go:65] [172.16.10.17:22] [preflight] Running pre-flight checks
19:07:51 [INFO] [ssh.go:65] [172.16.10.18:22] [preflight] Running pre-flight checks
19:07:51 [INFO] [ssh.go:65] [172.16.10.17:22] 	[WARNING FileExisting-socat]: socat not found in system path
19:07:51 [INFO] [ssh.go:65] [172.16.10.18:22] 	[WARNING FileExisting-socat]: socat not found in system path
19:07:52 [INFO] [ssh.go:65] [172.16.10.18:22] error execution phase preflight: couldn't validate the identity of the API Server: cluster CA found in cluster-info ConfigMap is invalid: none of the public keys "sha256:20d5d52c31c52a29edb3865a31c31f44effc8c0688f8ec0edbeaf0d3e05a9321" are pinned
19:07:52 [INFO] [ssh.go:65] [172.16.10.18:22] To see the stack trace of this error execute with --v=5 or higher
19:07:52 [INFO] [ssh.go:27] [ssh][172.16.10.18:22] mkdir -p /etc/kubernetes/manifests
19:07:52 [INFO] [ssh.go:65] [172.16.10.17:22] error execution phase preflight: couldn't validate the identity of the API Server: cluster CA found in cluster-info ConfigMap is invalid: none of the public keys "sha256:20d5d52c31c52a29edb3865a31c31f44effc8c0688f8ec0edbeaf0d3e05a9321" are pinned
19:07:52 [INFO] [ssh.go:65] [172.16.10.17:22] To see the stack trace of this error execute with --v=5 or higher

**运行环境**

searlos版本：

Version: 3.3.9-rc.11
Last Commit: 49e79d2
Build Date: 2022-02-17T06:17:34Z

Kubernetes版本 
1.21.11

**Comment by fanux** [comment]
得backup才能restore

**Comment by 651764643** [comment]
是先备份了的  不备份就无法恢复啊
