### ISSUE TITLE
sealos4.0 - 需求单

### ISSUE THREAD

**Issue by cuisongliu** [labring/sealos#963]
1. 支持修改主机名

**Comment by cuisongliu** [comment]
save 出来没有tag

**Comment by cuisongliu** [comment]
1. add的时候不需要拷贝非k8s的镜像
2. 默认run 不需要拷贝到各个节点 
3.不需要做nochage 操作 run (这个需要思考一下)。

**Comment by sheaven79** [comment]
支持openEuler、Alibaba Cloud Linux、TencentOS Server等国产系统

**Comment by cuisongliu** [comment]
1. buildah sdk集成
2. registry (registry sdk集成)
3. chroot

**Comment by cuisongliu** [comment]
> 支持openEuler、Alibaba Cloud Linux、TencentOS Server等国产系统

内核基本一致应该默认是支持的，但是没有测试而已。

**Comment by fanux** [comment]
registry.cn-hongkong.aliyuncs.com/sealyun/ 太长，给个default domian和namespace,这样可以
 
sealos run oci-kubernetes:v1.24.0 这样简单干净

**Comment by eadou** [comment]
1、建议支持集群升级跨度从1.19等低版本升级到1.20版本及以上，这会涉及container runtime的更改
2、升级时候，可以可控升级节点，比如一台一台的升级而非一次升级所有节点。

**Comment by willzhang** [comment]
support ubuntu 22.04 LTS
