### ISSUE TITLE
问题: 早期的 config.yaml 文件丢失问题，能否从现有的 k8s 集群里生成 sealos config.yaml ？

### ISSUE THREAD

**Issue by soulmz** [labring/sealos#966]
**那个命令或者组件**
eg. sealos init , sealos install , kubernetes cni, docker  and so on 

sealos join 

**描述你的问题**

1. sealos config 怎么来生成？ 
2. 是否可以通过保存现有 k8s 集群信息来重新生成 sealos 的 config 文件呢？(都是用 sealos 搭建的)
3. 现在需要增加部分 worker 或 master 节点，不确定能否通过 `sealos --join`  来添加节点。

**你看到的一些参考资料**
eg. 文档的引用xxxx

**Comment by cuisongliu** [comment]
https://github.com/labring/sealos/blob/main/docs/3.0/plan/recovery_sealos.md  可以参考一下这个。

**Comment by soulmz** [comment]
> https://github.com/labring/sealos/blob/main/docs/3.0/plan/recovery_sealos.md 可以参考一下这个。

假如，上述 config 文件都不确定，是否可以通过 sealos Build 的 kubeadm 进行 join ？ 当然初始化都是通过 离线包脚本执行的。

另外提个小建议， 可以在k8s 集群里 放置一份 configmap 。每次集群升级或调整配置，通过 kube-system 空间 configmap ，读取。便于还原和丢失 机器上的 ~/.sealos/config.yaml 配置。
