### ISSUE TITLE
指定仓库calico镜像kube-controllers未修改

### ISSUE THREAD

**Issue by cc20110101** [labring/sealos#982]
**哪个命令或者组件**
sealos init --repo ...

**描述这个缺陷**
简短描述这个缺陷内容.
--repo指定仓库后calico网络插件镜像docker.io/calico/kube-controllers:v3.19.1未替换，其他镜像替换

![image](https://user-images.githubusercontent.com/12064991/167521760-b74ac8ac-7b9a-4436-9cdd-4ece445aa864.png)

**运行环境**

- Kubernetes版本 : kube1.23.5tar.gz
- sealos版本: 3.3.9-rc.11
- 操作系统:  eg. centos7

**Comment by cuisongliu** [comment]
这个只替换kubeadm 的配置，kubeadm 不负责calico 的镜像

**Comment by cc20110101** [comment]
![image](https://user-images.githubusercontent.com/12064991/168208430-2d6f3a6c-44eb-4e2f-a8cf-ede6107ee7ef.png)
我的意思是为啥calico多个镜像都根据--repo替换了镜像仓库，但是还有一个不替换；还有就是kube包里面conf下面的calico配置文件不用为啥不删除，看是用到代码里面的，但是镜像仓库处理又不一样，导致也有从仓库拉取也有从本地的很乱

**Comment by cuisongliu** [comment]
3.0的代码的确是很乱，设计也不是很合理，如果用k8s推荐用4.0  https://github.com/labring/sealos/releases/tag/v4.0.0-alpha.11
现在3.0的代码基本上都在4.0做了调整

**Comment by cc20110101** [comment]
好的
