### ISSUE TITLE
sealos(3.3.9-rc.11)创建一个master，一个node时，node上kubelet启动不起来

### ISSUE THREAD

**Issue by ttt307307** [labring/sealos#985]
sealos 版本: 3.3.9-rc.11
kubelet版本：kube1.22.0

## 创建命令：
`
 sealos init --passwd 'xxxxxx' \
	--master 172.17.16.3  \
	--node 172.17.16.11 \
	--pkg-url /root/kube1.22.0.tar.gz \
	--version v1.22.0 \
	--podcidr 172.16.0.0/24
`

## node上日志：
`
May 10 10:48:03 sh2q-16-11 kubelet[20853]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 10 10:48:03 sh2q-16-11 kubelet[20853]: Flag --runtime-request-timeout has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 10 10:48:03 sh2q-16-11 kubelet[20853]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 10 10:48:03 sh2q-16-11 kubelet[20853]: Flag --runtime-request-timeout has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 10 10:48:03 sh2q-16-11 kubelet[20853]: E0510 10:48:03.511384   20853 server.go:271] "Failed to construct kubelet dependencies" err="unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory"
May 10 10:48:03 sh2q-16-11 systemd[1]: kubelet.service: main process exited, code=exited, status=1/FAILURE
May 10 10:48:03 sh2q-16-11 systemd[1]: Unit kubelet.service entered failed state.
May 10 10:48:03 sh2q-16-11 systemd[1]: kubelet.service failed.
May 10 10:48:11 sh2q-16-11 systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
`

**Comment by zhangguanzhang** [comment]
```
open /etc/kubernetes/pki/ca.crt: no such file or directory
```

**Comment by ttt307307** [comment]
> ```
> open /etc/kubernetes/pki/ca.crt: no such file or directory
> ```

需要手动复制过去？master节点有，node节点没有。sealos没有自动复制过去。
我手动复制到node节点了，再join node的话，会自动删除这个目录/etc/kubernetes/pki

**Comment by zhangguanzhang** [comment]
@cuisongliu

**Comment by fanux** [comment]
建议使用4.0版本
